### PR TITLE
hotfix 2 exceptions

### LINKED ISSUE #1907: Crash at the entrance to the world.
minecolonies-universal-1.12.2-0.8.6215.jar

[10:16:50] [main/INFO]: Setting user: RedBilly
[10:16:54] [main/WARN]: Skipping bad option: lastServer:
[10:16:54] [main/INFO]: LWJGL Version: 2.9.4
[10:17:05] [main/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:mercurius_updater, FMLFileResourcePack:Version Checker, FMLFileResourcePack:Wood Converter, FMLFileResourcePack:Antique Atlas, FMLFileResourcePack:Antique Atlas Overlay, FMLFileResourcePack:Aroma1997Core, FMLFileResourcePack:AromaBackuprecovery, FMLFileResourcePack:AromaBackup, FMLFileResourcePack:Avaritia, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:Bonsai Trees, FMLFileResourcePack:Calculator, FMLFileResourcePack:Chameleon, FMLFileResourcePack:ChickenChunks, FMLFileResourcePack:CodeChicken Lib, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:CoFH World, FMLFileResourcePack:CTM, FMLFileResourcePack:CXLibrary, FMLFileResourcePack:Dynamic Trees, FMLFileResourcePack:Forestry, FMLFileResourcePack:MrCrayfish's Furniture Mod, FMLFileResourcePack:Futurepack, FMLFileResourcePack:Futurepack API, FMLFileResourcePack:Immersive Engineering, FMLFileResourcePack:Immersive Petroleum, FMLFileResourcePack:Immersive Tech, FMLFileResourcePack:Inventory Tweaks, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:Just Enough Items, FMLFileResourcePack:LunatriusCore, FMLFileResourcePack:MalisisCore, FMLFileResourcePack:MalisisDoors, FMLFileResourcePack:Mantle, FMLFileResourcePack:Mekanism, FMLFileResourcePack:MekanismGenerators, FMLFileResourcePack:MekanismTools, FMLFileResourcePack:MineColonies, FMLFileResourcePack:MiniHeads, FMLFileResourcePack:More Furnaces, FMLFileResourcePack:NoMoreRecipeConflict, FMLFileResourcePack:OreExcavation, FMLFileResourcePack:Reborn Core, FMLFileResourcePack:Redstone Arsenal, FMLFileResourcePack:Redstone Flux, FMLFileResourcePack:Roost, FMLFileResourcePack:Schematica, FMLFileResourcePack:Simple Ore Generation, FMLFileResourcePack:SonarCore, FMLFileResourcePack:Storage Drawers, FMLFileResourcePack:Tinkers' Construct, FMLFileResourcePack:Tech Reborn, FMLFileResourcePack:Thermal Cultivation, FMLFileResourcePack:Thermal Dynamics, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:The Twilight Forest, FMLFileResourcePack:Water Strainer, FMLFileResourcePack:Wearable Backpacks, FMLFileResourcePack:Wolf Armor and Storage
[10:17:24] [main/WARN]: File minecolonies:sounds/mob/deliveryman/female/inhaleexhale1.ogg does not exist, cannot add it to event minecolonies:mob.deliveryman.female.noise
[10:17:24] [main/WARN]: File minecolonies:sounds/mob/builder/female/whatisit.ogg does not exist, cannot add it to event minecolonies:mob.builder.female.interaction
[10:17:24] [main/WARN]: Missing sound for event: minecolonies:mob.guard.archer.female.badhousing
[10:17:24] [Sound Library Loader/INFO]: Starting up SoundSystem...
[10:17:24] [Thread-10/INFO]: Initializing LWJGL OpenAL
[10:17:24] [Thread-10/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[10:17:25] [Thread-10/INFO]: OpenAL initialized.
[10:17:25] [Sound Library Loader/INFO]: Sound engine started
[10:17:36] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/opaque/pressurizedtubeverticalelite.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:36] [main/WARN]: Texture bibliocraft:textures/models/inkplate1.png with size 8x8 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:36] [main/WARN]: Texture bibliocraft:textures/models/inkplate0.png with size 8x8 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:36] [main/WARN]: Texture bibliocraft:textures/models/inkplate3.png with size 8x8 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:36] [main/WARN]: Texture bibliocraft:textures/models/inkplate2.png with size 8x8 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:36] [main/WARN]: Texture bibliocraft:textures/models/inkplate8.png with size 8x8 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:36] [main/WARN]: Texture bibliocraft:textures/models/inkplate5.png with size 8x8 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:36] [main/WARN]: Texture bibliocraft:textures/models/inkplate4.png with size 8x8 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:36] [main/WARN]: Texture bibliocraft:textures/models/inkplate7.png with size 8x8 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:36] [main/WARN]: Texture bibliocraft:textures/models/inkplate6.png with size 8x8 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:36] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/opaque/thermodynamicconductorverticalelite.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:37] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/thermodynamicconductorverticaladvanced.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:37] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/opaque/universalcableverticalbasic.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:37] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/universalcableverticaladvanced.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:38] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/opaque/thermodynamicconductorverticaladvanced.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:38] [main/WARN]: Texture immersiveengineering:textures/blocks/metal_multiblock_silo.png with size 88x88 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:39] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/pressurizedtubeverticalelite.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:39] [main/WARN]: Texture minecolonies:textures/blocks/info/info_poster_wax.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:39] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/thermodynamicconductorverticalultimate.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:39] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/universalcableverticalelite.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:39] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/pressurizedtubeverticaladvanced.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:39] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/thermodynamicconductorverticalelite.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:40] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/opaque/thermodynamicconductorverticalbasic.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:40] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/opaque/universalcableverticalultimate.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:40] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/opaque/pressurizedtubeverticalbasic.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:40] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/opaque/pressurizedtubeverticaladvanced.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:42] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/opaque/pressurizedtubeverticalultimate.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:42] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/opaque/thermodynamicconductorverticalultimate.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:42] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/universalcableverticalultimate.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:42] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/pressurizedtubeverticalultimate.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:42] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/universalcableverticalbasic.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:42] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/opaque/universalcableverticalelite.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:42] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/opaque/universalcableverticaladvanced.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:42] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/pressurizedtubeverticalbasic.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:43] [main/WARN]: Texture mekanism:textures/blocks/models/multipart/thermodynamicconductorverticalbasic.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[10:17:45] [main/INFO]: Created: 4096x4096 textures-atlas
[10:17:47] [main/WARN]: Unable to resolve texture due to upward reference: #1 in cfm:models/block/blinds_closed
[10:18:12] [main/WARN]: Skipping bad option: lastServer:
[10:18:12] [main/INFO]: Narrator library for x64 successfully loaded
[10:18:38] [Server thread/INFO]: Starting integrated minecraft server version 1.12.2
[10:18:38] [Server thread/INFO]: Generating keypair
[10:18:41] [Server thread/INFO]: Loaded 589 advancements
[10:18:42] [Server thread/INFO]: Preparing start region for level 0
[10:18:43] [Server thread/INFO]: Preparing spawn area: 20%
[10:18:44] [Server thread/INFO]: Preparing spawn area: 77%
[10:18:44] [Aromabackup-Backup/INFO]: [§1AromaBackup§r] Starting Backup. The world may lag for a bit!
[10:18:45] [Server thread/INFO]: Changing view distance to 8, from 10
[10:18:46] [Server thread/INFO]: RedBilly[local:E:4f635097] logged in with entity id 417 at (50.83199476955406, 32.7, 113.03286934265813)
[10:18:46] [Server thread/INFO]: RedBilly присоединился к игре
[10:18:51] [Server thread/INFO]: Saving and pausing game...
[10:18:51] [Server thread/INFO]: Saving chunks for level 'Новый мир'/overworld
[10:18:52] [Server thread/INFO]: Saving chunks for level 'Новый мир'/the_nether
[10:18:52] [Server thread/INFO]: Saving chunks for level 'Новый мир'/the_end
[10:18:52] [Server thread/INFO]: Saving chunks for level 'Новый мир'/tyros
[10:18:52] [Server thread/INFO]: Saving chunks for level 'Новый мир'/menelaus
[10:18:52] [Server thread/INFO]: Saving chunks for level 'Новый мир'/twilight_forest
[10:18:52] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 6122ms behind, skipping 122 tick(s)
[10:18:53] [main/INFO]: [CHAT] §6Thank you for downloading MrCrayfish's Furniture Mod
[10:18:53] [main/INFO]: [CHAT] §6-> §aCheck out all MrCrayfish's Mods
[10:18:53] [main/INFO]: [CHAT] §6-> §rmrcrayfish.com
[10:18:53] [main/INFO]: Loaded 65 advancements
[10:18:53] [main/INFO]: [CHAT] §7------------- §1[Mekanism]§7 -------------
[10:18:53] [main/INFO]: [CHAT] §7 Используется устаревшая версия одного или нескольких модулей.
[10:18:53] [main/INFO]: [CHAT] §9 Mekanism: §49.4.2
[10:18:53] [main/INFO]: [CHAT] §9 MekanismGenerators: §49.4.2
[10:18:53] [main/INFO]: [CHAT] §9 MekanismTools: §49.4.2
[10:18:53] [main/INFO]: [CHAT] §7 Подумайте о обновлении до версии §89.4.3
[10:18:53] [main/INFO]: [CHAT] §7 Нововведения: §9(12/17/17) More fixes for Mekanism. Happy holidays!
[10:18:53] [main/INFO]: [CHAT] §7 Посетите §8aidancbrady.com/mekanism§7 чтобы загрузить.
[10:18:53] [main/INFO]: [CHAT] §7------------- §1[=======]§7 -------------
[10:18:53] [main/INFO]: [CHAT] §2-§4-§2-§4-§2-§4-§2-§4-§2-§4-§2-§4-§2-§1[Mekanism]§2-§4-§2-§4-§2-§4-§2-§4-§2-§4-§2-§4-§2-
[10:18:53] [main/INFO]: [CHAT] §cMerry Christmas, §1RedBilly§c!
[10:18:53] [main/INFO]: [CHAT] §cMay you have plenty of Christmas cheer
[10:18:53] [main/INFO]: [CHAT] §cand have a relaxing holiday with your
[10:18:53] [main/INFO]: [CHAT] §cfamily :)
[10:18:53] [main/INFO]: [CHAT] §8-aidancbrady
[10:18:53] [main/INFO]: [CHAT] §2-§4-§2-§4-§2-§4-§2-§4-§2-§4-§2-§4-§2-§1[=======]§2-§4-§2-§4-§2-§4-§2-§4-§2-§4-§2-§4-§2-
[10:18:58] [Server thread/INFO]: Saving and pausing game...
[10:18:58] [Server thread/INFO]: Saving chunks for level 'Новый мир'/overworld
[10:18:58] [Server thread/INFO]: Saving chunks for level 'Новый мир'/the_nether
[10:18:58] [Server thread/INFO]: Saving chunks for level 'Новый мир'/the_end
[10:18:58] [Server thread/INFO]: Saving chunks for level 'Новый мир'/tyros
[10:18:58] [Server thread/INFO]: Saving chunks for level 'Новый мир'/menelaus
[10:18:58] [Server thread/INFO]: Saving chunks for level 'Новый мир'/twilight_forest
[10:19:00] [Server thread/INFO]: Saving and pausing game...
[10:19:00] [Server thread/INFO]: Saving chunks for level 'Новый мир'/overworld
[10:19:00] [Server thread/INFO]: Saving chunks for level 'Новый мир'/the_nether
[10:19:01] [Server thread/INFO]: Saving chunks for level 'Новый мир'/the_end
[10:19:01] [Server thread/INFO]: Saving chunks for level 'Новый мир'/tyros
[10:19:01] [Server thread/INFO]: Saving chunks for level 'Новый мир'/menelaus
[10:19:01] [Server thread/INFO]: Saving chunks for level 'Новый мир'/twilight_forest
[10:19:01] [Server thread/INFO]: Stopping server
[10:19:01] [Server thread/INFO]: Saving players
[10:19:01] [Server thread/INFO]: RedBilly lost connection: Отключение
[10:19:01] [Server thread/INFO]: RedBilly покинул игру
[10:19:01] [Server thread/INFO]: Stopping singleplayer server as player logged out
[10:19:01] [Server thread/INFO]: Saving worlds
[10:19:01] [Server thread/INFO]: Saving chunks for level 'Новый мир'/overworld
[10:19:01] [Server thread/INFO]: Saving chunks for level 'Новый мир'/the_nether
[10:19:01] [Server thread/INFO]: Saving chunks for level 'Новый мир'/the_end
[10:19:01] [Server thread/INFO]: Saving chunks for level 'Новый мир'/tyros
[10:19:01] [Server thread/INFO]: Saving chunks for level 'Новый мир'/menelaus
[10:19:01] [Server thread/INFO]: Saving chunks for level 'Новый мир'/twilight_forest
[10:19:21] [Server thread/INFO]: Starting integrated minecraft server version 1.12.2
[10:19:21] [Server thread/INFO]: Generating keypair
[10:19:23] [Server thread/INFO]: Loaded 589 advancements
[10:19:24] [Server thread/INFO]: Preparing start region for level 0
[10:19:24] [Server thread/WARN]: Keeping entity minecraft:sheep that already exists with UUID 24436495-465c-431a-aef0-be7602993dbf
[10:19:25] [Server thread/INFO]: Preparing spawn area: 74%
[10:19:26] [Aromabackup-Backup/INFO]: [§1AromaBackup§r] Starting Backup. The world may lag for a bit!
[10:19:26] [Server thread/INFO]: Changing view distance to 8, from 10
[10:19:26] [Server thread/INFO]: RedBilly[local:E:571208b3] logged in with entity id 765 at (37.46906951846774, 71.0, 194.25593261364216)
[10:19:26] [Server thread/INFO]: RedBilly присоединился к игре
[10:19:31] [Server thread/INFO]: Saving and pausing game...
[10:19:31] [Server thread/INFO]: Saving chunks for level 'Fex1'/overworld
[10:19:31] [main/INFO]: [CHAT] §6Thank you for downloading MrCrayfish's Furniture Mod
[10:19:31] [main/INFO]: [CHAT] §6-> §aCheck out MrCrayfish's YouTube
[10:19:31] [main/INFO]: [CHAT] §6-> §ryoutube.com/user/MrCrayfishMinecraft
[10:19:31] [Server thread/INFO]: Saving chunks for level 'Fex1'/the_nether
[10:19:31] [Server thread/INFO]: Saving chunks for level 'Fex1'/the_end
[10:19:31] [Server thread/INFO]: Saving chunks for level 'Fex1'/tyros
[10:19:31] [Server thread/INFO]: Saving chunks for level 'Fex1'/menelaus
[10:19:31] [Server thread/INFO]: Saving chunks for level 'Fex1'/twilight_forest
[10:19:31] [main/INFO]: Loaded 373 advancements
[10:19:32] [Server thread/WARN]: Keeping entity minecraft:sheep that already exists with UUID 0916113c-efa7-433b-9a91-1a2547eac6e9
[10:19:32] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 5762ms behind, skipping 115 tick(s)
[10:19:32] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_121]
	at java.util.Optional.<init>(Unknown Source) ~[?:1.8.0_121]
	at java.util.Optional.of(Unknown Source) ~[?:1.8.0_121]
	at com.minecolonies.coremod.colony.buildings.AbstractBuilding.getCitizenForRequest(AbstractBuilding.java:1718) ~[AbstractBuilding.class:?]
	at com.minecolonies.coremod.colony.buildings.AbstractBuilding.getDisplayName(AbstractBuilding.java:1707) ~[AbstractBuilding.class:?]
	at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester.lambda$getDisplayName$2(BuildingBasedRequester.java:90) ~[BuildingBasedRequester.class:?]
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_121]
	at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester.getDisplayName(BuildingBasedRequester.java:90) ~[BuildingBasedRequester.class:?]
	at com.minecolonies.coremod.colony.requestsystem.resolvers.StandardPlayerRequestResolver.resolve(StandardPlayerRequestResolver.java:123) ~[StandardPlayerRequestResolver.class:?]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.resolveRequest(RequestHandler.java:464) ~[RequestHandler.class:?]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.assignRequestDefault(RequestHandler.java:198) ~[RequestHandler.class:?]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.assignRequest(RequestHandler.java:92) ~[RequestHandler.class:?]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.reassignRequest(RequestHandler.java:252) ~[RequestHandler.class:?]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.reassignRequest(StandardRequestManager.java:235) ~[StandardRequestManager.class:?]
	at com.minecolonies.coremod.colony.requestsystem.resolvers.StandardRetryingRequestResolver.lambda$update$2(StandardRetryingRequestResolver.java:166) ~[StandardRetryingRequestResolver.class:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_121]
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_121]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_121]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_121]
	at com.minecolonies.coremod.colony.requestsystem.resolvers.StandardRetryingRequestResolver.func_73660_a(StandardRetryingRequestResolver.java:178) ~[StandardRetryingRequestResolver.class:?]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.func_73660_a(StandardRequestManager.java:517) ~[StandardRequestManager.class:?]
	at com.minecolonies.coremod.colony.Colony.onServerTick(Colony.java:783) ~[Colony.class:?]
	at com.minecolonies.coremod.colony.ColonyManager.onServerTick(ColonyManager.java:583) ~[ColonyManager.class:?]
	at com.minecolonies.coremod.event.FMLEventHandler.onServerTick(FMLEventHandler.java:35) ~[FMLEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_142_FMLEventHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:264) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[10:19:32] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Administrator\AppData\Roaming\.minecraft\crash-reports\crash-2017-12-25_10.19.32-server.txt
[10:19:32] [Server thread/INFO]: Stopping server
[10:19:32] [Server thread/INFO]: Saving players
[10:19:32] [Server thread/INFO]: RedBilly lost connection: Сервер выключен
[10:19:32] [Server thread/INFO]: RedBilly покинул игру
[10:19:32] [Server thread/INFO]: Stopping singleplayer server as player logged out
[10:19:32] [Server thread/INFO]: Saving worlds
[10:19:32] [Server thread/INFO]: Saving chunks for level 'Fex1'/overworld
[10:19:33] [Server thread/INFO]: Saving chunks for level 'Fex1'/the_nether
[10:19:33] [Server thread/INFO]: Saving chunks for level 'Fex1'/the_end
[10:19:33] [Server thread/INFO]: Saving chunks for level 'Fex1'/tyros
[10:19:33] [Server thread/INFO]: Saving chunks for level 'Fex1'/menelaus
[10:19:33] [Server thread/INFO]: Saving chunks for level 'Fex1'/twilight_forest
[10:19:39] [Client Shutdown Thread/INFO]: Stopping server

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #1907

# Changes proposed in this pull request:
- Fixes 2 exceptions thrown by the requestSystem
- Also fixes a problem where nbt data from itemStacks wasn't copied to the workers.
-

Review please

### CODE REVIEW

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 47 issues
* ![CRITICAL][CRITICAL] 5 critical
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 39 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1437](https://github.com/Minecolonies/minecolonies/blob/bb2d13a3abd7bf5eb2977e75f0d3bea8f2bbb48c/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1437): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1466](https://github.com/Minecolonies/minecolonies/blob/bb2d13a3abd7bf5eb2977e75f0d3bea8f2bbb48c/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1466): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1477](https://github.com/Minecolonies/minecolonies/blob/bb2d13a3abd7bf5eb2977e75f0d3bea8f2bbb48c/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1477): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1583](https://github.com/Minecolonies/minecolonies/blob/bb2d13a3abd7bf5eb2977e75f0d3bea8f2bbb48c/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1583): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1697](https://github.com/Minecolonies/minecolonies/blob/bb2d13a3abd7bf5eb2977e75f0d3bea8f2bbb48c/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1697): Missing curly brace. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00121)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#](https://github.com/Minecolonies/minecolonies/blob/bb2d13a3abd7bf5eb2977e75f0d3bea8f2bbb48c/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#): This file has 1.125 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L80](https://github.com/Minecolonies/minecolonies/blob/bb2d13a3abd7bf5eb2977e75f0d3bea8f2bbb48c/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L80): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 61 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L80](https://github.com/Minecolonies/minecolonies/blob/bb2d13a3abd7bf5eb2977e75f0d3bea8f2bbb48c/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L80): class "AbstractBuilding" has 92 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MINOR][MINOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/bb2d13a3abd7bf5eb2977e75f0d3bea8f2bbb48c/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/bb2d13a3abd7bf5eb2977e75f0d3bea8f2bbb48c/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 47 issues
* ![CRITICAL][CRITICAL] 5 critical
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 39 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1437](https://github.com/Minecolonies/minecolonies/blob/c65836c3538c42bcb77f0e82c5f221cced43b6d3/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1437): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1466](https://github.com/Minecolonies/minecolonies/blob/c65836c3538c42bcb77f0e82c5f221cced43b6d3/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1466): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1477](https://github.com/Minecolonies/minecolonies/blob/c65836c3538c42bcb77f0e82c5f221cced43b6d3/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1477): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1583](https://github.com/Minecolonies/minecolonies/blob/c65836c3538c42bcb77f0e82c5f221cced43b6d3/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1583): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1697](https://github.com/Minecolonies/minecolonies/blob/c65836c3538c42bcb77f0e82c5f221cced43b6d3/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1697): Missing curly brace. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00121)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#](https://github.com/Minecolonies/minecolonies/blob/c65836c3538c42bcb77f0e82c5f221cced43b6d3/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#): This file has 1.125 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L80](https://github.com/Minecolonies/minecolonies/blob/c65836c3538c42bcb77f0e82c5f221cced43b6d3/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L80): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 61 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L80](https://github.com/Minecolonies/minecolonies/blob/c65836c3538c42bcb77f0e82c5f221cced43b6d3/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L80): class "AbstractBuilding" has 92 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MINOR][MINOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/c65836c3538c42bcb77f0e82c5f221cced43b6d3/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/c65836c3538c42bcb77f0e82c5f221cced43b6d3/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 1]
```diff
@@ -1714,8 +1714,15 @@ public ITextComponent getDisplayName(@NotNull final IToken token)
             return Optional.empty();
         }
 
-        Integer citizenData = requestsByCitizen.get(token);
-        return Optional.of(getColony().getCitizen(citizenData));
+        int citizenID = requestsByCitizen.get(token);
+
+        if(getColony().getCitizen(citizenID) == null)
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: This is not needed. If you pass null to a Optional, it will create an Empty Optional

**Review by marchermans — CHANGES_REQUESTED** [review]

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java (hunk 1 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: how does it crash in the following line then with an NPE?

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: https://github.com/Minecolonies/minecolonies/issues/1907

Comment (marchermans) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: getColony() is null

**Comment by Raycoms** [comment]
Ahh will adapt then when I get home and return when getcolony is null

**Comment by marchermans** [comment]
An NPE is only thrown when you Access the null object.
So calling a method, accessing a field etc causes it to throw an NPE.
However you can pass a null as a parameter just fine without it throwing an NPE.

**Comment by Raycoms** [comment]
Ah but isn't the exception null when notnull was expected?

On Dec 25, 2017 4:04 PM, "Marc Hermans" <notifications@github.com> wrote:

An NPE is only thrown when you Access the null object.
So calling a method, accessing a field etc causes it to throw an NPE.
However you can pass a null as a parameter just fine without it throwing an
NPE.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Minecolonies/minecolonies/pull/1908#issuecomment-353883063>,
or mute the thread

**Comment by Raycoms** [comment]
Ahh I interpreted wrongly since it's a NPE where he expected no null

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 47 issues
* ![CRITICAL][CRITICAL] 5 critical
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 39 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1437](https://github.com/Minecolonies/minecolonies/blob/a974715a63ec3d99814919a88fe5789feb96417a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1437): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1466](https://github.com/Minecolonies/minecolonies/blob/a974715a63ec3d99814919a88fe5789feb96417a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1466): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1477](https://github.com/Minecolonies/minecolonies/blob/a974715a63ec3d99814919a88fe5789feb96417a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1477): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1583](https://github.com/Minecolonies/minecolonies/blob/a974715a63ec3d99814919a88fe5789feb96417a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1583): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1697](https://github.com/Minecolonies/minecolonies/blob/a974715a63ec3d99814919a88fe5789feb96417a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1697): Missing curly brace. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00121)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#](https://github.com/Minecolonies/minecolonies/blob/a974715a63ec3d99814919a88fe5789feb96417a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#): This file has 1.121 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L80](https://github.com/Minecolonies/minecolonies/blob/a974715a63ec3d99814919a88fe5789feb96417a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L80): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 61 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L80](https://github.com/Minecolonies/minecolonies/blob/a974715a63ec3d99814919a88fe5789feb96417a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L80): class "AbstractBuilding" has 92 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MINOR][MINOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/a974715a63ec3d99814919a88fe5789feb96417a/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/a974715a63ec3d99814919a88fe5789feb96417a/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Review by marchermans — APPROVED** [review]
