### PR TITLE
More fixes

### LINKED ISSUE #5498: [1.15.2] Crash when accessing Dyer Colonist GUI when no fuel is selected in Dyer Block
When the colonist is asking for fuel and is being player provided, when you access the colonists gui, it crashes the game. As long as some type of fuel source is selected, it doesn't crash.

Minecolonies: 0.13.88-BETA
Structurize: 0.13.35-ALPHA
Forge: 31.2.33

Crash Report: https://gist.github.com/Dyonovan/d361b88c192e0afc337e959dceaf7f53

### LINKED ISSUE #5513: Lvl 3 farm only have 2 fields?
The wiki says a lvl 3 farm can have 3 fields, but my own lvl 3 farm only has access to 2 fields?

(I have th newest version as of today 7th august)

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #5513
Closes #5498
Closes #

# Changes proposed in this pull request:
- Fixes worker not recognizing item he needs (async)
- Fixes Crafterworker with empty fuel setup crash
-

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructureWithWorkOrder.java [hunk 1]
```diff
@@ -178,7 +178,8 @@ private void requestMaterialsState()
             final AbstractBuildingStructureBuilder buildingWorker = getOwnBuilding();
             job.getWorkOrder().setRequested(true);
 
-            if (job.getWorkOrder().getAmountOfRes() == 0)
+            if (job.getWorkOrder().getAmountOfRes() == 0 || buildingWorker.getNeededResources().values().stream()
+                                                              .mapToInt(ItemStorage::getAmount).sum() > job.getWorkOrder().getAmountOfRes())
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructureWithWorkOrder.java]: save the value, you're re-executing the very same below

**Review by someaddons — APPROVED** [review]
