### PR TITLE
GUI Item Tooltips Improvements

### LINKED ISSUE #4161: [1.14.4] Tooltips Render Incorrectly w/ Storage Racks & Citizen Inventories
### Minecolonies version

Version: 0.10.600-alpha

### Expected behavior

-  For the Citizens' inventory, tooltips should render.
- For the Storage Rack, tooltips should render above JEI items.
- The background behind these two GUIs should render slightly darker, similar to other inventories.

### Actual Behavior

- For the Citizens, tooltips don't render at all.
- For the Storage Rack, tooltips render below JEI items instead of above.
- These two inventories don't render w/ slightly darker backgrounds

- Rack inventory:

### Steps to reproduce the problem

1.  Install JEI
2.  Check tooltips of the Storage Rack
3.  Check for tooltips in Citizen inventories.
4. ... Profit

### PR DESCRIPTION
**Pull request by WenXin20**
Closes #4161 

# Changes proposed in this pull request:
- Fixes tooltips not rendering in Citizen's GUI
- Fixes tooltips not rendering in Furnace/Crafting Teach Recipe GUIs
- Fixes tooltips not rendering in the Field GUI
- Fixes tooltips rendering below JEI's item list in the Rack 

Review please,
this was surprisingly easy to fix

### CODE REVIEW

**Comment by Raycoms** [comment]
Thanks a lot for the contribution, could you add @Override signs over those methods. So we detect when they change in a mapping change?

**Comment by WenXin20** [comment]
Alright, they should all have it now.

**Comment by Raycoms** [comment]
ty :shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/4486/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

File: src/main/java/com/minecolonies/coremod/client/gui/containers/WindowCitizenInventory.java [hunk 1]
```diff
@@ -29,6 +29,14 @@ public WindowCitizenInventory(final ContainerCitizenInventory container, final P
         this.ySize = 114 + this.inventoryRows * 18;
     }
 
+    @override
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/client/gui/containers/WindowCitizenInventory.java]: Misscase

**Review by Nightenom — CHANGES_REQUESTED** [review]

File: src/main/java/com/minecolonies/coremod/client/gui/containers/WindowCitizenInventory.java (hunk 1 above)
Comment (WenXin20) [reply src/main/java/com/minecolonies/coremod/client/gui/containers/WindowCitizenInventory.java]: Fixed
