### PR TITLE
Fix knight damage

### LINKED ISSUE #10631: Guards(Knight) permanently gain 1 damage for each attack in 1.21.1.
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

minecolonies-1.1.864-1.21.1-snapshot

### Structurize Version

structurize-1.0.758-1.21.1-snapshot

### Related Mods and their Versions

Neoforge - 21.1.115
Neat.
No other mods were used.

### Current Behavior

Guards permanently gain 1 damage for each attack.
https://youtu.be/bGiV5io6OK8
(Works as expected in 1.20.1.)

### Expected Behavior

Deal normal damage.

### Reproduction Steps

Find a knight and let him attack something.

### Logs

https://gist.github.com/fulmoonless/4ea695236b0e327f362a826703bace09

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by someaddons**
Closes #10631
Closes #

# Changes proposed in this pull request
- Fix knight damage calculation, no longer uses durability for damage
-

## Testing
- [ x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/core/entity/ai/workers/guard/KnightCombatAI.java [hunk 1]
```diff
@@ -256,13 +257,13 @@ private double getAttackDamage()
         {
             if (heldItem.getItem() instanceof SwordItem)
             {
-                addDmg += ((SwordItem) heldItem.getItem()).getDamage(heldItem) + BASE_PHYSICAL_DAMAGE;
+                addDmg += user.getAttribute(Attributes.ATTACK_DAMAGE).getValue();
```
Comment (uecasm) [inline src/main/java/com/minecolonies/core/entity/ai/workers/guard/KnightCombatAI.java:260]: It should probably do this unconditionally (i.e. remove the SwordItem/Tinkers check. since Tinkers swords should support this query too).
