### PR TITLE
Fill in many of the builder-requested recipes

### LINKED ISSUE #5303: Can't create cactus planks
Version: minecolonies-0.13.7-ALPHA-universal

### Expected behavior
When I teach the recipe for cactus planks at Sawmill or Planter, then he adds it.

### Actual behaviour
It does not add, I have a message: "Unable to store th blueprint. Either the sawmill has no space for any more blueprints, or the blueprint doesn't correspond with its profession". Even if there is no recipe.
Or then I don't have the right worker ...

### Steps to reproduce the problem
1. Teach "Cactus plank" to Sawmill or Planter

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log: no needed
- crashlog: no crash

### PR DESCRIPTION
**Pull request by Mekle001**
Closes #5303

# Changes proposed in this pull request:
- Add tag based recipe support to stonesmeltery
- Add Redsand recipe to dyer
- Add sandstone recipes to stonemason
- Add many other recipes to the other crafters.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingStonemason.java [hunk 1]
```diff
@@ -50,6 +56,30 @@ public BuildingStonemason(final IColony c, final BlockPos l)
...
+    @Override
+    public void checkForWorkerSpecificRecipes()
+    {
+        final IRecipeStorage sandstoneStorage = StandardFactoryController.getInstance().getNewInstance(
+          TypeConstants.RECIPE,
+          StandardFactoryController.getInstance().getNewInstance(TypeConstants.ITOKEN),
+          ImmutableList.of(new ItemStack(Blocks.COBBLESTONE, 1), new ItemStack(Blocks.SAND, 1)),
+          1,
+          new ItemStack(Blocks.SANDSTONE, 1),
+          Blocks.AIR);
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingStonemason.java:68]: We wanted to make it 2 sandstone here. Could make that a research though too.

Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingStonemason.java:68]: think the research isnt that required though, since the sand from the crusher already hasone

Comment (Mekle001) [reply src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingStonemason.java:68]: I like the idea of a research for that. This already reduces the cost of sandstone quite a bit, from 4 sand to 1 sand and 1 cobble. Dropping it to 1:1 seems like a research. I'll look at that in a future round.

**Comment by Mekle001** [comment]
Closes #5303

**Review by marchermans — APPROVED** [review]
@Mekle001 Could you also document this on the wiki please?

**Comment by Mekle001** [comment]
@OrionDevelopment Absolutely, will do.

**Comment by PowerSchill** [comment]
Won't this break the blacksmith making stone tools and weapons?

**Comment by Mekle001** [comment]
@PowerSchill Yup. Good catch. Additional Rules should always take precedence over tags. Fix incoming.
