### PR TITLE
Fix crafter issues

### LINKED ISSUE #4860: Crash Report RE: Ticking Entity related to fulfilling a builder's last requested item
### Minecolonies version: 0.11.913

I fulfilled the builder's last request for upgrading my wooden university to level 2 (the last requested item was a powered rail). This was through the builder's block "fulfill" button, not the builder's requests menu.

The citizen named in the crash log isn't the builder. The citizen named in the crash log is one of my deliverymen. I had extras of the last few items the builder needed in the warehouse already, is it possible the crash is related to the deliveryman wigging out when I fulfilled the builder's request before he did?

### Log: 

- crashlog: [crash-2020-05-03_05.34.40-server.txt](https://github.com/ldtteam/minecolonies/files/4570294/crash-2020-05-03_05.34.40-server.txt)

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #4860

# Changes proposed in this pull request:
- Fixes crafting request loops
- Allows crafter to detect and recover from issues
-

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAICrafting.java [hunk 1]
```diff
@@ -141,7 +140,20 @@ private IAIState getRecipe()
...
         final int currentCount = InventoryUtils.getItemCountInItemHandler(worker.getInventoryCitizen(), stack -> stack.isItemEqual(currentRecipeStorage.getPrimaryOutput()));
         final int countPerIteration = currentRecipeStorage.getPrimaryOutput().getCount();
-        job.setCraftCounter(currentCount/countPerIteration);
+        final int doneOpsCount = currentCount/countPerIteration;
+        final int remainingOpsCount = currentRequest.getRequest().getCount() - doneOpsCount;
+
+        final List<ItemStorage> input = currentRecipeStorage.getCleanedInput();
+        for (final ItemStorage inputStorage : input)
+        {
+            if (InventoryUtils.getItemCountInProvider(getOwnBuilding(), itemStack -> itemStack.isItemEqual(inputStorage.getItemStack())) + InventoryUtils.getItemCountInItemHandler(worker.getInventoryCitizen(), itemStack -> itemStack.isItemEqual(inputStorage.getItemStack())) < inputStorage.getAmount() * remainingOpsCount)
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAICrafting.java]: line length

**Review by marchermans — DISMISSED** [review]

**Review by someaddons — DISMISSED** [review]
