### PR TITLE
Study improvement, solve deprecated, assistant interference improvement

### LINKED ISSUE #7489: Cook Issues - Stuck on requests and sitting down when hungry
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.328-ALPHA-universal
- Structurize Version: structurize-0.13.208-ALPHA-universal
- Related Mods and their Versions: Adventures 3.5 server

## Expected behavior
When minimum food requests are set, I would expect for the assistant cook to handle all crafting related requests. Allowing for the cook to request all other type of foods for the restaurant. Additionally, I would expect for the cook to work though hunger to ensure food is still being requested / prepared, and eating to at least half food saturation, before serving others.

## Actual behavior
I have put golden carrots and Sweet Bread as minimum 1 stack stock in the restaurant. Occasionally, the cook themselves handle the request for ingredients. If there is not enough ingredients to make the required items, the cook will get stuck waiting on that request to be fulfilled. Resulting in the cook never requesting any other food supplies to keep the restaurant in stock.    

Additionally, if the cook gets hungry and does not have food for themselves, the cook will then sit down and stop all work until they are manually fed.

https://cdn.discordapp.com/attachments/486940969737125922/875071377625976833/Cook_-_Stuck_requesting.mp4

## Steps to reproduce the issue

Setting complicated recipes as minimum stocks in restaurant. Golden Carrots, Loaded Potatoes are the ones I've had primary issues causing this.  Then not have enough ingredients to make the full stack at once, and time.

### Notes
Part of the issue may be that the crafters are attempting to put a request in to make the entire stack at a time, rather than piecemealing what they can.  So currently putting in a single request to craft x64 recipe at once, rather than crafting it in smaller batches such as x8 or x16 at a time.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #7498: Future Forge Compat issue in log
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:             1.16.5
- MineColonies Version:      0.14.328
- Structurize Version:           0.13.208

## Problem description
Forge console output strongly suggests a class Minecolonies is using is deprecated.  See this:

```
12:22:03
Called deprecated GlobalEntityTypeAttributes#put for numina:armor_stand_entity, use EntityAttributeCreationEvent instead.
Called deprecated GlobalEntityTypeAttributes#put for minecolonies:citizen, use EntityAttributeCreationEvent instead.
Called deprecated GlobalEntityTypeAttributes#put for minecolonies:visitor, use EntityAttributeCreationEvent instead.
Called deprecated GlobalEntityTypeAttributes#put for minecolonies:mercenary, use EntityAttributeCreationEvent instead.
Called deprecated GlobalEntityTypeAttributes#put for minecolonies:mercenary, use EntityAttributeCreationEvent instead.
Called deprecated GlobalEntityTypeAttributes#put for minecolonies:barbarian, use EntityAttributeCreationEvent instead.
Called deprecated GlobalEntityTypeAttributes#put for minecolonies:archerbarbarian, use EntityAttributeCreationEvent instead.
Called deprecated GlobalEntityTypeAttributes#put for minecolonies:chiefbarbarian, use EntityAttributeCreationEvent instead.
Called deprecated GlobalEntityTypeAttributes#put for minecolonies:pharao, use EntityAttributeCreationEvent instead.
Called deprecated GlobalEntityTypeAttributes#put for minecolonies:mummy, use EntityAttributeCreationEvent instead.
Called deprecated GlobalEntityTypeAttributes#put for minecolonies:archermummy, use EntityAttributeCreationEvent instead.
Called deprecated GlobalEntityTypeAttributes#put for minecolonies:pirate, use EntityAttributeCreationEvent instead.
Called deprecated GlobalEntityTypeAttributes#put for minecolonies:archerpirate, use EntityAttributeCreationEvent instead.
Called deprecated GlobalEntityTypeAttributes#put for minecolonies:chiefpirate, use EntityAttributeCreationEvent instead.
Called deprecated GlobalEntityTypeAttributes#put for minecolonies:amazon, use EntityAttributeCreationEvent instead.
Called deprecated GlobalEntityTypeAttributes#put for minecolonies:amazonchief, use EntityAttributeCreationEvent instead.
Called deprecated GlobalEntityTypeAttributes#put for minecolonies:norsemenarcher, use EntityAttributeCreationEvent instead.
Called deprecated GlobalEntityTypeAttributes#put for minecolonies:norsemenchief, use EntityAttributeCreationEvent instead.
Called deprecated GlobalEntityTypeAttributes#put for minecolonies:shieldmaiden, use EntityAttributeCreationEvent instead.
```

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #7498 
Closes #7489
Closes #

# Changes proposed in this pull request:
- Move entity attributes to event
- Adjust study food counter properly
- Consider assistant items at cook properly

Review please

### CODE REVIEW

**Review by someaddons — APPROVED** [review]

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/cook/EntityAIWorkCook.java [hunk 1]
```diff
@@ -327,15 +334,14 @@ else if (!InventoryUtils.hasItemInProvider(getOwnBuilding(), stack -> ItemStackU
...
     {
-        if(this.assistantTests.isEmpty())
+        if(this.reservedItemCache.isEmpty())
         {
-            this.assistantTests.addAll(getOwnBuilding().getFirstModuleOccurance(BuildingCook.CraftingModule.class).getAssistantItems());
+            this.reservedItemCache.addAll(getOwnBuilding().getFirstModuleOccurance(BuildingCook.CraftingModule.class).reservedStacks().keySet());
         }
 
-        return ItemStackUtils.compareItemStackListIgnoreStackSize(new ArrayList<>(assistantTests), stack, true, true);
+        return reservedItemCache.contains(new ItemStorage(stack));
```
Comment (uecasm) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/cook/EntityAIWorkCook.java:342]: Unless `reservedStacks()` returns storages with the ignore NBT flag set, this will no longer ignore NBT.  For most crafting ingredients that may be a good thing, but I suspect it might break compatibility with utensils that take damage (unless those already weren't supported due to other code).

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/cook/EntityAIWorkCook.java:342]: This is only for "cook not taking away cooking materials", so this should not be a problem with taking damage ones?
