### PR TITLE
Fix/crashes expceptions

### LINKED ISSUE #953: [1.11.2- 0.7.887
no idea what's causing the crash

https://paste.ee/p/40Et9

### LINKED ISSUE #956: Crash Report
---- Minecraft Crash Report ----

WARNING: coremods are present:
  RebornCoreASM (RebornCore-1.11.2-2.14.1.92-universal.jar)
  IvToolkit (IvToolkit-1.3.3.jar)
  RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.1.0.jar)
  LoadingPlugin (Quark-r1.2-91.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 5/9/17 2:02 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.minecolonies.coremod.entity.EntityCitizen.addExperience(EntityCitizen.java:609)
	at com.minecolonies.coremod.entity.EntityCitizen.gatherXp(EntityCitizen.java:574)
	at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:1042)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1784)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.minecolonies.coremod.entity.EntityCitizen.addExperience(EntityCitizen.java:609)
	at com.minecolonies.coremod.entity.EntityCitizen.gatherXp(EntityCitizen.java:574)
	at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:1042)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: minecolonies:citizen (com.minecolonies.coremod.entity.EntityCitizen)
	Entity ID: 152
	Entity Name: Hannah Z. Basset
	Entity's Exact location: 248.52, 63.00, 214.71
	Entity's Block location: World: (248,63,214), Chunk: (at 8,3,6 in 15,13; contains blocks 240,0,208 to 255,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1748)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['fito'/386, l='MpServer', x=216.32, y=68.00, z=141.84]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (244,64,160), Chunk: (at 4,4,0 in 15,10; contains blocks 240,0,160 to 255,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 20702989 game time, 21914640 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 76 total; [EntityBat['Murciélago'/1542, l='MpServer', x=242.48, y=44.69, z=140.96], EntityBat['Murciélago'/1543, l='MpServer', x=233.29, y=46.02, z=155.60], EntityDonkey['Burro'/35, l='MpServer', x=141.92, y=67.00, z=77.14], EntityPig['Cerdo'/37, l='MpServer', x=137.52, y=63.00, z=83.30], EntityPig['Cerdo'/38, l='MpServer', x=140.23, y=66.00, z=89.54], EntityBat['Murciélago'/807, l='MpServer', x=231.78, y=20.53, z=179.96], EntityChicken['Gallina'/40, l='MpServer', x=138.38, y=68.00, z=126.03], EntitySkeleton['Esqueleto'/1323, l='MpServer', x=157.50, y=29.00, z=101.50], EntityCreeper['Creeper'/1586, l='MpServer', x=175.50, y=46.00, z=132.62], EntityPig['Cerdo'/56, l='MpServer', x=145.78, y=65.00, z=78.52], EntityPig['Cerdo'/77, l='MpServer', x=172.55, y=64.00, z=63.21], EntityItem['item.item.bone'/78, l='MpServer', x=175.20, y=64.00, z=127.41], EntityItem['item.item.arrow'/79, l='MpServer', x=175.44, y=65.00, z=124.95], EntityCitizen['Juliana U. Cranford'/82, l='MpServer', x=166.69, y=68.06, z=157.50], EntityCitizen['Daniela H. Askew'/83, l='MpServer', x=164.97, y=68.00, z=156.70], EntityCitizen['Jacob F. Arnold'/84, l='MpServer', x=166.50, y=68.06, z=156.33], EntityCitizen['Elizabeth O. Clark'/85, l='MpServer', x=167.50, y=68.00, z=155.01], EntityCitizen['Elliot P. Compton'/86, l='MpServer', x=165.48, y=68.28, z=158.44], EntityChicken['Gallina'/87, l='MpServer', x=175.87, y=65.00, z=158.48], EntityCitizen['Kaylee V. Brown'/88, l='MpServer', x=166.88, y=68.00, z=180.25], EntityCitizen['Jane M. Badby'/89, l='MpServer', x=166.30, y=68.06, z=171.59], EntityCitizen['Edmund J. Hackman'/90, l='MpServer', x=167.50, y=68.04, z=169.61], EntityCitizen['Austin V. Clitherow'/91, l='MpServer', x=166.90, y=68.06, z=171.44], EntitySkeleton['Esqueleto'/859, l='MpServer', x=194.49, y=47.00, z=116.76], EntityCitizen['Katia R. White'/92, l='MpServer', x=208.31, y=66.00, z=112.48], EntityCitizen['Curtis V. White'/93, l='MpServer', x=255.40, y=64.00, z=200.50], EntityCitizen['Elinor S. Aldebourne'/107, l='MpServer', x=222.85, y=64.00, z=168.24], EntityItem['item.tile.tnt'/117, l='MpServer', x=200.21, y=67.00, z=84.20], EntityItem['item.tile.cloth.lime'/118, l='MpServer', x=200.13, y=67.00, z=84.41], EntitySkeleton['Esqueleto'/1913, l='MpServer', x=195.50, y=20.00, z=145.50], EntityCreeper['Creeper'/1915, l='MpServer', x=185.52, y=20.00, z=152.19], EntityZombie['Zombi'/125, l='MpServer', x=199.59, y=64.00, z=218.04], EntityCitizen['Guewen V. Gare'/129, l='MpServer', x=295.78, y=64.00, z=115.53], EntityPlayerSP['fito'/386, l='MpServer', x=216.32, y=68.00, z=141.84], EntitySkeleton['Esqueleto'/1925, l='MpServer', x=246.50, y=7.00, z=204.50], EntityZombie['Zombi'/135, l='MpServer', x=200.56, y=17.00, z=74.74], EntityArmorStand['Soporte para armadura'/137, l='MpServer', x=223.50, y=68.00, z=139.50], EntityArmorStand['Soporte para armadura'/138, l='MpServer', x=223.50, y=64.00, z=141.50], EntityArmorStand['Soporte para armadura'/139, l='MpServer', x=215.50, y=64.00, z=143.50], EntityArmorStand['Soporte para armadura'/140, l='MpServer', x=215.50, y=69.00, z=149.50], EntityFishHook['entity.Fishhook.name'/2188, l='MpServer', x=244.82, y=63.41, z=215.18], EntityArmorStand['Soporte para armadura'/141, l='MpServer', x=220.50, y=65.00, z=151.50], EntityCitizen['Maisy D. Atkinson'/149, l='MpServer', x=233.50, y=63.00, z=33.72], EntityItem['item.item.bone'/150, l='MpServer', x=225.04, y=66.00, z=116.17], EntityBat['Murciélago'/1687, l='MpServer', x=253.07, y=47.00, z=214.89], EntityCitizen['Hannah Z. Basset'/152, l='MpServer', x=248.52, y=63.00, z=214.71], EntityCitizen['James I. Greene'/153, l='MpServer', x=221.67, y=64.00, z=171.91], EntityCitizen['Miles P. Aynesworth'/154, l='MpServer', x=228.95, y=64.00, z=174.49], EntityCitizen['Elias F. Gonson'/155, l='MpServer', x=225.15, y=12.00, z=190.58], EntityItem['item.tile.tnt'/160, l='MpServer', x=255.02, y=70.00, z=90.15], EntityItem['item.tile.cloth.lime'/161, l='MpServer', x=255.76, y=70.00, z=92.07], EntityItem['item.item.sulphur'/162, l='MpServer', x=255.60, y=70.00, z=91.66], EntityWolf['Lobo'/164, l='MpServer', x=242.26, y=63.00, z=137.30], EntityCitizen['Asher V. Babington'/165, l='MpServer', x=243.35, y=63.06, z=142.50], EntityWolf['Lobo'/166, l='MpServer', x=240.68, y=57.00, z=155.34], EntityZombie['Zombi'/2470, l='MpServer', x=252.27, y=31.00, z=137.51], EntityCitizen['Jack L. Greenway'/167, l='MpServer', x=205.33, y=64.94, z=127.53], EntityZombie['Zombi'/2471, l='MpServer', x=250.50, y=31.00, z=135.50], EntityZombie['Zombi'/2472, l='MpServer', x=251.18, y=31.00, z=136.13], EntityZombie['Zombi'/1712, l='MpServer', x=190.50, y=21.00, z=144.50], EntityCreeper['Creeper'/1713, l='MpServer', x=190.50, y=21.00, z=144.50], EntitySkeleton['Esqueleto'/948, l='MpServer', x=255.50, y=7.00, z=217.50], EntitySpider['Araña'/949, l='MpServer', x=247.50, y=7.00, z=212.50], EntityZombie['Zombi'/2491, l='MpServer', x=150.50, y=23.00, z=98.50], EntityChicken['Gallina'/188, l='MpServer', x=265.50, y=75.29, z=111.80], EntityItem['item.item.bone'/189, l='MpServer', x=264.88, y=73.00, z=99.72], EntityItem['item.tile.sapling.oak'/2503, l='MpServer', x=214.57, y=77.00, z=182.06], EntityBat['Murciélago'/2507, l='MpServer', x=222.88, y=11.76, z=216.75], EntityZombie['Zombi'/1996, l='MpServer', x=245.50, y=27.00, z=90.50], EntityPig['Cerdo'/209, l='MpServer', x=282.67, y=73.00, z=90.51], EntityPig['Cerdo'/210, l='MpServer', x=276.59, y=78.00, z=106.29], EntityPig['Cerdo'/211, l='MpServer', x=274.50, y=84.00, z=107.28], EntityCreeper['Creeper'/2009, l='MpServer', x=212.50, y=28.00, z=67.50], EntityZombie['Zombi'/1754, l='MpServer', x=214.50, y=11.00, z=181.50], EntityXPOrb['Orbe de experiencia'/2528, l='MpServer', x=248.52, y=63.00, z=215.21], EntityCreeper['Creeper'/2297, l='MpServer', x=156.50, y=42.00, z=90.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 404130568 bytes (385 MB) / 2313158656 bytes (2206 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G
	IntCache: cache: 0, tcache: 0, allocated: 20, tallocated: 86
	FML: MCP 9.38 Powered by Forge 13.20.0.2294 Optifine OptiFine_1.11.2_HD_U_B7 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2294.jar) 
	UCHIJAAAA	forge{13.20.0.2294} [Minecraft Forge] (forge-1.11.2-13.20.0.2294.jar) 
	UCHIJAAAA	ivtoolkit{1.3.3} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	uncraftingtable{1.7.1-pre15} [Uncrafting Table] ([1.11.2]UncraftingTable-1.7.1-pre15.jar) 
	UCHIJAAAA	autoplant{1.11.2-1.0.0} [AutoPlant] (autoplant-1.11.2-1.0.0.jar) 
	UCHIJAAAA	quark{r1.2-91} [Quark] (Quark-r1.2-91.jar) 
	UCHIJAAAA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.11.2.jar) 
	UCHIJAAAA	betterthanmending{@VERSION@} [Better Than Mending] (BetterThanMending-1.1.0.jar) 
	UCHIJAAAA	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHIJAAAA	koresample{1.11.2-L1.2} [Kore Sample] (koresample-1.11.2-L1.2.jar) 
	UCHIJAAAA	dendrology{1.11.2-L1.2.1} [Ancient Trees] (dendrology-1.11.2-L1.2.1.jar) 
	UCHIJAAAA	dsurround{3.4.1.0} [§3Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.4.1.0.jar) 
	UCHIJAAAA	presets{3.4.1.0} [§3Presets!] (DynamicSurroundings-1.11.2-3.4.1.0.jar) 
	UCHIJAAAA	logicaldrops{0.9.4} [Logical Drops] (EM3R50N-LogicalDrops-1.11.2-13.20.0.2201.jar) 
	UCHIJAAAA	excore{2.0.0-alpha10-1.11.2} [EXCore] (EXCore-2.0.0-alpha10-1.11.2.jar) 
	UCHIJAAAA	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIJAAAA	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCHIJAAAA	waila{1.8.12} [Waila] (Hwyla-1.8.12-B25_1.11.jar) 
	UCHIJAAAA	jei{4.3.4.273} [Just Enough Items] (jei_1.11.2-4.3.4.273.jar) 
	UCHIJAAAA	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHIJAAAA	minecolonies{1.11.2-0.7.887} [MineColonies] (minecolonies-universal-1.11.2-0.7.887.jar) 
	UCHIJAAAA	reborncore{2.14.1.92} [Reborn Core] (RebornCore-1.11.2-2.14.1.92-universal.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.14.1.92} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.14.1.92-universal.jar) 
	UCHIJAAAA	reccomplex{1.3.1} [Recurrent Complex] (RecurrentComplex-1.3.1.jar) 
	UCHIJAAAA	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCHIJAAAA	shulkerbox{1.1.1} [Shulkerbox] (shulkerbox-1.1.1.jar) 
	UCHIJAAAA	storagedrawers{1.11.2-4.2.4} [Storage Drawers] (StorageDrawers-1.11.2-4.2.4.jar) 
	UCHIJAAAA	techreborn{2.2.1.142} [Tech Reborn] (TechReborn-1.11.2-2.2.1.142-universal.jar) 
	UCHIJAAAA	torohealthmod{1.11.2-11} [ToroHealth Damage Indicators] (torohealth-1.11.2-11.jar) 
	UCHIJAAAA	unifieditems{1.5.4.168} [Unified Items] (UnifiedItems-1.11.2-1.5.4-168.jar) 
	UCHIJAAAA	veinminer{0.35.3} [Vein Miner] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJAAAA	veinminermodsupport{0.35.3} [Mod Support] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJAAAA	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	UCHIJAAAA	wanionlib{1.11.2-1.0} [WanionLib] (WanionLib-1.11.2-1.0.jar) 
	UCHIJAAAA	xaerominimap{1.12.7} [Xaero's Minimap] (Xaeros_Minimap_1.12.7_Forge_1.11.jar) 
	UCHIJAAAA	xaeroworldmap{1.8.1} [Xaero's World Map] (XaerosWorldMap_b1.8.1_Forge_1.11.jar) 
	UCHIJAAAA	unidict{1.11.2-1.0} [UniDict] (UniDict-1.11.2-1.0.jar) 
	Loaded coremods (and transformers): 
RebornCoreASM (RebornCore-1.11.2-2.14.1.92-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
IvToolkit (IvToolkit-1.3.3.jar)
  
RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  pw.prok.realbench.asm.RBTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.1.0.jar)
  org.blockartistry.DynSurround.asm.Transformer
LoadingPlugin (Quark-r1.2-91.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.14.4432' Renderer: 'Intel(R) HD Graphics 4400'
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.14.1.92
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 1
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2294
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 10.18.14.4432, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Lithos-Core v1.14 for 1.11x.zip
	Current Language: Español (España)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 10.18.14.4432
	OpenGlRenderer: Intel(R) HD Graphics 4400
	OpenGlVendor: Intel
	CpuCount: 4

### LINKED ISSUE #957: Crash when upgrading or repairing buildings
### Minecolonies version

minecolonies-universal-1.11.2-0.7.887.jar

### Expected behavior

- Upgrading a building to level 2 or repair it

### Actual behaviour

- Builder take ressources, go to build spot to upgrade and doesn't do anything (problem occurs for my friend and me, not the same city or building but can't go to level 2 building like Citizen's Hut or Sawmill. Here is the console log: 

[13:42:04] [Server thread/ERROR] [minecolonies]: Pausing Entity Melanie L. Cheyne (com.minecolonies.coremod.job.Builder) at BlockPos{x=310, y=63, z=561} for 0 Seconds because of error:
[13:42:04] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException: The validated object is null
[13:42:04] [Server thread/INFO]: [STDERR]: at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
[13:42:04] [Server thread/INFO]: [STDERR]: at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.util.NonNullList.set(SourceFile:45)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.entity.EntityLiving.func_184201_a(EntityLiving.java:919)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.placementhandlers.PlacementHandlers$AirPlacementHandler.handle(PlacementHandlers.java:271)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.placeBlockAt(AbstractEntityAIStructure.java:547)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.structureStep(AbstractEntityAIStructure.java:241)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure$$Lambda$98/1586102803.apply(Unknown Source)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.lambda$generateStructureGenerator$3(AbstractEntityAIStructure.java:279)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure$$Lambda$97/1515049437.get(Unknown Source)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.util.AITarget.apply(AITarget.java:125)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.applyTarget(AbstractAISkeleton.java:201)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.checkOnTarget(AbstractAISkeleton.java:175)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton$$Lambda$138/411806598.test(Unknown Source)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:128)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:769)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2258)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:573)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:171)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:1061)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.world.World.func_72866_a(World.java:1963)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.world.World.func_72870_g(World.java:1932)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.world.World.func_72939_s(World.java:1748)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.
minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.lang.Thread.run(Thread.java:745)

### Steps to reproduce the problem

1. Launch Minecraft with forge 1.11.2-13.20.0.2282
2. Launch upgrade level 2 for sawmill (wood) or citizen's hut (stone)
3. Huge lag on server and if we don't stop builder, server crash

Thanks for your help :)

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #953
Closes #957
Closes #956 

# Changes proposed in this pull request:
- Fixes a nullpointer exception with citizenData

Review please

### CODE REVIEW

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 113 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 44 major
* ![MINOR][MINOR] 58 minor
* ![INFO][INFO] 10 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BlockUtils.java#L238](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L238): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.289 lines, which is greater than 750 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 64 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L355](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L355): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L356](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L356): Assign this magic number 6.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 114 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 45 major
* ![MINOR][MINOR] 58 minor
* ![INFO][INFO] 10 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BlockUtils.java#L238](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L238): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [CitizenData.java#L23](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/colony/CitizenData.java#L23): class "CitizenData" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.289 lines, which is greater than 750 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 64 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L355](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L355): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 114 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 45 major
* ![MINOR][MINOR] 58 minor
* ![INFO][INFO] 10 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BlockUtils.java#L238](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L238): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [CitizenData.java#L23](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/colony/CitizenData.java#L23): class "CitizenData" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.289 lines, which is greater than 750 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 64 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L355](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L355): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/colony/CitizenData.java [hunk 1]
```diff
@@ -329,18 +329,25 @@ public void initializeFromEntity(@NotNull final EntityCitizen entity)
...
-            firstName = String.format("%s %s. %s", getRandomElement(rand, Configurations.maleFirstNames), getRandomLetter(rand),
+            citizenName = String.format("%s %s. %s", getRandomElement(rand, Configurations.maleFirstNames), getRandomLetter(rand),
                     getRandomElement(rand, Configurations.lastNames));
         }
-        return String.format("%s %s. %s", firstName, getRandomLetter(rand), getRandomElement(rand, Configurations.lastNames));
+        for (int i = 1; i <= this.getColony().getMaxCitizens(); i++)
+        {
+            if (this.getColony().getCitizen(i) != null && this.getColony().getCitizen(i).getName().equals(citizenName))
+            {
+                citizenName = generateName(rand);
```
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/colony/CitizenData.java:347]: This will stackoverflow if all names are used.

**Review by marvin-bitterlich — CHANGES_REQUESTED** [review]
You killed the creative tab background? What happened there?

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 114 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 45 major
* ![MINOR][MINOR] 58 minor
* ![INFO][INFO] 10 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BlockUtils.java#L238](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L238): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [CitizenData.java#L23](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/colony/CitizenData.java#L23): class "CitizenData" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.289 lines, which is greater than 750 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 64 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L355](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L355): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 118 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 46 major
* ![MINOR][MINOR] 58 minor
* ![INFO][INFO] 13 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BlockUtils.java#L238](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L238): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [CitizenData.java#L23](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/colony/CitizenData.java#L23): class "CitizenData" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.289 lines, which is greater than 750 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 64 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L355](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L355): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 118 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 46 major
* ![MINOR][MINOR] 58 minor
* ![INFO][INFO] 13 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BlockUtils.java#L238](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L238): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [CitizenData.java#L23](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/colony/CitizenData.java#L23): class "CitizenData" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.289 lines, which is greater than 750 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 64 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L355](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L355): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/colony/CitizenData.java (hunk 1 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/CitizenData.java:347]: Nojo created that a whole while ago already.
That's the same like in 1.10 I just copied it from there to here because merged broke it
