### PR TITLE
Fix pathfinding crash

### LINKED ISSUE #4156: Server crashes -- Entity being ticked --
### Minecolonies version

Version: forge-1.12.2-14.23.5.2836-universal 
 minecolonies-1.12.2-0.10.599-ALPHA-universal
 structurize-1.12.2-0.10.124-ALPHA
 

### Expected behavior

-  Server should start 

### Actual behaviour

-  Server is crashing, while trying to start

### Steps to reproduce the problem

Hi Team 

This time I have an Issue with my 1.12.2 Forge Server (hosted server)
The Server crashed and I cannot bring him back to start up

I have played for a while with minecolonies-1.12.2-0.10.545-ALPHA-universal.jar and nearly everything was fine
At the 12/16/2019 I updated to minecolonies-1.12.2-0.10.592-RELEASE-universal.jar and it was fine, played for a while
At the 12/17/2019 I logged on, checked a few things and left the Server for an hour or so running, with only me loggend on.
When I came back to my System, I found the Server crashed and couldt not startup the Server again.
With minecolonies-1.12.2-0.10.545-ALPHA-universal and all my mods in these Versions, I have already played for weeks, with no big issues or crashes.

Today i tried to update to minecolonies-1.12.2-0.10.599-ALPHA-universal.jar, just to see if there was any change. The Server crashed again, while stating up. In the crash log I can find

-- Entity being ticked --
Details:
	Entity Type: minecolonies:sitting_entity (com.minecolonies.coremod.entity.SittingEntity)
	Entity ID: 439
	Entity Name: entity.SITTING_ENTITY.name
	Entity's Exact location: 107.62, 72.00, 582.57
	Entity's Block location: World: (107,72,582), Chunk: (at 11,4,6 in 6,36; contains blocks 96,0,576 to 111,255,591), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [EntityCitizen['Charity S. Gorney'/440, l='world', x=107.62, y=72.38, z=582.57]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
	
so it might be, that one of my Guards fell asleep in maybe one of Mr.Crayfish cars, but I am not sure
I have tried to start the Server with deactivated Mr.Crayfishs Vehicle Mod, but no change, the Server still crashes with the same issue

I have added the Server Logs here from the 17. and 18. maybe you can see more

Hope you will have an idea to fix this some way

Best Regards

Inomutso

[Inomutso_20191218_Server_Log.zip](https://github.com/ldtteam/minecolonies/files/3980875/Inomutso_20191218_Server_Log.zip)

### PR DESCRIPTION
**Pull request by someaddons**
Closes #4156

# Changes proposed in this pull request:
Always converts vanilla paths now, instead of only on setPath.
Auto-dismounts our citizens when they try to path somewhere.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java [hunk 1]
```diff
@@ -262,7 +267,17 @@ public boolean setPath(@Nullable final Path path, final double speed)
...
+     * Converts the given path to a minecolonies path if needed.
+     *
+     * @param path given path
+     * @return resulting path
+     */
+    private Path convertPath(final Path path)
+    {
         final int pathLength = path.getCurrentPathLength();
         Path tempPath = null;
         if (pathLength > 0 && !(path.getPathPointFromIndex(0) instanceof PathPointExtended))
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java:283]: Why is there this check twice?

Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java:283]: its used in two places, pathfollow and setpath

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java:283]: Ah, almost skipped the convertPath up there.

**Review by marchermans — APPROVED** [review]
