### PR TITLE
fix 9175

### LINKED ISSUE #9120: [BUG] Farmer mudmaking is pretty buggy (inventory management)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1390-ALPHA

### Structurize Version

1.0.491-ALPHA

### Related Mods and their Versions

_No response_

### Current Behavior

Farmer takes bottles and dirt from racks but hasn't room for the full batch. They get stuck putting back bottles/taking them out, and not doing the crafting of the mud. If I clear out the farmer's inventory then they craft it fine

### Expected Behavior

Farmer to manage inventory better;
1. When doing crafting like mud, maybe put in stuff they don't need for the crafting into the racks temporarily to make more room
2. If the batch is big enough to be problematic, break it in half (iterate if needed) so inventory isn't a blocker

### Reproduction Steps

Start a build that requires X mud blocks, with 0 mud blocks in the colony inventories (and 0 empty bottles/water bottles for testing purposes.
Teach the farmer the mud recipe (1 dirt/1 water bottle)
Place the X water bottles in the farmer inventory

where X + 1 (for the dirt) + 1 (for the output mud) is greater than the available inventory in the farmer's inventory. In my case they had 20 slots free and the craft was for 21 mud, but you can also have them empty and do more, I suspect

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #9175: [BUG] Sawmill removes stick recipes when they get too cheap
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1433-ALPHA

### Structurize Version

1.19.2-1.0.491-ALPHA

### Related Mods and their Versions

Forge Version: 43.2.11
BlockUI Version: 1.19-0.0.69-ALPHA
Domum Ornamentum Version: 1.19-1.0.83-ALPHA

### Current Behavior

The recipe is removed when the Sawmill reduces the recipe cost of Item Frames and Armor Stands below 4 sticks, forcing the player to add the vanilla recipe again. Unsure if this applies to other stick-related recipes but these two are consistent and reproducible.

### Expected Behavior

Sawmill should be able to reduce the recipe cost of Item Frames and Armor Stands all the way down to 1 stick + 1 smooth stone slab/leather.

### Reproduction Steps

1. Teach the Sawmill the vanilla recipe for Item Frame/Armor Stand
2. Repeatedly craft these until their cost drops to 4 sticks + leather/smooth stone slab
3. Repeatedly craft again until the notification that the carpenter reduced the need for sticks for the recipe pops up
4. Sawmill no longer knows how to craft Item Frame/Armor Stand

### Logs

https://pastebin.com/KiwCNNyV

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #9175
Closes #9120
Closes #

# Changes proposed in this pull request:
- Fixes an issue with recipe sbeing improved beyong limit
- Makes crafters dump if they got unrelated stuff in their invs
-

Review please

### CODE REVIEW

**Review by someaddons — APPROVED** [review]

File: src/main/java/com/minecolonies/coremod/colony/buildings/modules/AbstractCraftingBuildingModule.java [hunk 1]
```diff
@@ -591,16 +591,20 @@ public void improveRecipe(IRecipeStorage recipe, int count, ICitizenData citizen
...
-                MessageUtils.format(RECIPE_IMPROVED + citizen.getRandom().nextInt(3),
-                    jobComponent,
-                    recipe.getPrimaryOutput().getHoverName(),
-                    reducedItem.getItemStack().getHoverName(),
-                    citizen.getName()
-                ).sendTo(building.getColony()).forAllPlayers();
+                final IToken<?> token = IColonyManager.getInstance().getRecipeManager().checkOrAddRecipe(storage);
+                if (isRecipeCompatibleWithCraftingModule(token))
+                {
+                    replaceRecipe(recipe.getToken(), IColonyManager.getInstance().getRecipeManager().checkOrAddRecipe(storage));
```
Comment (uecasm) [inline src/main/java/com/minecolonies/coremod/colony/buildings/modules/AbstractCraftingBuildingModule.java:597]: Shouldn't this just use `token` rather than calling `checkOrAddRecipe` again?  (Current will behave correctly but is inefficient.)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAICrafting.java [hunk 2]
```diff
@@ -189,6 +194,29 @@ protected IAIState getNextCraftingState()
...
+     * @param currentRecipeStorage the recipe to compare.
+     * @return true if so.
+     */
+    private boolean isPartOfRecipe(final ItemStack stack, final IRecipeStorage currentRecipeStorage)
+    {
+        if (ItemStackUtils.compareItemStacksIgnoreStackSize(stack, currentRecipeStorage.getPrimaryOutput()))
+        {
+            return true;
+        }
+
```
Comment (uecasm) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAICrafting.java:209]: What about required tools?  Or tools not required for this particular recipe but required for some other part of their job?  This seems like it might get triggered more often than perhaps is intended.
