### PR TITLE
Hotfix/d man fix

### LINKED ISSUE #1297: EMPTY WAREHOUSE SAYING ITS FULL
### Minecolonies version

minecolonies-universal-1.10.2-0.8.3171

### Expected behavior

Delivery man being able to use the new shelves

### Actual behaviour

When delivery man enters warehouse : he says its full or needs to be upgraded

### Steps to reproduce the problem

1. Build Warehouse and delivery man
2. Upgrade warehouse and delivery man to level 5
3. Delivery man will not use new shelve system in warehouse
4. I can put things on the shelf by hand by opening the GUI

I've attached my server startup log

[Serverstartup.txt](https://github.com/Minecolonies/minecolonies/files/1151139/Serverstartup.txt)

THIS IS A SCREENSHOT OF A SINGLE PLAYER WORLD WITH ONLY MINECOLONIES INSTALLED
screenshot

### PR DESCRIPTION
**Pull request by Asherslab**
Closes #1297 
# Changes proposed in this pull request:
- Fixes the D-Man saying "The warehouse is full, please upgrade or make space" 
- fixes it by registering the BlockMinecoloniesRack in "additionalinventories" =P
- repair warehouse should work to fix it =D

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1303/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by Raycoms** [comment]
Or wait @OrionDevelopment couldn't we just check if the tileEntity at the location has inventoryHandling capabilities?

**Comment by marvin-bitterlich** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1303/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 59 issues
* ![MAJOR][MAJOR] 29 major
* ![MINOR][MINOR] 29 minor
* ![INFO][INFO] 1 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/f8dbac0f4cb6824db8f981744096a02fa94942a7/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 36 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/f8dbac0f4cb6824db8f981744096a02fa94942a7/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): class "AbstractBuilding" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/f8dbac0f4cb6824db8f981744096a02fa94942a7/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/f8dbac0f4cb6824db8f981744096a02fa94942a7/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/f8dbac0f4cb6824db8f981744096a02fa94942a7/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/f8dbac0f4cb6824db8f981744096a02fa94942a7/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L122](https://github.com/Minecolonies/minecolonies/blob/f8dbac0f4cb6824db8f981744096a02fa94942a7/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L122): Remove this reference to "BuildingBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/f8dbac0f4cb6824db8f981744096a02fa94942a7/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/f8dbac0f4cb6824db8f981744096a02fa94942a7/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L124](https://github.com/Minecolonies/minecolonies/blob/f8dbac0f4cb6824db8f981744096a02fa94942a7/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L124): Remove this reference to "BuildingFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by marchermans** [comment]
@Raycoms let me check, theoretically yes. the TileEntity#hasCapability method does that.

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 1]
```diff
@@ -853,7 +853,7 @@ public final void markDirty()
      */
     public void registerBlockPosition(@NotNull Block block, @NotNull final BlockPos pos)
     {
-        if (block instanceof BlockContainer)
+        if (block instanceof BlockContainer || block instanceof BlockMinecoloniesRack)
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: If the block is already placed here, we should check the TE, it has a method hasCapabilty, which allows to check for IItemHandlers, regardless of block or mod.

This would in my humble opinion be the better solution (if we have the TE), if we donnot have the TE this is a good hotfix.

**Review by marchermans — DISMISSED** [review]

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java (hunk 1 above)
Comment (Asherslab) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: okay, sounds good, lemme see if i can get the TE =D

**Comment by marchermans** [comment]
@Raycoms @Asherslab check comments, their are better ways to do this if we have the TE already in the world, especially since our inventory handling methods already take care of this for us, we just need to all IItemHandlers to the list.

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java (hunk 1 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: Yeah that's what I meant, checking for the TileEntity capability would be the saver way to capture all kinds of chests

Comment (Asherslab) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: the only question is the Facing that i need...

**Comment by Asherslab** [comment]
~~I've already got most of it, i just need a way to get the facing... but i'm working on that =P~~

Actually i think i can just use null for facing =D

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java (hunk 1 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: what do you need the facing for?

Comment (marchermans) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: Ehm their is a method in the inventoryutils that gets you all of them (which is what we use to extract anyway). Call that, check if it returns an empty list

File: src/main/java/com/minecolonies/coremod/colony/buildings/BuildingBaker.java [hunk 2]
```diff
@@ -319,9 +319,9 @@ public void readFromNBT(@NotNull final NBTTagCompound compound)
     }
 
     @Override
-    public void registerBlockPosition(@NotNull final Block block, @NotNull final BlockPos pos)
+    public void registerBlockPosition(@NotNull final Block block, @NotNull final BlockPos pos, @NotNull final World world)
     {
-        super.registerBlockPosition(block, pos);
+        super.registerBlockPosition(block, pos,world);
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/colony/buildings/BuildingBaker.java]: white space after comma

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java [hunk 3]
```diff
@@ -520,7 +520,7 @@ public void connectBlockToBuildingIfNecessary(@NotNull Block block, @NotNull fin
 
         if (building != null)
         {
-            building.registerBlockPosition(block, pos);
+            building.registerBlockPosition(block, pos,world);
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java]: same whitespace here

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 4]
```diff
@@ -849,18 +849,25 @@ public final void markDirty()
      * register a block and position.
      *
      * @param block to be registered
-     * @param pos of the block
+     * @param pos   of the block
      */
-    public void registerBlockPosition(@NotNull Block block, @NotNull final BlockPos pos)
+    public void registerBlockPosition(@NotNull Block block, @NotNull final BlockPos pos, @NotNull final World world)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: MAJOR Remove this unused method parameter "block". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 5]
```diff
@@ -849,18 +849,25 @@ public final void markDirty()
...
     {
-        if (block instanceof BlockContainer)
+
+        TileEntity tile = world.getTileEntity(pos);
+
+        if (tile != null)
         {
-            addContainerPosition(pos);
+            if (tile.hasCapability(CapabilityItemHandler.ITEM_HANDLER_CAPABILITY, null))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: MAJOR Merge this if statement with the enclosing one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1066)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 69 issues
* ![MAJOR][MAJOR] 33 major
* ![MINOR][MINOR] 35 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/e16934f1e8a8e398f07272190111d3e3a58b594a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 34 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/e16934f1e8a8e398f07272190111d3e3a58b594a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): class "AbstractBuilding" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/e16934f1e8a8e398f07272190111d3e3a58b594a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/e16934f1e8a8e398f07272190111d3e3a58b594a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/e16934f1e8a8e398f07272190111d3e3a58b594a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/e16934f1e8a8e398f07272190111d3e3a58b594a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L122](https://github.com/Minecolonies/minecolonies/blob/e16934f1e8a8e398f07272190111d3e3a58b594a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L122): Remove this reference to "BuildingBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/e16934f1e8a8e398f07272190111d3e3a58b594a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/e16934f1e8a8e398f07272190111d3e3a58b594a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L124](https://github.com/Minecolonies/minecolonies/blob/e16934f1e8a8e398f07272190111d3e3a58b594a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L124): Remove this reference to "BuildingFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 6]
```diff
@@ -839,28 +839,32 @@ public void setBuildingLevel(final int level)
...
-     * register a block and position.
+     * register a TileEntity and position.
      *
-     * @param block to be registered
-     * @param pos of the block
+     * @param world the world the TileEntity is being registered in
+     * @param pos   of the block
      */
-    public void registerBlockPosition(@NotNull Block block, @NotNull final BlockPos pos)
+    public void registerBlockPosition(@NotNull final BlockPos pos, @NotNull final World world)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: MAJOR Remove this unused method parameter "block". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 68 issues
* ![MAJOR][MAJOR] 32 major
* ![MINOR][MINOR] 35 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/dbc648aba55472089f821117f6f3a70a78ff9036/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 34 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/dbc648aba55472089f821117f6f3a70a78ff9036/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): class "AbstractBuilding" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/dbc648aba55472089f821117f6f3a70a78ff9036/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/dbc648aba55472089f821117f6f3a70a78ff9036/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/dbc648aba55472089f821117f6f3a70a78ff9036/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/dbc648aba55472089f821117f6f3a70a78ff9036/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L122](https://github.com/Minecolonies/minecolonies/blob/dbc648aba55472089f821117f6f3a70a78ff9036/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L122): Remove this reference to "BuildingBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/dbc648aba55472089f821117f6f3a70a78ff9036/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/dbc648aba55472089f821117f6f3a70a78ff9036/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L124](https://github.com/Minecolonies/minecolonies/blob/dbc648aba55472089f821117f6f3a70a78ff9036/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L124): Remove this reference to "BuildingFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java (hunk 6 above)
Comment (Asherslab) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: uhh??? i did?? =P

**Comment by Raycoms** [comment]
:shipit:

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 7]
```diff
@@ -849,18 +849,23 @@ public final void markDirty()
...
+     * @param world the world to place the tileentity in
      */
-    public void registerBlockPosition(@NotNull Block block, @NotNull final BlockPos pos)
+    public void registerBlockPosition(@NotNull Block block, @NotNull final BlockPos pos, @NotNull final World world)
     {
-        if (block instanceof BlockContainer)
+
+        final TileEntity tile = world.getTileEntity(pos);
+
+        if (tile != null && tile.hasCapability(CapabilityItemHandler.ITEM_HANDLER_CAPABILITY, null))
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: Please do not do this. Use the inventoryutils method to get all itemhandlers in a te, then check for an empty list. This will break on a sided block.

**Review by marchermans — DISMISSED** [review]
This will not work for sided blocks.
Implement this properly once and for all please.

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 8]
```diff
@@ -849,18 +849,23 @@ public final void markDirty()
      * register a block and position.
      *
      * @param block to be registered
-     * @param pos of the block
+     * @param pos   of the block
+     * @param world the world to place the tileentity in
      */
-    public void registerBlockPosition(@NotNull Block block, @NotNull final BlockPos pos)
+    public void registerBlockPosition(@NotNull Block block, @NotNull final BlockPos pos, @NotNull final World world)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: MAJOR Remove this unused method parameter "block". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 68 issues
* ![MAJOR][MAJOR] 32 major
* ![MINOR][MINOR] 35 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/c886524b69a5c6f21e5915aea7b3c0ad8d8e9bb5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 34 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/c886524b69a5c6f21e5915aea7b3c0ad8d8e9bb5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): class "AbstractBuilding" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/c886524b69a5c6f21e5915aea7b3c0ad8d8e9bb5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/c886524b69a5c6f21e5915aea7b3c0ad8d8e9bb5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/c886524b69a5c6f21e5915aea7b3c0ad8d8e9bb5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/c886524b69a5c6f21e5915aea7b3c0ad8d8e9bb5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L122](https://github.com/Minecolonies/minecolonies/blob/c886524b69a5c6f21e5915aea7b3c0ad8d8e9bb5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L122): Remove this reference to "BuildingBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/c886524b69a5c6f21e5915aea7b3c0ad8d8e9bb5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/c886524b69a5c6f21e5915aea7b3c0ad8d8e9bb5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L124](https://github.com/Minecolonies/minecolonies/blob/c886524b69a5c6f21e5915aea7b3c0ad8d8e9bb5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L124): Remove this reference to "BuildingFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java (hunk 8 above)
Comment (Asherslab) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: Oh shut-it

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 9]
```diff
@@ -849,18 +848,22 @@ public final void markDirty()
...
     {
-        if (block instanceof BlockContainer)
+        final TileEntity tile = world.getTileEntity(pos);
+
+        if (tile != null && !InventoryUtils.getItemHandlersFromProvider(tile).isEmpty())
```
Comment (OrionDevelopment) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: This is correct.

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 68 issues
* ![MAJOR][MAJOR] 32 major
* ![MINOR][MINOR] 35 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L42](https://github.com/Minecolonies/minecolonies/blob/f1dcb245b0fca03f751c9c90e7c07b9df94cef3a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L42): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 34 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L42](https://github.com/Minecolonies/minecolonies/blob/f1dcb245b0fca03f751c9c90e7c07b9df94cef3a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L42): class "AbstractBuilding" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L119](https://github.com/Minecolonies/minecolonies/blob/f1dcb245b0fca03f751c9c90e7c07b9df94cef3a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L119): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L119](https://github.com/Minecolonies/minecolonies/blob/f1dcb245b0fca03f751c9c90e7c07b9df94cef3a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L119): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/f1dcb245b0fca03f751c9c90e7c07b9df94cef3a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/f1dcb245b0fca03f751c9c90e7c07b9df94cef3a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/f1dcb245b0fca03f751c9c90e7c07b9df94cef3a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L122](https://github.com/Minecolonies/minecolonies/blob/f1dcb245b0fca03f751c9c90e7c07b9df94cef3a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L122): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L122](https://github.com/Minecolonies/minecolonies/blob/f1dcb245b0fca03f751c9c90e7c07b9df94cef3a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L122): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/f1dcb245b0fca03f751c9c90e7c07b9df94cef3a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
