### PR TITLE
Zombie & displayfixes

### LINKED ISSUE #11029: Zombie Villagers disappear upon conversion
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

minecolonies-1.20.1-1.1.975-snapshot.jar

### Structurize Version

structurize-1.20.1-1.0.775-snapshot.jar

### Related Mods and their Versions

_No response_

### Current Behavior

Attempting to cure a zombie villager while within the chunks claimed by an active colony leads to them just disappearing at the end of their shaking animation. Curing a zombie villager outside the boundaries of a colony works as intended

### Expected Behavior

Zombie villager disappearing and normal villager appearing in their place

### Reproduction Steps

1. Find or zombify a villager
2. Douse them in weakness potion and force feed them a golden apple
3. Wait

### Logs

https://pastebin.com/SJES5LSy

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #11071: farmers and planter won't work
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.1065-1.21.1-snapshot

### Structurize Version

1.0.782-1.21.1-snapshot

### Related Mods and their Versions

NeoForge version: 21.1.194
Multi-Piston version: 1.2.57-1.21.1-snapshot
Towntalk version: 1.2.0
Domum Ornamentum version: 1.0.220-snapshot
UI Library Mod version: 1.0.205-1.21.1
JadeColonies version: 1.6.0
MineColonies for ComputerCraft version: 2.8.0

### Current Behavior

Neither the farmer nor planter will work at all. It is stuck in the farming cycle (currently in my world stuck on Harvest, Tilling, Harvest in my main farmer), same goes for planter except for recipes. Upon troubleshooting with the discord server they told me to open an issue. 

The planter issue I've been having for a while but the farmer recently started doing it (wanna say 2 snapshots ago?)

### Expected Behavior

Farmer proceeds in the farming cycles instead of being stuck for weeks on end.

### Reproduction Steps

Hire new farmer.
Give them a field.
Set up the field and assign it in the GUI
Farmer is in WORKING state, and the 2 sub states are START_WORKING

### Logs

https://gist.github.com/ShinySSB/9e80e1f96f976720708503a7e7e1a6df

### Anything else?

Image

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #11076: Recruitement items has non-stackable items requiring more than player inventory space
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

minecolonies-1.20.1-1.1.976.jar (custom branch from this version)

### Structurize Version

structurize-1.20.1-1.0.772-snapshot.jar

### Related Mods and their Versions

_No response_

### Current Behavior

For a level 1 tavern building, the recruitment cost of a visitor resulted in a 42 beetroot soup need. As the item doesn't stack, I cannot fit more than (4x7) 28 beetroot soup in my inventory to recruit the visitor.

From the source code file, the calculation seems to be correct for stackable items.
~15 multiplied by rarity of (2+1)

### Expected Behavior

Non-stackable items have their cost somewhat divided by ~5 maybe, or they are removed from the recruitment json list or replaced by some other stackable items.

### Reproduction Steps

Review the visitors recruitment costs on a tavern level 1.

### Logs

https://pastebin.com/majkAbXQ

### Anything else?

Image

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #11071
Closes #11076
Closes #11029

# Changes proposed in this pull request
- Fix farmer/planter not working, improve field assignment
- Fix zombie village disappearing on conversion
- Fix out of range item requests from visitors

## Testing
- [x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/core/colony/buildings/modules/TavernBuildingModule.java [hunk 1]
```diff
@@ -193,7 +193,7 @@ public IVisitorData spawnVisitor()
         newCitizen.getCitizenSkillHandler().init(cost.recruitLevel());
 
         final ItemStack recruitCostItem = cost.recruitItem().copy();
-        recruitCostItem.setCount(recruitCostItem.getCount() + MathUtils.RANDOM.nextInt(3));
+        recruitCostItem.setCount(Math.min(cost.recruitItem().getMaxStackSize(), recruitCostItem.getCount() + MathUtils.RANDOM.nextInt(3)));
```
Comment (someaddons) [inline src/main/java/com/minecolonies/core/colony/buildings/modules/TavernBuildingModule.java:196]: I think we should also in addition by default not include nonstackables in our cost

**Review by someaddons — APPROVED** [review]
