### PR TITLE
Fix townhall placement and lumberjack issues

### LINKED ISSUE #3865: [1.14.4] Lumberjack's sapling filter has no effect
### Minecolonies version

Version: minecolonies-0.10.359-ALPHA-universal (1.14.4)

### Expected behavior

Toggling the handling of specific saplings off should prevent the lumberjack from working with those types of saplings.

### Actual behaviour

Toggling the lumberjack handling for specific saplings doesn't prevent said lumberjack to plant whatever sapling is present in its inventory.

### Steps to reproduce the problem

1. Tasklist of the lumberjack hut
2. Toggle off a type of sapling
3. Give said sapling to lumberjack
4. Wait for lumberjack to chop down tree and replant

### PR DESCRIPTION
**Pull request by someaddons**
Closes #3865 

# Changes proposed in this pull request:
- fix lumberjack's option to turn off/on trees to chop.
- re-Added clony deletion/abandon options on placing a 2. TH

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/permissions/Permissions.java [hunk 1]
```diff
@@ -474,6 +474,22 @@ public boolean setOwner(final PlayerEntity player)
...
+     * Change the owner of a colony to [abandoned]
+     */
+    @Override
+    public void setOwnerAbandoned()
+    {
+        players.remove(getOwner());
+
+        ownerName = "[abandoned]";
+        ownerUUID = new UUID(235123534,131231234);
+
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/colony/permissions/Permissions.java:487]: There is a UUID function to get a random UUID

Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/colony/permissions/Permissions.java:487]: oh that one is indeed nicer, changed that
