### PR TITLE
Fixes

### LINKED ISSUE #9284: [BUG] Claimed message showing three times
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1-1.1.28

### Structurize Version

1.0.590

### Related Mods and their Versions

Forge: 47.1.43  
BlockUI: 0.0.84
Domum Ornamentum: 1.0.110

### Current Behavior

If I click "Reactivate" on an abandoned structure the claimed message is shown three times.

### Expected Behavior

To show the message only once.

### Reproduction Steps

1. Place a town hall near an abandoned colony
2. Enter one of the abandoned buildings
3. Right-click on their controller block and click Reactivate

### Logs

N/A

### Anything else?

P.S. I am not using the alpha version as it is not installed by the CurseForge client automatically - manual version selection tends to be funky! Apologies if this has already been addressed in alpha builds of the mod.

### LINKED ISSUE #9326: [BUG] <Colony Lost Dimension Info>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.1.96-BETA.jar

### Structurize Version

1.19.2-1.0.629-RELEASE.jar

### Related Mods and their Versions

1. Forge version: 43.2.21 (43.2.12 in server, latest version available)
2. Block UI Version: 1.19-0.0.69-ALPHA.jar
3. Domum Ornamentum version: 1.19-1.0.127-BETA-universal.jar
4. JEI version: 1.19.2-forge-11.6.0.1017.jar

### Reproduction Steps

This part I am very unsure of, no one can tell me what exactly happened for the steps to be reproduced here.

### Logs

https://gist.github.com/DSMister/c3fe3095b4122d166d65ac6c9a7adba9

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by someaddons**
Closes #9326
Closes #9284

# Changes proposed in this pull request:
- Fix claim message displaying too often
- Fix builder resource list fighting with network data
- Add error message when a resource could not be inserted to a builder
- Fix crash with entities trying to register with a colony before its world is loaded

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 1]
```diff
@@ -306,7 +306,10 @@ public void onPlayerEnterNearby(final Player player)
     @Override
     public void onPlacement()
     {
-        ChunkDataHelper.claimBuildingChunks(colony, true, getPosition(), getClaimRadius(getBuildingLevel()), getCorners());
+        if (getBuildingLevel() == 0)
+        {
+            ChunkDataHelper.claimBuildingChunks(colony, true, getPosition(), getClaimRadius(getBuildingLevel()), getCorners());
```
Comment (MotionlessTrain) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java:311]: Would this properly expand the claim area when a building gets upgraded, or when a building gets pasted in at a higher level than level 0?

**Review by Raycoms — APPROVED** [review]

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java (hunk 1 above)
Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java:311]: ye that still triggers upgrades on the building
