### PR TITLE
Fix/farmer

### LINKED ISSUE #235: Farm more things
Farmer should be able to farm additional plant types.

IE. Pumpkins, melons, netherwart.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38776180-farm-more-things?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #301: Farmer not properly working
### Minecolonies version

version X.X.1784

### Expected behavior

- when farming would replant seeds

### Actual behaviour

- when harvesting, the field is harvested, but the farmlandblock is replaced by dirt/grass
- farmers won't use hoe to regenerate it to farmland

### Steps to reproduce the problem

1. came after i uploaded that version

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39568288-farmer-not-properly-working?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #303: [Suggestion] Various observations made while setting up a farm
Hi,

I'm experimenting with 0.4.1784 today and I've a few suggestions relating to construction. 

Firstly, overall, I think it's really cool! I really enjoy the building system, providing materials, some custom NPCs, nicely designed buildings and so forth. Thank you very much for your hard work and generosity in sharing it with us. I think it will be a valuable and loved addition to our modpack.

1. The ghost images for decorations and huts (fountains, fields, etc.) are full opacity which makes it hard to see where things are going to be. I suggest dropping the opacity to 40% or so, to make it easier to see the terrain through the planned build.

2. I built 3 fields and then placed a farm block and told it to build. Apparently I placed the block too close to my farm because my builder proceeded to demolish parts of the fields she just worked so hard to make! Again, a transparent ghost image of the planned build, and a confirmation button, would've helped avoid this. Perhaps as a result of this, my builder is currently just walking back and forth between the site and the workshop with no forward progress.

3. Builder is ignoring construction materials that have been placed in the farm block inventory. I can see that the farm block is intended to hold seeds, but it would be helpful if it could also help the builder, and the builder check that one before she returns to the workshop.

4. If possible, have a Bill of Materials visible in the workshop and/or the current project box to indicate what the builder will need to complete the project. Ideally floating text in the way that RFTools machines display info. That way the player can get busy, rather than loitering around waiting to be told what to fetch next.

5. "Field" should be renamed to "Scarecrow". Farmer dialog is "Please select a type of seed to grow in the scarecrow. Looks like these two have had their names switched!

6. Builder with her hat is taller than a 2 block doorway!

7. Builder's dialog is very depressing :( Doesn't she know that it's her own livelihood that she's contributing to?

8. Fence gates on fields are north facing. Gap in fence of the farm is facing south. Perhaps check and reorient these depending on where they are in relation to each other?

9. Builder stands about 12 blocks away from the project she's building. Would be better if she stood closer. Perhaps 4 or 5 blocks.

10. It would be nice if we could rename our citizens.

11. My builder just completed farmer3. The last things she did was to place some buttons and then remove the row of planks they were sitting on. Now I have a couple of buttons floating in mid-air!
_(edit: floating buttons were no longer an issue by the time I'd upgraded to level 5, but definitely existed at the completion of level 3.)_

12. My farmer has planted pumpkin in the same way you'd plant wheat. i.e. on every available piece of farmland, leaving no room for the pumpkins to grow. Also, she's breaking existing pumpkin plants and planting new pumpkin seeds on the same patch.

13. I feel the farmer should do her best to put any items she doesn't need for this project in the workshop. That would save her a lot of running back and forth, I suspect!

14. Farm building has some oddly-placed orange wool blocks. They're not connected to anything.
_(edit: Orange wool blocks: http://i.imgur.com/hfUMTlX.png )_

15. Possible duping bug. I gave my builder just one cauldron for the farm building yet so far I've removed one from the workshop, one from the farm chest and one from her inventory. 
_(edit: definite dupe bug. I gave my farmer one diamond hoe. She still has that one (with some damage) but the farm chest now has two unused ones in it.)_

16. When the builder calls for a particular item, it would be helpful if she'd specify the desired quantity.

17. At the moment, I see the builder wand places the structure at the same rotation every time. The expectation set by many other mods is that the orientation is based on the direction the player is facing. I suggest for "intuitive" control, that you make it work in this way.

18. What are "birch blocks with tennis rackets" under a proposed build? Is that where the existing terrain goes? If so, I suggest you just leave those out as it's misleading. I was expecting the builder to place some blocks there. Players should be able to notice if they've positioned it such that they're floating. 

19. When the blocks of a proposed build are going to require existing blocks be removed, I suggest a red wireframe around those blocks, to indicate a conflict. At the moment it just shows the new block in its proper position and it's not clear that destruction will happen.

That's all I have for the moment. I hope you like this kind of feedback. If you'd prefer to go your own way, or to have separate issues for each idea, please let me know. I can shut up or post multiple issues as you desire :)

Cheers!

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39578230-suggestion-various-observations-made-while-setting-up-a-farm?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #304: [Suggestion] Farmer
I know Farmers are still WIP, but I propose having them harvest plants with a right-click (seeing as that's a Vanilla mechanic now) rather than breaking the plant and replanting the crop.  Not only will this lead to more effective farms (due to inconsistent seed drop rates), but it would improve the overall mod compatibility (Pam's Harvestcraft crops drop vegetables rather than seeds, so no replanting is going to happen).

Thanks for your time and hard work.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39588155-suggestion-farmer?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #633: farmer hangs on harvestcraft seeds as a tool
### Minecolonies version

version X.X.XXXX or curse 0.6.2837

### Expected behavior

- XXX

### Actual behaviour

[Server] Server thread/INFO [minecolonies]: ForgeHook not in sync with EfficientTool for Block{minecraft:tallgrass} and 13xitem.seeds@0
[Server] Server thread/INFO [minecolonies]: ForgeHook not in sync with EfficientTool for Block{minecraft:red_flower} and 16xitem.seeds@0
doing that over and over
### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/42204813-farmer-hangs-on-harvestcraft-seeds-as-a-tool?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #235
Closes #301
Closes #303 
Closes #304 
Closes #633 

# Changes proposed in this pull request:
- Allows pumpkins and melons
- Fixes some problems
- Overhaul his asynch requesting
- Fix pam support

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/farmer/EntityAIWorkFarmer.java [hunk 1]
```diff
@@ -124,14 +125,12 @@ private AIState startWorkingAtOwnBuilding()
     private AIState prepareForFarming()
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/farmer/EntityAIWorkFarmer.java:128]: MAJOR Reduce the number of returns of this method 7, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/farmer/EntityAIWorkFarmer.java [hunk 2]
```diff
@@ -471,112 +363,132 @@ private boolean shouldHarvest(@NotNull final BlockPos position)
      * This (re)initializes a field.
      * Checks the block above to see if it is a plant, if so, breaks it. Then tills.
      */
-    private AIState initialize()
+    private AIState workAtField()
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/farmer/EntityAIWorkFarmer.java:369]: MAJOR Reduce the number of returns of this method 8, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 41 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 34 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L39](https://github.com/Minecolonies/minecolonies/blob/b85773173700332b237f372c43a5443c3cf7c8c7/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L39): class "AbstractEntityAIBasic" has 56 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L204](https://github.com/Minecolonies/minecolonies/blob/b85773173700332b237f372c43a5443c3cf7c8c7/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L204): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L532](https://github.com/Minecolonies/minecolonies/blob/b85773173700332b237f372c43a5443c3cf7c8c7/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L532): Remove this unused private "requestWithoutSpam" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L983](https://github.com/Minecolonies/minecolonies/blob/b85773173700332b237f372c43a5443c3cf7c8c7/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L983): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1032](https://github.com/Minecolonies/minecolonies/blob/b85773173700332b237f372c43a5443c3cf7c8c7/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1032): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/b85773173700332b237f372c43a5443c3cf7c8c7/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/b85773173700332b237f372c43a5443c3cf7c8c7/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/b85773173700332b237f372c43a5443c3cf7c8c7/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/b85773173700332b237f372c43a5443c3cf7c8c7/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/b85773173700332b237f372c43a5443c3cf7c8c7/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 41 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 34 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L39](https://github.com/Minecolonies/minecolonies/blob/047ec96c61ca490e705fa436dd994f3294d6a71b/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L39): class "AbstractEntityAIBasic" has 56 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L204](https://github.com/Minecolonies/minecolonies/blob/047ec96c61ca490e705fa436dd994f3294d6a71b/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L204): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L532](https://github.com/Minecolonies/minecolonies/blob/047ec96c61ca490e705fa436dd994f3294d6a71b/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L532): Remove this unused private "requestWithoutSpam" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L983](https://github.com/Minecolonies/minecolonies/blob/047ec96c61ca490e705fa436dd994f3294d6a71b/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L983): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1032](https://github.com/Minecolonies/minecolonies/blob/047ec96c61ca490e705fa436dd994f3294d6a71b/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1032): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/047ec96c61ca490e705fa436dd994f3294d6a71b/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/047ec96c61ca490e705fa436dd994f3294d6a71b/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/047ec96c61ca490e705fa436dd994f3294d6a71b/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/047ec96c61ca490e705fa436dd994f3294d6a71b/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/047ec96c61ca490e705fa436dd994f3294d6a71b/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 41 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 34 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L39](https://github.com/Minecolonies/minecolonies/blob/1b3260f7a6125fd1506f58ee339bd94166cc27f5/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L39): class "AbstractEntityAIBasic" has 56 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L204](https://github.com/Minecolonies/minecolonies/blob/1b3260f7a6125fd1506f58ee339bd94166cc27f5/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L204): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L532](https://github.com/Minecolonies/minecolonies/blob/1b3260f7a6125fd1506f58ee339bd94166cc27f5/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L532): Remove this unused private "requestWithoutSpam" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L983](https://github.com/Minecolonies/minecolonies/blob/1b3260f7a6125fd1506f58ee339bd94166cc27f5/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L983): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1032](https://github.com/Minecolonies/minecolonies/blob/1b3260f7a6125fd1506f58ee339bd94166cc27f5/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1032): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/1b3260f7a6125fd1506f58ee339bd94166cc27f5/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/1b3260f7a6125fd1506f58ee339bd94166cc27f5/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/1b3260f7a6125fd1506f58ee339bd94166cc27f5/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/1b3260f7a6125fd1506f58ee339bd94166cc27f5/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/1b3260f7a6125fd1506f58ee339bd94166cc27f5/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 37 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 30 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L39](https://github.com/Minecolonies/minecolonies/blob/0f082d23fb1cd6276d9801637f7f00bcc5f2a778/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L39): class "AbstractEntityAIBasic" has 56 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L204](https://github.com/Minecolonies/minecolonies/blob/0f082d23fb1cd6276d9801637f7f00bcc5f2a778/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L204): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L532](https://github.com/Minecolonies/minecolonies/blob/0f082d23fb1cd6276d9801637f7f00bcc5f2a778/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L532): Remove this unused private "requestWithoutSpam" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L983](https://github.com/Minecolonies/minecolonies/blob/0f082d23fb1cd6276d9801637f7f00bcc5f2a778/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L983): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1032](https://github.com/Minecolonies/minecolonies/blob/0f082d23fb1cd6276d9801637f7f00bcc5f2a778/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1032): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/0f082d23fb1cd6276d9801637f7f00bcc5f2a778/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/0f082d23fb1cd6276d9801637f7f00bcc5f2a778/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/0f082d23fb1cd6276d9801637f7f00bcc5f2a778/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/0f082d23fb1cd6276d9801637f7f00bcc5f2a778/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/0f082d23fb1cd6276d9801637f7f00bcc5f2a778/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 37 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 30 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L39](https://github.com/Minecolonies/minecolonies/blob/25c6ab70c20c49e7f83ea9c06180e7db52cc3aae/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L39): class "AbstractEntityAIBasic" has 56 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L204](https://github.com/Minecolonies/minecolonies/blob/25c6ab70c20c49e7f83ea9c06180e7db52cc3aae/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L204): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L532](https://github.com/Minecolonies/minecolonies/blob/25c6ab70c20c49e7f83ea9c06180e7db52cc3aae/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L532): Remove this unused private "requestWithoutSpam" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L983](https://github.com/Minecolonies/minecolonies/blob/25c6ab70c20c49e7f83ea9c06180e7db52cc3aae/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L983): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1032](https://github.com/Minecolonies/minecolonies/blob/25c6ab70c20c49e7f83ea9c06180e7db52cc3aae/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1032): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/25c6ab70c20c49e7f83ea9c06180e7db52cc3aae/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/25c6ab70c20c49e7f83ea9c06180e7db52cc3aae/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/25c6ab70c20c49e7f83ea9c06180e7db52cc3aae/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/25c6ab70c20c49e7f83ea9c06180e7db52cc3aae/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/25c6ab70c20c49e7f83ea9c06180e7db52cc3aae/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 37 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 30 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L39](https://github.com/Minecolonies/minecolonies/blob/a5ee5983b7d95af000d9ae20839707295a0b05a8/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L39): class "AbstractEntityAIBasic" has 56 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L204](https://github.com/Minecolonies/minecolonies/blob/a5ee5983b7d95af000d9ae20839707295a0b05a8/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L204): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L532](https://github.com/Minecolonies/minecolonies/blob/a5ee5983b7d95af000d9ae20839707295a0b05a8/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L532): Remove this unused private "requestWithoutSpam" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L983](https://github.com/Minecolonies/minecolonies/blob/a5ee5983b7d95af000d9ae20839707295a0b05a8/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L983): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1032](https://github.com/Minecolonies/minecolonies/blob/a5ee5983b7d95af000d9ae20839707295a0b05a8/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1032): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/a5ee5983b7d95af000d9ae20839707295a0b05a8/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/a5ee5983b7d95af000d9ae20839707295a0b05a8/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/a5ee5983b7d95af000d9ae20839707295a0b05a8/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/a5ee5983b7d95af000d9ae20839707295a0b05a8/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/a5ee5983b7d95af000d9ae20839707295a0b05a8/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Review by xavierh — APPROVED** [review]

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 37 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 30 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L39](https://github.com/Minecolonies/minecolonies/blob/6b51db13bebfefecc760114ceb03f93f4de86764/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L39): class "AbstractEntityAIBasic" has 56 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L204](https://github.com/Minecolonies/minecolonies/blob/6b51db13bebfefecc760114ceb03f93f4de86764/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L204): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L532](https://github.com/Minecolonies/minecolonies/blob/6b51db13bebfefecc760114ceb03f93f4de86764/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L532): Remove this unused private "requestWithoutSpam" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L983](https://github.com/Minecolonies/minecolonies/blob/6b51db13bebfefecc760114ceb03f93f4de86764/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L983): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1032](https://github.com/Minecolonies/minecolonies/blob/6b51db13bebfefecc760114ceb03f93f4de86764/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1032): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/6b51db13bebfefecc760114ceb03f93f4de86764/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/6b51db13bebfefecc760114ceb03f93f4de86764/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/6b51db13bebfefecc760114ceb03f93f4de86764/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/6b51db13bebfefecc760114ceb03f93f4de86764/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/6b51db13bebfefecc760114ceb03f93f4de86764/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 37 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 30 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L39](https://github.com/Minecolonies/minecolonies/blob/707b22bae7684ed82c4ed6474a8cf71f71be4087/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L39): class "AbstractEntityAIBasic" has 56 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L204](https://github.com/Minecolonies/minecolonies/blob/707b22bae7684ed82c4ed6474a8cf71f71be4087/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L204): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L532](https://github.com/Minecolonies/minecolonies/blob/707b22bae7684ed82c4ed6474a8cf71f71be4087/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L532): Remove this unused private "requestWithoutSpam" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L983](https://github.com/Minecolonies/minecolonies/blob/707b22bae7684ed82c4ed6474a8cf71f71be4087/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L983): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1032](https://github.com/Minecolonies/minecolonies/blob/707b22bae7684ed82c4ed6474a8cf71f71be4087/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1032): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/707b22bae7684ed82c4ed6474a8cf71f71be4087/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/707b22bae7684ed82c4ed6474a8cf71f71be4087/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/707b22bae7684ed82c4ed6474a8cf71f71be4087/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/707b22bae7684ed82c4ed6474a8cf71f71be4087/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/707b22bae7684ed82c4ed6474a8cf71f71be4087/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Review by marchermans — APPROVED** [review]
