### PR TITLE
Fix gate tooltip

### LINKED ISSUE #9871: [BUG] Gate Tooltip outdated
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.515-BETA

### Structurize Version

1.20.1-1.07.0.712

### Related Mods and their Versions

ATM9 0.2.54

### Current Behavior

Wooden Gate and Iron gate tooltip indicates max size id 5x4. 

Gates are not limited to 5x4.

### Expected Behavior

Expected gate to be limited to 5x4

### Reproduction Steps

Place down gate with inventory gate count > 20. Gate works. 
image

### Logs

none.

### Anything else?

image

Lady Shatana Style: Cavern Megahall. Townhall building.

### PR DESCRIPTION
**Pull request by uecasm**
Closes #9871

# Changes proposed in this pull request:
- Makes the tooltip for the gates use the correct size limits.

[x] Yes I tested this before submitting it.
[ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/api/blocks/decorative/AbstractBlockGate.java [hunk 1]
```diff
@@ -83,6 +83,16 @@ public AbstractBlockGate(final String name, final float hardness, final int maxW
         this.hardness = hardness;
     }
 
+    public int getMaxWidth()
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/api/blocks/decorative/AbstractBlockGate.java:86]: no javadoc?

Comment (uecasm) [reply src/main/java/com/minecolonies/api/blocks/decorative/AbstractBlockGate.java:86]: I thought about it, but getters seemed sufficiently trivial.

**Review by someaddons — APPROVED** [review]
