### PR TITLE
Dynamic tree compatibility

### LINKED ISSUE #2316: [mod compatiblity] When Dynamic trees is present, lumberjack fails
### Minecolonies version

1.12.2-0.8.7719

### Expected behavior

- expect lumberjack to collect wood from dynamic tree

### Actual behaviour

- lumberjack never collects the wood

### Steps to reproduce the problem

1. install dynamic tree mod
2. make a new world
3. make a saw mill
4. watch the lumberjack struggle to make wood because the tree grows against him
5. Profit

### Suggestion
Lumber jack needs detect the tree type and if it is a dynamic tree, switch to chopping the bottom log block, at which point the dynamic tree completely falls apart and the wood can be collected.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/56163168-mod-compatiblity-when-dynamic-trees-is-present-lumberjack-fails?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by someaddons**
Closes #2316 

Adds dynamic tree compatibility to the lumberjack.:
- Falling tree dmg immunity(new dynamic tree feature)
- Limiting tree search interval(performance)
- Adding custom blockbreak actions
- Fells dynamic trees(except cactus)

Review please

### CODE REVIEW

File: src/api/java/com/minecolonies/api/compatibility/dynamictrees/DynamicTreeCompat.java [hunk 1]
```diff
@@ -0,0 +1,277 @@
...
+        {
+            final IBlockState curBlockState = world.getBlockState(blockToBreak);
+            @Nullable final Block curBlock = curBlockState.getBlock();
+
+            if (world.getMinecraftServer() == null)
+            {
+                Log.getLogger().error("Minecolonies:DynamicTreeCompat unexpected null while trying to get World");
+                return;
+            }
+            final FakePlayer fake =
```
Comment (Raycoms) [inline src/api/java/com/minecolonies/api/compatibility/dynamictrees/DynamicTreeCompat.java]: Can't we create it static in this class? Maybe even something like "if not null create it, else use it"

Comment (someaddons) [reply src/api/java/com/minecolonies/api/compatibility/dynamictrees/DynamicTreeCompat.java]: done 👍

**Review by marchermans — DISMISSED** [review]

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/3036/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)
