### PR TITLE
Port1.12/fix barbarian spawning

### LINKED ISSUE #1481: crash while exploring on server(1.12.1-2485)
### Minecolonies version

minecolonies-universal-1.12.1-0.8.4026
### Expected behavior

-go exploring and not crash

### Actual behaviour

crashed me back to desktop

### Steps to reproduce the problem

1. have version listed above with forge 1.12.1-2485
2. go explore on server 
3. crash back to desktop
4. Profit

crash report: http://puu.sh/xJFRP/ad9b15dacd.txt

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #1481 

# Changes proposed in this pull request:
- Ports of previous fixes + forge version dump.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 1]
```diff
@@ -41,7 +43,12 @@
 
 /**
  * Base building class, has all the foundation for what a building stores and does.
+ *
+ * We suppress the warning which warns you about referencing child classes in the parent because that's how we register the instances of the childClasses
+ * to their views and blocks.
+ *
  */
+@SuppressWarnings("squid:S2390")
 public abstract class AbstractBuilding
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java:52]: MAJOR Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 37 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
MAJOR class "AbstractBuilding" has 64 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)

File: src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java [hunk 2]
```diff
@@ -213,14 +223,15 @@ public void neighborChanged(final IBlockState state, final World worldIn, final
...
+     * @deprecated but we still need it.
      * @param world   The current world
      * @param pos     Block position in world
      * @param state   Current state
      * @param fortune Breakers fortune level
      * @return A ArrayList containing all items this block drops
      */
     @Override
+    @Deprecated
     public List<ItemStack> getDrops(final IBlockAccess world, final BlockPos pos, final IBlockState state, final int fortune)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java:235]: INFO Do not forget to remove this deprecated code someday. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1133)

File: src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java [hunk 3]
```diff
@@ -192,7 +192,17 @@ public int getMetaFromState(@NotNull final IBlockState state)
...
+     * @deprecated but we definitely need it.
+     * @param state the state.
+     * @param worldIn the world.
+     * @param pos the pos.
+     * @param blockIn the block.
+     * @param fromPos the changed ps.
+     */
     @Override
+    @Deprecated
     public void neighborChanged(final IBlockState state, final World worldIn, final BlockPos pos, final Block blockIn, final BlockPos fromPos)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java:206]: INFO Do not forget to remove this deprecated code someday. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1133)

File: src/main/java/com/minecolonies/coremod/util/ColonyUtils.java [hunk 4]
```diff
@@ -44,4 +48,28 @@ public static boolean hasNewSubscribers(@NotNull final Set<EntityPlayerMP> oldSu
...
+    /**
+     * Calculated the corner of a building.
+     * @param pos the central position.
+     * @param world the world.
+     * @param structureName the name of the structure (resource location).
+     * @param rotation the rotation.
+     * @param isMirrored if its mirrored.
+     * @return a tuple with the required corners.
+     */
+    public static Tuple<Tuple<Integer, Integer>, Tuple<Integer, Integer>> calculateCorners(
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/util/ColonyUtils.java:61]: MAJOR Provide multiple methods instead of using "isMirrored" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)

File: src/main/java/com/minecolonies/coremod/blocks/BlockHutBarracksTower.java [hunk 5]
```diff
@@ -32,14 +32,15 @@ public String getName()
...
+     * @deprecated but we still need it.
      * @param world   The current world
      * @param pos     Block position in world
      * @param state   Current state
      * @param fortune Breakers fortune level
      * @return A ArrayList containing all items this block drops
      */
     @Override
+    @Deprecated
     public List<ItemStack> getDrops(final IBlockAccess world, final BlockPos pos, final IBlockState state, final int fortune)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockHutBarracksTower.java:44]: INFO Do not forget to remove this deprecated code someday. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1133)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 168 issues
* ![MAJOR][MAJOR] 91 major
* ![MINOR][MINOR] 60 minor
* ![INFO][INFO] 17 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [BlockMinecoloniesRack.java#L129](https://github.com/Minecolonies/minecolonies/blob/f7b6fb5b9166db21522034dd2fcc44d11977c80a/src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java#L129): Reduce the number of returns of this method 7, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [BlockMinecoloniesRack.java#L129](https://github.com/Minecolonies/minecolonies/blob/f7b6fb5b9166db21522034dd2fcc44d11977c80a/src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java#L129): Add the missing @Deprecated annotation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMissingDeprecatedCheck)
1. ![MAJOR][MAJOR] [BlockMinecoloniesRack.java#L412](https://github.com/Minecolonies/minecolonies/blob/f7b6fb5b9166db21522034dd2fcc44d11977c80a/src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java#L412): Reduce this class from 51 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/f7b6fb5b9166db21522034dd2fcc44d11977c80a/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.343 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L55](https://github.com/Minecolonies/minecolonies/blob/f7b6fb5b9166db21522034dd2fcc44d11977c80a/src/main/java/com/minecolonies/coremod/colony/Colony.java#L55): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 49 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L55](https://github.com/Minecolonies/minecolonies/blob/f7b6fb5b9166db21522034dd2fcc44d11977c80a/src/main/java/com/minecolonies/coremod/colony/Colony.java#L55): class "Colony" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L230](https://github.com/Minecolonies/minecolonies/blob/f7b6fb5b9166db21522034dd2fcc44d11977c80a/src/main/java/com/minecolonies/coremod/colony/Colony.java#L230): Assign this magic number 5 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L355](https://github.com/Minecolonies/minecolonies/blob/f7b6fb5b9166db21522034dd2fcc44d11977c80a/src/main/java/com/minecolonies/coremod/colony/Colony.java#L355): Remove this useless assignment to local variable "achievementKey". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [Colony.java#L514](https://github.com/Minecolonies/minecolonies/blob/f7b6fb5b9166db21522034dd2fcc44d11977c80a/src/main/java/com/minecolonies/coremod/colony/Colony.java#L514): Remove this useless assignment to local variable "achievementCompound". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [Colony.java#L635](https://github.com/Minecolonies/minecolonies/blob/f7b6fb5b9166db21522034dd2fcc44d11977c80a/src/main/java/com/minecolonies/coremod/colony/Colony.java#L635): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
