### PR TITLE
Fix/jei fake level

### LINKED ISSUE #10486: Recipes crafted by workers at JEI are not displayed.
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.813-1.21.1-snapshot

### Structurize Version

1.0.755-1.21.1

### Related Mods and their Versions

1. blockui-1.0.192-1.21.1-snapshot.jar
2. domum_ornamentum-1.0.204-1.21.1-snapshot.jar
3. jei-1.21.1-neoforge-19.21.0.247.jar
4. multipiston-1.2.51-1.21.1-snapshot.jar
5. towntalk-1.2.0.jar

### Current Behavior

Recipes using Minecolonies functions are not displayed, but if they can be crafted on a Crafting Table, etc., they are displayed as only thier recipes.
For example, recipes for carpenters to process wood, bread to make in the bakery, etc.

### Expected Behavior

At least as of the Minecolonies-1.1.802-1.21.1-snapshot version the recipe was displayed correctly

### Reproduction Steps

1. Open inventory
2. Check JEI recipe
3. Left or Right clicking Minecolonies recipe

### Logs

N/A

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by uecasm**
Closes #10486

# Changes proposed in this pull request
- Fixes missing JEI pages.
- Also fixes missing JEI tooltips.

## Testing
- [x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please (do not port)

### CODE REVIEW

File: src/main/java/com/minecolonies/core/compatibility/jei/JobBasedRecipeCategory.java [hunk 1]
```diff
@@ -285,7 +286,8 @@ public InfoBlock(final String text, final String tip, final Rect2i bounds)
     @NotNull
     private static EntityCitizen createCitizenWithJob(@NotNull final IJob<?> job)
     {
-        final EntityCitizen citizen = new EntityCitizen(ModEntities.CITIZEN, FAKE_LEVEL);
+        final FakeLevel level = new SingleBlockFakeLevel(Minecraft.getInstance().level);
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/core/compatibility/jei/JobBasedRecipeCategory.java:289]: couldn't we "static cache" this?

Comment (uecasm) [reply src/main/java/com/minecolonies/core/compatibility/jei/JobBasedRecipeCategory.java:289]: We could, and probably should, but I was going to do that in a separate PR because 1.20 should do something similar.

Comment (Raycoms) [reply src/main/java/com/minecolonies/core/compatibility/jei/JobBasedRecipeCategory.java:289]: kk
