### PR TITLE
move soundsource, prob fixes 10644

### LINKED ISSUE #10644: Raid alert sound not playing in 1.21
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [x] Multi Player

### Minecraft Version

1.21

### MineColonies Version

minecolonies-1.1.873-1.21.1-snapshot

### Structurize Version

structurize-1.0.758-1.21.1-snapshot

### Related Mods and their Versions

_No response_

### Current Behavior

When a colony get raided, the alert sound doesn't play in 1.21

Image

### Expected Behavior

Hear the raid sounds

### Reproduction Steps

Get raided

### Logs

none

### Anything else?

Sam asked me to hub this

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #10646: Bugs with concrete mixer
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.875

### Structurize Version

1.0.758

### Related Mods and their Versions

_No response_

### Current Behavior

1.They can produce concrete,but for some reasons not delivered correctly,causing builder repeat requesting(I guess it might be caused by that the delivery man delivered while the concrete mixer has not done his works, I'm not sure)
2.They cannot produce concrete powder because they put the powder block nearby water,thus it turn into concrete

### Expected Behavior

produce and deliver correctly

### Reproduction Steps

request concrete

### Logs

I don't think logs are necessary for this issue,I will update it if you actually need it.

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #10644
Closes #10646 

# Changes proposed in this pull request
- Move soundsource of raid source to hostile
- Fix concrete mixer issue
- Remove extra food handout
- Fix standup/sitdown loop at restaurant

## Testing
- [x] Yes I tested this before submitting it.
- [x] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/core/entity/ai/minimal/EntityAIEatTask.java [hunk 1]
```diff
@@ -292,7 +291,7 @@ private EatingState goToEatingPlace()
             }
         }
 
-        if (EntityNavigationUtils.walkToPos(citizen, eatPos, 2, true))
+        if (citizen.getVehicle() != null || EntityNavigationUtils.walkToPos(citizen, eatPos, 2, true))
```
Comment (someaddons) [inline src/main/java/com/minecolonies/core/entity/ai/minimal/EntityAIEatTask.java]: this shouldnt be needed, if it is then another logic is failing, an it creates a new sitting entity for the citizen that is sitting already

Comment (Raycoms) [reply src/main/java/com/minecolonies/core/entity/ai/minimal/EntityAIEatTask.java]: The citizen end up in a sit/stand loop because walkToPos resets the sitting position

**Review by someaddons — APPROVED** [review]
