### PR TITLE
Fix grave CME

### LINKED ISSUE #7075: Undertaker AI issue -- java.util.ConcurrentModificationException
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.151-ALPHA-universal

### Logs

- [latest.log](https://gist.github.com/Billijk/bce4f7ec9e16e1a42bc6aaa712736f33) 

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

The part in the log with exception:
```
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1493) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1516) ~[?:?]
	at com.minecolonies.coremod.colony.managers.GraveManager.reserveNextFreeGrave(GraveManager.java:212) ~[minecolonies:0.14.131-ALPHA]
	at com.minecolonies.coremod.colony.buildings.workerbuildings.BuildingGraveyard.getGraveToWorkOn(BuildingGraveyard.java:173) ~[minecolonies:0.14.131-ALPHA]
	at com.minecolonies.coremod.entity.ai.citizen.undertaker.EntityAIWorkUndertaker.startWorking(EntityAIWorkUndertaker.java:107) ~[minecolonies:0.14.131-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[minecolonies:0.14.131-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163) ~[minecolonies:0.14.131-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149) ~[minecolonies:0.14.131-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:129) ~[minecolonies:0.14.131-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:108) ~[minecolonies:0.14.131-ALPHA]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129) ~[minecolonies:0.14.131-ALPHA]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?]
	at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:223) ~[minecolonies:0.14.131-ALPHA]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?]
	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:389) ~[minecolonies:0.14.131-ALPHA]
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:455) ~[minecolonies:0.14.131-ALPHA]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by someaddons**
Closes #7075

# Changes proposed in this pull request:
Fix CME, improve gravediggers to make them work on loaded only graves and not load chunks

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingGraveyard.java [hunk 1]
```diff
@@ -1,539 +1,537 @@
...
+    /**
+     * Retrieves a random grave to work on for the undertaker.
+     *
+     * @return a field to work on.
+     */
+    @Nullable
+    public BlockPos getGraveToWorkOn()
+    {
+        if(currentGrave != null)
+        {
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingGraveyard.java:169]: Only this part is new, seems the file was missing some formatting. I've added that it checks for loading here, and releases the lock on the grave when its not loaded

**Review by Raycoms — APPROVED** [review]

**Review by marchermans — APPROVED** [review]

**Review by Mekle001 — APPROVED** [review]
