### PR TITLE
Fix/crashes expceptions

### LINKED ISSUE #947: Collection of issues - 0.7.777
Hey guys- 

Looking forward to the Bakery & Food system, but having a few issues with the 0.7.777 build. I've gathered that there are hotfixes for the issues; at least all bar the warehouse one. Just wondering when the next version is due that will have these as we're losing resources left right and centre, which is bad enough normally but I've recently moved my server to the "Colonial Expansion" modpack which makes survival (or resource gathering) much harder, so when you lose your stuff it's all the more devastating.

### Minecolonies version

version 0.7.777

### Expected behavior

- Supply Camp can be placed
- Items appear in warehouse chests
- Items from Warehouses arrive at their destination
- Items from Workers appear in their huts

### Actual behaviour

* Items taken to Warehouse disappear before they are placed in chests
* Items taken from Warehouse to huts disappear on handoff
* Items from Workers disappear when placed in the hut inventory
* Supply Camp cannot be placed

### Steps to reproduce the problem

Just allowing the colony to run as normal; workers all appear to go from place to place but no items appear at their destination. 

Plus the supply camp doesn't work at all which has put a few of my players on hold just gathering resources as they are VERY keen to try out the camp.

Anyway- I know you're hard at work on these, so just looking for an ETA on a fixed build.

Keep up the good work- we love this mod! :-)

### LINKED ISSUE #949: Crash when i will right klick on Peoples or the town hall
### Minecolonies version

minecraft version 1.11.2 
minecolony version on curserforge: 0.7.862
forge version: 13.20.0.2284 or 13.20.0.2296

### Expected behavior

- open the Gui 

### Actual behaviour

- Crash when i will right klick on Peoples or the town hall

### Steps to reproduce the problem

1. Make a new colony
2. right klick on Peoples or the town hall
3. Crash!

Single and Multiplayer World.
i do it with other and no other Mods.
under the line is the Crash report from the Town Hall and a Citizen.
when i will right klicking its crashd with every people.
sorry for my bad english...i hope you understand my english... 
_____________________________________________________________________________________ 

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 5/7/17 9:36 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
at com.minecolonies.coremod.client.gui.WindowTownHall.createAndSetStatistics(WindowTownHall.java:813)
at com.minecolonies.coremod.client.gui.WindowTownHall.onOpened(WindowTownHall.java:759)
at com.minecolonies.blockout.Screen.func_73866_w_(Screen.java:97)
at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:489)
at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:966)
at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:538)
at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:317)
at com.minecolonies.blockout.views.Window.open(Window.java:167)
at com.minecolonies.coremod.colony.buildings.AbstractBuilding$View.openGui(AbstractBuilding.java:1359)
at com.minecolonies.coremod.blocks.AbstractBlockHut.func_180639_a(AbstractBlockHut.java:208)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:408)
at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1521)
at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
at com.minecolonies.coremod.client.gui.WindowTownHall.createAndSetStatistics(WindowTownHall.java:813)
at com.minecolonies.coremod.client.gui.WindowTownHall.onOpened(WindowTownHall.java:759)
at com.minecolonies.blockout.Screen.func_73866_w_(Screen.java:97)
at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:489)
at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:966)
at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:538)
at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:317)
at com.minecolonies.blockout.views.Window.open(Window.java:167)
at com.minecolonies.coremod.colony.buildings.AbstractBuilding$View.openGui(AbstractBuilding.java:1359)
at com.minecolonies.coremod.blocks.AbstractBlockHut.func_180639_a(AbstractBlockHut.java:208)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:408)
at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1521)
at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)

-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityPlayerSP['Durothan'/4, l='MpServer', x=294.49, y=4.00, z=-573.99]]
Chunk stats: MultiplayerChunkCache: 534, 534
Level seed: 0
Level generator: ID 01 - flat, ver 0. Features enabled: false
Level generator options:
Level spawn location: World: (290,4,-574), Chunk: (at 2,0,2 in 18,-36; contains blocks 288,0,-576 to 303,255,-561), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
Level time: 247 game time, 247 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Forced entities: 2 total; [EntityPlayerSP['Durothan'/4, l='MpServer', x=294.49, y=4.00, z=-573.99], EntitySlime['Schleim'/13572, l='MpServer', x=220.38, y=4.00, z=-628.15]]
Retry entities: 0 total; []
Server brand: fml,forge
Server type: Integrated singleplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.11.2
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 262074760 bytes (249 MB) / 541904896 bytes (516 MB) up to 5355339776 bytes (5107 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.38 Powered by Forge 13.20.0.2284 6 mods loaded, 6 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAAAAAA minecraft{1.11.2} [Minecraft] (minecraft.jar)
UCHIJAAAAAA mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
UCHIJAAAAAA FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2284.jar)
UCHIJAAAAAA forge{13.20.0.2284} [Minecraft Forge] (forge-1.11.2-13.20.0.2284.jar)
UCHIJAAAAAA mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar)
UCHIJAAAAAA minecolonies{1.11.2-0.7.862} [MineColonies] (minecolonies-universal-1.11.2-0.7.862.jar)
Loaded coremods (and transformers):
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 760/PCIe/SSE2'
Launched Version: 1.11.2-forge1.11.2-13.20.0.2284
LWJGL: 2.9.4
OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.05, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs:
Current Language: Deutsch (Deutschland)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
______________________________________________________________________________________________
AND BY KLICKING ON PEOPLE IS THE CRASH REPORT: 
_____________________________________________________________________________________________

---- Minecraft Crash Report ----

WARNING: coremods are present:
AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.1.0.jar)
TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 5/7/17 9:51 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
at com.minecolonies.coremod.client.gui.WindowCitizen.createSaturationBar(WindowCitizen.java:268)
at com.minecolonies.coremod.client.gui.WindowCitizen.onOpened(WindowCitizen.java:222)
at com.minecolonies.blockout.Screen.func_73866_w_(Screen.java:97)
at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:489)
at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:966)
at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:542)
at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:317)
at com.minecolonies.blockout.views.Window.open(Window.java:167)
at com.minecolonies.coremod.proxy.ClientProxy.showCitizenWindow(ClientProxy.java:80)
at com.minecolonies.coremod.entity.EntityCitizen.func_184645_a(EntityCitizen.java:948)
at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1213)
at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1191)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_187097_a(PlayerControllerMP.java:534)
at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1509)
at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
at com.minecolonies.coremod.client.gui.WindowCitizen.createSaturationBar(WindowCitizen.java:268)
at com.minecolonies.coremod.client.gui.WindowCitizen.onOpened(WindowCitizen.java:222)
at com.minecolonies.blockout.Screen.func_73866_w_(Screen.java:97)
at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:489)
at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:966)
at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:542)
at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:317)
at com.minecolonies.blockout.views.Window.open(Window.java:167)
at com.minecolonies.coremod.proxy.ClientProxy.showCitizenWindow(ClientProxy.java:80)
at com.minecolonies.coremod.entity.EntityCitizen.func_184645_a(EntityCitizen.java:948)
at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1213)
at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1191)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_187097_a(PlayerControllerMP.java:534)
at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1509)
at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)

-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityPlayerSP['Durothan'/55, l='MpServer', x=695.70, y=4.00, z=-71.41]]
Chunk stats: MultiplayerChunkCache: 624, 624
Level seed: 0
Level generator: ID 01 - flat, ver 0. Features enabled: false
Level generator options:
Level spawn location: World: (803,4,-69), Chunk: (at 3,0,11 in 50,-5; contains blocks 800,0,-80 to 815,255,-65), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
Level time: 930666 game time, 958 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Forced entities: 12 total; [EntityHenLeghorn['Leghorn Huhn (Henne)'/17, l='MpServer', x=751.66, y=4.00, z=-101.55], EntityHogYorkshire['Yorkshire Schwein (Eber)'/2, l='MpServer', x=668.06, y=4.00, z=-107.50], EntityCitizen['Gerard H. Ardern'/5, l='MpServer', x=695.70, y=4.00, z=-69.47], EntityCitizen['Jasmine Q. Gobberd'/6, l='MpServer', x=693.30, y=4.00, z=-69.70], EntityCitizen['Lorena J. Haddock'/7, l='MpServer', x=693.98, y=4.00, z=-69.70], EntityCitizen['Jordan S. Gavell'/8, l='MpServer', x=699.86, y=4.00, z=-69.07], EntitySheep['Schaf'/9, l='MpServer', x=698.44, y=4.00, z=-4.25], EntityHogYorkshire['Yorkshire Schwein (Eber)'/10, l='MpServer', x=712.50, y=3.00, z=-52.92], EntityHenLeghorn['Leghorn Huhn (Henne)'/11, l='MpServer', x=746.51, y=4.00, z=-109.22], EntityHenLeghorn['Leghorn Huhn (Henne)'/12, l='MpServer', x=751.58, y=4.00, z=-39.11], EntitySheep['Schaf'/13, l='MpServer', x=744.22, y=4.00, z=3.58], EntityPlayerSP['Durothan'/55, l='MpServer', x=695.70, y=4.00, z=-71.41]]
Retry entities: 0 total; []
Server brand: fml,forge
Server type: Integrated singleplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.11.2
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1526905256 bytes (1456 MB) / 3824861184 bytes (3647 MB) up to 5355339776 bytes (5107 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.38 Powered by Forge 13.20.0.2296 38 mods loaded, 38 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAAAA minecraft{1.11.2} [Minecraft] (minecraft.jar)
UCHIJAAAA mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
UCHIJAAAA FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2296.jar)
UCHIJAAAA forge{13.20.0.2296} [Minecraft Forge] (forge-1.11.2-13.20.0.2296.jar)
UCHIJAAAA mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar)
UCHIJAAAA dmonsters{1.15} [Deadly Monsters] (1.11.2_deadly_monsters_1.15.jar)
UCHIJAAAA jei{4.3.4.273} [Just Enough Items] (jei_1.11.2-4.3.4.273.jar)
UCHIJAAAA abyssalcraft{1.9.4-pre-2} [AbyssalCraft] (AbyssalCraft-1.11.2-1.9.4-pre-2.jar)
UCHIJAAAA aether_legacy{v1.4.1} [Aether Legacy] (aether_legacy-1.11.2-1.0.jar)
UCHIJAAAA harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft.jar)
UCHIJAAAA angrybees{1.0} [Angry Bees] (AngryBees (Pams Mod).jar)
UCHIJAAAA animania{1.0.4.7} [Animania] (Animania.jar)
UCHIJAAAA applecore{2.1.2} [AppleCore] (AppleCore-mc1.11.2-2.1.2.jar)
UCHIJAAAA betterwithmods{1.1.7} [Better With Mods] (Better With Mods-1.1.7-1.11.2.jar)
UCHIJAAAA customnpcs{1.11.2} [CustomNPCs] (CustomNPCs.jar)
UCHIJAAAA drpcore{0.2.0b} [Dark Roleplay Core] (Dark Roleplay Core Alpha.jar)
UCHIJAAAA drpmedieval{0.1.8} [Dark Roleplay Medieval] (Dark Roleplay Medieval Alpha.jar)
UCHIJAAAA ptrmodellib{1.0.0} [ptrmodellib] (Decocraft-2.4.2_1.11.2.jar)
UCHIJAAAA props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.11.2.jar)
UCHIJAAAA dsurround{3.4.1.0} [§3Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.4.1.0.jar)
UCHIJAAAA presets{3.4.1.0} [§3Presets!] (DynamicSurroundings-1.11.2-3.4.1.0.jar)
UCHIJAAAA earthworks{1.2.1} [Earthworks] (Earthworks-1.11.2-1.2.2.jar)
UCHIJAAAA fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay.jar)
UCHIJAAAA foragecraft{1.11} [ForageCraft] (ForageCraft.jar)
UCHIJAAAA journeymap{1.11.2-5.4.6} [JourneyMap] (JourneyMap.jar)
UCHIJAAAA malisiscore{1.11.2-5.1.1} [MalisisCore] (malisiscore-1.11.2-5.1.1.jar)
UCHIJAAAA malisisdoors{1.11.2-6.1.0} [MalisisDoors] (malisisdoors-1.11.2-6.1.0.jar)
UCHIJAAAA minecolonies{1.11.2-0.7.862} [MineColonies] (minecolonies-universal-1.11.2-0.7.862.jar)
UCHIJAAAA neat{1.4-13} [Neat] (Neat 1.4-13.jar)
UCHIJAAAA placeableitems{3.0.4} [Placeable Items Mod] (PlaceableItems.jar)
UCHIJAAAA roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar)
UCHIJAAAA rustic{0.2} [Rustic] (rustic-0.2.jar)
UCHIJAAAA spartanshields{1.3} [Spartan Shields] (SpartanShields.jar)
UCHIJAAAA spiceoflife{1.3.8} [The Spice of Life] (SpiceOfLife-mc1.11.2-1.3.8.jar)
UCHIJAAAA toughasnails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.11-2.0.5.jar)
UCHIJAAAA treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.11.2-1.1.2.jar)
UCHIJAAAA weaponcaseloot{5.0.3-beta} [WeaponCaseLoot] (weaponcaseloot-1.11.2-5.0.3-beta.jar)
UCHIJAAAA wearablebackpacks{2.3.2} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.3.2.jar)
Loaded coremods (and transformers):
AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
squeek.applecore.asm.TransformerModuleHandler
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.1.0.jar)
org.blockartistry.DynSurround.asm.Transformer
TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
toughasnails.asm.transformer.BlockCropsTransformer
toughasnails.asm.transformer.EntityRendererTransformer
toughasnails.asm.transformer.WorldTransformer
MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
net.malisis.core.util.chunkblock.ChunkBlockTransformer
net.malisis.core.renderer.transformer.MalisisRendererTransformer
net.malisis.core.renderer.icon.asm.TextureMapTransformer
net.malisis.core.util.clientnotif.ClientNotifTransformer
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 760/PCIe/SSE2'
Launched Version: 1.11.2-forge1.11.2-13.20.0.2296
LWJGL: 2.9.4
OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.05, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs:
Current Language: Deutsch (Deutschland)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz

### LINKED ISSUE #950: Loosing Items
### Minecolonies version

1.11.2 - 0.7.811 (Same thing happens with 1.11.2 - 0.7.830 & 1.11.2 - 0.7.832)

### Expected behavior

a) Lumberjack deposits wood into building (chest) and wood is available for collection.
b) Deliveryman collects items and places them in the warehouse.

### Actual behaviour

a) Lumberjack deposits wood into building (chest) and wood disappears.
b) Deliveryman collects items and the items never appear in the warehouse (or anywhere else).

### Steps to reproduce the problem

1. Tried with all available versions of the mod, problem still remains.
2. Removed all other mods I am running and problem still remains.
3. Checked the config files to see if anything was relevant to the issue, nothing found.
4. Demolished the warehouse and had it rebuilt, problem still remains.

Note:  I understand that the 1.11.2 version is not the most stable yet.  I love the mod and hope to be playing it for a long time to come.  Thanks for a great mod!

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #947
Closes #949 
Closes #950

# Changes proposed in this pull request:
- Fix various crashes and exceptions with builder and guis

Review please

### CODE REVIEW

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 87 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 23 major
* ![MINOR][MINOR] 56 minor
* ![INFO][INFO] 7 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BlockUtils.java#L238](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L238): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L58](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L58): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 29 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L721](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L721): Refactor this method to reduce its Cognitive Complexity from 32 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [BlockUtils.java#L27](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L27): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 52 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [BlockUtils.java#L70](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L70): Assign this magic number 3 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [BlockUtils.java#L124](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L124): Assign this magic number 3 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [BlockUtils.java#L192](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L192): This method has 150 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS138)
1. ![MAJOR][MAJOR] [BlockUtils.java#L192](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L192): Reduce the number of returns of this method 34, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [BlockUtils.java#L192](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L192): The Cyclomatic Complexity of this method "getItem" is 43 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [BlockUtils.java#L192](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L192): Refactor this method to reduce its Cognitive Complexity from 68 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 87 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 23 major
* ![MINOR][MINOR] 56 minor
* ![INFO][INFO] 7 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BlockUtils.java#L238](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L238): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L58](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L58): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 29 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L720](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L720): Refactor this method to reduce its Cognitive Complexity from 32 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [BlockUtils.java#L27](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L27): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 52 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [BlockUtils.java#L70](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L70): Assign this magic number 3 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [BlockUtils.java#L124](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L124): Assign this magic number 3 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [BlockUtils.java#L192](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L192): This method has 150 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS138)
1. ![MAJOR][MAJOR] [BlockUtils.java#L192](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L192): Reduce the number of returns of this method 34, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [BlockUtils.java#L192](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L192): The Cyclomatic Complexity of this method "getItem" is 43 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [BlockUtils.java#L192](https://github.com/Minecolonies/minecolonies/blob/4e43736e0db116d463efcc37874158b5761b40ab/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L192): Refactor this method to reduce its Cognitive Complexity from 68 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 99 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 31 major
* ![MINOR][MINOR] 60 minor
* ![INFO][INFO] 7 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BlockUtils.java#L238](https://github.com/Minecolonies/minecolonies/blob/dcf7b07f6d8bc560aa72b45067b28449df44dcd4/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L238): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java](https://github.com/Minecolonies/minecolonies/blob/dcf7b07f6d8bc560aa72b45067b28449df44dcd4/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java): This file has 784 lines, which is greater than 750 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L36](https://github.com/Minecolonies/minecolonies/blob/dcf7b07f6d8bc560aa72b45067b28449df44dcd4/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L36): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 25 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L36](https://github.com/Minecolonies/minecolonies/blob/dcf7b07f6d8bc560aa72b45067b28449df44dcd4/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L36): class "AbstractEntityAIBasic" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L205](https://github.com/Minecolonies/minecolonies/blob/dcf7b07f6d8bc560aa72b45067b28449df44dcd4/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L205): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1165](https://github.com/Minecolonies/minecolonies/blob/dcf7b07f6d8bc560aa72b45067b28449df44dcd4/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1165): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1303](https://github.com/Minecolonies/minecolonies/blob/dcf7b07f6d8bc560aa72b45067b28449df44dcd4/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1303): Merge this if statement with the enclosing one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1066)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L58](https://github.com/Minecolonies/minecolonies/blob/dcf7b07f6d8bc560aa72b45067b28449df44dcd4/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L58): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 29 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L720](https://github.com/Minecolonies/minecolonies/blob/dcf7b07f6d8bc560aa72b45067b28449df44dcd4/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L720): Refactor this method to reduce its Cognitive Complexity from 32 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [PlacementHandlers.java#L58](https://github.com/Minecolonies/minecolonies/blob/dcf7b07f6d8bc560aa72b45067b28449df44dcd4/src/main/java/com/minecolonies/coremod/placementhandlers/PlacementHandlers.java#L58): Reduce this class from 31 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

**Comment by marchermans** [comment]
I seem to have missed a beautifull Corner case in 1.11 again......
I definitly Need to finish the Transaction System somewhere this week....

File: src/main/java/com/minecolonies/coremod/util/InventoryUtils.java [hunk 1]
```diff
@@ -686,12 +688,15 @@ public static int findFirstSlotInProviderNotEmptyWith(@NotNull final ICapability
      */
     public static int findFirstSlotInItemHandlerNotEmptyWith(@NotNull final IItemHandler itemHandler, @NotNull final Predicate<ItemStack> itemStackSelectionPredicate)
     {
-        @NotNull final Predicate<ItemStack> notEmptyPredicate = itemStack -> !InventoryUtils.isItemStackEmpty(itemStack);
-        notEmptyPredicate.and(itemStackSelectionPredicate);
+        @NotNull final Predicate<ItemStack> emptyPredicate = InventoryUtils::isItemStackEmpty;
+        @NotNull final Predicate<ItemStack> notEmptyPredicate = emptyPredicate.negate();
+        //todo: extract the first to as static fields
```
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/util/InventoryUtils.java]: I fixed your thing here, can you later finish the todo? @Raycoms

Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/util/InventoryUtils.java]: INFO Complete the task associated to this TODO comment. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1135)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 100 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 31 major
* ![MINOR][MINOR] 60 minor
* ![INFO][INFO] 8 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BlockUtils.java#L238](https://github.com/Minecolonies/minecolonies/blob/ee1c17c4323121a876a67fd40c8112a11f6919fb/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L238): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java](https://github.com/Minecolonies/minecolonies/blob/ee1c17c4323121a876a67fd40c8112a11f6919fb/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java): This file has 784 lines, which is greater than 750 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L36](https://github.com/Minecolonies/minecolonies/blob/ee1c17c4323121a876a67fd40c8112a11f6919fb/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L36): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 25 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L36](https://github.com/Minecolonies/minecolonies/blob/ee1c17c4323121a876a67fd40c8112a11f6919fb/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L36): class "AbstractEntityAIBasic" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L205](https://github.com/Minecolonies/minecolonies/blob/ee1c17c4323121a876a67fd40c8112a11f6919fb/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L205): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1165](https://github.com/Minecolonies/minecolonies/blob/ee1c17c4323121a876a67fd40c8112a11f6919fb/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1165): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1303](https://github.com/Minecolonies/minecolonies/blob/ee1c17c4323121a876a67fd40c8112a11f6919fb/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1303): Merge this if statement with the enclosing one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1066)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L58](https://github.com/Minecolonies/minecolonies/blob/ee1c17c4323121a876a67fd40c8112a11f6919fb/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L58): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 29 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L720](https://github.com/Minecolonies/minecolonies/blob/ee1c17c4323121a876a67fd40c8112a11f6919fb/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L720): Refactor this method to reduce its Cognitive Complexity from 32 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [PlacementHandlers.java#L58](https://github.com/Minecolonies/minecolonies/blob/ee1c17c4323121a876a67fd40c8112a11f6919fb/src/main/java/com/minecolonies/coremod/placementhandlers/PlacementHandlers.java#L58): Reduce this class from 31 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 99 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 31 major
* ![MINOR][MINOR] 60 minor
* ![INFO][INFO] 7 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BlockUtils.java#L238](https://github.com/Minecolonies/minecolonies/blob/11dfe489a8448c88df70978c5a5345e84546dc68/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L238): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java](https://github.com/Minecolonies/minecolonies/blob/11dfe489a8448c88df70978c5a5345e84546dc68/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java): This file has 784 lines, which is greater than 750 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L36](https://github.com/Minecolonies/minecolonies/blob/11dfe489a8448c88df70978c5a5345e84546dc68/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L36): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 25 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L36](https://github.com/Minecolonies/minecolonies/blob/11dfe489a8448c88df70978c5a5345e84546dc68/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L36): class "AbstractEntityAIBasic" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L205](https://github.com/Minecolonies/minecolonies/blob/11dfe489a8448c88df70978c5a5345e84546dc68/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L205): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1165](https://github.com/Minecolonies/minecolonies/blob/11dfe489a8448c88df70978c5a5345e84546dc68/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1165): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1303](https://github.com/Minecolonies/minecolonies/blob/11dfe489a8448c88df70978c5a5345e84546dc68/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1303): Merge this if statement with the enclosing one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1066)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L58](https://github.com/Minecolonies/minecolonies/blob/11dfe489a8448c88df70978c5a5345e84546dc68/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L58): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 29 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L720](https://github.com/Minecolonies/minecolonies/blob/11dfe489a8448c88df70978c5a5345e84546dc68/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L720): Refactor this method to reduce its Cognitive Complexity from 32 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [PlacementHandlers.java#L58](https://github.com/Minecolonies/minecolonies/blob/11dfe489a8448c88df70978c5a5345e84546dc68/src/main/java/com/minecolonies/coremod/placementhandlers/PlacementHandlers.java#L58): Reduce this class from 31 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'
