### PR TITLE
Fix leave stuck problem

### LINKED ISSUE #4880: Lumberjack still not able to chop down certain trees due to foliage.
### Minecolonies version

Version: 0.11.917-ALPHA

### Expected behavior

- 
That the Lumberjack can actually get close enough to the trunk of the tree to chop the tree down
### Actual behaviour

- 
The lumberjack just bounces off the leaves of the tree repeatedly and gets stuck.  Will not give up on tree.  After an evening of returning to sleep lumberjack goes back to the same tree and is stuck.  This loop continues until the tree is manually chopped down.

This bug was opened previously and closed via a commit. I am still experiencing this in build 917 as shown in this video:

https://youtu.be/19yxRp8a8E8

### Steps to reproduce the problem

1. have lumberjack find odd tree (might be that he was up one level)
2.  don't profit, since he/she won't chop that sucker down! :P

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

Nothing is logged in the latest.log or debug.log

### PR DESCRIPTION
**Pull request by Tobiti**
Closes #4880

# Changes proposed in this pull request:
- mines the leaves when worker is stuck
- mines leaves when they are in the way to a tree

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java [hunk 1]
```diff
@@ -300,6 +311,65 @@ private IAIState findTrees()
         return LUMBERJACK_CHOP_TREE;
     }
 
+    @NotNull
+    @Override
+    protected IAIState dumpInventory() {
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: I don't think all this dump inventory code here is necessary?

Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: The problem is that the worker can get stuck when a tree grows around him while he is choking down a tree, so when he then tries to bring the items back I need to check if he is stuck.
I can reduce it to only the first few lines and then call the super dumpInventory function

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: did you test this? Because normally the AI should shut down completely when the head is in the leaves

Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: I tested it some minutes ago and its working fine :)

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: shouldn't be necessary to copy all this code here though. If anything then you should put this in the walkToBlock override and not in copied functions.

Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: But then I need to copy everything to the EntityCitizenWalkToProxy class

**Comment by Raycoms** [comment]
No you just intercept the call of the AI, make it call super and check if stuck.

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java (hunk 1 above)
Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: image
The problem is that its final

Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: I will change that and override the function

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: ye

Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: Still have the problem for the dumpInventory function, because its not calling the walkToBlock function of the ai
Instead its calling this function on the worker:
image

Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: Am I allowed to change it in the abstract class to the walkToBlock funtion?

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: and the walkToBlock on the AI, calls this also doesn't it? So we just redirect the dump call to this one.

Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: image
Its nearly the same

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: it returns the opposite though. So you have to take that into account.

Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: I can just remove the ! in dumpInventory :)

**Comment by Tobiti** [comment]
Its done

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java [hunk 2]
```diff
@@ -544,31 +565,93 @@ private Boolean isPassable(final BlockState blockState)
...
     {
         if (!worker.getNavigator().noPath())
         {
-            Path pathToTree = worker.getNavigator().getPath();
-            if (pathToTree != null && pathToTree.getCurrentPathLength() > pathToTree.getCurrentPathIndex())
-            {
-                PathPoint next = pathToTree.getPathPointFromIndex(pathToTree.getCurrentPathIndex());
-                BlockPos nextPos = new BlockPos(next.x, next.y, next.z);
-                BlockPos nextPosUp = new BlockPos(next.x, next.y + 1, next.z);
-
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java:562]: I think all you needed to add for the unstuck to work better is here to add  `BlockPos nextPosUpUp = new BlockPos(next.x, next.y + 2, next.z);` as it gets stuck in cases where it needs space to change height.

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java [hunk 3]
```diff
@@ -227,6 +235,17 @@ protected IAIState decide()
         return GET_RECIPE;
     }
 
+    @Override
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: see my comment above, this shouldnt be here at all

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java [hunk 4]
```diff
@@ -544,31 +565,93 @@ private Boolean isPassable(final BlockState blockState)
...
+                // Block above the worker
+                checkPositions.add(new BlockPos(worker.getCurrentPosition().getX(), worker.getCurrentPosition().getY() + 2, worker.getCurrentPosition().getZ()));
+
+                mineIfEqualsBlockTag(checkPositions, BlockTags.LEAVES);
+                return;
+            }
+        }
+
+        // General unstuck
+        ArrayList<BlockPos> checkPositions = new ArrayList<>();
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java:618]: we are already using the pathing to see which leaves need to be removed, I don't think we need this general remove all around worker

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java [hunk 5]
```diff
@@ -544,31 +565,93 @@ private Boolean isPassable(final BlockState blockState)
...
+
+        mineIfEqualsBlockTag(checkPositions, BlockTags.LEAVES);
+    }
+
+    /**
+     * Checks blocks for tag and mines the first it fines if its the same
+     * @param blockPositions block positions
+     * @param tag tag to check
+     */
+    private boolean mineIfEqualsBlockTag(List<BlockPos> blockPositions, Tag<Block> tag){
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: This function isnt going to work nicely like this, because our mineBlock() is made to mine one position after another as it works through repeated calls and a delay inbetween

**Review by someaddons — CHANGES_REQUESTED** [review]
thanks for the pr, always nice to see new ppl contributing!
Now I think you're overshooting the target here, trying to catch any cases where the citizen may walk to detect/unstuck him. Which isnt really possible to get all the edge cases and should be done as unstuck handling in our navigator instead, which I'll soon improve on, atm that is a bit broken. So all you gotta do here is adding additional leave breaking when walking to a tree

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java (hunk 4 above)
Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java:618]: But you dont have always a path, sometimes the path is empty or null

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java (hunk 5 above)
Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: Why? 
Its only adding one block per call

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java (hunk 3 above)
Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: Done

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java (hunk 5 above)
Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: ye one block per call isnt enough, you need to call the same position twice, with a time delay inbetween. It simulates the harvesting with a delay before actually breaking the block. Since the AI repeatedly executes this code. You should do if(leaf) mine(leaf) and then you do nothing but wait for the next time it runs into it again, and you check for the first leaf you find again and break that one again.

Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: But that was happening before, I just moved it into a separate function to minimize the code lines

Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: no before it was an if else, it did check first pos -> is leaf? -> mine block. Next AI update it does check first pos -> is leaf? -> mine block (block breaks). Then next AI update it does check first pos -> no leaf -> check second pos -> is leaf -> mine second

Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: And now its the same
I starts with the first object in the list
if leaf -> mine and return, second run, again first is leaf -> mine(break) -> return
3rd run first is not leaf -> check second, if leaf ...

**Comment by Tobiti** [comment]
Do I need to change more or can this be merged?

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java [hunk 6]
```diff
@@ -114,7 +114,7 @@
     /**
      * Slot he is currently trying to dump.
      */
-    private int slotAt = 0;
+    protected int slotAt = 0;
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java]: Do these still all have to be protected?

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java [hunk 7]
```diff
@@ -413,7 +421,9 @@ private IAIState chopTree()
         {
             if (!walkToTree(job.getTree().getStumpLocations().get(0)))
             {
-                checkIfStuckOnLeaves();
+                if(checkIfStuck()) {
+                    tryUnstuck();
+                }
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java:428]: brackets

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java [hunk 8]
```diff
@@ -544,31 +554,94 @@ private Boolean isPassable(final BlockState blockState)
...
-                BlockPos nextPos = new BlockPos(next.x, next.y, next.z);
-                BlockPos nextPosUp = new BlockPos(next.x, next.y + 1, next.z);
-
-                if (world.getBlockState(nextPos).getBlock().isIn(BlockTags.LEAVES))
-                {
-                    mineBlock(nextPos);
+            Path path = worker.getNavigator().getPath();
+            if(path != null) {
+                if (path.getCurrentPathLength() > path.getCurrentPathIndex()) {
+                    return true;
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java:574]: code format is off

**Comment by Raycoms** [comment]
Missing mainly code format now

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java [hunk 9]
```diff
@@ -544,31 +555,102 @@ private Boolean isPassable(final BlockState blockState)
...
+                return true;
+            }
+        }
+        return false;
+    }
+
+    /**
+     * Mines leaves on path and above.
+     */
+    private void tryUnstuck(){
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: format

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java [hunk 10]
```diff
@@ -544,31 +555,102 @@ private Boolean isPassable(final BlockState blockState)
...
+
+                mineIfEqualsBlockTag(checkPositions, BlockTags.LEAVES);
+                return;
+            }
+        }
+
+        // General unstuck
+        ArrayList<BlockPos> checkPositions = new ArrayList<>();
+        // Blocks in front of the worker
+        checkPositions.add(new BlockPos(worker.getForward().getX(), worker.getForward().getY(), worker.getForward().getZ()));
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: This looks like you could make a 

for each Direction in Horizontal directions 
addInDirection

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java [hunk 11]
```diff
@@ -544,31 +555,102 @@ private Boolean isPassable(final BlockState blockState)
...
+        mineIfEqualsBlockTag(checkPositions, BlockTags.LEAVES);
+    }
+
+    /**
+     * Checks blocks for tag and mines the first it fines if its the same
+     * @param blockPositions block positions
+     * @param tag tag to check
+     */
+    private boolean mineIfEqualsBlockTag(List<BlockPos> blockPositions, Tag<Block> tag){
+        for (BlockPos currentPos : blockPositions) {
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: format this entire method too

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java (hunk 10 above)
Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: Done :)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java (hunk 11 above)
Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: Is fixed :)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java (hunk 9 above)
Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: Done :)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java [hunk 12]
```diff
@@ -544,30 +555,105 @@ private Boolean isPassable(final BlockState blockState)
...
+        {
+            Path path = worker.getNavigator().getPath();
+            if (path != null)
+            {
+                // Unstuck with path
+                ArrayList<BlockPos> checkPositions = new ArrayList<>();
+                PathPoint next = path.getPathPointFromIndex(path.getCurrentPathIndex());
+
+                // Blocks in front of the worker
+                for(int i = 0; i <= 2; i++){
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: cough

Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: Done
i need to change the code style in intellj

Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: you can import the codestyle from the documentation folder

**Review by someaddons — DISMISSED** [review]
Don't forget to accept the CLA :)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java (hunk 10 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: where?

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java [hunk 13]
```diff
@@ -544,30 +556,98 @@ private Boolean isPassable(final BlockState blockState)
...
+
+        // General unstuck
+        ArrayList<BlockPos> checkPositions = new ArrayList<>();
+        List<Direction> directions = new ArrayList<>();
+        directions.add(Direction.NORTH);
+        directions.add(Direction.EAST);
+        directions.add(Direction.WEST);
+        directions.add(Direction.SOUTH);
+
+        for (Direction direction: directions)
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: There is a minecraft class for all horizontal directions =D

Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: Couldn't find it :(

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: Plane.HORIZONTAL.values()

Comment (Tobiti) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: Is done :)

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/5136/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)
