### PR TITLE
fix 7184

### LINKED ISSUE #7184: AI issue - builder couldn't mine modded block/entity (Supplementals signpost)
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.6.4
- MineColonies Version: .196

### Logs

- latest.log: 
https://gist.github.com/mcmanustfj/4451cad20231a032e4bad791de157185 

## Steps to reproduce the issue / details

Just reporting the AI issue. 
I believe it has to do with a builder trying to remove a signpost from Supplementals, I could see the builder try and fail to remove the signpost.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #7184
Closes #
Closes #

# Changes proposed in this pull request:
- Use TE for loottable if te exists
-
-

Review please

### CODE REVIEW

File: src/api/java/com/minecolonies/api/util/BlockPosUtil.java [hunk 1]
```diff
@@ -413,10 +413,22 @@ public static TileEntity getTileEntity(@NotNull final World world, @NotNull fina
...
+            return world.getBlockState(coords).getDrops(new LootContext.Builder((ServerWorld) world)
+                                                          .withLuck(fortune)
+                                                          .withParameter(LootParameters.field_237457_g_, entity.getPositionVec())
+                                                          .withParameter(LootParameters.TOOL, stack));
+        }
+        else
+        {
+            return world.getBlockState(coords).getDrops(new LootContext.Builder((ServerWorld) world)
+                                                          .withLuck(fortune)
+                                                          .withParameter(LootParameters.BLOCK_ENTITY, te)
```
Comment (uecasm) [inline src/api/java/com/minecolonies/api/util/BlockPosUtil.java]: Why duplicate this whole block just to conditionally add one parameter?

Comment (uecasm) [reply src/api/java/com/minecolonies/api/util/BlockPosUtil.java]: Especially since you can just use `withNullableParameter` to avoid the condition entirely...

Comment (Raycoms) [reply src/api/java/com/minecolonies/api/util/BlockPosUtil.java]: didn't know about NullableParameter

**Review by uecasm — APPROVED** [review]

**Review by someaddons — APPROVED** [review]
