### PR TITLE
TileEntity improvements

### LINKED ISSUE #4717: Builder hut losing Items
### Minecolonies version 0.11.827-ALPHA
Part of Just not enough mods 2 Mod pack

Version: 

### Expected behavior
 Builder hut page two take items from my inventory and add to its own so that the builder can use.

### Actual behavior
Builder Hut takes items from my inventory but does not add to its own

### Steps to reproduce the problem 
1. start building any building (had happen with level 1 building hut and level 1 mine)
2. used page two of builder hut to give all items needed for current build before builder requested (he was clearing area). 
3. Went to work on something else while builder worked.
4. notice the builder was requesting something, went to see what he need. It was one of the items that I had already given when I checked in hut chest it wasn't there and nether was the rest of the stuff I had just given the hut.

The way it seems to happen is to use page two of hut before the build requests the items. I used creative mode and used page two and it did keep the items a second time after builder started requesting items.

### LINKED ISSUE #5566: Game Crashes when talking with Builder NPC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16
- MineColonies Version: 0.13.123 alpha
- Structurize Version: 1.2.1
- Related Mods and their Versions:

## Expected behavior
Open the NPC Gui and see why she had a red gear on the Head

## Actual behavior
When i rightlick on the NPC my game Crashes

## Steps to reproduce the issue

Rightclick the NPC to talk with her.

### Logs

https://gist.github.com/Dreadnouhgt/dc0ab2c2a4ed46956261f49e9b9c8f17
### Notes

Server restart did not help. 

http://prntscr.com/tz234b Second Builder also start with the weirdness now.... moves around the house, gos in the house, gos up and down, moves outside and not finishing the build. 
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #4717 
Closes #5566

# Changes proposed in this pull request:
- Fixes finally the item losing problem.
- 
-

Review please

### CODE REVIEW

**Review by marchermans — APPROVED** [review]

File: src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java [hunk 1]
```diff
@@ -166,29 +170,34 @@ public int getItemCount(final Predicate<ItemStack> predicate)
     @Override
     public void updateItemStorage()
     {
-        content.clear();
-        for (int slot = 0; slot < inventory.getSlots(); slot++)
+        if (world != null && !world.isRemote)
         {
-            final ItemStack stack = inventory.getStackInSlot(slot);
+            Log.getLogger().warn("changed");
```
Comment (someaddons) [inline src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java:175]: chrm :D

Comment (someaddons) [reply src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java:175]: btw Inv utils do have a function to map an inventory to a storage map

File: src/main/java/com/minecolonies/coremod/colony/interactionhandling/RequestBasedInteraction.java [hunk 2]
```diff
@@ -150,7 +150,10 @@ public void onWindowOpened(final Window window, final ICitizenDataView dataView)
 
                 icon.setID("request_item");
                 icon.setSize(32, 32);
-                icon.setItem((request.getDisplayStacks().get(0)));
+                if (!request.getDisplayStacks().isEmpty())
+                {
+                    icon.setItem((request.getDisplayStacks().get(0)));
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/colony/interactionhandling/RequestBasedInteraction.java:155]: might want to include the `   icon.setPosition(30, 60);
                icon.setVisible(true);` aswell, to not display Air?
