### PR TITLE
Restaurants should only be visitable to eat if there's someone working there

### LINKED ISSUE #11102: Nonfunctional restaurants 'grab' colonists
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [x] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.1.985

### Structurize Version

1.0.775

### Related Mods and their Versions

_No response_

### Current Behavior

In my colony I have a functional restaurant (level 3, Cliffs, menu/fuel/employee/food all good).
I built a building from another style that has a nested restaurant (steampunk alt barracks, though I doubt that's relevant). This restaurant is not staffed, has no menu items, inventory empty, and all fuel is Off.
To my surprise suddenly there were many colonists sitting in it waiting for food.

### Expected Behavior

A restaurant should not attract diners if it is non functional (especially if there's a restaurant that is). Multiple styles nest restaurants...some, in multiple buildings; some of those restaurants will not be in active usage.
While I'm not sure what constitutes the min bar for nonfunctional, I'd say the above situation definitely does (no inventory, no menu, no employee, no fuel config'd)

### Reproduction Steps

1. Have a working restaurant
2. Have a second one show up, and turn it all off as indicated above

### Logs

n/a

### Anything else?

I checked the checkbox about running latest, but I am not. I did put the correct version in there.
Unfortunately I can't update to the latest, ever, really, as I run a server and I can't risk having a build that new on there.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Thodor12**
Closes #11102 

# Changes proposed in this pull request
- Expand getBestBuilding with an optional predicate functionality
- When searching for a restaurant, try to check if the restaurant is actually occupied with a worker, with a fallback to go anyway.

## Testing
- [X] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/api/colony/managers/interfaces/IRegisteredStructureManager.java [hunk 1]
```diff
@@ -208,6 +208,16 @@ public interface IRegisteredStructureManager
      */
     BlockPos getBestBuilding(final AbstractEntityCitizen citizen, final Class<? extends IBuilding> building);
 
+    /**
+     * Calculate a good cook for a certain citizen.
```
Comment (someaddons) [inline src/main/java/com/minecolonies/api/colony/managers/interfaces/IRegisteredStructureManager.java]: "Search for the closest building matching type and filter"

File: src/main/java/com/minecolonies/api/colony/managers/interfaces/IRegisteredStructureManager.java [hunk 2]
```diff
@@ -217,6 +227,16 @@ public interface IRegisteredStructureManager
      */
     BlockPos getBestBuilding(final BlockPos pos, final Class<? extends IBuilding> building);
 
+    /**
+     * Calculate a good building for a certain pos.
```
Comment (someaddons) [inline src/main/java/com/minecolonies/api/colony/managers/interfaces/IRegisteredStructureManager.java]: "Search for the closest building matching type and filter"

File: src/main/java/com/minecolonies/core/entity/ai/minimal/EntityAIEatTask.java [hunk 3]
```diff
@@ -47,7 +49,12 @@
 public class EntityAIEatTask implements IStateAI
 {
     /**
-     * Max waiting time for food in minutes..
+     * Predicate for matching valid restaurants to navigate to.
+     */
+    private static final Predicate<BuildingCook> VALID_RESTAURANTS = restaurant -> restaurant.getModule(BuildingModules.COOK_WORK).hasAssignedCitizen();
```
Comment (someaddons) [inline src/main/java/com/minecolonies/core/entity/ai/minimal/EntityAIEatTask.java]: I'd call it STAFFED_RESTAURANTS isntead, as a nonstaffed restaurant is still valid, the staffed is just preferred

**Review by someaddons — APPROVED** [review]

**Review by Raycoms — APPROVED** [review]
