### PR TITLE
Use fake level for JEI

### LINKED ISSUE #10302: Memory Leak of Client Level
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.719

### Structurize Version

1.0.752

### Related Mods and their Versions

JEI - 19.19.3.226

### Current Behavior

To add JEI Compat, Minecolonies instantiate Citizens with the current real ClientLevel, causing it to hold forever.

image

### Expected Behavior

Maybe implement some sort of fake level or grab the level/instantiate lazily? dunno.

### Reproduction Steps

1. Load world with JEI in the mod list
2. Change dimensions
3. Check memory for active ClientLevels, you might see at least 2. the old and the current.

### Logs

check image

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by uecasm**
Closes #10302 (once ported)

# Changes proposed in this pull request
- Use a fake level when creating citizens for JEI

## Testing
- [x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please (should port)

### CODE REVIEW

**Review by Thodor12 — DISMISSED** [review]

**Review by Nightenom — CHANGES_REQUESTED** [review]
There is technically breaking change logic-wise in latest fakelevel backport, so please update
Use singleblockfakelevel, probably with blockstate of air 
Don't forget to override getRealLevel as redirect to mc.instance.level

**Review by Nightenom — DISMISSED** [review]

**Review by Raycoms — DISMISSED** [review]

**Review by Nightenom — DISMISSED** [review]

File: src/main/java/com/minecolonies/core/compatibility/jei/JeiFakeLevel.java [hunk 1]
```diff
@@ -0,0 +1,24 @@
+package com.minecolonies.core.compatibility.jei;
+
+import com.ldtteam.structurize.client.fakelevel.SingleBlockFakeLevel;
+import net.minecraft.client.Minecraft;
+import net.minecraft.world.level.Level;
+import net.minecraft.world.level.block.Blocks;
+import net.minecraftforge.api.distmarker.Dist;
+import net.minecraftforge.api.distmarker.OnlyIn;
+
+@OnlyIn(Dist.CLIENT)
```
Comment (someaddons) [inline src/main/java/com/minecolonies/core/compatibility/jei/JeiFakeLevel.java:10]: why onlyin? dont think we should use that in 1.21

**Comment by pietro-lopes** [comment]
Please, check how you are instancing this LivingEntity if you would need to use a fake level here too.

https://github.com/ldtteam/minecolonies/blob/7066c5cc40296ced6aa53d24cdbe11f3040d1164/src/main/java/com/minecolonies/api/crafting/GenericRecipe.java#L96

This is where it starts:
https://github.com/ldtteam/minecolonies/blob/7066c5cc40296ced6aa53d24cdbe11f3040d1164/src/main/java/com/minecolonies/core/compatibility/jei/JEIPlugin.java#L131

File: src/main/java/com/minecolonies/core/compatibility/jei/JeiFakeLevel.java (hunk 1 above)
Comment (uecasm) [reply src/main/java/com/minecolonies/core/compatibility/jei/JeiFakeLevel.java:10]: Paranoia, mostly.  Since it's using client-only classes it must not be loaded in the server jar.  Though that should be the case even without this, it seems safer to make it explicit.

**Comment by uecasm** [comment]
> Please, check how you are instancing this LivingEntity if you would need to use a fake level here too.

Good catch, thanks.

File: src/main/resources/META-INF/accesstransformer.cfg [hunk 2]
```diff
@@ -57,6 +57,7 @@ public net.minecraft.client.multiplayer.ClientAdvancements f_104390_ # advanceme
 public net.minecraft.world.level.block.DoorBlock m_245755_(Lnet/minecraft/world/entity/Entity;Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Z)V # playSound
 
 public net.minecraft.world.entity.Entity f_19816_ # eyeHeight
+public net.minecraft.world.entity.Entity m_284535_(Lnet/minecraft/world/level/Level;)V # setLevel
```
Comment (Nightenom) [inline src/main/resources/META-INF/accesstransformer.cfg]: Plain no, unlike BE entity level is notnull, please find another way

**Review by Nightenom — DISMISSED** [review]

File: src/main/resources/META-INF/accesstransformer.cfg (hunk 2 above)
Comment (uecasm) [reply src/main/resources/META-INF/accesstransformer.cfg]: There's no harm in it, I tested it.  The entity is never added to any world, it only exists for the renderer and it does get a level set while that happens.

Comment (Nightenom) [reply src/main/resources/META-INF/accesstransformer.cfg]: Not even BE has this method nullable (few vanilla BEs), so at least try catch it. Plus I really don't like it, unlike BE entities simply have non-null level contract..

**Review by Nightenom — APPROVED** [review]

**Comment by Nightenom** [comment]
Hmm, out of scope of this PR: but why do we pass instantiated entity in the first place?

**Comment by uecasm** [comment]
Because (a) that's what the entity renderer wants in order to draw an entity, and (b) other places need to query various instance methods that only exist on the instantiated entity.

**Comment by pietro-lopes** [comment]
Honestly, if possible, I prefer WeakReference instead of cached by *magic number 2 minutes*

**Comment by uecasm** [comment]
Minecraft GCs all the time, so a WeakReference is almost identical to not caching it at all.  And entities are not sufficiently lightweight for that to seem justifiable.

**Review by Raycoms — APPROVED** [review]

**Review by someaddons — APPROVED** [review]
