### PR TITLE
Because

### LINKED ISSUE #9851: [BUG] <Scaffolding pathing broken>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.512-BETA

### Structurize Version

1.0.712-BETA

### Related Mods and their Versions

_No response_

### Current Behavior

Citizens will just stand/ignore scaffolding path, no matter if it's underground pathing or made as a bridge.

### Expected Behavior

To be able to path via scaffolding, (in this case for animal pens)

### Reproduction Steps

Try and do the animal scaffolding guide that is usually posted on the official discord.

### Logs

https://gist.github.com/Tuganace/dc91ae0da6e0f7b3443dadf5fc7bba84

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by uecasm**
Closes #9851

# Changes proposed in this pull request:
- Adds a "free climbing" tag that allows climbing without research, with ladders and scaffolds in it.  (Vines still require the research.)

[ ] Yes I tested this before submitting it.
[ ] I also did a multiplayer test.

Review please

Because

### CODE REVIEW

**Comment by Moobien** [comment]
why is a tag needed? I dont understand the need for this

File: src/main/java/com/minecolonies/core/entity/pathfinding/PathfindingUtils.java [hunk 1]
```diff
@@ -331,7 +329,7 @@ public static boolean isLava(@NotNull final BlockGetter world, final BlockPos po
      */
     public static boolean isLadder(final BlockState blockState, @Nullable final PathingOptions options)
     {
-        return blockState.is(BlockTags.CLIMBABLE) && ((options != null && options.canClimbNonLadders()) || blockState.getBlock() instanceof LadderBlock);
+        return blockState.is(BlockTags.CLIMBABLE) && ((options != null && options.canClimbNonLadders()) || blockState.is(ModTags.freeClimbBlocks));
```
Comment (Thodor12) [inline src/main/java/com/minecolonies/core/entity/pathfinding/PathfindingUtils.java]: What about modded blocks that implement a ladder, those will seize to work now.
Additionally, should it respect that `options.canClimbNonLadders`?

Also the method probably should be renamed if this is to be considered.

**Comment by uecasm** [comment]
So that modpacks can make other climbable blocks also not require a research if they want.

File: src/main/java/com/minecolonies/core/entity/pathfinding/PathfindingUtils.java (hunk 1 above)
Comment (uecasm) [reply src/main/java/com/minecolonies/core/entity/pathfinding/PathfindingUtils.java]: That's why there's a tag, they had to be in the `CLIMBABLE` tag anyway, now they need to be in the other tag too -- or they're still climbable, but need the research.

But yes, I could rename the method.  I wanted it to be a smaller change for now 😁

**Comment by Moobien** [comment]
> So that modpacks can make other climbable blocks also not require a research if they want.

never needed a research to begin with. this is just convoluting a problem that never existed lol

File: src/main/java/com/minecolonies/core/entity/pathfinding/PathfindingUtils.java (hunk 1 above)
Comment (Moobien) [reply src/main/java/com/minecolonies/core/entity/pathfinding/PathfindingUtils.java]: but why is a tag even needed in the first place?

**Comment by uecasm** [comment]
> never needed a research to begin with. this is just convoluting a problem that never existed lol

They kinda did, actually.  In vanilla, all the CLIMBABLE blocks that aren't ladders or scaffolds are vines.  So this change essentially restores the previous behaviour that vines require the research and other things don't.

File: src/main/java/com/minecolonies/core/entity/pathfinding/PathfindingUtils.java (hunk 1 above)
Comment (uecasm) [reply src/main/java/com/minecolonies/core/entity/pathfinding/PathfindingUtils.java]: Because using a tag is better than hard-coding things, because modpacks can extend tags and they can't extend not-tags.

**Comment by Moobien** [comment]
> > never needed a research to begin with. this is just convoluting a problem that never existed lol
> 
> They kinda did, actually. In vanilla, all the CLIMBABLE blocks that aren't ladders or scaffolds are vines. So this change essentially restores the previous behaviour that vines require the research and other things don't.

yet it all worked fine before making it a research

**Comment by uecasm** [comment]
Please stop arguing that point, because you're missing it.  The pathfinding was previously a lot more limited in what blocks were considered climbable at all.  It was recently changed to improve support by using a standard vanilla tag instead of hard-coding things.  Scaffolds were a casualty in that change, which I am attempting to correct with this PR.

**Comment by Moobien** [comment]
> Please stop arguing that point, because you're missing it. The pathfinding was previously a lot more limited in what blocks were considered climbable at all. It was recently changed to improve support by using a standard vanilla tag instead of hard-coding things. Scaffolds were a casualty in that change, which I am attempting to correct with this PR.

ohh ok that makes sense now that you explained it. you forget I can't read/understand the code.

**Comment by uecasm** [comment]
Though TBF, this PR makes the rule "climbable things require the Vines research by default, but the Free Climb blocks [ladders, scaffolds] can be climbed without the research".

An alternative rule, that some people might prefer, would be "all climbable blocks are free by default, but specifically Vines require the Vines research".  I could write that version instead, if feedback (esp. from leads) prefers it.  But the implication from the code changes is that at least some of the former was intended.

**Comment by Raycoms** [comment]
> > Please stop arguing that point, because you're missing it. The pathfinding was previously a lot more limited in what blocks were considered climbable at all. It was recently changed to improve support by using a standard vanilla tag instead of hard-coding things. Scaffolds were a casualty in that change, which I am attempting to correct with this PR.
> 
> ohh ok that makes sense now that you explained it. you forget I can't read/understand the code.

The rule usually is: Don't argue about stuff you don't understand =P

**Comment by Moobien** [comment]
> > > Please stop arguing that point, because you're missing it. The pathfinding was previously a lot more limited in what blocks were considered climbable at all. It was recently changed to improve support by using a standard vanilla tag instead of hard-coding things. Scaffolds were a casualty in that change, which I am attempting to correct with this PR.
> > 
> > 
> > ohh ok that makes sense now that you explained it. you forget I can't read/understand the code.
> 
> The rule usually is: Don't argue about stuff you don't understand =P

addendum rule: don't throw code at the person who doesn't understand coding and expect them to understand :P *glares at Thodor and Ray*

**Comment by Thodor12** [comment]
Nobody asked you to look at this, you invited yourself to comment on this PR.

File: src/main/java/com/minecolonies/core/entity/pathfinding/PathfindingUtils.java (hunk 1 above)
Comment (someaddons) [reply src/main/java/com/minecolonies/core/entity/pathfinding/PathfindingUtils.java]: instanceof ladder is intentional here for automatic mod compat

Comment (Thodor12) [reply src/main/java/com/minecolonies/core/entity/pathfinding/PathfindingUtils.java]: You can technically just have both can't you? `blockState.getBlock instanceof LadderBlock || blockState.is(ModTags.freeClimbBlocks)`

**Comment by someaddons** [comment]
Btw the scaffolding & others being part of the research has been a thing since ~5 months or so :)

File: src/main/java/com/minecolonies/core/entity/pathfinding/PathfindingUtils.java (hunk 1 above)
Comment (uecasm) [reply src/main/java/com/minecolonies/core/entity/pathfinding/PathfindingUtils.java]: Are there mods that derive from LadderBlock?

But they'd still have to be added to `CLIMBABLE` explicitly anyway.  Though yeah, it could check both.

**Comment by uecasm** [comment]
Scaffolds work without research in 1.19 though 😛

File: src/main/java/com/minecolonies/core/entity/pathfinding/PathfindingUtils.java (hunk 1 above)
Comment (someaddons) [reply src/main/java/com/minecolonies/core/entity/pathfinding/PathfindingUtils.java]: ye there is a bunch of mods that do that for sure^^

**Comment by Shadizar** [comment]
Can't scaffolding just be climbable without any research or tags, and the modded stuff can use the tags and/or research?

**Comment by Raycoms** [comment]
> Can't scaffolding just be climbable without any research or tags, and the modded stuff can use the tags and/or research?

Tags has nothing to do with the tag tool.

**Comment by Shadizar** [comment]
Ah ok
Sorry for the churn
Just trying to understand how to keep my style  working & how to keep using scaffolding in play, will wait for clarity

**Review by someaddons — APPROVED** [review]
