### PR TITLE
Fancy fixes

### LINKED ISSUE #10358: Guards not going to hospital when sick
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-.1.1.696

### Structurize Version

1.20.1-1.0.760

### Related Mods and their Versions

_No response_

### Current Behavior

Guards will not go to the hospital, Specifically barracks guards.
image

They will not move from that spot, It's not just that spot tho, it happens with the other hut's too. When it first happened, I showed the same issue to Thodor who then broke the barrack's hut and slapped them a few times which then caused them to go straight to the hospital. However, 6 hours later, the same issue arose so i've created a bug ticket. I'm still in the server if anyone wants to come check it out :P

Another thing I would like to mention is that when they are given the cure to their illness, That they don't use it at all. 

Another thing I would like to mention is that the doctor doesn't come to any of the sick guards.

### Expected Behavior

Run to the hospital to get healed.

### Reproduction Steps

Join the multiplayer event server and teleport to me. Otherwise get the fortress style, or some other style, i'm not sure if it's just with the fortress style, But once you've got the fortress barracks, get a few guards that are sick and follow them around until they go to a barrack's hut and get stuck 🤔

### Logs

Why is this a requirement? Not everyone crashes..

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #10462: Ladder Dancies Part II
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

Raid comp

### Structurize Version

Raid comp

### Related Mods and their Versions

Raid comp

### Current Behavior

Guards are still getting stuck at the top of the barracks ladders. It seems one will try to go up, get stuck, and then the whole barrack group will get jammed and they're just having a grand time in the mosh pit. I stood watching a good five minutes or so, left and came back a couple of times after that. Still there! I'm re-reporting as I promised I would Ray. Best of luck. As an aside, I even had a raid at this barracks and these guards, despite being closest, failed to respond to the injuries of their fellows. So it IS affecting gameplay significantly.

### Expected Behavior

Go up and down ladders like, you know, a normal human being. Ha!

### Reproduction Steps

Have Fortress barracks and a wall for them to patrol. That is all you need to recreate the epic ladder dance parties!

### Logs

raidcomp

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #10464: Food update Part 2 Couriers stealing food from restaurant and shenanigans
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

Raid comp

### Structurize Version

Raid comp

### Related Mods and their Versions

Raid comp

### Current Behavior

Ok, I have some minimum stocks set in the restaurant from before the food update, but only for 2 stacks. Imagine my surprise when I found the cookery hoarding 14 stacks of stuffed pita and not delivering it to the restaurant. For only working on request, seems weird, right? So I took the stuffed pita and put it in the restaurant racks. 

I discovered a couple hours later that the couriers had absconded to the warehouse with almost all the stuffed pita again. Along with most everything else the restaurant *should* have had in stock. Couriers are not supposed to take food OUT of the warehouse, right?

I've seen this behavior with non-food items as well. A request is made, the item is made, but it is never delivered. The request is not fulfilled... so the crafter just makes more, and more, and more! Until next thing you know you've got about a thousand stuffed pita, or nearly 500 iron gates... Either in the hut of the crafter that made them, or sitting in the warehouse.

### Expected Behavior

Things get delivered to their destination and then stay there.

### Reproduction Steps

Just pay very close attention to your cookery and it should become apparent they are not working as intended. Hopefully you catch it *before* you have nearly a thousand of one food item....

### Logs

Raidcomp

### Anything else?

Also being reported on 1.21 that couriers are stealing food from the restaurant. Will try to get that individual to comment as well with their experience.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #10469: Apple Pie is not among the baker's recipes
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.1.740-snapshot

### Structurize Version

1.0.760-snapshot

### Related Mods and their Versions

_No response_

### Current Behavior

When adding the apple pie to the menu, the chef requests the finished item, despite it being craftable.  However, the baker has no knowledge of the recipe, and as such cannot make it on request.

### Expected Behavior

I add apple pie to the menu, the chef requests the baker make apple pies, the baker finds the recipe and bakes it.

### Reproduction Steps

1. Add Apple Pie to menu.
2. Check Requests on clipboard
3. See it request the finished item.

### Logs

https://www.dropbox.com/scl/fi/651qd0dqy6hr2cox7q1ju/latest.log?rlkey=64cbv8qu2p1ur07d004wubafd&st=4jf8y9nv&dl=1

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #10358
Closes #10462
Closes #10464 
Closes #10469 

# Changes proposed in this pull request
- Fix apple pie assignment
- Make barracks guard not tag along when sick etc
- Stop ladder dancies Number 2 (Mojang does weird things)
- Stop couriers from picking up food at restaurant
- Rotten potatoe right click on citizen makes them sick (surprised?)

## Testing
- [x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/core/entity/citizen/EntityCitizen.java [hunk 1]
```diff
@@ -1514,6 +1546,193 @@ private void performMoveAway(@Nullable final Entity attacker)
         }
     }
 
+    @Override
+    public void travel(Vec3 p_21280_)
```
Comment (someaddons) [inline src/main/java/com/minecolonies/core/entity/citizen/EntityCitizen.java]: I'm not sure if this is a good idea 😅  what did you change in here compared to vanilla?

Comment (Raycoms) [reply src/main/java/com/minecolonies/core/entity/citizen/EntityCitizen.java]: The place with the comment

Comment (someaddons) [reply src/main/java/com/minecolonies/core/entity/citizen/EntityCitizen.java]: shouldnt it be enough to just override onclimbable?

**Review by someaddons — APPROVED** [review]
