### PR TITLE
Smeltercrafter/reliability

### LINKED ISSUE #5447: Smelter AI Error
Version: 0.13.64-alpha

### Expected behavior
No AI error

### Actual behaviour
The stone smelter has an AI error:
[minecolonies/]: Statemachine for transition com.minecolonies.api.entity.ai.statemachine.AITarget@797c93c0 threw an exception:
java.lang.NullPointerException: null
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIRequestSmelter.craft(AbstractEntityAIRequestSmelter.java:384) ~[?:0.13.64-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[?:0.13.64-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148) ~[?:0.13.64-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:134) ~[?:0.13.64-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126) ~[?:0.13.64-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:105) ~[?:0.13.64-ALPHA]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:130) ~[?:0.13.64-ALPHA]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?]
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:368) ~[?:1.15-2.11m]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:1307) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159) ~[?:?]
	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:347) ~[?:0.13.64-ALPHA]
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:388) ~[?:0.13.64-ALPHA]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:536) [?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

### Steps to reproduce the problem
No idea, just loaded the world, let it finish townhall4 and walked around giving new build orders when I saw the AI error.

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log: https://gist.github.com/MatthiasMann/dc83959d722e7652e447299dff964cb8

### PR DESCRIPTION
**Pull request by Mekle001**
Closes #5447 

# Changes proposed in this pull request:
- Make the smeltercrafters track what is in furnaces better, and what they pull out
- Fix AI Error due to no defined fuels. 
- Tweak fuel handling behavior further to fall in line with upgraded tracking

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingSmelterCrafter.java [hunk 1]
```diff
@@ -106,6 +106,13 @@ public int getMaxBuildingLevel()
         return builder.build();
     }
 
+    @Override
+    public int buildingRequiresCertainAmountOfItem(final ItemStack stack, final List<ItemStorage> localAlreadyKept, final boolean inventory)
+    {
+        localAlreadyKept.addAll(getAllowedFuel().stream().map(is -> new ItemStorage(is)).filter(i -> i.getItemStack().equals(stack)).collect(Collectors.toCollection(ArrayList::new)));
+        return super.buildingRequiresCertainAmountOfItem(stack, localAlreadyKept, inventory);
+    }
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingSmelterCrafter.java]: Why would we store all allowed fuel as already kept?

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java [hunk 2]
```diff
@@ -61,13 +63,28 @@ public AbstractEntityAIRequestSmelter(@NotNull final J smelteryJob)
...
+    }
+
     @NotNull
     @Override
     protected List<ItemStack> itemsNiceToHave()
     {
         return getOwnBuilding().getAllowedFuel();
     }
 
+    protected int getExtendedOutputCount(final ItemStack primaryOutput)
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java:85]: @Override

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingSmelterCrafter.java (hunk 1 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingSmelterCrafter.java]: besides being an expensive stream, I don't think this is doing what you think it is. You put in the localAlreadyKept the blocks you did not dump. This way it will dump them. What you want to do is to check if stack is part of allowed fuel and then if localAlreadyKept contains 64 of allowed fuel. If not, then you return the quantity yu want to dump (to make sure at least 64 stay in the workers inv), else you'll return stack.size and if not allowed fuel you return super

Comment (MatthiasMann) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingSmelterCrafter.java]: As you are filtering only on the ItemStack and not on the ItemStorage it would make sense to swap the order of operations to prevent creating unneeded ItemStorage instances:
localAlreadyKept.addAll(getAllowedFuel().stream().filter(i -> i.equals(stack)).map(ItemStorage::new).collect(Collectors.toCollection(ArrayList::new)));

Comment (Mekle001) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingSmelterCrafter.java]: This code is gone.

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/5455/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java [hunk 3]
```diff
@@ -272,6 +302,10 @@ private IAIState checkIfAbleToSmelt(final int amountOfFuel, final boolean checkS
             }
         }
 
+        if(furnaceBurning)
+        {
+            //Todo: Scalable Delay
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java:307]: for the scalable Delays you can either use setDelay(ticks) which pauses the AI for X ticks, or add some local counter var.

**Review by someaddons — COMMENTED** [review]
Looks good, apart from the TODO's still in there?

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java (hunk 3 above)
Comment (Mekle001) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java:307]: Yeah, I actually had some in there, but removed them and put the todos in to mark where I wanted them in the next phase. That's phase is where I work the primary and secondary stats into the behavior. Better parallelization on primary, and more responsive on secondary (thus the scalable delays)

**Review by someaddons — APPROVED** [review]
