### PR TITLE
Fix/several

### LINKED ISSUE #4318: Colonists get stuck in Blacksmith
### Minecolonies version
Version: 0.10.680-release-universal.jar
Minecraft 1.14.4

### Expected behavior
I expect colonist to go in and out of the building normally.

### Actual behaviour
What actually happens is they go into the level two stone blacksmith and get stuck in the courtyard on the left. I'm unsure if it also happens at level one or not, upgraded too quickly to tell.

image

### Steps to reproduce the problem

1. Build a Stone style Blacksmith
2. Upgrade to level two, and have some requests come in that require the blacksmith to work.
3. Eventually, this will happen.
4. ... Profit

### Observations
I noticed this stopped being an issue (IE, the workers stopped getting stuck here) after I upgraded the blacksmith to level 3 and the design changed to a room.
Also, while this was an issue (at level two), I broke the cobbletone wall leading out of the little courtyard, and with a little bumping, got them on their way again. Didn't notice them get stuck again as long as the courtyard wasn't enclosed.

### LINKED ISSUE #4333: Scan tool issues
Mincolonies 0.10.696-ALPHA  and  Structurize 0.10.250-ALPHA

When using the scan tool, replace doesn't keep the rotation of some of the blocks, specifically the structurize blocks, and at least the fences. Fences aren't "connecting" like they should and will sometimes have connectors where there shouldn't be any. 

Sometimes after selecting the corners of a scan area, when clicking in air to get the outline, it deselects the area and only selects the air block.

### LINKED ISSUE #4339: [1.15][Bug] Builder freezes whenever he runs out of resources.
Minecolonies version: minecolonies-0.10.716-RELEASE-universal.jar
Minecraft 1.15.2

### Expected behavior
When provided with adequate food and materials the builder eventually builds things.

### Actual behaviour
Builder will build until he runs out of materials, instead of creating a request or returning to his building he stops right next to his base and stands there permanently. See Screenshot below.
If I finish supplying all materials for a building to the builders hut then recall the worker he will resume after a short delay(2-3 sec) and finish the building. If I don't recall the worker he will stand there indefinitely, ignoring night time, rain, etc.

Builder Stuck

### Steps to reproduce the problem
1. Install Mod
2. Try to build a building and let him run out of supplies.
3. Builder gets stuck
4. Supply builders hut, shove worker, whatever. He won't resume until you recall him.
[latest.log](https://github.com/ldtteam/minecolonies/files/4220094/latest.log)

### Logs: Latest.log and crashlog at https://gist.github.com/
On reviewing the log I see a ton of messages from wall jump... possibly causing lag and leading to path finding issues?? Will try without the wall jump mod and report back if this is a compatibility issue.

### LINKED ISSUE #4350: [1.15.2] No Event list generated for Digital Miner from Mekanism
Modpack: Just Not Enough Mods 2 v0.4.5
Minecolonies RELEASE-0.10.716

In previous versions of Minecolonies an Event would be created when a Digital Miner tried to mine within a Colony.

As of RELEASE-0.10.716 this is no longer the case.

### LINKED ISSUE #4353: Deco Block hit box in the wrong location
When placing the deco block, it now shows up on the block you place it on, but the hit box is on the opposite side of the "block" area.

image

### LINKED ISSUE #4354: Blacksmith not accepting shield recipe
Newest 1.15 release mc .716 St .254

When trying to teach the blacksmith the shield recipe, it says "Unable to store the blueprint. Either the blacksmith has no space for any more blueprints, or the blueprint doesn't correspond with its profession.

### LINKED ISSUE #4355: Decoration bug and others
minecolonies-0.10.716-RELEASE-universal.jar
minecraft 1.15.2

When I try to build a decoration such as the fortress angle wall, the builder only builds the 1st on the list and cant build the other 3. Also it gives me problems with the orientation. the field had the same problem: the builder couldn't build the 2nd or 3rd one, although the orientation was not an issue here.

There are also lots of visual bug: the shigle have shadow problems, some building chest are misplaced inside the building (the builder's chest is facing a wall for example) and have shadow problems, the racks shift places when placed by the builder (you can access the storage by clicking both on the actual position of the rack and where the racks looks to be).

I play the RaoulTech modpack so some of this can be due to a compatibility problem.

list of mods:
A Lib 
Additional Enchanted Miner 
Alchemistry
Ama's Damage Indicator
Biomes O' Plenty 
Blue Power 
Bonsai Trees 2
Chem Lib 
Corpse 
Default Amplified Biomes(DAB)
Dimensional Dungeons
Essentials
Expanded Storage
Extra Disks
Falling Tree 
Fast Leaf Decay
Gauges and Switches
Hwyla 
Inventory Sorter
Just Enough Items (JEI
Large Fluid Tank
Libnonymous
Mekanism
Mekanism Generators 
Mekanism Tools 
Minecolonies 
Miner's Helmet
Morpheus
OpenBlocks Elevator 
Ore Excavation
Packing Tape
Patchouli
Planet Evelon 
Potions Master
Ranged Pumps 
Refined Storage
Refined Storage Addons
Ropes Mod!
Scalable Cat's Force 
Serene Seasons 
Simple Chunk Loaders 
Spice of Life: Carrot Edition
Storage Drawers
Structurize
Tool Belt 
TorchBowMod 
Tubes Reloaded 
U Team Core 
Useful Backpacks 
ValkyrieLib 
Water Erosion (Forge and Fabric)
Xaero's Minimap (Fair-play Edition)
Xaero's World Map

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #4350
Closes #4318
Closes #4339
Closes #4333
Closes #4355
Closes #4354 
Closes #4353 
 
# Changes proposed in this pull request:
- Unregister event handlers properly
- Vastly improve jump pathfinding (for half and not full blocks)
- Improves scan tool issues

Review please

### CODE REVIEW

**Review by someaddons — DISMISSED** [review]

File: src/main/java/com/minecolonies/coremod/client/gui/WindowResourceList.java [hunk 1]
```diff
@@ -114,6 +114,11 @@ public void onOpened()
         pullResourcesFromHut();
 
         final ScrollingList resourceList = findPaneOfTypeByID(LIST_RESOURCES, ScrollingList.class);
+        if (resourceList == null)
+        {
+            close();
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowResourceList.java:121]: Message into chat why it was closed during opening
Same for close() above

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/AbstractPathJob.java [hunk 2]
```diff
@@ -978,9 +979,23 @@ private int handleTargeNotPassable(@Nullable final Node parent, @NotNull final B
...
         {
+            double dif = bb.getEnd(Direction.Axis.Y);
+            final double parentY = target.getCollisionShape(world, pos).getEnd(Direction.Axis.Y);
+            dif = dif + 1 - parentY;
+            if (dif < 1.3)
+            {
+                return pos.getY() + 1;
+            }
+            if (target.getBlock() instanceof StairsBlock
+                  && dif - 0.5 < 1.3
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/AbstractPathJob.java]: At least comment for 1.3 constant

**Comment by marchermans** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/4351/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Review by someaddons — DISMISSED** [review]

File: src/main/java/com/minecolonies/coremod/blocks/BlockDecorationController.java [hunk 3]
```diff
@@ -55,10 +55,10 @@
     /**
      * The bounding boxes.
      */
-    protected static final VoxelShape AABB_NORTH = VoxelShapes.create(0.4125D, 0.375D, 0.950D, 0.5875D, 0.625D, 1.0D);
-    protected static final VoxelShape AABB_SOUTH = VoxelShapes.create(0.4125D, 0.375D, 0.0D, 0.5875D, 0.625D, 0.050D);
-    protected static final VoxelShape AABB_WEST  = VoxelShapes.create(0.950D, 0.375D, 0.4125D, 1.0D, 0.625D, 0.5875D);
-    protected static final VoxelShape AABB_EAST  = VoxelShapes.create(0.0D, 0.375D, 0.4125D, 0.050D, 0.625D, 0.5875D);
+    protected static final VoxelShape AABB_SOUTH = VoxelShapes.create(0.4125D, 0.375D, 0.950D, 0.5875D, 0.625D, 1.0D);
+    protected static final VoxelShape AABB_NORTH = VoxelShapes.create(0.4125D, 0.375D, 0.0D, 0.5875D, 0.625D, 0.050D);
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/blocks/BlockDecorationController.java:59]: ?? Why where these swapped all of a sudden?

File: src/main/java/com/minecolonies/coremod/client/gui/WindowResourceList.java (hunk 1 above)
Comment (marchermans) [reply src/main/java/com/minecolonies/coremod/client/gui/WindowResourceList.java:121]: Agreed!

File: src/main/java/com/minecolonies/coremod/colony/Colony.java [hunk 4]
```diff
@@ -866,6 +866,10 @@ public void onWorldUnload(@NotNull final World w)
             return;
         }
 
+        if (eventHandler != null)
+        {
+            MinecraftForge.EVENT_BUS.unregister(eventHandler);
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/colony/Colony.java:871]: Good catch.

**Review by marchermans — DISMISSED** [review]
Some minor things. But in general good to go.

File: src/main/java/com/minecolonies/coremod/blocks/BlockDecorationController.java (hunk 3 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/blocks/BlockDecorationController.java:59]: Because they weren't matching the model.
In 1.15 the model rotated due to some placement differences.
