### PR TITLE
#7754 and #7751

### LINKED ISSUE #7751: Missing some localization strings
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:1.0.106-ALPHA
- Structurize Version:0.13.252-ALPHA

## Steps to reproduce the issue
A. `tile.bed.occupied`
1. At night, player tries to sleep on the bed with sleeping citizen;
2. Chat message shows `tile.bed.occupied`

B. 3 Spawn eggs doesn't have their own localization name:
```
item.minecolonies.mummyegg
item.minecolonies.mummyarcheregg
item.minecolonies.pharaoegg
```
1. Enter `@minecolonies egg` in JEI;
2. I found 3 Spawn eggs doesn't have their own localization name.

### LINKED ISSUE #7754: Gravedigger reports it has an AI issue
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-1.0.111-ALPHA-universal, structurize-0.13.252-ALPHA-universal
- latest Direwolf20 pack for mc 1.16.5 but bumped the two aforementioned mods to their current release above to see if the problem had been resolved in a more current version of minecolonies but it persists in spite of the updates. 

### Logs

- latest.log: https://gist.github.com/WebDragon/4e36989dc1f2fe287df4f9748d1c608d

## Steps to reproduce the issue / details

Problem occurred possibly after upgrading their hut (Stone type) to either tier 3 or tier 4 (it was at tier 4 before I noticed the villager wasn't coming around to work but was instead malingering around their bed). I also have a Jungle mystical site immediately adjacent to the graveyard, also at tier 4.

Just reporting the AI issue. 

### Notes

I may try a teardown and rebuild if you think that would be a good idea. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #7754 
Closes #7751
Closes #

# Changes proposed in this pull request:
- Improved pathing considering waypoints
- fixed localization string
- Adjust sick handling to statemachine
- Fix stuck bug with low health
- Improved walk command debugging

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java [hunk 1]
```diff
@@ -135,7 +135,7 @@
     /**
      * The current position the worker should walk to.
      */
-    protected BlockPos walkTo = null;
+    public BlockPos walkTo = null;
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java]: Make this a getter and a setter instead of a public field

**Review by marchermans — CHANGES_REQUESTED** [review]
Generally good but the field access should be wrapped.

**Review by marchermans — APPROVED** [review]
