### PR TITLE
Prevent building upgrade fireworks from damaging nearby entities

### LINKED ISSUE #9427: [BUG] [1.19.2] Fireworks At Building Completion Can Break Things
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.194-BETA

### Structurize Version

1.19.2-1.0.649-BETA

### Related Mods and their Versions

Forge: 43.2.21

### Current Behavior

When a building completes that is in a confined space, the fireworks can cause some blocks to break. In a custom build of mine they are destroying the armor stand, which doesn't even drop when destroyed- making the situation more annoying.

### Expected Behavior

Fireworks not to break blocks.

Perhaps, if possible, they should be a visual-only effect rather than using real fireworks?

Otherwise a way to disable the fireworks would be nice.

### Reproduction Steps

1. Build a building (in my case it is a small custom guard tower made to go in a much larger build).
2. When completed the fireworks go off, destroying the armor stand that is part of the build.

### Logs

N/A

### Anything else?

Screenshot of the custom guard tower:

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Thodor12**
Closes #9427

# Changes proposed in this pull request:
- Create an overwritten firework entity which does not include the explosion damage code.
- Tested in colonial barracks (which has loose tower interiors), standing close by the fireworks, did not take any damage.

[X] Yes I tested this before submitting it.
[ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/api/java/com/minecolonies/api/util/NoDamageFireworkRocketEntity.java [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+import net.minecraft.world.level.Level;
+import net.minecraft.world.level.gameevent.GameEvent;
+import net.minecraft.world.phys.BlockHitResult;
+import net.minecraft.world.phys.EntityHitResult;
+import org.jetbrains.annotations.NotNull;
+
+/**
+ * Overwritten {@link FireworkRocketEntity} for spawning on buildings that does not damage entities in the vicinity.
+ */
+public class NoDamageFireworkRocketEntity extends FireworkRocketEntity
```
Comment (Raycoms) [inline src/api/java/com/minecolonies/api/util/NoDamageFireworkRocketEntity.java]: formatting in class is off and doc on non @Override methods

**Comment by someaddons** [comment]
Pretty sure you'll need to actually register the custom entity for multiplayer

File: src/api/java/com/minecolonies/api/util/FireworkUtils.java [hunk 2]
```diff
@@ -40,16 +40,16 @@ private FireworkUtils()
      */
     public static void spawnFireworksAtAABBCorners(final Tuple<BlockPos, BlockPos> realaabb, final Level world, final int explosionLevel)
     {
-        final FireworkRocketEntity firework = new FireworkRocketEntity(world, realaabb.getB().getX(), realaabb.getB().getY(), realaabb.getB().getZ(), genFireworkItemStack(explosionLevel));
+        final FireworkRocketEntity firework = new NoDamageFireworkRocketEntity(world, realaabb.getB().getX(), realaabb.getB().getY(), realaabb.getB().getZ(), genFireworkItemStack(explosionLevel));
         world.addFreshEntity(firework);
 
-        final FireworkRocketEntity fireworka = new FireworkRocketEntity(world, realaabb.getB().getX(), realaabb.getB().getY(), realaabb.getA().getZ(), genFireworkItemStack(explosionLevel));
+        final FireworkRocketEntity fireworka = new NoDamageFireworkRocketEntity(world, realaabb.getB().getX(), realaabb.getB().getY(), realaabb.getA().getZ(), genFireworkItemStack(explosionLevel));
```
Comment (Raycoms) [inline src/api/java/com/minecolonies/api/util/FireworkUtils.java]: Still needs to make sure > above parent y

**Review by Raycoms — APPROVED** [review]

**Review by someaddons — APPROVED** [review]
