### PR TITLE
finish the tree stuff

### LINKED ISSUE #6657: Bunch of issues I've met during playing
List of random nitpicks/issues to fix:
_If you are not from dev team and want to comment please create a new issue and describe it properly_

- [x] 1) negative and weird percentage during requirements gathering phase, #6726
image
- [x] 2) ~lumberjack spinning when idling (when having no work)~ overridden by 9, #6678
- [x] 3) lumberjack restriction area has either bad chat info or does not work properly - not sure if it's 3d or 2d, if 3d then bad chat info, if 2d then he does not detect trees correctly - should be probably 2d from level y, #6678
- [x] 4) chest are still considered as storage but citizens do not consider them when searching items
- [x] 5) lumberjack should have separate toggles for planting and chopping - requires small gui redesign (box should have two lines probably: itemicon (left-aligned), first line sapling name, second line two toggles - chop and plant
- [x] 6) citizen should have stronger ai task for doors of citizen huts (houses), the current one is lenient cause of chunk-loading, special handling or stronger task should be used so doors are always closed during night
#### edit 1:
- [x] 7) remove alpha from tool textures, #6726
image
- [ ] 8) minecolonies build tool requires having hut block to display its schematic, this is rather problematic when using preview sharing since other players are required to have the block too otherwise their build tool resets the schematic to decos (to raven - I consider this to be a bug)
#### edit2:
- [x] 9) (overrides 2) lumberjack looping in no_tree_found and start_working stages when no tree found, #6678
a) searchIncrement is never resetted
b) [this code](https://github.com/ldtteam/minecolonies/blob/version/1.16.3/src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java#L335) is problematic in setTree because the setTree doesn't take restriction in account thus lumber just spins between restriction area and building
c) waitBeforeCheckingAgain is not working as intended, the AI never pauses if no_tree_found state is hit
- [x] 10) [code](https://github.com/ldtteam/minecolonies/pull/6659/files#diff-9623ce8a29e14a2b175b5be13523cb1a6fb53ece1efb1d92d0ec976d83557841L515-L521) add new ctor to our container and remove packet buffer, #6676
#### edit3:
- [x] 11) block placing still not working correctly in terms of block update, #6677
- [x] 12) waypoints not rendering, blame me - it's working
- [x] 13) add partial tick to colony border rendering, #6675

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #6657

# Changes proposed in this pull request:
- make a new methods for giving tools to hotbar
- trying to fix lumberjack ai being stuck or looping
- fix lumberjack tool setup
- fix lumberjack restriction mode

Thanks for @Nightenom for most of the work of this.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java [hunk 1]
```diff
@@ -109,6 +109,7 @@
     public StandardRequestManager(@NotNull final IColony colony)
     {
         this.colony = colony;
+
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java]: this

File: src/main/resources/assets/minecolonies/lang/en_us.json [hunk 2]
```diff
@@ -59,10 +59,13 @@
...
-  "item.minecolonies.scepterlumberjack.usedend": "Second position set.",
-  "item.minecolonies.scepterlumberjack.restrictiontoobig": "Area %s is too large. Maximum restricted area for the Forester is %s blocks.",
-  "item.minecolonies.scepterlumberjack.restrictionset": "Forester restricted area set. Size is %s blocks. Max size is %s blocks.",
+  "item.minecolonies.scepterlumberjack.usedstart": "First position set. (Click same position to finish)",
+  "item.minecolonies.scepterlumberjack.usedend": "Second position set. (Click same position to finish)",
+  "item.minecolonies.scepterlumberjack.restrictiontoobig": "An area of %d blocks is too large. The maximum restricted area for the Forester is %d blocks.",
+  "item.minecolonies.scepterlumberjack.restrictionset": "Forester restricted area set (x: %d to %d, z: %d to %d, area: %d blocks). The max size is %d blocks.",
+  
+  "minecolonies.config.maxtreesize": "Max tree size",
+  "minecolonies.config.maxtreesize.comment": "Maximal log count in one tree during lumberjack tree search.",
```
Comment (Nightenom) [inline src/main/resources/assets/minecolonies/lang/en_us.json]:
```suggestion
  "minecolonies.config.maxtreesize.comment": "Max log count in one tree for the Forester to check during their tree search.",
```
> It's not the lumberjack anymore :D

By Raven in the old PR

File: src/main/java/com/minecolonies/coremod/items/ItemScepterLumberjack.java [hunk 3]
```diff
@@ -107,22 +101,38 @@ private void storeRestrictedArea(final PlayerEntity player, final Hand hand, fin
             return;
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/items/ItemScepterLumberjack.java:99]: Can't comment on lines that are not in this commit, but maxArea was changed in the older PR

**Review by Nightenom — COMMENTED** [review]
Honestly, the changes you made to ItemScepterLumberjack are completely different, not like just remove the air click action from AbstractItemWithPosSelector

File: src/main/resources/assets/minecolonies/lang/en_us.json [hunk 4]
```diff
@@ -59,10 +59,13 @@
...
-  "item.minecolonies.scepterlumberjack.usedstart": "First position set.",
-  "item.minecolonies.scepterlumberjack.usedend": "Second position set.",
-  "item.minecolonies.scepterlumberjack.restrictiontoobig": "Area %s is too large. Maximum restricted area for the Forester is %s blocks.",
-  "item.minecolonies.scepterlumberjack.restrictionset": "Forester restricted area set. Size is %s blocks. Max size is %s blocks.",
+  "item.minecolonies.scepterlumberjack.usedstart": "First position set. (Click same position to finish)",
+  "item.minecolonies.scepterlumberjack.usedend": "Second position set. (Click same position to finish)",
+  "item.minecolonies.scepterlumberjack.restrictiontoobig": "An area of %d blocks is too large. The maximum restricted area for the Forester is %d blocks.",
+  "item.minecolonies.scepterlumberjack.restrictionset": "Forester restricted area set (x: %d to %d, z: %d to %d, area: %d blocks). The max size is %d blocks.",
+  
+  "minecolonies.config.maxtreesize": "Max tree size",
```
Comment (ravenbuilder934) [inline src/main/resources/assets/minecolonies/lang/en_us.json]: Title should be capitalized

File: src/main/resources/assets/minecolonies/lang/en_us.json [hunk 5]
```diff
@@ -59,10 +59,13 @@
   "minecolonies.config.listofplantables.comment": "The items and item-tags that the Florist can plant.",
 
   "item.minecolonies.scepterlumberjack": "Forest Tool",
-  "item.minecolonies.scepterlumberjack.usedstart": "First position set.",
-  "item.minecolonies.scepterlumberjack.usedend": "Second position set.",
-  "item.minecolonies.scepterlumberjack.restrictiontoobig": "Area %s is too large. Maximum restricted area for the Forester is %s blocks.",
-  "item.minecolonies.scepterlumberjack.restrictionset": "Forester restricted area set. Size is %s blocks. Max size is %s blocks.",
+  "item.minecolonies.scepterlumberjack.usedstart": "First position set. (Click same position to finish)",
```
Comment (ravenbuilder934) [inline src/main/resources/assets/minecolonies/lang/en_us.json]:
```suggestion
  "item.minecolonies.scepterlumberjack.usedstart": "First position set. Click the same position to finish.",
```
For the second position as well

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java [hunk 6]
```diff
@@ -711,7 +705,7 @@ private void addAndSearch(@NotNull final World world)
         }
         for (int locX = locXMin; locX <= locXMax; locX++)
         {
-            for (int locY = locYMin; locY <= MAX_TREE_SIZE; locY++)
+            for (int locY = locYMin; !world.isYOutOfBounds(locY); locY++)
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java]: world.func_234938_ad_() is the right call for this, yours is just the static version

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java [hunk 7]
```diff
@@ -888,8 +888,11 @@ public TreePathResult moveToTree(final BlockPos startRestriction, final BlockPos
         @NotNull final BlockPos start = AbstractPathJob.prepareStart(ourEntity);
         final BlockPos buildingPos = ((AbstractEntityCitizen) entity).getCitizenColonyHandler().getWorkBuilding().getPosition();
 
+        final BlockPos furthestRestriction = BlockPosUtil.getRandomPosInBoxPlane(BlockPosUtil
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java]: whatfor do we need the furthest restriction?

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java [hunk 8]
```diff
@@ -1341,4 +1398,14 @@ public void setPathingOptions(final PathingOptions pathingOptions)
         DROPABLE,
         NOT_PASSABLE
     }
+
+    /**
+     * Check if in restricted area.
+     * @param pos the pos to check.
+     * @return true if so.
+     */
+    public boolean isInRestrictedArea(final BlockPos pos)
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java:1407]: could even make this a general canWalkNode(pos) which just defaults to true and specialized jobs can override and then we dont need any restriction logic at the highest level which is only seeing use in the special cases anyways

File: src/main/java/com/minecolonies/coremod/items/ItemScepterLumberjack.java [hunk 9]
```diff
@@ -97,32 +91,46 @@ private void storeRestrictedArea(final PlayerEntity player, final Hand hand, fin
...
 
-        final BuildingLumberjack lumberjackBuilding = (BuildingLumberjack) abstractBuilding;
-        lumberjackBuilding.setRestrictedArea(startRestriction, endRestriction);
-        player.inventory.removeStackFromSlot(player.inventory.currentItem);
+        hut.setRestrictedArea(startRestriction, endRestriction);
     }
 
-    private void setPosition(final CompoundNBT compound, final String NBT, final BlockPos pos)
+    /**
+     * Continue the flux.
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/items/ItemScepterLumberjack.java]: this is rather odd javadoc

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java (hunk 8 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java:1407]: Well, in this use-case it's a specific pass function which we already override. The method itself is just a utility method we can call.

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java (hunk 7 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java]: to calculate the max pathing range mostly.

Comment (Nightenom) [reply src/main/java/com/minecolonies/coremod/entity/pathfinding/MinecoloniesAdvancedPathNavigate.java]: Since we search in the area from nearest to furthest so this somehow makes the heuristic work

**Review by marchermans — APPROVED** [review]

**Review by Mekle001 — APPROVED** [review]

**Review by marchermans — APPROVED** [review]

**Review by someaddons — APPROVED** [review]
