### PR TITLE
Fix/more crafting

### LINKED ISSUE #2091: Client crash - teaching crafting recipe.
### Minecolonies version

minecolonies-universal-1.12.2-0.8.7200

### Actual behaviour

- https://gist.github.com/ProsperCraft/b8f1246a4a4900f516e94c723f0b9c29

### Steps to reproduce the problem

1. Open the gui to teach citizens recipies.
2. Shift click a stack of sticks in.
3. Lock up
4. Crash.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #2091

# Changes proposed in this pull request:
- Fixes some more GUI issues
- Allows to shiftclick confirm to keep the buildTool open
- Fixes a few other crafting related issues.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java [hunk 1]
```diff
@@ -7,6 +7,7 @@
 import com.minecolonies.api.colony.requestsystem.resolver.IRequestResolver;
 import com.minecolonies.api.colony.requestsystem.token.IToken;
 import com.minecolonies.api.crafting.IRecipeStorage;
+import com.minecolonies.api.crafting.RecipeStorage;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java]: MINOR Remove this unused import 'com.minecolonies.api.crafting.RecipeStorage'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 64 issues
* ![CRITICAL][CRITICAL] 2 critical
* ![MAJOR][MAJOR] 56 major
* ![MINOR][MINOR] 5 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuildingWorker.java#L90](https://github.com/Minecolonies/minecolonies/blob/85e20a7f3aa060a24b2bffb0abab6da887f189cb/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L90): Remove this call from a constructor to the overridable "getBuildingLevel" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1699)
1. ![CRITICAL][CRITICAL] [CraftingGUIBuilding.java#L179](https://github.com/Minecolonies/minecolonies/blob/85e20a7f3aa060a24b2bffb0abab6da887f189cb/src/main/java/com/minecolonies/coremod/inventory/CraftingGUIBuilding.java#L179): Remove this call from a constructor to the overridable "onCraftMatrixChanged" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1699)
1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/85e20a7f3aa060a24b2bffb0abab6da887f189cb/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/85e20a7f3aa060a24b2bffb0abab6da887f189cb/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L169](https://github.com/Minecolonies/minecolonies/blob/85e20a7f3aa060a24b2bffb0abab6da887f189cb/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L169): The Cyclomatic Complexity of this method "updateResources" is 22 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L169](https://github.com/Minecolonies/minecolonies/blob/85e20a7f3aa060a24b2bffb0abab6da887f189cb/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L169): Refactor this method to reduce its Cognitive Complexity from 35 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L181](https://github.com/Minecolonies/minecolonies/blob/85e20a7f3aa060a24b2bffb0abab6da887f189cb/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L181): Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS135)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L298](https://github.com/Minecolonies/minecolonies/blob/85e20a7f3aa060a24b2bffb0abab6da887f189cb/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L298): Remove this unused method parameter "list". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L42](https://github.com/Minecolonies/minecolonies/blob/85e20a7f3aa060a24b2bffb0abab6da887f189cb/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L42): class "WindowBuildTool" has 41 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/85e20a7f3aa060a24b2bffb0abab6da887f189cb/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 63 issues
* ![CRITICAL][CRITICAL] 2 critical
* ![MAJOR][MAJOR] 56 major
* ![MINOR][MINOR] 4 minor
* ![INFO][INFO] 1 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuildingWorker.java#L89](https://github.com/Minecolonies/minecolonies/blob/5d34b5611ac79d49f493c8f4d7ebafb8280e0f4f/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L89): Remove this call from a constructor to the overridable "getBuildingLevel" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1699)
1. ![CRITICAL][CRITICAL] [CraftingGUIBuilding.java#L179](https://github.com/Minecolonies/minecolonies/blob/5d34b5611ac79d49f493c8f4d7ebafb8280e0f4f/src/main/java/com/minecolonies/coremod/inventory/CraftingGUIBuilding.java#L179): Remove this call from a constructor to the overridable "onCraftMatrixChanged" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1699)
1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/5d34b5611ac79d49f493c8f4d7ebafb8280e0f4f/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/5d34b5611ac79d49f493c8f4d7ebafb8280e0f4f/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L169](https://github.com/Minecolonies/minecolonies/blob/5d34b5611ac79d49f493c8f4d7ebafb8280e0f4f/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L169): The Cyclomatic Complexity of this method "updateResources" is 22 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L169](https://github.com/Minecolonies/minecolonies/blob/5d34b5611ac79d49f493c8f4d7ebafb8280e0f4f/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L169): Refactor this method to reduce its Cognitive Complexity from 35 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L181](https://github.com/Minecolonies/minecolonies/blob/5d34b5611ac79d49f493c8f4d7ebafb8280e0f4f/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L181): Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS135)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L298](https://github.com/Minecolonies/minecolonies/blob/5d34b5611ac79d49f493c8f4d7ebafb8280e0f4f/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L298): Remove this unused method parameter "list". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L42](https://github.com/Minecolonies/minecolonies/blob/5d34b5611ac79d49f493c8f4d7ebafb8280e0f4f/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L42): class "WindowBuildTool" has 41 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/5d34b5611ac79d49f493c8f4d7ebafb8280e0f4f/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Review by marchermans — APPROVED** [review]
