### PR TITLE
Div text

### LINKED ISSUE #5055: Signs and vines confuses colonists
### Version:
MC-TechColonies: Version: v 3.0 Minecraft Version: 1.15.2 (modded) forge-31.1.87
minecolonies-1.15.2-0.11.948-universal.jar
structurize-0.10.315-ALPHA.jar
(older versions as well)

### Expected behavior
Placing sings (or vines), colonists just ignore them. and walk through them.
Pathing would ignore signs / vines, and treat them as air. (perhaps an added weight for vines due to the lower speed it might involve)

### Actual behaviour
When a sign is in the path of a colonist, the colonist gets confused.
The colonist keeps turning around not knowing which direction to go. eventually it will but can take up to 10 seconds. The fortress build has signs everywhere, and it is obvious there.

As an aditional problem, pathing will try and not takes routes with signs. this especially was obvious on the Fortress set, where they rather walk over blocks around houses, and through other areas then to take the 1 block wide space with signs in it., when i removed the signs, or placed them higher, they picked the correct paths. 

### Steps to reproduce the problem
1. place a sign in the pathway of a colonist.
2. wait
3. Colonist walks over sign
4. Colonist gets confused 

### Logs: Latest.log and crashlog at https://gist.github.com/
logs not relevant i presume

### LINKED ISSUE #5110: Colonists are not aware fire will kill them.
### Minecolonies version # 
Version: minecolonies-1.15.2-0.11.948-universal

### Expected behavior
Colonists being smart enough to not walk into fire. 

### Actual behaviour
The Archery 4 and 5 huts, type Fortress, have an open fire in their design.  Colonists that just wander around sometimes walk into that fire and die.  

### Steps to reproduce the problem
Build an Archery level 4 or 5, type Fortress. Let some citizens walk around in it, and watch them walk into the fire and die.

So please make colonists smarter, or alternatively, do not use structures that have open fires that can be walked into. 

### Logs: Latest.log and crashlog at https://gist.github.com/
n/a

### LINKED ISSUE #5146: third page on npc crashes game
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!
Exact version, 0.11.957 (MC1.15.2)

-->

Version: 0.11.957

### Expected behavior
 some third page about the npc like the first two when you right click them 

- 

### Actual behaviour
 the game freezes for a second, saves the world, and proceeds to crash. -

- 

### Steps to reproduce the problem

1.  create town hall 
2.  get npc to spawn 
3.  right click them 
4. ... click the arrow at the top left twice

### Logs: Latest.log and crashlog at https://gist.github.com/
 https://gist.github.com/ItzMeDB/6d86003455e1ed721ccf5178acc716d2. 
- latest.log:
- crashlog:

### LINKED ISSUE #5190: Barabarian Texture is violet/black
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: minecolonies-1.15.2-0.11.958-universal

### Expected behavior

- Working textures

### Actual behaviour

- Broken Barbarian texture

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #5146
Closes #5055
Closes #5110
Closes #5190

# Changes proposed in this pull request:
- Some minor fixes
- Add full diversity textures to minecolonies entities
-

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/CitizenData.java [hunk 1]
```diff
@@ -76,6 +69,11 @@
      */
     private static final int MIN_SATURATION = 0;
 
+    /**
+     * Possible texture suffixes.
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/colony/CitizenData.java:73]: do these suffixes have a meaning?

**Review by someaddons — DISMISSED** [review]

File: src/main/java/com/minecolonies/coremod/colony/CitizenData.java (hunk 1 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/CitizenData.java:73]: I kept it generic on purpose because we can use this for more generic things in the future.
