### PR TITLE
Prevent some crashes

### LINKED ISSUE #10167: [BUG] <title> Multiple crash issues after updating
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.647

### Structurize Version

1.20.1-1.0.752

### Related Mods and their Versions

Forge: 47.3.1
Block UI: 1.20.1-1.0.186
Domum ornamentum: 1.20.1-1.0.199
Stylecolonies: 1.9
Create: 1.20.1-0.5.1.f

### Current Behavior

Firstly, I apologize if I do anything here that is wrong, I have never done a bug report here before, and was directed here from the discord.

Firstly, I noticed that I did not have the version of the mod that gave the stylecolonies steampunk style restaurant that included the cookery.  I was directed to change my options to allow alpha versions, and updated to the most recent versions.  At first this seemed to work okay, but then I noticed that 1) both my skin and the custom villager skins (I think from patreon donations?) had been replaced with vanilla skins, and also 2) almost all of the items from create, such a cogs, were no longer in JEI or Creative.

I attempted to fix this by updating JEI, and this led to the first full crash. Well, technically, the game simply wouldn't load, it went to the red loading screen and no further.  I removed the updated JEI, and then tried to join again.  It said "Invalid player data" despite this being a single world, and then would spit me out at the server menu.  I posted my logs from that on the discord, and was told to update several mods that had just gotten updates.

I did this, and this time made it into the game for about 1 second, after which it gave a long message about being "kicked for a ticking exception."  These are the logs that go with that.

### Expected Behavior

The game would run, and create items would be available?

### Reproduction Steps

I'm sorry, I don't feel like this really applies?  I hope I'm posting this in the right place, it is where I was directed.

### Logs

https://gist.github.com/reticentwit/46c24076f976237be7b4349afa709bcf

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #10176: [BUG] Error and Server Crash if Spawner block is broken before its SpawnData has been set
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.647-beta

### Structurize Version

1.20.1-1.0.742

### Related Mods and their Versions

- Forge - 47.3.0
- BlockUI - 1.20.1-1.0.156
- Domum Ornamentum - 1.20.1-1.0.186

### Current Behavior

Single Player

Block breaks but is still there and invisible, will re-appear on a block update.
Error in the log file, but no crash:

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.SpawnData.m_186567_()" because "net.minecraft.world.level.block.entity.SpawnerBlockEntity.m_59801_().f_45444_" is null
	at TRANSFORMER/minecolonies@1.20.1-1.1.647-beta/com.minecolonies.core.event.EventHandler.onBlockBreak(EventHandler.java:607)
	at TRANSFORMER/minecolonies@1.20.1-1.1.647-beta/com.minecolonies.core.event.__EventHandler_onBlockBreak_BreakEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.3.0/net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:543)
	...
```

Multiplayer

Server Crash with the same error as in SP

### Expected Behavior

No error, no crash.

### Reproduction Steps

1. Switch to Creative Mode
   This will allow you to break the spawner quick enough
2. Give yourself an empty spawner
3. Place the spawner and immediately break it

### Logs

https://gist.github.com/TigerWalts/caf2450b1e24ad1819fdbe30fdd9074e

### Anything else?

The crash happens because `nextSpawnData` here is `null`:

https://github.com/ldtteam/minecolonies/blob/4f972e8582b051902c4212a636dea7570f147b02/src/main/java/com/minecolonies/core/event/EventHandler.java#L609-L612

`nextSpawnData` may be `null` for the first few ticks after the spawner is placed. I believe that this is set after being generated in an off thread task to avoid latency from spawn and loot table lookups.

In normal play a spawner being broken immediately after being placed is an incredibly low chance. However we had a player manage to do this by using a QuarryPlus quarry.

---

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #10181: [BUG] texture loading crash Non [a-z0-9/._-] character in path
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.644

### Structurize Version

1.20.1-1.0.752

### Related Mods and their Versions

its also listing Entity Model Features (2.2) as it has a mixin there

### Reproduction Steps

i start the game
i join the server and it crashes right when it starts rendering i am near a minecolonies village

### Logs

https://gist.github.com/JurkoDev/1c2f4b6b06407df9193607abe6aeed02

### Anything else?

i had issues with optimisation mods just wrecking it i think theres probably something still based on the log spam

idk what this loading issue is also the sound loading issues in the console log

also am not on latest minecolonies as i couldnt be as the server is just rejecting me (also cant test sp as it will just eat all my ram (32gb) and cpu and then crash while trying to load a sp world huh)

### PR DESCRIPTION
**Pull request by someaddons**
Closes #10181
Closes #10176
Closes #10167

# Changes proposed in this pull request:
- Prevent some crashes

[x ] Yes I tested this before submitting it.
[x ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/core/colony/buildings/AbstractBuilding.java [hunk 1]
```diff
@@ -1897,10 +1895,21 @@ public final ImmutableCollection<IRequestResolver<?>> getResolvers()
...
+            List<IRequestResolver<? extends IRequestable>> list = new ArrayList<>();
+            for (Iterator<IToken<?>> iterator = requestManager.getProviderHandler().getRegisteredResolvers(this).iterator(); iterator.hasNext(); )
+            {
+                final IToken<?> token = iterator.next();
+                try
+                {
+                    IRequestResolver<? extends IRequestable> resolver = requestManager.getResolverHandler().getResolver(token);
+                    list.add(resolver);
+                }
+                catch (Exception e)
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/core/colony/buildings/AbstractBuilding.java:1907]: No idea if its safe to remove from registered resolvers, but shouldnt we log the exception?

**Review by Nightenom — DISMISSED** [review]
Just small question, fine otherwise

File: src/main/java/com/minecolonies/core/colony/buildings/AbstractBuilding.java (hunk 1 above)
Comment (someaddons) [reply src/main/java/com/minecolonies/core/colony/buildings/AbstractBuilding.java:1907]: we could log it, but its just a "resolver not found for token" one, doesnt hold much info on why it happens

File: src/main/java/com/minecolonies/core/network/messages/client/colony/PlaySoundForCitizenMessage.java [hunk 2]
```diff
@@ -150,7 +150,7 @@ public PlaySoundForCitizenMessage(final int entityID, final SoundEvent event, fi
     @Override
     public void toBytes(final FriendlyByteBuf buf)
     {
-        buf.writeResourceLocation(ForgeRegistries.SOUND_EVENTS.getKey(this.soundEvent));
+        buf.writeResourceLocation(this.soundEvent.getLocation());
```
Comment (Thodor12) [inline src/main/java/com/minecolonies/core/network/messages/client/colony/PlaySoundForCitizenMessage.java:153]: Does this solve the issue with "Sounds"?

Comment (someaddons) [reply src/main/java/com/minecolonies/core/network/messages/client/colony/PlaySoundForCitizenMessage.java:153]: ye

Comment (someaddons) [reply src/main/java/com/minecolonies/core/network/messages/client/colony/PlaySoundForCitizenMessage.java:153]: we're actually checking the registry for the existence of the sound event ID, but the registry doesnt know the actual sound event instance, so that fails then
