### PR TITLE
General overhaul of translation and message sending

### LINKED ISSUE #8289: Town Hall does not show building names
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.654-ALPHA

### Structurize Version

1.18.2-1.0.389-RELEASE

### Related Mods and their Versions

Forge Version: 40.0.1
Multi-piston 1.18.2-1.2.3-ALPHA
Domum_ornamentum 1.18.2-1.0.50-ALPHA
BlockUI 1.18.2-0.0.47-ALPHA

### Current Behavior

image

### Expected Behavior

Should show building names, not code snippets

### Reproduction Steps

Go to town hall after sending builders to build stuff and check the display above

### Logs

https://pastebin.com/ududqtYy

### Anything else?

switch between creative and survival modes, but mostly creative 

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Thodor12**
Closes #8289

# Changes proposed in this pull request:
- The LanguageHandler has been almost completely removed from the code (there's only like 7 occurences left which are required for the entire translation system to operate, these have not been touched.)
- Player.sendMessage is not directly used anymore in the code except for the singular occurence in `MessageUtils`
- Introduced a new class `MessageUtils` responsible for handling all the message sending code, this class has some nice overloads which allow you to message with directly adding a TextFormatting, send messages originating from a given colony (and then prepending the colony name when outside of that colony)
- Made proper use of the `notifyColony(Members|Managers)` methods throughout the code, also given this method an overload which allows you to pass a TextFormatting, aswell as a `Consumer<PlayerEntity>` so you can execute additional tasks without having to manually iterate or iterate over the list of players again.
- Made the colonist death message RED 🔥

### CODE REVIEW

File: src/api/java/com/minecolonies/api/tileentities/TileEntityColonyBuilding.java [hunk 1]
```diff
@@ -313,7 +312,7 @@ public ITextComponent getDisplayName()
         {
             return super.getDisplayName();
         }
-        return new StringTextComponent(LanguageHandler.format(getBlockState().getBlock().getDescriptionId() + ".name"));
+        return new TranslationTextComponent(getBlockState().getBlock().getDescriptionId() + ".name");
```
Comment (Raycoms) [inline src/api/java/com/minecolonies/api/tileentities/TileEntityColonyBuilding.java]: Can't we get the component even directly from the blockState?

File: src/main/java/com/minecolonies/coremod/client/gui/AbstractWindowModuleBuilding.java [hunk 2]
```diff
@@ -88,17 +90,21 @@ private void allInventoryClicked()
...
-        final String buttonLabel = buttonBuild.getTextAsString();
-        if (buttonLabel.equalsIgnoreCase(LanguageHandler.format("com.minecolonies.coremod.gui.workerhuts.cancelbuild"))
-              || buttonLabel.equalsIgnoreCase(LanguageHandler.format("com.minecolonies.coremod.gui.workerhuts.cancelupgrade")))
+        String buttonLabel = buttonBuild.getTextAsString();
+        if (buttonBuild.getText() instanceof TranslationTextComponent)
+        {
+            buttonLabel = ((TranslationTextComponent) buttonBuild.getText()).getKey();
+        }
+
+        if (buttonLabel.equalsIgnoreCase(ACTION_CANCEL_BUILD) || buttonLabel.equalsIgnoreCase(ACTION_CANCEL_UPGRADE))
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/client/gui/AbstractWindowModuleBuilding.java:96]: Did you test this?

File: src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowSettingsPage.java [hunk 3]
```diff
@@ -206,15 +205,21 @@ public void onOpened()
      */
     private void toggleHiring(@NotNull final Button button)
     {
+        String key = button.getTextAsString();
+        if (button.getText() instanceof TranslationTextComponent)
+        {
+            key = ((TranslationTextComponent) button.getText()).getKey();
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowSettingsPage.java]: Isn't there a method to get the text? Like toString or so?

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/undertaker/EntityAIWorkUndertaker.java [hunk 4]
```diff
@@ -414,18 +411,18 @@ private IAIState buryCitizen()
...
 
-        if(burialPos == null || burialPos.getA() == null)
+        if (burialPos == null || burialPos.getA() == null)
         {
-            //coudn't find a place to dig a grave
-            LanguageHandler.sendPlayersMessage(buildingGraveyard.getColony().getImportantMessageEntityPlayers(),
-                    "com.minecolonies.coremod.nospaceforgrave", module.getLastGraveData().getCitizenName());
+            // couldn't find a place to dig a grave
+            buildingGraveyard.getColony()
+              .notifyColonyManagers(new TranslationTextComponent(MESSAGE_INFO_CITIZEN_UNDERTAKER_GRAVEYARD_NO_SPACE, module.getLastGraveData().getCitizenName()));
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/undertaker/EntityAIWorkUndertaker.java]: Those two entries here we probably want to use in the chat handler too

File: src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenChatHandler.java [hunk 5]
```diff
@@ -47,78 +40,64 @@ public void notifyDeath(final DamageSource damageSource)
         if (citizen.getCitizenColonyHandler().getColony() != null && citizen.getCitizenData() != null)
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenChatHandler.java:42]: I wonder if we could get rid of this chat handler and make this a util method in the MsgUtils 
sendMessageFromCitizen(worker, ....)

File: src/main/java/com/minecolonies/coremod/util/ServerUtils.java [hunk 6]
```diff
@@ -3,6 +3,8 @@
 import com.minecolonies.api.colony.permissions.Player;
 import net.minecraft.entity.player.PlayerEntity;
 import net.minecraft.entity.player.ServerPlayerEntity;
+import net.minecraft.util.text.ITextComponent;
+import net.minecraft.util.text.TranslationTextComponent;
 import net.minecraft.world.World;
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/util/ServerUtils.java]: needed?

**Review by Raycoms — COMMENTED** [review]
Some small comments

File: src/api/java/com/minecolonies/api/util/MessageUtils.java [hunk 7]
```diff
@@ -0,0 +1,153 @@
...
+     *
+     * @param player     the player to send to.
+     * @param component  the text component to send.
+     * @param formatters a collection of formatter to apply to the root component.
+     */
+    private static void sendMessageInternal(PlayerEntity player, ITextComponent component, Collection<TextFormatting> formatters)
+    {
+        if (player == null)
+        {
+            Log.getLogger().log(Level.ERROR, "Attempting to send player message without passing a player, please report this to the developers!");
```
Comment (Nightenom) [inline src/api/java/com/minecolonies/api/util/MessageUtils.java]: This should crash in dev space (same way as in dist executor)

File: src/api/java/com/minecolonies/api/util/MessageUtils.java [hunk 8]
```diff
@@ -0,0 +1,153 @@
...
+        {
+            Log.getLogger().log(Level.ERROR, "Attempting to send player message without passing a message component, please report this to the developers!");
+            return;
+        }
+
+        if (component instanceof IFormattableTextComponent)
+        {
+            for (TextFormatting formatter : formatters)
+            {
+                ((IFormattableTextComponent) component).withStyle(formatter);
```
Comment (Nightenom) [inline src/api/java/com/minecolonies/api/util/MessageUtils.java]: Meh, if I use the method with component I expect it to not change (beware - you **should** copy before applying style, especially if its foreign component), so rather than applying it here I would make methods
sendXYmessage(player, key, args...) - no style modify
sendXYmessage(player, key, style, args...) - rather than color you should use style directly (if textformatting does not implement style then unfortunately another method overload)
sendXYmessage(player, component) - no style modify
sendXYmessage(player, style, component) - makes little sense since if you already have component then you can style it urself

also not sure why this **private** method use list when you do `Collections.singletonList` everywhere

File: src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java [hunk 9]
```diff
@@ -129,7 +130,7 @@ public static void init()
         InteractionValidatorRegistry.registerStandardPredicate(new TranslationTextComponent(COM_MINECOLONIES_COREMOD_ENTITY_WORKER_INVENTORYFULLCHEST),
           citizen -> citizen.getWorkBuilding() != null && InventoryUtils.isProviderFull(citizen.getWorkBuilding()));
         InteractionValidatorRegistry.registerPosBasedPredicate(
-          new TranslationTextComponent(BUILDING_LEVEL_TOO_LOW), (citizen, pos) ->
+          new TranslationTextComponent(RequestSystemTranslationConstants.REQUEST_SYSTEM_BUILDING_LEVEL_TOO_LOW), (citizen, pos) ->
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java]: the class has RS in name, might want to remove rs from constant name then (look for other constant also if so)
(idk, the name looks long xd)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowHireWorker.java [hunk 10]
```diff
@@ -406,11 +400,15 @@ else if ((selectedModule.isFull()) && !selectedModule.getAssignedCitizens().cont
...
+                ITextComponent citizenLabelComponent =
+                  citizen.getJob().isEmpty() ? new StringTextComponent(citizen.getName()) : new TranslationTextComponent(citizen.getJob()).append(": ").append(citizen.getName());
+                rowPane.findPaneOfTypeByID(CITIZEN_LABEL, Text.class).setText(citizenLabelComponent);
                 rowPane.findPaneOfTypeByID(ATTRIBUTES_LABEL, Text.class).setText(textBuilder.getText());
                 final JobEntry entry = selectedModule.getJobEntry();
-                PaneBuilders.tooltipBuilder().hoverPane(rowPane.findPaneOfTypeByID(ATTRIBUTES_LABEL, Text.class)).build().setText(new TranslationTextComponent(entry.getKey().toString() + ".skills.desc"));
+                PaneBuilders.tooltipBuilder()
+                  .hoverPane(rowPane.findPaneOfTypeByID(ATTRIBUTES_LABEL, Text.class))
+                  .build()
+                  .setText(new TranslationTextComponent(entry.getKey().toString() + ".skills.desc"));
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowHireWorker.java:411]: could use append method in builder (i see it was there before and its not ur change but still)

File: src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowPermissionsPage.java [hunk 11]
```diff
@@ -451,7 +450,12 @@ private void trigger(@NotNull final Button button)
 
         final IPermissions permissions = building.getColony().getPermissions();
         final PlayerEntity playerEntity = Minecraft.getInstance().player;
-        final boolean enable = !LanguageHandler.format(COM_MINECOLONIES_COREMOD_GUI_WORKERHUTS_RETRIEVE_ON).equals(button.getTextAsString());
+        String key = button.getTextAsString();
+        if (button.getText() instanceof TranslationTextComponent)
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowPermissionsPage.java]: could be oneliner using ternary (also at other places - search for casting to TranslationTextComponent to find them)

**Review by Nightenom — COMMENTED** [review]
While I agree with removing usage of the ancient LanguageHandler, rather than with_style/from_args method I would with full-fledged text builder similarly in way its done in [blockui](https://github.com/ldtteam/BlockUI/blob/version/latest/src/main/java/com/ldtteam/blockui/controls/AbstractTextBuilder.java#L379) - this method gets you list text elements and then we would call sendXYmessage on every part
Mby you could create new textbuilder with null panefactory and few overrides so it can be used for messages

Decision left up to others

Also might want to look at usages of I18n class :P

**Comment by uecasm** [comment]
Yeah, I agree that a builder style would be nicer than having a bunch of optional arguments methods.  Then you could have things like:

```
MessageUtils.build()
    .append(SOME_LANG_ID)
    .append(ANOTHER_ID, 12, building.getName()).withStyle(ChatFormatting.RED)
    .append(YET_ANOTHER)
    .sendTo(player);
```
where each message can be styled separately.

Having said that, the append-append-append style of message creation is typically a Very Bad Idea™ unless you're careful to ensure that each one is at least a complete sentence (or preferably a complete paragraph); otherwise it causes problems for translation.  So on that basis it might be too dangerous to make the syntax too fluent 😁

File: src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowSettingsPage.java (hunk 3 above)
Comment (Thodor12) [reply src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowSettingsPage.java]: There is a method `getTextAsString()` which is used above it, the problem is we're comparing translated text which isn't always the best idea, so in case the component is a translation text component we have access to a translation key and arguments.
I use this key to compare to a translation constants key in order to determine which action to take, this mainly stems from the fact I do not have a `LanguageHandler.format` equivalent method to translate a string directly outside of a translation component.

File: src/api/java/com/minecolonies/api/util/MessageUtils.java (hunk 7 above)
Comment (Thodor12) [reply src/api/java/com/minecolonies/api/util/MessageUtils.java]: I have not had this error just yet, a player technically does exist, he just can't be authenticated against mojang it's authorization servers, but the instance does exist.

**Comment by Thodor12** [comment]
> Yeah, I agree that a builder style would be nicer than having a bunch of optional arguments methods. Then you could have things like:
> 
> ```
> MessageUtils.build()
>     .append(SOME_LANG_ID)
>     .append(ANOTHER_ID, 12, building.getName()).withStyle(ChatFormatting.RED)
>     .append(YET_ANOTHER)
>     .sendTo(player);
> ```
> 
> where each message can be styled separately.
> 
> Having said that, the append-append-append style of message creation is typically a Very Bad Idea™ unless you're careful to ensure that each one is at least a complete sentence (or preferably a complete paragraph); otherwise it causes problems for translation. So on that basis it might be too dangerous to make the syntax too fluent 😁

I think the idea of the proposed builder would be more in line of passing a prebuilt text component, then passing options like `.withStyle()` `.withColony`, etc

File: src/main/java/com/minecolonies/coremod/client/gui/AbstractWindowModuleBuilding.java (hunk 2 above)
Comment (Thodor12) [reply src/main/java/com/minecolonies/coremod/client/gui/AbstractWindowModuleBuilding.java:96]: I can confirm this works as intended

**Comment by uecasm** [comment]
> I think the idea of the proposed builder would be more in line of passing a prebuilt text component, then passing options like .withStyle() .withColony, etc

Well, with either interface you should have one overload that takes `(id, args...)` and one that takes `(Component)`.  But I don't think there's much point in only taking the latter.

File: src/api/java/com/minecolonies/api/util/MessageUtils.java (hunk 7 above)
Comment (Nightenom) [reply src/api/java/com/minecolonies/api/util/MessageUtils.java]: w/e applies to all if null checks in this class
especially its nice to log error instead of hard crash if possible in production
but we should always crash in dev

File: src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowPermissionsPage.java (hunk 11 above)
Comment (Thodor12) [reply src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowPermissionsPage.java]: There were only 3 occurences of this, a couple of them were using `I18n.exists` which I didn't know how to replace, so I left them for now.

File: src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenChatHandler.java (hunk 5 above)
Comment (Thodor12) [reply src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenChatHandler.java:42]: Switched to a builder-like setup, we could technically make this part of the MessageBuilder with a new `sendTo` overload?

File: src/api/java/com/minecolonies/api/blocks/AbstractBlockHut.java [hunk 12]
```diff
@@ -103,7 +108,7 @@ public float getDestroyProgress(final BlockState state, @NotNull final PlayerEnt
         if (building != null && !building.getChildren().isEmpty() && (player.level.getGameTime() - lastBreakTickWarn) < 100)
         {
             lastBreakTickWarn = player.level.getGameTime();
-            LanguageHandler.sendPlayerMessage(player, "block.minecolonies.blockhut.breakwarn.children");
+            MessageUtils.format(HUT_BREAK_WARNING_CHILD_BUILDINGS).sendTo(player);
```
Comment (Raycoms) [inline src/api/java/com/minecolonies/api/blocks/AbstractBlockHut.java:111]: Seems weird calling it format if we give it the main string. MessageUtils.message().append().sendTo() feels better

Comment (uecasm) [reply src/api/java/com/minecolonies/api/blocks/AbstractBlockHut.java:111]: it's `format(id, args...)`, following in the fine tradition of `string.format` in various languages, albeit with a translation key instead of a literal format string.  `translate(...)` could be another reasonable method name; `message(...)` is probably fine too, but sounds a little redundant when on `MessageUtils`.

Comment (Thodor12) [reply src/api/java/com/minecolonies/api/blocks/AbstractBlockHut.java:111]: So do I change this to `translate` instead? Don't want to have to rename it all again unless it's for a good reason

**Review by someaddons — DISMISSED** [review]

File: src/main/java/com/minecolonies/coremod/client/gui/modules/FarmerFieldsModuleWindow.java [hunk 13]
```diff
@@ -166,14 +166,20 @@ private void pullLevelsFromHut()
      */
     private void assignmentModeClicked(@NotNull final Button button)
     {
-        if (button.getTextAsString().equals(LanguageHandler.format(COM_MINECOLONIES_COREMOD_GUI_HIRING_OFF)))
+        String buttonText = button.getTextAsString();
+        if (button.getText() instanceof TranslationTextComponent)
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/client/gui/modules/FarmerFieldsModuleWindow.java]: Ternaryable _(see the suggestion in last comment)_

File: src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowPermissionsPage.java (hunk 11 above)
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowPermissionsPage.java]: Ternaryable

File: src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowSettingsPage.java [hunk 14]
```diff
@@ -206,15 +205,21 @@ public void onOpened()
      */
     private void toggleHiring(@NotNull final Button button)
     {
+        String key = button.getTextAsString();
+        if (button.getText() instanceof TranslationTextComponent)
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowSettingsPage.java]: Ternaryable

File: src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowSettingsPage.java [hunk 15]
```diff
@@ -227,15 +232,21 @@ private void toggleHiring(@NotNull final Button button)
      */
     private void toggleHousing(@NotNull final Button button)
     {
+        String key = button.getTextAsString();
+        if (button.getText() instanceof TranslationTextComponent)
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowSettingsPage.java]: Ternaryable

File: src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowSettingsPage.java [hunk 16]
```diff
@@ -248,15 +259,21 @@ private void toggleHousing(@NotNull final Button button)
      */
     private void toggleMoveIn(@NotNull final Button button)
     {
+        String key = button.getTextAsString();
+        if (button.getText() instanceof TranslationTextComponent)
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowSettingsPage.java]: Ternaryable

File: src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowSettingsPage.java [hunk 17]
```diff
@@ -269,13 +286,19 @@ private void toggleMoveIn(@NotNull final Button button)
      */
     private void togglePrintProgress(@NotNull final Button button)
     {
-        if (button.getTextAsString().equals(LanguageHandler.format(OFF_STRING)))
+        String key = button.getTextAsString();
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/client/gui/townhall/WindowSettingsPage.java]: Ternaryable

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 18]
```diff
@@ -780,13 +781,14 @@ public void requestUpgrade(final PlayerEntity player, final BlockPos builder)
...
         {
-            player.sendMessage(new TranslationTextComponent("com.minecolonies.coremod.research.havetounlock"), player.getUUID());
+            MessageUtils.format(WARNING_BUILDING_REQUIRES_RESEARCH).sendTo(player);
             return;
         }
         if (MinecoloniesAPIProxy.getInstance().getGlobalResearchTree().hasResearchEffect(hutResearch) &&
               (colony.getResearchManager().getResearchEffects().getEffectStrength(hutResearch) <= getBuildingLevel()))
         {
-            player.sendMessage(new TranslationTextComponent("com.minecolonies.coremod.research.unlocktoupgrade"), player.getUUID());
+            // TODO: Translation key does not exist, is this still needed?
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: Please resolve the todo

File: src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenChatHandler.java [hunk 19]
```diff
@@ -47,78 +44,65 @@ public void notifyDeath(final DamageSource damageSource)
...
             }
+
+            MessageUtils.format(contentComponent)
+              .with(TextFormatting.RED)
+              .sendTo(citizen.getCitizenColonyHandler().getColony()).forManagers();
         }
     }
 
     @Override
     public void sendLocalizedChat(final String keyIn, final Object... msg)
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenChatHandler.java:75]: Would make sense for me to remove this method

File: src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenChatHandler.java [hunk 20]
```diff
@@ -47,78 +44,65 @@ public void notifyDeath(final DamageSource damageSource)
...
-                    citizen.getCitizenColonyHandler().getColony().getPermissions().getOwner());
+            final IJob<?> job = citizen.getCitizenJobHandler().getColonyJob();
 
-            if (owner != null)
+            MessageUtils.MessageBuilder builder;
+            if (job != null)
+            {
+                builder = MessageUtils.format(job.getJobRegistryEntry().getTranslationKey())
+                            .append(new StringTextComponent(" "))
+                            .append(Objects.requireNonNull(citizen.getCustomName()))
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenChatHandler.java]: Wonder if `Objects.requireNonNull` is needed

File: src/main/java/com/minecolonies/coremod/client/gui/modules/EnchanterStationModuleWindow.java [hunk 21]
```diff
@@ -126,7 +124,13 @@ public void updateElement(final int index, @NotNull final Pane rowPane)
     private void switchClicked(@NotNull final Button button)
     {
         final int row = workerList.getListElementIndexByPane(button);
-        if (button.getTextAsString().equals(LanguageHandler.format(OFF)))
+        String buttonText = button.getTextAsString();
+        if (button.getText() instanceof TranslationTextComponent)
+        {
+            buttonText = ((TranslationTextComponent) button.getText()).getKey();
+        }
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/client/gui/modules/EnchanterStationModuleWindow.java]: Ternaryable
```suggestion
        final String buttonText = button.getText() instanceof TranslationTextComponent ? ((TranslationTextComponent) button.getText()).getKey() : button.getTextAsString();
```

**Review by Nightenom — COMMENTED** [review]
I'm not happy with the messageUtils design, but mergeable once todo resolved

File: src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenChatHandler.java (hunk 19 above)
Comment (Thodor12) [reply src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenChatHandler.java:75]: Whilst I agree with the fact that the method technically is only used once, and therefore shouldn't be needed, I don't think cramming everything together in one method is great practice either.
This class already exists to handle messages related to citizens, so rather keep it and expand on it in the future, moving more messaging to this class instead.
