### PR TITLE
Several fixes

### LINKED ISSUE #6471: former archer in training going to bed at archery ground
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.13.596-ALPHA-universal
- Structurize Version: structurize-0.13.113-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

Citizen with changed job sleep in a house.
## Actual behavior

So I had a citizen levelling up in the archery hut, and then decided to use them as a courier. so I hired them directly from the courier hut. Was flying around and noticed the courier had decided they would go to bed at the archery ground instead of a house.

## Steps to reproduce the issue

1: put citizen in archery training ground
2) hire that citizen directly to another building.

1. 
2. 
3. 

### Logs

- latest.log: https://gist.github.com/Moobien/ff496091966ea2efb344e3ba34f84f49
- crashlog: 

### Notes

https://imgur.com/a/FQPYLDb - lvl 1 fortress archery training ground.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #6549: Builder does not place bell in lv 4 med oak library
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.610
- Structurize Version: 0.13.113
- Related Mods and their Versions:

## Expected behavior

Builder places a bell in the last few steps of the building process.
## Actual behavior

The bell is not placed, despite the schematic including one, thus it looks weird.

## Steps to reproduce the issue

1.  build library
2.  upgrade to level 4
3.  bell is not placed.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #6934: Builder won't build guardtowers anymore
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.163
- MineColonies Version (if related bug): 0.14.100
- Related Mods and their Versions:

## Expected behavior

Builders build guardtowers.

## Actual behavior

Builder stand at the corner of the building area and does nothing.

## Steps to reproduce the issue

1.  Order the building of a guardtower.
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

I don't know if it's related but the building block is 167 blocks from the town center. I set the claim limit to 50 chunks.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #7039: Clicking "Place Anyways" Removes Stored Hut Level.
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5.36.1.2
- MineColonies Version: minecolonies-0.14.134-ALPHA-universal.jar
- Structurize Version: 169-Alpha
- Related Mods and their Versions: ATM6 1.6.2

## Expected behavior

When placing a deconstructed hut back into the world, it would keep its hut level.

## Actual behavior

When clicking to place deconstructed hut back into world, without the wand, the hut loses its level. The pop up tells you that you might want to use the tool so you can reposition it, but it does not tell you that it will lose its level.

This happened with the farm hut, I am not sure if it happens with any other hut.

## Steps to reproduce the issue

1.  Deconstruct level 5 hut.
2.  Right click to place hut, click on "place anyways."
3.  Look in GUI to see hut level lost.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #6471
Closes #6549
Closes #6934
Closes #7039

# Changes proposed in this pull request:
- Fixes direct placement not carrying building level along
- Fixes builder selecting bad positions to build from
- Fixes incorrect bell placement
- Fixes citizens staying behind sleeping in academies

Review please

### CODE REVIEW

**Review by someaddons — APPROVED** [review]

File: src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java [hunk 1]
```diff
@@ -449,6 +449,12 @@
     public static final String RESEARCH_AVAILABLE                                                   = "com.minecolonies.coremod.research.available";
     @NonNls
     public static final String RESEARCH_REQUIRES                                                    = "com.minecolonies.coremod.research.requirement.research";
+    @NonNls
```
Comment (ravenbuilder934) [inline src/api/java/com/minecolonies/api/util/constant/TranslationConstants.java:452]: ...whitespace?
