### PR TITLE
Miner builder

### LINKED ISSUE #7904: AI Issues Miner Level 3 Nordic Style
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.81.1-1.0.328-ALPHA

### Logs

- latest.log: 
https://gist.github.com/JavelinD/af66dee9354790cd1ac320bf71459b00

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

Miner Level 3 Nordic style mining at level 12
AI Log at bottom of text

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #7905: Villager House assign screen - Relative distance display not working
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.18.1-1.0.328-ALPHA
- Structurize Version: 1.18.1-1.0.319-BETA
- Related Mods and their Versions: ATM 7 Mod pack

## Actual behavior

image

## Steps to reproduce the issue

Unsure what is causing this

### Logs

- latest.log: https://gist.github.com/JavelinD/52be8509069c150b9c9e71b71bdd3ce2
- crashlog: N/A

### Notes

Unsure as to what is actually causing the issue. Only noticing it because I'm literally only playing with minecolonies in the modpack at the moment. Absolutely love it

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #7904
Closes #7905
Closes #

# Changes proposed in this pull request:
- Fix miner AI exception
- Fix hut display
- Add a way to configure the max depth the miner goes down to
- Add to the builder configuration of solid placeholder

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java [hunk 1]
```diff
@@ -124,7 +124,8 @@ public static void init(final RegistryEvent.Register<BuildingEntry> event)
                                  .addBuildingModuleProducer(() -> new SettingsModule()
                                                                     .with(BuildingBuilder.MODE, new StringSetting(BuildingBuilder.AUTO_SETTING, BuildingBuilder.MANUAL_SETTING))
                                                                     .with(AbstractCraftingBuildingModule.RECIPE_MODE, new CrafterRecipeSetting())
-                                                                    .with(BuildingBuilder.BUILDING_MODE, new BuilderModeSetting()), () -> SettingsModuleView::new)
+                                                                    .with(BuildingBuilder.BUILDING_MODE, new BuilderModeSetting())
+                                                                    .with(BuildingMiner.FILL_BLOCK, new BlockSetting((BlockItem) Items.COBBLESTONE)), () -> SettingsModuleView::new)
```
Comment (MotionlessTrain) [inline src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java]: Shouldn’t the builder default to dirt of grass instead of cobblestone?

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java [hunk 2]
```diff
@@ -169,18 +175,31 @@ public int getDepthLimit(final Level level)
...
-        else if (this.getBuildingLevel() >= 3)
+        else
         {
-            return level.getMinBuildHeight() + MAX_DEPTH_LEVEL_3;
+            return normalizeMaxDepth(-100, level);
         }
+    }
 
-        return MAX_DEPTH_LEVEL_0;
+    public int normalizeMaxDepth(final int max, final Level level)
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java:201]: javadoc

**Review by someaddons — DISMISSED** [review]

**Review by someaddons — APPROVED** [review]

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java [hunk 3]
```diff
@@ -169,18 +175,38 @@ public int getDepthLimit(final Level level)
...
         }
         else if (this.getBuildingLevel() == 2)
         {
-            return MAX_DEPTH_LEVEL_2;
+            return normalizeMaxDepth(MAX_DEPTH_LEVEL_2, level);
         }
-        else if (this.getBuildingLevel() >= 3)
+        else if (this.getBuildingLevel() == 3)
+        {
+            return normalizeMaxDepth(MAX_DEPTH_MAX, level);
```
Comment (uecasm) [inline src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java:186]: Shouldn't this be using `MAX_DEPTH_LEVEL_3` so that they actually stop at 0 rather than going all the way to bedrock?

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java [hunk 4]
```diff
@@ -169,18 +175,38 @@ public int getDepthLimit(final Level level)
...
+        }
+        else
         {
-            return level.getMinBuildHeight() + MAX_DEPTH_LEVEL_3;
+            return normalizeMaxDepth(-100, level);
```
Comment (uecasm) [inline src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java:190]: And shouldn't this one be using `MAX_DEPTH_MAX`?

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java [hunk 5]
```diff
@@ -169,18 +175,38 @@ public int getDepthLimit(final Level level)
...
         }
+    }
 
-        return MAX_DEPTH_LEVEL_0;
```
Comment (uecasm) [inline src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java:183]: Meanwhile this condition is no longer handled (building level 0 shouldn't dig at all) ... _hopefully_ that doesn't matter as the miner shouldn't start actually working until they hit level 1, but it might be safer to keep the original behaviour there.

File: src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java [hunk 6]
```diff
@@ -306,7 +307,10 @@ public static void init(final RegistryEvent.Register<BuildingEntry> event)
                                .addBuildingModuleProducer(MinimumStockModule::new, () -> MinimumStockModuleView::new)
                                .addBuildingModuleProducer(BuildingResourcesModule::new, () -> BuildingResourcesModuleView::new)
                                .addBuildingModuleProducer(MinerLevelManagementModule::new, () -> MinerLevelManagementModuleView::new)
-                               .addBuildingModuleProducer(() -> new SettingsModule().with(BuildingMiner.FILL_BLOCK, new BlockSetting((BlockItem) Items.COBBLESTONE)), () -> SettingsModuleView::new)
+                               .addBuildingModuleProducer(() -> new SettingsModule()
+                                                                  .with(AbstractCraftingBuildingModule.RECIPE_MODE, new CrafterRecipeSetting())
+                                                                  .with(BuildingMiner.FILL_BLOCK, new BlockSetting((BlockItem) Items.COBBLESTONE))
+                                                                  .with(BuildingMiner.MAX_DEPTH, new IntSetting(-100)), () -> SettingsModuleView::new)
```
Comment (uecasm) [inline src/main/java/com/minecolonies/apiimp/initializer/ModBuildingsInitializer.java:313]: Probably should be using `MAX_DEPTH_MAX` here too.

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java [hunk 7]
```diff
@@ -169,18 +175,38 @@ public int getDepthLimit(final Level level)
...
+     * @return the max.
+     */
+    public int normalizeMaxDepth(final int max, final Level level)
+    {
+        final int worldMaxDepth = level.getMinBuildHeight() + 5;
+        final IntSetting maxDepth = getSetting(MAX_DEPTH);
+        if (maxDepth.getValue() == maxDepth.getDefault())
+        {
+            return Math.max(worldMaxDepth, max);
+        }
```
Comment (uecasm) [inline src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java:208]: The check against the default value seems unnecessary.  The default is currently `-100` (which is equal to `MAX_DEPTH_MAX` anyway) which is already lower than or equal to any currently possible value of `worldMaxDepth` and `max` (until the world depth is increased again), so the line below would do the right thing even if this check were omitted.

And if in the future the world depth is increased further, then `MAX_DEPTH_MAX` would probably be decreased, as would the option default, but the current option value in existing colonies probably wouldn't (unless there was some explicit upgrade code over in the persistence, which still doesn't require anything here) and so the value would no longer equal the default and this check would be ignored anyway.
