### PR TITLE
Ray fixes

### LINKED ISSUE #8967: [BUG] Rotating costume style packs crashes an ATM 8 server
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1262-ALPHA

### Structurize Version

1.19.2-1.0.480-ALPHA

### Related Mods and their Versions

_No response_

### Current Behavior

When I would attempt to place a structure I made with the build tool and then rotate the building the server would crash.

### Expected Behavior

I expected to turn the structure 180 degrees to have the door facing me and for the building to be placed for construction

### Reproduction Steps

1. Download the ATM 8 server zip folder
2. Copy your costume style pack
3. Use the building tool to rotate the structure 180 degrees
4. Click the green check mark

### Logs

https://pastebin.com/Y5x5UWCv

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #8973: [BUG] Sorting erased all the items in the warehouse
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.3-1.0.1243-ALPHA

### Structurize Version

1.19.3-1.0.482-ALPHA

### Related Mods and their Versions

1. alexsmobs-1.22.0
2. Aquaculture-1.19.3-2.4.11
3. blockui-1.19.3-0.0.68-ALPHA
4. carryon-forge-1.19.3-2.0.5.17
5. citadel-2.2.3-1.19.3
6. Clumps-forge-1.19.3-9.0.0+16
7. corpse-1.19.3-1.0.2
8. domum_ornamentum-1.19.3-1.0.79-ALPHA-universal
9. EasierSleeping-1.19.3-2.1.2
10. ecologics-forge-1.19.3-2.1.12
11. FallingTree-1.19.3-3.11.2
12. ferritecore-5.1.0-forge
13. geckolib-forge-1.19.3-4.0.3
14. ironchest-1.19.3-14.3.2
15. jei-1.19.3-forge-12.1.1.13
16. multipiston-1.19.3-1.2.26-ALPHA
17. queencats-1.0.3-1.19.3-Forge
18. twilightforest-1.19.3-4.2.1528-universal
19. u_team_core-1.19.3-4.5.1.238
20. useful_backpacks-1.19.3-1.14.2.108

### Reproduction Steps

1. Build a second-level warehouse
2. Fill the warehouse pallets with various items
3. Improve the warehouse to the third level
4. Click the "sort" button in the warehouse control panel
5. ???
6. All items disappear

I couldn't reproduce it again

### Logs

https://gist.githubusercontent.com/Falk20/3800a3c2895ed11ecae3a57b16904b24/raw/91078f7bd4e5f323a1b1c793a024441db6ddd5bf/Log

### Anything else?

I found a similar complaint in the discord, but I didn't see the issue in the github. https://discord.com/channels/139070364159311872/1003402487417548801/1073965064052281385

### LINKED ISSUE #8977: [BUG] AI issue with a builder
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1262-ALPHA

### Structurize Version

structurize-1.19.2-1.0.480-ALPHA

### Related Mods and their Versions

domum_ornamentum-1.19-1.0.76-ALPHA-universal

### Reproduction Steps

No idea! Train said just to report it here.
Restarting Minecraft and restarting the worker didn't do anything to fix this.

### Logs

https://gist.github.com/anonymous563/dd0b1239c40fd8d611e5d4c3cf9545e6

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #8983: [BUG] Raiders don't take void (out of world) damage
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1244-ALPHA

### Structurize Version

1.0.480-ALPHA

### Related Mods and their Versions

Forge 1.19.2-43.2.0
BlockUI 0.0.67-ALPHA
Domum Ornamentum 1.0.76-ALPHA
Multipiston 1.2.25-ALPHA

Running Cities Skylands v1.3 (latest at the time of writing)

### Current Behavior

Raiders don't take void (out of world) damage. Happened to me and others on the Skyblock server.

### Expected Behavior

Raiders should take void (out of world) damage, as other entities would.

### Reproduction Steps

1. Make hole to the void
2. Spawn raider
3. Push them into the void
4. Observe how they will not die

### Logs

N/A

### Anything else?

N/A

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #8967
Closes #8983
Closes #8973
Closes #8977

# Changes proposed in this pull request:
- Fix combined inv backup
- Fix crash when blueprint didnt arrive on time
- Fix raiders not receiving void damage
- Fix dyer not having a sec check

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/placementhandlers/main/SurvivalHandler.java [hunk 1]
```diff
@@ -92,6 +92,13 @@ public void handle(
       final BlockPos blockPos,
       final PlacementSettings placementSettings)
     {
+        if (blueprint == null)
+        {
+            // This can happen if the file didnt finish synching with the server from the client, or something went wrong when synching (package dropped, etc).
+            MessageUtils.format(NO_CUSTOM_BUILDINGS).sendTo(player);
```
Comment (MotionlessTrain) [inline src/main/java/com/minecolonies/coremod/placementhandlers/main/SurvivalHandler.java:97]: Shouldn't this be `BUILDING_MISSING` instead?

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/placementhandlers/main/SurvivalHandler.java:97]: derp

**Review by someaddons — APPROVED** [review]
