### PR TITLE
Stats for Barracks, Blacksmith, Builder, Chickenherder

### LINKED ISSUE #10961: Chicken Herder stats say "Used Raw Chicken" instead of "Got Raw Chicken"
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.1.939-snapshot

### Structurize Version

1.0.773-snapshot

### Related Mods and their Versions

_No response_

### Current Behavior

Image
The same behavior happens with eggs and feathers too.

### Expected Behavior

The raw chicken and the other obtained items should be "Got", not "Used"

### Reproduction Steps

1. Build a chicken herder's hut
2. Assign a chicken herder to the hut
3. Bring two chickens inside the hut
4. Give the herder some seeds to breed the chickens
5. Watch the stat change after the herder has killed one of the chicken, listing `Used x seeds` and `Used x raw chickens`

### Logs

-

### Anything else?

The issue might be the way [AbstractEntityAIHerder](https://github.com/ldtteam/minecolonies/blob/version/main/src/main/java/com/minecolonies/core/entity/ai/workers/production/herders/AbstractEntityAIHerder.java) tracks the number of used items.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by armele**
Also includes introduction of "hide zero values" button on the stats window.

Closes #10961 

# Changes proposed in this pull request
- Builder stats: block placed by detail, as well as building built, repaired, upgraded, removed (the latter 4 were already in the town hall stats)
- Blacksmith stats: Items crafted
- Barracks stats: Simply collects the tower-level stats that already existed for the towers of the barracks.
- Chickenherder: Changed "Used" to "Got" for collected items, added breeding, refactored existing stats to use helper method for consistency.
- Because some buildings have long stat lists and by default any key ever used will show in every interval, created a filter on the stat window to allow zero-value stats to be filtered out.

## Testing
- [X] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/core/client/gui/modules/WindowStatsModule.java [hunk 1]
```diff
@@ -52,6 +80,18 @@ public class WindowStatsModule extends AbstractModuleWindow
      */
     private static final String HUT_RESOURCE_SUFFIX = ":gui/layouthuts/layoutstatsmodule.xml";
 
+    /*
+     * Module view
+     */
+    private BuildingStatisticsModuleView moduleView = null;
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/core/client/gui/modules/WindowStatsModule.java:86]: If we cache this here we have to make sure that we're not under the hood replacing the stats module. (I.e. on deserialize we don't make a new instance).

File: src/main/java/com/minecolonies/core/entity/ai/workers/util/BuildingStructureHandler.java [hunk 2]
```diff
@@ -195,6 +197,7 @@ public void triggerSuccess(final BlockPos pos, final List<ItemStack> list, final
 
             for (final ItemStack stack : list)
             {
+                StatsUtil.trackStatByName( structureAI.getWorker().getCitizenData().getWorkBuilding(), BLOCKS_PLACED_DETAIL, stack.getHoverName(), 1);
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/core/entity/ai/workers/util/BuildingStructureHandler.java]: I would not add all individual blocks here, this would become a lot and we have to sync all of this data for all the builders to the clients etc.

**Review by Raycoms — COMMENTED** [review]
I like the barracks overview stats, makes the barracks hut block more useful.
I would not individually track all builder blocks as this would become too much data.
And if we don't do that, we probably can probably skip the stat filtering.

**Comment by armele** [comment]
Good point on the builders - I will change this to just be blocks placed as well as the four building stage counts. I do think that with some of the crafters (carpenter and stonemason come to mind) it will be useful to keep the ability to filter the stats. How strongly do you feel about wanting that out?

**Review by someaddons — APPROVED** [review]
