### PR TITLE
Don't allow removing datapack recipes unless holding Ctrl

### LINKED ISSUE #6708: breaking the recipe cap of sawmill
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.690-ALPHA
- Structurize Version: 0.13.148-ALPHA
- Related Mods and their Versions: none

## Expected behavior

the number of recipe saved should be under the cap.

## Actual behavior

the feature where the recipe for timber frame around wooden center is automatically added
to the sawmill ignore the total number of recipe the saw mill have.

[

](url)

## Steps to reproduce the issue

1. Fill a saw mill completely with recipes, including a mix of player made recipe and auto generated ones, using a variety of wood types
2. remove one or more of the auto-generated recipes to bring down the total number of recipes
3. quickly add new recipes before the game updates and re-add those auto-generated ones
4. close out the menu, wait a bit, open it again and you break the cap of recipes

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #11248: Can't remove default recipe from crafters, it get added back and overflow max recipes
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

minecolonies-1.1.1143-1.21.1-snapshot

### Structurize Version

structurize-1.0.787-1.21.1-snapshot

### Related Mods and their Versions

_No response_

### Current Behavior

Removing a default recipe from any crafter, it will instantly be added back after making any change on the crafter.

Image

In this case, I removed the first 3 recipes, then I added one I needed, once I back to the crafting list, it not only the recipe I added but all first 3 as well, ending with 31/30 recipes.

I believe it does that even if it is not maxed out, the removed default recipe is always added back

### Expected Behavior

Removed default recipe from that crafter should not be added back upon updating the crafting list.

### Reproduction Steps

Get any crafter that have default recipes like (Fletcher, Stonemason, etc).
In this case I'm using the Stonemason.

Max out the recipes it can learn (10/10, 30/30, whatever research level allows).

Once maxed out, on the crafting list, remove one of the default recipes, then click on add, and add another recipe that isn't the default and is also not in the list.

Go back to the recip list, the default recipe will be back in the list and the  count will have pass the max.

### Logs

https://gist.github.com/pwaksman973/f0cb7aa1b8ff9d2b948fc4360d99b55b

### Anything else?

_No response_

### Footer

---
 ## Viewers
  *  Add a 👍 reaction to the bug report if you are also affected. This helps the bug report become more visible without cluttering the comments.
  *  ⚠️ Only add a comment if you have new insights or background information not already mentioned. Off-topic or "+1" comments will be deleted to keep the discussion focused.

### PR DESCRIPTION
**Pull request by uecasm**
Closes #6708
Closes #11248

# Changes proposed in this pull request
- Disable the "remove recipe" button for datapack-added recipes.
    - The button can still be clicked if you hold the Ctrl key, just in case something derps and you need to reset it.
    - There's a tooltip telling the player this.

## Testing
- [x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please (should port)

### CODE REVIEW

**Review by Raycoms — DISMISSED** [review]

File: src/main/java/com/minecolonies/core/client/gui/modules/WindowListRecipes.java [hunk 1]
```diff
@@ -184,12 +184,18 @@ public void updateElement(final int index, @NotNull final Pane rowPane)
...
-                    if (removeButton != null)
+                    if (module.isRecipeAlterationAllowed())
+                    {
+                        removeButton.setVisible(true);
+                        removeButton.setEnabled(recipe.getRecipeSource() == null || Screen.hasControlDown());
+                    }
+                    else
                     {
                         removeButton.setVisible(false);
+                        removeButton.setEnabled(false);
```
Comment (Thodor12) [inline src/main/java/com/minecolonies/core/client/gui/modules/WindowListRecipes.java]:
```suggestion
                        removeButton.off();
```

File: src/main/java/com/minecolonies/core/client/gui/modules/WindowListRecipes.java [hunk 2]
```diff
@@ -184,12 +184,18 @@ public void updateElement(final int index, @NotNull final Pane rowPane)
...
-                if (!module.isRecipeAlterationAllowed())
+                final Button removeButton = rowPane.findPaneOfTypeByID(BUTTON_REMOVE, Button.class);
+                if (removeButton != null)
                 {
-                    final Button removeButton = rowPane.findPaneOfTypeByID(BUTTON_REMOVE, Button.class);
-                    if (removeButton != null)
+                    if (module.isRecipeAlterationAllowed())
+                    {
+                        removeButton.setVisible(true);
+                        removeButton.setEnabled(recipe.getRecipeSource() == null || Screen.hasControlDown());
```
Comment (Thodor12) [inline src/main/java/com/minecolonies/core/client/gui/modules/WindowListRecipes.java]: I'm not sure locking it behind holding CTRL is a good idea without some kind of targeted information that it works this way. People are just going to see a previously unlocked button now disabled without any kind of information on how it actually works now.

We should come up with a proper idea and not shoehorn a quick and dirty fix into it.

**Review by Thodor12 — CHANGES_REQUESTED** [review]

File: src/main/java/com/minecolonies/core/client/gui/modules/WindowListRecipes.java (hunk 1 above)
Comment (uecasm) [reply src/main/java/com/minecolonies/core/client/gui/modules/WindowListRecipes.java]: That's not an improvement.  This is deliberately mirroring the other if branch.

**Comment by MotionlessTrain** [comment]
Probably also closes #6708

**Comment by uecasm** [comment]
Added a tooltip.

**Review by Thodor12 — APPROVED** [review]

**Review by Raycoms — APPROVED** [review]

**Review by someaddons — APPROVED** [review]
