### PR TITLE
Fix completition message, furnace issue and resourcelist display

### LINKED ISSUE #7293: Builder notifications on manual mode
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version: 0.14.223-ALPHA-universal
- Structurize Version:0.13.177-ALPHA-universal
- Related Mods and their Versions: - Adventure pack

## Expected behavior
Builder in manual mode with a queue, doesn't inform you they need a job if they already have a task

## Actual behavior
Every time a builder finishes a task, they inform you that they are ready for another job, however, has another task ready for the,

## Steps to reproduce the issue

1. Change builder to manual mode
2.  Queue up a few tasks for them
3. Note the chat message when they finish one job and move on to the next

### Notes
No other issues - maybe as a suggestion add how many tasks they have left in queue as a chat message?

e.g - " I have completed X, I'm now working on X with X amount of jobs remaining.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #7308: Courier AI Issue
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.224

### Logs

- latest.log: https://gist.github.com/Pikman1210/8f61716ffeb623c5aa9236b33a3d6ae2
- https://gist.githubusercontent.com/Pikman1210/8f61716ffeb623c5aa9236b33a3d6ae2/raw/49b3e9fc8a2950fcebf9cb86e95967b26a393739/latest.log

## Steps to reproduce the issue / details

Just reporting the AI issue. I honestly have no idea how this happened. 

### Notes

The citizen had a "work issue" that told me to make this issue

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #7293
Closes #7308
Closes #

# Changes proposed in this pull request:
- Fix issue with the manual message
- Reorganize messages to be all in one place (what a mess)
- Fix resource scroll display
- Fix exception of the furnace users

Review please

### CODE REVIEW

**Review by Mekle001 — DISMISSED** [review]

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java [hunk 1]
```diff
@@ -348,4 +350,61 @@ protected int getActionsDoneUntilDumping()
     {
         return ACTIONS_UNTIL_DUMP;
     }
+
+    @Override
+    protected void sendCompletionMessage(final WorkOrderBuildDecoration wo)
+    {
+        super.sendCompletionMessage(wo);
+
+        final String structureName = job.getBlueprint().getName();
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java]: why are you manually using the blueprints name instead of using the workorders display name?

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java]: Good question

**Review by someaddons — APPROVED** [review]

**Review by marchermans — APPROVED** [review]
