### PR TITLE
Fix bug with placing supplyships in others colonies.

### LINKED ISSUE #379: Supply Ship Underwater made of WATER.
Minecolonies version 1.10.2 on Official Server
When placing the Supply ship underwater it spawns a supply ship made of WATER and the chest as well.
underwater
underwater_1

### LINKED ISSUE #541: [b2464] placing supply ship too close to claimed area ...
In build 2464, when placing a supply ship, if you place it close to another players claimed area, instead of telling you that it is too close, it tries to build the ship and fails only rendering as much of it as it can and because it fails to build the ship, you don't get the starter chest with the town hall placer in it and further you can't place another supply ship obviously.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #541
Closes #379 

# Changes proposed in this pull request:
- New method to check for colonies at a certain location.
- Fix so that supplyships can't be build in someone elses colony.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/ColonyManager.java [hunk 1]
```diff
@@ -64,17 +64,23 @@
...
      * The list of colony views.
      */
     @NotNull
-    private static final ColonyList<ColonyView>     colonyViews           = new ColonyList<>();
+    private static final ColonyList<ColonyView>     colonyViews     = new ColonyList<>();
+
+    /**
+     * A buffer value to be sure to be outside of the colony.
+     */
+    private static final int BUFFER                                 = 10;
```
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/colony/ColonyManager.java:82]: why not use the already in config value?

File: src/main/java/com/minecolonies/coremod/colony/ColonyManager.java [hunk 2]
```diff
@@ -942,4 +948,26 @@ public static IMessage handleColonyViewRemoveWorkOrderMessage(final int colonyId
...
         return null;
     }
+
+    /**
+     * Check if a given coordinate is inside any other colony.
+     * @param world the world to check in.
+     * @param pos the position to check.
+     * @return true if a colony has been found.
+     */
+    public static boolean isCoordinateInAnyColony(@NotNull final World world, final BlockPos pos)
```
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/colony/ColonyManager.java:958]: you sure we do not have this already somewhere?

**Review by marvin-bitterlich — CHANGES_REQUESTED** [review]
looking good. Just minor stuff

File: src/main/java/com/minecolonies/coremod/colony/ColonyManager.java (hunk 1 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/ColonyManager.java:82]: because players can configure it. What if the put the padding to 0.
I still want to be sure here.

File: src/main/java/com/minecolonies/coremod/colony/ColonyManager.java (hunk 2 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/ColonyManager.java:958]: Nope only isCoordinateInColony(Colony, pos) we have.

**Comment by marvin-bitterlich** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/688/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Review by marvin-bitterlich — APPROVED** [review]
