### PR TITLE
fix visitor name loading & builder requests

### LINKED ISSUE #10858: Patreon player skins have lost their names
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.876

### Structurize Version

1.20.1-1.0.771

### Related Mods and their Versions

Forge 47.4.0
I was using the Dwarven namepack

### Current Behavior

Image

This is a patreon skin that should be named Undead. They still have their story, unique recruiting item and skin, but they lost their name.
https://discord.com/channels/472875599422291968/1366299342427783230/1366299342427783230

Image
Shin reported this one. He should be named Doggus.
https://discord.com/channels/472875599422291968/1361845471487852724/1361845471487852724

Image
From John https://discord.com/channels/472875599422291968/473575384445878273/1371564158587502673

### Expected Behavior

Patreon skins to have their unique name

### Reproduction Steps

I've seen it a fair bit, but it just occurs and I can't say why.

### Logs

No log. Can find one if you need one though.

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #10862: New builder fixes in latest version cause builders to request more than needed
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

minecolonies-1.20.1-1.1.884-snapshot.jar

### Structurize Version

.772

### Related Mods and their Versions

_No response_

### Current Behavior

When builders need an item for a build, it is showing up multiple times on clipboard.
in my game it was showing 3 request for a gray bed, when only one was needed.

Knaxia on discord had it happen in latest 1.21.1 version as well https://discord.com/channels/139070364159311872/1284909613401247785/1372012440769921075

Trying to get screenshots, but so far my builder aren't asking for anything I don't have

### Expected Behavior

They only ask for the one thing they need

### Reproduction Steps

Make a build order
wait for them to request stuff you don't have in stock

### Logs

https://gist.github.com/Talyda/f34b2289c309d774f422d385307af8e2

### Anything else?

Will try and get screenshots once they finish digging and start building - just wanted to make the issue before I forgot=P

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #10862
Closes #10858

# Changes proposed in this pull request
- Fix weird builder requests
- Fix visitor name loading

## Testing
- [x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/core/colony/buildings/modules/BuildingResourcesModule.java [hunk 1]
```diff
@@ -336,7 +336,13 @@ public void checkOrRequestBucket(@Nullable final BuilderBucket requiredResources
             return;
         }
 
-        resourceloop:
+        final ImmutableList<IRequest<? extends Stack>> list = building.getOpenRequestsOfType(-1, TypeToken.of(Stack.class));
+        final Set<ItemStorage> requestedItems = new HashSet<>();
+        for (final IRequest<? extends Stack> request : list)
+        {
+            requestedItems.add(new ItemStorage(request.getRequest().getStack()));
```
Comment (someaddons) [inline src/main/java/com/minecolonies/core/colony/buildings/modules/BuildingResourcesModule.java:343]: why create a new itemstorage when it is only used for checking contains? that should be only needed if you need to modify it, should be able to just add to the existing ones from the list

**Review by someaddons — APPROVED** [review]

**Comment by Talyda** [comment]
Didn't fix builders Ray!
I have 4 requests for hoppers in my clipboard, both builders need one each

**Comment by Raycoms** [comment]
> Didn't fix builders Ray! I have 4 requests for hoppers in my clipboard, both builders need one each

It didn't fix requests made before the update. It should be fine for future requests?

**Comment by Talyda** [comment]
Was new requests

**Comment by Talyda** [comment]
And it's on the clipboard without the name of the builder again too.  (miners too)

Lemme cancel everything and have them request again to be sure

**Comment by Raycoms** [comment]
> And it's on the clipboard without the name of the builder again too. Lemme cancel everything and have them request again to be sure

Not having the name is correct, the building requests it so that it stays active for the next builder too.

**Comment by Raycoms** [comment]
Like, if a builder dies

**Comment by Talyda** [comment]
Oh, thought it had a name, like the miner one does in this screenie, so you knew which builder =P
image

Cancelled the jobs, did request system reset, and restarted the game =P
Waiting on requests now...
God they take a long time when you are specifically waiting for them LOL

Nope, still weird.

**Comment by Talyda** [comment]
Required resources here
image

Requests on person here
image

Clipboard (does show builder name for one!)
image

**Comment by Raycoms** [comment]
odd, I'll have to spend some more time debugging later then

**Comment by Talyda** [comment]
Other builder isn't requesting any either, so it's not theirs =)

**Comment by Talyda** [comment]
Actually, it IS only asking for normal amount of the other things though - will keep an eye on it for the next 20 minutes til I go offline

**Comment by Talyda** [comment]
Yeah, nah, second builder is doing it now for hoppers. But not for everything on their requests
