### PR TITLE
Fix soy bottle duplication

### LINKED ISSUE #10863: Making soy milks results in an extra bottle
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.884

### Structurize Version

1.20.1-1.0.772

### Related Mods and their Versions

1. Forge - 47.4.0
2. blockUI - 1.20.1-1.0.190
3. domum-ornamentum - 1.20.1-1.0.285
4. multi-pistion - 1.20.1-1.2.43
5. towntalk - 1.20.1-1.1.0

### Current Behavior

When crafting soy milk either by hand or through the cookery it leaves behind an empty bottle after crafting which results in an extra bottles since using soy milk also produces an empty bottle after use.

### Expected Behavior

Either crafting soy milk shouldn't leave an empty bottle or using soy milk shouldn't leave an empty bottle.

### Reproduction Steps

1. preform the soy milk crafting recipe either by hand or through the cookery
2. use soy milk in a crafting recipe
3. results in having an extra bottle

### Logs

https://pastebin.com/HsxiThb9

### Anything else?

Image

Image

Image

Image

Image

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by uecasm**
Closes #10863

# Changes proposed in this pull request
- Fixes duplication of empty bottle when crafting soy milk.
- Adds some simple player recipes to transfer water/milk from buckets to large bottles.
- Fixes (unrelated) crash in NBT datagen due to spawn eggs.

## Testing
- [x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please (do not port; will need changes)

### CODE REVIEW

File: src/main/java/com/minecolonies/api/crafting/BottleRecipe.java [hunk 1]
```diff
@@ -0,0 +1,275 @@
...
+            {
+                inputs.set(i, Ingredient.fromNetwork(buf));
+            }
+            final ItemStack output = buf.readItem();
+
+            return new BottleRecipe(id, output, inputs);
+        }
+
+        @Override
+        public void toNetwork(@NotNull final FriendlyByteBuf buf,
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/api/crafting/BottleRecipe.java]: That feels like a lot of methods, do we need all of them? I thought this should be more of a straightforward copy of shapeless with only the remainingitems changing

Comment (uecasm) [reply src/main/java/com/minecolonies/api/crafting/BottleRecipe.java]: That's exactly what it is.  Though I lumped the `Builder` in there too, whereas with Shapeless it's in a separate file.

Pretty sure it will get shorter in 1.21, where a lot of this will be codecs instead, but I haven't looked closely at that yet.

**Review by Raycoms — DISMISSED** [review]

**Review by someaddons — DISMISSED** [review]
