### PR TITLE
Fix/double warehouse

### LINKED ISSUE #10145: [BUG] <Multiple Warehouses Breaks Tasks System"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.629-BETA.jar

### Structurize Version

Warehouse 

### Related Mods and their Versions

_No response_

### Current Behavior

When more than one warehouse is created in a colony, the newest warehouse created will not complete tasks. 

Ex.) Builder requires Cobblestone, Warehouse 1 does not have cobblestone. Warehouse 2, does have cobblestones. As warehouse 2nd was created 2nd, it will not complete or register the task. The courier will idle. However, the building hut/builder, will register the task as assigned to warehouse 2.

### Expected Behavior

The warehouse receives the request, assigns the request as a task, and then the courier completes the task as requested. Assuming relevant resources exist in the warehouse. 

### Reproduction Steps

1. Create two operational warehouses in one colony
2. Create a request through a builder
3. Deposit required items for said request, specifically in the warehouse built 2nd

### Logs

https://gist.github.com/Petonix954/8d72ae64fd19d3940bea2cd4801de127

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #10145
Closes #
Closes #

# Changes proposed in this pull request:
- Make courier not accept tasks of other warehouses
- Make warhouses partial resolve
- Couple of performance improvements
- Fix some spammy debug logging

[ x ] Yes I tested this before submitting it.
[ ] I also did a multiplayer test.

Review please

### CODE REVIEW

**Review by Thodor12 — DISMISSED** [review]

File: src/main/java/com/minecolonies/api/colony/requestsystem/requestable/Stack.java [hunk 1]
```diff
@@ -342,7 +342,7 @@ public boolean matchDamage()
     @Override
     public IDeliverable copyWithCount(final int newCount)
     {
-        return new Stack(this.theStack, this.matchDamage, this.matchNBT, this.matchOreDic, this.result, newCount, this.minCount);
+        return new Stack(this.theStack, this.matchDamage, this.matchNBT, this.matchOreDic, this.result, newCount, Math.min(newCount, this.minCount));
```
Comment (someaddons) [inline src/main/java/com/minecolonies/api/colony/requestsystem/requestable/Stack.java]: Math.max

Comment (Raycoms) [reply src/main/java/com/minecolonies/api/colony/requestsystem/requestable/Stack.java]: No, right min, but will move into constructor

**Review by someaddons — APPROVED** [review]
