### PR TITLE
Tool handling

### LINKED ISSUE #9764: [BUG] Crafter recipe added by datapck does not ignore damage tag of tool item
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.453 - RELEASE

### Structurize Version

1.0.683 - RELEASE

### Related Mods and their Versions

1. Forge Version: 43.3.2
2. BlockUI Version: 1.0.140 - BETA
3. Domum Ornamentum: 1.0.146 - BETA
4. Farmer's Delight: 1.2.4

### Current Behavior

I made a custom craftman recipe for assistant cook via datapack,
This photo is JEI screen for that recipe

And this pastebin link is datapack source
https://pastebin.com/0Y0QTi3K

According to Mirality says to me in discord,
Recipe should ignore nbt tag of "iron knife"

BUT it doesn't, check the nbt tag of "iron knife", if durability is not max they can't use it

### Expected Behavior

Custom recipe should ignore the nbt tag of "iron knife"
Or find another way to add "iron knife" using recipe

### Reproduction Steps

1. make a datapack
2. make a json file and paste datapack code of below pastebin link
https://pastebin.com/0Y0QTi3K
3. put the json file in following directory 
/data/minecolonies/crafterrecipes/assistantcook/

### Logs

https://gist.github.com/supernova0102/24cc6583bae0539368b79c5ca00cedc2

### Anything else?

I'm attatching minecolonies discord message link about discussion of this issue
https://discord.com/channels/139070364159311872/976625343358189618/1203233898570457108

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #9764
Closes #
Closes #

# Changes proposed in this pull request:
- Simplify tool handling
-
-

[ x ] Yes I tested this before submitting it.
[ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/api/crafting/RecipeStorage.java [hunk 1]
```diff
@@ -166,38 +164,57 @@ public RecipeStorage(final IToken<?> token, final List<ItemStorage> input, final
...
             }
 
+            final ItemStack container = inputItem.getItemStack().getCraftingRemainingItem();
+            if (secOutputs == null && !ItemStackUtils.isEmpty(container))
+            {
+                container.setCount(inputItem.getAmount());
+                this.secondaryOutputs.add(container);
+            }
+
+            for(ItemStack result: this.secondaryOutputs)
```
Comment (Thodor12) [inline src/main/java/com/minecolonies/api/crafting/RecipeStorage.java]: Formatting

File: src/main/java/com/minecolonies/api/crafting/RecipeStorage.java [hunk 2]
```diff
@@ -166,38 +164,57 @@ public RecipeStorage(final IToken<?> token, final List<ItemStorage> input, final
...
+            {
+                if(ItemStackUtils.compareItemStacksIgnoreStackSize(inputItem.getItemStack(), result, false, true) && result.isDamageableItem())
```
Comment (Thodor12) [inline src/main/java/com/minecolonies/api/crafting/RecipeStorage.java]: Formatting

**Review by Thodor12 — DISMISSED** [review]

**Review by Thodor12 — APPROVED** [review]

**Review by someaddons — APPROVED** [review]
