### PR TITLE
Couple o fixes

### LINKED ISSUE #10920: Dying citizen causing ticking entity crash
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [x] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.909-snapshot

### Structurize Version

1.20.1-1.0.773-snapshot

### Related Mods and their Versions

Forge 1.20.1 47.4.0
blockui-1.20.1-1.0.190-snapshot
domum_ornamentum-1.20.1-1.0.285-snapshot

### Current Behavior

In multiplayer, a player killing their citizen with a lava bucket causes a ticking entity which crashes the server. The server will crash again shortly if the server is re-opened.

### Expected Behavior

The citizen dying and spawning their gravestone without causing a crash.

### Reproduction Steps

Killing a citizen of your colony by placing lava on them, based on the band-aid fix I was given, the citizen should need to have a job. 

### Logs

https://gist.github.com/ImCommanderCody/fe3732361e71441471de18f70bac55fd

### Anything else?

**Shindria.** on the MineColonies discord was very helpful. She provided **/mc colony requestsystem-reset-all** as a band-aid fix, which stopped the server from crashing, but the same crash happened again when the player resumed killing their citizens with lava. There are more logs and info posted in the discord from that conversation: https://discord.com/channels/139070364159311872/1003402487417548801/1379630113762836480

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #10921: Chef keeps requested food!
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [x] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.901

### Structurize Version

1.20.1-1.0.772

### Related Mods and their Versions

Forge: 47.4.0
Modpack link: https://www.curseforge.com/minecraft/modpacks/wolf-craft-colonies

### Current Behavior

A report from one of our players on the server. She tried reporting herself but her account has been locked down for some reason, so her report may pop up later. (https://github.com/ldtteam/minecolonies/issues/10917)

"My chef is the only reliable complainer about the menu. I've been watching her for days. Most recently, I staring into her inventory as she moved around and worked. 

My chef keeps the first 10 food items in her inventory. She will make the foods requested by the restaurant, but keeps the first ten when she goes to put them up. If the restaurant requests 16 ramen, they get six because she's keeping 10. Then they order 10 more, so she makes ten and sends them that set of ten because she has ten in her inventory. If she makes spicy eggplant next, but has eaten a ramen, she might make 16 spicy eggplant, but send only 15 to the restaurant (triggering the request of another 16) because she has only 9 ramen, now. Right now, she has one spicy eggplant, one fish dinner, and 8 dried kelp. She is making spicy eggplant, so all of them go into the first inventory spot. She turns around and deposits all but the first 10 spicy eggplant, and then all the left over ingredients, including now the 8 dried kelp and the singular fish dinner.
If she is eating from her inventory, that's why she's popping the red gear for not enough variety. She's not eating poor quality foods (unless she's getting to the dried kelp and I can't tell). She may be not eating what the cook gives her. 

I began staring into her inventory all the time because I can track what's in her inventory even if she's sick in the hospital, which was her next move. 10 spicy eggplant, 16 noodles, 5 dried kelp, 16 garlic, one potato, one carrot.

Confirmed. Just saw her eat one of the spicy eggplant from her work station, never going to the restaurant.
Right after she ate the spicy eggplant, she sat at the restaurant, grabbing garlic as she went. She sat there with 9 spicy eggplant and one garlic (10 items).
Then she ate another spicy eggplant, was never served by the cook, and went back to work.
The first thing she did when she went back to work was make a singular ramen and another load of spicy eggplant. Once again, everything except ten of the spicy eggplant went into her racks. 
So that's what's happening. As long as she keeps one set of 10 foods in that first slot of her inventory, that's what she's eating. When she refills the normal restaurant stash, she's refilling her own stash first. She sits at the restaurant to eat from her stash, and will never get variety."

They also reported on public discord: https://discord.com/channels/139070364159311872/1003402487417548801/1379303831053013122

### Expected Behavior

Chef should leave the food alone and eat from the restaurant like everyone else? Maybe? 

### Reproduction Steps

Make a busy colony. Watch the chef steal food!

### Logs

Can give if you want them

### Anything else?

Reporting for one of our players who can't report herself. Will play middleman if you have questions.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #10920
Closes #10921

# Changes proposed in this pull request
- Builder should only move request that are not already sync assigned to them, that was causing duplication and missing request issues.
- Chef/baker shouldn't eat the food that is currently assigned to them.
- Still issues during cancel shouldn't crash

## Testing
- [x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/core/colony/buildings/workerbuildings/BuildingBaker.java [hunk 1]
```diff
@@ -88,6 +95,33 @@ public boolean canEat(final ItemStack stack)
         {
             return false;
         }
+
+        final ICitizenData citizenData = getFirstModuleOccurance(WorkerBuildingModule.class).getFirstCitizen();
```
Comment (someaddons) [inline src/main/java/com/minecolonies/core/colony/buildings/workerbuildings/BuildingBaker.java]: wrong module lookup

**Review by someaddons — APPROVED** [review]
