### PR TITLE
fix 7389

### LINKED ISSUE #7389: Undertaker AI problem when resurrecting a guard
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:0.14.286-ALPHA

### Logs

- latest.log: https://gist.github.com/MotionlessTrain/79ece2e05ffd046235ccd4413dc2a624

## Steps to reproduce the issue / details

A guard (archer) died. The undertaker came to pick up the grave, and managed to resurrect the archer.
Apparently, something went wrong reassigning the guard tower to this archer, as the undertaker has enclosed AI issue,
and the archer stood somewhere in the neighbourhood not knowing what to do.

I could solve the issue myself by hiring the archer back at their tower.

Just reporting the AI issue. 

### Notes
The guard tower was not claimed by anyone else in the meantime.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #7389
Closes #
Closes #

# Changes proposed in this pull request:
- Kicks the citizen out of their job on resurrection to avoid any assignment issues (double job assignment or similar).
- Also kicks them out of their citizen hut to avoid too many citizens living in the same hut.
-

Review please

### CODE REVIEW

**Review by marchermans — DISMISSED** [review]

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/undertaker/EntityAIWorkUndertaker.java [hunk 1]
```diff
@@ -347,6 +347,7 @@ private IAIState tryResurrect()
             if (chance >= random.nextDouble())
             {
                 final ICitizenData citizenData = buildingGraveyard.getColony().getCitizenManager().resurrectCivilianData(buildingGraveyard.getLastGraveData().getCitizenDataNBT(), true, world, gravePos);
+                citizenData.setWorkBuilding(null);
```
Comment (MotionlessTrain) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/undertaker/EntityAIWorkUndertaker.java]: Reading my own log, I thought I saw the error occured in the resurrectCivilianData call in the line above.
If so, this won't fix anything.

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/undertaker/EntityAIWorkUndertaker.java]: True, I thought this was on the next AI tick....
