### PR TITLE
Fix/rtp death

### LINKED ISSUE #184: Teleport to Colony [$5]
Admins and Members of a colony should be able to teleport to their townhall.

We should make this configurable for server admins to allow it or not. 

[Bountysource](https://www.bountysource.com/issues/41624375-teleport-to-colony?utm_source=41624375&utm_medium=shield&utm_campaign=ISSUE_BADGE)

<bountysource-plugin>

---
There is a **[$5 open bounty](https://www.bountysource.com/issues/41624375-teleport-to-colony?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by opmis**
Closes #184 

# Changes proposed in this pull request:
- Adds hometp command
-Fixed the death trap
-Dropping player a little higher
-Turned damage off during TP

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
OKay seems okay for me.
Just will have to wait for the hometp merge coming in to compare it correctly.

File: src/main/java/com/minecolonies/coremod/commands/AbstractSingleCommand.java [hunk 1]
```diff
@@ -17,14 +18,13 @@
...
     private final String[] parents;
     public static final String NOT_PERMITTED = "You are not allowed to do that!";
-    public static final Integer PERMNUM = Configurations.opLevelForServer;
     enum Commands
     {
-        CITIZENINFO, COLONYTP, DELETECOLONY, KILLCITIZENS, LISTCITIZENS, RESPAWNCITIZENS, SHOWCOLONYINFO, ADDOFFICER, CHANGE_COLONY_OWNER, REFRESH_COLONY
+        CITIZENINFO, COLONYTP, DELETECOLONY, KILLCITIZENS, LISTCITIZENS, RESPAWNCITIZENS, SHOWCOLONYINFO, ADDOFFICER, CHANGE_COLONY_OWNER, REFRESH_COLONY, HOMETP, MC_BACKUP
     }
 
     /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/AbstractSingleCommand.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/coremod/commands/RandomTeleportCommand.java [hunk 2]
```diff
@@ -92,6 +92,7 @@ public void execute(@NotNull MinecraftServer server, @NotNull ICommandSender sen
         }
         playerToTeleport.getCommandSenderEntity().addChatMessage(new TextComponentString("Buckle up buttercup, this ain't no joy ride!!!"));
         teleportPlayer(sender, playerToTeleport);
+        playerToTeleport.fallDistance=-5;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/RandomTeleportCommand.java]: MINOR Assign this magic number 5 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/commands/HomeTeleportCommand.java [hunk 3]
```diff
@@ -0,0 +1,136 @@
...
+
+    @NotNull
+    @Override
+    public String getCommandUsage(@NotNull final ICommandSender sender)
+    {
+        return super.getCommandUsage(sender) + "home";
+    }
+
+    @Override
+    public void execute(@NotNull MinecraftServer server, @NotNull ICommandSender sender, @NotNull String... args) throws CommandException {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/HomeTeleportCommand.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

File: src/main/java/com/minecolonies/coremod/commands/HomeTeleportCommand.java [hunk 4]
```diff
@@ -0,0 +1,136 @@
...
+
+            }
+            else
+            {
+                sender.getCommandSenderEntity().addChatMessage(new TextComponentString(CANT_FIND_PLAYER));
+                return;
+            }
+
+
+            if (colony.equals(null))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/HomeTeleportCommand.java]: BLOCKER Change this condition so that it does not always evaluate to "false" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2583)
CRITICAL Remove this call to "equals"; comparisons against null always return false; consider using '== null' to check for nullity. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2159)

File: src/main/java/com/minecolonies/coremod/commands/HomeTeleportCommand.java [hunk 5]
```diff
@@ -0,0 +1,136 @@
...
+        if (MinecoloniesCommand.canExecuteCommand((EntityPlayer) sender))
+        {
+            playerToTeleport.getCommandSenderEntity().addChatMessage(new TextComponentString("There's no place like home, there's no place like home..."));
+            teleportPlayer(playerToTeleport, colonyId);
+        }
+        else
+        {
+            sender.getCommandSenderEntity().addChatMessage(new TextComponentString("Please wait at least " + Configurations.teleportBuffer + " seconds to teleport again"));
+        }
+        return;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/HomeTeleportCommand.java]: MINOR Avoid unnecessary return statements [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3AUnnecessaryReturn)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 7 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 4 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractSingleCommand.java#L116](https://github.com/Minecolonies/minecolonies/blob/272b82505f4d87f879b30b4edf46099138822dac/src/main/java/com/minecolonies/coremod/commands/AbstractSingleCommand.java#L116): The Cyclomatic Complexity of this method "canCommandSenderUseCommand" is 13 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[BLOCKER]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-blocker.png 'Severity: BLOCKER'
[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/commands/AbstractSingleCommand.java [hunk 6]
```diff
@@ -17,14 +18,13 @@
...
     private final String[] parents;
     public static final String NOT_PERMITTED = "You are not allowed to do that!";
-    public static final Integer PERMNUM = Configurations.opLevelForServer;
     enum Commands
     {
-        CITIZENINFO, COLONYTP, DELETECOLONY, KILLCITIZENS, LISTCITIZENS, RESPAWNCITIZENS, SHOWCOLONYINFO, ADDOFFICER, CHANGE_COLONY_OWNER, REFRESH_COLONY
+        CITIZENINFO, COLONYTP, RTP, DELETECOLONY, KILLCITIZENS, LISTCITIZENS, RESPAWNCITIZENS, SHOWCOLONYINFO, ADDOFFICER, CHANGE_COLONY_OWNER, REFRESH_COLONY, HOMETP, MC_BACKUP
     }
 
     /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/AbstractSingleCommand.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/coremod/commands/ColonyTeleportCommand.java [hunk 7]
```diff
@@ -0,0 +1,76 @@
...
+    {
+        return super.getCommandUsage(sender) + "colonytp" + "<colID>";
+    }
+
+    @Override
+    public void execute(@NotNull MinecraftServer server, @NotNull ICommandSender sender, @NotNull String... args) throws CommandException
+    {
+
+        //see if player is allowed to use in the configs
+        if (!canCommandSenderUseCommand(COLONYTP))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/ColonyTeleportCommand.java]: MAJOR Avoid if (x != y) ..; else ..; [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3AConfusingTernary)

File: src/main/java/com/minecolonies/coremod/commands/RandomTeleportCommand.java [hunk 8]
```diff
@@ -91,7 +91,9 @@ public void execute(@NotNull MinecraftServer server, @NotNull ICommandSender sen
             return;
         }
         playerToTeleport.getCommandSenderEntity().addChatMessage(new TextComponentString("Buckle up buttercup, this ain't no joy ride!!!"));
+
         teleportPlayer(sender, playerToTeleport);
+        playerToTeleport.fallDistance=-5;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/RandomTeleportCommand.java]: MINOR Assign this magic number 5 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/util/TeleportToColony.java [hunk 9]
```diff
@@ -0,0 +1,85 @@
...
+    /**
+     * Private constructor to hide the implicit public one.
+     */
+    public TeleportToColony(@NotNull final String... parents)
+    {
+
+    }
+
+    @NotNull
+    public static void ColonyTeleport(@NotNull MinecraftServer server, @NotNull ICommandSender sender, @NotNull String... args){
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/util/TeleportToColony.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR Document this public method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)
MINOR Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS00100)

File: src/main/java/com/minecolonies/coremod/util/TeleportToColony.java [hunk 10]
```diff
@@ -0,0 +1,85 @@
+package com.minecolonies.coremod.util;
+
+import com.minecolonies.coremod.colony.Colony;
+import com.minecolonies.coremod.colony.ColonyManager;
+import com.minecolonies.coremod.colony.IColony;
+import com.minecolonies.coremod.commands.MinecoloniesCommand;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/util/TeleportToColony.java]: MINOR Remove this unused import 'com.minecolonies.coremod.commands.MinecoloniesCommand'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/util/TeleportToColony.java [hunk 11]
```diff
@@ -0,0 +1,85 @@
...
+import com.minecolonies.coremod.configuration.Configurations;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/util/TeleportToColony.java]: MINOR Remove this unused import 'com.minecolonies.coremod.configuration.Configurations'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/util/TeleportToColony.java [hunk 12]
```diff
@@ -0,0 +1,85 @@
...
+ */
+public final class TeleportToColony
+{
+    private static final String CANT_FIND_COLONY = "No Colony found for teleport, please define one.";
+    private static final String CANT_FIND_PLAYER = "No player found for teleport, please define one.";
+
+    /**
+     * Private constructor to hide the implicit public one.
+     */
+    public TeleportToColony(@NotNull final String... parents)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/util/TeleportToColony.java]: MAJOR Hide this public constructor. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1118)
MINOR Document the parameter(s): parents [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

File: src/main/java/com/minecolonies/coremod/util/TeleportToColony.java [hunk 13]
```diff
@@ -0,0 +1,85 @@
...
+     * @param playerToTeleport the player which shall be teleported.
+     */
+    private static void teleportPlayer(final EntityPlayer playerToTeleport,int colID)
+    {
+        final Colony colony = ColonyManager.getColony(colID);
+        final BlockPos position = colony.getCenter();
+
+        if (colID >= 1)
+        {
+            playerToTeleport.setPositionAndUpdate(position.getX(),position.getY()+2,position.getZ());
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/util/TeleportToColony.java]: CRITICAL Cast one of the operands of this addition operation to a "double". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2184)

File: src/main/java/com/minecolonies/coremod/commands/HomeTeleportCommand.java [hunk 14]
```diff
@@ -0,0 +1,77 @@
...
+        //see if player is allowed to use in the configs
+            if (!canCommandSenderUseCommand(HOMETP))
+            {
+                sender.getCommandSenderEntity().addChatMessage(new TextComponentString("This is not allowed on this server."));
+                return;
+            }
+            else
+            {
+                //send the info to the Colony TP utils
+                String homeID = "99999";
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/HomeTeleportCommand.java]: MINOR Local variable 'homeID' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/commands/HomeTeleportCommand.java [hunk 15]
```diff
@@ -0,0 +1,77 @@
...
+    {
+        return super.getCommandUsage(sender) + "home";
+    }
+
+    @Override
+    public void execute(@NotNull MinecraftServer server, @NotNull ICommandSender sender, @NotNull String... args) throws CommandException
+    {
+
+        //see if player is allowed to use in the configs
+            if (!canCommandSenderUseCommand(HOMETP))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/HomeTeleportCommand.java]: MAJOR Avoid if (x != y) ..; else ..; [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3AConfusingTernary)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 14 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 4 major
* ![MINOR][MINOR] 9 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractSingleCommand.java#L116](https://github.com/Minecolonies/minecolonies/blob/457ffeaf00818a5fc6021ce33f1e3c5de4056f92/src/main/java/com/minecolonies/coremod/commands/AbstractSingleCommand.java#L116): The Cyclomatic Complexity of this method "canCommandSenderUseCommand" is 14 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/util/TeleportToColony.java [hunk 16]
```diff
@@ -0,0 +1,92 @@
...
+ */
+public final class TeleportToColony
+{
+    private static final String CANT_FIND_COLONY = "No Colony found for teleport, please define one.";
+    private static final String CANT_FIND_PLAYER = "No player found for teleport, please define one.";
+
+    /**
+     * Private constructor to hide the implicit public one.
+     */
+    private TeleportToColony(@NotNull final String... parents)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/util/TeleportToColony.java]: MAJOR Remove this unused private "TeleportToColony" constructor. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

File: src/main/java/com/minecolonies/coremod/util/TeleportToColony.java [hunk 17]
```diff
@@ -0,0 +1,92 @@
...
+    {
+
+    }
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/util/TeleportToColony.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 4 issues
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractSingleCommand.java#L116](https://github.com/Minecolonies/minecolonies/blob/d299517ab51e3d55ba523dc239e65441220f32b9/src/main/java/com/minecolonies/coremod/commands/AbstractSingleCommand.java#L116): The Cyclomatic Complexity of this method "canCommandSenderUseCommand" is 14 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/commands/ColonyTeleportCommand.java (hunk 7 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/commands/ColonyTeleportCommand.java]: @opmis can we switch this around here, the if and else?

File: src/main/java/com/minecolonies/coremod/util/TeleportToColony.java (hunk 17 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/util/TeleportToColony.java]: Period missing here

File: src/main/java/com/minecolonies/coremod/util/TeleportToColony.java (hunk 16 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/util/TeleportToColony.java]: You can make this here public

Comment (opmis) [reply src/main/java/com/minecolonies/coremod/util/TeleportToColony.java]: ok I will make this public but if you tell me to change it back to private as you did before I will punch you.... Just sayin

Comment (opmis) [reply src/main/java/com/minecolonies/coremod/util/TeleportToColony.java]: FIXED

File: src/main/java/com/minecolonies/coremod/commands/ColonyTeleportCommand.java (hunk 7 above)
Comment (opmis) [reply src/main/java/com/minecolonies/coremod/commands/ColonyTeleportCommand.java]: FIXED

File: src/main/java/com/minecolonies/coremod/util/TeleportToColony.java (hunk 17 above)
Comment (opmis) [reply src/main/java/com/minecolonies/coremod/util/TeleportToColony.java]: FIXED

File: src/main/java/com/minecolonies/coremod/util/TeleportToColony.java [hunk 18]
```diff
@@ -0,0 +1,92 @@
...
+ */
+public final class TeleportToColony
+{
+    private static final String CANT_FIND_COLONY = "No Colony found for teleport, please define one.";
+    private static final String CANT_FIND_PLAYER = "No player found for teleport, please define one.";
+
+    /**
+     * Private constructor to hide the implicit public one.
+     */
+    public TeleportToColony(@NotNull final String... parents)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/util/TeleportToColony.java]: MAJOR Hide this public constructor. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1118)
MINOR Document the parameter(s): parents [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 3 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractSingleCommand.java#L116](https://github.com/Minecolonies/minecolonies/blob/6fd9ef02e74ee18a9d68e992d757339ac70427a9/src/main/java/com/minecolonies/coremod/commands/AbstractSingleCommand.java#L116): The Cyclomatic Complexity of this method "canCommandSenderUseCommand" is 14 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/commands/ListColoniesCommand.java [hunk 19]
```diff
@@ -27,6 +27,7 @@
     private static final String COORDINATES_TEXT       = "§2Coordinates: §f";
     private static final String COORDINATES_XYZ        = "§4x=§f%s §4y=§f%s §4z=§f%s";
     private static final String LIST_COMMAND_SUGGESTED = "/mc colonies list ";
+    private static final String TELEPORT_COMMAND       = "/mc colony teleport ";
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/ListColoniesCommand.java]: MAJOR Remove this unused "TELEPORT_COMMAND" private field. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1068)

File: src/main/java/com/minecolonies/coremod/commands/HomeTeleportCommand.java [hunk 20]
```diff
@@ -0,0 +1,79 @@
+package com.minecolonies.coremod.commands;
+
+import com.minecolonies.coremod.configuration.Configurations;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/HomeTeleportCommand.java]: MINOR Remove this unused import 'com.minecolonies.coremod.configuration.Configurations'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/commands/HomeTeleportCommand.java [hunk 21]
```diff
@@ -0,0 +1,79 @@
...
+import com.minecolonies.coremod.util.TeleportToColony;
+import net.minecraft.command.CommandException;
+import net.minecraft.command.ICommandSender;
+import net.minecraft.entity.player.EntityPlayer;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/HomeTeleportCommand.java]: MINOR Remove this unused import 'net.minecraft.entity.player.EntityPlayer'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 4 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 2 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractSingleCommand.java#L116](https://github.com/Minecolonies/minecolonies/blob/210502d6ee7a0bc4e5d173b477917dc7cd2f74ff/src/main/java/com/minecolonies/coremod/commands/AbstractSingleCommand.java#L116): The Cyclomatic Complexity of this method "canCommandSenderUseCommand" is 14 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/commands/ColonyTeleportCommand.java [hunk 22]
```diff
@@ -0,0 +1,88 @@
+package com.minecolonies.coremod.commands;
+
+import com.minecolonies.coremod.colony.Colony;
+import com.minecolonies.coremod.colony.ColonyManager;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/ColonyTeleportCommand.java]: MINOR Remove this unused import 'com.minecolonies.coremod.colony.ColonyManager'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/commands/HomeTeleportCommand.java [hunk 23]
```diff
@@ -0,0 +1,77 @@
+package com.minecolonies.coremod.commands;
+
+import com.minecolonies.coremod.util.TeleportToColony;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/HomeTeleportCommand.java]: MINOR Remove this unused import 'com.minecolonies.coremod.configuration.Configurations'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/commands/HomeTeleportCommand.java [hunk 24]
```diff
@@ -0,0 +1,77 @@
...
+import net.minecraft.command.CommandException;
+import net.minecraft.command.ICommandSender;
+import net.minecraft.server.MinecraftServer;
+import net.minecraft.util.math.BlockPos;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/HomeTeleportCommand.java]: MINOR Remove this unused import 'net.minecraft.entity.player.EntityPlayer'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 4 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 3 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractSingleCommand.java#L116](https://github.com/Minecolonies/minecolonies/blob/394d2a2b68dab6b765c8668a8493abc6458371a0/src/main/java/com/minecolonies/coremod/commands/AbstractSingleCommand.java#L116): The Cyclomatic Complexity of this method "canCommandSenderUseCommand" is 14 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 2 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractSingleCommand.java#L116](https://github.com/Minecolonies/minecolonies/blob/394d2a2b68dab6b765c8668a8493abc6458371a0/src/main/java/com/minecolonies/coremod/commands/AbstractSingleCommand.java#L116): The Cyclomatic Complexity of this method "canCommandSenderUseCommand" is 14 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

**Comment by marvin-bitterlich** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/695/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

File: src/main/java/com/minecolonies/coremod/commands/ColonyTeleportCommand.java [hunk 25]
```diff
@@ -0,0 +1,87 @@
+package com.minecolonies.coremod.commands;
+
+import com.minecolonies.coremod.colony.Colony;
+import com.minecolonies.coremod.colony.permissions.Permissions;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/ColonyTeleportCommand.java]: MINOR Remove this unused import 'com.minecolonies.coremod.colony.ColonyManager'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 2 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractSingleCommand.java#L116](https://github.com/Minecolonies/minecolonies/blob/d1f6210fd72672cc2b42f9d420a77356eddf90bd/src/main/java/com/minecolonies/coremod/commands/AbstractSingleCommand.java#L116): The Cyclomatic Complexity of this method "canCommandSenderUseCommand" is 14 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractSingleCommand.java#L116](https://github.com/Minecolonies/minecolonies/blob/d1f6210fd72672cc2b42f9d420a77356eddf90bd/src/main/java/com/minecolonies/coremod/commands/AbstractSingleCommand.java#L116): The Cyclomatic Complexity of this method "canCommandSenderUseCommand" is 14 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
