### PR TITLE
Fix/barbarian spawns

### LINKED ISSUE #1350: Barbarians don't spawn.
### Minecolonies version

minecolonies-universal-1.10.2-0.8.3321

### Expected behavior

- Barbarians should spawn after the message "Get ready cowboy. Barbarians are going to raid you tonight (or something like that)."

### Actual behaviour

- Barbarians don't actually spawn after the message even though I waited the whole night, 2 nights in a row.

### Steps to reproduce the problem

1. Well
2. You
3. Know
4. How
5. Just wait for the night I guess.

### LINKED ISSUE #1445: Massive horde of barbarians when config set to size 10 max.
### Minecolonies version

1.10.2-0.8.3880

### Expected behavior

Barbarian horde to be easy to kill and number 10  or less.

### Actual behaviour

Massive and strong barbarian horde, say 60? 50?  No chance of killing them all. I had config set to:
Days between: 7
Attack difficulty: 2
Max horde size: 10

### Steps to reproduce the problem

1. Change config, play game.

### LINKED ISSUE #1478: The waypoint block is not being scanned into the .nbt file
### Minecolonies version

version 1.10.2-0.8.4038

### Expected behavior

- When you scan a structure or path that has waypoint, the waypoint is included in the resulting .nbt file.

### Actual behaviour

- Created several paths and scanned them in. None of them have the waypoint block included in the .nbt file.

### Steps to reproduce the problem

1. Place a Waypoint block on the ground.
2. Scan the ground and the waypoint.
3. Have the builder build the resulting .nbt file.
4. Using the builders wand, select Waypoints.

When you do, you do not see the waypoint marker floating in the desired location.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #1350 
Closes #1445
Closes #1478

# Changes proposed in this pull request:
- Reworks the Ctape placement and calculate the house borders on creation only once.
- Rework barbarian spawns to spawn them in loaded chunks
- Rework barbarians spawn to decrease the amount to a reasonable
- Rework xp gain on high level to be slower.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 1]
```diff
@@ -133,7 +147,6 @@
         addMapping("WareHouse", BuildingWareHouse.class, BuildingWareHouse.View.class, BlockHutWareHouse.class);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: MAJOR Remove this reference to "BuildingWareHouse". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
MAJOR Remove this reference to "BuildingWareHouse". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 2]
```diff
@@ -133,7 +147,6 @@
...
         addMapping("Barracks", BuildingBarracks.class, BuildingBarracks.View.class, BlockHutBarracks.class);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: MAJOR Remove this reference to "BuildingBarracks". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
MAJOR Remove this reference to "BuildingBarracks". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 3]
```diff
@@ -133,7 +147,6 @@
...
         addMapping("BarracksTower", BuildingBarracksTower.class, BuildingBarracksTower.View.class, BlockHutBarracksTower.class);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: MAJOR Remove this reference to "BuildingBarracksTower". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
MAJOR Remove this reference to "BuildingBarracksTower". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 4]
```diff
@@ -795,7 +858,10 @@ public void setStyle(final String style)
      */
     public void onUpgradeComplete(final int newLevel)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: MAJOR Remove this unused method parameter "newLevel". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)

File: src/main/java/com/minecolonies/coremod/entity/ai/mobs/util/MobEventsUtils.java [hunk 5]
```diff
@@ -94,9 +96,9 @@ private static void numberOfSpawns(final Colony colony)
 
         final int raidLevel = getColonyRaidLevel(colony);
 
-        numberOfBarbarians = (int) (BARBARIANS_MULTIPLIER * raidLevel);
-        numberOfArchers = (int) (ARCHER_BARBARIANS_MULTIPLIER * raidLevel);
-        numberOfChiefs = (int) (CHIEF_BARBARIANS_MULTIPLIER * raidLevel);
+        numberOfBarbarians = (int) (BARBARIANS_MULTIPLIER * raidLevel/3);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/mobs/util/MobEventsUtils.java]: MAJOR Assign this magic number 3 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/ai/mobs/util/MobEventsUtils.java [hunk 6]
```diff
@@ -94,9 +96,9 @@ private static void numberOfSpawns(final Colony colony)
...
+        numberOfArchers = (int) (ARCHER_BARBARIANS_MULTIPLIER * raidLevel/3);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/mobs/util/MobEventsUtils.java]: MAJOR Assign this magic number 3 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/ai/mobs/util/MobEventsUtils.java [hunk 7]
```diff
@@ -94,9 +96,9 @@ private static void numberOfSpawns(final Colony colony)
...
+        numberOfChiefs = (int) (CHIEF_BARBARIANS_MULTIPLIER * raidLevel/3);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/mobs/util/MobEventsUtils.java]: MAJOR Assign this magic number 3 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/util/ColonyUtils.java [hunk 8]
```diff
@@ -44,4 +48,28 @@ public static boolean hasNewSubscribers(@NotNull final Set<EntityPlayerMP> oldSu
...
+    /**
+     * Calculated the corner of a building.
+     * @param pos the central position.
+     * @param world the world.
+     * @param structureName the name of the structure (resource location).
+     * @param rotation the rotation.
+     * @param isMirrored if its mirrored.
+     * @return a tuple with the required corners.
+     */
+    public static Tuple<Tuple<Integer, Integer>, Tuple<Integer, Integer>> calculateCorners(
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/util/ColonyUtils.java:61]: MAJOR Provide multiple methods instead of using "isMirrored" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 102 issues
* ![MAJOR][MAJOR] 69 major
* ![MINOR][MINOR] 31 minor
* ![INFO][INFO] 2 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/b0cddadfe6be23bb0fe03cb01a0c557ac4c6bb7d/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.369 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L54](https://github.com/Minecolonies/minecolonies/blob/b0cddadfe6be23bb0fe03cb01a0c557ac4c6bb7d/src/main/java/com/minecolonies/coremod/colony/Colony.java#L54): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 48 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L54](https://github.com/Minecolonies/minecolonies/blob/b0cddadfe6be23bb0fe03cb01a0c557ac4c6bb7d/src/main/java/com/minecolonies/coremod/colony/Colony.java#L54): class "Colony" has 92 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L694](https://github.com/Minecolonies/minecolonies/blob/b0cddadfe6be23bb0fe03cb01a0c557ac4c6bb7d/src/main/java/com/minecolonies/coremod/colony/Colony.java#L694): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L887](https://github.com/Minecolonies/minecolonies/blob/b0cddadfe6be23bb0fe03cb01a0c557ac4c6bb7d/src/main/java/com/minecolonies/coremod/colony/Colony.java#L887): Refactor this method to reduce its Cognitive Complexity from 22 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [Colony.java#L1209](https://github.com/Minecolonies/minecolonies/blob/b0cddadfe6be23bb0fe03cb01a0c557ac4c6bb7d/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1209): The Cyclomatic Complexity of this method "onWorldTick" is 17 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [Colony.java#L1364](https://github.com/Minecolonies/minecolonies/blob/b0cddadfe6be23bb0fe03cb01a0c557ac4c6bb7d/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1364): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1366](https://github.com/Minecolonies/minecolonies/blob/b0cddadfe6be23bb0fe03cb01a0c557ac4c6bb7d/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1366): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1368](https://github.com/Minecolonies/minecolonies/blob/b0cddadfe6be23bb0fe03cb01a0c557ac4c6bb7d/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1368): Assign this magic number 128 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1487](https://github.com/Minecolonies/minecolonies/blob/b0cddadfe6be23bb0fe03cb01a0c557ac4c6bb7d/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1487): Assign this magic number 0.5D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 102 issues
* ![MAJOR][MAJOR] 69 major
* ![MINOR][MINOR] 31 minor
* ![INFO][INFO] 2 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/c6d25c59070e7d285a79f8fcf11fbd10d5dab420/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.369 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L54](https://github.com/Minecolonies/minecolonies/blob/c6d25c59070e7d285a79f8fcf11fbd10d5dab420/src/main/java/com/minecolonies/coremod/colony/Colony.java#L54): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 48 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L54](https://github.com/Minecolonies/minecolonies/blob/c6d25c59070e7d285a79f8fcf11fbd10d5dab420/src/main/java/com/minecolonies/coremod/colony/Colony.java#L54): class "Colony" has 92 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L694](https://github.com/Minecolonies/minecolonies/blob/c6d25c59070e7d285a79f8fcf11fbd10d5dab420/src/main/java/com/minecolonies/coremod/colony/Colony.java#L694): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L887](https://github.com/Minecolonies/minecolonies/blob/c6d25c59070e7d285a79f8fcf11fbd10d5dab420/src/main/java/com/minecolonies/coremod/colony/Colony.java#L887): Refactor this method to reduce its Cognitive Complexity from 22 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [Colony.java#L1209](https://github.com/Minecolonies/minecolonies/blob/c6d25c59070e7d285a79f8fcf11fbd10d5dab420/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1209): The Cyclomatic Complexity of this method "onWorldTick" is 17 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [Colony.java#L1364](https://github.com/Minecolonies/minecolonies/blob/c6d25c59070e7d285a79f8fcf11fbd10d5dab420/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1364): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1366](https://github.com/Minecolonies/minecolonies/blob/c6d25c59070e7d285a79f8fcf11fbd10d5dab420/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1366): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1368](https://github.com/Minecolonies/minecolonies/blob/c6d25c59070e7d285a79f8fcf11fbd10d5dab420/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1368): Assign this magic number 128 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1487](https://github.com/Minecolonies/minecolonies/blob/c6d25c59070e7d285a79f8fcf11fbd10d5dab420/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1487): Assign this magic number 0.5D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 102 issues
* ![MAJOR][MAJOR] 69 major
* ![MINOR][MINOR] 31 minor
* ![INFO][INFO] 2 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/db08750e86143a5e303bbd95731433caf2cec2ac/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.365 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L54](https://github.com/Minecolonies/minecolonies/blob/db08750e86143a5e303bbd95731433caf2cec2ac/src/main/java/com/minecolonies/coremod/colony/Colony.java#L54): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 48 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L54](https://github.com/Minecolonies/minecolonies/blob/db08750e86143a5e303bbd95731433caf2cec2ac/src/main/java/com/minecolonies/coremod/colony/Colony.java#L54): class "Colony" has 92 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L694](https://github.com/Minecolonies/minecolonies/blob/db08750e86143a5e303bbd95731433caf2cec2ac/src/main/java/com/minecolonies/coremod/colony/Colony.java#L694): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L887](https://github.com/Minecolonies/minecolonies/blob/db08750e86143a5e303bbd95731433caf2cec2ac/src/main/java/com/minecolonies/coremod/colony/Colony.java#L887): Refactor this method to reduce its Cognitive Complexity from 22 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [Colony.java#L1209](https://github.com/Minecolonies/minecolonies/blob/db08750e86143a5e303bbd95731433caf2cec2ac/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1209): The Cyclomatic Complexity of this method "onWorldTick" is 17 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [Colony.java#L1364](https://github.com/Minecolonies/minecolonies/blob/db08750e86143a5e303bbd95731433caf2cec2ac/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1364): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1366](https://github.com/Minecolonies/minecolonies/blob/db08750e86143a5e303bbd95731433caf2cec2ac/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1366): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1368](https://github.com/Minecolonies/minecolonies/blob/db08750e86143a5e303bbd95731433caf2cec2ac/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1368): Assign this magic number 128 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1487](https://github.com/Minecolonies/minecolonies/blob/db08750e86143a5e303bbd95731433caf2cec2ac/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1487): Assign this magic number 0.5D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 9]
```diff
@@ -855,12 +929,14 @@ public final void markDirty()
     }
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: MAJOR Remove this unused method parameter "block". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 10]
```diff
@@ -113,6 +132,7 @@
      */
     @NotNull
     private static final Map<Integer, Class<?>> classNameHashToViewClassMap = new HashMap<>();
+
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: MAJOR Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
MAJOR Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 11]
```diff
@@ -113,6 +132,7 @@
...
     /*
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: MAJOR Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
MAJOR Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 12]
```diff
@@ -113,6 +132,7 @@
...
      * Add all the mappings.
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: MAJOR Remove this reference to "BuildingBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 13]
```diff
@@ -113,6 +132,7 @@
...
      */
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: MAJOR Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
MAJOR Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 14]
```diff
@@ -790,12 +859,17 @@ public void setStyle(final String style)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: MAJOR Remove this unused method parameter "newLevel". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 15]
```diff
@@ -40,7 +42,12 @@
 
 /**
  * Base building class, has all the foundation for what a building stores and does.
+ *
+ * We suppress the warning which warns you about referencing child classes in the parent because that's how we register the instances of the childClasses
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: MAJOR Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 36 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
MAJOR class "AbstractBuilding" has 64 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)

File: src/main/java/com/minecolonies/coremod/entity/ai/mobs/util/MobEventsUtils.java [hunk 16]
```diff
@@ -94,9 +101,9 @@ private static void numberOfSpawns(final Colony colony)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/mobs/util/MobEventsUtils.java]: MAJOR Assign this magic number 3 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 119 issues
* ![MAJOR][MAJOR] 77 major
* ![MINOR][MINOR] 31 minor
* ![INFO][INFO] 11 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [BlockMinecoloniesRack.java#L132](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java#L132): Reduce the number of returns of this method 7, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [BlockMinecoloniesRack.java#L132](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java#L132): Add the missing @Deprecated annotation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMissingDeprecatedCheck)
1. ![MAJOR][MAJOR] [BlockMinecoloniesRack.java#L204](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java#L204): Add the missing @Deprecated annotation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMissingDeprecatedCheck)
1. ![MAJOR][MAJOR] [BlockMinecoloniesRack.java#L389](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java#L389): Reduce this class from 51 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.365 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L54](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/colony/Colony.java#L54): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 48 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L54](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/colony/Colony.java#L54): class "Colony" has 92 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L694](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/colony/Colony.java#L694): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L887](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/colony/Colony.java#L887): Refactor this method to reduce its Cognitive Complexity from 22 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [Colony.java#L1209](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1209): The Cyclomatic Complexity of this method "onWorldTick" is 17 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 17]
```diff
@@ -40,7 +42,12 @@
...
+ * to their views and blocks.
+ *
  */
+@SuppressWarnings("squid:S2390")
 public abstract class AbstractBuilding
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java:51]: MAJOR Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 36 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
MAJOR class "AbstractBuilding" has 64 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 85 issues
* ![MAJOR][MAJOR] 43 major
* ![MINOR][MINOR] 31 minor
* ![INFO][INFO] 11 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [BlockMinecoloniesRack.java#L132](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java#L132): Reduce the number of returns of this method 7, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [BlockMinecoloniesRack.java#L132](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java#L132): Add the missing @Deprecated annotation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMissingDeprecatedCheck)
1. ![MAJOR][MAJOR] [BlockMinecoloniesRack.java#L204](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java#L204): Add the missing @Deprecated annotation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMissingDeprecatedCheck)
1. ![MAJOR][MAJOR] [BlockMinecoloniesRack.java#L389](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java#L389): Reduce this class from 51 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.365 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L54](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/colony/Colony.java#L54): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 48 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L54](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/colony/Colony.java#L54): class "Colony" has 92 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L694](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/colony/Colony.java#L694): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L887](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/colony/Colony.java#L887): Refactor this method to reduce its Cognitive Complexity from 22 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [Colony.java#L1209](https://github.com/Minecolonies/minecolonies/blob/89128e56276f57c5d89ccc3cf53e2d0f8eab94b6/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1209): The Cyclomatic Complexity of this method "onWorldTick" is 17 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 94 issues
* ![MAJOR][MAJOR] 44 major
* ![MINOR][MINOR] 39 minor
* ![INFO][INFO] 11 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [BlockMinecoloniesRack.java#L132](https://github.com/Minecolonies/minecolonies/blob/6cb5b24bebdd9c7d4b23d7033d46f13756ffedbc/src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java#L132): Reduce the number of returns of this method 7, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [BlockMinecoloniesRack.java#L132](https://github.com/Minecolonies/minecolonies/blob/6cb5b24bebdd9c7d4b23d7033d46f13756ffedbc/src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java#L132): Add the missing @Deprecated annotation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMissingDeprecatedCheck)
1. ![MAJOR][MAJOR] [BlockMinecoloniesRack.java#L204](https://github.com/Minecolonies/minecolonies/blob/6cb5b24bebdd9c7d4b23d7033d46f13756ffedbc/src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java#L204): Add the missing @Deprecated annotation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMissingDeprecatedCheck)
1. ![MAJOR][MAJOR] [BlockMinecoloniesRack.java#L389](https://github.com/Minecolonies/minecolonies/blob/6cb5b24bebdd9c7d4b23d7033d46f13756ffedbc/src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java#L389): Reduce this class from 51 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/6cb5b24bebdd9c7d4b23d7033d46f13756ffedbc/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.367 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L54](https://github.com/Minecolonies/minecolonies/blob/6cb5b24bebdd9c7d4b23d7033d46f13756ffedbc/src/main/java/com/minecolonies/coremod/colony/Colony.java#L54): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 48 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L54](https://github.com/Minecolonies/minecolonies/blob/6cb5b24bebdd9c7d4b23d7033d46f13756ffedbc/src/main/java/com/minecolonies/coremod/colony/Colony.java#L54): class "Colony" has 92 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L699](https://github.com/Minecolonies/minecolonies/blob/6cb5b24bebdd9c7d4b23d7033d46f13756ffedbc/src/main/java/com/minecolonies/coremod/colony/Colony.java#L699): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L892](https://github.com/Minecolonies/minecolonies/blob/6cb5b24bebdd9c7d4b23d7033d46f13756ffedbc/src/main/java/com/minecolonies/coremod/colony/Colony.java#L892): Refactor this method to reduce its Cognitive Complexity from 22 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [Colony.java#L1214](https://github.com/Minecolonies/minecolonies/blob/6cb5b24bebdd9c7d4b23d7033d46f13756ffedbc/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1214): The Cyclomatic Complexity of this method "onWorldTick" is 17 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Review by marchermans — APPROVED** [review]
