### PR TITLE
Food related fixe

### LINKED ISSUE #9944: cook incessantly cooking mushrooms and unable to turn off as food
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1..1.1.567-beta-jar

### Structurize Version

1.20.1.1.0.731

### Related Mods and their Versions

vanilla plus cookbook 2.2.2
I am on cavecolonies server using the cavecolonies modpack 

### Current Behavior

the cook is cooking all the mushrooms, wasting fuel and preventing using mushrooms in recipes,  this has been going on since the restaurant was level 1 - that the cooked mushrooms are not on the list of foods to disable,  the restaurant is currently level 4 and most citizens will not eat cooked mushrooms which only satisfy one shank of hunger, so he's wasting fuel and tying up couriers delivering then sending it back to the warehouse after a while 

  While discussing this on discord  and getting screen shots he cooked up 22 mushrooms 
   I have noticed in the past also that several ingredients in pams recipes randomly seem to not be on the list of things you can disable,  that is pams roasted mushrooms , roasted garlic,   etc 
    

### Expected Behavior

I would expect the cook to have left the mushrooms alone because the assitant cook needed them for rabbit stew
I would expect to be able to turn off cooked mushroom in the food tab  so he would stop cooking them
I would expect a level 4 restaurant not to cook up low quality food but I do have 1 or 2 citizens in a new house that "might" eat it 
I wish I could expect him to only cook what I tell him to cook in the smelting recipes tab but that is not how it's supposed to work

### Reproduction Steps

come over to my restaurant and look 
Or put some mushrooms in your restaurant and see what happens 
set min stock of mushroom stew and see if your assistant cook is fast enough to make it 

### Logs

it's the cavecolonies server 

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #10050: [BUG] <Restaurant cooking disabled food without limit>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

Tropical Colonies 1.8 

### Structurize Version

1.20.1-1.0.742

### Related Mods and their Versions

_No response_

### Current Behavior

7c543ec1-479c-42d6-b6d8-ae4667b0e36f

### Expected Behavior

Once u add a fuel type, the restaurant starts cooking cod, salmon and potatoes despite not being listed anymore. 

### Reproduction Steps

1. select the fuel type 
2.  the cook will start cooking previously mentioned food 

### Logs

https://gist.github.com/SnowySakura1/c36e604a7a3c54cee3ea82bac6b4309b

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #10050
Closes #9944
Closes #

# Changes proposed in this pull request:
- Restaurant is consistent about the food that it doesnt request and doesnt display in the UI
- Add a cookery notice to the interaction if it doesn't exist
- Interaction only show for citizens at > level 2 buildings
- Happiness factor is now 7 days (week)
- Added tooltip to minecol food 
- Only request building level foods

[ x ] Yes I tested this before submitting it.
[ ] I also did a multiplayer test.

Review please

### CODE REVIEW

**Review by Thodor12 — DISMISSED** [review]

File: src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java [hunk 1]
```diff
@@ -261,8 +261,10 @@ public static void init()
           citizen -> !(citizen.getJob() instanceof AbstractJobGuard) && ((ITimeBasedHappinessModifier)citizen.getCitizenHappinessHandler().getModifier(SLEPTTONIGHT)).getDays() <= 0);
 
         InteractionValidatorRegistry.registerStandardPredicate(Component.translatable(NO + HADDECENTFOOD),
-          citizen -> ((ITimeBasedHappinessModifier)citizen.getCitizenHappinessHandler().getModifier(HADDECENTFOOD)).getDays() <= 0);
+          citizen -> ((ITimeBasedHappinessModifier)citizen.getCitizenHappinessHandler().getModifier(HADDECENTFOOD)).getDays() <= 0 && citizen.getHomeBuilding() != null && citizen.getHomeBuilding().getBuildingLevel() > 2 && citizen.getColony().getBuildingManager().getFirstBuildingMatching(b -> b instanceof BuildingKitchen) != null);
```
Comment (someaddons) [inline src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java]: getBuildingType() == ModBuildings.cook.get()
Instead of instanceof

File: src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java [hunk 2]
```diff
@@ -261,8 +261,10 @@ public static void init()
...
 
+        InteractionValidatorRegistry.registerStandardPredicate(Component.translatable(NO + HADDECENTFOOD + NOKITCHEN),
+          citizen -> ((ITimeBasedHappinessModifier)citizen.getCitizenHappinessHandler().getModifier(HADDECENTFOOD)).getDays() <= 0 && citizen.getHomeBuilding() != null && citizen.getHomeBuilding().getBuildingLevel() > 2 && citizen.getColony().getBuildingManager().getFirstBuildingMatching(b -> b instanceof BuildingKitchen) == null);
```
Comment (someaddons) [inline src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java]: same here

File: src/main/java/com/minecolonies/core/client/gui/modules/FoodItemListModuleWindow.java [hunk 3]
```diff
@@ -37,7 +37,7 @@ public FoodItemListModuleWindow(
       final IItemListModuleView moduleView)
     {
         super(res, building, moduleView);
-        groupedItemList.removeIf(c -> c.getItemStack().is(ModTags.excludedFood) || !FoodUtils.canEat(c.getItemStack(), building.getBuildingLevel()));
+        groupedItemList.removeIf(c -> c.getItemStack().is(ModTags.excludedFood) || !FoodUtils.canEat(c.getItemStack(), building.getBuildingLevel() - 1));
```
Comment (someaddons) [inline src/main/java/com/minecolonies/core/client/gui/modules/FoodItemListModuleWindow.java:40]: maybe put the -1 into the util directly? looks like its used everywhere and would be easy to forget when calling from elsewhere

File: src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java (hunk 1 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java]: fixed

File: src/main/java/com/minecolonies/core/client/gui/modules/FoodItemListModuleWindow.java (hunk 3 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/core/client/gui/modules/FoodItemListModuleWindow.java:40]: The cook serves until buildinglevel-1, the citizens accept until their own buildinglevel

**Review by someaddons — DISMISSED** [review]

File: src/main/java/com/minecolonies/api/util/FoodUtils.java [hunk 4]
```diff
@@ -17,7 +18,12 @@ public class FoodUtils
      */
     public static boolean canEat(final ItemStack stack, final int buildingLevel)
     {
-        return buildingLevel < 3 || stack.getItem().getFoodProperties(stack, null).getNutrition() >= buildingLevel + 1;
+        if (buildingLevel < 3)
+        {
+            return stack.getItem().getFoodProperties(stack, null) != null;
+        }
+        final FoodProperties foodProperties = stack.getItem().getFoodProperties(stack, null);
+        return foodProperties != null && stack.getItem().getFoodProperties(stack, null).getNutrition() >= buildingLevel + 1;
```
Comment (uecasm) [inline src/main/java/com/minecolonies/api/util/FoodUtils.java]: Should use `foodProperties` rather than fetching again.

Comment (Raycoms) [reply src/main/java/com/minecolonies/api/util/FoodUtils.java]: yes

**Review by someaddons — APPROVED** [review]
