### PR TITLE
#4517

### LINKED ISSUE #4517: Citizens never use alternative skins
### Minecolonies version
All of them up to and including building from source

### Expected behavior
Colonists should use all varieties of available skins (i.e. `childfemale1.png`, `childfemale2.png`, etc)

### Actual behaviour
Colonists only use the xxx1.png version of the skin.  For instance, if you have 10 builders they will all use the skins `buildermale1.png` and `builderfemale1.png`, and never `buildermale2.png` or `buildermale3.png`

### Steps to reproduce the problem
1.  Change in config to allow the maximum number of starting colonists.
2.  Create a new world, and place a town hall.
3.  Wait for all the colonists to spawn.
4.  Observe that all the new settlers have the skin `settlermale1.png` and `settlerfemale1.png`
[https://i.imgur.com/Q9yhl9I.png](Result)

### PR DESCRIPTION
**Pull request by mcmanustfj**
Closes #4517 
# Changes proposed in this pull request:
- Assigns a random textureId to a citizen in CitizenData::initForNewCitizen() (same place as name and gender)
- Removes renderMetadata from the creation of the resourcelocation in AbstractEntityCitizen::setTexture()

Review please!

### CODE REVIEW

File: src/api/java/com/minecolonies/api/entity/citizen/AbstractEntityCitizen.java [hunk 1]
```diff
@@ -201,7 +201,7 @@ public void setTexture()
 
         final String textureBase = "textures/entity/" + model.getTextureBase() + (female ? "female" : "male");
         final int moddedTextureId = (textureId % model.getNumTextures()) + 1;
-        texture = new ResourceLocation(Constants.MOD_ID, textureBase + moddedTextureId + renderMetadata + ".png");
+        texture = new ResourceLocation(Constants.MOD_ID, textureBase + moddedTextureId + ".png");
     }
```
Comment (Raycoms) [inline src/api/java/com/minecolonies/api/entity/citizen/AbstractEntityCitizen.java]: We do need the renderMetadata for things like the logs in the lumberjack backpack, etc.

Comment (mcmanustfj) [reply src/api/java/com/minecolonies/api/entity/citizen/AbstractEntityCitizen.java]: Yeah, just saw that and was about to post here. It was auto-populating to 'null' for me for new citizens without any renderMetadata.  If you point me to where it is populated, I can try to make sure it gets defaulted to '' or something.

Comment (Raycoms) [reply src/api/java/com/minecolonies/api/entity/citizen/AbstractEntityCitizen.java]: setRenderMetadata is called by the AI

Comment (mcmanustfj) [reply src/api/java/com/minecolonies/api/entity/citizen/AbstractEntityCitizen.java]: turns out it doesn't actually break anything, reverted

**Comment by Raycoms** [comment]
Looks good :shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/4518/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Review by someaddons — APPROVED** [review]
