### PR TITLE
Happiness

### LINKED ISSUE #4653: Miner outside of colony border
Version: minecolonies-0.11.832-ALPHA-universal

MC 1.15.2

### Expected behavior
Miner not spamming chat box and working

### Actual behaviour
The recent change with building outside of colony border made miner... a bit nasty about it. They spam the chat box until you get bigger colony border/upgrade mine to make them busy/stop their work.

Maybe miner can be an exception to this rule? Unless they stumble to the enemy's border, they should be allowed to mine, aren't they?

### Steps to reproduce the problem
Build a miner near a colony border and wait for them to do branch mining and get stopped by colony border

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #4653

image

Complete happiness rework:

Added four different types of Happiness Modifiers.

Static: Depending statically on a value of the citizen
Time Based: Change factor over time
Expiration based: Invoked for a short time (buff for three days on a colonist death for example)
Client Sided: With the factor only for the client side.

All the lists in the GUI are now automatically generated from the list of modifiers.

Review please

### CODE REVIEW

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/api/java/com/minecolonies/api/entity/citizen/happiness/TimeBasedHappinessModifier.java  4
- src/api/java/com/minecolonies/api/entity/citizen/happiness/ClientHappinessModifier.java  1
- src/api/java/com/minecolonies/api/entity/citizen/happiness/ExpirationBasedHappinessModifier.java  4
- src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenHappinessHandler.java  2
- src/api/java/com/minecolonies/api/entity/citizen/happiness/StaticHappinessModifier.java  1
- src/api/java/com/minecolonies/api/entity/citizen/happiness/AbstractHappinessModifier.java  1
         

Complexity decreasing per file
==============================
+ src/main/java/com/minecolonies/coremod/colony/Colony.java  -1
+ src/main/java/com/minecolonies/coremod/colony/managers/CitizenManager.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5372088&bid=17608746)

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/api/java/com/minecolonies/api/entity/citizen/happiness/TimeBasedHappinessModifier.java  4
- src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenHappinessHandler.java  2
- src/api/java/com/minecolonies/api/entity/citizen/happiness/AbstractHappinessModifier.java  1
- src/api/java/com/minecolonies/api/entity/citizen/happiness/StaticHappinessModifier.java  1
- src/api/java/com/minecolonies/api/entity/citizen/happiness/ClientHappinessModifier.java  1
- src/api/java/com/minecolonies/api/entity/citizen/happiness/ExpirationBasedHappinessModifier.java  4
         

Complexity decreasing per file
==============================
+ src/main/java/com/minecolonies/coremod/colony/Colony.java  -1
+ src/main/java/com/minecolonies/coremod/colony/managers/CitizenManager.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5372088&bid=17608746)

**Comment by marvin-bitterlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/api/java/com/minecolonies/api/entity/citizen/happiness/TimeBasedHappinessModifier.java  4
- src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenHappinessHandler.java  2
- src/api/java/com/minecolonies/api/entity/citizen/happiness/ExpirationBasedHappinessModifier.java  4
- src/api/java/com/minecolonies/api/entity/citizen/happiness/ClientHappinessModifier.java  1
- src/main/java/com/minecolonies/coremod/colony/workorders/WorkManager.java  1
- src/api/java/com/minecolonies/api/entity/citizen/happiness/AbstractHappinessModifier.java  1
- src/api/java/com/minecolonies/api/entity/citizen/happiness/StaticHappinessModifier.java  1
         

Complexity decreasing per file
==============================
+ src/main/java/com/minecolonies/coremod/colony/managers/CitizenManager.java  -2
+ src/main/java/com/minecolonies/coremod/colony/Colony.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5372088&bid=17608746)

File: src/api/java/com/minecolonies/api/entity/citizen/happiness/ExpirationBasedHappinessModifier.java [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+        {
+            if (days > 0)
+            {
+                return 1;
+            }
+            return super.getFactor();
+        }
+        else
+        {
+            if (days > 0)
```
Comment (marvin-bitterlich) [inline src/api/java/com/minecolonies/api/entity/citizen/happiness/ExpirationBasedHappinessModifier.java:69]: you could flip this comparison, as that makes it way easier to read

File: src/api/java/com/minecolonies/api/entity/citizen/happiness/ExpirationBasedHappinessModifier.java [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+        this.period = period;
+    }
+
+    /**
+     * Create an instance of the happiness modifier.
+     *
+     * @param id     its string id.
+     * @param weight its weight.
+     * @param period the period.
+     * @param inverted if inverted.
```
Comment (marvin-bitterlich) [inline src/api/java/com/minecolonies/api/entity/citizen/happiness/ExpirationBasedHappinessModifier.java:48]: Can you crite some documentation on what inverted means? I can roughly understand it from the code, but the use case is unclear and should be documented, so that people using this method know what they are changing with this

File: src/api/java/com/minecolonies/api/entity/citizen/happiness/TimeBasedHappinessModifier.java [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+    /**
+     * The number of passed days.
+     */
+    private int days = 0;
+
+    /**
+     * Create an instance of the happiness modifier.
+     *
+     * @param id     its string id.
+     * @param weight its weight.
```
Comment (marvin-bitterlich) [inline src/api/java/com/minecolonies/api/entity/citizen/happiness/TimeBasedHappinessModifier.java:29]: missing javadoc, as supplier and timebasedfactor are both undocumented and actually important parts for understanding this

**Review by marvin-bitterlich — CHANGES_REQUESTED** [review]
I saw you merged this just now :D
