### PR TITLE
Fix herder item stack request corruption

### LINKED ISSUE #10884: Cowhand requesting a lot of air.
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.894

### Structurize Version

1.20.1-1.0.772

### Related Mods and their Versions

_No response_

### Current Behavior

I have my cowhand requesting air. They should not.

Image
Their current minimum stock.

Image

Deleting the air just makes it recreate itself, and they aren't requesting things or doing much.

### Expected Behavior

They should not ask for air.

### Reproduction Steps

I don't know what caused this or how to reproduce it, alas.

### Logs

https://gist.github.com/Nuku/24f16573db3d46dcdb3bfaee40183912

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by rivon0507**
Closes #10884 

# Changes proposed in this pull request

- Prevent item stack corruption in herder AI by requesting single-item stacks alongside the count parameter instead of an oversized stack that get corrupted during network transmission. (Inspired by the postbox)

- Use placeholder values in error logging for deserialization issues.

## Testing
- [x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/core/entity/ai/workers/production/herders/AbstractEntityAIHerder.java [hunk 1]
```diff
@@ -314,7 +314,7 @@ private IAIState prepareForHerding()
 
         for (final ItemStack item : getExtraItemsNeeded())
         {
-            checkIfRequestForItemExistOrCreateAsync(item);
+            checkIfRequestForItemExistOrCreateAsync(item.copyWithCount(1), item.getCount(), item.getCount());
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/core/entity/ai/workers/production/herders/AbstractEntityAIHerder.java]: Ohhh, that's why it's running into the problem. I think we should probably
a) Inside the request creation do this, and log if the itemstack does exceed the 64 with stacktrace where this was created.
b) Make getExtraItemsNeeded an actual ItemStorage(ItemStack, qty). To avoid creating bad stacks to begin with here.

Comment (rivon0507) [reply src/main/java/com/minecolonies/core/entity/ai/workers/production/herders/AbstractEntityAIHerder.java]: Does the item count in the `ItemStack` matter in a request, in the request system? If not (which is probably the case) the constructor of `com.minecolonies.api.colony.requestsystem.requestable.Stack` can be altered so that the `ItemStack` will always have a count of `1`, since that data is already available in `Stack.getCount()`.

And I'll make getExtraItemsNeeded return ItemStorage now.

Comment (Raycoms) [reply src/main/java/com/minecolonies/core/entity/ai/workers/production/herders/AbstractEntityAIHerder.java]: I'm not 100% sure if it matters. But overall we should never make too large stacks and log if we accidentially do from somewhere.

Comment (rivon0507) [reply src/main/java/com/minecolonies/core/entity/ai/workers/production/herders/AbstractEntityAIHerder.java]: In `com.minecolonies.api.colony.requestsystem.requestable.Stack`, after looking up usages of `theStack` and ensuring no logic depends on `ItemStack.getCount()`, `theStack`'s count is set to `1` in the constructor of `Stack`. That way, we'll never have too large `ItemStack`s in requests.

And `getExtraItemsNeeded()` now returns an `ItemStorage`.

**Review by Raycoms — APPROVED** [review]

**Review by someaddons — APPROVED** [review]
