### PR TITLE
Xp changes

### LINKED ISSUE #1319: Support Mending enchantment
### Minecolonies version

- Version 0.8.3167, MC 1.12, Forge 14.21.1.2424

### Expected behavior

- Fisherman's rod doesn't break due to the XP collected during fishing

### Actual behaviour

- The rod deteriorates at the normal rate, as if Mending wasn't applied

### Steps to reproduce the problem

1. Get a fishing rod with the mending enchantment
2. Give to fisherman and watch him fish
3. Observe that the durability does not go back up after reeling in a fish and collecting experience

### PR DESCRIPTION
**Pull request by ghost**
Closes #1319 

# Changes proposed in this pull request:
- Builders gain xp for placing blocks.
- Builders build faster based on their level. (lv0 = default, lv 50 = 6x faster).
- Equipped/Held items with mending enchant repair with xp.
- Small bugfix where max cit level is too high. (9 when it should be 8 for lv 2 hut)

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/client/gui/WindowHomeBuilding.java [hunk 1]
```diff
@@ -1,24 +1,146 @@
...
+
+        refreshView();
+    }
+
+    /**
+     * Action when an assign button is clicked.
+     *
+     * @param button the clicked button.
+     */
+    private void assignClicked(@NotNull final Button button)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowHomeBuilding.java]: MAJOR Remove this unused method parameter "button". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 2]
```diff
@@ -869,18 +848,22 @@ public final void markDirty()
      * register a block and position.
      *
      * @param block to be registered
-     * @param pos of the block
+     * @param pos   of the block
+     * @param world the world to place the tileentity in
      */
-    public void registerBlockPosition(@NotNull Block block, @NotNull final BlockPos pos)
+    public void registerBlockPosition(@NotNull Block block, @NotNull final BlockPos pos, @NotNull final World world)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: MAJOR Remove this unused method parameter "block". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)

File: src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java [hunk 3]
```diff
@@ -653,6 +659,25 @@ else if (saturation > AVERAGE_SATURATION)
...
+     * @param xp amount of xp available to mend with
+     * @return xp left after mending
+     */
+    private double applyMending(double xp) {
+        ItemStack tool = EnchantmentHelper.getEnchantedItem(Enchantments.MENDING, this);
+
+        if (tool != null && tool.isItemDamaged()) {
+            //2 xp to heal 1 dmg
+            double dmgHealed = Math.min(xp / 2, tool.getItemDamage());
+            xp -= dmgHealed * 2;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java]: MINOR Introduce a new variable instead of reusing the parameter "xp". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1226)

File: src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java [hunk 4]
```diff
@@ -1750,42 +1774,44 @@ private void hitBlockWithToolInHand(@Nullable final BlockPos blockPos, final boo
...
-            worldObj.setBlockToAir(blockPos);
+                    block.getSoundType(blockState, CompatibilityUtils.getWorld(this), blockPos, this).getVolume(),
+                    block.getSoundType(blockState, CompatibilityUtils.getWorld(this), blockPos, this).getPitch());
+            CompatibilityUtils.getWorld(this).setBlockToAir(blockPos);
 
             damageItemInHand(1);
         }
         else
         {
             //todo: might remove this
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java]: INFO Complete the task associated to this TODO comment. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java [hunk 5]
```diff
@@ -653,6 +659,25 @@ else if (saturation > AVERAGE_SATURATION)
         }
     }
 
+    /**
+     * repair random equipped/held item with mending enchant.
+     *
+     * @param xp amount of xp available to mend with
+     * @return xp left after mending
+     */
+    private double applyMending(double xp) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

File: src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java [hunk 6]
```diff
@@ -1750,42 +1774,44 @@ private void hitBlockWithToolInHand(@Nullable final BlockPos blockPos, final boo
...
             damageItemInHand(1);
         }
         else
         {
             //todo: might remove this
-            if (!worldObj.isRemote)
+            if (!CompatibilityUtils.getWorld(this).isRemote)
             {
                 MineColonies.getNetwork().sendToAllAround(
                         //todo: correct side
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java]: INFO Complete the task associated to this TODO comment. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java [hunk 7]
```diff
@@ -1676,18 +1700,18 @@ private void tryPickupEntityItem(@NotNull final EntityItem entityItem)
...
-            if (InventoryUtils.isItemStackEmpty(resultStack) || InventoryUtils.compareItemStacksIgnoreStackSize(itemStack, resultStack))
+            final int resultingStackSize = ItemStackUtils.getSize(resultStack);
+            if (ItemStackUtils.isEmpty(resultStack) || ItemStackUtils.compareItemStacksIgnoreStackSize(itemStack, resultStack))
             {
-                this.worldObj.playSound((EntityPlayer) null,
+                CompatibilityUtils.getWorld(this).playSound((EntityPlayer) null,
                         this.getPosition(),
                         SoundEvents.ENTITY_ITEM_PICKUP,
                         SoundCategory.AMBIENT,
                         0.2F,
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java]: MAJOR Assign this magic number 0.2F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java [hunk 8]
```diff
@@ -1676,18 +1700,18 @@ private void tryPickupEntityItem(@NotNull final EntityItem entityItem)
...
                         (float) ((this.rand.nextGaussian() * 0.7D + 1.0D) * 2.0D));
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java]: MAJOR Assign this magic number 0.7D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java [hunk 9]
```diff
@@ -653,6 +659,25 @@ else if (saturation > AVERAGE_SATURATION)
...
+    /**
+     * repair random equipped/held item with mending enchant.
+     *
+     * @param xp amount of xp available to mend with
+     * @return xp left after mending
+     */
+    private double applyMending(double xp) {
+        ItemStack tool = EnchantmentHelper.getEnchantedItem(Enchantments.MENDING, this);
+
+        if (tool != null && tool.isItemDamaged()) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

File: src/main/java/com/minecolonies/coremod/colony/buildings/BuildingLumberjack.java [hunk 10]
```diff
@@ -1,50 +1,74 @@
...
-import java.util.HashMap;
-import java.util.Map;
+import java.util.*;
+
+import static com.minecolonies.api.util.constant.ToolLevelConstants.TOOL_LEVEL_WOOD_OR_GOLD;
 
 /**
  * The lumberjacks building.
  */
 public class BuildingLumberjack extends AbstractBuildingWorker
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/BuildingLumberjack.java]: MINOR Override the "equals" method in this class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2160)

File: src/main/java/com/minecolonies/coremod/colony/buildings/BuildingLumberjack.java [hunk 11]
```diff
@@ -157,8 +248,12 @@ public AbstractJob createJob(final CitizenData citizen)
     public static class View extends AbstractBuildingWorker.View
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/BuildingLumberjack.java]: MAJOR Reduce this class from 70 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java [hunk 12]
```diff
@@ -800,7 +890,7 @@ public void updateElement(final int index, @NotNull final Pane rowPane)
                 }
 
                 rowPane.findPaneOfTypeByID("name", Label.class).setLabelText(name);
-                final boolean isTriggered = townHall.getColony().getPermissions().hasPermission(Permissions.Rank.valueOf(actionsList.getParent().getID().toUpperCase()), action);
+                final boolean isTriggered = townHall.getColony().getPermissions().hasPermission(Rank.valueOf(actionsList.getParent().getID().toUpperCase()), action);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java]: MINOR Define the locale to be used in this String operation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1449)

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java [hunk 13]
```diff
@@ -13,12 +14,19 @@
 import org.jetbrains.annotations.NotNull;
 import org.jetbrains.annotations.Nullable;
 
+import static com.minecolonies.api.util.constant.ToolLevelConstants.*;
+
 /**
  * The abstract class for each worker building.
  */
 public abstract class AbstractBuildingWorker extends AbstractBuildingHut
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java]: MINOR Override the "equals" method in this class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2160)

File: src/main/java/com/minecolonies/coremod/colony/buildings/BuildingHome.java [hunk 14]
```diff
@@ -237,6 +249,15 @@ public boolean hasResident(final CitizenData citizen)
...
+     */
+    public void checkIfFoodNeeded()
+    {
+        setFoodNeeded(residents.stream().filter(resident -> resident.getSaturation() < EntityCitizen.HIGH_SATURATION).findFirst().isPresent());
+    }
+
+    /**
      * The view of the citizen hut.
      */
     public static class View extends AbstractBuildingHut.View
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/BuildingHome.java]: MAJOR Reduce this class from 38 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/miner/EntityAIStructureMiner.java [hunk 15]
```diff
@@ -103,7 +103,7 @@ public IBlockState getSolidSubstitution(BlockPos ignored)
     private static boolean isOre(final Block block)
     {
         //TODO make this more sophisticated
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/miner/EntityAIStructureMiner.java]: INFO Complete the task associated to this TODO comment. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java [hunk 16]
```diff
@@ -504,56 +493,70 @@ else if (itemsToDeliver.isEmpty())
      * Gathers only one stack of the item.
      *
      * @param buildingToDeliver building to deliver to.
-     * @return true if continue, false if not succuesful
      */
-    private boolean gatherItems(@NotNull final AbstractBuilding buildingToDeliver, @NotNull final BlockPos position)
+    private AIState gatherItems(@NotNull final AbstractBuilding buildingToDeliver, @NotNull final BlockPos position)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java]: MAJOR Reduce the number of returns of this method 7, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)

File: src/main/java/com/minecolonies/blockout/controls/TextField.java [hunk 17]
```diff
@@ -315,10 +317,10 @@ public void onFocus()
         cursorBlinkCounter = 0;
     }
 
-    @Override
     /**
      * Draw itself at positions mx and my.
      */
+    @Override
     protected void drawSelf(final int mx, final int my)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blockout/controls/TextField.java]: MAJOR The Cyclomatic Complexity of this method "drawSelf" is 21 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
MAJOR Refactor this method to reduce its Cognitive Complexity from 24 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIMeleeGuard.java [hunk 18]
```diff
@@ -108,11 +109,11 @@ public EntityAIMeleeGuard(@NotNull final JobGuard job)
     @Override
     protected AIState searchTarget()
     {
-        if (checkForWeapon())
+        if (checkForToolOrWeapon(ToolType.SWORD))
         {
             return AIState.GUARD_SEARCH_TARGET;
         }
-        InventoryFunctions.matchFirstInProvider(worker, stack -> stack != null && Utils.doesItemServeAsWeapon(stack), worker::setHeldItem);
+        InventoryFunctions.matchFirstInProviderWithSimpleAction(worker, stack -> !ItemStackUtils.isEmpty(stack) && ItemStackUtils.doesItemServeAsWeapon(stack), worker::setHeldItem);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIMeleeGuard.java]: MAJOR Split this 181 characters long line (which is greater than 180 authorized). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00103)

File: src/main/java/com/minecolonies/coremod/colony/ColonyView.java [hunk 19]
```diff
@@ -75,6 +85,11 @@
     private double overallHappiness = 5;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/ColonyView.java]: MAJOR Assign this magic number 5 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/commands/colonycommands/ChangeColonyOwnerCommand.java [hunk 20]
```diff
@@ -50,30 +50,47 @@ public String getCommandUsage(@NotNull final ICommandSender sender)
     @Override
     public void execute(@NotNull final MinecraftServer server, @NotNull final ICommandSender sender, @NotNull final String... args) throws CommandException
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/colonycommands/ChangeColonyOwnerCommand.java]: MAJOR Reduce the number of returns of this method 9, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java [hunk 21]
```diff
@@ -1,21 +1,26 @@
...
 import com.minecolonies.coremod.colony.jobs.JobBuilder;
-import com.minecolonies.coremod.colony.workorders.WorkOrderBuildDecoration;
 import com.minecolonies.coremod.colony.workorders.WorkOrderBuild;
-import com.minecolonies.coremod.configuration.Configurations;
+import com.minecolonies.coremod.colony.workorders.WorkOrderBuildDecoration;
 import com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure;
 import com.minecolonies.coremod.entity.ai.util.AIState;
 import com.minecolonies.coremod.entity.ai.util.AITarget;
-import com.minecolonies.coremod.util.*;
+import com.minecolonies.coremod.tileentities.TileEntityRack;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java]: MINOR Remove this unused import 'com.minecolonies.coremod.tileentities.TileEntityRack'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java [hunk 22]
```diff
@@ -27,6 +32,7 @@
 import net.minecraft.item.ItemStack;
 import net.minecraft.nbt.NBTTagCompound;
 import net.minecraft.tileentity.TileEntity;
+import net.minecraft.tileentity.TileEntityChest;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java]: MINOR Remove this unused import 'net.minecraft.tileentity.TileEntityChest'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java [hunk 23]
```diff
@@ -1,21 +1,26 @@
 package com.minecolonies.coremod.entity.ai.citizen.builder;
 
+import com.minecolonies.api.configuration.Configurations;
+import com.minecolonies.api.util.*;
 import com.minecolonies.coremod.blocks.AbstractBlockHut;
 import com.minecolonies.coremod.blocks.BlockSolidSubstitution;
+import com.minecolonies.coremod.blocks.ModBlocks;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java]: MINOR Remove this unused import 'com.minecolonies.coremod.blocks.ModBlocks'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java [hunk 24]
```diff
@@ -1,21 +1,26 @@
...
+import com.minecolonies.coremod.colony.workorders.WorkOrderBuildDecoration;
 import com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure;
 import com.minecolonies.coremod.entity.ai.util.AIState;
 import com.minecolonies.coremod.entity.ai.util.AITarget;
-import com.minecolonies.coremod.util.*;
+import com.minecolonies.coremod.tileentities.TileEntityRack;
+import com.minecolonies.coremod.util.StructureWrapper;
 import net.minecraft.block.Block;
 import net.minecraft.block.BlockBed;
+import net.minecraft.block.BlockChest;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java]: MINOR Remove this unused import 'net.minecraft.block.BlockChest'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java [hunk 25]
```diff
@@ -1,21 +1,26 @@
...
 
+import com.minecolonies.api.configuration.Configurations;
+import com.minecolonies.api.util.*;
 import com.minecolonies.coremod.blocks.AbstractBlockHut;
 import com.minecolonies.coremod.blocks.BlockSolidSubstitution;
+import com.minecolonies.coremod.blocks.ModBlocks;
 import com.minecolonies.coremod.colony.buildings.AbstractBuilding;
 import com.minecolonies.coremod.colony.buildings.AbstractBuildingWorker;
 import com.minecolonies.coremod.colony.buildings.BuildingBuilder;
+import com.minecolonies.coremod.colony.buildings.BuildingWareHouse;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java]: MINOR Remove this unused import 'com.minecolonies.coremod.colony.buildings.BuildingWareHouse'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java [hunk 26]
```diff
@@ -0,0 +1,449 @@
...
+    {
+        final EnumFacing enumFacing = EnumFacing.getHorizontal(meta);
+        return this.getDefaultState().withProperty(FACING, enumFacing);
+    }
+
+    /**
+     * @deprecated but we still need this because there is nothing better.
+     */
+    @Override
+    public IBlockState getActualState(final IBlockState state, final IBlockAccess worldIn, final BlockPos pos)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java]: MAJOR Reduce the number of returns of this method 7, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
MAJOR Add the missing @Deprecated annotation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMissingDeprecatedCheck)
INFO Do not forget to remove this deprecated code someday. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1133)

File: src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java [hunk 27]
```diff
@@ -0,0 +1,449 @@
...
+        return state.withProperty(FACING, rot.rotate(state.getValue(FACING)));
+    }
+
+    /**
+     * @deprecated (Remove this as soon as minecraft offers anything better).
+     */
+    @NotNull
+    @Override
+    @Deprecated
+    public IBlockState withMirror(@NotNull final IBlockState state, final Mirror mirrorIn)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java]: INFO Do not forget to remove this deprecated code someday. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1133)

File: src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java [hunk 28]
```diff
@@ -0,0 +1,449 @@
...
+
+    @NotNull
+    @Override
+    @SideOnly(Side.CLIENT)
+    public BlockRenderLayer getBlockLayer()
+    {
+        return BlockRenderLayer.SOLID;
+    }
+
+    public enum EnumType implements IStringSerializable
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java]: MAJOR Reduce this class from 51 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)

File: src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java [hunk 29]
```diff
@@ -0,0 +1,449 @@
...
+    {
+        return new TileEntityRack();
+    }
+
+    /**
+     * @deprecated (Remove this as soon as minecraft offers anything better).
+     */
+    @Override
+    @Deprecated
+    public boolean isFullBlock(final IBlockState state)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java]: INFO Do not forget to remove this deprecated code someday. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1133)

File: src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java [hunk 30]
```diff
@@ -0,0 +1,449 @@
...
+    {
+        return false;
+    }
+
+    /**
+     * @deprecated (Remove this as soon as minecraft offers anything better).
+     */
+    @Override
+    @Deprecated
+    public boolean isOpaqueCube(final IBlockState state)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java]: INFO Do not forget to remove this deprecated code someday. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1133)

File: src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java [hunk 31]
```diff
@@ -0,0 +1,449 @@
...
+
+    /**
+     * Convert the BlockState into the correct metadata value.
+     *
+     * @deprecated (Remove this as soon as minecraft offers anything better).
+     */
+    @NotNull
+    @Override
+    @Deprecated
+    public IBlockState withRotation(@NotNull final IBlockState state, final Rotation rot)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java]: INFO Do not forget to remove this deprecated code someday. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1133)

File: src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java [hunk 32]
```diff
@@ -0,0 +1,449 @@
...
+
+        worldIn.setBlockState(pos, tempState, 2);
+    }
+
+    /**
+     * @deprecated but we still need this because there is nothing better.
+     */
+    @Deprecated
+    @Override
+    public IBlockState getStateFromMeta(final int meta)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java]: INFO Do not forget to remove this deprecated code someday. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1133)

File: src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java [hunk 33]
```diff
@@ -0,0 +1,449 @@
...
+        return state.getValue(FACING).getHorizontalIndex();
+    }
+
+    /**
+     * On the change of a neighbor block.
+     *
+     * @deprecated (Remove this as soon as minecraft offers anything better).
+     */
+    @Override
+    public void neighborChanged(final IBlockState state, final World worldIn, final BlockPos pos, final Block blockIn)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java]: MAJOR Add the missing @Deprecated annotation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMissingDeprecatedCheck)
INFO Do not forget to remove this deprecated code someday. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1133)

File: src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java [hunk 34]
```diff
@@ -0,0 +1,449 @@
...
+    {
+        return state.withRotation(mirrorIn.toRotation(state.getValue(FACING)));
+    }
+
+    /**
+     * @deprecated (Remove this as soon as minecraft offers anything better).
+     */
+    @Override
+    @Deprecated
+    public boolean isFullCube(final IBlockState state)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java]: INFO Do not forget to remove this deprecated code someday. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1133)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java [hunk 35]
```diff
@@ -252,17 +270,32 @@ public static boolean checkTree(@NotNull final IBlockAccess world, final BlockPo
...
 
-    private static boolean hasEnoughLeaves(@NotNull final IBlockAccess world, final BlockPos pos)
+    /**
+     * Check if the tree has enough leaves and the lj is supposed to cut them.
+     * @param world the world it is in.
+     * @param pos the position.
+     * @param treesToCut the trees the lj is supposed to cut.
+     * @return true if so.
+     */
+    private static boolean hasEnoughLeavesAndIsSupposedToCut(@NotNull final IBlockAccess world, final BlockPos pos, final Map<ItemStorage, Boolean> treesToCut)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java]: MAJOR Refactor this method to reduce its Cognitive Complexity from 21 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

File: src/main/java/com/minecolonies/coremod/commands/citizencommands/AbstractCitizensCommands.java [hunk 36]
```diff
@@ -43,24 +44,24 @@ public String getCommandUsage(@NotNull final ICommandSender sender)
     @Override
     public void execute(@NotNull final MinecraftServer server, @NotNull final ICommandSender sender, @NotNull final String... args) throws CommandException
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/citizencommands/AbstractCitizensCommands.java]: MAJOR Refactor this method to reduce its Cognitive Complexity from 21 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

Comment (Asherslab) [inline src/main/java/com/minecolonies/coremod/commands/citizencommands/AbstractCitizensCommands.java]: Ignore

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java (hunk 35 above)
Comment (Asherslab) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java]: Ignore

File: src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java (hunk 34 above)
Comment (Asherslab) [inline src/main/java/com/minecolonies/coremod/blocks/BlockMinecoloniesRack.java]: Ignore

**Comment by Asherslab** [comment]
Close the PR and merge it into the correct branch (Version/1.10)

**Comment by marchermans** [comment]
Wrong branch as it Looks like. Closing.

**Comment by marchermans** [comment]
Never mind..

**Comment by Raycoms** [comment]
Can you please fix those codacity and sonar bugs?

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 46 issues
* ![MAJOR][MAJOR] 17 major
* ![MINOR][MINOR] 26 minor
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/a08330a3274a26fe62936b20d8de54711539d031/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.314 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L68](https://github.com/Minecolonies/minecolonies/blob/a08330a3274a26fe62936b20d8de54711539d031/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L68): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 56 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L68](https://github.com/Minecolonies/minecolonies/blob/a08330a3274a26fe62936b20d8de54711539d031/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L68): class "EntityCitizen" has 95 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/a08330a3274a26fe62936b20d8de54711539d031/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/a08330a3274a26fe62936b20d8de54711539d031/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/a08330a3274a26fe62936b20d8de54711539d031/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L355](https://github.com/Minecolonies/minecolonies/blob/a08330a3274a26fe62936b20d8de54711539d031/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L355): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L356](https://github.com/Minecolonies/minecolonies/blob/a08330a3274a26fe62936b20d8de54711539d031/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L356): Assign this magic number 6.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L385](https://github.com/Minecolonies/minecolonies/blob/a08330a3274a26fe62936b20d8de54711539d031/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L385): Assign this magic number 3 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L596](https://github.com/Minecolonies/minecolonies/blob/a08330a3274a26fe62936b20d8de54711539d031/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L596): Refactor this method to reduce its Cognitive Complexity from 25 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 46 issues
* ![MAJOR][MAJOR] 17 major
* ![MINOR][MINOR] 26 minor
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/d9638233387bbd18dfb8ff154dfd3b0197e0bc17/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.314 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L68](https://github.com/Minecolonies/minecolonies/blob/d9638233387bbd18dfb8ff154dfd3b0197e0bc17/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L68): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 56 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L68](https://github.com/Minecolonies/minecolonies/blob/d9638233387bbd18dfb8ff154dfd3b0197e0bc17/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L68): class "EntityCitizen" has 95 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/d9638233387bbd18dfb8ff154dfd3b0197e0bc17/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/d9638233387bbd18dfb8ff154dfd3b0197e0bc17/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/d9638233387bbd18dfb8ff154dfd3b0197e0bc17/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L355](https://github.com/Minecolonies/minecolonies/blob/d9638233387bbd18dfb8ff154dfd3b0197e0bc17/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L355): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L356](https://github.com/Minecolonies/minecolonies/blob/d9638233387bbd18dfb8ff154dfd3b0197e0bc17/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L356): Assign this magic number 6.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L385](https://github.com/Minecolonies/minecolonies/blob/d9638233387bbd18dfb8ff154dfd3b0197e0bc17/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L385): Assign this magic number 3 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L596](https://github.com/Minecolonies/minecolonies/blob/d9638233387bbd18dfb8ff154dfd3b0197e0bc17/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L596): Refactor this method to reduce its Cognitive Complexity from 25 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1321/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

File: src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java [hunk 37]
```diff
@@ -656,6 +659,28 @@ else if (saturation > AVERAGE_SATURATION)
...
 
+    /**
+     * repair random equipped/held item with mending enchant.
+     *
+     * @param xp amount of xp available to mend with
+     * @return xp left after mending
+     */
+    private double applyMending(final double xp)
+    {
+        double localXp = xp;
```
Comment (Asherslab) [inline src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java:676]: Quick question, what's the point in doing that? Declaring a value then immediately reassigning it? Please do correct me if I'm wrong =D

Comment (Asherslab) [reply src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java:676]: I.E. Is there any benefit to doing that, that I'm not seeing? =D (btw otherwise looks great)

Comment (ghost) [reply src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java:676]: That was a codacy error. It didn't like me reassigning parameters.

Comment (ghost) [reply src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java:676]: I guess it could cause some unexpected behavior.

Comment (Asherslab) [reply src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java:676]: Ahhh, sounds good then =D

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 46 issues
* ![MAJOR][MAJOR] 17 major
* ![MINOR][MINOR] 26 minor
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/205775aa295c740c959688dc9acbab5376c42d1f/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.320 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L69](https://github.com/Minecolonies/minecolonies/blob/205775aa295c740c959688dc9acbab5376c42d1f/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L69): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 56 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L69](https://github.com/Minecolonies/minecolonies/blob/205775aa295c740c959688dc9acbab5376c42d1f/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L69): class "EntityCitizen" has 95 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L359](https://github.com/Minecolonies/minecolonies/blob/205775aa295c740c959688dc9acbab5376c42d1f/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L359): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L360](https://github.com/Minecolonies/minecolonies/blob/205775aa295c740c959688dc9acbab5376c42d1f/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L360): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L360](https://github.com/Minecolonies/minecolonies/blob/205775aa295c740c959688dc9acbab5376c42d1f/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L360): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L361](https://github.com/Minecolonies/minecolonies/blob/205775aa295c740c959688dc9acbab5376c42d1f/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L361): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L362](https://github.com/Minecolonies/minecolonies/blob/205775aa295c740c959688dc9acbab5376c42d1f/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L362): Assign this magic number 6.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L391](https://github.com/Minecolonies/minecolonies/blob/205775aa295c740c959688dc9acbab5376c42d1f/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L391): Assign this magic number 3 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L602](https://github.com/Minecolonies/minecolonies/blob/205775aa295c740c959688dc9acbab5376c42d1f/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L602): Refactor this method to reduce its Cognitive Complexity from 25 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Asherslab** [comment]
:shipit: looks great to me =D @OrionDevelopment

**Comment by marvin-bitterlich** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1321/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by marvin-bitterlich** [comment]
@Vitridax can you make a port to other versions? (on our repo this time, you have access now 😄 )

**Comment by ghost** [comment]
Ok. It was pretty small, so I already did it. I ported to 1.11 and 1.12. I didn't think I needed to for 1.8 because that hasn't been updated in a year :laughing: !

**Comment by Asherslab** [comment]
@Vitridax you're correct, can you submit the PRs?
