### PR TITLE
Better building

### LINKED ISSUE #480: AbstractWindowBuilding: cost of the next upgrade in a tab
### Minecolonies version

Future version
### Expected behavior

- Add a tab with the list of resources needed if we where to upgrade

Difficulty: moderate (as it is similar to the Builder huts resources tab)

### Actual behaviour

- In the current version, we don't know what an upgrade is going to cost

### Steps to reproduce the problem

1. Try to upgrade Builder's hut to level 3
2. Find out that you need Coarse dirt
3. Realise that you haven't seen one of them yet
4. Scream and cry like a baby

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/41161233-abstractwindowbuilding-cost-of-the-next-upgrade-in-a-tab?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #2069: server crash on client connection
### Minecolonies version

updating from 0.8.6996 to 0.8.7011 (MC 1.12.2)

[https://gist.github.com/lebanni/2196710bc60516a9ba33ef300caa4540](url)

[https://gist.github.com/lebanni/9f04e02c3985a5f02df04a84258d06e5](url)

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #480 
Closes #2069

# Changes proposed in this pull request:
- Allows you to switch between styles
- Allows you to show the resources required for a build or upgrade
- Fixes missing citizens to auto spawn them.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java [hunk 1]
```diff
@@ -33,131 +33,13 @@
 import java.util.ArrayList;
 import java.util.List;
 
+import static com.minecolonies.api.util.constant.WindowConstants.*;
+
 /**
  * BuildTool window.
  */
 public class WindowBuildTool extends AbstractWindowSkeleton
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java:41]: MAJOR class "WindowBuildTool" has 41 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java [hunk 2]
```diff
@@ -27,12 +27,10 @@
 import net.minecraft.init.Blocks;
 import net.minecraft.init.Items;
 import net.minecraft.item.ItemStack;
-import net.minecraft.nbt.NBTTagCompound;
 import net.minecraft.tileentity.TileEntity;
-import net.minecraft.tileentity.TileEntityFlowerPot;
-import net.minecraft.tileentity.TileEntityLockable;
 import net.minecraft.util.math.BlockPos;
 import net.minecraft.util.math.RayTraceResult;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java]: MINOR Remove this unused import 'net.minecraft.util.math.RayTraceResult'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java [hunk 3]
```diff
@@ -27,12 +27,10 @@
...
+import net.minecraft.world.World;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java]: MINOR Remove this unused import 'net.minecraft.world.World'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java [hunk 4]
```diff
@@ -27,12 +27,10 @@
 import net.minecraft.init.Blocks;
 import net.minecraft.init.Items;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java]: MINOR Remove this unused import 'net.minecraft.init.Items'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 5]
```diff
@@ -0,0 +1,362 @@
...
+import com.minecolonies.coremod.colony.ColonyView;
+import com.minecolonies.coremod.colony.StructureName;
+import com.minecolonies.coremod.colony.Structures;
+import com.minecolonies.coremod.colony.buildings.BuildingBuilder;
+import com.minecolonies.coremod.colony.buildings.utils.BuildingBuilderResource;
+import com.minecolonies.coremod.colony.buildings.views.AbstractBuildingView;
+import com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure;
+import com.minecolonies.coremod.entity.ai.citizen.builder.EntityAIStructureBuilder;
+import com.minecolonies.coremod.network.messages.BuildRequestMessage;
+import com.minecolonies.coremod.network.messages.BuildingSetStyleMessage;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MINOR Remove this unused import 'com.minecolonies.coremod.network.messages.HireFireMessage'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 6]
```diff
@@ -0,0 +1,362 @@
...
+                    return styles.get(index);
+                }
+                return "";
+            }
+        });
+    }
+
+    /**
+     * called every time one of the dropdownlist changed.
+     *
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MAJOR Remove this unused method parameter "list". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 7]
```diff
@@ -0,0 +1,362 @@
+package com.minecolonies.coremod.client.gui;
+
+import com.minecolonies.api.crafting.ItemStorage;
+import com.minecolonies.api.util.BlockPosUtil;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MINOR Remove this unused import 'com.minecolonies.api.util.BlockPosUtil'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 8]
```diff
@@ -0,0 +1,362 @@
...
+
+        findPaneOfTypeByID(BUTTON_PREVIOUS_STYLE_ID, Button.class).setEnabled(enabled);
+        findPaneOfTypeByID(DROPDOWN_STYLE_ID, DropDownList.class).setEnabled(enabled);
+        findPaneOfTypeByID(BUTTON_NEXT_STYLE_ID, Button.class).setEnabled(enabled);
+        stylesDropDownList.setSelectedIndex(newIndex);
+    }
+
+    /**
+     * Clears and resets/updates all resources.
+     */
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MAJOR The Cyclomatic Complexity of this method "updateResources" is 19 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
MAJOR Refactor this method to reduce its Cognitive Complexity from 34 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 9]
```diff
@@ -0,0 +1,362 @@
+package com.minecolonies.coremod.client.gui;
+
+import com.minecolonies.api.crafting.ItemStorage;
+import com.minecolonies.api.util.BlockPosUtil;
+import com.minecolonies.api.util.BlockUtils;
+import com.minecolonies.api.util.ItemStackUtils;
+import com.minecolonies.api.util.LanguageHandler;
+import com.minecolonies.api.util.constant.ColorConstants;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MINOR Remove this unused import 'com.minecolonies.api.util.constant.ColorConstants'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 10]
```diff
@@ -0,0 +1,362 @@
...
+    }
+
+    /**
+     * Clears and resets/updates all resources.
+     */
+    private void updateResources()
+    {
+        final World world = Minecraft.getMinecraft().world;
+        resources.clear();
+
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MAJOR Split this 198 characters long line (which is greater than 180 authorized). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00103)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 11]
```diff
@@ -0,0 +1,362 @@
...
+        final StructureName sn = new StructureName(Structures.SCHEMATICS_PREFIX, styles.get(stylesDropDownList.getSelectedIndex()) , building.getSchematicName() + (building.getBuildingLevel() + 1));
+        final StructureWrapper wrapper = new StructureWrapper(world, sn.toString());
+        wrapper.setPosition(building.getLocation());
+        wrapper.rotate(building.getRotation(), world, building.getLocation(), building.isMirrored() ? Mirror.FRONT_BACK : Mirror.NONE);
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MAJOR Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS135)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 12]
```diff
@@ -0,0 +1,362 @@
...
+import net.minecraft.init.Blocks;
+import net.minecraft.item.ItemStack;
+import net.minecraft.util.Mirror;
+import net.minecraft.util.math.BlockPos;
+import net.minecraft.world.World;
+import net.minecraft.world.gen.structure.template.Template;
+import org.jetbrains.annotations.NotNull;
+import org.jetbrains.annotations.Nullable;
+
+import java.util.ArrayList;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MINOR Remove this unused import 'java.util.Collections'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 13]
```diff
@@ -0,0 +1,362 @@
...
+import com.minecolonies.blockout.Pane;
+import com.minecolonies.blockout.controls.Button;
+import com.minecolonies.blockout.controls.ButtonHandler;
+import com.minecolonies.blockout.controls.ItemIcon;
+import com.minecolonies.blockout.controls.Label;
+import com.minecolonies.blockout.views.DropDownList;
+import com.minecolonies.blockout.views.ScrollingList;
+import com.minecolonies.blockout.views.Window;
+import com.minecolonies.coremod.MineColonies;
+import com.minecolonies.coremod.blocks.AbstractBlockHut;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MINOR Remove this unused import 'com.minecolonies.coremod.blocks.AbstractBlockHut'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 14]
```diff
@@ -0,0 +1,362 @@
...
+import com.minecolonies.coremod.blocks.BlockSolidSubstitution;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MINOR Remove this unused import 'com.minecolonies.coremod.blocks.BlockSolidSubstitution'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 15]
```diff
@@ -0,0 +1,362 @@
...
+import com.minecolonies.coremod.blocks.ModBlocks;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MINOR Remove this unused import 'com.minecolonies.coremod.colony.CitizenDataView'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 16]
```diff
@@ -0,0 +1,362 @@
...
+import com.minecolonies.coremod.colony.CitizenDataView;
+import com.minecolonies.coremod.colony.ColonyView;
+import com.minecolonies.coremod.colony.StructureName;
+import com.minecolonies.coremod.colony.Structures;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MINOR Remove this unused import 'com.minecolonies.coremod.colony.buildings.BuildingBuilder'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 17]
```diff
@@ -0,0 +1,362 @@
...
+import com.minecolonies.coremod.colony.buildings.BuildingBuilder;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MINOR Remove this unused import 'com.minecolonies.coremod.colony.buildings.utils.BuildingBuilderResource'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 18]
```diff
@@ -0,0 +1,362 @@
...
+import java.util.Collections;
+import java.util.HashMap;
+import java.util.List;
+
+import static com.minecolonies.api.util.constant.TranslationConstants.*;
+import static com.minecolonies.api.util.constant.WindowConstants.*;
+
+/**
+ * Window for selecting the style and confirming the resources.
+ */
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MINOR "ButtonHandler" is implemented by a super class; there is no need to implement it here. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1939)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 19]
```diff
@@ -0,0 +1,362 @@
...
+import com.minecolonies.coremod.blocks.BlockSolidSubstitution;
+import com.minecolonies.coremod.blocks.ModBlocks;
+import com.minecolonies.coremod.colony.CitizenDataView;
+import com.minecolonies.coremod.colony.ColonyView;
+import com.minecolonies.coremod.colony.StructureName;
+import com.minecolonies.coremod.colony.Structures;
+import com.minecolonies.coremod.colony.buildings.BuildingBuilder;
+import com.minecolonies.coremod.colony.buildings.utils.BuildingBuilderResource;
+import com.minecolonies.coremod.colony.buildings.views.AbstractBuildingView;
+import com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MINOR Remove this unused import 'com.minecolonies.coremod.entity.ai.citizen.builder.EntityAIStructureBuilder'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 20]
```diff
@@ -0,0 +1,362 @@
...
+                    && block != ModBlocks.blockSubstitution)
+            {
+                if (wrapper.getBlockInfo().tileentityData != null)
+                {
+                    final List<ItemStack> itemList = new ArrayList<>();
+                    if (wrapper.getBlockInfo() != null && wrapper.getBlockInfo().tileentityData != null)
+                    {
+                        itemList.addAll(ItemStackUtils.getItemStacksOfTileEntity(wrapper.getBlockInfo().tileentityData, world));
+                    }
+
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MINOR Make this line start at column 25. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

File: src/main/java/com/minecolonies/blockout/controls/TextField.java [hunk 21]
```diff
@@ -322,7 +322,7 @@ public void onFocus()
      * Draw itself at positions mx and my.
      */
     @Override
-    protected void drawSelf(final int mx, final int my)
+    public void drawSelf(final int mx, final int my)
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/blockout/controls/TextField.java:325]: MAJOR The Cyclomatic Complexity of this method "drawSelf" is 21 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
MAJOR Refactor this method to reduce its Cognitive Complexity from 24 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 106 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 72 major
* ![MINOR][MINOR] 28 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1447](https://github.com/Minecolonies/minecolonies/blob/790d2fef4bee1dd0e5b7008450d3ae9301f14b74/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1447): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1476](https://github.com/Minecolonies/minecolonies/blob/790d2fef4bee1dd0e5b7008450d3ae9301f14b74/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1476): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1487](https://github.com/Minecolonies/minecolonies/blob/790d2fef4bee1dd0e5b7008450d3ae9301f14b74/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1487): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1593](https://github.com/Minecolonies/minecolonies/blob/790d2fef4bee1dd0e5b7008450d3ae9301f14b74/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1593): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L303](https://github.com/Minecolonies/minecolonies/blob/790d2fef4bee1dd0e5b7008450d3ae9301f14b74/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L303): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L335](https://github.com/Minecolonies/minecolonies/blob/790d2fef4bee1dd0e5b7008450d3ae9301f14b74/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L335): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [Pane.java#L19](https://github.com/Minecolonies/minecolonies/blob/790d2fef4bee1dd0e5b7008450d3ae9301f14b74/src/main/java/com/minecolonies/blockout/Pane.java#L19): class "Pane" has 47 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L13](https://github.com/Minecolonies/minecolonies/blob/790d2fef4bee1dd0e5b7008450d3ae9301f14b74/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L13): class "ButtonImage" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L563](https://github.com/Minecolonies/minecolonies/blob/790d2fef4bee1dd0e5b7008450d3ae9301f14b74/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L563): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [TextField.java#L21](https://github.com/Minecolonies/minecolonies/blob/790d2fef4bee1dd0e5b7008450d3ae9301f14b74/src/main/java/com/minecolonies/blockout/controls/TextField.java#L21): class "TextField" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 22]
```diff
@@ -0,0 +1,353 @@
...
+    /**
+     * Clears and resets/updates all resources.
+     */
+    private void updateResources()
+    {
+        final World world = Minecraft.getMinecraft().world;
+        resources.clear();
+
+        final StructureName sn = new StructureName(Structures.SCHEMATICS_PREFIX, styles.get(stylesDropDownList.getSelectedIndex()) , building.getSchematicName() + (building.getBuildingLevel() + 1));
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MAJOR Split this 198 characters long line (which is greater than 180 authorized). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00103)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 23]
```diff
@@ -0,0 +1,353 @@
...
+import java.util.HashMap;
+import java.util.List;
+
+import static com.minecolonies.api.util.constant.TranslationConstants.*;
+import static com.minecolonies.api.util.constant.WindowConstants.*;
+
+/**
+ * Window for selecting the style and confirming the resources.
+ */
+public class WindowBuildBuilding extends AbstractWindowSkeleton implements ButtonHandler
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MINOR "ButtonHandler" is implemented by a super class; there is no need to implement it here. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1939)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 24]
```diff
@@ -0,0 +1,353 @@
...
+                {
+                    final List<ItemStack> itemList = new ArrayList<>();
+                    if (wrapper.getBlockInfo() != null && wrapper.getBlockInfo().tileentityData != null)
+                    {
+                        itemList.addAll(ItemStackUtils.getItemStacksOfTileEntity(wrapper.getBlockInfo().tileentityData, world));
+                    }
+
+                    for (final ItemStack stack : itemList)
+                    {
+                       addNeededResource(stack, 1);
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MINOR Make this line start at column 25. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 25]
```diff
@@ -0,0 +1,353 @@
...
+    private void updateResources()
+    {
+        final World world = Minecraft.getMinecraft().world;
+        resources.clear();
+
+        final StructureName sn = new StructureName(Structures.SCHEMATICS_PREFIX, styles.get(stylesDropDownList.getSelectedIndex()) , building.getSchematicName() + (building.getBuildingLevel() + 1));
+        final StructureWrapper wrapper = new StructureWrapper(world, sn.toString());
+        wrapper.setPosition(building.getLocation());
+        wrapper.rotate(building.getRotation(), world, building.getLocation(), building.isMirrored() ? Mirror.FRONT_BACK : Mirror.NONE);
+        while (wrapper.findNextBlock())
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MAJOR Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS135)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 26]
```diff
@@ -0,0 +1,353 @@
...
+import net.minecraft.item.ItemStack;
+import net.minecraft.util.Mirror;
+import net.minecraft.util.math.BlockPos;
+import net.minecraft.world.World;
+import net.minecraft.world.gen.structure.template.Template;
+import org.jetbrains.annotations.NotNull;
+import org.jetbrains.annotations.Nullable;
+
+import java.util.ArrayList;
+import java.util.Collections;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MINOR Remove this unused import 'java.util.Collections'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 27]
```diff
@@ -0,0 +1,353 @@
...
+            }
+        });
+    }
+
+    /**
+     * called every time one of the dropdownlist changed.
+     *
+     * @param list the dropdown list which change
+     */
+    private void onDropDownListChanged(final DropDownList list)
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MAJOR Remove this unused method parameter "list". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 28]
```diff
@@ -0,0 +1,353 @@
...
+        findPaneOfTypeByID(BUTTON_PREVIOUS_STYLE_ID, Button.class).setEnabled(enabled);
+        findPaneOfTypeByID(DROPDOWN_STYLE_ID, DropDownList.class).setEnabled(enabled);
+        findPaneOfTypeByID(BUTTON_NEXT_STYLE_ID, Button.class).setEnabled(enabled);
+        stylesDropDownList.setSelectedIndex(newIndex);
+    }
+
+    /**
+     * Clears and resets/updates all resources.
+     */
+    private void updateResources()
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MAJOR The Cyclomatic Complexity of this method "updateResources" is 21 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
MAJOR Refactor this method to reduce its Cognitive Complexity from 34 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 86 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 72 major
* ![MINOR][MINOR] 8 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1447](https://github.com/Minecolonies/minecolonies/blob/ef7f34eb71c682bb587c5e605123492985d7f94f/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1447): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1476](https://github.com/Minecolonies/minecolonies/blob/ef7f34eb71c682bb587c5e605123492985d7f94f/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1476): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1487](https://github.com/Minecolonies/minecolonies/blob/ef7f34eb71c682bb587c5e605123492985d7f94f/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1487): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1593](https://github.com/Minecolonies/minecolonies/blob/ef7f34eb71c682bb587c5e605123492985d7f94f/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1593): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L303](https://github.com/Minecolonies/minecolonies/blob/ef7f34eb71c682bb587c5e605123492985d7f94f/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L303): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L335](https://github.com/Minecolonies/minecolonies/blob/ef7f34eb71c682bb587c5e605123492985d7f94f/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L335): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [Pane.java#L19](https://github.com/Minecolonies/minecolonies/blob/ef7f34eb71c682bb587c5e605123492985d7f94f/src/main/java/com/minecolonies/blockout/Pane.java#L19): class "Pane" has 47 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L13](https://github.com/Minecolonies/minecolonies/blob/ef7f34eb71c682bb587c5e605123492985d7f94f/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L13): class "ButtonImage" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L563](https://github.com/Minecolonies/minecolonies/blob/ef7f34eb71c682bb587c5e605123492985d7f94f/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L563): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [TextField.java#L21](https://github.com/Minecolonies/minecolonies/blob/ef7f34eb71c682bb587c5e605123492985d7f94f/src/main/java/com/minecolonies/blockout/controls/TextField.java#L21): class "TextField" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 83 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 71 major
* ![MINOR][MINOR] 6 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1448](https://github.com/Minecolonies/minecolonies/blob/f3d2de7dc3c8e40c8fe962b6ac7728069b3c8320/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1448): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1477](https://github.com/Minecolonies/minecolonies/blob/f3d2de7dc3c8e40c8fe962b6ac7728069b3c8320/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1477): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1488](https://github.com/Minecolonies/minecolonies/blob/f3d2de7dc3c8e40c8fe962b6ac7728069b3c8320/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1488): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1594](https://github.com/Minecolonies/minecolonies/blob/f3d2de7dc3c8e40c8fe962b6ac7728069b3c8320/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1594): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L303](https://github.com/Minecolonies/minecolonies/blob/f3d2de7dc3c8e40c8fe962b6ac7728069b3c8320/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L303): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L335](https://github.com/Minecolonies/minecolonies/blob/f3d2de7dc3c8e40c8fe962b6ac7728069b3c8320/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L335): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [Pane.java#L19](https://github.com/Minecolonies/minecolonies/blob/f3d2de7dc3c8e40c8fe962b6ac7728069b3c8320/src/main/java/com/minecolonies/blockout/Pane.java#L19): class "Pane" has 47 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L13](https://github.com/Minecolonies/minecolonies/blob/f3d2de7dc3c8e40c8fe962b6ac7728069b3c8320/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L13): class "ButtonImage" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L563](https://github.com/Minecolonies/minecolonies/blob/f3d2de7dc3c8e40c8fe962b6ac7728069b3c8320/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L563): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [TextField.java#L21](https://github.com/Minecolonies/minecolonies/blob/f3d2de7dc3c8e40c8fe962b6ac7728069b3c8320/src/main/java/com/minecolonies/blockout/controls/TextField.java#L21): class "TextField" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Review by marchermans — DISMISSED** [review]

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 29]
```diff
@@ -0,0 +1,360 @@
...
+    {
+        final World world = Minecraft.getMinecraft().world;
+        resources.clear();
+
+        int nextLevel = building.getBuildingLevel() == building.getBuildingMaxLevel() ? building.getBuildingMaxLevel() : building.getBuildingLevel() + 1;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MAJOR Add parentheses to make the operator precedence explicit. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS864)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 30]
```diff
@@ -0,0 +1,360 @@
...
+        final StructureName sn = new StructureName(Structures.SCHEMATICS_PREFIX, styles.get(stylesDropDownList.getSelectedIndex()) ,
+                building.getSchematicName() + nextLevel);
+        final StructureWrapper wrapper = new StructureWrapper(world, sn.toString());
+        wrapper.setPosition(building.getLocation());
+        wrapper.rotate(building.getRotation(), world, building.getLocation(), building.isMirrored() ? Mirror.FRONT_BACK : Mirror.NONE);
+        while (wrapper.findNextBlock())
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MAJOR Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS135)

File: src/main/java/com/minecolonies/blockout/views/ScrollingView.java [hunk 31]
```diff
@@ -4,6 +4,7 @@
 import com.minecolonies.blockout.PaneParams;
 import com.minecolonies.blockout.controls.Scrollbar;
 import org.jetbrains.annotations.NotNull;
+import org.lwjgl.input.Mouse;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/blockout/views/ScrollingView.java]: MINOR Remove this unused import 'org.lwjgl.input.Mouse'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 85 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 72 major
* ![MINOR][MINOR] 7 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1448](https://github.com/Minecolonies/minecolonies/blob/6d0eff2afa7fdc3aba99891f8cf8ac760839f668/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1448): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1477](https://github.com/Minecolonies/minecolonies/blob/6d0eff2afa7fdc3aba99891f8cf8ac760839f668/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1477): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1488](https://github.com/Minecolonies/minecolonies/blob/6d0eff2afa7fdc3aba99891f8cf8ac760839f668/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1488): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1594](https://github.com/Minecolonies/minecolonies/blob/6d0eff2afa7fdc3aba99891f8cf8ac760839f668/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1594): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L303](https://github.com/Minecolonies/minecolonies/blob/6d0eff2afa7fdc3aba99891f8cf8ac760839f668/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L303): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L335](https://github.com/Minecolonies/minecolonies/blob/6d0eff2afa7fdc3aba99891f8cf8ac760839f668/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L335): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [Pane.java#L19](https://github.com/Minecolonies/minecolonies/blob/6d0eff2afa7fdc3aba99891f8cf8ac760839f668/src/main/java/com/minecolonies/blockout/Pane.java#L19): class "Pane" has 48 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L13](https://github.com/Minecolonies/minecolonies/blob/6d0eff2afa7fdc3aba99891f8cf8ac760839f668/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L13): class "ButtonImage" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L563](https://github.com/Minecolonies/minecolonies/blob/6d0eff2afa7fdc3aba99891f8cf8ac760839f668/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L563): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [TextField.java#L21](https://github.com/Minecolonies/minecolonies/blob/6d0eff2afa7fdc3aba99891f8cf8ac760839f668/src/main/java/com/minecolonies/blockout/controls/TextField.java#L21): class "TextField" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 86 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 72 major
* ![MINOR][MINOR] 8 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1448](https://github.com/Minecolonies/minecolonies/blob/9349261642cf324561385be9e5bde58b2a353142/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1448): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1477](https://github.com/Minecolonies/minecolonies/blob/9349261642cf324561385be9e5bde58b2a353142/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1477): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1488](https://github.com/Minecolonies/minecolonies/blob/9349261642cf324561385be9e5bde58b2a353142/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1488): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1594](https://github.com/Minecolonies/minecolonies/blob/9349261642cf324561385be9e5bde58b2a353142/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1594): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L303](https://github.com/Minecolonies/minecolonies/blob/9349261642cf324561385be9e5bde58b2a353142/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L303): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L335](https://github.com/Minecolonies/minecolonies/blob/9349261642cf324561385be9e5bde58b2a353142/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L335): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [Pane.java#L19](https://github.com/Minecolonies/minecolonies/blob/9349261642cf324561385be9e5bde58b2a353142/src/main/java/com/minecolonies/blockout/Pane.java#L19): class "Pane" has 48 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L13](https://github.com/Minecolonies/minecolonies/blob/9349261642cf324561385be9e5bde58b2a353142/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L13): class "ButtonImage" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L563](https://github.com/Minecolonies/minecolonies/blob/9349261642cf324561385be9e5bde58b2a353142/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L563): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [TextField.java#L21](https://github.com/Minecolonies/minecolonies/blob/9349261642cf324561385be9e5bde58b2a353142/src/main/java/com/minecolonies/blockout/controls/TextField.java#L21): class "TextField" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 32]
```diff
@@ -0,0 +1,359 @@
...
+        findPaneOfTypeByID(DROPDOWN_STYLE_ID, DropDownList.class).setEnabled(enabled);
+        findPaneOfTypeByID(BUTTON_NEXT_STYLE_ID, Button.class).setEnabled(enabled);
+        stylesDropDownList.setSelectedIndex(newIndex);
+    }
+
+    /**
+     * Clears and resets/updates all resources.
+     */
+    private void updateResources()
+    {
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MAJOR The Cyclomatic Complexity of this method "updateResources" is 22 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
MAJOR Refactor this method to reduce its Cognitive Complexity from 35 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 33]
```diff
@@ -0,0 +1,359 @@
...
+        });
+    }
+
+    /**
+     * called every time one of the dropdownlist changed.
+     *
+     * @param list the dropdown list which change
+     */
+    private void onDropDownListChanged(final DropDownList list)
+    {
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MAJOR Remove this unused method parameter "list". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 34]
```diff
@@ -0,0 +1,359 @@
...
+    /**
+     * Clears and resets/updates all resources.
+     */
+    private void updateResources()
+    {
+        final World world = Minecraft.getMinecraft().world;
+        resources.clear();
+
+        final int nextLevel = building.getBuildingLevel() == building.getBuildingMaxLevel() ? building.getBuildingMaxLevel() : building.getBuildingLevel() + 1;
+        final StructureName sn = new StructureName(Structures.SCHEMATICS_PREFIX, styles.get(stylesDropDownList.getSelectedIndex()) ,
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MAJOR Add parentheses to make the operator precedence explicit. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS864)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 35]
```diff
@@ -0,0 +1,359 @@
+package com.minecolonies.coremod.client.gui;
+
+import com.minecolonies.api.crafting.ItemStorage;
+import com.minecolonies.api.util.BlockUtils;
+import com.minecolonies.api.util.ItemStackUtils;
+import com.minecolonies.api.util.LanguageHandler;
+import com.minecolonies.api.util.constant.Constants;
+import com.minecolonies.blockout.Pane;
+import com.minecolonies.blockout.controls.Button;
+import com.minecolonies.blockout.controls.ItemIcon;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MINOR Remove this unused import 'com.minecolonies.blockout.controls.ButtonHandler'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 36]
```diff
@@ -0,0 +1,359 @@
...
+        resources.clear();
+
+        final int nextLevel = building.getBuildingLevel() == building.getBuildingMaxLevel() ? building.getBuildingMaxLevel() : building.getBuildingLevel() + 1;
+        final StructureName sn = new StructureName(Structures.SCHEMATICS_PREFIX, styles.get(stylesDropDownList.getSelectedIndex()) ,
+                building.getSchematicName() + nextLevel);
+        final StructureWrapper wrapper = new StructureWrapper(world, sn.toString());
+        wrapper.setPosition(building.getLocation());
+        wrapper.rotate(building.getRotation(), world, building.getLocation(), building.isMirrored() ? Mirror.FRONT_BACK : Mirror.NONE);
+        while (wrapper.findNextBlock())
+        {
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: MAJOR Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS135)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 86 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 72 major
* ![MINOR][MINOR] 8 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1448](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1448): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1477](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1477): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1488](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1488): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1594](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1594): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L303](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L303): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L335](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L335): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [Pane.java#L19](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/blockout/Pane.java#L19): class "Pane" has 48 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L13](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L13): class "ButtonImage" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L563](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L563): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [TextField.java#L21](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/blockout/controls/TextField.java#L21): class "TextField" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 86 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 72 major
* ![MINOR][MINOR] 8 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1448](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1448): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1477](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1477): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1488](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1488): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1594](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1594): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L300](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L300): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L332](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L332): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [Pane.java#L19](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/blockout/Pane.java#L19): class "Pane" has 48 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L13](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L13): class "ButtonImage" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L563](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L563): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [TextField.java#L21](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/blockout/controls/TextField.java#L21): class "TextField" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 37]
```diff
@@ -0,0 +1,359 @@
...
+        findPaneOfTypeByID(BUTTON_PREVIOUS_STYLE_ID, Button.class).setEnabled(enabled);
+        findPaneOfTypeByID(DROPDOWN_STYLE_ID, DropDownList.class).setEnabled(enabled);
+        findPaneOfTypeByID(BUTTON_NEXT_STYLE_ID, Button.class).setEnabled(enabled);
+        stylesDropDownList.setSelectedIndex(newIndex);
+    }
+
+    /**
+     * Clears and resets/updates all resources.
+     */
+    private void updateResources()
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java:163]: MAJOR The Cyclomatic Complexity of this method "updateResources" is 22 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
MAJOR Refactor this method to reduce its Cognitive Complexity from 35 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 38]
```diff
@@ -0,0 +1,359 @@
...
+            }
+        });
+    }
+
+    /**
+     * called every time one of the dropdownlist changed.
+     *
+     * @param list the dropdown list which change
+     */
+    private void onDropDownListChanged(final DropDownList list)
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java:291]: MAJOR Remove this unused method parameter "list". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 39]
```diff
@@ -0,0 +1,359 @@
...
+
+    /**
+     * Clears and resets/updates all resources.
+     */
+    private void updateResources()
+    {
+        final World world = Minecraft.getMinecraft().world;
+        resources.clear();
+
+        final int nextLevel = building.getBuildingLevel() == building.getBuildingMaxLevel() ? building.getBuildingMaxLevel() : building.getBuildingLevel() + 1;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java:168]: MAJOR Add parentheses to make the operator precedence explicit. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS864)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 40]
```diff
@@ -0,0 +1,359 @@
...
+        final StructureName sn = new StructureName(Structures.SCHEMATICS_PREFIX, styles.get(stylesDropDownList.getSelectedIndex()) ,
+                building.getSchematicName() + nextLevel);
+        final StructureWrapper wrapper = new StructureWrapper(world, sn.toString());
+        wrapper.setPosition(building.getLocation());
+        wrapper.rotate(building.getRotation(), world, building.getLocation(), building.isMirrored() ? Mirror.FRONT_BACK : Mirror.NONE);
+        while (wrapper.findNextBlock())
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java:174]: MAJOR Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS135)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 84 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 72 major
* ![MINOR][MINOR] 6 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1448](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1448): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1477](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1477): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1488](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1488): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1594](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1594): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L300](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L300): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L332](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L332): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [Pane.java#L19](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/blockout/Pane.java#L19): class "Pane" has 48 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L13](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L13): class "ButtonImage" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L563](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L563): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [TextField.java#L21](https://github.com/Minecolonies/minecolonies/blob/d1d4fd93ba846a31c61b6f9bd6b8b40c0c2442b8/src/main/java/com/minecolonies/blockout/controls/TextField.java#L21): class "TextField" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 84 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 72 major
* ![MINOR][MINOR] 6 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1449](https://github.com/Minecolonies/minecolonies/blob/21a7f0933f845457dd01bbac5bd4634749d13079/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1449): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1478](https://github.com/Minecolonies/minecolonies/blob/21a7f0933f845457dd01bbac5bd4634749d13079/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1478): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1489](https://github.com/Minecolonies/minecolonies/blob/21a7f0933f845457dd01bbac5bd4634749d13079/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1489): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1595](https://github.com/Minecolonies/minecolonies/blob/21a7f0933f845457dd01bbac5bd4634749d13079/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1595): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L300](https://github.com/Minecolonies/minecolonies/blob/21a7f0933f845457dd01bbac5bd4634749d13079/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L300): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L332](https://github.com/Minecolonies/minecolonies/blob/21a7f0933f845457dd01bbac5bd4634749d13079/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L332): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [Pane.java#L19](https://github.com/Minecolonies/minecolonies/blob/21a7f0933f845457dd01bbac5bd4634749d13079/src/main/java/com/minecolonies/blockout/Pane.java#L19): class "Pane" has 48 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L13](https://github.com/Minecolonies/minecolonies/blob/21a7f0933f845457dd01bbac5bd4634749d13079/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L13): class "ButtonImage" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L563](https://github.com/Minecolonies/minecolonies/blob/21a7f0933f845457dd01bbac5bd4634749d13079/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L563): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [TextField.java#L21](https://github.com/Minecolonies/minecolonies/blob/21a7f0933f845457dd01bbac5bd4634749d13079/src/main/java/com/minecolonies/blockout/controls/TextField.java#L21): class "TextField" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 84 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 72 major
* ![MINOR][MINOR] 6 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1449](https://github.com/Minecolonies/minecolonies/blob/e54b46d639e0ae3cdc632802a21bbe24837f6d88/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1449): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1478](https://github.com/Minecolonies/minecolonies/blob/e54b46d639e0ae3cdc632802a21bbe24837f6d88/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1478): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1489](https://github.com/Minecolonies/minecolonies/blob/e54b46d639e0ae3cdc632802a21bbe24837f6d88/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1489): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1595](https://github.com/Minecolonies/minecolonies/blob/e54b46d639e0ae3cdc632802a21bbe24837f6d88/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1595): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L300](https://github.com/Minecolonies/minecolonies/blob/e54b46d639e0ae3cdc632802a21bbe24837f6d88/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L300): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L332](https://github.com/Minecolonies/minecolonies/blob/e54b46d639e0ae3cdc632802a21bbe24837f6d88/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L332): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [Pane.java#L19](https://github.com/Minecolonies/minecolonies/blob/e54b46d639e0ae3cdc632802a21bbe24837f6d88/src/main/java/com/minecolonies/blockout/Pane.java#L19): class "Pane" has 48 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L13](https://github.com/Minecolonies/minecolonies/blob/e54b46d639e0ae3cdc632802a21bbe24837f6d88/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L13): class "ButtonImage" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L563](https://github.com/Minecolonies/minecolonies/blob/e54b46d639e0ae3cdc632802a21bbe24837f6d88/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L563): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [TextField.java#L21](https://github.com/Minecolonies/minecolonies/blob/e54b46d639e0ae3cdc632802a21bbe24837f6d88/src/main/java/com/minecolonies/blockout/controls/TextField.java#L21): class "TextField" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 87 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 73 major
* ![MINOR][MINOR] 8 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1449](https://github.com/Minecolonies/minecolonies/blob/46784ec854b46070d14ed5be503a17c0e5260937/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1449): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1478](https://github.com/Minecolonies/minecolonies/blob/46784ec854b46070d14ed5be503a17c0e5260937/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1478): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1489](https://github.com/Minecolonies/minecolonies/blob/46784ec854b46070d14ed5be503a17c0e5260937/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1489): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1595](https://github.com/Minecolonies/minecolonies/blob/46784ec854b46070d14ed5be503a17c0e5260937/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1595): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L300](https://github.com/Minecolonies/minecolonies/blob/46784ec854b46070d14ed5be503a17c0e5260937/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L300): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L332](https://github.com/Minecolonies/minecolonies/blob/46784ec854b46070d14ed5be503a17c0e5260937/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L332): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [Pane.java#L19](https://github.com/Minecolonies/minecolonies/blob/46784ec854b46070d14ed5be503a17c0e5260937/src/main/java/com/minecolonies/blockout/Pane.java#L19): class "Pane" has 48 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L13](https://github.com/Minecolonies/minecolonies/blob/46784ec854b46070d14ed5be503a17c0e5260937/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L13): class "ButtonImage" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L563](https://github.com/Minecolonies/minecolonies/blob/46784ec854b46070d14ed5be503a17c0e5260937/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L563): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [TextField.java#L21](https://github.com/Minecolonies/minecolonies/blob/46784ec854b46070d14ed5be503a17c0e5260937/src/main/java/com/minecolonies/blockout/controls/TextField.java#L21): class "TextField" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 87 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 73 major
* ![MINOR][MINOR] 8 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1448](https://github.com/Minecolonies/minecolonies/blob/98832a2274e924862818ac203a6afd616b54b682/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1448): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1477](https://github.com/Minecolonies/minecolonies/blob/98832a2274e924862818ac203a6afd616b54b682/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1477): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1488](https://github.com/Minecolonies/minecolonies/blob/98832a2274e924862818ac203a6afd616b54b682/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1488): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1594](https://github.com/Minecolonies/minecolonies/blob/98832a2274e924862818ac203a6afd616b54b682/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1594): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L300](https://github.com/Minecolonies/minecolonies/blob/98832a2274e924862818ac203a6afd616b54b682/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L300): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L332](https://github.com/Minecolonies/minecolonies/blob/98832a2274e924862818ac203a6afd616b54b682/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L332): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [Pane.java#L19](https://github.com/Minecolonies/minecolonies/blob/98832a2274e924862818ac203a6afd616b54b682/src/main/java/com/minecolonies/blockout/Pane.java#L19): class "Pane" has 48 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L13](https://github.com/Minecolonies/minecolonies/blob/98832a2274e924862818ac203a6afd616b54b682/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L13): class "ButtonImage" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ButtonImage.java#L563](https://github.com/Minecolonies/minecolonies/blob/98832a2274e924862818ac203a6afd616b54b682/src/main/java/com/minecolonies/blockout/controls/ButtonImage.java#L563): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [TextField.java#L21](https://github.com/Minecolonies/minecolonies/blob/98832a2274e924862818ac203a6afd616b54b682/src/main/java/com/minecolonies/blockout/controls/TextField.java#L21): class "TextField" has 38 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
