### PR TITLE
Small fixes

### LINKED ISSUE #6012: Courier doesn't deposit in warehouse
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version:minecolonies-0.13.390-ALPHA-universal - was 0.13.394
- Structurize Version:structurize-0.13.94-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior
Stores items correct as mod intends

## Actual behavior
my courier is only using the original half of the warehouse to store - the building is level two currently
in addition, when he stores items, he gets stuck with items still in their inventory

## Steps to reproduce the issue
1. Build warehouse
2. upgrade warehouse to level two
3. Courier gets stuck with items they are trying to deposit into warehouse second section.

### Logs
 - Logs do not show error

### Notes
This was fixed by down grading my Alpha to 0.13.390

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #6016: Fortress Walls Rotate When Upgraded
### Prerequisite
- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 
- Minecraft Version:1.16.3
- MineColonies Version: 0.13.398-ALPHA
- Structurize Version: 0.13.92-ALPHA
- Related Mods and their Versions: forge 34.1.25, JEI 1.163.-7.6.0.49

## Expected behavior
Had the builder build a fortress wall 4 decoration. Upgraded it and expected it to be in the same orientation. 

## Actual behavior
Every time I try to upgrade fortress wall 4 from level 1 up to level 2, it’s rotated 90 degrees. I didn’t try it on all the other walls but it also happens on wall 3

## Steps to reproduce the issue
1. Have builder build decoration fortress wall 4 or 3 (maybe others as well, those are the only two I tested)
2. Have the builder upgrade from level 1 to 2
3. Wall should be rotated 90 degrees from how it started. 

### Logs
- latest.log: https://gist.github.com/praus1/f8d5bd6349df112aaa1101c6afe1baea
- crashlog: N/A

### Notes
I first encountered this in the FTB unstable pack but I tried in a totally empty Minecraft install with just the forge version, JEI, and the latest Alpha of Minecolonies and Structurize and got the same behavior. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #6017: updated minecolonies official modpack, now miner wont eat or mine, also have to restart builders all the time.
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version:0.13.379
- Structurize Version:0.13.94
- Related Mods and their Versions:

## Expected behavior
<the miner would mine and eat when necessary, builders would go to next task.

## Actual behavior
<the miner just stands there and starves until you fire him. then he eats and goes about regular life. until you hire him back. or another npc. the builders just finish a task and start another, but never leave builder hut to do next task. have to pause and restart them.
Try to give as much detail as possible here to help us properly understand the issue. -->

## Steps to reproduce the issue

1. <not sure what versions i was playing before. using the minecolonies official modpack, but bugs came with update.
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #6021: the cowboy is feeding all the wheat to cows
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.401-BETA-universal
- Structurize Version:0.13.92-ALPHA-universal
- Related Mods and their Versions:forge 34.1.35

## Expected behavior
the cowboy should feed the wheat to cows only once to make them breed, after that he shall return to base

## Actual behavior
the cowboy feeds the cow all the wheat he has in stock, basically depleting all of the stock, repeatedly feeding the cows, that just have breed 1 second ago.

Another user had same issue (discord):
_ok my shepard and Cowherd always use all of the wheat i give them even tho the animal are not breedable so my wheat from my farm gets basically deleted(the 2 from the first breeding not included)_

he mentioned he has it in Minecolonies 13.394 structurize 0.13.94 forge 31.2.45

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #6017 
Closes #6016
Closes #6012
Closes #6021

# Changes proposed in this pull request:
- Fixes deco block rotations
- Fixes eating problems, EatingAI is now AITarget based and compatible for future AI stuff
- Cook and eating AI now transfer food items based of food value

Review please

### CODE REVIEW

**Review by someaddons — DISMISSED** [review]

**Review by Mekle001 — DISMISSED** [review]

File: src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java [hunk 1]
```diff
@@ -132,7 +133,7 @@ public boolean hasSimilarStack(@NotNull final ItemStack stack)
         {
             for (final ResourceLocation tag : stack.getItem().getTags())
             {
-                if (storage.getItemStack().getItem().getTags().contains(tag))
```
Comment (marchermans) [inline src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java:135]: Why are our tags excluded here?

**Review by marchermans — CHANGES_REQUESTED** [review]
Add a comment why our tags are excluded there and it is good.

File: src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java (hunk 1 above)
Comment (Raycoms) [reply src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java:135]: because we got some "all including tags" like "exclusion lists for crafters" where a lot of random items are matched together.

Comment (marchermans) [reply src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java:135]: Make that a config then. Cause there are a lot of tags which have that property potentially.

Comment (Raycoms) [reply src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java:135]: mod exclusion config?

File: src/api/java/com/minecolonies/api/configuration/CommonConfiguration.java [hunk 2]
```diff
@@ -485,6 +486,11 @@ protected CommonConfiguration(final ForgeConfigSpec.Builder builder)
                    ("minestuck:ore_cruxite",
                      "minestuck:ore_uranium"),
           s -> s instanceof String);
+
+        disabledModTags = defineList(builder, "disabledmodtags",
+          Collections.singletonList("minecolonies"),
```
Comment (marchermans) [inline src/api/java/com/minecolonies/api/configuration/CommonConfiguration.java]: Not disable tags from all mods.
But allow tags to be specifically excluded.

See Aequivaleos vanilla plugin on how todo that, since that already filters on tags.

**Review by marchermans — CHANGES_REQUESTED** [review]

File: src/api/java/com/minecolonies/api/configuration/CommonConfiguration.java (hunk 2 above)
Comment (Raycoms) [reply src/api/java/com/minecolonies/api/configuration/CommonConfiguration.java]: Meh, that would become a large list we always have to extend every time we add a new crafter. I rather not do that.

Comment (marchermans) [reply src/api/java/com/minecolonies/api/configuration/CommonConfiguration.java]: I rather you would. This already makes no sense since minecraft itself has both collective and functional tags.

So make the distinction on tag level please.
Possibly with a mod wide override.

**Review by marchermans — CHANGES_REQUESTED** [review]
See comment

File: src/api/java/com/minecolonies/api/configuration/CommonConfiguration.java (hunk 2 above)
Comment (Raycoms) [reply src/api/java/com/minecolonies/api/configuration/CommonConfiguration.java]: I'll make it opt-in, I think that's the best thing anyway.
