### PR TITLE
[RS 1.12] - Bughunting finished. Fixes several problems introduced with the private crafting update.

### LINKED ISSUE #2100: Deliveryman
### 0.8.7210 Minecraft 1.12.2

version 0.8.7210

### Expected behavior

- Deliveryman brings slabs to Miner

### Actual behaviour

- Deliveryman only Gathers and dumps items

### Steps to reproduce the problem

1. Build Warehouse
2. Build Miner
3. Build Deliveryman Hut
4. Wait untill Miner wants something

### LINKED ISSUE #2101: Builder
### Minecolonies version

version 0.8.7210

### Expected behavior

- Builder picks up cobblestone and goes buildind

### Actual behaviour

- Still asking for materials, even if they are at Builder's chest

### Steps to reproduce the problem

1. Build Builder's Hut
2. Ask to build something.
3. Wait untill builder ask for materials
4. Deposit material in their chest

### LINKED ISSUE #2104: Client crash - com.minecolonies.coremod.colony.buildings.views.AbstractBuildingView.getOpenRequests
### Minecolonies version

- minecolonies-universal-1.12.2-0.8.7210

### Actual behaviour

- https://gist.github.com/ProsperCraft/cd55139ba1eb9501571b4cf2b39e24c0

### LINKED ISSUE #2105: 1.12.2 - Builder will not pull things from his buidlers hut chest.
### Minecolonies version

- minecolonies-universal-1.12.2-0.8.7210

### Expected behavior

- Builder takes the items he needs from the builders hut.

### Actual behaviour

I have to take things out of his hut and hand it to him.
The following stacktrace is in the server console - 
- https://gist.github.com/ProsperCraft/d9ddc48d8084907654440aaadb7cc8a2

### LINKED ISSUE #2109: Misbehaving Builder
### Minecolonies version

Minecolonies: 0.8.6934
MC: 1.12.2
forge: 2601

### Expected behavior

The Builder should find most direct path to destination, and should choose a single block as destination, in order to build the current project

### Actual behaviour

The Builder wanders around aimlessly, or gets close to current project, but wanders in the area, sometimes path finding through the area required to actually build, but mostly getting stuck in corners, or on the roof of buildings. (from a non-coders perspective, it seems that the builder tries to find the highest point he/she can along the path, and then climbs, often getting stuck on a roof or tree)

### Steps to reproduce the problem

1. Install proposed versions of applicable mods.
2. Get enough of a colony to have the builder able to build things
*I dont know if level, or type/amounts of buildings matter, but I currently have:
- Town Hall lvl3
- Builder lvl3
- Miner lvl3
- Sawmill lvl3
- Deliveryman lvl1
- Warehouse lvl1
- Currently attempting to upgrade deliveryman to lvl2
3. assign the builder to upgrade a building.

### Extra Notes:

My world was recently corrupted (unrelated to your mod), so I am in creative using the builder's tool to place the colony. I select the lvl1 form of the building and select the left blue icon at the bottom of the screen to have it placed automatically. I then remove the "placeholder blocks" and replace them with grass (via creative mode) and choose to upgrade the building.

Attached is a screenshot of the builder stuck on a tree with the pathfinding display on. but a similar situation happened with other buildings of other levels. but all buildings placed so far have used the same method as outlined above, and most have had at least a small amount of builder related issues.

### PR DESCRIPTION
**Pull request by marchermans**
# Purpose:
- Fixes several problems with the current resolving implementation of the RS.
- Ensures that Priority is now the dominant factor instead of Specificity.
- Moves al RS related data into the DataStore.
- Ensures that when an update of the RS's NBT Data structure is made, an automatic Whipe is triggered. (Missing or not matching NBT Type found -> Reset)
- Prevents the RS from creating duplicate SRRR and SPRR.
- Makes the RS notifiy Requesters and Requestresolvers of cancellations.
- Ensures that when a cancellation happens the Request state is update to cancelled before any action is undertaken. Ensures that Requesters and Resolvers can handle child request cancellations properly (aka rerequests a delivery etc).

# Issues closed
Closes #2109 
Closes #2105 
Closes #2104 
Closes #2101 
Closes #2100

### CODE REVIEW

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/2110/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java [hunk 1]
```diff
@@ -22,11 +22,16 @@
...
+import net.minecraft.nbt.NBTBase;
 import net.minecraft.nbt.NBTTagCompound;
 import org.jetbrains.annotations.NotNull;
 import org.jetbrains.annotations.Nullable;
 
+import javax.naming.spi.Resolver;
 import java.util.Collection;
+import java.util.function.BiFunction;
+import java.util.function.Consumer;
+import java.util.function.Function;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java:34]: MINOR Remove this unused import 'java.util.function.Function'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java [hunk 2]
```diff
@@ -406,71 +380,89 @@ public NBTTagCompound serializeNBT()
...
-        if (nbt.hasKey(NBT_PLAYER))
-        {
-            this.playerResolver = getFactoryController().deserialize(nbt.getCompoundTag(NBT_PLAYER));
-        }
-        else
-        {
-            this.playerResolver = null;
-        }
+        T base;
+        try {
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java:436]: MINOR Move this left curly brace to the beginning of next line of code. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java [hunk 3]
```diff
@@ -62,50 +67,25 @@
...
-     * Constructor for unit tests.
-     */
-    StandardRequestManager()
-    {
-        this.colony = null;
-        this.playerResolver = null;
-        this.retryingResolver = null;
-
-        setup();
+        reset();
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java:88]: CRITICAL Remove this call from a constructor to the overridable "reset" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1699)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java [hunk 4]
```diff
@@ -406,71 +380,89 @@ public NBTTagCompound serializeNBT()
...
+        try {
+            base = extractor.apply(nbt, key);
 
-        if (nbt.hasKey(NBT_RETRYING))
-        {
-            this.retryingResolver = getFactoryController().deserialize(nbt.getCompoundTag(NBT_RETRYING));
-            this.retryingResolver.updateManager(this);
         }
-        else
+        catch (Exception ex)
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java:440]: MAJOR Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java [hunk 5]
```diff
@@ -22,11 +22,16 @@
 import com.minecolonies.coremod.colony.requestsystem.management.handlers.*;
 import com.minecolonies.coremod.colony.requestsystem.management.manager.wrapped.WrappedStaticStateRequestManager;
 import net.minecraft.item.ItemStack;
+import net.minecraft.nbt.NBTBase;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java:25]: MINOR Remove this unused import 'net.minecraft.nbt.NBTBase'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java [hunk 6]
```diff
@@ -406,71 +380,89 @@ public NBTTagCompound serializeNBT()
...
+        executeDeserializationStepOrMarkForUpdate(nbt,
+          NBT_ID_RETRYING,
+          NBTTagCompound::getCompoundTag,
+          c -> retryingRequestResolverId = getFactoryController().deserialize(c));
+
+        updateIfRequired();
+    }
 
-        if (retryingResolver != null)
+    private <T> void executeDeserializationStepOrMarkForUpdate(@NotNull final NBTTagCompound nbt, @NotNull final String key, @NotNull final BiFunction<NBTTagCompound, String, T> extractor, @NotNull final Consumer<T> valueConsumer)
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java:427]: MAJOR Split this 230 characters long line (which is greater than 180 authorized). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00103)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java [hunk 7]
```diff
@@ -22,11 +22,16 @@
 import com.minecolonies.coremod.colony.requestsystem.management.handlers.*;
 import com.minecolonies.coremod.colony.requestsystem.management.manager.wrapped.WrappedStaticStateRequestManager;
 import net.minecraft.item.ItemStack;
+import net.minecraft.nbt.NBTBase;
 import net.minecraft.nbt.NBTTagCompound;
 import org.jetbrains.annotations.NotNull;
 import org.jetbrains.annotations.Nullable;
 
+import javax.naming.spi.Resolver;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java:30]: MINOR Remove this unused import 'javax.naming.spi.Resolver'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java [hunk 8]
```diff
@@ -111,7 +112,7 @@ public static void assignRequest(final IStandardRequestManager manager, final IR
      *
      * @throws IllegalArgumentException is thrown when the request is unknown to this manager.
      */
-    @SuppressWarnings({UNCHECKED,RAWTYPES})
+    @SuppressWarnings({UNCHECKED, RAWTYPES})
     public static IToken<?> assignRequestDefault(final IStandardRequestManager manager, final IRequest request, final Collection<IToken<?>> resolverTokenBlackList)
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java:116]: CRITICAL Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java [hunk 9]
```diff
@@ -1,6 +1,7 @@
 package com.minecolonies.coremod.colony.requestsystem.management.handlers;
 
 import com.google.common.collect.ImmutableCollection;
+import com.google.common.collect.ImmutableList;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java:4]: MINOR Remove this unused import 'com.google.common.collect.ImmutableList'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java [hunk 10]
```diff
@@ -121,86 +122,75 @@ public static void assignRequest(final IStandardRequestManager manager, final IR
...
+                                                                        .get(type)
+                                                                        .stream()
+                                                                        .map(iToken -> ResolverHandler.getResolver(manager, iToken)))
+                                                     .filter(iRequestResolver -> typeIndexList.contains(iRequestResolver.getRequestType()))
+                                                     .sorted(Comparator.comparingInt((IRequestResolver<?> r) -> -1 * r.getPriority())
+                                                               .thenComparingInt((IRequestResolver<?> r) -> typeIndexList.indexOf(r.getRequestType())))
+                                                     .collect(Collectors.toCollection(LinkedHashSet::new));
+
+
+        for (final IRequestResolver<?> resolver : resolvers)
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java:143]: MAJOR Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS135)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/WarehouseRequestResolver.java [hunk 11]
```diff
@@ -57,8 +58,15 @@ public boolean canResolve(@NotNull final IRequestManager manager, final IRequest
             final Colony colony = (Colony) manager.getColony();
             final Set<TileEntityWareHouse> wareHouses = getWareHousesInColony(colony);
             wareHouses.removeIf(Objects::isNull);
-            
-            return wareHouses.stream().anyMatch(wareHouse -> wareHouse.hasMatchinItemStackInWarehouse(itemStack -> requestToCheck.getRequest().matches(itemStack)));
+
+            try
+            {
+                return wareHouses.stream().anyMatch(wareHouse -> wareHouse.hasMatchinItemStackInWarehouse(itemStack -> requestToCheck.getRequest().matches(itemStack)));
+            } catch (Exception e)
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/WarehouseRequestResolver.java:65]: MINOR Move this "catch" keyword to a new dedicated line. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ARightCurlyBraceDifferentLineAsNextBlockCheck)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/WarehouseRequestResolver.java [hunk 12]
```diff
@@ -160,7 +168,9 @@ public void onRequestCancelled(@NotNull final IRequestManager manager, @NotNull
         if (request.hasParent())
         {
             final IRequest parent = manager.getRequestForToken(token);
-            manager.reassignRequest(parent.getToken(), ImmutableList.of());
+
+            if (parent.getState() != RequestState.CANCELLED && parent.getState() != RequestState.OVERRULED)
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/WarehouseRequestResolver.java:172]: CRITICAL Missing curly brace. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00121)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java [hunk 13]
```diff
@@ -370,7 +370,8 @@ public void onOpened()
         createXpBar();
         createSkillContent();
 
-        resourceList.setDataProvider(new ScrollingList.DataProvider() {
+        resourceList.setDataProvider(new ScrollingList.DataProvider()
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java:373]: MAJOR Reduce this anonymous class number of lines from 65 to at most 40, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/UpdateHandler.java [hunk 14]
```diff
@@ -36,4 +36,9 @@ public static void handleUpdate(@NotNull final IStandardRequestManager manager)
               manager.setCurrentVersion(s.updatesToVersion());
           });
     }
+
+    public static int getCurrentVersion()
+    {
+        return steps.stream().max(Comparator.comparing(IUpdateStep::updatesToVersion)).get().updatesToVersion();
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/UpdateHandler.java:42]: MAJOR Call "Optional#isPresent()" before accessing the value. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3655)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 106 issues
* ![CRITICAL][CRITICAL] 10 critical
* ![MAJOR][MAJOR] 66 major
* ![MINOR][MINOR] 26 minor
* ![INFO][INFO] 4 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L303](https://github.com/Minecolonies/minecolonies/blob/305f6ebc75ddb476f064ef2c2a195b35b8427f46/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L303): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuildingView.java#L351](https://github.com/Minecolonies/minecolonies/blob/305f6ebc75ddb476f064ef2c2a195b35b8427f46/src/main/java/com/minecolonies/coremod/colony/buildings/views/AbstractBuildingView.java#L351): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [RequestHandler.java#L88](https://github.com/Minecolonies/minecolonies/blob/305f6ebc75ddb476f064ef2c2a195b35b8427f46/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L88): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [RequestHandler.java#L90](https://github.com/Minecolonies/minecolonies/blob/305f6ebc75ddb476f064ef2c2a195b35b8427f46/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L90): Add a default case to this switch. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ASwitchLastCaseIsDefaultCheck)
1. ![CRITICAL][CRITICAL] [RequestHandler.java#L210](https://github.com/Minecolonies/minecolonies/blob/305f6ebc75ddb476f064ef2c2a195b35b8427f46/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L210): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [WarehouseRequestResolver.java#L143](https://github.com/Minecolonies/minecolonies/blob/305f6ebc75ddb476f064ef2c2a195b35b8427f46/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/WarehouseRequestResolver.java#L143): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![CRITICAL][CRITICAL] [WarehouseRequestResolver.java#L158](https://github.com/Minecolonies/minecolonies/blob/305f6ebc75ddb476f064ef2c2a195b35b8427f46/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/WarehouseRequestResolver.java#L158): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/305f6ebc75ddb476f064ef2c2a195b35b8427f46/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/305f6ebc75ddb476f064ef2c2a195b35b8427f46/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [WindowCitizen.java#L364](https://github.com/Minecolonies/minecolonies/blob/305f6ebc75ddb476f064ef2c2a195b35b8427f46/src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java#L364): Refactor this method to reduce its Cognitive Complexity from 23 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
