### PR TITLE
fix 10894

### LINKED ISSUE #10894: Farmers stuck in loop in the same field forever.
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

minecolonies-1.1.976-1.21.1

### Structurize Version

structurize-1.0.775-1.21.1

### Related Mods and their Versions

Neoforge 21.1.172
blockui-1.0.200-1.21.1
domum-ornamentum-1.0.213

### Current Behavior

Since the recent farmer fix, farmers stay stuck on what seems their furthest field, and are stuck in loop harvesting and planting that one, ignore any other fields.

it's been a week in game, and my level 4 farmer, with 3 fields assigned (onions, durum wheat and garlic), has been looping the garlic field over and over, while both other fields have been fully grown for days. My secondary farmer, level 3, with 3 fields (durum wheat, wheat, tomatoes) has also been on loop on the tomatoes field.

I've been watching my level 4 for a few days with the /mc info command at each step, and it's always FARMER_HARVEST -> INVENTORY_FULL -> PREPARING -> FARMER_PLANT -> INVENTORY_FULL -> Repeat on the same field. If I disable that field, he went straight to continue where he was (no pause) on the durum wheat field, he didn't start harvesting from the middle, but from where he was in the previous field. If I re-enable the garlic field, he will instantly return to that field, stopping his work on the durum.

### Expected Behavior

Should circle the fields when finished with one, and not loop the same one over and over.

### Reproduction Steps

1. Have a farmer level 2 minimum with 2 assigned and working fields, if possible make sure they're fully planted and grown.
2. watch as the farmer goes in loop on one field only, ignore the other one, even after a while in-game week.

### Logs

None needed.

### Anything else?

I tried to fire and re-hire him, I tried to pause and restart his AI, but he keeps doing the same thing. I have to only have 1 field enable when he's done and switch it manually.

What's also weird it it always seem to be field that's the furthest away from their hut, at least for both of mines.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #10894
Closes #

# Changes proposed in this pull request
- Persist current farmer field
- Persist current farmer progress
- Query farmer field by id and only store the id.

## Testing
- [x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/api/colony/buildingextensions/IBuildingExtension.java [hunk 1]
```diff
@@ -108,4 +108,10 @@ public interface IBuildingExtension extends IModuleContainer<IBuildingExtensionM
      * Equals implementation for this building extension.
      */
     boolean equals(Object other);
+
+    /**
+     * Get the unique extension id.
+     * @return the unique id.
+     */
+    int getId();
```
Comment (someaddons) [inline src/main/java/com/minecolonies/api/colony/buildingextensions/IBuildingExtension.java]: I think position makes a better identity than an int we need to keep unique, why not use the blockpos? Its similar to the buildings and building manager

**Review by someaddons — APPROVED** [review]
