### PR TITLE
Handle removing used fuels from furnaces

### LINKED ISSUE #208: the glass cleaner does not take the empty lava bucket out of the furnace, which makes the production last for days
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.4
- MineColonies Version: minecolonies-0.13.482-ALPHA-universal
- Structurize Version: structurize-0.13.100-RELEASE-universal
- Related Mods and their Versions:

## Expected behavior
after the stove stops burning, the worker should take out the empty bucket and put in new fuel

## Actual behavior

the worker does not take out the bucket, so he does nothing and the order waits for days

## Steps to reproduce the issue

set fuel as lava bucket and give im work

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by chandler05**
Closes ldtteam/minecolonies-features#208
Closes #
Closes #

# Changes proposed in this pull request:
- Allow furnace users and smelters to remove used fuel (such as empty buckets) from the furnace's fuel slot
-
-

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java [hunk 1]
```diff
@@ -423,6 +434,31 @@ private BlockPos getPositionOfOvenToRetrieveFrom()
...
+    protected BlockPos getPositionOfOvenToRetrieveFuelFrom()
+    {
+        for (final BlockPos pos : getOwnBuilding().getFurnaces())
+        {
+            final TileEntity entity = world.getTileEntity(pos);
+            if (entity instanceof FurnaceTileEntity)
+            {
+                final FurnaceTileEntity furnace = (FurnaceTileEntity) entity;
+
+                if (furnace.getStackInSlot(FUEL_SLOT).getItem() == Items.BUCKET)
```
Comment (Mekle001) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java]: While bucket is the only 'valid' result today, I can see the possibility of other items in a modded world. This might be better as "if the stack in the slot isn't a valid fuel"

Comment (chandler05) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java:451]: I was wondering if this would be better as "if the stack in the slot isn't an allowed fuel"

Comment (chandler05) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java:451]: So any fuel that is turned off in the GUI will be removed from the fuel slot as well

Comment (Asherslab) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java]: mmm, i believe (not certain) "Lava Cells" from industrial craft 2 would be an example

Comment (chandler05) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java]: OK done.

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java [hunk 2]
```diff
@@ -448,7 +448,7 @@ protected BlockPos getPositionOfOvenToRetrieveFuelFrom()
             {
                 final FurnaceTileEntity furnace = (FurnaceTileEntity) entity;
 
-                if (furnace.getStackInSlot(FUEL_SLOT).getItem() == Items.BUCKET)
+                if (!compareItemStackListIgnoreStackSize(getOwnBuilding().getAllowedFuel(), furnace.getStackInSlot(FUEL_SLOT), false, false) && !furnace.getStackInSlot(FUEL_SLOT).isEmpty())
```
Comment (Mekle001) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java]: Can you do the not empty first? It's a cheaper check, and there is no reason to do the list comparison if the slot is empty

Comment (chandler05) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java]: Yep good point. Done 👍

**Review by Mekle001 — DISMISSED** [review]

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java [hunk 3]
```diff
@@ -534,6 +604,18 @@ private void extractFromFurnace(final FurnaceTileEntity furnace)
         worker.getCitizenExperienceHandler().addExperience(BASE_XP_GAIN);
     }
 
+    /**
+     * Extract fuel from the furnace.
+     *
+     * @param furnace the furnace to retrieve from.
+     */
+    private void extractFuelFromFurnace(final FurnaceTileEntity furnace)
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java]: There seems to be a lot of boilerplate code for this.
Can't we just have an extractFromFurnaceSlot(furnace, slot) as one method instead of two seperate ones?

Comment (chandler05) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java]: The AbstractEntityAIUsesFurnace requires extractFromFurnace to be defined by each individual class, while the extractFuelFromFurnace is defined for all extension classes in the main one.

But I could do this in the RequestSmelter class

Comment (chandler05) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java]: Ok, I've combined the functions in the AbstractEntityAIRequestSmelter class but left it alone in the AbstractEntityAIUsesFurnace class

**Review by Raycoms — APPROVED** [review]

**Review by Mekle001 — APPROVED** [review]

**Review by someaddons — APPROVED** [review]

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java [hunk 4]
```diff
@@ -522,16 +558,53 @@ private IAIState retrieveSmeltableFromFurnace()
...
     {
         InventoryUtils.transferItemStackIntoNextFreeSlotInItemHandler(
-          new InvWrapper(furnace), RESULT_SLOT,
+          new InvWrapper(furnace), slot,
           worker.getInventoryCitizen());
-        worker.getCitizenExperienceHandler().addExperience(BASE_XP_GAIN);
+        if(slot == RESULT_SLOT)
+        {
+            worker.getCitizenExperienceHandler().addExperience(BASE_XP_GAIN);
+        {
```
Comment (uecasm) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java:607]: wat

Comment (chandler05) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java:607]: I combined the functions for extracting from a furnace slot for both the fuel and result slots, and I changed it so experience would only be rewarded if an item was taken from the result slot as none should be rewarded from the fuel slot.

Comment (uecasm) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java:607]: No, my point was that this doesn't even compile, since the wrong brace was used.

Comment (chandler05) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java:607]: I have no idea how that snuck by. I even tested it on my computer and it compiled fine. I fixed it in another PR.
