### PR TITLE
Fix/archer pos

### LINKED ISSUE #6179: stone smelter or smelter
- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.482
- Structurize Version: 0.13.100
- Related Mods and their Versions:

build tool offers choice of both smelter and stone smelter.  

### Logs

- latest.log: https://gist.github.com/Moobien/728375f614647c1cb120274eb88fb968
- crashlog: 
-imgur links: https://imgur.com/a/HreQkkc
### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #6179

# Changes proposed in this pull request:
- Improved archer positioning to not leave the wall/tower all the time
- Fixes issue of stonesmeltery appearing with smeltery
-

Review please

### CODE REVIEW

**Review by Mekle001 — APPROVED** [review]

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java [hunk 1]
```diff
@@ -553,21 +553,33 @@ private double getAimHeight()
...
+    {
+        return buildingGuards.getTask() == GuardTask.GUARD || (buildingGuards.getTask() == GuardTask.PATROL && buildingGuards.shallPatrolManually());
     }
 
     @Override
     public void guardMovement()
     {
+        if (worker.getRandom().nextInt(3) < 1)
+        {
+            worker.isWorkerAtSiteWithMove(buildingGuards.getGuardPos(), 3);
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java:579]: what is this supposed to do?

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java:579]: Atm, there is a problem that the archer, stays a very long time, far away from the actual guarding spot. This should balance out that regularly the archer returns to the initial guarding spot and then from there walk a little bit again.

Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java:579]: ok

**Review by someaddons — APPROVED** [review]

**Review by marchermans — APPROVED** [review]
