### PR TITLE
Fix/warehouse issue

### LINKED ISSUE #10208: [BUG] The warehouse is still taking items from other warehouses to fulfill requests.
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.660

### Structurize Version

1.20.1-1.0.742

### Related Mods and their Versions

Minecolonies Offical WinterColonies-1.11

### Current Behavior

https://youtu.be/xSeGljUcBzw
The warehouse is still requesting items from other warehouses to deliver them elsewhere.
(Please only watch the beginning and the end of the video.)

### Expected Behavior

Ensure that the warehouse containing the requested item fulfills the request directly.

### Reproduction Steps

Build two warehouses and create multiple requests to test the behavior?

### Logs

No crash

### Anything else?

Additionally, I'm not sure if I remember correctly, but I seem to recall seeing in a previous update that warehouses now distribute tasks on their own rather than assigning everything to the nearest one. However, I sometimes still see one warehouse overloaded with tasks while the couriers from the other warehouse are idling. I'm not sure if this is normal, so I'm just mentioning it here. Since building two warehouses, the workload usually isn't high enough to keep the couriers too busy.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #10208
Closes #

# Changes proposed in this pull request
- Fix warehouse accepting task it has no items for
-

## Testing
- [x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/core/tileentities/TileEntityWareHouse.java [hunk 1]
```diff
@@ -91,6 +91,32 @@ public int getCountInWarehouse(@NotNull final ItemStorage storage, int count)
         return totalCount;
     }
 
+    @Override
+    public int getCountInWarehouse(@NotNull final Predicate<ItemStack> predicate, int count)
```
Comment (someaddons) [inline src/main/java/com/minecolonies/core/tileentities/TileEntityWareHouse.java]: why is this within the warehouse tileentity? Since it just forwards to the building we should use the building directly, also alleviating the need to load/loaded check on the TE to begin with

Comment (someaddons) [reply src/main/java/com/minecolonies/core/tileentities/TileEntityWareHouse.java]: could probably even use pre-existing generic building get count inventoryutils functions instead

File: src/main/java/com/minecolonies/api/util/InventoryUtils.java [hunk 2]
```diff
@@ -791,7 +787,7 @@ public static int hasBuildingEnoughElseCount(@NotNull final IBuilding provider,
                     totalCount += ((TileEntityRack) entity).getItemCount(stack);
                 }
 
-                if (totalCount > count)
+                if (totalCount >= count)
```
Comment (someaddons) [inline src/main/java/com/minecolonies/api/util/InventoryUtils.java:790]: nice find

**Review by someaddons — DISMISSED** [review]
