### PR TITLE
Delivery orders

### LINKED ISSUE #5811: Tavern Visitors falling through world
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version: 0.13.268
- Structurize Version:0.13.64
- Related Mods and their Versions:

## Actual behavior

image

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

issue has been ongoing through a few versions.

Update (22.09.2020): so it seems that even though the message appears it doesn't actually happen?
I got one 5 minutes ago saying Marion W. Chestor fell though the world but whilst I was wondering around my town at night i found her creeping like Ghost - she's not recruitable however 
image

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #5923: barbarians spawned 10blocks from town hall at the center of colony within borders
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies official and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any current existing issue. It was in the past**

It is Minecolonies-Official-1.15.2-v2.9 - minecolonies-0.13.328-ALPHA-universal and structurize-0.13.94-ALPHA-universal

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #5927: 1.15.2 Visitor entity set to zero pos, Condition check for transition
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.349-ALPHA
- Structurize Version: 0.13.94-ALPHA
- Related Mods and their Versions:  https://gist.github.com/piesio98/800e10e633d96baa1fbb324c119cabaa

## Expected behavior
no spam

## Actual behavior
spam in console with:

Condition check for transition com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickingTransition@1c124242 threw an exception:
java.lang.NullPointerException: null ...

and

Visitor entity set to zero pos, report to mod author:
java.lang.Exception: null ....

## Steps to reproduce the issue

none 

### Logs

- latest.log: https://gist.github.com/piesio98/3b9c5c6a6081004ad8d57afe5a52c1dc
- crashlog: none

### Notes

This creates lag spikes.

I know that this issue was posted before (#5898 , #5002) but my is without crash and with additional error code.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by someaddons**
Closes #5927
Closes #5923
Closes #5811

# Changes proposed in this pull request:
This adapts the way deliveries are assigned to deliveryman to a multi-factor comparison system.
The resolver for dmen now resides in a warehouse and resolves the request it gets to its delivermen in our case those of a single warehouse. So now we compare all assigned deliverymen of a warehouse to get the best fit for the request.
The resolver now ask the dmen for a score for adding a certain request and then compares the score to other dmen's scores. The score(lower is better) itself is combined of these factors:

- Closeness: How close the target/source of the new request is compared to an existing one, in relation to its total travel length.
- Priority(also contains age): Overtaking a request of a higher priority is worse.
- Pickup/Delivery alternating: When alternating between pickups and deliveries with close targets the score gets a little bonus.
- Index: The index we would add the new request at, higher the more request we overtake and the more request we have in total.

These result in lists on deliverymen of approx ~3 times closer deliveries, allowing the AI to also bunch up deliveries more nicer in the future.

Fixes visitors sometimes getting spawn on zero pos.
Fix raids not respecting distance to unloaded buildings
Fix shipsraids sometimes instantly despawning after killing spawners, now takes a day to do so.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/jobs/JobDeliveryman.java [hunk 1]
```diff
@@ -460,6 +456,209 @@ private boolean haveTasksSameSourceAndDest(@NotNull final Delivery requestA, @No
...
+     * Gets the right task insertion order for pickups, if a new request fitting an existing request is added and the existing is a pickup and the new is a delivery it should be
+     * infront.
+     *
+     * @param newRequest the new request to add
+     * @param existing   the existing request
+     * @return 1 for inserting after existing, 0 for infront
+     */
+    private int getPickupOrRequestOffset(final IRequest<?> newRequest, final IRequest<?> existing)
+    {
+        if (newRequest.getRequest() instanceof Delivery && existing.getRequest() instanceof Pickup)
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/colony/jobs/JobDeliveryman.java:548]: those all look like static utility methods?

Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/colony/jobs/JobDeliveryman.java:548]: true some don't require internal data

**Review by Mekle001 — DISMISSED** [review]

File: src/api/java/com/minecolonies/api/util/BlockPosUtil.java [hunk 2]
```diff
@@ -352,6 +352,22 @@ public static int getMaxDistance2D(@NotNull final BlockPos block1, @NotNull fina
...
     }
 
+    /**
+     * Gets the actual distance in blocks between two positions
+     *
+     * @param pos1 Blockpos 1
+     * @param pos2 Blockpos 2
+     * @return distance in blocks.
+     */
+    public static double getDistance(final BlockPos pos1, final BlockPos pos2)
```
Comment (marchermans) [inline src/api/java/com/minecolonies/api/util/BlockPosUtil.java:362]: There is a method on the blockpos todo this.

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/DeliveryRequestResolver.java [hunk 3]
```diff
@@ -47,159 +22,22 @@ public DeliveryRequestResolver(
...
-        if (manager.getColony().getWorld().isRemote)
-        {
-            return false;
-        }
-
-        final Colony colony = (Colony) manager.getColony();
-        final IWareHouse wareHouse = colony.getBuildingManager().getClosestWarehouseInColony(requestToCheck.getRequester().getLocation().getInDimensionLocation());
-        if (wareHouse == null)
+        final IWareHouse wareHouse = manager.getColony().getBuildingManager().getClosestWarehouseInColony(requestToCheck.getRequest().getStart().getInDimensionLocation());
+        if (wareHouse == null || !wareHouse.getID().equals(getLocation().getInDimensionLocation()))
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/DeliveryRequestResolver.java:29]: This won't work.
Deliveries are not requests solely by a warehouse, but can be requested by any worker.

**Review by marchermans — CHANGES_REQUESTED** [review]
Conceptually a good idea, implementation is not covering all current cases though.
Missing deliveries from other none warehouse buildings primarily. In its current case this will break any crafting worker, since results can not be delivered from him to his requester,

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/DeliveryRequestResolver.java (hunk 3 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/DeliveryRequestResolver.java:29]: Ye, that just means that the warehouse closest to the delivery position in in charge for a delivery (in particular the deliveryman around that area)

**Comment by someaddons** [comment]
The resolver itself is actually warehouse agnostic and only depends on the list of delivermen it gets fed. It just happens that by default the deliverymen from the closest warehouse are responsible for the delivery. So any to any deliveries do work but happen to be solved by the dmen of the closest warehouse

File: src/api/java/com/minecolonies/api/util/BlockPosUtil.java (hunk 2 above)
Comment (someaddons) [reply src/api/java/com/minecolonies/api/util/BlockPosUtil.java:362]: I thought that aswell, but was and still am unable to find any :D I only see a square one

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/DeliveryRequestResolver.java (hunk 3 above)
Comment (marchermans) [reply src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/DeliveryRequestResolver.java:29]: Arg it does getClosestWarehouse´

Okey.

**Review by marchermans — APPROVED** [review]
