### PR TITLE
Several miner fixes

### LINKED ISSUE #6579: Miner doesn't mine shaft down
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**
Issue exists but couldn't find a valid solution

### Context 

What I have tried to resolve:

recall miner
restart miner
repair building
remove the entire building/shaft with cobble and rebuild the mine

All of the above but in a different location in my world

Mine level 1
Worker level 5

Worker inventory: see attachment

minecraft 1.16.5 (All the Mods 6)
minecolonies 0.13.620-ALPHA -> upgraded from 0.13.596-ALPHA

although I noticed the issue also presented itself on numerous other versions that were RELEASE and not alpha and also on a different modpack

Am I missing something?

Anyway, thanks for the great mod, lad(s). truly one of the best mods out there

miner inventory
miner inventory

### Logs

- latest.log: 

## Steps to reproduce the issue / details

Build the miner I guess lol.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #7298: [1.16] Crashed while opening mystical site build options UI
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

Open Build options in mystical site

## Actual behavior

Crashed while opening build options

## Steps to reproduce the issue

1. Open UI
2. Click Build options
3. Crash

### Logs

- latest.log: 
- crashlog: https://gist.github.com/DarkGuardsman/6c312120fdd7105371e8ea96a8b78c20

### Notes

Creative build the site shortly before. Saw it show two messages for claimed chunks.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #7302: Minecolonies: Builders tape not removed after completion and sometimes appears one block farther out than expected
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.235-ALPHA
- Structurize Version: 0.13.192-ALPHA
- Related Mods and their Versions: n/a

## Expected behavior

When the builder completes upgrading a building the builders tape is removed. Also, the builders tape should appear one block outside of the building's boundary.

## Actual behavior

When the builder has completed constructing a building, the building tape is not removed. Also, the builder's tape appears one block further away from the building's boundary than expected. The image shows the placement of the builder's tape around the Caledonia Style Mechanic hut and is one block larger than expected. The tape should be placed adjacent to the cobblestone border. 

## Steps to reproduce the issue

1. Have the builder upgrade an existing hut.
2. The Builders tape appears 1 block farther out than expected from the building's border.
3. When the builder completes, the builder's tape remains in place.

### Logs

- latest.log: https://gist.github.com/kedamono/b50abd9631604519c302d2df2fd2e95c
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #7312: Cook gets swamped by citizens, cant get to their station.
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:0.14.231-ALPHA-universal
- Structurize Version:0.13.177-ALPHA-universal
- Related Mods and their Versions: ATM6 modpack v 1.6.11

## Expected behavior
Cooks and assistant cooks making food at their designated work area. Citizens walking in, receiving food from the cook and then consuming it. Multiple restaurants should draw citizens nearest to them to share the workload.

## Actual behavior
When cooks go to sleep and try to return in the morning they find a mass of soldiers and other citizens there waiting for food unable to get to their cooking area. They get stuck behind other citizens and cant cook or make food. Recalling doesnt seem to help much cause they get pushed aside again by all the citizens wanting to occupy that one space in front of the cook block.
Also several restaurants dont work cause they all seem to go to the cook that was built last.
Might be an AI issue as well but im unsure, anyways, here is a pic i took.

image

## Steps to reproduce the issue

1. Build a large city with working food chains and production chains etc.
2. Make sure you have at least one working level 3-5 restaurant with food and wait for the night or just dont hire any cooks untill villagers start to show up demanding food.
3. Hire a Cook and assistant cook and wait for the morning. The cooks will try to come to work and start distributing food but are unable to get to their stations due to the increasing numbers of clientele blocking them. They dont seem to go home for rest either while cooks do. 

### Logs

- latest.log: https://gist.github.com/starfall18/1d6622ef6a5be8b22d46eb5a84cac542
- crashlog: 

### Notes
The assistant cooks constantly seem to also have issues about getting to their workplace altogether. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #6579
Closes #7312
Closes #7302 
Closes #7298

Changes proposed in this pull request:
- Several miner fixes
- Moves ladder/cobble detection to tags instead of hacky search
- Code cleanup of the ladder/cobble handling
- Add way to recover missing tag data from building
- Solve issue with requests stuck as minimum stock
- Solve miner issues with weird requests

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java [hunk 1]
```diff
@@ -512,27 +418,32 @@ public void setVectorZ(final int vectorZ)
...
-    /**
-     * Setter of the shaftStart.
-     *
-     * @param pos the location.
-     */
-    public void setShaftStart(final BlockPos pos)
+    private void loadLadderPos()
     {
-        this.shaftStart = pos;
+        final Set<BlockPos> cobblePos = tileEntity.getWorldTagNamePosMap().get("cobble");
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java]: isnt it easier to keep the map var and check on that? also you'll get null values when it doesnt exist, its a hashmap

**Review by marchermans — APPROVED** [review]

**Review by someaddons — APPROVED** [review]
