### PR TITLE
Fix research cost list serialization in network buffers

### LINKED ISSUE #9631: [BUG] [1.19.2] Invalid Player Data - Cannot Login to Dedicated Server
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.370

### Structurize Version

1.19.2-1.0.665-BETA

### Related Mods and their Versions

Forge: 43.3.5

### Current Behavior

Getting an error "Invalid Player Data" when attempting to login to a dedicated server. Also noticed, during server start that Minecolonies updated from backup several times during start up.

Error seems related to the request system?

Included log is from dedicated server, from startup till the login error. Nothing meaningful on the client side, but can include that if requested.

### Expected Behavior

Able to login normally, and not restoring from backup.

### Reproduction Steps

Assume just updating and trying to login to a dedicated server will do it.

### Logs

https://gist.github.com/Sandriell/4f0c6eb68532f75a75832534a8f28795

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Thodor12**
- Closes #9631 

# Changes proposed in this pull request:
- Fix issues surrounding cost serialization to network buffers (and NBT)

[X] Yes I tested this before submitting it.
[X] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/research/costs/ListItemCost.java [hunk 1]
```diff
@@ -82,6 +90,29 @@ public void write(@NotNull final CompoundTag compound)
...
     }
 
+    @Override
+    public void serialize(final @NotNull FriendlyByteBuf buf)
+    {
+        buf.writeInt(this.count);
+        buf.writeInt(this.items.size());
+        for (final Item item : this.items)
+        {
+            buf.writeItem(new ItemStack(item));
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/research/costs/ListItemCost.java]: since items are also in a registry we could just write their ID right, similar to how you did it for the costtype

**Review by someaddons — APPROVED** [review]
