### PR TITLE
Fix library issues and gracefully handle building with missing blueprint

### LINKED ISSUE #7021: Library students not gaining intelligence when housed in a tavern
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.129-ALPHA
- Structurize Version: 0.13.167-ALPHA
- Related Mods and their Versions: N/A

## Expected behavior
Library students should be able to level up past Intelligence lv 6 if they are housed in a level 3 tavern. 

## Actual behavior
Library students are stuck at the same intelligence level forever despite using up paper and books and living in a level 3 tavern.

## Steps to reproduce the issue

1. Build a level 3 tavern and a level 2 library
2. Assign a colonist with low intelligence level (but greater than 5) to the library and tavern
3. Give the colonist plenty of books and paper
4. Wait several in game days as intelligence level remains the same low level

### Logs

- latest.log: 
- crashlog: 

### Notes
I am using manual assignment for housing and jobs in my colony. Not sure if this influences calculation of housing level or not, but I'm pretty sure it's just an issue with the library. Also the actual library block was placed by a builder as part of the True Dwarven University complex. Doubt this is part of the problem though.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #7343: Crafters get stuck when insufficient materials for a crafting request are available in their hut
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.256-ALPHA
- Structurize Version: 0.13.197-ALPHA
- Related Mods and their Versions:

## Expected behavior
This issue may or may not be related to #7320, as it shares some similarities.  The issue I reported there has been resolved, as far as I can tell.  It's been difficult to pin this one down exactly, but this is what I know:

* A request is made for a crafter to make one of their recipes by another colonist.
* The crafter is found stuck in a loop - they move between their hut and a work station in their building continuously.  No work is done - crafting or their normal job (if applicable.)
* When at the hut block, they transfer materials from the hut inventory needed to craft the request, but there is not enough to craft everything.  They then put the materials back and loop again.  Materials are available in warehouse, and I believe enough were delivered by the couriers initially.  It's unclear why the materials went missing (see below.)
* No request is ever generated to get additional materials - even when they are available in the warehouse.
* If the player manually gives them the needed materials, they craft the recipe and the issue resolves.

3 Specific cases I observed:
* Stonemason crafting stone into stone bricks (to resolve request from a builder.)  
* Not enough stone (not sure how this happened - they had crafted dozens of stacks of bricks before with no issues)- they started the loop.  
* I manually gave them stone - they finished the request and resumed normal operation.
* A stone smelter was available to make the stone, and lots of cobblestone was in the warehouse.  And from this point forward, all stone brick requests resolved normally, even when stone had to be smelted - just as you would expect.  So it's not every time.

* Planter crafting books on plantation (to resolve request from library:)
* Not enough sugar cane for the paper - they started the loop.
* I manually gave them sugar cane - request completed, things got back to normal.

* Assistant cook found stuck in this loop, and not crafting any food recipes.  Plenty of food ingredients in warehouse, but no finished products - many hungry colonists.
* resolved by manually giving them the raw ingredients
* They resumed normal operation from there on - requests to get stock from warehouse resumed working normally.

This is not happening every time, and I'm having a hard time figuring out how to manually trigger it consistently.  This colony is highly automated, and the entire supply chain is normally done automatically by the colonists without my intervention.  But I think it has something to do with couriers removing crafting supplies from the hut AFTER they are delivered but BEFORE the crafting request is complete.  I did see them remove potatoes from the restaurant that were needed for a "fish and chips" recipe after I manually delivered them.  Maybe the couriers can't always differentiate materials that need to stay, vs. the extras that need to go to warehouse?  At least under specific circumstances?

## Actual behavior
Crafting stops when insufficient materials are in the hut, no request to resolve is generated, and worker stops doing anything productive.  I would expect a new request to be generated to supply them again.  No request for player resolution ever shows up on clipboard.

## Steps to reproduce the issue

Doesn't reproduce every time, but grabbing crafting materials from the hut will sometimes break things.  I can't identify the exact automated process that's breaking, beyond suspecting the couriers.

Let me know if you need more info.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #7343
Closes #
Closes #

# Changes proposed in this pull request:
- Rework the library level up calc.
- Gracefully handle buildings with missing blueprints
-

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractSchematicProvider.java [hunk 1]
```diff
@@ -377,20 +378,30 @@ protected void updateTEDataFromSchematic()
...
-            saveUpdateTEDataFromSchematic(te);
+        }
+
+        try
+        {
+            unsaveUpdateTEDataFromSchematic(te);
+        }
+        catch (final Exception ex)
+        {
+            Log.getLogger().warn("Building with invalid data, setting building as deconstructed.");
```
Comment (uecasm) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractSchematicProvider.java]: Not true after the last edit. :)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/student/EntityAIStudy.java [hunk 2]
```diff
@@ -129,7 +129,7 @@ private IAIState study()
             final StudyItem chosenItem = currentItems.get(world.rand.nextInt(currentItems.size()));
 
             worker.setHeldItem(Hand.MAIN_HAND, new ItemStack(chosenItem.getItem(), 1));
-            data.getCitizenSkillHandler().tryLevelUpIntelligence(world.rand, ONE_IN_X_CHANCE * (100 / chosenItem.getSkillIncreasePct()), data);
+            data.getCitizenSkillHandler().tryLevelUpIntelligence(world.rand, (ONE_IN_X_CHANCE * (100.0 / chosenItem.getSkillIncreasePct())), data);
```
Comment (uecasm) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/student/EntityAIStudy.java]: The extra parens are not needed.

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractSchematicProvider.java (hunk 1 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractSchematicProvider.java]: Leftover from int cast attempt =D

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/student/EntityAIStudy.java (hunk 2 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/student/EntityAIStudy.java]: Leftover from int cast attempt =D

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractSchematicProvider.java (hunk 1 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractSchematicProvider.java]: No need to warn if we warn the players directly too.

**Review by uecasm — DISMISSED** [review]

**Review by marchermans — DISMISSED** [review]

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractSchematicProvider.java [hunk 3]
```diff
@@ -366,7 +367,7 @@ public int getRotation()
     /**
      * Load updated TE data from the schematic if missing.
      */
-    protected void updateTEDataFromSchematic()
+    protected void saveUpdateTEDataFromSchematic()
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractSchematicProvider.java]: isnt it safe not save?^^

File: src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/BuildPickUpMessage.java [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+    {
+
+    }
+
+    @Override
+    public void onExecute(final NetworkEvent.Context ctxIn, final boolean isLogicalServer, final IColony colony, final IBuilding building)
+    {
+        final PlayerEntity player = ctxIn.getSender();
+        building.pickUp(player);
+        for (final BlockPos childPos : building.getChildren())
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/BuildPickUpMessage.java]: we got some buildings of which you arent supposed to obtain a hutblock

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 5]
```diff
@@ -151,12 +153,20 @@ public WindowBuildBuilding(final IColonyView c, final IBuildingView building)
...
         }
     }
 
     /**
-     * When the move building button has been clicked.
+     * When the pickup building button was clicked.
+     */
+    private void pickUpBuilding()
+    {
+        Network.getNetwork().sendToServer(new BuildPickUpMessage(building));
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java:165]: probably should close the UI here

File: src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/BuildPickUpMessage.java (hunk 4 above)
Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/BuildPickUpMessage.java]: actually this might be a bad idea anyways, those blocks are integrated into the main buildings and are never meant to be seperated as having seperate blocks with level would do

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/student/EntityAIStudy.java [hunk 6]
```diff
@@ -129,7 +129,7 @@ private IAIState study()
             final StudyItem chosenItem = currentItems.get(world.rand.nextInt(currentItems.size()));
 
             worker.setHeldItem(Hand.MAIN_HAND, new ItemStack(chosenItem.getItem(), 1));
-            data.getCitizenSkillHandler().tryLevelUpIntelligence(world.rand, ONE_IN_X_CHANCE * (100 / chosenItem.getSkillIncreasePct()), data);
+            data.getCitizenSkillHandler().tryLevelUpIntelligence(world.rand, ONE_IN_X_CHANCE * (100.0 / chosenItem.getSkillIncreasePct()), data);
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/student/EntityAIStudy.java]: I'd use 100d instead

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java [hunk 7]
```diff
@@ -438,7 +438,7 @@ private void loadLadderPos()
         final Set<BlockPos> ladderPos = map.getOrDefault("ladder", new HashSet<>());
         if (cobblePos.isEmpty() || ladderPos.isEmpty())
         {
-            updateTEDataFromSchematic();
+            saveUpdateTEDataFromSchematic();
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java]: just noticing now, but incase we got a bad schematic with missing data this would reload-spam all day long

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractSchematicProvider.java (hunk 3 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractSchematicProvider.java]: the save one won't throw an exception, the other one will throw an exception

File: src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/BuildPickUpMessage.java (hunk 4 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/BuildPickUpMessage.java]: kk

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java (hunk 7 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingMiner.java]: Will make it a seperate PR after lunch
