### PR TITLE
Performance improvement TEs

### LINKED ISSUE #5382: Can't rotate when placing a building/decoration near another building/decoration.
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version:  0.13.29-ALPHA

### Expected behavior

- When placing a building, I should be able to use the rotate button to rotate the building.

### Actual behaviour

      
- When placing the building near another building (i.e. blue guidelines appear and level 5 ghost image is shown on already built building) the rotate buttons don't rotate the building, it seems to just move the current rotation.  

### Steps to reproduce the problem

1. Build a building
2. Try and place another building/decoration neat but not overlapping, then attempt to rotate it
3. It goes a bit bonkers and doesn't rotate, but just displaces.
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
- crashlog:

### LINKED ISSUE #5402: Guard AI error
Version: minecolonies-0.13.43-alpha

### Expected behavior
No AI error

### Actual behaviour
Guard has an AI error:
[minecolonies/]: Statemachine for transition com.minecolonies.api.entity.ai.statemachine.AITarget@65e7a47c threw an exception:
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.Arrays$ArrayList.get(Arrays.java:3841) ~[?:1.8.0_252]
	at net.minecraft.util.NonNullList.get(SourceFile:46) ~[?:?]
	at com.minecolonies.api.inventory.InventoryCitizen.getStackInSlot(InventoryCitizen.java:244) ~[?:0.13.43-ALPHA]
	at com.minecolonies.api.inventory.InventoryCitizen.getHeldItem(InventoryCitizen.java:115) ~[?:0.13.43-ALPHA]
	at com.minecolonies.coremod.entity.citizen.citizenhandlers.CitizenItemHandler.damageItemInHand(CitizenItemHandler.java:231) ~[?:0.13.43-ALPHA]
	at com.minecolonies.coremod.entity.ai.citizen.trainingcamps.EntityAICombatTraining.attack(EntityAICombatTraining.java:202) ~[?:0.13.43-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[?:0.13.43-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148) ~[?:0.13.43-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:134) ~[?:0.13.43-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126) ~[?:0.13.43-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:105) ~[?:0.13.43-ALPHA]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:127) ~[?:0.13.43-ALPHA]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?]
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:368) ~[?:1.15-2.11m]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:1307) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159) ~[?:?]
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:390) ~[?:0.13.43-ALPHA]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:536) [?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

### Steps to reproduce the problem
No idea

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log: https://gist.github.com/MatthiasMann/e15d7937a26051ea3025739af1414558

### LINKED ISSUE #5420: Warehouse Racks are twitching/not recognised
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: minecolonies-0.13.53-ALPHA-universal.jar
             structurize-0.13.19-ALPHA.jar
             Fortress Style

### Expected behavior

- Racks should connect in pairs of two, be all visible and recognized by the DelMan 

### Actual behaviour

- The Racks connect to each other every time you click one of them (first to the left, then to the right)
- Some Racks get invisible if you click another one
- Some Racks are not accessible for the Deliveryman (Tools/Items can not be requested if they are in that Rack)
- If the accessible Slots are full, the DelMan get stuck without the Prompt "Warehouse full"

I tried:
- Rebuild the Racks per hand: Visible and connected OK, but not all accessible
- Remove Racks and then let the Builder repair the WH: same as before

### Steps to reproduce the problem

1. Build Warehouse Fortress (Lvl 1 or 2) 
2. Let the Racks be filled 
3. Click the Racks and check which are empty 

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/MerlinplaysGames/708ee17ffe6ed7ad0f4e4a87941a9800 
- crashlog:

### LINKED ISSUE #5431: Lumberjack stuck searching for trees
Version: 0.13.59

### Expected behavior
Expected for the lumber jack to break the leaves so he can get to the tree trunk and start cutting it down.

### Actual behaviour
He bumps his head furiously in them hoping that they will give up and let him do his job. Basically he just sits around the trees unable to get to the trunk unless you break the leaves for him to get closer and it says when you click on him that he is looking for trees.

I should mention that this is happening in a spruce forest.

### Steps to reproduce the problem

1. Build the hut
2. Supply an axe
3. Watch him fail miserably 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/Dulap3/1c274db3601e69a37531de337eea0c39

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #5402
Closes #5420
Closes #5382
Closes #5431 

# Changes proposed in this pull request:
- Use our own dirty setting mechanic for our tileEntities.
- Vanilla causes a lot of stuff because of comparator output updates we don't need
-

Review please

### CODE REVIEW

File: src/api/java/com/minecolonies/api/blocks/AbstractBlockBarrel.java [hunk 1]
```diff
@@ -24,6 +24,10 @@ public AbstractBlockBarrel(final Properties properties)
 
     public static BlockState changeStateOverFullness(@NotNull final AbstractTileEntityBarrel te, @NotNull final BlockState blockState)
     {
+        if (blockState.getBlock() != ModBlocks.blockBarrel)
+        {
+            return blockState;
+        }
```
Comment (marchermans) [inline src/api/java/com/minecolonies/api/blocks/AbstractBlockBarrel.java]: If this logic should only work for the Barrel block, then this needs to be moved to its override, instead of this if-switch being here.

File: src/api/java/com/minecolonies/api/inventory/InventoryCitizen.java [hunk 2]
```diff
@@ -235,6 +235,10 @@ public boolean hasCustomName()
     @Override
     public ItemStack getStackInSlot(final int index)
     {
+        if (index == NO_SLOT)
```
Comment (marchermans) [inline src/api/java/com/minecolonies/api/inventory/InventoryCitizen.java:238]: What is NO_SLOT?
The contract specifies that index needs to be between 0 and at most the count of slots.

**Review by marchermans — DISMISSED** [review]
Some nitpicking

File: src/api/java/com/minecolonies/api/inventory/InventoryCitizen.java (hunk 2 above)
Comment (Raycoms) [reply src/api/java/com/minecolonies/api/inventory/InventoryCitizen.java:238]: This happens when the heldItemSlot = -1, should I move this in the getHeldItem instead?

File: src/api/java/com/minecolonies/api/blocks/AbstractBlockBarrel.java (hunk 1 above)
Comment (Raycoms) [reply src/api/java/com/minecolonies/api/blocks/AbstractBlockBarrel.java]: done

**Review by someaddons — APPROVED** [review]
