### PR TITLE
Fix #5880

### LINKED ISSUE #5880: Stonemason won't craft stone bricks
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.318-alpha
- Structurize Version: 0.13.91-alpha
- Related Mods and their Versions:
- Singleplayer

## Expected behavior
Stone mason will craft stone bricks when requested

## Actual behavior
Stone mason gets stone delivered (stored in hut block), the task view (2nd page of the hut block) shows for a brief moment the task to craft stone bricks for my builder and then the task vanishes again without having done any crafting.

## Steps to reproduce the issue
1. The stone mason last worked in 0.13.293
2. He improved the stone -> stone bricks recipe twice - now it only needs 2 stones to craft 4 stone bricks
3. Then I updated to 0.13.318 (I also tried 0.13.302 which had other issues so I rolled back to a backup of my world and tried today with 0.13.318 again).
4. Now the stone mason seems to be broken
5. I did restarts, fire&hire, RS resets, cancelled the requests for the 123 stone bricks several time - nothing got the stone mason working.

### Logs
I looked in both debug.log and latest.log and there are no debug messages or error messages from Minecolonies - only the messages I saw in the chat from resetting the RS or restarting the stone mason.

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Mekle001**
Closes #5880 

# Changes proposed in this pull request:

I *finally* found the root cause of these issues with some help from @Raycoms 

This PR tweaks inventory handling in addition to removing the old one-stack crafting limitation that was causing #5880 to happen. 

Review please

### CODE REVIEW

File: src/api/java/com/minecolonies/api/util/CraftingUtils.java [hunk 1]
```diff
@@ -55,23 +55,7 @@ public static int calculateMaxCraftingCount(@NotNull final ItemStack outputStack
...
-            {
-                //Recalculate the crafting limit using the maxstacksize of the ingredient.
-                craftingCount = Math.max(ingredient.getMaxStackSize(), ItemStackUtils.getSize(storage.getPrimaryOutput())) / ItemStackUtils.getSize(storage.getPrimaryOutput());
-            }
-        }
-
-        return craftingCount;
+        //Calculate the crafting count from the request and the storage output.
+        return (int) Math.ceil(Math.max(count, ItemStackUtils.getSize(storage.getPrimaryOutput())) / (double) ItemStackUtils.getSize(storage.getPrimaryOutput()));
     }
```
Comment (Raycoms) [inline src/api/java/com/minecolonies/api/util/CraftingUtils.java:60]: We used to have it to avoid subrequests < 64 items. We removed the limitations in other places but not here which caused some weird bugs. @OrionDevelopment

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/5957/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Review by marchermans — APPROVED** [review]
