### PR TITLE
Idle&foresterfix

### LINKED ISSUE #11096: Forester doesn't do their job
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.1006-snapshot

### Structurize Version

1.20.1-1.0.780-snapshot

### Related Mods and their Versions

_No response_

### Current Behavior

Forester is constantly stuck at in a state of "START_WORKING", and just hangs around the forester hut block. Downgrading to .995 fixes the issue, so it suggests something between then and this version did something.

### Expected Behavior

He's supposed to be cutting down trees and doing work.

### Reproduction Steps

1. Get a forester (Mine is level 3) and plant some trees around their hut block.
2. Watch as they stare very very hard at their forester hut block. And then do nothing.

### Logs

https://pastebin.com/XU4YLfSa

### Anything else?

Like said above, downgrading to .995 fixes the issue for now.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #11096 
Closes #

# Changes proposed in this pull request
- Forester fix
- Only leisure if not super busy right now

## Testing
- [ ] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

**Review by someaddons — APPROVED** [review]

File: src/main/java/com/minecolonies/core/entity/ai/workers/production/EntityAIWorkLumberjack.java
Comment (armele) [inline src/main/java/com/minecolonies/core/entity/ai/workers/production/EntityAIWorkLumberjack.java:1]: I'd love to better understand this change so I can avoid creating a similar problem in the future!

File: src/main/java/com/minecolonies/core/entity/ai/workers/production/EntityAIWorkLumberjack.java [hunk 1]
```diff
@@ -240,7 +240,8 @@ protected IAIState decide()
             return getState();
         }
 
-        if (building.getModule(BuildingModules.ITEMLIST_SAPLING).getList().size() > 0)
+        if (building.getModule(BuildingModules.ITEMLIST_SAPLING).getList().size()
+            < IColonyManager.getInstance().getCompatibilityManager().getNumberOfSaplings())
```
Comment (Thodor12) [inline src/main/java/com/minecolonies/core/entity/ai/workers/production/EntityAIWorkLumberjack.java:244]: Little late to the party, but isn't this always true @Raycoms?

Unless you're counting for a mod removal which might remove the amount of saplings in the compat manager, you can never select more saplings in the list then there exist, no?

The only thing this could check is if you have every single sapling selected I guess

Comment (MotionlessTrain) [reply src/main/java/com/minecolonies/core/entity/ai/workers/production/EntityAIWorkLumberjack.java:244]: I have the feeling the list works inverted. The list within the ITEMLIST_SAPLING module likely contains the saplings that have been turned off, rather than turned on
Note that the menu starts with all enabled, which would mean an empty list if my feeling is correct, and so everything disabled, means that all available items are in the list, i.e. that the list sizes between the module and the compatibility manager are equal

Comment (uecasm) [reply src/main/java/com/minecolonies/core/entity/ai/workers/production/EntityAIWorkLumberjack.java:244]: Yep, it's a blacklist.  Empty list => all saplings on, full list => all saplings off.
