### PR TITLE
Fixes and pathing improvements

### LINKED ISSUE #6100: Pathing Issue
**Prerequisites**
[x] I am running the latest alpha version of MineColonies and Structurize for my Minecraft version.
[x] I checked the MineColonies/Structurize wiki and made sure my issue is not covered there.
[x] I made sure that this issue is not a duplicate of any existing issue.

**Context**

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.450
- Structurize Version: 0.13.96

**Expected behavior**
Colonists and travelers will properly pathfind up the jungle tavern ladder (T1)

**Actual behavior**
Colonists and travelers will get most of the way up the ladder, and try to go directly away from the ladder, resulting in them taking fall damage and eventually dying.

**Steps to reproduce the issue**

1. Go through normal colony building procedures with jungle style.
2. Build jungle tavern (T1)
3. Wait.

### LINKED ISSUE #6193: AI Issues
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.484-ALPHA-universal
- Structurize Version: 0.13.94-ALPHA-universal

## Problem description
I have had two villager stop working and then appear with the red gear and exclamation point above there head which then states "My AI has run into an issue, please locate the latest.log file and send it to the Minecolonies authors with this message. 

### Notes or related things
I have attached both screenshots and the logs in [questions](url
[message.txt](https://github.com/ldtteam/minecolonies/files/5639215/message.txt)
[message (1).txt](https://github.com/ldtteam/minecolonies/files/5639216/message.1.txt)
Villager 1
Villager 2

)
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #6198: Guards Unresponsive
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context  

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.490-ALPHA-universal.jar
- Structurize Version: 0.13.100-RELEASE-universal.jar
- Related Mods and their Versions: ATM 6 1.3.3

## Expected behavior
Guards patrolling colony normally and responding to rally flag

## Actual behavior
 Same bug as "closed" https://github.com/ldtteam/minecolonies/issues/6180 

I followed the last recommendation on that topic which is to kill the guards and replace them. I killed all 5 of them since they were all unresponsive. Hired 4 from tavern visitors and assigned them manually to the guardpost so they don't get hired by different buildings. Did not provide any armor/weapons manually but let them order it through the system.  They started patrolling the village normally but then they went to the same spot that the older guards would congregate at, on the side of the Town Hall.  
Used the rallying banner and they do not respond.

I must note that I did all the steps mentioned in the closed post. I fire/hire. I fire and hired for a different job where they did just fine. When I hired them back to guardposts they bugged out.

You can see here 2 guards just standing there after using the rally banner

image

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log:  https://gist.github.com/Rithenar/85cc9345b6a526d90b29b40231c995a9
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by someaddons**
Closes #6100
Closes #6193
Closes #6198
# Changes proposed in this pull request:

Pathing now also maps corner nodes when going upstairs or dropping down, giving our citizen a more smooth path to follow and fixing some corner cases, like in 6100 where without that node they jump down from a ladder since the next node is diagonal in the opposite direction on the next floor.

Pathing now considers going down through passable blocks, which previously did not work in cases where the passable block is also of walkable ground type, like trapdoors are.

Improved pathfollow, it is now better at recognizing arrival at a path point and also displays this during debug draw, reached nodes are displayed as orange:
image

Adjust min raidlevel before the first raid to be a bit lower
Fix pathing trying to drop down from places where the previous block is passable and dropable, e.g. jumping down vines instead of going them down.
Fix random path generation beeing able to end up on blocks a citizen cannot stand upon.
Fix guards doing stuck teleport during combat
Fix guards using rails during combat
Fix visitor zero position check throwing errors on clientside, when some other mods are creating one at 0 0 for 
rendering
Fix raids not spawning at low levels
Fix AI getting stuck when removing tasks
Fix citizen loading the colony to find the team, when not needed to do so

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java [hunk 1]
```diff
@@ -438,6 +440,11 @@ private IAIState checkAndAttackTarget()
         if (fighttimer > 0)
         {
             fighttimer--;
+            if (fighttimer == 0)
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java:443]: I sthis enough to have this here, what happens if combat finishes and they are hungry, or try to retreat with low health?

Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java:443]: ye because this is the point which also prevents the interruption of the other AI's

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java:443]: kk

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/6196/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Comment by Aduis1210** [comment]
Will this fix the issue we are having with Guards not supporting the colony?

**Comment by Raycoms** [comment]
@Aduis1210 yes

File: src/api/java/com/minecolonies/api/entity/ai/statemachine/basestatemachine/BasicStateMachine.java [hunk 2]
```diff
@@ -92,15 +92,11 @@ public void removeTransition(final T transition)
     {
         if (transition instanceof IStateMachineEvent)
         {
-            final List<T> temp = new ArrayList<>(eventTransitionMap.get(((IStateMachineEvent<?>) transition).getEventType()));
-            temp.remove(transition);
-            eventTransitionMap.put(((IStateMachineEvent<?>) transition).getEventType(), temp);
+            eventTransitionMap.get(((IStateMachineEvent<?>) transition).getEventType()).removeIf(t -> t == transition);
```
Comment (marchermans) [inline src/api/java/com/minecolonies/api/entity/ai/statemachine/basestatemachine/BasicStateMachine.java:95]: Are we sure this can not produce an NPE?
Would a getOrDefault(..., Collections.emptyList()) not be better here just to be sure.

File: src/api/java/com/minecolonies/api/entity/ai/statemachine/basestatemachine/BasicStateMachine.java [hunk 3]
```diff
@@ -92,15 +92,11 @@ public void removeTransition(final T transition)
...
         }
         else
         {
-            final List<T> temp = new ArrayList<>(transitionMap.get(transition.getState()));
-            temp.remove(transition);
-            transitionMap.put(transition.getState(), temp);
+            transitionMap.get(transition.getState()).removeIf(t -> t == transition);
```
Comment (marchermans) [inline src/api/java/com/minecolonies/api/entity/ai/statemachine/basestatemachine/BasicStateMachine.java:99]: See other comments in the file.

**Review by marchermans — APPROVED** [review]

File: src/api/java/com/minecolonies/api/entity/ai/statemachine/basestatemachine/BasicStateMachine.java (hunk 2 above)
Comment (someaddons) [reply src/api/java/com/minecolonies/api/entity/ai/statemachine/basestatemachine/BasicStateMachine.java:95]: ye it would indeed cause and NPE, thought that too when writing it and just left it to crash as sth must be wrong when trying to remove one that isnt added at all
