### PR TITLE
Toggleable shepherd sheep autodyeing

### LINKED ISSUE #2935: Sheep farmer automatically colors sheep
### Minecolonies version

Version: 0.9.4-RELEASE

### Expected behavior
Expect the sheep farmer to harvest the wool and meat from sheep without doing anything extra.

### Actual behaviour

Sheep farmer decides it wants to color the sheep... so instead of getting a ton of usable white wool, I have chests full of multi-colored wool that I now have to trash because you cannot dye the wool back to white.

### Steps to reproduce the problem

Play the game, check the sheep farmer from time to time, see colored sheep, use bonemeal on the sheep to turn them back white again, return in the future and find colored sheep again.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/64378974-sheep-farmer-automatically-colors-sheep?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #3365: Log spam of NBT Tag being too big
### Minecolonies version

Version: minecolonies-1.12.2-0.10.154-BETA-universal

### Expected behavior

- A lot of log spam about NBT Tag being too big.

### Actual behaviour

- [19:49:00] [main/FATAL] [minecraft/Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097158bytes where max allowed: 2097152
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1087) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097158bytes where max allowed: 2097152
	at net.minecraft.nbt.NBTSizeTracker.func_152450_a(NBTSizeTracker.java:25) ~[gh.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:57) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagList.func_152446_a(NBTTagList.java:63) ~[ge.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:133) ~[gi.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:88) ~[gi.class:?]
	at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:315) ~[gy.class:?]
	at net.minecraftforge.fml.common.network.ByteBufUtils.readTag(ByteBufUtils.java:227) ~[ByteBufUtils.class:?]
	at com.minecolonies.coremod.colony.ColonyView.handleColonyViewMessage(ColonyView.java:520) ~[ColonyView.class:?]
	at com.minecolonies.coremod.colony.ColonyManager.handleColonyViewMessage(ColonyManager.java:926) ~[ColonyManager.class:?]
	at com.minecolonies.coremod.network.messages.ColonyViewMessage.messageOnClientThread(ColonyViewMessage.java:66) ~[ColonyViewMessage.class:?]
	at com.minecolonies.coremod.network.messages.ColonyViewMessage.messageOnClientThread(ColonyViewMessage.java:16) ~[ColonyViewMessage.class:?]
	at com.minecolonies.coremod.network.messages.AbstractMessage.lambda$onMessage$1(AbstractMessage.java:31) ~[AbstractMessage.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
	... 17 more

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit
[debug.log](https://github.com/ldtteam/minecolonies/files/2853765/debug.log)
[latest.log](https://github.com/ldtteam/minecolonies/files/2853767/latest.log)

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/69944502-log-spam-of-nbt-tag-being-too-big?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Nightenom**
Closes #2935
Closes #3365

# Changes proposed in this pull request:
- some cleaning
- trying to fix #3365 
- added button to control automatical sheep colouring
- remade PAUSED state handler

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/ColonyView.java [hunk 1]
```diff
@@ -541,9 +541,16 @@ public IMessage handleColonyViewMessage(@NotNull final ByteBuf buf, @NotNull fin
...
+            try
+            {
+                final NBTTagCompound compound = ByteBufUtils.readTag(buf);
+                this.requestManager = new StandardRequestManager(this);
+                this.requestManager.deserializeNBT(compound);
+            }
+            catch (RuntimeException e)
+            {
+                this.requestManager = new StandardRequestManager(this);
+            }
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/colony/ColonyView.java]: Honestly, why create a new one if it crashes?
I'd just not assign a new one.

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingShepherd.java [hunk 2]
```diff
@@ -68,11 +85,48 @@ public AbstractJob createJob(final CitizenData citizen)
...
+    }
+
+    @Override
+    public void readFromNBT(@NotNull final NBTTagCompound compound)
+    {
+        super.readFromNBT(compound);
+        this.dyeSheeps = compound.getBoolean(NBT_DYE_SHEEPS);
+    }
+
+    public boolean isDyeSheeps()
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingShepherd.java:110]: jdoc

File: src/main/java/com/minecolonies/coremod/colony/ColonyView.java (hunk 1 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/ColonyView.java]: And can we write trigger the rs reset message here if this fails? We don't want to avoid the crash we want to clean it up as well

Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/colony/ColonyView.java]: its not solving the NBT issue btw, just the clientsided crash. The server is still going to keep sending too large packages

Comment (Nightenom) [reply src/main/java/com/minecolonies/coremod/colony/ColonyView.java]: the problem is I did not found any method to calculate size of NBTTagCompound, I'm aware of it's not the best solution - so you want me to send a RS reset message?

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/ColonyView.java]: yeah, so we just send a reset on failure of this.

File: src/main/java/com/minecolonies/coremod/colony/ColonyView.java [hunk 3]
```diff
@@ -205,8 +210,17 @@ public static void serializeNetworkData(@NotNull final Colony colony, @NotNull f
...
+            final int preState = buf.readerIndex();
             buf.writeBoolean(true);
             ByteBufUtils.writeTag(buf, colony.getRequestManager().serializeNBT());
+            final int postSize = buf.writerIndex();
+            if ((postSize - preSize) >= MAX_BYTES_NBTCOMPOUND)
+            {
+                colony.getRequestManager().reset();
+                buf.setIndex(preState, preSize);
+                buf.writeBoolean(false);
+            }
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/colony/ColonyView.java:224]: Looks good to me

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingShepherd.java [hunk 4]
```diff
@@ -68,11 +79,54 @@ public AbstractJob createJob(final CitizenData citizen)
...
+    {
+        super.writeToNBT(compound);
+        compound.setBoolean(NBT_DYE_SHEEPS, this.dyeSheeps);
+    }
+
+    @Override
+    public void readFromNBT(@NotNull final NBTTagCompound compound)
+    {
+        super.readFromNBT(compound);
+        this.dyeSheeps = compound.getBoolean(NBT_DYE_SHEEPS);
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingShepherd.java:100]: Just missing a if !contains then = true, to make the default true

**Comment by Raycoms** [comment]
@Nightenom looks good besides the small thing I noted
After that :shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/3383/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingShepherd.java (hunk 4 above)
Comment (Nightenom) [reply src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingShepherd.java:100]: I had it there, then I was like nah, so I removed it

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingShepherd.java:100]: =D, I still think that the current default should be the default, else people will wonder why he stopped dying without actively turning it off.

Comment (Nightenom) [reply src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingShepherd.java:100]: done

**Comment by spacewolfcub** [comment]
Aren't the florist, dyer and weaver going to make the shepherd's random dyeing undesirable anyway? You would actually want the shepherd to only give white or natural colours. To make the florist, dyer, and weaver have a more realistic use.

**Comment by Raycoms** [comment]
We can remove this once both are implemented, which reminds me of bugging
the responsible dev for the florist.

Am Sa., 16. Feb. 2019 um 23:53 Uhr schrieb spacewolfcub <
notifications@github.com>:

File: src/api/java/com/minecolonies/api/colony/requestsystem/requestable/Tool.java [hunk 5]
```diff
@@ -154,7 +154,7 @@ public boolean matches(@NotNull final ItemStack stack)
 
     private Set<String> getToolClasses(final ItemStack stack)
     {
-        final Set set = new HashSet();
+        final Set<String> set = new HashSet<String>();
```
Comment (marchermans) [inline src/api/java/com/minecolonies/api/colony/requestsystem/requestable/Tool.java]: Remove the last <String>. Not needed, replace with <>

File: src/api/java/com/minecolonies/api/util/constant/WindowConstants.java [hunk 6]
```diff
@@ -1130,6 +1130,12 @@
      */
     public static final String CITIZEN_LIVING = "living";
 
+    /**
+     * General big on and big off
+     */
+    public static final String GENERAL_ON_BIG  = LanguageHandler.format(COM_MINECOLONIES_COREMOD_GENERAL_ONBIG);
```
Comment (marchermans) [inline src/api/java/com/minecolonies/api/util/constant/WindowConstants.java]: We should refrain from now on from doing this.
The player can chain the language during the game without restart.
This would not be updated.

Please fix.

File: src/main/java/com/minecolonies/coremod/colony/ColonyView.java (hunk 3 above)
Comment (marchermans) [reply src/main/java/com/minecolonies/coremod/colony/ColonyView.java:224]: Please run a reset here instead of just not sending it.
You can do this since this is the writing server side.

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingShepherd.java (hunk 4 above)
Comment (marchermans) [reply src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingShepherd.java:100]: This solution will throw an NPE if NBT_DYE_SHEEPS is not in the compound.
Please surround the compound with the if-switch and use an else switch to handle the default

**Review by marchermans — CHANGES_REQUESTED** [review]
Good work. Some small stuff.
Also next time, refrain from making changes to files you did not touch, this makes reviewing much harder.

File: src/main/java/com/minecolonies/coremod/colony/ColonyView.java (hunk 3 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/ColonyView.java:224]: Oh yeah, you can reset and then send, the effect should be immediate anyway.

Comment (marchermans) [reply src/main/java/com/minecolonies/coremod/colony/ColonyView.java:224]: Yep

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingShepherd.java (hunk 4 above)
Comment (Nightenom) [reply src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingShepherd.java:100]: It returns false and (in dev env) doesn't throw an npe. If statement added already

File: src/api/java/com/minecolonies/api/util/constant/WindowConstants.java (hunk 6 above)
Comment (Nightenom) [reply src/api/java/com/minecolonies/api/util/constant/WindowConstants.java]: edit: nothing...

**Review by marchermans — APPROVED** [review]
