### PR TITLE
Fix citizen limit calculation v1.12

### LINKED ISSUE #3463: Max citizen number not increasing
### Minecolonies version 

Version: minecolonies-1.12.2-0.10.202-RELEASE-universal.jar

### Expected behavior

I have been attempting to raise my citizen cap, but it's simply not going up. I've built several houses (4 level 3 houses and 1 level 2), but the cap was stuck at 4. I then killed one of my citizens to see if this would work (I'm not a smart guy), and now the citizen cap is simply 3/3. I would expect the number to go up according to my housing levels (which if my math serves, should be 14.)

### Actual behaviour

The cap stays the exact same.

### Steps to reproduce the problem

Well, as you can see I've built a townhall and several houses. I will say; while messing around with the reposition feature, I accidentally broke my townhall and had to place a new one, I have no idea if this is somehow messing with the mod, but I didn't even think about it until some time later.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/70910296-max-citizen-number-not-increasing?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #4191: Firing a knight/ranger from barracks results in funny colonist count
### Minecolonies version

Version: minecolonies-0.10.493-RELEASE-universal

### Expected behavior

- Total colonist count to count all colonists correctly: 

   current colonists/total possible

### Actual behaviour

- The total possible is less then the current population. I've seen this issue prevent children from showing up if there was an extra citizen home available. Building another or upgrading a home would fix the ratio and generally 2 children would soon show up.

### PR DESCRIPTION
**Pull request by someaddons**
Closes #4191
Closes #3463

# Changes proposed in this pull request:
Now Calculates on building upgrade/destruction.
Recalculates after colony load, instead of reading old values.
Recruitment of additional guards over the citizen hut limit now works.
Level 0 guard-buildings no longer count towards the limit.

**Update**: Fixed another case and changed it to global instead. So that in the future you only need to adjust the maxCitizenCalc for new buildings/other stuff that houses.
The max citizens are now recalculated on:
- Assign and removal from a building
- Upgrade and destruction from a building
- removal of a citizen
- Colony load

**1.12 only:**
Backported the RackInventory class from 1.14, as on 1.12 we're atm overwriting our setStackinSlot  hook needed for our warehouse and RS

Fixed an ID issue, causing the Townhalls info page to be hidden.

Review please

### CODE REVIEW

File: src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java [hunk 1]
```diff
@@ -330,15 +330,7 @@ public void readFromNBT(final NBTTagCompound compound)
...
             {
-                inventory = new ItemStackHandler(DEFAULT_SIZE + size * SLOT_PER_LINE)
-                {
-                    @Override
-                    protected void onContentsChanged(final int slot)
-                    {
-                        updateItemStorage();
-                        super.onContentsChanged(slot);
-                    }
-                };
```
Comment (someaddons) [inline src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java:341]: this above overwrote the hooks we setup for setStackInSlot on class load before

**Comment by marvin-bitterlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=4803609&bid=15984078)

**Review by marchermans — APPROVED** [review]
