### PR TITLE
fix 7373

### LINKED ISSUE #7373: Crash to desktop when worker is fired or removed from job
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.273-ALPHA
- Structurize Version: 0.13.198-ALPHA
- Related Mods and their Versions:

## Expected behavior
You should be able to fire a worker from their job at their job hut.

## Actual behavior
This behavior started when I updated from 0.14.263-ALPHA to 0.14.273-ALPHA.  

When a worker is fired from their job, the game crashes to desktop.  This happens if you do this from the "manage workers" screen at the job hut, but I have also seen it happen when a student in the school is removed because they grow up.  Hiring a worker works as expected.  I reproduced this behavior both on my long-term build, and a brand new creative test world.

Please refer to attached latest log.  A block similar to the one starting at line 1050 shows up each time a crash occurs.

## Steps to reproduce the issue

1. Update to 0.14.273-ALPHA
2. Fire a worker anywhere

### Logs

https://gist.github.com/Oraxian/81f842d42d75eecb43a61152753840b1

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #7373
Closes #
Closes #

# Changes proposed in this pull request:
-
-
-

Review please

### CODE REVIEW

**Review by someaddons — APPROVED** [review]

File: src/api/java/com/minecolonies/api/entity/CustomGoalSelector.java [hunk 1]
```diff
@@ -139,12 +141,14 @@ public void addGoal(int priority, Goal task)
...
-            return goal.getGoal() == task;
-        }).filter(PrioritizedGoal::isRunning).forEach(PrioritizedGoal::stop);
-        this.availableGoals.removeIf((goal) -> {
-            return goal.getGoal() == task;
-        });
+        for(final PrioritizedGoal prioritizedGoal : new ArrayList<>(availableGoals))
+        {
+            if (prioritizedGoal.getGoal() == task)
+            {
+                prioritizedGoal.stop();
```
Comment (uecasm) [inline src/api/java/com/minecolonies/api/entity/CustomGoalSelector.java:148]: This is a possible change of behaviour -- the previous code would `remove` as shown here but would only call `stop` when `isRunning`.

Having said that, it looks like `stop` will check `isRunning` internally anyway so it will probably work as expected as long as we trust that. 😄

**Review by uecasm — APPROVED** [review]

**Review by marchermans — APPROVED** [review]
