### PR TITLE
Some moar fixes

### LINKED ISSUE #7326: Looping Citizen Stuck
### Prerequisites 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.241
- Structurize Version: 0.13.195
- Related Mods and their Versions:

## Expected behavior
Citizens continue to their path instead of looping in same location over and over again.

## Actual behavior
While their hunger is low but not fully hungry , like in image below. They start looping around and they stay stuck forever until you give them food. I don't have restaurant yet. Interesting part is at night, they properly go and sleep. However next day, stuck again and in same spot. 
Edit: Same results for miner, looping miner climbing ladder.
image
image

If you feed them they start working back.

### LINKED ISSUE #7332: Can't remove smelting recipes
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.251-ALPHA
- Structurize Version: 0.13.195-ALPHA
- Related Mods and their Versions: -

## Expected behavior
I can remove recipe's from the stone smelter I taught before

## Actual behavior
In the smelting recipe GUI, there are no options to remove recipes.

Stone smelter screenshot

## Steps to reproduce the issue

1. Teach the stone smelter (or e.g. the dyer) a smelting recipe
2. Try to remove it from the GUI.

### Logs

I don't think the log is  useful here, but just in case

- latest.log: https://gist.github.com/MotionlessTrain/4c545f941ea9c76af06dadd8defd08b7
- crashlog: N/A

### Notes
Apparently, the amount of recipes for the stone smelter changed. I wanted to remove some recipes to teach another one I needed, but that didn't work...

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #7332
Closes #7326
Closes #

# Changes proposed in this pull request:
- List citizens propperly
- Fix issue with not being able to remove smelter recipes
- Issue looping when hungry and no restaurant is available

Review please

### CODE REVIEW

**Review by marchermans — DISMISSED** [review]

File: src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java [hunk 1]
```diff
@@ -182,9 +192,19 @@ public boolean shouldEat()
             return false;
         }
 
-        if (citizenData.getSaturation() <= CitizenConstants.LOW_SATURATION)
+        if (citizenData.getSaturation() <= CitizenConstants.AVERAGE_SATURATION)
         {
-            return true;
+            if (citizenData.getSaturation() == RESTAURANT_LIMIT)
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java]: == with doubles?

File: src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java [hunk 2]
```diff
@@ -466,7 +486,7 @@ private EatingState searchRestaurant()
         final ICitizenData citizenData = citizen.getCitizenData();
         final IColony colony = citizenData.getColony();
         restaurantPos = colony.getBuildingManager().getBestBuilding(citizen, BuildingCook.class);
-        if (citizenData.getSaturation() == 0.0)
+        if (citizenData.getSaturation() == RESTAURANT_LIMIT)
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java]: same here

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java]: good catch
