### PR TITLE
Fix structures loading

### LINKED ISSUE #899: Crash/Can't Create World/Crash on World Creation
forge 2285, minecolonies-universal-1.11.2-0.7.664.jar. please help, thanks.
[crash-2017-04-29_19.38.29-server.txt](https://github.com/Minecolonies/minecolonies/files/966274/crash-2017-04-29_19.38.29-server.txt)

edit: it doesn't happen with minecolonies-universal-1.11-0.6.3360.jar
edit2: it happens with **minecolonies-universal-1.11.2-0.7.683** too.

### LINKED ISSUE #906: Infinite Server Crash - 1.10.2 + Sponge
### Minecolonies version

https://minecraft.curseforge.com/projects/minecolonies/files/2414093

### Expected behavior
Should work

### Actual behaviour

https://gist.github.com/P3rf3ctXZer0/11c1908a40cc3af02e73c1144979f7de

### Steps to reproduce the problem

Don't know just reporting it I am a bit busy.

### PR DESCRIPTION
**Pull request by xavierh**
Closes #906
Closes #899

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/Structures.java [hunk 1]
```diff
@@ -119,14 +119,28 @@ private static void loadStyleMaps()
...
                 final Path basePath = fileSystem.getPath(SCHEMATICS_ASSET_PATH);
+                Log.getLogger().info("Load huts or decorations from jar");
                 loadSchematicsForPrefix(basePath, SCHEMATICS_PREFIX);
             }
-            catch (@NotNull IOException | URISyntaxException e)
+            /**
+             *  @Supresswarning("squid:S1166")
+             *  The same exception will be triggered in the catch with logging this time.
+             */
+            catch (@NotNull IOException | URISyntaxException | FileSystemNotFoundException e1)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/Structures.java]: MAJOR Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 43 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 41 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Structures.java#L497](https://github.com/Minecolonies/minecolonies/blob/86b7005d684e3d3a3699cd393a912c42f9836444/src/main/java/com/minecolonies/coremod/colony/Structures.java#L497): Reduce this class from 118 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/86b7005d684e3d3a3699cd393a912c42f9836444/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/86b7005d684e3d3a3699cd393a912c42f9836444/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/86b7005d684e3d3a3699cd393a912c42f9836444/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/86b7005d684e3d3a3699cd393a912c42f9836444/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/86b7005d684e3d3a3699cd393a912c42f9836444/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/86b7005d684e3d3a3699cd393a912c42f9836444/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/86b7005d684e3d3a3699cd393a912c42f9836444/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/86b7005d684e3d3a3699cd393a912c42f9836444/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [jobs](https://github.com/Minecolonies/minecolonies/blob/86b7005d684e3d3a3699cd393a912c42f9836444/src/main/java/com/minecolonies/coremod/colony/jobs): Add a 'package-info.java' file to document the 'jobs' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/colony/Structures.java [hunk 2]
```diff
@@ -119,14 +119,28 @@ private static void loadStyleMaps()
...
+            try (FileSystem fileSystem = FileSystems.getFileSystem(ColonyManager.class.getResource(SCHEMATICS_ASSET_PATH).toURI()))
             {
                 final Path basePath = fileSystem.getPath(SCHEMATICS_ASSET_PATH);
+                Log.getLogger().info("Load huts or decorations from jar");
                 loadSchematicsForPrefix(basePath, SCHEMATICS_PREFIX);
             }
-            catch (@NotNull IOException | URISyntaxException e)
+            /**
+             *  @Supresswarning("squid:S1166")
+             *  The same exception will be triggered in the catch with logging this time.
```
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/colony/Structures.java]: please follow the template :P 
and actually suppress the warning. Annotations need to be out of the comment

**Review by marvin-bitterlich — CHANGES_REQUESTED** [review]

File: src/main/java/com/minecolonies/coremod/colony/Structures.java [hunk 3]
```diff
@@ -115,18 +115,30 @@ public static void init()
      * Loads all styles saved in ["/assets/minecolonies/schematics/"].
      * Puts these in {@link #md5Map}, with key being the fullname of the structure (schematics/stone/Builder1).
      */
+    // The same exception will be triggered in the 2nd catch with logging this time.
+    @SuppressWarnings("squid:S1166")
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/Structures.java:120]: INFO Suppressing the 'squid:S1166' warning is not allowed [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1309)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 43 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 41 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Structures.java#L496](https://github.com/Minecolonies/minecolonies/blob/da96eadd46bd01636e89229245d4f440faba05ed/src/main/java/com/minecolonies/coremod/colony/Structures.java#L496): Reduce this class from 118 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/da96eadd46bd01636e89229245d4f440faba05ed/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/da96eadd46bd01636e89229245d4f440faba05ed/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/da96eadd46bd01636e89229245d4f440faba05ed/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/da96eadd46bd01636e89229245d4f440faba05ed/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/da96eadd46bd01636e89229245d4f440faba05ed/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/da96eadd46bd01636e89229245d4f440faba05ed/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/da96eadd46bd01636e89229245d4f440faba05ed/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/da96eadd46bd01636e89229245d4f440faba05ed/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [jobs](https://github.com/Minecolonies/minecolonies/blob/da96eadd46bd01636e89229245d4f440faba05ed/src/main/java/com/minecolonies/coremod/colony/jobs): Add a 'package-info.java' file to document the 'jobs' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/colony/Structures.java [hunk 4]
```diff
@@ -153,6 +148,50 @@ private static void loadStyleMaps()
...
+
+    private static void loadStyleMapsJar()
+    {
+        try
+        {
+            Log.getLogger().info("loadStyleMaps jar: " + ColonyManager.class.getResource(SCHEMATICS_ASSET_PATH).toURI()); 
+            final URI uri = ColonyManager.class.getResource(SCHEMATICS_ASSET_PATH).toURI();
+            if ("jar".equals(uri.getScheme()))
+            {
+                try (FileSystem fileSystem = FileSystems.getFileSystem(ColonyManager.class.getResource(SCHEMATICS_ASSET_PATH).toURI()))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/Structures.java]: MAJOR Extract this nested try block into a separate method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1141)

File: src/main/java/com/minecolonies/coremod/colony/Structures.java [hunk 5]
```diff
@@ -153,6 +148,50 @@ private static void loadStyleMaps()
...
+                {
+                    final Path basePath = fileSystem.getPath(SCHEMATICS_ASSET_PATH);
+                    Log.getLogger().info("Load huts or decorations from jar");
+                    loadSchematicsForPrefix(basePath, SCHEMATICS_PREFIX);
+                }
+                catch (@NotNull IOException | URISyntaxException | FileSystemNotFoundException e1)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/Structures.java]: MAJOR Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)

File: src/main/java/com/minecolonies/coremod/colony/Structures.java [hunk 6]
```diff
@@ -153,6 +148,50 @@ private static void loadStyleMaps()
...
+                {
+                    try (FileSystem fileSystem = FileSystems.newFileSystem(ColonyManager.class.getResource(SCHEMATICS_ASSET_PATH).toURI(), Collections.emptyMap()))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/Structures.java]: MAJOR Extract this nested try block into a separate method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1141)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 46 issues
* ![MAJOR][MAJOR] 4 major
* ![MINOR][MINOR] 41 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Structures.java#L523](https://github.com/Minecolonies/minecolonies/blob/52113630c268cdeb23a242b969fa39947d8e12e5/src/main/java/com/minecolonies/coremod/colony/Structures.java#L523): Reduce this class from 118 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/52113630c268cdeb23a242b969fa39947d8e12e5/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/52113630c268cdeb23a242b969fa39947d8e12e5/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/52113630c268cdeb23a242b969fa39947d8e12e5/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/52113630c268cdeb23a242b969fa39947d8e12e5/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/52113630c268cdeb23a242b969fa39947d8e12e5/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/52113630c268cdeb23a242b969fa39947d8e12e5/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/52113630c268cdeb23a242b969fa39947d8e12e5/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/52113630c268cdeb23a242b969fa39947d8e12e5/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [jobs](https://github.com/Minecolonies/minecolonies/blob/52113630c268cdeb23a242b969fa39947d8e12e5/src/main/java/com/minecolonies/coremod/colony/jobs): Add a 'package-info.java' file to document the 'jobs' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/colony/Structures.java [hunk 7]
```diff
@@ -153,6 +148,54 @@ private static void loadStyleMaps()
...
+
+        if ("jar".equals(uri.getScheme()))
+        {
+            try (FileSystem fileSystem = FileSystems.getFileSystem(ColonyManager.class.getResource(SCHEMATICS_ASSET_PATH).toURI()))
+            {
+                final Path basePath = fileSystem.getPath(SCHEMATICS_ASSET_PATH);
+                Log.getLogger().info("Load huts or decorations from jar");
+                loadSchematicsForPrefix(basePath, SCHEMATICS_PREFIX);
+            }
+            catch (@NotNull IOException | URISyntaxException | FileSystemNotFoundException e1)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/Structures.java]: MAJOR Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 44 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 41 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Structures.java#L527](https://github.com/Minecolonies/minecolonies/blob/a8986f15630494d6ddc0644e958f75014f18ce1b/src/main/java/com/minecolonies/coremod/colony/Structures.java#L527): Reduce this class from 118 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/a8986f15630494d6ddc0644e958f75014f18ce1b/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/a8986f15630494d6ddc0644e958f75014f18ce1b/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/a8986f15630494d6ddc0644e958f75014f18ce1b/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/a8986f15630494d6ddc0644e958f75014f18ce1b/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/a8986f15630494d6ddc0644e958f75014f18ce1b/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/a8986f15630494d6ddc0644e958f75014f18ce1b/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/a8986f15630494d6ddc0644e958f75014f18ce1b/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/a8986f15630494d6ddc0644e958f75014f18ce1b/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [jobs](https://github.com/Minecolonies/minecolonies/blob/a8986f15630494d6ddc0644e958f75014f18ce1b/src/main/java/com/minecolonies/coremod/colony/jobs): Add a 'package-info.java' file to document the 'jobs' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/colony/Structures.java [hunk 8]
```diff
@@ -165,6 +148,50 @@ private static void loadStyleMaps()
         }
     }
 
+
+    private static void loadStyleMapsJar()
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/colony/Structures.java]: This needs to be rewritten. It might work it might not. Use MC Resource system to load files from the JAR. It is a proven system and works regardless of dev environment, wrapped starter, etc.

This will break if somebody else opens the jars.
Resources are loaded before anything else.

**Review by marchermans — CHANGES_REQUESTED** [review]

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/910/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 44 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 41 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Structures.java#L527](https://github.com/Minecolonies/minecolonies/blob/3dc4164fa8245318c7f2c9d0e746c19445078f23/src/main/java/com/minecolonies/coremod/colony/Structures.java#L527): Reduce this class from 118 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/3dc4164fa8245318c7f2c9d0e746c19445078f23/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/3dc4164fa8245318c7f2c9d0e746c19445078f23/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/3dc4164fa8245318c7f2c9d0e746c19445078f23/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/3dc4164fa8245318c7f2c9d0e746c19445078f23/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/3dc4164fa8245318c7f2c9d0e746c19445078f23/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/3dc4164fa8245318c7f2c9d0e746c19445078f23/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/3dc4164fa8245318c7f2c9d0e746c19445078f23/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/3dc4164fa8245318c7f2c9d0e746c19445078f23/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [jobs](https://github.com/Minecolonies/minecolonies/blob/3dc4164fa8245318c7f2c9d0e746c19445078f23/src/main/java/com/minecolonies/coremod/colony/jobs): Add a 'package-info.java' file to document the 'jobs' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/colony/Structures.java [hunk 9]
```diff
@@ -154,6 +149,52 @@ private static void loadStyleMaps()
...
+
+        if ("jar".equals(uri.getScheme()))
+        {
+            try (FileSystem fileSystem = FileSystems.getFileSystem(uri))
+            {
+                final Path basePath = fileSystem.getPath(SCHEMATICS_ASSET_PATH);
+                Log.getLogger().info("Load huts or decorations from jar");
+                loadSchematicsForPrefix(basePath, SCHEMATICS_PREFIX);
+            }
+            catch (@NotNull IOException | FileSystemNotFoundException e1)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/Structures.java:175]: MAJOR Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 44 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 41 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Structures.java#L525](https://github.com/Minecolonies/minecolonies/blob/ff7aa8d57714d4bce05fdb974015c50d2595bfc9/src/main/java/com/minecolonies/coremod/colony/Structures.java#L525): Reduce this class from 118 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/ff7aa8d57714d4bce05fdb974015c50d2595bfc9/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/ff7aa8d57714d4bce05fdb974015c50d2595bfc9/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/ff7aa8d57714d4bce05fdb974015c50d2595bfc9/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/ff7aa8d57714d4bce05fdb974015c50d2595bfc9/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/ff7aa8d57714d4bce05fdb974015c50d2595bfc9/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/ff7aa8d57714d4bce05fdb974015c50d2595bfc9/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/ff7aa8d57714d4bce05fdb974015c50d2595bfc9/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/ff7aa8d57714d4bce05fdb974015c50d2595bfc9/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [jobs](https://github.com/Minecolonies/minecolonies/blob/ff7aa8d57714d4bce05fdb974015c50d2595bfc9/src/main/java/com/minecolonies/coremod/colony/jobs): Add a 'package-info.java' file to document the 'jobs' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'
