### PR TITLE
Migrated fixes from 1.12 branch: (#1896),(#2102), Other misc

### LINKED ISSUE #1896: [1.10] Crash on Server Startup (Ore Issue)
### Minecolonies version

version minecolonies-universal-1.10.2-0.9.6155 & minecolonies-universal-1.10.2-0.9.6188 

### Expected behavior

- Start normal like before with minecolonies-universal-1.10.2-0.9.6077

### Actual behaviour

Surprise! Haha. Well, this is awkward.

Time: 12/22/17 9:05 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at exterminatorjeff.undergroundbiomes.common.block.UBOreSedimentary.func_180642_a(UBOreSedimentary.java:42)
	at com.minecolonies.api.compatibility.CompatabilityManager.discoverOres(CompatabilityManager.java:162)
	at com.minecolonies.api.compatibility.CompatabilityManager.discover(CompatabilityManager.java:63)
	at com.minecolonies.coremod.colony.ColonyManager.readFromNBT(ColonyManager.java:818)
	at com.minecolonies.coremod.colony.ColonyManager.onWorldLoad(ColonyManager.java:716)
	at com.minecolonies.coremod.event.EventHandler.onWorldLoad(EventHandler.java:397)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_814_EventHandler_onWorldLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:263)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Unknown Source)

### LINKED ISSUE #2102: Crash on open TownHall Statistics
[crash-2018-01-28_02.01.52-client.txt](https://github.com/Minecolonies/minecolonies/files/1670799/crash-2018-01-28_02.01.52-client.txt)
### Minecolonies version

version minecolonies-universal-1.10.2-0.9.7220

### PR DESCRIPTION
**Pull request by Excyclic**
Fixed Guard label in Town Hall GUI

Closes #1896 
Closes #2102

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/client/gui/WindowClipBoard.java [hunk 1]
```diff
@@ -119,7 +119,9 @@ public void onOpened()
 
             if (!displayStacks.isEmpty())
             {
-                exampleStackDisplay.setItem(displayStacks.get((lifeCount / LIFE_COUNT_DIVIDER) % displayStacks.size()));
+                if(exampleStackDisplay != null) {
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowClipBoard.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 50 issues
* ![MAJOR][MAJOR] 46 major
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/fe5333305095e0f0b866482c37fe8e1658d4f1ff/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/fe5333305095e0f0b866482c37fe8e1658d4f1ff/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L169](https://github.com/Minecolonies/minecolonies/blob/fe5333305095e0f0b866482c37fe8e1658d4f1ff/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L169): The Cyclomatic Complexity of this method "updateResources" is 22 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L169](https://github.com/Minecolonies/minecolonies/blob/fe5333305095e0f0b866482c37fe8e1658d4f1ff/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L169): Refactor this method to reduce its Cognitive Complexity from 35 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L180](https://github.com/Minecolonies/minecolonies/blob/fe5333305095e0f0b866482c37fe8e1658d4f1ff/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L180): Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS135)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L297](https://github.com/Minecolonies/minecolonies/blob/fe5333305095e0f0b866482c37fe8e1658d4f1ff/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L297): Remove this unused method parameter "list". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L43](https://github.com/Minecolonies/minecolonies/blob/fe5333305095e0f0b866482c37fe8e1658d4f1ff/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L43): class "WindowBuildTool" has 41 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L146](https://github.com/Minecolonies/minecolonies/blob/fe5333305095e0f0b866482c37fe8e1658d4f1ff/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L146): Remove this unused "staticSchematicMode" private field. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1068)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/fe5333305095e0f0b866482c37fe8e1658d4f1ff/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/fe5333305095e0f0b866482c37fe8e1658d4f1ff/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 49 issues
* ![MAJOR][MAJOR] 46 major
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/a73243d4c0689a17918a13ef1df4b029e4c8c824/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/a73243d4c0689a17918a13ef1df4b029e4c8c824/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L169](https://github.com/Minecolonies/minecolonies/blob/a73243d4c0689a17918a13ef1df4b029e4c8c824/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L169): The Cyclomatic Complexity of this method "updateResources" is 22 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L169](https://github.com/Minecolonies/minecolonies/blob/a73243d4c0689a17918a13ef1df4b029e4c8c824/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L169): Refactor this method to reduce its Cognitive Complexity from 35 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L180](https://github.com/Minecolonies/minecolonies/blob/a73243d4c0689a17918a13ef1df4b029e4c8c824/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L180): Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS135)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L297](https://github.com/Minecolonies/minecolonies/blob/a73243d4c0689a17918a13ef1df4b029e4c8c824/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L297): Remove this unused method parameter "list". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L43](https://github.com/Minecolonies/minecolonies/blob/a73243d4c0689a17918a13ef1df4b029e4c8c824/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L43): class "WindowBuildTool" has 41 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L146](https://github.com/Minecolonies/minecolonies/blob/a73243d4c0689a17918a13ef1df4b029e4c8c824/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L146): Remove this unused "staticSchematicMode" private field. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1068)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/a73243d4c0689a17918a13ef1df4b029e4c8c824/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/a73243d4c0689a17918a13ef1df4b029e4c8c824/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Review by marchermans — APPROVED** [review]
