### PR TITLE
Delete building on colony remove

### LINKED ISSUE #1490: Item Frames missing from Builder's List of Materials for Warehouse 3,
### Minecolonies version

version 1.10.2-0.8.3880 and 0.8.3227

### Expected behavior

When building Warehouse 3 (wood), the total number of item frames needed should be on the builder's material list. The builder should ask for the full amount of item frames needed in chat and hold the item frame object in their hand. 

### Actual behaviour

The item frames don't show up on the builder's material list. When it is time to put in the item frames, the builder asks for 1 item frame at a time, and holds an non-item-frame object. Spruce slab, for me. (Not sure if the spruce slab is replicable, may just be the last item  the builder held.) I think this behavior also holds true for Warehouse 4 and  maybe 5, if more item frames are needed, but not sure.

### Steps to reproduce the problem

1. Build warehouse 3
2. Look at builder's material list and builder, look  for announcements about item frames in chat.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #1490

Destroy buildings when deleting the colony

# Changes proposed in this pull request:
- Actually destroy the buildings and not just the chests
- Sort list of citizens by name in the hire/fire and assign/unassign windows
- Fixes also builder not requesting itemStack.
Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/util/ColonyUtils.java [hunk 1]
```diff
@@ -53,15 +53,14 @@ public static boolean hasNewSubscribers(@NotNull final Set<EntityPlayerMP> oldSu
      * Calculated the corner of a building.
      * @param pos the central position.
      * @param world the world.
-     * @param structureName the name of the structure (resource location).
+     * @param wrapper the structureWrapper.
      * @param rotation the rotation.
      * @param isMirrored if its mirrored.
      * @return a tuple with the required corners.
      */
     public static Tuple<Tuple<Integer, Integer>, Tuple<Integer, Integer>> calculateCorners(
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/util/ColonyUtils.java:61]: MAJOR Provide multiple methods instead of using "isMirrored" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 41 issues
* ![MAJOR][MAJOR] 9 major
* ![MINOR][MINOR] 32 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ColonyManager.java#L40](https://github.com/Minecolonies/minecolonies/blob/8f5a3fa663511cc5731ec54a76e806be7b02ad7d/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L40): class "ColonyManager" has 50 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ColonyManager.java#L601](https://github.com/Minecolonies/minecolonies/blob/8f5a3fa663511cc5731ec54a76e806be7b02ad7d/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L601): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L52](https://github.com/Minecolonies/minecolonies/blob/8f5a3fa663511cc5731ec54a76e806be7b02ad7d/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L52): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 37 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L52](https://github.com/Minecolonies/minecolonies/blob/8f5a3fa663511cc5731ec54a76e806be7b02ad7d/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L52): class "AbstractBuilding" has 66 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L1299](https://github.com/Minecolonies/minecolonies/blob/8f5a3fa663511cc5731ec54a76e806be7b02ad7d/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1299): Reduce this class from 75 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L52](https://github.com/Minecolonies/minecolonies/blob/8f5a3fa663511cc5731ec54a76e806be7b02ad7d/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L52): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 31 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L177](https://github.com/Minecolonies/minecolonies/blob/8f5a3fa663511cc5731ec54a76e806be7b02ad7d/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L177): The Cyclomatic Complexity of this method "requestMaterials" is 17 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [ColonyUtils.java#L18](https://github.com/Minecolonies/minecolonies/blob/8f5a3fa663511cc5731ec54a76e806be7b02ad7d/src/main/java/com/minecolonies/coremod/util/ColonyUtils.java#L18): Add a private constructor to hide the implicit public one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1118)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/8f5a3fa663511cc5731ec54a76e806be7b02ad7d/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/8f5a3fa663511cc5731ec54a76e806be7b02ad7d/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Review by marchermans — APPROVED** [review]

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 41 issues
* ![MAJOR][MAJOR] 9 major
* ![MINOR][MINOR] 32 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ColonyManager.java#L40](https://github.com/Minecolonies/minecolonies/blob/f7a3b316a95375a239a1c6f228b3031497ce1847/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L40): class "ColonyManager" has 50 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ColonyManager.java#L601](https://github.com/Minecolonies/minecolonies/blob/f7a3b316a95375a239a1c6f228b3031497ce1847/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L601): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L52](https://github.com/Minecolonies/minecolonies/blob/f7a3b316a95375a239a1c6f228b3031497ce1847/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L52): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 37 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L52](https://github.com/Minecolonies/minecolonies/blob/f7a3b316a95375a239a1c6f228b3031497ce1847/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L52): class "AbstractBuilding" has 66 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L1301](https://github.com/Minecolonies/minecolonies/blob/f7a3b316a95375a239a1c6f228b3031497ce1847/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1301): Reduce this class from 75 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L52](https://github.com/Minecolonies/minecolonies/blob/f7a3b316a95375a239a1c6f228b3031497ce1847/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L52): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 31 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L177](https://github.com/Minecolonies/minecolonies/blob/f7a3b316a95375a239a1c6f228b3031497ce1847/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L177): The Cyclomatic Complexity of this method "requestMaterials" is 17 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [ColonyUtils.java#L18](https://github.com/Minecolonies/minecolonies/blob/f7a3b316a95375a239a1c6f228b3031497ce1847/src/main/java/com/minecolonies/coremod/util/ColonyUtils.java#L18): Add a private constructor to hide the implicit public one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1118)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/f7a3b316a95375a239a1c6f228b3031497ce1847/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/f7a3b316a95375a239a1c6f228b3031497ce1847/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
