### PR TITLE
Fixes Builds being too high or low.

### LINKED ISSUE #3285: Builder Gets Stuck if at build limit
### Minecolonies version

Version: 1.12.2-0.10.139-ALPHA

### Expected behavior

- Message from builder and/or warning indicating at build height/ builder quits building after error. 

### Actual behaviour

-  Builder tries to continuously build and stares into eternity.
   

### Steps to reproduce the problem

1. Get Close to Build Limit
2. Build Oak Town Hall
3. ???
4. ... Profit

### PR DESCRIPTION
**Pull request by Elrol**
Closes #3285 

# Changes proposed in this pull request:
- Checks if the build will exceed the build limit
- Remove the work order and send a message if so

Review please

### CODE REVIEW

**Comment by Asherslab** [comment]
~ Statement Recinded

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructureWithWorkOrder.java [hunk 1]
```diff
@@ -107,7 +108,17 @@ public void initiate()
                 }
 
                 worker.getCitizenChatHandler().sendLocalizedChat(COM_MINECOLONIES_COREMOD_ENTITY_BUILDER_BUILDSTART, job.getStructure().getBluePrint().getName());
-
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructureWithWorkOrder.java]: Wouldn't it be better to put this at the creation of the workorder and don't even send it to the builder?

Comment (Elrol) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructureWithWorkOrder.java]: I suppose it could be. I will move it over there.

Comment (marchermans) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructureWithWorkOrder.java]: Perfect! Nice catch

Comment (Elrol) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructureWithWorkOrder.java]: Fixed in the latest push.

**Comment by Asherslab** [comment]
Fixed a small something, otherwise this looks great, even better than before! LGTM


[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/3559/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Review by Asherslab — APPROVED** [review]
