### PR TITLE
fix #6161

### LINKED ISSUE #5395: Builder thinks he will get more items delivered than requested from crafter
Version: minecolonies-0.13.37-ALPHA-universal (but was also in 0.13.34)

### Expected behavior
Builders gets the items delivered he requests and then continue working.

### Actual behaviour
At some point the request for things to get crafted changes to this:

and once he gets the items delivered (which is the original number) he continues to wait for more - until you cancel the request.

### Steps to reproduce the problem
1. Have a sawmill setup to craft planks, stairs, signs, doors etc
2. Have the builder request crafting of one or more of these items
3. At some point the crafting / delivering amount starts to go up
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/
No messages in either latest.log or debug.log from Minecolonies since world load (this issue can also happen later not only after loading a world).

### LINKED ISSUE #6154: City hall says Unemployed: -1 and lists 2 Knights while I only have 1.
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2-forge-31.2.46
- MineColonies Version: minecolonies-0.13.464-BETA-universal
- Structurize Version: structurize-0.13.94-ALPHA-universal

## Problem description
In the City Hall it says i have -1 Unemployed citizens, and have 2 Knights employed. I only have 2 Guard towers but only 1 lists an employee. 

### Notes or related things
If I fire another worker so that it becomes unemployed, the City Hall will list 0 unemployed citizens.
I have tried to repair the Guard tower, and tore it down. This did not fix the issue and the City Hall kept listing 2 knights.
I have added pictures of both the guard tower window and the city hall window.
If needed I can provide the save before and after I tried the above changes.
I am playing minecolonies through the Valhelsia 2 modpack installed through twitch, and only manually added the FallingTree-1.15.2-2.4.0 mod and updated the minecolonies mod that came with the pack to the version listed above.

minecolonies tower window

minecolonies city hall info window

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #6161: freetointeractblocks & autodeletecoloniesinhours configs don't seem to function
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.469-ALPHA-universal.jar
- Structurize Version: structurize-0.13.94-ALPHA-universal.jar
- Related Mods and their Versions: Waystones_1.15.2-6.0.2.jar, CalemiUtils-1.15-1.1.4-MC1.15.2.jar
- Forge Version: 31.2.45 <-- you guys should include this in your templates!

## Expected behavior

**freetointeractblocks** - by including interactable blocks from other mods they should be available to access even in claims.

**autodeletecoloniesinhours** - after 7 days, inactive colonies are removed.

## Actual behavior

**freetointeractblocks** - they just aren't interactable. Players have had to whitelist the specific coordinates but of course, this is finicky and also poses issues with newer players who just don't know about that.

**autodeletecoloniesinhours** - on the official CtE [Dissonance] servers, I've noticed that old colonies aren't deleting. I've double checked the configs. I notice that doing a '/mc colony info XX' shows that no matter which colony I check, the player was last seen 0 days ago (which of course, is not true - there are 100's of colonies).

Whitelist Config:
image

## Steps to reproduce the issue

1. Use same Forge version, MineColonies version, Waystones (most importantly), and config file.
1. See if they're interactable.

### Logs

No relevant logs, but here are my [config files](https://pastebin.com/U4zrjpK3).

### Notes

No notes, but thanks for the amazing mod. Pack wouldn't be the same without it!

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #6161
Closes #5395
Closes #6154

# Changes proposed in this pull request:
- Performance improvement
- Fix free blocks config
- Fix abandoned colony calc

Review please

### CODE REVIEW

File: src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java [hunk 1]
```diff
@@ -994,4 +1018,30 @@ private static CompoundNBT writeLeafSaplingEntryToNBT(final BlockState state, fi
     {
         return new Tuple<>(NBTUtil.readBlockState(compound), new ItemStorage(ItemStack.read(compound), false, true));
     }
+
+    /**
+     * Load free blocks and pos from the config and add to colony.
+     */
+    private void discoverFreeBlocksAndPos()
+    {
+        for (final String s : MinecoloniesAPIProxy.getInstance().getConfig().getCommon().freeToInteractBlocks.get())
```
Comment (marchermans) [inline src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java:1027]: We are in the process of moving this kind of stuff out of configs and into tags.

Please adapt this old code to the new format.

**Review by marchermans — CHANGES_REQUESTED** [review]

File: src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java (hunk 1 above)
Comment (Raycoms) [reply src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java:1027]: I thought about this, but we got blocks and positions here + this here is important for servers to be backwards compatible. I can add a todo for 1.17 though.

Comment (someaddons) [reply src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java:1027]: I'm not sure if we really want to move these block permission exceptions stuff really over to tags

**Review by marchermans — APPROVED** [review]
