### PR TITLE
1.11 d-man delivery fix

### LINKED ISSUE #982: Modded Server Crash Minecolonies / by zero
### Minecolonies version

version ?.?.???? or curse 0.8.974 (1.11.2)

### Expected behavior

- Tried building a new colony on my new server everything fine.

### Actual behaviour

- Server crash. Sometimes immediately after giving a build order for the town hall, sometimes later at seemingly random points in time.
- I'm actually really unexperienced in programming, but I think it is trying to divide by zero somewhere, maybe it's something to do with the happiness value of the colony?

### How to solve the issue

- Well it didn't work in the version before this one, but maybe in an older one?
- Otherwise, I am lost.

[crash-2017-05-12_16.14.57-server.txt](https://github.com/Minecolonies/minecolonies/files/997133/crash-2017-05-12_16.14.57-server.txt)

### PR DESCRIPTION
**Pull request by xavierh**
Close  #982

When the worker chest is full, the dman take on stack but the item he deliver disappear.
 
# Changes proposed in this pull request:
- Fix incorrect javadoc
- AbstractBuilding.forceTransferStack return the stack when it can not transfer
- InventoryUtils.forceItemStackToItemHandler

Please review

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/util/InventoryUtils.java [hunk 1]
```diff
@@ -887,7 +887,7 @@ public static boolean addItemStackToProvider(@NotNull final ICapabilityProvider
      *
      * @param provider  {@link ICapabilityProvider} to add itemstack to.
      * @param itemStack ItemStack to add.
-     * @return True if successful, otherwise false.
+     * @return Empty when successful, otherwise return the itemStack which was supposed to be added.
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/util/InventoryUtils.java]: This is not correct.
It Returns the stack it replaced. Which might be the original stack if nothing is replaced, however this is not guaranteed.

File: src/main/java/com/minecolonies/coremod/util/InventoryUtils.java [hunk 2]
```diff
@@ -911,7 +911,7 @@ public static ItemStack addItemStackToProviderWithResult(@NotNull final ICapabil
      *
      * @param itemHandler {@link IItemHandler} to add itemstack to.
      * @param itemStack   ItemStack to add.
-     * @return True if successful, otherwise false.
+     * @return Empty if successfull, otherwise the itemStask which was supposed to be added.
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/util/InventoryUtils.java]: See above.

**Review by marchermans — CHANGES_REQUESTED** [review]
Javadoc is still not correct.

File: src/main/java/com/minecolonies/coremod/util/InventoryUtils.java (hunk 1 above)
Comment (xavierh) [reply src/main/java/com/minecolonies/coremod/util/InventoryUtils.java]: So it is empty when it has been transfered without swapping,
otherwise when not empty:
It return the itemStack it hase been swapped with
or
return the itemstack it cold not transfer.
Correct ?
Can it transfer partial stack ?

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 84 issues
* ![MAJOR][MAJOR] 30 major
* ![MINOR][MINOR] 48 minor
* ![INFO][INFO] 6 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L38](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L38): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 32 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L38](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L38): class "AbstractBuilding" has 68 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L106](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L106): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L106](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L106): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L107](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L107): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L107](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L107): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L108](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L108): Remove this reference to "BuildingBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L109](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L109): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L109](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L109): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L110](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L110): Remove this reference to "BuildingFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/util/InventoryUtils.java (hunk 1 above)
Comment (marchermans) [reply src/main/java/com/minecolonies/coremod/util/InventoryUtils.java]: Yes it can Transfer a partial stack. It will try partial first before swapping.

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 84 issues
* ![MAJOR][MAJOR] 30 major
* ![MINOR][MINOR] 48 minor
* ![INFO][INFO] 6 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L38](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L38): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 32 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L38](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L38): class "AbstractBuilding" has 68 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L106](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L106): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L106](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L106): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L107](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L107): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L107](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L107): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L108](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L108): Remove this reference to "BuildingBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L109](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L109): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L109](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L109): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L110](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L110): Remove this reference to "BuildingFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Review by marchermans — COMMENTED** [review]
The JavaDoc is now correct.

**Review by marchermans — APPROVED** [review]

**Comment by marvin-bitterlich** [comment]
:shipit: @Raycoms 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/980/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by xavierh** [comment]
@Kostronor Don't merge, I am not done with it

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 100 issues
* ![MAJOR][MAJOR] 44 major
* ![MINOR][MINOR] 49 minor
* ![INFO][INFO] 7 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.203 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 42 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): class "Colony" has 81 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): Refactor this class so it has no more than 20 fields, rather than the 35 it currently has. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [Colony.java#L172](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L172): Assign this magic number 5 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L547](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L547): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1007](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1007): Assign this magic number 20 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1008](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1008): Assign this magic number 60 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1132](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1132): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1134](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1134): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 100 issues
* ![MAJOR][MAJOR] 44 major
* ![MINOR][MINOR] 49 minor
* ![INFO][INFO] 7 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.203 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 42 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): class "Colony" has 81 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): Refactor this class so it has no more than 20 fields, rather than the 35 it currently has. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [Colony.java#L172](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java#L172): Assign this magic number 5 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L547](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java#L547): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1007](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1007): Assign this magic number 20 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1008](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1008): Assign this magic number 60 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1132](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1132): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1134](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1134): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/980/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by Raycoms** [comment]
:shipit:  Nice that one will bring stability to 1.11.2 finally I feel.

**Comment by marvin-bitterlich** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/980/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by xavierh** [comment]
This could have been an hotfix. I don't know when the next release is.
I will do the back port for 1.10 sometimes this week end
