### PR TITLE
Fix assistant hammer clearing

### LINKED ISSUE #10957: Assistant Hammer's area clear is too restrictive
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [x] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.924-snapshot

### Structurize Version

1.20.1-1.0.773-snapshot

### Related Mods and their Versions

Forge 47.4.0
DO 1.20.1-1.0.285-snapshot

### Current Behavior

Using the Assistant Hammer (any material, Iron Gold or Diamond all the same) works fine on tier 1 buildings; however once the building is complete and you go to upgrade, the hammer becomes effectively useless. Every swing returns the error "You need to wait until the Builder finishes clearing the area" - even if you right-click the exact block/area the builder is currently working in, and even if it is actually clear.

### Expected Behavior

I'm not sure what the best behavior is here and I'll leave that up to others.

### Reproduction Steps

1. Start constructing any tier 1 structure
2. Equip an Assistant Hammer
3. Make sure area is clear
4. Help builder, it should work
5. Once building is complete, upgrade and repeat step 4, it should not work

### Logs

n/a

### Anything else?

Overall the check for "is the area clear enough to allow the hammer to work" is a bit too restrictive; it seems (I haven't looked at the code and probably couldn't if I tried) but it seems to check for any foreign blocks not matching the schematic inside the build zone and if it finds even one it says no.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by someaddons**
Closes #10957
Closes #

# Changes proposed in this pull request
- Fix the assistant hammer requesting to wait for the builder clearing for leveling up buildings
- The enum for the building progress is now named BuildingProgressStage and got moved into its own class

## Testing
- [ x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/core/entity/ai/workers/util/BuildingStructureHandler.java [hunk 1]
```diff
@@ -98,7 +98,16 @@ public BuildingStructureHandler(
...
         this.structureAI = entityAIStructure;
         this.stages = stages;
-        this.stage = workOrder.getStage();
+
+        for (int i = 0; i < stages.length; i++)
+        {
+            final BuildingProgressStage stage = stages[i];
+            if (stage == workOrder.getStage())
+            {
+                this.stage = i;
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/core/entity/ai/workers/util/BuildingStructureHandler.java:107]: Why do we need to loop match here?

Comment (someaddons) [reply src/main/java/com/minecolonies/core/entity/ai/workers/util/BuildingStructureHandler.java:107]: because the stage index we're saving is not the enum ordinal, which is what originally created the bug.
The stages are an arbitrary array which do not have all stages in them and could even have stages in a custom order for which we save the index.

Comment (Raycoms) [reply src/main/java/com/minecolonies/core/entity/ai/workers/util/BuildingStructureHandler.java:107]: Can't we just save the stage here as well than as the enum value?

Comment (someaddons) [reply src/main/java/com/minecolonies/core/entity/ai/workers/util/BuildingStructureHandler.java:107]: I dont think so since the array determines the stage order, not the enum. But it is your code, ask yourself? :D

Comment (Raycoms) [reply src/main/java/com/minecolonies/core/entity/ai/workers/util/BuildingStructureHandler.java:107]: No, I mean, the loop you do to assign a stage, we could just store the stage in the class instead of the int version of it.

Comment (someaddons) [reply src/main/java/com/minecolonies/core/entity/ai/workers/util/BuildingStructureHandler.java:107]: the int we store
is NOT the int version of the stage
it is the index of the array of stages, it may point to whatever stage
