### PR TITLE
Prevent an exception during attribute calculation caused by modded items

### LINKED ISSUE #10726: Minecolonies: clipboard crashes the game after rightclicking it
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [x] Multi Player

### Minecraft Version

1.20

### MineColonies Version

 1.20.1-1.1.835-snapshot

### Structurize Version

structurize-1.20.1-1.0.765-snapshot

### Related Mods and their Versions

ATM 9 1.0.6

### Current Behavior

rightclicking the clipboard crashes the game immediately 

### Expected Behavior

working clipboard

### Reproduction Steps

idk

### Logs

https://gnomebot.dev/paste/mclogs/tlRKOyN 

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Thodor12**
Closes #10726

# Changes proposed in this pull request
- Add a try catch around the method and logging in case this happens, so we can tell what items cause this issue.

## Testing
- [ ] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/api/util/ItemStackUtils.java [hunk 1]
```diff
@@ -954,9 +954,18 @@ else if (foodStack.getItem() instanceof ItemBowlFood)
      */
     public static double getItemStackAttributeValue(final ItemStack itemStack, final Attribute attribute)
     {
-        final AttributeInstance instance = new AttributeInstance(attribute, (f) -> {});
-        itemStack.getAttributeModifiers(LivingEntity.getEquipmentSlotForItem(itemStack)).get(attribute).forEach(instance::addTransientModifier);
-        return instance.getValue();
+        try
+        {
+            final AttributeInstance instance = new AttributeInstance(attribute, (f) -> {
+            });
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/api/util/ItemStackUtils.java]: weird formatting

Comment (Thodor12) [reply src/main/java/com/minecolonies/api/util/ItemStackUtils.java]: That's what the formatter gave me /shrug

**Comment by rednax111** [comment]
Sorry, but I really dont understand what i have to do. Could you explain it please for a non-programmer?

**Comment by Thodor12** [comment]
Nothing, wait for the next release

**Comment by rednax111** [comment]
> Nothing, wait for the next release

So I cant play rn? Id really like to use my clipboard in my current colonie :')

**Comment by MotionlessTrain** [comment]
You need to update to 1.1.837, that has the fix
