### PR TITLE
Prevent removed mods' food from becoming air on read and crashes

### LINKED ISSUE #10577: Client crashing when clicking on Food Menu in restaurant
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

minecolonies-1.20.1-1.1.787-snapshot

### Structurize Version

structurize-1.20.1-1.0.763-snapshot

### Related Mods and their Versions

1. Forge 47.2.23
2. BlockUI 1.20.1-1.0.186-beta
3. https://www.curseforge.com/minecraft/modpacks/wolf-craft-colonies

### Current Behavior

Player r-clicks on restaurant ui
Clicks on menu tab
Crashes

### Expected Behavior

Player r-clicks on restaurant ui
Clicks on menu tab
Selects a variety of delicious minecolonies foods for their colonists

### Reproduction Steps

The player thought it had something to do with the cookery giving the "this block has lost its respective building, try restarting or loading a backup copy" message. They deconstructed and reconstructed the cookery but they still crashed when clicking on the food menu.
The style is Old English. Restaurant is level 3.

### Logs

https://gist.github.com/kezmodius/a61ec69087f369fd0b9c40eebe8cca2a

### Anything else?

2nd crash soon after has different info: https://gist.github.com/kezmodius/b63a763693dce2ababe6dd255becd0fc
I can get server logs if you need.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Thodor12**
Closes #10577 

# Changes proposed in this pull request
- Verify each item is actually food before adding it back to the menu

## Testing
- [ ] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/core/colony/buildings/modules/RestaurantMenuModule.java [hunk 1]
```diff
@@ -205,7 +207,11 @@ public void deserializeNBT(final CompoundTag compound)
         final ListTag minimumStockTagList = compound.getList(TAG_MENU, Tag.TAG_COMPOUND);
         for (int i = 0; i < minimumStockTagList.size(); i++)
         {
-            menu.add(new ItemStorage(ItemStack.of(minimumStockTagList.getCompound(i))));
+            final ItemStack itemStack = ItemStack.of(minimumStockTagList.getCompound(i));
+            if (ISFOOD.test(itemStack) || itemStack.getItem() instanceof IMinecoloniesFoodItem)
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/core/colony/buildings/modules/RestaurantMenuModule.java]: Don't we have somewhere a util call for this?

Comment (Thodor12) [reply src/main/java/com/minecolonies/core/colony/buildings/modules/RestaurantMenuModule.java]: Not that I could find, no

Comment (someaddons) [reply src/main/java/com/minecolonies/core/colony/buildings/modules/RestaurantMenuModule.java]: FoodUtils.EDIBLE is what we use elsewhere, dont think we need the instanceof. If if cannot be eaten it should not be on the menu

File: src/main/java/com/minecolonies/core/colony/buildings/modules/RestaurantMenuModule.java [hunk 2]
```diff
@@ -205,7 +202,11 @@ public void deserializeNBT(final CompoundTag compound)
         final ListTag minimumStockTagList = compound.getList(TAG_MENU, Tag.TAG_COMPOUND);
         for (int i = 0; i < minimumStockTagList.size(); i++)
         {
-            menu.add(new ItemStorage(ItemStack.of(minimumStockTagList.getCompound(i))));
+            final ItemStack itemStack = ItemStack.of(minimumStockTagList.getCompound(i));
+            if (FoodUtils.EDIBLE.test(itemStack))
```
Comment (uecasm) [inline src/main/java/com/minecolonies/core/colony/buildings/modules/RestaurantMenuModule.java:206]:
```
[12Jan2025 21:08:48.965] [Server thread/ERROR] [minecolonies/]: A Building minecolonies:cook(com.minecolonies.core.colony.buildings.workerbuildings.BuildingCook) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException: Cannot invoke "java.util.function.Predicate.test(Object)" because "com.minecolonies.api.util.FoodUtils.EDIBLE" is null
	at com.minecolonies.core.colony.buildings.modules.RestaurantMenuModule.deserializeNBT(RestaurantMenuModule.java:206) ~[minecolonies-1.20.1-1.1.791-snapshot.jar%23501!/:1.20.1-1.1.791-snapshot]
	at com.minecolonies.core.colony.buildings.AbstractBuilding.deserializeNBT(AbstractBuilding.java:376) ~[minecolonies-1.20.1-1.1.791-snapshot.jar%23501!/:1.20.1-1.1.791-snapshot]
	at com.minecolonies.core.colony.buildings.registry.BuildingDataManager.createFrom(BuildingDataManager.java:37) ~[minecolonies-1.20.1-1.1.791-snapshot.jar%23501!/:1.20.1-1.1.791-snapshot]
	at com.minecolonies.core.colony.managers.RegisteredStructureManager.read(RegisteredStructureManager.java:154) ~[minecolonies-1.20.1-1.1.791-snapshot.jar%23501!/:1.20.1-1.1.791-snapshot]
	at com.minecolonies.core.colony.Colony.read(Colony.java:707) ~[minecolonies-1.20.1-1.1.791-snapshot.jar%23501!/:1.20.1-1.1.791-snapshot]
	at com.minecolonies.core.colony.Colony.loadColony(Colony.java:671) ~[minecolonies-1.20.1-1.1.791-snapshot.jar%23501!/:1.20.1-1.1.791-snapshot]
	at com.minecolonies.core.colony.IColonyManagerCapability$Storage.readNBT(IColonyManagerCapability.java:181) ~[minecolonies-1.20.1-1.1.791-snapshot.jar%23501!/:1.20.1-1.1.791-snapshot]
	at com.minecolonies.core.event.capabilityproviders.MinecoloniesWorldColonyManagerCapabilityProvider.deserializeNBT(MinecoloniesWorldColonyManagerCapabilityProvider.java:53) ~[minecolonies-1.20.1-1.1.791-snapshot.jar%23501!/:1.20.1-1.1.791-snapshot]
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:127) ~[forge-1.20.1-47.2.23-universal.jar%23620!/:?]
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:35) ~[forge-1.20.1-47.2.23-universal.jar%23620!/:?]
	at net.minecraftforge.common.util.LevelCapabilityData.read(LevelCapabilityData.java:35) ~[forge-1.20.1-47.2.23-universal.jar%23620!/:?]
	at net.minecraftforge.common.util.LevelCapabilityData.load(LevelCapabilityData.java:26) ~[forge-1.20.1-47.2.23-universal.jar%23620!/:?]
	at net.minecraft.server.level.ServerLevel.lambda$initCapabilities$24(ServerLevel.java:1421) ~[server-1.20.1-20230612.114412-srg.jar%23615!/:?]
	at net.minecraft.world.level.storage.DimensionDataStorage.m_164868_(DimensionDataStorage.java:70) ~[server-1.20.1-20230612.114412-srg.jar%23615!/:?]
	at net.minecraft.world.level.storage.DimensionDataStorage.m_164858_(DimensionDataStorage.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23615!/:?]
	at net.minecraft.world.level.storage.DimensionDataStorage.m_164861_(DimensionDataStorage.java:39) ~[server-1.20.1-20230612.114412-srg.jar%23615!/:?]
	at net.minecraft.server.level.ServerLevel.initCapabilities(ServerLevel.java:1421) ~[server-1.20.1-20230612.114412-srg.jar%23615!/:?]
	at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:244) ~[server-1.20.1-20230612.114412-srg.jar%23615!/:?]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:337) ~[server-1.20.1-20230612.114412-srg.jar%23615!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:308) ~[server-1.20.1-20230612.114412-srg.jar%23615!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:164) ~[server-1.20.1-20230612.114412-srg.jar%23615!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[server-1.20.1-20230612.114412-srg.jar%23615!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23615!/:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

The predicates are not available at deserialization time; they're populated during datapack load, which happens later.  This check needs to be removed from here and put into the places the list is used instead
