### PR TITLE
Language adjustments & fix double claiming

### LINKED ISSUE #5736: The chunks claimed message which was introduced by #5734 is displayed even if no actual expansion happens
### Prerequisites 
- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.234-ALPHA-universal
- Structurize Version: structurize-0.13.64-ALPHA
- Related Mods and their Versions:

## Expected behavior
That the message is only displayed when new chunks have been claimed by my colony.

## Actual behavior
[07Sep2020 23:26:17.819] [Server thread/INFO] [minecolonies/]: WorkOrderBuild at location BlockPos{x=899, y=70, z=51} is using schematics/fortress/shepherd1 instead of schematics/fortress/shepherd1
[07Sep2020 23:26:17.821] [Server thread/INFO] [minecolonies/]: WorkOrderBuild at location BlockPos{x=899, y=70, z=51} is using schematics/fortress/shepherd2 instead of schematics/fortress/shepherd2
[07Sep2020 23:26:17.848] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] 1 chunks around shepherd have been claimed for your colony.
[07Sep2020 23:26:17.848] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Build Request Created!
[07Sep2020 23:26:35.543] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Builder Luna A. Johnson  started building shepherd2.

...

[07Sep2020 23:35:24.636] [Server thread/INFO] [minecolonies/]: WorkOrderBuild at location BlockPos{x=899, y=70, z=51} is using schematics/fortress/shepherd2 instead of schematics/fortress/shepherd2
[07Sep2020 23:35:24.640] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Builder Luna A. Johnson  finished building shepherd2.
[07Sep2020 23:35:24.640] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] 1 chunks around shepherd have been claimed for your colony.

The shepard is placed directly next to the townhall (fortress style) and surrounded by a citizen3 and a cowherder3 and further away (2 chunks) is also a guardtower2.

## Steps to reproduce the issue
1. Upgrade or build a normal hut (no guard tower or barracks which have a big claim area) in a place surrounded by other buildings with big claim areas
2. See the chunks claimed message appear both at the start of the build and when it finished even so these chunks have long since been claimed and even been build on before.

### Logs
I can upload the logs when required - but in this case I don't think it's needed as every building job has the same output as these above.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by ShadowProtocol**
Closes #5736 

# Changes proposed in this pull request:
* Fixed the inconsistent raid messages
* The research start message is more descriptive
* Added missing scepter names and missing advancement description
* Removed Asher's fascination with towers ... and with exclamation marks
    * Some more interesting titles were attempted for some advancements
* Some advancements' tooltips have been made more brief
* The Barrel is now called the Compost Barrel (seriously, confused me when I rejoined mc in 1.15)
* Players can no longer change styles when upgrading a hut
    * Fixes chunk claiming happening twice

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 1]
```diff
@@ -176,7 +176,11 @@ private void cancelClicked()
      */
     private void confirmClicked()
     {
+        if (building.getBuildingLevel() > 0 && !building.getStyle().equals(styles.get(stylesDropDownList.getSelectedIndex())))
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: Maybe we should here:
a) check if the hut is deconstructed
b) Send a message telling the player it failed?

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java]: forget b) I saw the code down there now

**Comment by ravenbuilder934** [comment]
Does this close #5736?

File: src/main/resources/assets/minecolonies/lang/en_us.json [hunk 2]
```diff
@@ -1256,102 +1258,103 @@
...
-  "advancements.minecolonies.complete_build_request_1_builder.title": "Build the Builder's Hut",
-  "advancements.minecolonies.complete_build_request_1_builder.description": "If you keep your Builder fed and fulfill their requests, they should start and finish building your first hut!",
+  "advancements.minecolonies.place_townhall.description": "Place the Town Hall using the Build Tool - with this tool you can choose the style and hall position.",
+  "advancements.minecolonies.create_build_request_1_builder.title": "The Builder Begins",
+  "advancements.minecolonies.create_build_request_1_builder.description": "Craft and place a Builder's Hut with the Build Tool, hire a Builder (automatic by default), and tell them to build their hut!",
+  "advancements.minecolonies.click_gui_button_fulfill.title": "Fulfillment Comes Cheap",
+  "advancements.minecolonies.click_gui_button_fulfill.description": "Fulfil one of the Builder's requests for tools or resources using the buttons in their request screen",
```
Comment (ravenbuilder934) [inline src/main/resources/assets/minecolonies/lang/en_us.json]:
```suggestion
  "advancements.minecolonies.click_gui_button_fulfill.description": "Fulfill one of the Builder's requests for tools or resources using the buttons in their request screen.",
```

File: src/main/resources/assets/minecolonies/lang/en_us.json [hunk 3]
```diff
@@ -1256,102 +1258,103 @@
...
   "advancements.minecolonies.complete_build_request_1_shepherd.title": "Mary had a Little Lamb",
-  "advancements.minecolonies.complete_build_request_1_shepherd.description": "Sometimes you really need some soft wool in your life. Build a Shepherd's Hut to take advantage of those poor unsuspecting sheep!",
+  "advancements.minecolonies.complete_build_request_1_shepherd.description": "Build a Shepherd's Hut to take advantage of those poor unsuspecting sheep",
   "advancements.minecolonies.complete_build_request_1_sifter.title": "Diamond in the Rough",
-  "advancements.minecolonies.complete_build_request_1_sifter.description": "Sometimes you'll find goodies inside random blocks. Build a Sifter's Hut to take advantage of that!",
-  "advancements.minecolonies.complete_build_request_1_swine_herder.title": "Getting the Bacon",
-  "advancements.minecolonies.complete_build_request_1_swine_herder.description": "Nobody can resist bacon, build a Swineherd's Hut so your citizens don't miss out!",
+  "advancements.minecolonies.complete_build_request_1_sifter.description": "Build a Sifter's Hut to take advantage of extra resources hiding in blocks",
```
Comment (ravenbuilder934) [inline src/main/resources/assets/minecolonies/lang/en_us.json:1333]:
```suggestion
  "advancements.minecolonies.complete_build_request_1_sifter.description": "Build a Sifter's Hut to take advantage of extra resources hiding in blocks!",
```

Comment (ShadowProtocol) [reply src/main/resources/assets/minecolonies/lang/en_us.json:1333]: My point was to avoid the excessive use of exclamation marks! Because vanilla doesn't use them often! And if everything's emphasized, effectively nothing is! So we can't make greater achievements seem more special!

File: src/main/resources/assets/minecolonies/lang/en_us.json (hunk 2 above)
Comment (ShadowProtocol) [reply src/main/resources/assets/minecolonies/lang/en_us.json]: Good catch. Though if you look at vanilla's advancements, they only use full stops when there's more than one sentence.

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/5849/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Review by someaddons — APPROVED** [review]
