### PR TITLE
Small fixes

### LINKED ISSUE #7876: Wrong citizen being removed or replaced in a house when moved as a guard and/or when a child is born.
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1 (Forge 37.1.1)
- MineColonies Version: 1.17.1-1.0.201-ALPHA, 1.17.1-1.0.275-ALPHA & 1.17.1-1.0.312-BETA (beta being the most up to date)
- Structurize Version: structurize-1.17.1-0.13.264-ALPHA & structurize-1.17.1-1.0.311-BETA
- Related Mods and their Versions: [None that I know that affects that)

## Expected behavior
When a Citizen is moved as a guard, they are the only one removed from their assigned house. When an empty spot is available and childs are turned on, that empty spot will be used.

## Actual behavior
I've had this issue since I started my colony in 1.17.1, which was on alpha 201, even today, on beta 312, which is newer than current alpha, the issue persist. It creates a lot of issues with bed assignations and is annoying to fix.

I have Housing set to MANUAL, and Child will be born set to ON.

When a guard is moved to a tower or barrack, their spot and sometimes a random other spot will also be freed in their house. It does not happen all the time, but I've been so often, I have to keep a spreadsheet up to date to fix the issue manually and it's time consuming. This issue will also affect any newly assigned child that will be born in that house.

The wrongly removed citizen will still acts as if it's their house, and their assigned bed in the house, and will go sleep there during the night, but the UI will not show it. If you open the UI when the guard left, but no child is born, their name will be missing from assigned citizens, and when you select the "assign citizen" button, their name will NOT appear in the list. If you go to another house and remove anyone, you can then add the citizen that is "missing" from the other house then return and assign them back.

Now if a child is born in that said house, it will do so because the mod behavior will check if there are empty spots in that house, it will then check who lives there in order to give them a name and assigns them a bed in that house. That child can end up, if it wasn't fixed before, being assigned to that ghosted citizen, which is still assigned to that house and a bed. Sometimes the child will be assigned to the same bed as that previous citizen, making it impossible for both of them to sleep at night. 

I've had a recent occurrence where I had 2 citizen from 2 different houses sent as guards on the same day. So there was one spot empty in 2 different houses. But with that issue, both children were born in the same house and were both assigned ghosted citizen, so I ended up with 4 citizen in a level 3 house (max 3 citizen).

This behavior has been going on with any houses (any level) , and the tavern (any level). The only real way to fix it is to kick out all the current residents of another house, assign all of those from the bugged house, then kick them again, assign back the original people and then go back to the bugged out and re-assign everyone.

I am not sure if the guard being removed and the child being born are both independent issues, or if they're the result of each other.

## Steps to reproduce the issue

1. Have a colony set up, housing set to MANUAL - Child will be born to ON
2. Build a tavern and assign all your citizens (faster than having to make a house on level 2 or 3)
3. Make a guard tower
4. Assign guard for the tower
5. Wait for a child to be born
6. Check the Tavern UI and check for assigned citizen, there might be a missing name from someone who wasn't set as a guard, and you can't assign them back. The child might also be there, but still have an empty spot (it might NOT always happen ,but it does frequently.)

### Logs

Apart from a lot of [Server thread/WARN]: Could not find iterator for value: using default instead! , I don't see anything in the latest.log that could point to anything.
- latest.log: [latest.log](https://github.com/ldtteam/minecolonies/files/7780699/latest.log)

I did not have a crash related to that, the only crashes I had were related to the miner position on ladder when I was connecting to the server. Which seems gone since I updated version, I will post something different if it happens again.
- crashlog: NONE

### Notes
I've waited before reporting this because it took me a while to figure out what was happening. Each time I was having new children, I would often not get the colonists being all tucked into bed message, and I often saw weird empty spots in my tavern when I was going to check, or assign different people.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #7897: Null Pointer Exception on server in com.minecolonies.api.tileentities.AbstractTileEntityColonyBuilding
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.18.1-1.0.278-RELEASE
- Structurize Version: 1.18.1-1.0.319-BETA
- Forge Version: 39.0.0
- Java Version: 17.0.1

## Problem description

Periodically, my server running a small mix of Mods, including MineColonies and Structurize, will produce the following Null Pointer Exception in the log:
[08:38:44 FATAL]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "com.minecolonies.api.tileentities.AbstractTileEntityColonyBuilding.m_6596_()" because the return value of "com.minecolonies.api.colony.buildings.IBuilding.getTileEntity()" is null
	at com.minecolonies.coremod.network.messages.server.colony.building.MarkBuildingDirtyMessage.onExecute(MarkBuildingDirtyMessage.java:45) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2356!:1.18.1-1.0.278-RELEASE]
	at com.minecolonies.coremod.network.messages.server.AbstractBuildingServerMessage.onExecute(AbstractBuildingServerMessage.java:81) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2356!:1.18.1-1.0.278-RELEASE]
	at com.minecolonies.coremod.network.messages.server.AbstractColonyServerMessage.onExecute(AbstractColonyServerMessage.java:140) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2356!:1.18.1-1.0.278-RELEASE]
	at com.minecolonies.coremod.network.messages.splitting.SplitPacketMessage.lambda$onExecute$1(SplitPacketMessage.java:128) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2356!:1.18.1-1.0.278-RELEASE]
	at net.minecraftforge.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:222) ~[forge-1.18.1-39.0.0-universal.jar%2373!:?]
	at com.minecolonies.coremod.network.messages.splitting.SplitPacketMessage.onExecute(SplitPacketMessage.java:128) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2356!:1.18.1-1.0.278-RELEASE]
	at com.minecolonies.coremod.network.NetworkChannel.lambda$setupInternalMessages$4(NetworkChannel.java:256) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2356!:1.18.1-1.0.278-RELEASE]
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge-1.18.1-39.0.0-universal.jar%2373!:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge-1.18.1-39.0.0-universal.jar%2373!:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge-1.18.1-39.0.0-universal.jar%2373!:?]
	at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:82) ~[forge-1.18.1-39.0.0-universal.jar%2373!:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:82) ~[forge-1.18.1-39.0.0-universal.jar%2373!:?]
	at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:89) ~[forge-1.18.1-39.0.0-universal.jar%2373!:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:89) ~[forge-1.18.1-39.0.0-universal.jar%2373!:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerGamePacketListenerImpl.java:1416) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2369!:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

### Notes or related things

Note that this does not cause any crashing or other bad behavior and things seem to continue running without issues.  Users on the server do not indicate there is any obvious issue.  As such, this appears to be a very benign error.  Just a bit alarming is all.
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #7897
Closes #7923
Closes #7876

# Changes proposed in this pull request:
- Make sure assignment map is not modified
- Handle build tool placement better
- Avoid NPE

Review please

### CODE REVIEW

**Review by someaddons — APPROVED** [review]

File: src/main/java/com/minecolonies/coremod/network/messages/server/BuildToolPlaceMessage.java [hunk 1]
```diff
@@ -205,8 +205,7 @@ private static void handleHut(
             return;
         }
 
-        final String hut = sn.getSection();
-        final ItemStack stack = BuildingUtils.getItemStackForHutFromInventory(player.inventory, hut);
+        final ItemStack stack = new ItemStack(state.getBlock(), 1);
         final Block block = stack.getItem() instanceof BlockItem ? ((BlockItem) stack.getItem()).getBlock() : null;
```
Comment (uecasm) [inline src/main/java/com/minecolonies/coremod/network/messages/server/BuildToolPlaceMessage.java:209]: This `block` initialization seems a bit roundabout now that `stack` seems to be guaranteed to be a `BlockItem`...
