### PR TITLE
Breeding request refactoring.

### LINKED ISSUE #11037: Stack count mismatch
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [x] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.975

### Structurize Version

1.20.1-1.0.775

### Related Mods and their Versions

Forge 47.4.0
Modpack: https://www.curseforge.com/minecraft/modpacks/wolf-craft-colonies

### Current Behavior

Noticed in server logs. No player has complained. 
Stack count mismatch (stack=2 wheat_seeds, count=15). ItemStack's count will be ignored. 
java.lang.Exception: Stack constructor

Shindria suggested I post this when I asked on discord if it's a known issue.

### Expected Behavior

No exceptions?

### Reproduction Steps

Uncertain.

### Logs

https://gist.github.com/kezmodius/33de4cca6050159daa72a9dbf5eae19c

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by armele**
Closes #11037

# Changes proposed in this pull request
Convert ItemStack pattern used for getBreedingItems to ItemStorage pattern.

## Testing
- [X] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/core/colony/buildings/modules/AnimalHerdingModule.java [hunk 1]
```diff
@@ -23,15 +24,15 @@ public class AnimalHerdingModule extends AbstractBuildingModule
 {
     private final JobEntry jobEntry;
     private final Predicate<Animal> animalPredicate;
-    private final ItemStack breedingItem;
+    private final ItemStorage breedingItem;
 
     public AnimalHerdingModule(@NotNull final JobEntry jobEntry,
                                @NotNull final Predicate<Animal> animalPredicate,
                                @NotNull final ItemStack breedingItem)
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/core/colony/buildings/modules/AnimalHerdingModule.java]: Probably this here should already be an ItemStorage input

File: src/main/java/com/minecolonies/core/entity/ai/workers/production/herders/EntityAIWorkCowboy.java [hunk 2]
```diff
@@ -164,13 +164,12 @@ && walkToBuilding())
             return DECIDE;
         }
 
-        if (equipItem(InteractionHand.MAIN_HAND, Collections.singletonList(building.getMilkInputItem())) && !walkingToAnimal(cow))
+        if (equipItem(InteractionHand.MAIN_HAND, Collections.singletonList(new ItemStorage(building.getMilkInputItem().getItem(), building.getMilkInputItem().getCount()))) && !walkingToAnimal(cow))
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/core/entity/ai/workers/production/herders/EntityAIWorkCowboy.java:167]: for equip this is always 1, I guess

File: src/main/java/com/minecolonies/core/entity/ai/workers/production/herders/AbstractEntityAIHerder.java [hunk 3]
```diff
@@ -220,8 +220,12 @@ public IAIState decideWhatToDo()
             }
 
             final boolean hasBreedingItem =
-              InventoryUtils.getItemCountInItemHandler((worker.getInventoryCitizen()),
-                (ItemStack stack) -> ItemStackUtils.compareItemStackListIgnoreStackSize(module.getBreedingItems(), stack)) > 1;
+                InventoryUtils.getItemCountInItemHandler(worker.getInventoryCitizen(),
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/core/entity/ai/workers/production/herders/AbstractEntityAIHerder.java]: here we might want a storage based utility to avoid the bad performance stream. This is quite often called

File: src/main/java/com/minecolonies/core/entity/ai/workers/production/herders/EntityAIWorkCowboy.java (hunk 2 above)
Comment (armele) [reply src/main/java/com/minecolonies/core/entity/ai/workers/production/herders/EntityAIWorkCowboy.java:167]: the equipItem function has a side effect of placing an order if needed (checkIfRequestForItemExistOrCreateAsync is called), so I think we might want to keep the amount here? (So we're ordering at least the 2 needed for breeding, and not 1?)

**Review by Raycoms — APPROVED** [review]

**Review by someaddons — APPROVED** [review]
