### PR TITLE
Craft fixes

### LINKED ISSUE #7350: Blacksmith not using best available material when crafting tools for colonists
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.259-ALPHA
- Structurize Version: 0.13.197-ALPHA
- Related Mods and their Versions:

## Expected behavior
When a colonist requests a new tool from the the blacksmith, it should use the best material the colonist can use.  In my setup, this should be iron tools.

## Actual behavior
The blacksmith is only crafting stone tool recipes.  He knows all wood, stone and iron recipes, and there are plenty of all materials in the warehouse.  The blacksmith hut and requesting colony huts are all level 4.  The colonists will use iron and even diamond tools normally if the player supplies them.  This behavior is the same for all tools - axe, pick, etc.

## Steps to reproduce the issue

* Make sure enough materials for iron tools are in warehouse.  Also make sure there are no tools in warehouse.
* Remove tool from any colonist to force them to request a new tool from blacksmith.
* Only stone tools are created.

### Logs

https://gist.github.com/Oraxian/8368f971ca417efb91aba63c3a1aa897

### Notes
In the recipe list, the up and down arrows do not work, so the list order cannot be changed.  I'm not sure if this related, but thought I should mention it.  In my blacksmith recipe list, the order (from top to bottom) is iron - stone - wood.  I didn't this order mattered, but I could be wrong.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #7351: Crafter recipe lists not updating until relog
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.259-ALPHA
- Structurize Version: 0.13.197-ALPHA
- Related Mods and their Versions:

## Expected behavior
This was buried in an issue that was closed, so I'm breaking it out here.  

For any crafter that has a recipe list, the arrows that reorder the recipes should update in the UI when the player clicks on them.  

## Actual behavior
The recipe list does not appear to change - it looks like the arrow buttons do not work.  However, if the player exits and logs back into the world, the list is updated.  A relog is required - just closing the UI and going back in does not display the update.  Teaching and removing recipes update the UI as expected.  Only the reordering seems to be impacted.

I was able to reproduce this problem both in my current world that is frequently updated, and a newly created creative world.

## Steps to reproduce the issue
Use the arrow buttons in any crafter recipe list.  Exit the game and log back in.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #7350
Closes #7351
Closes #

# Changes proposed in this pull request:
- Fixes issue with recipe list not updating priority
- Fix issue with priority not being respected, add setting and research to allow triggering it warehouse based
- Adjust buildtool usage when placing building, to put the buildtool in the position of the building and warn if no buildtool in inventory

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/network/messages/server/SwitchBuildingWithToolMessage.java [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+
+        for (int i = 9; i < player.inventory.getSizeInventory(); i++)
+        {
+            if (player.inventory.getStackInSlot(i).getItem() == ModItems.buildTool.get())
+            {
+                buildToolSlot = i;
+            }
+        }
+
+        if (stackSLot != buildToolSlot)
```
Comment (uecasm) [inline src/main/java/com/minecolonies/coremod/network/messages/server/SwitchBuildingWithToolMessage.java]: This looks like if it finds neither item then it will do nothing, but if it finds only the build tool it will swap that with whatever was in slot 0, and if it finds only the target stack then it will destroy whatever was in slot 0 and replace it with a build tool?  That doesn't sound right.
(Not that I'm entirely clear on the intended purpose of this message.)

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/network/messages/server/SwitchBuildingWithToolMessage.java]: It shouldn't be possible for the stack to not exist, but true I'd better safeguard this.

**Review by someaddons — DISMISSED** [review]

**Review by marchermans — DISMISSED** [review]

**Review by someaddons — APPROVED** [review]
