### PR TITLE
Fix Stock View sometimes not showing all items

### LINKED ISSUE #4758: Stock window not showing all items if multiple stacks of the same item are in the same rack
### Minecolonies version
Version: 0.11.880

### Expected behavior
I expect the Stock window to show the amount of all items of the same type added together.

### Actual behaviour
If more than one stack(doesn't have to be a full stack) of the same type of item is in the same rack, it only counts one of the stacks.
Under some circumstances it also shows more items of a type than there are, but i can't reproduce that yet.

### Steps to reproduce the problem
1. Build a warehouse(i tested it with nordic and fortress level 2)
2. distribute a stack of items into multiple slots of the same rack
3. go to the stock window in the warehouse block
4. see only some of your items

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log:[ByrpvEJA](https://pastebin.com/ByrpvEJA)
- crashlog: Not a Crash.

### PR DESCRIPTION
**Pull request by ToMe25**
Closes #4758
Closes #
Closes #

# Changes proposed in this pull request:
- Fix item handling in StockView to prevent it from only showing the amount if items from one stack per Item type per rack.
- Add the Hut block inventory to the stock view.
-

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
Stack has a max size of 64, and for some things even less, you'll need to store this in an itemStorage object to fix this.

**Comment by ToMe25** [comment]
> Stack has a max size of 64

In theory maybe, but it does work like this as can be seen here:

All these Hut blocks are in the same rack.

**Comment by lexustec** [comment]
It should count together all Stacks.. so it shows ONLY one Itemtype per Stack.. so You know exactly how much You have in a glance

It is not a chest view where You have stacks it is like the View in Refined storage

**Comment by ToMe25** [comment]
I moved the Fix to the TileEntityRack class as that seems to be the less hacky solution, tell me if i should moce it back.
> It should count together all Stacks

i know, it still does that, the problem before was that it only counted some stacks.

**Comment by lexustec** [comment]
You mean it counted the Stacks twice ?

**Comment by ToMe25** [comment]
No.
lets say you have two stacks of cobble in one rack, then it counted only one of them.
If you however have two stacks of cobble in different racks it counts both.

File: src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java [hunk 1]
```diff
@@ -225,12 +225,14 @@ public void updateItemStorage()
...
+            final ItemStack stackCopy = stack.copy();
+            final ItemStorage storage = new ItemStorage(stackCopy);
             int amount = ItemStackUtils.getSize(stack);
             if (content.containsKey(storage))
             {
                 amount += content.remove(storage);
             }
+            stackCopy.setCount(amount);
             content.put(storage, amount);
         }
```
Comment (Raycoms) [inline src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java]:
```
int amount = ItemStackUtils.getSize(stack);
if (content.containsKey(storage))
{
amount += content.remove(storage);
}
content.put(storage, amount);
```
Why isn't this enough?

**Comment by lexustec** [comment]
Okay ,.... i tried that btw.. this is funny maybe i lost sth while having issues with my GIT

File: src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java (hunk 1 above)
Comment (ToMe25) [reply src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java]: because [this](https://github.com/ldtteam/minecolonies/blob/84fa0aaf06052529fb9c664f27a6f715c3b2bb2b/src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java#L150) only uses the stack, not the amount.
both in the current, and my changed version.

Comment (lexustec) [reply src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java]: that should work normally

Comment (Raycoms) [reply src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java]: it gets the amount from the stack and adds it to the amount in the map. That should be enough

Comment (ToMe25) [reply src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java]: Should i change it back to how it was in the second commit then? that didn't change TileEntityRack at all.

Comment (Raycoms) [reply src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java]: none of this should be necessary of the above.

Comment (ToMe25) [reply src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java]: does that mean you prefer leaving this alone like it was, and just changing the WindowHutAllInventory?

Comment (Raycoms) [reply src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java]: The above code is correct. It should not be the cause of any issue.

Comment (ToMe25) [reply src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java]: ok i changed it back.

File: src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java [hunk 2]
```diff
@@ -147,7 +147,9 @@ private void updateResources()
 
                 for (final Map.Entry<ItemStorage, Integer> entry : storage.entrySet())
                 {
-                    items.add(new ItemStorage(entry.getKey().getItemStack(), entry.getValue(), false).getItemStack());
+                	ItemStack stack = entry.getKey().getItemStack().copy();
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java]: This does not work officially, and even though it works in the current Mc version it is not officially supported. As such please change this to use itemstorage instances or use the proposed change by @Raycoms.

**Review by marchermans — CHANGES_REQUESTED** [review]

File: src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java (hunk 2 above)
Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java]: should i just change the items list to use ItemStorage instead of ItemStack then?

**Comment by Raycoms** [comment]
okay, I was looking over all of this again and I think there are things we can improve:

https://github.com/ldtteam/minecolonies/blob/3f60f2e9d059d2f00f6d923b273936db8c7faba9/src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java#L169

Instead of filling a list and then filling the map in my link. We can move this map up to the beginning of the class and count up in this map from the beginning. This should also solve this issue.

**Comment by ToMe25** [comment]
OK i will do that.

**Comment by lexustec** [comment]
It happened after i changed the code from the original aproach with the new map   

```
if (rack instanceof TileEntityRack)
            {
                 int allSlots = ((AbstractTileEntityRack) rack).getInventory().getSlots();
                        Log.getLogger().info("Used Slots " + allSlots);
                        for (int i = 0; i < allSlots; i++)
                        {
                            if (!((AbstractTileEntityRack) rack).getInventory().getStackInSlot(i).isEmpty())
                            {
                                items.add(((AbstractTileEntityRack) rack).getInventory().getStackInSlot(i));
                            }
                        }


            }

```

that was the old aproach..

**Comment by ToMe25** [comment]
@Raycoms you mean like this?

**Comment by lexustec** [comment]
the change of allItems will break the view

**Comment by ToMe25** [comment]
Again if absolutely no change to TileEntityRack is wanted, i can undo that and instead get the value of the map in WindowHutAllInventory and set the amount there.

**Comment by ToMe25** [comment]
> the change of allItems will break the view

allItems? i am not messing with anything names allItems.

**Comment by lexustec** [comment]
sorry i read it wrong

File: src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java (hunk 2 above)
Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java]: I did get rid of it now.

File: src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java [hunk 3]
```diff
@@ -135,7 +135,7 @@ private void updateResources()
     {
         final List<BlockPos> containerList = building.getContainerList();
 
-        final List<ItemStack> items = new ArrayList<>();
+        final Map<ItemStorage, ItemStorage> storedItems = new HashMap<>();
         final World world = building.getColony().getWorld();
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java:139]: Yes better, and make this a Map<ItemStorage, Integer> and increment the quantity in the. And keep ItemStorage the same

File: src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java [hunk 4]
```diff
@@ -231,6 +231,7 @@ public void updateItemStorage()
             {
                 amount += content.remove(storage);
             }
+            storage.setAmount(amount);
             content.put(storage, amount);
```
Comment (Raycoms) [inline src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java]: this should not be necessary.

Comment (ToMe25) [reply src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java]: ok i will remove it.

File: src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java [hunk 5]
```diff
@@ -158,29 +165,25 @@ else if (rack instanceof ChestTileEntity)
...
-                storedItems.put(currentStorage, currentStorage);
-            }
-        }
-
-        final List<ItemStorage> filterItems = new ArrayList<>(storedItems.keySet());
+        final List<ItemStorage> filterItems = new ArrayList<>();
+        storedItems.forEach((storage, amount) -> {
+            storage.setAmount(amount);
+            filterItems.add(storage);
+        });
```
Comment (ToMe25) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java:182]: Is like this OK, or do i have to find another way to set the amount of the ItemStorage?

File: src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java (hunk 4 above)
Comment (ToMe25) [reply src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java]: I removed it.

File: src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java (hunk 3 above)
Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java:139]: Did that.

File: src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java (hunk 5 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java:182]: Should be fine like this.
Did you test this?

Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java:182]: Yes i did.

Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java:182]: If you want to suggest any more changes, i will look at it tomorrow, today its late enough :)

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java:182]: Looks fine for me now. Does this solve all the issues there were before?

Can you add an additional check to query the rack from the position of the building itself (it's not include din the list of containers, so it needs an additional line to add the stacks from it.

Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java:182]: "Does this solve all the issues there were before?" idk, i don't know about many issues with this view, i just made this to fix the linked issue.
"Can you add an additional check to query the rack from the position of the building itself" I can do that, but i think lexustec said he is working on that, so i wouldn't put that in here.

Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/client/gui/WindowHutAllInventory.java:182]: "Can you add an additional check to query the rack from the position of the building itself"
I have a working version for the warehouse now, i will test it with some other buildings, and than hopefully push it.

**Comment by lexustec** [comment]
saw it ..... nice fix :-)

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/4759/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Comment by ToMe25** [comment]
For some reason this currently isn't working for vanilla chests, i will work on fixing that now.

**Review by marchermans — DISMISSED** [review]

**Comment by ToMe25** [comment]
I looked at the problem with the chests some more, and i think there are three solutions for it, but i am not sure which one to use.
The solutions:
1. Ignore that this isn't working with chests as it didn't before this PR either
2. Create a custom packet to transfer the chest inventory to the client to read it
3. I am not sure, but maybe it would be possible to (mis?)use a vanilla packet to transfer the chest contents

Please tell me what the prefered solution would be

**Comment by Raycoms** [comment]
That sounds weird, the chest contents should also exist on the client side, don't they?

**Comment by ToMe25** [comment]
I haven't found anything that is able to get them clientside without a custom packet, and the clientside tileentity doesn't contain any items even when the chest is full.

**Comment by Raycoms** [comment]
@OrionDevelopment did you know that?

**Comment by ToMe25** [comment]
I also thought that is weird, but i couldn't find anything that is able to read this clientside.

**Comment by marchermans** [comment]
No this is the normal state. All vanilla inventories do not sync their inventory. Only when a container is opened the container contents are synced.

**Comment by ToMe25** [comment]
So should i just leave the chest problem be, or make a packet for that?
I don't think there is a vanilla packet for this.

**Comment by Raycoms** [comment]
I'd say then remove the vanilla support code and leave it be. And we tell our schematic authors to not use chests at all anymore =)

**Comment by ToMe25** [comment]
ok, but i think no chests will be a loss for the mod, as just one type of storage just always has places where it looks wrong.

**Comment by lunadragnstar** [comment]
We primarily use racks, but sometimes we use chests and barrels in builds

**Comment by ToMe25** [comment]
barrels already don't fully work, i think about making a pr for that tho...
but i probably wont as this doesn't supports chests now anyways.

**Comment by lunadragnstar** [comment]
Is this specifically for the warehouse, or for all storage

**Comment by ToMe25** [comment]
is what for the warehouse or all storage?

**Comment by Raycoms** [comment]
@lunadragnstar it's for all buildings.

**Comment by Raycoms** [comment]
@OrionDevelopment what is your opinion on this?

**Review by marchermans — APPROVED** [review]
Not the greatest of solutions. But alright.
