### PR TITLE
Somefixes

### LINKED ISSUE #10504: Christmas server scrolls de-register their waypoints after a time
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.1.759

### Structurize Version

1.0.760

### Related Mods and their Versions

The Patreon Christmas server with  MColonies1.1.759

### Current Behavior

A teleport scroll made by the Enchanter is registered to a townhall. The scroll shows the name of the townhall. After some time and going to another colony or through the nether (not all instances of deregistering are because the scroll went through the nether), the scroll doesn't show the name of its registered townhall. Sometimes, if we're lucky, we can use the scroll and be sent to the registered townhall, sometimes it doesn't work at all, but sometimes we're teleported to some random place. Anastasia mentioned she was teleported off of a cliff with no buildings around.

### Expected Behavior

After registering a scroll to a townhall and after any length of time from the time of registration, I expect that the scroll will take me back to the townhall from any place and any dimension.

### Reproduction Steps

Log onto the Christmas server
Register a scroll with the townhall there.
Go to someone else's colony.
Review what happens to the scroll.
Do the same after some period of time has passed.
Do the same after running through the nether with the scroll in your inventory.

### Logs

No log available

### Anything else?

See references in Discord to players sharing their experiences with the teleportation scrolls.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #10505: Concrete mixer does not stop making concrete
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.817-1.21.1

### Structurize Version

1.0.755-1.21.1

### Related Mods and their Versions

NeoForge: 21.1.69

### Current Behavior

I have tried this with a clean instance, just minecolonies and whatever dependencies curseforge auto installed. The issue begins when a request for concrete is placed, either by postbox or builder. A courier will take the necessary materials to mixer, he starts making powder and he turns the powder into concrete. There are two things that might happen next. He either places a few blocks in the rack or he keeps it all on him. The courier comes back, finds no concrete (even the few blocks) and creates a new task in the warehouse for more materials for concrete. Even if at some point he places enough concrete to complete the order, the courier refuses to pick them up and keeps bringing more material which is turned into powder and then concrete. When you manually request a pickup, the courier will get the concrete and put it in the warehouse, instead of completing the original request. The mixer will continue making concrete until you cancel the request or use the reset request command (if there is enough concrete in the warehouse, otherwise the loop will begin again). Something similar happens when requesting just powder. He makes the powder but starts converting it into concrete. The courier keeps delivering materials for powder and creates another loop. This issue has been tested by me and another person on discord, on brand new minecolonies instances with no other mods, with the same exact results. 

### Expected Behavior

Request concrete, couriers provides materials, mixer makes powder and converts to concrete, courier picks up concrete and delivers the original request (player or builder). 

### Reproduction Steps

1. Add a stack of sand, gravel and dye to warehouse
2. Request concrete from postbox
3. Watch as the mixer creates concrete for ever

### Logs

https://gist.github.com/mafamaul/534966fd99c5ccd4239a9b79f5f3e70f

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #10508: Smeltery upgrade achivments need updating
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

minecolonies-1.20.1-1.1.740-snapshot

### Structurize Version

structurize-1.20.1-1.0.742-RELEASE

### Related Mods and their Versions

_No response_

### Current Behavior

The two upgrade achievements, [Double Trouble] and [That's Oresome!], are still referencing the old hut behaviors of doubling and tripling ore outputs. Causing confusion on how the hut works.

### Expected Behavior

Achievements should be reworded to reflect current behaviors 

### Reproduction Steps

Get the achievements for upgrading the Smeltery

### Logs

none

### Anything else?

none

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #10504 
Closes #10508 
Closes #10505 

# Changes proposed in this pull request
- Fix concrete mixer infinite loop
- Fix concrete mixer achievement descriptions
- Cache colony name in the tp scroll & calculate a non in air position

## Testing
- [x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/core/items/ItemScrollColonyTP.java [hunk 1]
```diff
@@ -133,6 +134,10 @@ public void appendHoverText(
         {
             colonyDesc = Component.literal(colony.getName());
         }
+        else if (stack.getOrCreateTag().contains(TAG_CACHED_COLONY_NAME))
+        {
+            colonyDesc = Component.literal(stack.getOrCreateTag().getString(TAG_CACHED_COLONY_NAME));
```
Comment (someaddons) [inline src/main/java/com/minecolonies/core/items/ItemScrollColonyTP.java:139]: we actuall yhad that before and removed it since it doesnt adjust to changed names xD

Comment (someaddons) [reply src/main/java/com/minecolonies/core/items/ItemScrollColonyTP.java:139]: nvm

**Review by someaddons — APPROVED** [review]
