### PR TITLE
Fix/builder metadata

### LINKED ISSUE #93: Fully implement flower pots for the builder
When the builder builds a flower pot, he should place both the pot and the flower, and should request and use both resources.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #93, #329, #424 

# Changes proposed in this pull request:
- Fix little bug with farmer
- Overwrite item comparison completely, use damage values as well now. (-1 means don't care)
- builder spawns entities and set tileEnty info correctly. (Also requests items)

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/structures/helpers/StructureProxy.java [hunk 1]
```diff
@@ -51,14 +44,19 @@ public StructureProxy(final World worldObj, final String name)
         this.height = size.getY();
         this.length = size.getZ();
 
-        this.blocks = new Block[width][height][length];
-        this.metadata = new IBlockState[width][height][length];
+        this.blocks = new Template.BlockInfo[width][height][length];
+        this.entities = new Template.EntityInfo[width][height][length];
+
+        for(Template.EntityInfo info: structure.getTileEntities())
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/structures/helpers/StructureProxy.java]: MINOR Local variable 'info' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/structures/helpers/StructureProxy.java [hunk 2]
```diff
@@ -24,14 +19,12 @@
...
     private final Structure structure;
-    private final List<TileEntity> tileEntities = new ArrayList<>();
-    private final List<Entity>     entities     = new ArrayList<>();
-    private Block[][][]       blocks;
-    private IBlockState[][][] metadata;
-    private int               width;
-    private int               height;
-    private int               length;
-    private BlockPos          offset;
+    private Template.EntityInfo[][][] entities;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/structures/helpers/StructureProxy.java]: MAJOR Private field 'entities' could be made final; it is only initialized in the declaration or constructor. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3AImmutableField)

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 3]
```diff
@@ -484,7 +484,7 @@ public void onDestroyed()
      */
     public TileEntityColonyBuilding getTileEntity()
     {
-        if (tileEntity == null && colony.getWorld().getBlockState(location).getBlock() != null)
+        if ((tileEntity == null && colony.getWorld().getBlockState(location).getBlock() != null) || tileEntity.isInvalid())
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: BLOCKER NullPointerException might be thrown as 'tileEntity' is nullable here [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2259)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 4]
```diff
@@ -901,43 +1014,76 @@ public void reduceNeededResources(final Block block)
...
+                    final int slot = worker.findFirstSlotInInventoryWith(stack.getItem(), stack.getItemDamage());
+                    if (slot != -1)
+                    {
+                        getInventory().decrStackSize(slot, 1);
+                        reduceNeededResources(Block.getBlockFromItem(stack.getItem()));
+                    }
+                }
+
+                entity.setUniqueId(UUID.randomUUID());
+                final double rotationYaw = entity.getMirroredYaw(settings.getMirror()) + (entity.rotationYaw - entity.getRotatedYaw(settings.getRotation()));
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: CRITICAL Use a "double" or "BigDecimal" instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2164)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 5]
```diff
@@ -901,43 +1014,76 @@ public void reduceNeededResources(final Block block)
...
-                entityHanging.posY += pos.getY();
-                entityHanging.posZ += pos.getZ();
-                //also sets position based on tile
-                entityHanging.setPosition(
-                        entityHanging.getHangingPosition().getX(),
-                        entityHanging.getHangingPosition().getY(),
-                        entityHanging.getHangingPosition().getZ());
+                entity = EntityList.createEntityFromNBT(entityInfo.entityData, world);
+            }
+            catch (Exception e)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: CRITICAL Catch a list of specific exception subtypes instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2221)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 6]
```diff
@@ -515,6 +577,14 @@ private void requestMaterials()
                 final AbstractBuilding building = getOwnBuilding();
                 if (building instanceof BuildingBuilder)
                 {
+                    if(((JobBuilder) job).getStructure().getBlockInfo().tileentityData != null)
+                    {
+                        Item secondaryItem = Item.getByNameOrId(((JobBuilder) job).getStructure().getBlockInfo().tileentityData.getString("Item"));
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR Local variable 'secondaryItem' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 7]
```diff
@@ -901,43 +1014,76 @@ public void reduceNeededResources(final Block block)
         }
     }
 
-    private void spawnEntity(@Nullable final Entity entity)
+    private Boolean spawnEntity(@NotNull final Structure.StructureBlock currentBlock)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MAJOR The Cyclomatic Complexity of this method "spawnEntity" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 8]
```diff
@@ -494,8 +505,59 @@ private void requestMaterials()
         final JobBuilder builderJob = (JobBuilder) job;
         while (builderJob.getStructure().findNextBlock())
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:525]: MAJOR Reduce the total number of break and continue statements in this loop to use at most one. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS135)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 9]
```diff
@@ -857,6 +939,24 @@ else if (block instanceof BlockEndPortal || block instanceof BlockMobSpawner ||
...
+            {
+                return false;
+            }
+
+            if(job instanceof JobBuilder)
+            {
+                secondaryItem = Item.getByNameOrId(((JobBuilder) job).getStructure().getBlockInfo().tileentityData.getString("Item"));
+            }
+
+            TileEntityFlowerPot tileentityflowerpot = (TileEntityFlowerPot) world.getTileEntity(pos);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR Local variable 'tileentityflowerpot' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 10]
```diff
@@ -494,8 +505,59 @@ private void requestMaterials()
...
+            @Nullable final Block block = blockState.getBlock();
+
+            if (entityInfo != null)
+            {
+                Entity entity;
+                try
+                {
+                    entity = EntityList.createEntityFromNBT(entityInfo.entityData, world);
+                }
+                catch (Exception e)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: CRITICAL Catch a list of specific exception subtypes instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2221)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 18 issues
* BLOCKER 1 blocker
* CRITICAL 3 critical
* MAJOR 7 major
* MINOR 7 minor

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L62](https://github.com/Minecolonies/minecolonies/blob/13362c4f29415713f5a091096a538183b409eaf5/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L62): The Cyclomatic Complexity of this class is 234 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L809](https://github.com/Minecolonies/minecolonies/blob/13362c4f29415713f5a091096a538183b409eaf5/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L809): The Cyclomatic Complexity of this method "handleMaterials" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L878](https://github.com/Minecolonies/minecolonies/blob/13362c4f29415713f5a091096a538183b409eaf5/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L878): This method has 123 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [StructureProxy.java#L159](https://github.com/Minecolonies/minecolonies/blob/13362c4f29415713f5a091096a538183b409eaf5/src/main/java/com/minecolonies/structures/helpers/StructureProxy.java#L159): Remove this unused private "isInvalid" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/13362c4f29415713f5a091096a538183b409eaf5/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/13362c4f29415713f5a091096a538183b409eaf5/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/13362c4f29415713f5a091096a538183b409eaf5/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/13362c4f29415713f5a091096a538183b409eaf5/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 18 issues
* BLOCKER 1 blocker
* CRITICAL 3 critical
* MAJOR 7 major
* MINOR 7 minor

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L62](https://github.com/Minecolonies/minecolonies/blob/fcbe39fdf8ff9038cb7b3267176b5ef816022709/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L62): The Cyclomatic Complexity of this class is 234 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L809](https://github.com/Minecolonies/minecolonies/blob/fcbe39fdf8ff9038cb7b3267176b5ef816022709/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L809): The Cyclomatic Complexity of this method "handleMaterials" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L878](https://github.com/Minecolonies/minecolonies/blob/fcbe39fdf8ff9038cb7b3267176b5ef816022709/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L878): This method has 123 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [StructureProxy.java#L159](https://github.com/Minecolonies/minecolonies/blob/fcbe39fdf8ff9038cb7b3267176b5ef816022709/src/main/java/com/minecolonies/structures/helpers/StructureProxy.java#L159): Remove this unused private "isInvalid" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/fcbe39fdf8ff9038cb7b3267176b5ef816022709/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/fcbe39fdf8ff9038cb7b3267176b5ef816022709/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/fcbe39fdf8ff9038cb7b3267176b5ef816022709/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/fcbe39fdf8ff9038cb7b3267176b5ef816022709/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

File: src/main/java/com/minecolonies/structures/helpers/StructureProxy.java (hunk 2 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/structures/helpers/StructureProxy.java:23]: @Kostronor Bug here?

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 4 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: also a bug ? @Kostronor

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 5 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: @Kostronor can we deactivate this for this class?
Minecraft does it this way...

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 10 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: As previous, can't change this. minecraft does it this way.

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 14 issues
* CRITICAL 3 critical
* MAJOR 7 major
* MINOR 4 minor

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L62](https://github.com/Minecolonies/minecolonies/blob/fc12c5f935d44e64e9f50a0b9030789ef151321d/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L62): The Cyclomatic Complexity of this class is 234 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L809](https://github.com/Minecolonies/minecolonies/blob/fc12c5f935d44e64e9f50a0b9030789ef151321d/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L809): The Cyclomatic Complexity of this method "handleMaterials" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L878](https://github.com/Minecolonies/minecolonies/blob/fc12c5f935d44e64e9f50a0b9030789ef151321d/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L878): This method has 123 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [StructureProxy.java#L159](https://github.com/Minecolonies/minecolonies/blob/fc12c5f935d44e64e9f50a0b9030789ef151321d/src/main/java/com/minecolonies/structures/helpers/StructureProxy.java#L159): Remove this unused private "isInvalid" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/fc12c5f935d44e64e9f50a0b9030789ef151321d/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/fc12c5f935d44e64e9f50a0b9030789ef151321d/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/fc12c5f935d44e64e9f50a0b9030789ef151321d/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/fc12c5f935d44e64e9f50a0b9030789ef151321d/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

**Comment by Raycoms** [comment]
and @Kostronor can we let the structure have more complex methods?

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 11]
```diff
@@ -901,43 +1006,87 @@ public void reduceNeededResources(final Block block)
...
+                    final int slot = worker.findFirstSlotInInventoryWith(stack.getItem(), stack.getItemDamage());
+                    if (slot != -1)
+                    {
+                        getInventory().decrStackSize(slot, 1);
+                        reduceNeededResources(Block.getBlockFromItem(stack.getItem()));
+                    }
+                }
+
+                entity.setUniqueId(UUID.randomUUID());
+                final double rotationYaw
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: CRITICAL Use a "double" or "BigDecimal" instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2164)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 12]
```diff
@@ -901,43 +1006,87 @@ public void reduceNeededResources(final Block block)
...
 
-                entityHanging.posX += pos.getX();
-                entityHanging.posY += pos.getY();
-                entityHanging.posZ += pos.getZ();
-                //also sets position based on tile
-                entityHanging.setPosition(
-                        entityHanging.getHangingPosition().getX(),
-                        entityHanging.getHangingPosition().getY(),
-                        entityHanging.getHangingPosition().getZ());
+    private Boolean spawnEntity(@NotNull final Structure.StructureBlock currentBlock)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MAJOR The Cyclomatic Complexity of this method "spawnEntity" is 11 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 13]
```diff
@@ -494,8 +505,51 @@ private void requestMaterials()
...
+            {
+                continue;
+            }
+
+            @Nullable final IBlockState blockState = blockInfo.blockState;
+            @Nullable final Block block = blockState.getBlock();
+
+            if (entityInfo != null)
+            {
+                Entity entity = getEntityFromEntityInfoOrNull(entityInfo);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR Local variable 'entity' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 14]
```diff
@@ -901,43 +1006,87 @@ public void reduceNeededResources(final Block block)
...
+        try
         {
-            final BlockPos pos = ((JobBuilder) job).getStructure().getOffsetPosition();
-
-            if (entity instanceof EntityHanging)
-            {
-                @NotNull final EntityHanging entityHanging = (EntityHanging) entity;
+            return EntityList.createEntityFromNBT(entityInfo.entityData, world);
+        }
+        catch (Exception e)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: CRITICAL Catch a list of specific exception subtypes instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2221)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 14 issues
* CRITICAL 2 critical
* MAJOR 7 major
* MINOR 5 minor

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L62](https://github.com/Minecolonies/minecolonies/blob/3f115c2e38595e1e4b10785aaec4d9974df7e13c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L62): The Cyclomatic Complexity of this class is 236 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L801](https://github.com/Minecolonies/minecolonies/blob/3f115c2e38595e1e4b10785aaec4d9974df7e13c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L801): The Cyclomatic Complexity of this method "handleMaterials" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L870](https://github.com/Minecolonies/minecolonies/blob/3f115c2e38595e1e4b10785aaec4d9974df7e13c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L870): This method has 123 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [StructureProxy.java#L159](https://github.com/Minecolonies/minecolonies/blob/3f115c2e38595e1e4b10785aaec4d9974df7e13c/src/main/java/com/minecolonies/structures/helpers/StructureProxy.java#L159): Remove this unused private "isInvalid" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/3f115c2e38595e1e4b10785aaec4d9974df7e13c/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/3f115c2e38595e1e4b10785aaec4d9974df7e13c/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/3f115c2e38595e1e4b10785aaec4d9974df7e13c/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/3f115c2e38595e1e4b10785aaec4d9974df7e13c/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 8 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:525]: We should increase this cap to 2-3

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 13 issues
* CRITICAL 1 critical
* MAJOR 7 major
* MINOR 5 minor

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L62](https://github.com/Minecolonies/minecolonies/blob/3f115c2e38595e1e4b10785aaec4d9974df7e13c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L62): The Cyclomatic Complexity of this class is 236 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L801](https://github.com/Minecolonies/minecolonies/blob/3f115c2e38595e1e4b10785aaec4d9974df7e13c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L801): The Cyclomatic Complexity of this method "handleMaterials" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L870](https://github.com/Minecolonies/minecolonies/blob/3f115c2e38595e1e4b10785aaec4d9974df7e13c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L870): This method has 123 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [StructureProxy.java#L159](https://github.com/Minecolonies/minecolonies/blob/3f115c2e38595e1e4b10785aaec4d9974df7e13c/src/main/java/com/minecolonies/structures/helpers/StructureProxy.java#L159): Remove this unused private "isInvalid" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/3f115c2e38595e1e4b10785aaec4d9974df7e13c/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/3f115c2e38595e1e4b10785aaec4d9974df7e13c/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/3f115c2e38595e1e4b10785aaec4d9974df7e13c/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/3f115c2e38595e1e4b10785aaec4d9974df7e13c/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 12 issues
* CRITICAL 1 critical
* MAJOR 7 major
* MINOR 4 minor

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L62](https://github.com/Minecolonies/minecolonies/blob/997c88b32a2b6020457fe578d5b55d6f6a1117b0/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L62): The Cyclomatic Complexity of this class is 236 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L801](https://github.com/Minecolonies/minecolonies/blob/997c88b32a2b6020457fe578d5b55d6f6a1117b0/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L801): The Cyclomatic Complexity of this method "handleMaterials" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L870](https://github.com/Minecolonies/minecolonies/blob/997c88b32a2b6020457fe578d5b55d6f6a1117b0/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L870): This method has 123 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [StructureProxy.java#L159](https://github.com/Minecolonies/minecolonies/blob/997c88b32a2b6020457fe578d5b55d6f6a1117b0/src/main/java/com/minecolonies/structures/helpers/StructureProxy.java#L159): Remove this unused private "isInvalid" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/997c88b32a2b6020457fe578d5b55d6f6a1117b0/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/997c88b32a2b6020457fe578d5b55d6f6a1117b0/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/997c88b32a2b6020457fe578d5b55d6f6a1117b0/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/997c88b32a2b6020457fe578d5b55d6f6a1117b0/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 15]
```diff
@@ -901,43 +1006,94 @@ public void reduceNeededResources(final Block block)
...
-                world.spawnEntityInWorld(minecart);
+                for(final ItemStack stack: request)
+                {
+                    if (checkOrRequestItems(stack))
+                    {
+                        return false;
+                    }
+                }
+
+                for(final ItemStack stack: request)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MAJOR Combine this loop with the one that starts on line 1059. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS3047)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 13 issues
* CRITICAL 1 critical
* MAJOR 8 major
* MINOR 4 minor

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L62](https://github.com/Minecolonies/minecolonies/blob/991996f7200f377ac06ac5258192033c1c014884/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L62): The Cyclomatic Complexity of this class is 238 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L801](https://github.com/Minecolonies/minecolonies/blob/991996f7200f377ac06ac5258192033c1c014884/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L801): The Cyclomatic Complexity of this method "handleMaterials" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L870](https://github.com/Minecolonies/minecolonies/blob/991996f7200f377ac06ac5258192033c1c014884/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L870): This method has 123 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [StructureProxy.java#L160](https://github.com/Minecolonies/minecolonies/blob/991996f7200f377ac06ac5258192033c1c014884/src/main/java/com/minecolonies/structures/helpers/StructureProxy.java#L160): Remove this unused private "isInvalid" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/991996f7200f377ac06ac5258192033c1c014884/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/991996f7200f377ac06ac5258192033c1c014884/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/991996f7200f377ac06ac5258192033c1c014884/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/991996f7200f377ac06ac5258192033c1c014884/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 13 issues
* CRITICAL 1 critical
* MAJOR 8 major
* MINOR 4 minor

Watch the comments in this conversation to review them.

#### 9 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L62](https://github.com/Minecolonies/minecolonies/blob/6a0703adb342bdab85966d543a283f92a36616b4/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L62): The Cyclomatic Complexity of this class is 238 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L801](https://github.com/Minecolonies/minecolonies/blob/6a0703adb342bdab85966d543a283f92a36616b4/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L801): The Cyclomatic Complexity of this method "handleMaterials" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L870](https://github.com/Minecolonies/minecolonies/blob/6a0703adb342bdab85966d543a283f92a36616b4/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L870): This method has 123 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [StructureProxy.java#L160](https://github.com/Minecolonies/minecolonies/blob/6a0703adb342bdab85966d543a283f92a36616b4/src/main/java/com/minecolonies/structures/helpers/StructureProxy.java#L160): Remove this unused private "isInvalid" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [StructureProxy.java#L220](https://github.com/Minecolonies/minecolonies/blob/6a0703adb342bdab85966d543a283f92a36616b4/src/main/java/com/minecolonies/structures/helpers/StructureProxy.java#L220): The Cyclomatic Complexity of this method "rotate" is 11 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/6a0703adb342bdab85966d543a283f92a36616b4/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/6a0703adb342bdab85966d543a283f92a36616b4/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/6a0703adb342bdab85966d543a283f92a36616b4/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/6a0703adb342bdab85966d543a283f92a36616b4/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 16]
```diff
@@ -515,7 +573,20 @@ private void requestMaterials()
                 final AbstractBuilding building = getOwnBuilding();
                 if (building instanceof BuildingBuilder)
                 {
-                    ((BuildingBuilder) building).addNeededResource(block, 1);
+                    if(((JobBuilder) job).getStructure().getBlockInfo().tileentityData != null)
+                    {
+                        List<ItemStack> itemList = new ArrayList<>();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR Local variable 'itemList' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 17]
```diff
@@ -744,12 +815,59 @@ private boolean handleMaterials(@NotNull final Block block, @NotNull final IBloc
...
+            if(!isBlockFree(stack) && checkOrRequestItems(stack))
+            {
+                return false;
+            }
+        }
+
+        return true;
+    }
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 18]
```diff
@@ -515,7 +573,20 @@ private void requestMaterials()
                 final AbstractBuilding building = getOwnBuilding();
                 if (building instanceof BuildingBuilder)
                 {
-                    ((BuildingBuilder) building).addNeededResource(block, 1);
+                    if(((JobBuilder) job).getStructure().getBlockInfo().tileentityData != null)
+                    {
+                        List<ItemStack> itemList = new ArrayList<>();
+                        itemList.addAll(getItemStacksOfTileEntity(((JobBuilder) job).getStructure().getBlockInfo().tileentityData));
+
+                        for(ItemStack stack: itemList)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR Local variable 'stack' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 19]
```diff
@@ -515,7 +573,20 @@ private void requestMaterials()
...
+                        {
+                            if(!isBlockFree(stack) && checkOrRequestItems(stack))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MAJOR Refactor this code to not nest more than 5 if/for/while/switch/try statements. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS134)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 20]
```diff
@@ -744,12 +815,59 @@ private boolean handleMaterials(@NotNull final Block block, @NotNull final IBloc
...
+        return true;
+    }
+
+    /**
+     *((JobBuilder) job).getStructure().getBlockInfo().tileentityData
+     * @return
+     */
+    private List<ItemStack> getItemStacksOfTileEntity(NBTTagCompound compound)
+    {
+        List<ItemStack> items = new ArrayList<>();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR Local variable 'items' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 21]
```diff
@@ -744,12 +815,59 @@ private boolean handleMaterials(@NotNull final Block block, @NotNull final IBloc
...
+        TileEntity tileEntity = TileEntity.create(world, compound);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR Local variable 'tileEntity' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 22]
```diff
@@ -824,6 +942,7 @@ private boolean placeBlock(@NotNull final BlockPos pos, final Block block, @NotN
             }
         }
 
+        Item secondaryItem = null;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MAJOR Move the declaration of "secondaryItem" closer to the code that uses it. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1941)
MINOR Local variable 'secondaryItem' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 23]
```diff
@@ -744,12 +815,59 @@ private boolean handleMaterials(@NotNull final Block block, @NotNull final IBloc
             return true;
         }
 
-        if (isBlockFree(block, block.getMetaFromState(blockState)))
+        List<ItemStack> itemList = new ArrayList<>();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR Local variable 'itemList' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 24]
```diff
@@ -744,12 +815,59 @@ private boolean handleMaterials(@NotNull final Block block, @NotNull final IBloc
...
+        TileEntity tileEntity = TileEntity.create(world, compound);
+        if(tileEntity instanceof TileEntityFlowerPot)
+        {
+            items.add(((TileEntityFlowerPot) tileEntity).getFlowerItemStack());
+        }
+        else if(tileEntity instanceof TileEntityLockable)
+        {
+            for(int i = 0; i < ((TileEntityLockable) tileEntity).getSizeInventory(); i++)
+            {
+                ItemStack stack = ((TileEntityLockable) tileEntity).getStackInSlot(i);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR Local variable 'stack' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 25]
```diff
@@ -744,12 +815,59 @@ private boolean handleMaterials(@NotNull final Block block, @NotNull final IBloc
...
-        if (isBlockFree(block, block.getMetaFromState(blockState)))
+        List<ItemStack> itemList = new ArrayList<>();
+        itemList.add(BlockUtils.getItemStackFromBlockState(blockState));
+        if(job instanceof JobBuilder && ((JobBuilder) job).getStructure().getBlockInfo() != null && ((JobBuilder) job).getStructure().getBlockInfo().tileentityData != null)
         {
-            return true;
+            itemList.addAll(getItemStacksOfTileEntity(((JobBuilder) job).getStructure().getBlockInfo().tileentityData));
+        }
+
+        for(ItemStack stack: itemList)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR Local variable 'stack' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/util/StructureWrapper.java [hunk 26]
```diff
@@ -284,6 +279,8 @@ public boolean doesStructureBlockEqualWorldBlock()
     {
         final IBlockState structureBlockState = structure.getBlockState(this.getLocalPosition());
         final Block structureBlock = structureBlockState.getBlock();
+        final Template.EntityInfo entityInfo = structure.getEntityinfo(this.getLocalPosition());
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/util/StructureWrapper.java]: MAJOR Move the declaration of "entityInfo" closer to the code that uses it. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1941)

File: src/main/java/com/minecolonies/coremod/colony/buildings/BuildingBuilder.java [hunk 27]
```diff
@@ -220,7 +223,9 @@ public void reduceNeededResource(Block res, int amount)
         }
         else
         {
-            this.neededResources.put(res, preAmount - amount);
+            IBlockState state = res.getStateFromMeta(metaData);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/BuildingBuilder.java]: MINOR Remove this use of "getStateFromMeta"; it is deprecated. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
MINOR Local variable 'state' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/colony/buildings/BuildingBuilder.java [hunk 28]
```diff
@@ -178,25 +179,26 @@ public void serializeToView(@NotNull ByteBuf buf)
...
-    public void addNeededResource(Block res, int amount)
+    public void addNeededResource(@Nullable final Block res, final int amount, final int metaData)
     {
         int preAmount = 0;
         if (this.neededResources.containsKey(res))
         {
             preAmount = this.neededResources.get(res);
         }
-        this.neededResources.put(res, preAmount + amount);
+        IBlockState state = res.getStateFromMeta(metaData);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/BuildingBuilder.java]: MINOR Remove this use of "getStateFromMeta"; it is deprecated. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
MINOR Local variable 'state' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 29 issues
* CRITICAL 1 critical
* MAJOR 11 major
* MINOR 17 minor

Watch the comments in this conversation to review them.

#### 9 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L65](https://github.com/Minecolonies/minecolonies/blob/9b50e88d42345f1210266fe47d7de68404df0a0a/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L65): The Cyclomatic Complexity of this class is 243 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L915](https://github.com/Minecolonies/minecolonies/blob/9b50e88d42345f1210266fe47d7de68404df0a0a/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L915): This method has 118 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [StructureWrapper.java#L278](https://github.com/Minecolonies/minecolonies/blob/9b50e88d42345f1210266fe47d7de68404df0a0a/src/main/java/com/minecolonies/coremod/util/StructureWrapper.java#L278): The Cyclomatic Complexity of this method "doesStructureBlockEqualWorldBlock" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [StructureProxy.java#L160](https://github.com/Minecolonies/minecolonies/blob/9b50e88d42345f1210266fe47d7de68404df0a0a/src/main/java/com/minecolonies/structures/helpers/StructureProxy.java#L160): Remove this unused private "isInvalid" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [StructureProxy.java#L220](https://github.com/Minecolonies/minecolonies/blob/9b50e88d42345f1210266fe47d7de68404df0a0a/src/main/java/com/minecolonies/structures/helpers/StructureProxy.java#L220): The Cyclomatic Complexity of this method "rotate" is 11 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/9b50e88d42345f1210266fe47d7de68404df0a0a/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/9b50e88d42345f1210266fe47d7de68404df0a0a/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/9b50e88d42345f1210266fe47d7de68404df0a0a/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/9b50e88d42345f1210266fe47d7de68404df0a0a/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

File: src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java [hunk 29]
```diff
@@ -296,7 +296,8 @@ public ItemStack removeItemNeeded(@NotNull final ItemStack stack)
                 neededItem.stackSize -= itemsToRemove;
                 stackCopy.stackSize -= itemsToRemove;
 
-                if (neededItem.stackSize == 0)
+                //Deativate this for now in order to keep working even if not all items are given.
+                //if (neededItem.stackSize == 0)
                 {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java]: MAJOR Extract this nested code block into a method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1199)

File: src/main/java/com/minecolonies/structures/helpers/StructureProxy.java [hunk 30]
```diff
@@ -306,8 +202,10 @@ public int getHeight()
      * Rotate the structure depending on the direction it's facing.
      *
      * @param times times to rotate.
+     * @param world the world to rotate it in.
+     * @param rotatePos the pos to rotate it around.
      */
-    public void rotate(final int times)
+    public void rotate(final int times, World world, BlockPos rotatePos)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/structures/helpers/StructureProxy.java:208]: MAJOR The Cyclomatic Complexity of this method "rotate" is 11 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

File: src/main/java/com/minecolonies/structures/helpers/StructureProxy.java [hunk 31]
```diff
@@ -365,23 +263,35 @@ public void rotate(final int times)
         minY = Math.abs(minY);
         minZ = Math.abs(minZ);
         boolean foundHut = false;
+        PlacementSettings settings = new PlacementSettings().setRotation(rotation);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/structures/helpers/StructureProxy.java]: MINOR Local variable 'settings' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/structures/helpers/StructureProxy.java [hunk 32]
```diff
@@ -365,23 +263,35 @@ public void rotate(final int times)
...
             if (info.blockState.getBlock() instanceof AbstractBlockHut)
             {
                 foundHut = true;
                 offset = info.pos.add(minX, minY, minZ);
             }
         }
+
+        for(final Template.EntityInfo info: structure.getTileEntities())
+        {
+            Template.EntityInfo newInfo = structure.transformEntityInfoWithSettings(info, world, Template.transformedBlockPos(settings, info.blockPos), settings);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/structures/helpers/StructureProxy.java]: MINOR Local variable 'newInfo' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 33]
```diff
@@ -744,12 +840,77 @@ private boolean handleMaterials(@NotNull final Block block, @NotNull final IBloc
...
+    }
+
+    /**
+     * Check how much of a certain stuck is actually required.
+     * @param stack the stack to check.
+     * @return the new stack with the correct amount.
+     */
+    private ItemStack getTotalAmount(ItemStack stack)
+    {
+        AbstractBuildingWorker buildingWorker = getOwnBuilding();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR Local variable 'buildingWorker' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 34]
```diff
@@ -744,12 +840,77 @@ private boolean handleMaterials(@NotNull final Block block, @NotNull final IBloc
...
+        if(buildingWorker instanceof BuildingBuilder)
+        {
+            //todo not working correctly yet! is running around strangely!
+            ItemStack tempStack = ((BuildingBuilder) buildingWorker).getNeededResources().get(stack.getUnlocalizedName());
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR Local variable 'tempStack' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 35]
```diff
@@ -744,12 +840,77 @@ private boolean handleMaterials(@NotNull final Block block, @NotNull final IBloc
...
+            return tempStack == null ? stack : tempStack.copy();
+        }
+        return stack;
+    }
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 36]
```diff
@@ -878,66 +1054,130 @@ else if (block instanceof BlockEndPortal || block instanceof BlockMobSpawner ||
...
+     */
+    @Nullable
+    private Entity getEntityFromEntityInfoOrNull(Template.EntityInfo entityInfo)
     {
-        if (entity != null && job instanceof JobBuilder)
+        try
+        {
+            return EntityList.createEntityFromNBT(entityInfo.entityData, world);
+        }
+        catch (Exception e)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: CRITICAL Catch a list of specific exception subtypes instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2221)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 37]
```diff
@@ -530,7 +626,7 @@ private void requestMaterials()
      */
     private boolean clearStep(@NotNull final Structure.StructureBlock currentBlock)
     {
-        if((job instanceof JobBuilder && ((JobBuilder) job).getWorkOrder().isCleared()) || !currentStructure.getStage().equals(Structure.Stage.CLEAR))
+        if((job instanceof JobBuilder && ((JobBuilder) job).getWorkOrder() != null && ((JobBuilder) job).getWorkOrder().isCleared()) || !currentStructure.getStage().equals(Structure.Stage.CLEAR))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR Split this 195 characters long line (which is greater than 180 authorized). [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS00103)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 38]
```diff
@@ -878,66 +1054,130 @@ else if (block instanceof BlockEndPortal || block instanceof BlockMobSpawner ||
...
-            final BlockPos pos = ((JobBuilder) job).getStructure().getOffsetPosition();
+            Log.getLogger().info("Couldn't restore entitiy", e);
+            return null;
+        }
+    }
 
-            if (entity instanceof EntityHanging)
-            {
-                @NotNull final EntityHanging entityHanging = (EntityHanging) entity;
+    private Boolean spawnEntity(@NotNull final Structure.StructureBlock currentBlock)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MAJOR The Cyclomatic Complexity of this method "spawnEntity" is 14 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 39]
```diff
@@ -515,7 +597,21 @@ private void requestMaterials()
...
                 {
-                    ((BuildingBuilder) building).addNeededResource(block, 1);
+                    if(((JobBuilder) job).getStructure().getBlockInfo().tileentityData != null)
+                    {
+                        List<ItemStack> itemList = new ArrayList<>();
+                        itemList.addAll(getItemStacksOfTileEntity(((JobBuilder) job).getStructure().getBlockInfo().tileentityData));
+
+                        for(ItemStack stack: itemList)
+                        {
+                            if(!isBlockFree(stack))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MAJOR Refactor this code to not nest more than 5 if/for/while/switch/try statements. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS134)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 40]
```diff
@@ -878,66 +1054,130 @@ else if (block instanceof BlockEndPortal || block instanceof BlockMobSpawner ||
...
+                {
+                    if (checkOrRequestItems(stack))
+                    {
+                        return false;
+                    }
+                }
 
-                minecart.setWorld(world);
-                minecart.dimension = world.provider.getDimension();
+                for(final ItemStack stack: request)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:1167]: MAJOR Combine this loop with the one that starts on line 1159. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS3047)

File: src/main/java/com/minecolonies/structures/helpers/Structure.java [hunk 41]
```diff
@@ -256,6 +256,35 @@ public void renderStructure(@NotNull final BlockPos startingPos, @NotNull final
...
+    public Template.EntityInfo transformEntityInfoWithSettings(final Template.EntityInfo entityInfo, final World world, final BlockPos pos, final PlacementSettings settings)
+    {
+        final Entity finalEntity = EntityList.createEntityFromNBT(entityInfo.entityData, world);
+        final Vec3d entityVec = Structure.transformedVec3d(settings, entityInfo.pos).add(new Vec3d(pos));
+
+        if (finalEntity != null)
+        {
+            finalEntity.prevRotationYaw = (float) (finalEntity.getMirroredYaw(settings.getMirror()) - NINETY_DEGREE);
+            //Don't remove that line. Seems like it is doing nothing but it changes behavior!
+            final double rotation =
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/structures/helpers/Structure.java]: MAJOR Remove this unused "rotation" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
MAJOR Remove this useless assignment to local variable "rotation". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)

File: src/main/java/com/minecolonies/structures/helpers/Structure.java [hunk 42]
```diff
@@ -256,6 +256,35 @@ public void renderStructure(@NotNull final BlockPos startingPos, @NotNull final
...
+                    (double) finalEntity.getMirroredYaw(settings.getMirror()) + ((double) finalEntity.rotationYaw - finalEntity.getRotatedYaw(settings.getRotation()));
+            finalEntity.setLocationAndAngles(entityVec.xCoord, entityVec.yCoord, entityVec.zCoord, finalEntity.getRotatedYaw(settings.getRotation()), finalEntity.rotationPitch);
+
+            NBTTagCompound nbttagcompound = new NBTTagCompound();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/structures/helpers/Structure.java]: MINOR Local variable 'nbttagcompound' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/colony/buildings/BuildingBuilder.java [hunk 43]
```diff
@@ -39,13 +38,13 @@
     /**
      * Tags to store the needed resourced to nbt.
      */
-    private static final String TAG_RESOURCE_LIST = "resources";
+    private static final String TAG_RESOURCE_LIST = "resourcesItem";
     private static final String TAG_AMOUNT        = "amount";
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/BuildingBuilder.java]: MAJOR Remove this unused "TAG_AMOUNT" private field. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1068)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 37 issues
* CRITICAL 1 critical
* MAJOR 17 major
* MINOR 19 minor

Watch the comments in this conversation to review them.

#### 9 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L66](https://github.com/Minecolonies/minecolonies/blob/8e75bb26ebc1f2a6fd79d7024fce6a83dddbae06/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L66): The Cyclomatic Complexity of this class is 256 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L835](https://github.com/Minecolonies/minecolonies/blob/8e75bb26ebc1f2a6fd79d7024fce6a83dddbae06/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L835): The Cyclomatic Complexity of this method "handleMaterials" is 11 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L958](https://github.com/Minecolonies/minecolonies/blob/8e75bb26ebc1f2a6fd79d7024fce6a83dddbae06/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L958): This method has 119 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [EntityAIStructureBuilder.java#L51](https://github.com/Minecolonies/minecolonies/blob/8e75bb26ebc1f2a6fd79d7024fce6a83dddbae06/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L51): Remove the "workFrom" field and declare it as a local variable in the relevant methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1450)
1. MAJOR [StructureWrapper.java#L280](https://github.com/Minecolonies/minecolonies/blob/8e75bb26ebc1f2a6fd79d7024fce6a83dddbae06/src/main/java/com/minecolonies/coremod/util/StructureWrapper.java#L280): The Cyclomatic Complexity of this method "doesStructureBlockEqualWorldBlock" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/8e75bb26ebc1f2a6fd79d7024fce6a83dddbae06/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/8e75bb26ebc1f2a6fd79d7024fce6a83dddbae06/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/8e75bb26ebc1f2a6fd79d7024fce6a83dddbae06/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/8e75bb26ebc1f2a6fd79d7024fce6a83dddbae06/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 37 issues
* CRITICAL 1 critical
* MAJOR 17 major
* MINOR 19 minor

Watch the comments in this conversation to review them.

#### 9 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L66](https://github.com/Minecolonies/minecolonies/blob/cbead9e89f052ef19787d763b1683ad04046a7e3/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L66): The Cyclomatic Complexity of this class is 256 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L835](https://github.com/Minecolonies/minecolonies/blob/cbead9e89f052ef19787d763b1683ad04046a7e3/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L835): The Cyclomatic Complexity of this method "handleMaterials" is 11 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L958](https://github.com/Minecolonies/minecolonies/blob/cbead9e89f052ef19787d763b1683ad04046a7e3/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L958): This method has 119 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [EntityAIStructureBuilder.java#L51](https://github.com/Minecolonies/minecolonies/blob/cbead9e89f052ef19787d763b1683ad04046a7e3/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L51): Remove the "workFrom" field and declare it as a local variable in the relevant methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1450)
1. MAJOR [StructureWrapper.java#L280](https://github.com/Minecolonies/minecolonies/blob/cbead9e89f052ef19787d763b1683ad04046a7e3/src/main/java/com/minecolonies/coremod/util/StructureWrapper.java#L280): The Cyclomatic Complexity of this method "doesStructureBlockEqualWorldBlock" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/cbead9e89f052ef19787d763b1683ad04046a7e3/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/cbead9e89f052ef19787d763b1683ad04046a7e3/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/cbead9e89f052ef19787d763b1683ad04046a7e3/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/cbead9e89f052ef19787d763b1683ad04046a7e3/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

File: src/main/java/com/minecolonies/structures/helpers/StructureProxy.java [hunk 44]
```diff
@@ -365,24 +264,37 @@ public void rotate(final int times)
...
                 foundHut = true;
                 offset = info.pos.add(minX, minY, minZ);
             }
         }
+
         updateOffSetIfDecoration(foundHut, size, times, minX, minY, minZ);
+
+        for(final Template.EntityInfo info: structure.getTileEntities())
+        {
+            Template.EntityInfo newInfo = structure.transformEntityInfoWithSettings(info, world, rotatePos.subtract(offset).add(new BlockPos(minX, minY, minZ)), settings);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/structures/helpers/StructureProxy.java]: MINOR Local variable 'newInfo' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/structures/helpers/StructureProxy.java [hunk 45]
```diff
@@ -2,20 +2,17 @@
...
 import com.minecolonies.coremod.blocks.AbstractBlockHut;
 import com.minecolonies.coremod.util.BlockPosUtil;
-import net.minecraft.block.Block;
 import net.minecraft.block.state.IBlockState;
 import net.minecraft.entity.Entity;
-import net.minecraft.entity.player.EntityPlayer;
-import net.minecraft.tileentity.TileEntity;
 import net.minecraft.util.Rotation;
 import net.minecraft.util.math.BlockPos;
+import net.minecraft.util.math.Vec3d;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/structures/helpers/StructureProxy.java]: MINOR Remove this unused import 'net.minecraft.util.math.Vec3d'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 46]
```diff
@@ -20,21 +21,32 @@
...
 import net.minecraft.item.ItemStack;
+import net.minecraft.nbt.NBTTagCompound;
+import net.minecraft.tileentity.TileEntity;
+import net.minecraft.tileentity.TileEntityFlowerPot;
+import net.minecraft.tileentity.TileEntityLockable;
 import net.minecraft.util.EnumFacing;
 import net.minecraft.util.math.BlockPos;
 import net.minecraft.util.math.MathHelper;
+import net.minecraft.util.math.RayTraceResult;
+import net.minecraft.world.gen.structure.template.PlacementSettings;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR Remove this unused import 'net.minecraft.world.gen.structure.template.PlacementSettings'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 47]
```diff
@@ -744,12 +840,77 @@ private boolean handleMaterials(@NotNull final Block block, @NotNull final IBloc
...
+        itemList.add(BlockUtils.getItemStackFromBlockState(blockState));
+        if(job instanceof JobBuilder && ((JobBuilder) job).getStructure() != null
+                && ((JobBuilder) job).getStructure().getBlockInfo() != null && ((JobBuilder) job).getStructure().getBlockInfo().tileentityData != null)
         {
-            return true;
+            itemList.addAll(getItemStacksOfTileEntity(((JobBuilder) job).getStructure().getBlockInfo().tileentityData));
         }
 
-        return !checkOrRequestItems(BlockUtils.getItemStackFromBlockState(blockState));
+        for(ItemStack stack: itemList)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR Local variable 'stack' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 48]
```diff
@@ -878,66 +1054,124 @@ else if (block instanceof BlockEndPortal || block instanceof BlockMobSpawner ||
...
+        catch (Exception e)
         {
-            final BlockPos pos = ((JobBuilder) job).getStructure().getOffsetPosition();
+            Log.getLogger().info("Couldn't restore entitiy", e);
+            return null;
+        }
+    }
 
-            if (entity instanceof EntityHanging)
+    private Boolean spawnEntity(@NotNull final Structure.StructureBlock currentBlock)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:1129]: MAJOR The Cyclomatic Complexity of this method "spawnEntity" is 15 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

File: src/main/java/com/minecolonies/structures/helpers/Structure.java [hunk 49]
```diff
@@ -256,6 +269,61 @@ public void renderStructure(@NotNull final BlockPos startingPos, @NotNull final
...
+        if (finalEntity != null)
+        {
+            finalEntity.prevRotationYaw = (float) (finalEntity.getMirroredYaw(settings.getMirror()) - NINETY_DEGREES);
+            final double rotationYaw
+                    = (double)finalEntity.getMirroredYaw(settings.getMirror()) + ((double)finalEntity.rotationYaw - (double)finalEntity.getRotatedYaw(settings.getRotation()));
+
+            finalEntity.setLocationAndAngles(entityVec.xCoord, entityVec.yCoord, entityVec.zCoord,
+                    (float) rotationYaw, finalEntity.rotationPitch);
+
+            NBTTagCompound nbttagcompound = new NBTTagCompound();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/structures/helpers/Structure.java]: MINOR Local variable 'nbttagcompound' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 36 issues
* CRITICAL 1 critical
* MAJOR 14 major
* MINOR 21 minor

Watch the comments in this conversation to review them.

#### 9 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L66](https://github.com/Minecolonies/minecolonies/blob/1030c63f576d45b72889f8b91b107c227065371b/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L66): The Cyclomatic Complexity of this class is 256 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L835](https://github.com/Minecolonies/minecolonies/blob/1030c63f576d45b72889f8b91b107c227065371b/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L835): The Cyclomatic Complexity of this method "handleMaterials" is 11 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L958](https://github.com/Minecolonies/minecolonies/blob/1030c63f576d45b72889f8b91b107c227065371b/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L958): This method has 119 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [EntityAIStructureBuilder.java#L51](https://github.com/Minecolonies/minecolonies/blob/1030c63f576d45b72889f8b91b107c227065371b/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L51): Remove the "workFrom" field and declare it as a local variable in the relevant methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1450)
1. MAJOR [StructureWrapper.java#L280](https://github.com/Minecolonies/minecolonies/blob/1030c63f576d45b72889f8b91b107c227065371b/src/main/java/com/minecolonies/coremod/util/StructureWrapper.java#L280): The Cyclomatic Complexity of this method "doesStructureBlockEqualWorldBlock" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/1030c63f576d45b72889f8b91b107c227065371b/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/1030c63f576d45b72889f8b91b107c227065371b/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/1030c63f576d45b72889f8b91b107c227065371b/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/1030c63f576d45b72889f8b91b107c227065371b/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 40 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:1167]: Can't. that would change logic.

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 36 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: Can't minecraft does it this way.

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 50]
```diff
@@ -878,66 +1055,125 @@ else if (block instanceof BlockEndPortal || block instanceof BlockMobSpawner ||
...
+    @Nullable
+    private Entity getEntityFromEntityInfoOrNull(Template.EntityInfo entityInfo)
     {
-        if (entity != null && job instanceof JobBuilder)
+        try
         {
-            final BlockPos pos = ((JobBuilder) job).getStructure().getOffsetPosition();
+            return EntityList.createEntityFromNBT(entityInfo.entityData, world);
+        }
+        catch (Exception e)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: CRITICAL Catch a list of specific exception subtypes instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2221)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 51]
```diff
@@ -515,7 +596,21 @@ private void requestMaterials()
...
                 {
-                    ((BuildingBuilder) building).addNeededResource(block, 1);
+                    if(((JobBuilder) job).getStructure().getBlockInfo().tileentityData != null)
+                    {
+                        final List<ItemStack> itemList = new ArrayList<>();
+                        itemList.addAll(getItemStacksOfTileEntity(((JobBuilder) job).getStructure().getBlockInfo().tileentityData));
+
+                        for(final ItemStack stack: itemList)
+                        {
+                            if(!isBlockFree(stack))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MAJOR Refactor this code to not nest more than 5 if/for/while/switch/try statements. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS134)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 16 issues
* CRITICAL 1 critical
* MAJOR 11 major
* MINOR 4 minor

Watch the comments in this conversation to review them.

#### 9 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L65](https://github.com/Minecolonies/minecolonies/blob/6951bd6a801ea097d00d91cff3ea13ee4a703d7e/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L65): The Cyclomatic Complexity of this class is 256 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L835](https://github.com/Minecolonies/minecolonies/blob/6951bd6a801ea097d00d91cff3ea13ee4a703d7e/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L835): The Cyclomatic Complexity of this method "handleMaterials" is 11 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L960](https://github.com/Minecolonies/minecolonies/blob/6951bd6a801ea097d00d91cff3ea13ee4a703d7e/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L960): This method has 119 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [EntityAIStructureBuilder.java#L51](https://github.com/Minecolonies/minecolonies/blob/6951bd6a801ea097d00d91cff3ea13ee4a703d7e/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L51): Remove the "workFrom" field and declare it as a local variable in the relevant methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1450)
1. MAJOR [StructureWrapper.java#L280](https://github.com/Minecolonies/minecolonies/blob/6951bd6a801ea097d00d91cff3ea13ee4a703d7e/src/main/java/com/minecolonies/coremod/util/StructureWrapper.java#L280): The Cyclomatic Complexity of this method "doesStructureBlockEqualWorldBlock" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/6951bd6a801ea097d00d91cff3ea13ee4a703d7e/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/6951bd6a801ea097d00d91cff3ea13ee4a703d7e/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/6951bd6a801ea097d00d91cff3ea13ee4a703d7e/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/6951bd6a801ea097d00d91cff3ea13ee4a703d7e/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 50 above)
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: RuntimeException + all thrown clauses

File: src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java (hunk 29 above)
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java]: deactivating the if is in this case if(true)!!!

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 8 above)
Comment (marvin-bitterlich) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:525]: I'd say we should split this while-loop up into smaller segments... I'll bump up the continue/break limit once that is done

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 51 above)
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: as said above dfinitely needed

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 40 above)
Comment (marvin-bitterlich) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:1167]: true, false positive

File: src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java (hunk 29 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java]: Sonar doesn't like if true very much either

File: src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java [hunk 52]
```diff
@@ -296,7 +296,8 @@ public ItemStack removeItemNeeded(@NotNull final ItemStack stack)
                 neededItem.stackSize -= itemsToRemove;
                 stackCopy.stackSize -= itemsToRemove;
 
-                if (neededItem.stackSize == 0)
+                //Deativate this for now in order to keep working even if not all items are given. previously checked if stackSize is 0.
+                if (true)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java]: BLOCKER Change this condition so that it does not always evaluate to "true" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2583)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 14 issues
* BLOCKER 1 blocker
* MAJOR 9 major
* MINOR 4 minor

Watch the comments in this conversation to review them.

#### 9 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L65](https://github.com/Minecolonies/minecolonies/blob/9ee77d50c1e86ac167becbe4928666178ee8a2ad/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L65): The Cyclomatic Complexity of this class is 258 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L853](https://github.com/Minecolonies/minecolonies/blob/9ee77d50c1e86ac167becbe4928666178ee8a2ad/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L853): The Cyclomatic Complexity of this method "handleMaterials" is 11 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L978](https://github.com/Minecolonies/minecolonies/blob/9ee77d50c1e86ac167becbe4928666178ee8a2ad/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L978): This method has 119 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [EntityAIStructureBuilder.java#L51](https://github.com/Minecolonies/minecolonies/blob/9ee77d50c1e86ac167becbe4928666178ee8a2ad/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L51): Remove the "workFrom" field and declare it as a local variable in the relevant methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1450)
1. MAJOR [StructureWrapper.java#L280](https://github.com/Minecolonies/minecolonies/blob/9ee77d50c1e86ac167becbe4928666178ee8a2ad/src/main/java/com/minecolonies/coremod/util/StructureWrapper.java#L280): The Cyclomatic Complexity of this method "doesStructureBlockEqualWorldBlock" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/9ee77d50c1e86ac167becbe4928666178ee8a2ad/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/9ee77d50c1e86ac167becbe4928666178ee8a2ad/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/9ee77d50c1e86ac167becbe4928666178ee8a2ad/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/9ee77d50c1e86ac167becbe4928666178ee8a2ad/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 13 issues
* MAJOR 9 major
* MINOR 4 minor

Watch the comments in this conversation to review them.

#### 9 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L65](https://github.com/Minecolonies/minecolonies/blob/149b7c6985e4c2a79e8f3820fdb62995dd85bf5f/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L65): The Cyclomatic Complexity of this class is 258 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L853](https://github.com/Minecolonies/minecolonies/blob/149b7c6985e4c2a79e8f3820fdb62995dd85bf5f/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L853): The Cyclomatic Complexity of this method "handleMaterials" is 11 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L978](https://github.com/Minecolonies/minecolonies/blob/149b7c6985e4c2a79e8f3820fdb62995dd85bf5f/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L978): This method has 119 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [EntityAIStructureBuilder.java#L51](https://github.com/Minecolonies/minecolonies/blob/149b7c6985e4c2a79e8f3820fdb62995dd85bf5f/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L51): Remove the "workFrom" field and declare it as a local variable in the relevant methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1450)
1. MAJOR [StructureWrapper.java#L280](https://github.com/Minecolonies/minecolonies/blob/149b7c6985e4c2a79e8f3820fdb62995dd85bf5f/src/main/java/com/minecolonies/coremod/util/StructureWrapper.java#L280): The Cyclomatic Complexity of this method "doesStructureBlockEqualWorldBlock" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/149b7c6985e4c2a79e8f3820fdb62995dd85bf5f/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/149b7c6985e4c2a79e8f3820fdb62995dd85bf5f/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/149b7c6985e4c2a79e8f3820fdb62995dd85bf5f/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/149b7c6985e4c2a79e8f3820fdb62995dd85bf5f/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java [hunk 53]
```diff
@@ -16,6 +16,7 @@
 
 import java.util.*;
 import java.util.function.Predicate;
+import java.util.stream.Collectors;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java]: MINOR Remove this unused import 'java.util.stream.Collectors'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 14 issues
* MAJOR 9 major
* MINOR 5 minor

Watch the comments in this conversation to review them.

#### 9 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L65](https://github.com/Minecolonies/minecolonies/blob/99c9d3dc3d6ea3793a1d6c8657a32b4a6ba526d5/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L65): The Cyclomatic Complexity of this class is 261 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L856](https://github.com/Minecolonies/minecolonies/blob/99c9d3dc3d6ea3793a1d6c8657a32b4a6ba526d5/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L856): The Cyclomatic Complexity of this method "handleMaterials" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L981](https://github.com/Minecolonies/minecolonies/blob/99c9d3dc3d6ea3793a1d6c8657a32b4a6ba526d5/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L981): This method has 119 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [EntityAIStructureBuilder.java#L51](https://github.com/Minecolonies/minecolonies/blob/99c9d3dc3d6ea3793a1d6c8657a32b4a6ba526d5/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L51): Remove the "workFrom" field and declare it as a local variable in the relevant methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1450)
1. MAJOR [StructureWrapper.java#L280](https://github.com/Minecolonies/minecolonies/blob/99c9d3dc3d6ea3793a1d6c8657a32b4a6ba526d5/src/main/java/com/minecolonies/coremod/util/StructureWrapper.java#L280): The Cyclomatic Complexity of this method "doesStructureBlockEqualWorldBlock" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/99c9d3dc3d6ea3793a1d6c8657a32b4a6ba526d5/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/99c9d3dc3d6ea3793a1d6c8657a32b4a6ba526d5/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/99c9d3dc3d6ea3793a1d6c8657a32b4a6ba526d5/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/99c9d3dc3d6ea3793a1d6c8657a32b4a6ba526d5/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 13 issues
* MAJOR 9 major
* MINOR 4 minor

Watch the comments in this conversation to review them.

#### 9 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L65](https://github.com/Minecolonies/minecolonies/blob/ad5630a2bd3536dfd501632debdaa6d4242cea0f/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L65): The Cyclomatic Complexity of this class is 261 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L856](https://github.com/Minecolonies/minecolonies/blob/ad5630a2bd3536dfd501632debdaa6d4242cea0f/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L856): The Cyclomatic Complexity of this method "handleMaterials" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L981](https://github.com/Minecolonies/minecolonies/blob/ad5630a2bd3536dfd501632debdaa6d4242cea0f/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L981): This method has 119 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [EntityAIStructureBuilder.java#L51](https://github.com/Minecolonies/minecolonies/blob/ad5630a2bd3536dfd501632debdaa6d4242cea0f/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L51): Remove the "workFrom" field and declare it as a local variable in the relevant methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1450)
1. MAJOR [StructureWrapper.java#L280](https://github.com/Minecolonies/minecolonies/blob/ad5630a2bd3536dfd501632debdaa6d4242cea0f/src/main/java/com/minecolonies/coremod/util/StructureWrapper.java#L280): The Cyclomatic Complexity of this method "doesStructureBlockEqualWorldBlock" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/ad5630a2bd3536dfd501632debdaa6d4242cea0f/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/ad5630a2bd3536dfd501632debdaa6d4242cea0f/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/ad5630a2bd3536dfd501632debdaa6d4242cea0f/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/ad5630a2bd3536dfd501632debdaa6d4242cea0f/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

**Comment by marvin-bitterlich** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/426/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 54]
```diff
@@ -481,11 +500,29 @@ public void loadStructure(@NotNull final String name, int rotateTimes, BlockPos
...
+    private boolean checkIfCanceled()
+    {
+        if(job instanceof JobBuilder)
+        {
+            final WorkOrderBuild wo = ((JobBuilder) job).getWorkOrder();
+
+            if (wo == null)
+            {
+                super.resetTask();
+                ((JobBuilder) job).setWorkOrder(null);
```
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: cast only one time and no net to set workorder if it already is null

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 55]
```diff
@@ -481,11 +500,29 @@ public void loadStructure(@NotNull final String name, int rotateTimes, BlockPos
...
         }
     }
 
+    private boolean checkIfCanceled()
+    {
+        if(job instanceof JobBuilder)
+        {
+            final WorkOrderBuild wo = ((JobBuilder) job).getWorkOrder();
+
+            if (wo == null)
```
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: inline the variable

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 56]
```diff
@@ -530,7 +646,8 @@ private void requestMaterials()
      */
     private boolean clearStep(@NotNull final Structure.StructureBlock currentBlock)
     {
-        if((job instanceof JobBuilder && ((JobBuilder) job).getWorkOrder().isCleared()) || !currentStructure.getStage().equals(Structure.Stage.CLEAR))
+        if((job instanceof JobBuilder && ((JobBuilder) job).getWorkOrder() != null && ((JobBuilder) job).getWorkOrder().isCleared())
+                || !currentStructure.getStage().equals(Structure.Stage.CLEAR))
```
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:643]: properly formatting this ensures readability

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 57]
```diff
@@ -857,6 +1041,20 @@ else if (block instanceof BlockEndPortal || block instanceof BlockMobSpawner ||
         {
             return true;
         }
+        else if(block instanceof BlockFlowerPot)
+        {
+            if (!world.setBlockState(pos, blockState, 0x03))
```
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:1038]: comment explaining what this voodoo does

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 58]
```diff
@@ -744,12 +861,79 @@ private boolean handleMaterials(@NotNull final Block block, @NotNull final IBloc
...
         }
 
-        if (isBlockFree(block, block.getMetaFromState(blockState)))
+        final List<ItemStack> itemList = new ArrayList<>();
+        itemList.add(BlockUtils.getItemStackFromBlockState(blockState));
+        if(job instanceof JobBuilder && ((JobBuilder) job).getStructure() != null
+                && ((JobBuilder) job).getStructure().getBlockInfo() != null && ((JobBuilder) job).getStructure().getBlockInfo().tileentityData != null)
         {
-            return true;
+            itemList.addAll(getItemStacksOfTileEntity(((JobBuilder) job).getStructure().getBlockInfo().tileentityData));
```
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:862]: we should not hardcode the builder in an ai, that is wrong on many levels, for example for the miner it breaks stuff

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 59]
```diff
@@ -857,6 +1041,20 @@ else if (block instanceof BlockEndPortal || block instanceof BlockMobSpawner ||
...
             return true;
         }
+        else if(block instanceof BlockFlowerPot)
+        {
+            if (!world.setBlockState(pos, blockState, 0x03))
+            {
+                return false;
+            }
+
+            if(job instanceof JobBuilder && ((JobBuilder) job).getStructure().getBlockInfo().tileentityData != null)
```
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:1044]: what if a miner wants flower pots in his shaft?

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 60]
```diff
@@ -878,66 +1076,128 @@ else if (block instanceof BlockEndPortal || block instanceof BlockMobSpawner ||
...
-        final int slot = worker.findFirstSlotInInventoryWith(stack.getItem());
+        final int slot = worker.findFirstSlotInInventoryWith(stack.getItem(), stack.getItemDamage());
         if (slot != -1)
         {
             getInventory().decrStackSize(slot, 1);
-            reduceNeededResources(block);
+            reduceNeededResources(stack);
         }
+
+        final Item secondaryItem = null;
```
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: wat? always true

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 61]
```diff
@@ -878,66 +1076,128 @@ else if (block instanceof BlockEndPortal || block instanceof BlockMobSpawner ||
...
+            Log.getLogger().info("Couldn't restore entitiy", e);
+            return null;
+        }
+    }
 
-            if (entity instanceof EntityHanging)
+    private Boolean spawnEntity(@NotNull final Structure.StructureBlock currentBlock)
+    {
+        final Template.EntityInfo entityInfo = currentBlock.entity;
+        if (entityInfo != null && job instanceof JobBuilder && ((JobBuilder) job).getStructure() != null)
```
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:1132]: so miners cannot spawn entities?

**Review by marvin-bitterlich — CHANGES_REQUESTED** [review]
well hardcoding the builder is not cool

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 62]
```diff
@@ -871,73 +1063,136 @@ else if (block instanceof BlockEndPortal || block instanceof BlockMobSpawner ||
             return true;
         }
 
+        final List<ItemStack> itemList = new ArrayList<>();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MAJOR Move the declaration of "itemList" closer to the code that uses it. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1941)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 63]
```diff
@@ -20,21 +21,31 @@
...
 import net.minecraft.entity.Entity;
-import net.minecraft.entity.EntityHanging;
-import net.minecraft.entity.item.EntityMinecart;
+import net.minecraft.entity.EntityList;
+import net.minecraft.entity.item.EntityArmorStand;
+import net.minecraft.entity.item.EntityItemFrame;
 import net.minecraft.init.Blocks;
+import net.minecraft.init.Items;
 import net.minecraft.inventory.EntityEquipmentSlot;
 import net.minecraft.item.Item;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR Remove this unused import 'net.minecraft.item.Item'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 15 issues
* MAJOR 10 major
* MINOR 5 minor

Watch the comments in this conversation to review them.

#### 9 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L65](https://github.com/Minecolonies/minecolonies/blob/53d9e08b8d8299122a4b3f4bc78241ca720a0e46/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L65): The Cyclomatic Complexity of this class is 264 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L850](https://github.com/Minecolonies/minecolonies/blob/53d9e08b8d8299122a4b3f4bc78241ca720a0e46/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L850): The Cyclomatic Complexity of this method "handleMaterials" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L974](https://github.com/Minecolonies/minecolonies/blob/53d9e08b8d8299122a4b3f4bc78241ca720a0e46/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L974): This method has 121 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [EntityAIStructureBuilder.java#L51](https://github.com/Minecolonies/minecolonies/blob/53d9e08b8d8299122a4b3f4bc78241ca720a0e46/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L51): Remove the "workFrom" field and declare it as a local variable in the relevant methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1450)
1. MAJOR [StructureWrapper.java#L280](https://github.com/Minecolonies/minecolonies/blob/53d9e08b8d8299122a4b3f4bc78241ca720a0e46/src/main/java/com/minecolonies/coremod/util/StructureWrapper.java#L280): The Cyclomatic Complexity of this method "doesStructureBlockEqualWorldBlock" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/53d9e08b8d8299122a4b3f4bc78241ca720a0e46/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/53d9e08b8d8299122a4b3f4bc78241ca720a0e46/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/53d9e08b8d8299122a4b3f4bc78241ca720a0e46/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/53d9e08b8d8299122a4b3f4bc78241ca720a0e46/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 13 issues
* MAJOR 9 major
* MINOR 4 minor

Watch the comments in this conversation to review them.

#### 9 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIStructure.java#L64](https://github.com/Minecolonies/minecolonies/blob/fd46b5a766175628ae697575e1d33baea92c7da3/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L64): The Cyclomatic Complexity of this class is 264 which is greater than 200 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L849](https://github.com/Minecolonies/minecolonies/blob/fd46b5a766175628ae697575e1d33baea92c7da3/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L849): The Cyclomatic Complexity of this method "handleMaterials" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MAJOR [AbstractEntityAIStructure.java#L973](https://github.com/Minecolonies/minecolonies/blob/fd46b5a766175628ae697575e1d33baea92c7da3/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L973): This method has 121 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS138)
1. MAJOR [EntityAIStructureBuilder.java#L51](https://github.com/Minecolonies/minecolonies/blob/fd46b5a766175628ae697575e1d33baea92c7da3/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L51): Remove the "workFrom" field and declare it as a local variable in the relevant methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1450)
1. MAJOR [StructureWrapper.java#L280](https://github.com/Minecolonies/minecolonies/blob/fd46b5a766175628ae697575e1d33baea92c7da3/src/main/java/com/minecolonies/coremod/util/StructureWrapper.java#L280): The Cyclomatic Complexity of this method "doesStructureBlockEqualWorldBlock" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. MINOR [WalkToProxy.java#L241](https://github.com/Minecolonies/minecolonies/blob/fd46b5a766175628ae697575e1d33baea92c7da3/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L241): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L269](https://github.com/Minecolonies/minecolonies/blob/fd46b5a766175628ae697575e1d33baea92c7da3/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L269): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L301](https://github.com/Minecolonies/minecolonies/blob/fd46b5a766175628ae697575e1d33baea92c7da3/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L301): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)
1. MINOR [WalkToProxy.java#L312](https://github.com/Minecolonies/minecolonies/blob/fd46b5a766175628ae697575e1d33baea92c7da3/src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java#L312): Replace this fully qualified name with "Node" [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1942)

**Review by marvin-bitterlich — APPROVED** [review]
