### PR TITLE
Fix Builder trying to break water

### LINKED ISSUE #4796: Builder tries to break water
### Minecolonies version
Version: 0.11.893

### Expected behavior
I am not sure what i expected, to be honest.

### Actual behaviour
when the builder is ordered to build a building, he will first break all the blocks in that area, including water, which doesn't make much sense as the water will just regenerate in most cases.

### Steps to reproduce the problem
1. Find or create a lake
2. place a building over it
3. see the builder wasting its time by trying to break the water that is instantly regenerating

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

### PR DESCRIPTION
**Pull request by ToMe25**
Closes #4796
Closes #
Closes #

# Changes proposed in this pull request:
- Fix builder trying to break fluid blocks in the clear phase
- Fix builder ignoring waterlogged blocks
- 

Review please

### CODE REVIEW

**Comment by LDTTeam-Buildsystem** [comment]
This PR has been automatically built and hosted by our build system, during this process there was a crash, error, or otherwise, please check on this at: https://teamcity.minecolonies.com/viewLog.html?buildId=38355&buildTypeId=LetSDevTogether_Minecolonies_PullRequests_2_DeployTestServer

**Comment by ToMe25** [comment]
This should be ready now.
It currently doesn't remove non-source blocks, if it should tell me, i will just copy the sponge code then.

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 1]
```diff
@@ -960,6 +980,88 @@ protected boolean isThereAStructureToBuild()
         return currentStructure != null;
     }
 
+    private boolean fluidDetectStep(@NotNull final StructureIterator.StructureBlock currentBlock) {
+        worker.getCitizenStatusHandler().setLatestStatus(new TranslationTextComponent("com.minecolonies.coremod.status.detecting_fluids"));
+        if (!walkToConstructionSite(currentStructure.getCurrentBlockPosition()))
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:988]: that needs to be properly formatted and needs javadoc, same thing for the next method.

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 2]
```diff
@@ -130,6 +130,11 @@
      */
     private int rotation = 0;
 
+    /**
+     * all the fluids to be removed later.
+     */
+    private Map<Integer, List<BlockPos>> fluidsToRemove = new TreeMap<>();
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: this needs to be stored in the building class and serialized/deserialized so that it works on restart midway

File: src/main/java/com/minecolonies/coremod/entity/ai/util/StructureIterator.java [hunk 3]
```diff
@@ -226,11 +226,18 @@ public Result advanceBlock(final AbstractEntityAIStructure abstractEntityAIStruc
...
                   structureBlock -> structureBlock.doesStructureBlockEqualWorldBlock()
-                                      || structureBlock.worldBlock == Blocks.AIR);
+                                      || structureBlock.worldBlock == Blocks.AIR
+                                      || structureBlock.worldBlock instanceof FlowingFluidBlock);
             case BUILD:
                 return advanceBlocks(this.theStructure::incrementBlock, structureBlock -> doesStructureBlockEqualWorldBlock(structureBlock, abstractEntityAIStructure)
                                                                                          || structureBlock.block == Blocks.AIR
                                                                                          || !structureBlock.metadata.getMaterial().isSolid());
+            case FLUID_DETECT:
+            case FLUID_REMOVE:
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/util/StructureIterator.java]: I think we only need fluid detect, fluid remove is independent of block progress. (It's basically while list is not empty, return same state).

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 1 above)
Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:988]: Javadoc: yes, i missed that.
formatting: what is wrong with the formatting? i tried to make it like everything else.

File: src/main/java/com/minecolonies/coremod/entity/ai/util/StructureIterator.java (hunk 3 above)
Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/entity/ai/util/StructureIterator.java]: I didn't know the step would work without this, so i left it there, i will remove it then.

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 1 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:988]: the bracket is on the new line

Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:988]: it was like that in clearStep so i kept it like that, or did you mean they should all get moved to a new line?

File: src/main/java/com/minecolonies/coremod/entity/ai/util/StructureIterator.java (hunk 3 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/util/StructureIterator.java]: you make it a normal state (like the completion state) with the if (list.hasElements ) return getState(). else return Completion (last state)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 2 above)
Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: OK i will do that.

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 1 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:988]: all
{

}

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:988]: if that is in clear step then someone messed that one up (can you please put it on a new line for cleanStep too?)

Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:988]: ok

Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:988]: i hope i didn't miss any {

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 2 above)
Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: uhm, in what building class?

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: AbstractBuildingStructureBuilder

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 1 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:988]: awesome

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 2 above)
Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: ok thanks

File: src/main/java/com/minecolonies/coremod/entity/ai/util/StructureIterator.java (hunk 3 above)
Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/entity/ai/util/StructureIterator.java]: I did this.

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 2 above)
Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: I have tried implementing this, but as i can due to the game crashing when i try to load a world with a working builder(in the dev env only) i can't test it, so i just hope it works.

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingStructureBuilder.java [hunk 4]
```diff
@@ -79,6 +97,11 @@
      */
     private int progressCounter = 0;
 
+    /**
+     * all the fluids to be removed in fluids_remove.
+     */
+    private Map<Integer, List<BlockPos>> fluidsToRemove = new TreeMap<>();
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingStructureBuilder.java]: this should be a ordered list.

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingStructureBuilder.java [hunk 5]
```diff
@@ -408,4 +458,12 @@ public boolean requiresCompleteRequestFulfillment()
     {
         return false;
     }
+
+    /**
+     * Getter for the blocks to be removed in fluids_remove.
+     * @return the blocks to be removed in fluids_remove.
+     */
+    public Map<Integer, List<BlockPos>> getFluidsToRemove() {
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingStructureBuilder.java]: bracket

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 6]
```diff
@@ -960,6 +977,126 @@ protected boolean isThereAStructureToBuild()
...
     }
 
+    /**
+     * Works on detecting fluid blocks that should get removed.
+     * @param currentBlock the block that is currently being worked on.
+     * @return the next step once done.
+     */
+    private boolean fluidDetectStep(@NotNull final StructureIterator.StructureBlock currentBlock) {
+        worker.getCitizenStatusHandler().setLatestStatus(new TranslationTextComponent("com.minecolonies.coremod.status.detecting_fluids"));
+        if (!walkToConstructionSite(currentStructure.getCurrentBlockPosition())) {
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: bracket here and of method name

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 7]
```diff
@@ -960,6 +977,126 @@ protected boolean isThereAStructureToBuild()
...
+        }
+        return true;
+    }
+
+    /**
+     * Works on removing the fluid blocks that should get removed.
+     * @param currentBlock
+     * @return the next step once done.
+     */
+    private IAIState fluidRemoveStep() {
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: bracket

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 2 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: game crashing on startup of the world?

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: In dev mode it should crash less not more =D

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingStructureBuilder.java (hunk 4 above)
Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingStructureBuilder.java]: earlier you told me to make it an ordered map, however i forgot that and made it a tree map.
what should i make it, ordered map, or list?

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 2 above)
Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: yes, when i load a world in the dev env and there is a builder in it the game crashes.
i did post that on discord some time in the past(with log), i just didn't make an issue for it because its only in the dev env.

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingStructureBuilder.java (hunk 4 above)
Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingStructureBuilder.java]: what type of map/list should this be?
java has neither a OrderedMap nor a OrderedList.

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 2 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: can you send this to me (via pm)?

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingStructureBuilder.java (hunk 4 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingStructureBuilder.java]: LinkedHashMap

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 2 above)
Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: yes.

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingStructureBuilder.java (hunk 4 above)
Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingStructureBuilder.java]: done.

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 2 above)
Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: This should work now...

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 8]
```diff
@@ -158,7 +158,7 @@ protected AbstractEntityAIStructure(@NotNull final J job)
           /*
            * Check if we have to build something.
            */
-          new AITarget(IDLE, this::isThereAStructureToBuild, () -> START_BUILDING, 100),
+          new AITarget(IDLE, this::isThereAStructureToBuild, () -> START_BUILDING, 1),
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: That's the wrong AI state you reset it =D

Comment (ToMe25) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: I wonder why tho, i just pressed ctrl+z to undo the last change.

**Review by marchermans — DISMISSED** [review]
Generally good. However even better would be to move the Constants for the nbt names to NbtConstants.

**Comment by ToMe25** [comment]
all from that class or only the new ones?

**Comment by ToMe25** [comment]
This should be finished now, i think.

**Review by marchermans — DISMISSED** [review]

**Comment by Raycoms** [comment]
:shipit: I'll merge it as soon as the build is finished

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/4803/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Review by someaddons — APPROVED** [review]
