### PR TITLE
Fix dimension change

### LINKED ISSUE #4787: After leaving overworld dim, then returning, unable to interact with any colony object.
### Minecolonies version

Version: 0.11.888-ALPHA

### Expected behavior

I- 
That I would be able to right click on building control  block, or interact with Citizens

### Actual behaviour

- 

There is no ability to interact with colony objects.  I can add blocks, break blocks, break colony building blocks I just cannot get MC UI to load and interact.

### Steps to reproduce the problem

1. Have Active Colony
2. Travel to other dimension. I tried Nether, custom mining Dim, Dim via RFTools Dim. All exhibit same behavior.  I tried all the two custom dims separately so to ensure mods did not clash.

3. 
No UI displays when right clicking on colony interaction item like block or citizen.
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
https://gist.github.com/BrewingCoder/108c0ecf6c7817aa7157c31788865d96

- crashlog: No Crash.

### PR DESCRIPTION
**Pull request by someaddons**
Closes #4787

# Changes proposed in this pull request:
Fix dimension change subscribers add/removal, our usual onChunkEnter fails since it is coord based on the entities current world obj so it can't compare the right chunk objects from two different worlds.

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
:shipit: @OrionDevelopment 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/4791/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

File: src/main/java/com/minecolonies/coremod/event/EventHandler.java [hunk 1]
```diff
@@ -210,6 +210,57 @@ public static void onChunkUnLoad(final ChunkEvent.Unload event)
...
+    @SubscribeEvent(priority = LOWEST)
+    public static void onEntityTravelToDimensionEvent(final EntityTravelToDimensionEvent event)
+    {
+        if (event.getEntity() instanceof ServerPlayerEntity && !event.isCanceled())
+        {
+            final ServerPlayerEntity player = (ServerPlayerEntity) event.getEntity();
+            final Chunk oldChunk = player.world.getChunk(player.chunkCoordX, player.chunkCoordZ);
+            final IColonyTagCapability oldCloseColonies = oldChunk.getCapability(CLOSE_COLONY_CAP, null).orElse(null);
+            // Remove visiting/subscriber from old colony
+            if (oldCloseColonies.getOwningColony() != 0)
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/event/EventHandler.java]: Null check please! Since you are explicitly returning null for the orElse(...) and it is possible that the capability does not exist for some reason or another, a null check is required here.

**Review by marchermans — CHANGES_REQUESTED** [review]

**Comment by LDTTeam-Buildsystem** [comment]
This PR has been automatically built and hosted by our build system, during this process there was a crash, error, or otherwise, please check on this at: https://teamcity.minecolonies.com/viewLog.html?buildId=38259&buildTypeId=LetSDevTogether_Minecolonies_PullRequests_2_DeployTestServer
