### PR TITLE
Adjust WorldUtil.isChunkLoaded and ChunkCache for compatibility with Moonrise chunk system

### LINKED ISSUE #10417: Town hall crash
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.774

### Structurize Version

1.0.754

### Related Mods and their Versions

_No response_

### Current Behavior

If you reinstate a settlement then click on sign and found colony the game will crash.

### Expected Behavior

The game not to crash after clicking Sign and found colony

### Reproduction Steps

1. Find abandoned settlement
2. Open the town hall
3. Click on Reinstate button
4. Click on sign and found colony button
5. Crash

### Logs

https://pste.me/@jHN5B_i3TDY & https://pste.me/@5PcytE9Oib8

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
[](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6109)

### LINKED ISSUE #10418: Crash on placing Camp Supply building in Fortress style
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.774

### Structurize Version

1.0.754

### Related Mods and their Versions

Direwolf20 Modpack for Minecraft 1.21 Version 1.4

neoforge-21.1.74
Mod List: 
accelerated-decay-neoforge-21.0.0.jar |Accelerated Decay |accelerateddecay|21.0.0|Manifest: NOSIGNATURE
actuallyharvest-1.21.1-1.1.1.1-NEOFORGE.jar |ActuallyHarvest |actuallyharvest |1.1.1.1 |Manifest: NOSIGNATURE
curios-neoforge-9.1.4+1.21.0.jar|Adorned API |curios|9.1.4+1.21.0|Manifest: NOSIGNATURE
AdvancedAE-1.1.1-1.21.1.jar |Advanced AE |advanced_ae |1.1.1-1.21.1|Manifest: NOSIGNATURE
ae2jeiintegration-1.2.0.jar |AE2 JEI Integration |ae2jeiintegration |1.2.0 |Manifest: NOSIGNATURE
AE2-Things-1.4.2-beta.jar |AE2 Things|ae2things |1.4.2-beta|Manifest: NOSIGNATURE
ae2ct-1.21.1-1.0.3-beta.jar |AE2:Crafting Tree |ae2ct |1.21.1-1.0.3-beta |Manifest: NOSIGNATURE
AE2NetworkAnalyzer-1.21-2.0.1-neoforge.jar|AE2NetworkAnalyzer|ae2netanalyser|1.21-2.0.1-neoforge |Manifest: NOSIGNATURE
ae2wtlib-19.1.6-beta.jar|AE2WTLib|ae2wtlib|19.1.6-beta |Manifest: NOSIGNATURE
de.mari_023.ae2wtlib_api-19.1.6-beta.jar|AE2WTLib API|ae2wtlib_api|19.1.6-beta |Manifest: NOSIGNATURE
almostunified-neoforge-1.21.1-1.2.2.jar |AlmostUnified |almostunified |1.21.1-1.2.2|Manifest: NOSIGNATURE
ApothicAttributes-1.21.1-2.4.0.jar|Apothic Attributes|apothic_attributes|2.4.0 |Manifest: NOSIGNATURE
ApothicEnchanting-1.21.1-1.2.3.jar|Apothic Enchanting|apothic_enchanting|1.2.3 |Manifest: NOSIGNATURE
ApothicSpawners-1.21.1-1.1.1.jar|Apothic Spawners|apothic_spawners|1.1.1 |Manifest: NOSIGNATURE
appleskin-neoforge-mc1.21-3.0.5.jar |AppleSkin |appleskin |3.0.5+mc1.21|Manifest: NOSIGNATURE
appliedenergistics2-19.0.23-beta.jar|Applied Energistics 2 |ae2 |19.0.23-beta|Manifest: NOSIGNATURE
Applied-Mekanistics-1.6.1.jar |Applied Mekanistics |appmek|1.6.1 |Manifest: NOSIGNATURE
AppliedFlux-1.21-2.0.2-neoforge.jar |AppliedFlux |appflux |1.21-2.0.2-neoforge |Manifest: NOSIGNATURE
architectury-13.0.8-neoforge.jar|Architectury|architectury|13.0.8|Manifest: NOSIGNATURE
ArmorPoser-neoforge-1.21.1-6.1.3.jar|Armor Poser |armorposer|6.1.3 |Manifest: NOSIGNATURE
ars_elemental-1.21.1-0.7.0.9.jar|Ars Elemental |ars_elemental |0.7.0.9 |Manifest: NOSIGNATURE
ars_nouveau-1.21.1-5.2.3-all.jar|Ars Nouveau |ars_nouveau |5.2.3 |Manifest: NOSIGNATURE
arsnouveaudelight-1.0.3.4-1.21.x.jar|Ars Nouveau Delight |arsnouveaudelight |1.0.3.4-1.21.x|Manifest: NOSIGNATURE
athena-neoforge-1.21-4.0.1.jar|Athena|athena|4.0.1 |Manifest: NOSIGNATURE
bagofyurting-1.21-5.0.0.0.jar |Bag of Yurting|bagofyurting|5.0.0.0 |Manifest: NOSIGNATURE
bagus_lib-1.21.1-13.5.0.jar |Bagus Lib |bagus_lib |1.21.1-13.5.0 |Manifest: NOSIGNATURE
balm-neoforge-1.21.1-21.0.20.jar|Balm|balm|21.0.20 |Manifest: NOSIGNATURE
bankstorage-1.4.2+1.21.jar|Bank Storage|bankstorage |1.4.2+1.21|Manifest: NOSIGNATURE
BetterAdvancements-NeoForge-1.21.1-0.4.3.21.jar |Better Advancements |betteradvancements|0.4.3.21|Manifest: NOSIGNATURE
BetterF3-11.0.3-NeoForge-1.21.1.jar |BetterF3|betterf3|11.0.3|Manifest: NOSIGNATURE
buildinggadgets2-1.3.7.jar|Building Gadgets 2|buildinggadgets2|1.3.7 |Manifest: NOSIGNATURE
caelus-neoforge-7.0.1+1.21.1.jar|Caelus API|caelus|7.0.1+1.21.1|Manifest: NOSIGNATURE
CarbonConfig-Neoforge-1.21-1.2.9.2.jar|Carbon Config Library |carbonconfig|0.0NONE |Manifest: NOSIGNATURE
cc-tweaked-1.21.1-forge-1.113.1.jar |CC: Tweaked |computercraft |1.113.1 |Manifest: NOSIGNATURE
chalk-1.6.8.jar |Chalk |chalk |1.6.8 |Manifest: NOSIGNATURE
charginggadgets-1.14.1.jar|Charging Gadgets|charginggadgets |1.14.1|Manifest: NOSIGNATURE
chipped-neoforge-1.21.1-4.0.2.jar |Chipped |chipped |4.0.2 |Manifest: NOSIGNATURE
cleanswing-1.7.jar|Clean Swing |cleanswing|1.7 |Manifest: NOSIGNATURE
cleanview-1.21.1-v1-neoforge.jar|CleanView |cleanview |1.21.1-v1-neoforge|Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
cloth-config-15.0.140-neoforge.jar|Cloth Config v15 API|cloth_config|15.0.140|Manifest: NOSIGNATURE
Clumps-neoforge-1.21.1-19.0.0.1.jar |Clumps|clumps|19.0.0.1|Manifest: NOSIGNATURE
collective-1.21.1-7.87.jar|Collective|collective|7.87|Manifest: NOSIGNATURE
colorfulhearts-neoforge-1.21.1-10.3.8.jar |Colorful Hearts |colorfulhearts|10.3.8|Manifest: NOSIGNATURE
comforts-neoforge-9.0.3+1.21.1.jar|Comforts|comforts|9.0.3+1.21.1|Manifest: NOSIGNATURE
common-networking-neoforge-1.0.17-beta.2-1.21.1.ja|Common Networking |commonnetworking|1.0.17-beta.2-1.21.1|Manifest: NOSIGNATURE
CommonCapabilities-1.21.1-neoforge-2.9.5.jar|CommonCapabilities|commoncapabilities|2.9.5 |Manifest: NOSIGNATURE
Controlling-neoforge-1.21.1-19.0.3.jar|Controlling |controlling |19.0.3|Manifest: NOSIGNATURE
cookingforblockheads-neoforge-1.21.1-21.1.3.jar |Cooking for Blockheads|cookingforblockheads|21.1.3|Manifest: NOSIGNATURE
coroutil-neoforge-1.21.0-1.3.8.jar|CoroUtil|coroutil|1.21.0-1.3.8|Manifest: NOSIGNATURE
cosmeticarmorreworked-1.21.1-v1-neoforge.jar|CosmeticArmorReworked |cosmeticarmorreworked |1.21.1-v1-neoforge|Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
cottonly-neo-0.16.4.jar |Cottonly|cottonly|0.16.4|Manifest: NOSIGNATURE
craftingtweaks-neoforge-1.21.1-21.1.3.jar |Crafting Tweaks |craftingtweaks|21.1.3|Manifest: NOSIGNATURE
CreativeCore_NEOFORGE_v2.12.22_mc1.21.1.jar |CreativeCore|creativecore|2.12.22 |Manifest: NOSIGNATURE
Cucumber-1.21.1-8.0.7.jar |Cucumber Library|cucumber|8.0.7 |Manifest: NOSIGNATURE
cupboard-1.21-2.8.jar |Cupboard mod|cupboard|2.8 |Manifest: NOSIGNATURE
cyclopscore-1.21.1-neoforge-1.25.2-634.jar|Cyclops Core|cyclopscore |1.25.2|Manifest: NOSIGNATURE
domum_ornamentum-1.0.204-1.21.1-snapshot.jar|Domum Ornamentum|domum_ornamentum|1.0.204-1.21.1-snaps|Manifest: NOSIGNATURE
DungeonCrawl-NeoForge-1.21-2.3.14.jar |Dungeon Crawl |dungeoncrawl|2.3.14|Manifest: NOSIGNATURE
easy-piglins-neoforge-1.21.1-1.0.13.jar |Easy Piglins|easy_piglins|1.21.1-1.0.13 |Manifest: NOSIGNATURE
easy-villagers-neoforge-1.21.1-1.1.23.jar |Easy Villagers|easy_villagers|1.21.1-1.1.23 |Manifest: NOSIGNATURE
EdivadLib-1.21-3.0.0.jar|EdivadLib |edivadlib |3.0.0 |Manifest: NOSIGNATURE
elevatorid-neoforge-1.21.1-1.11.3.jar |ElevatorMod |elevatorid|1.21.1-1.11.3 |Manifest: NOSIGNATURE
Emojiful-Neoforge-1.21-5.1.5-all.jar|Emojiful|emojiful|5.1.5 |Manifest: NOSIGNATURE
EnchantableBlocks-1.21.1-0.1.3.2.jar|Enchantable Blocks|enchantableblocks |0.1.3.2 |Manifest: NOSIGNATURE
enchantwithmob-1.21.1-20.3.0.jar|EnchantWithMob|enchantwithmob|1.21.1-20.3.0 |Manifest: NOSIGNATURE
com.enderio.endercore-7.0.9-alpha.jar |Ender Core|endercore |7.0.9-alpha |Manifest: NOSIGNATURE
enderio-7.0.9-alpha.jar |Ender IO|enderio |7.0.9-alpha |Manifest: NOSIGNATURE
com.enderio.enderio-armory-7.0.9-alpha.jar|Ender IO Armory |enderio_armory|7.0.9-alpha |Manifest: NOSIGNATURE
com.enderio.enderio-base-7.0.9-alpha.jar|Ender IO Base |enderio_base|7.0.9-alpha |Manifest: NOSIGNATURE
com.enderio.enderio-conduits-7.0.9-alpha.jar|Ender IO Conduits |enderio_conduits|7.0.9-alpha |Manifest: NOSIGNATURE
com.enderio.enderio-machines-7.0.9-alpha.jar|Ender IO Machines |enderio_machines|7.0.9-alpha |Manifest: NOSIGNATURE
com.enderio.enderio-conduits-modded-7.0.9-alpha.ja|Ender IO Modded Conduits|enderio_conduits_modded |7.0.9-alpha |Manifest: NOSIGNATURE
entangled-1.3.19a-neoforge-mc1.21.jar |Entangled |entangled |1.3.19+a|Manifest: NOSIGNATURE
eventslib-1.0.55.jar|EventsLib |eventslib |1.0.55|Manifest: NOSIGNATURE
EvilCraft-1.21.1-neoforge-1.2.59.jar|EvilCraft |evilcraft |1.2.59|Manifest: NOSIGNATURE
ExtendedAE-1.21-2.1.3-neoforge.jar|ExtendedAE|extendedae|1.21-2.1.3-neoforge |Manifest: NOSIGNATURE
ExtremeReactors2-1.21.1-2.4.13.jar|Extreme Reactors|bigreactors |1.21.1-2.4.13 |Manifest: NOSIGNATURE
ExtremeSoundMuffler-3.48.3_NeoForge-1.21.jar|Extreme Sound Muffler |extremesoundmuffler |3.48.3|Manifest: NOSIGNATURE
fancymenu_neoforge_3.3.2_MC_1.21.1.jar|FancyMenu |fancymenu |3.3.2 |Manifest: NOSIGNATURE
fargostalismans-2.1.7.jar |Fargo's Talismans |fargostalismans |2.1.7 |Manifest: NOSIGNATURE
FarmersDelight-1.21.1-1.2.5.jar |Farmer's Delight|farmersdelight|1.2.5 |Manifest: NOSIGNATURE
farmingforblockheads-neoforge-1.21.1-21.1.2.jar |Farming for Blockheads|farmingforblockheads|21.1.2|Manifest: NOSIGNATURE
ferritecore-7.0.2-neoforge.jar|Ferrite Core|ferritecore |7.0.2 |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
findme-3.3.1-neoforge.jar |FindMe|findme|3.3.1 |Manifest: NOSIGNATURE
FlowerPatch-neoforge-1.21-7.0.1.jar |Flower Patch|flowerpatch |7.0.1 |Manifest: NOSIGNATURE
ForgeConfigAPIPort-v21.1.1-1.21.1-NeoForge.jar|Forge Config API Port |forgeconfigapiport|21.1.1|Manifest: NOSIGNATURE
fabric-api-base-0.4.42+d1308ded19.jar |Forgified Fabric API Base |fabric_api_base |0.4.42+d1308ded19 |Manifest: NOSIGNATURE
fabric-block-view-api-v2-1.0.10+9afaaf8c19.jar|Forgified Fabric BlockView API|fabric_block_view_api_v2|1.0.10+9afaaf8c19 |Manifest: NOSIGNATURE
fabric-renderer-api-v1-3.4.0+acb05a3919.jar |Forgified Fabric Renderer API |fabric_renderer_api_v1|3.4.0+acb05a3919|Manifest: NOSIGNATURE
fabric-rendering-data-attachment-v1-0.3.48+73761d2|Forgified Fabric Rendering Dat|fabric_rendering_data_attachme|0.3.48+73761d2e19 |Manifest: NOSIGNATURE
formations-1.0.2-neoforge-mc1.21.jar|Formations|formations|1.0.2 |Manifest: NOSIGNATURE
formationsnether-1.0.5-mc1.21+.jar|Formations Nether |formationsnether|1.0.5 |Manifest: NOSIGNATURE
FramedBlocks-10.2.1.jar |FramedBlocks|framedblocks|10.2.1|Manifest: NOSIGNATURE
ftb-auxilium-neoforge-21.0.1.jar|FTB Auxilium|ftbauxilium |21.0.1|Manifest: NOSIGNATURE
ftbbackups2-neoforge-1.21-1.0.28.jar|FTB Backups 2 |ftbbackups2 |1.0.28|Manifest: NOSIGNATURE
ftb-chunks-neoforge-2101.1.2.jar|FTB Chunks|ftbchunks |2101.1.2|Manifest: NOSIGNATURE
ftb-essentials-neoforge-2101.1.0.jar|FTB Essentials|ftbessentials |2101.1.0|Manifest: NOSIGNATURE
ftbjeiextras-21.1.1.jar |FTB Jei Extras|ftbjeiextras|21.1.1|Manifest: NOSIGNATURE
ftb-library-neoforge-2101.1.4.jar |FTB Library |ftblibrary|2101.1.4|Manifest: NOSIGNATURE
ftb-pack-companion-neoforge-21.1.0-beta.1+mc1.21.1|FTB Pack Companion|ftbpc |21.1.0-beta.1+mc1.21|Manifest: NOSIGNATURE
ftb-teams-neoforge-2101.1.0.jar |FTB Teams |ftbteams|2101.1.0|Manifest: NOSIGNATURE
ftb-xmod-compat-neoforge-21.1.1.jar |FTB XMod Compat |ftbxmodcompat |21.1.1|Manifest: NOSIGNATURE
functionalstorage-1.21.1-1.3.5.jar|Functional Storage|functionalstorage |1.21.1-1.3.5|Manifest: NOSIGNATURE
fusion-1.1.1a-neoforge-mc1.21.jar |Fusion|fusion|1.1.1+a |Manifest: NOSIGNATURE
gag-5.0.1.jar |Gadgets Against Grind |gag |5.0.1 |Manifest: NOSIGNATURE
GatewaysToEternity-1.21.1-5.0.1.jar |Gateways To Eternity|gateways|5.0.1 |Manifest: NOSIGNATURE
geckolib-neoforge-1.21.1-4.7.jar|GeckoLib 4|geckolib|4.7 |Manifest: NOSIGNATURE
GeOre-1.21-6.0.4.jar|GeOre |geore |6.0.4 |Manifest: NOSIGNATURE
GeOre_Nouveau-1.21.1-0.5.1.jar|GeOre Nouveau |georenouveau|0.5.1 |Manifest: NOSIGNATURE
Glassential-renewed-neoforge-1.21.1-3.1.4.jar |Glassential-renewed |glassential |3.1.4 |Manifest: NOSIGNATURE
Glodium-1.21-2.2-neoforge.jar |Glodium |glodium |1.21-2.2-neoforge |Manifest: NOSIGNATURE
gpumemleakfix-1.21-1.8.jar|Gpu memory leak fix |gpumemleakfix |1.8 |Manifest: NOSIGNATURE
gravestone-neoforge-1.21.1-1.0.24.jar |Gravestone Mod|gravestone|1.21.1-1.0.24 |Manifest: NOSIGNATURE
handcrafted-neoforge-1.21.1-4.0.2.jar |Handcrafted |handcrafted |4.0.2 |Manifest: NOSIGNATURE
HostileNeuralNetworks-1.21.1-6.1.0.jar|Hostile Neural Networks |hostilenetworks |6.1.0 |Manifest: NOSIGNATURE
hyperbox-1.21-6.0.0.1.jar |Hyperbox|hyperbox|6.0.0.1 |Manifest: NOSIGNATURE
industrialforegoing-1.21-3.6.19.jar |Industrial Foregoing|industrialforegoing |1.21-3.6.19 |Manifest: NOSIGNATURE
industrial-foregoing-souls-1.21.1-1.10.1.jar|Industrial Foregoing Souls|industrialforegoingsouls|1.10.1|Manifest: NOSIGNATURE
infiniverse-1.21-2.0.1.0.jar|Infiniverse |infiniverse |2.0.1.0 |Manifest: NOSIGNATURE
IntegratedCrafting-1.21.1-neoforge-1.1.11.jar |IntegratedCrafting|integratedcrafting|1.1.11|Manifest: NOSIGNATURE
IntegratedDynamics-1.21.1-neoforge-1.23.15.jar|IntegratedDynamics|integrateddynamics|1.23.15 |Manifest: NOSIGNATURE
IntegratedScripting-1.21.1-neoforge-1.0.6.jar |IntegratedScripting |integratedscripting |1.0.6 |Manifest: NOSIGNATURE
IntegratedTerminals-1.21.1-neoforge-1.6.4.jar |IntegratedTerminals |integratedterminals |1.6.4 |Manifest: NOSIGNATURE
IntegratedTunnels-1.21.1-neoforge-1.8.28.jar|IntegratedTunnels |integratedtunnels |1.8.28|Manifest: NOSIGNATURE
ironfurnaces-neoforge-1.21.1-4.2.6.jar|Iron Furnaces |ironfurnaces|4.2.6 |Manifest: NOSIGNATURE
IronJetpacks-1.21.1-8.0.5.jar |Iron Jetpacks |ironjetpacks|8.0.5 |Manifest: NOSIGNATURE
irons_spellbooks-1.21-3.8.4.jar |Iron's Spells 'n Spellbooks |irons_spellbooks|1.21-3.8.4|Manifest: NOSIGNATURE
Jade-1.21.1-NeoForge-15.8.2.jar |Jade|jade|15.8.2+neoforge |Manifest: NOSIGNATURE
JAOPCA-1.21.1-5.0.4.5.jar |JAOPCA|jaopca|5.0.4.5 |Manifest: NOSIGNATURE
jumbofurnace-1.21.1-5.0.0.7.jar |Jumbo Furnace |jumbofurnace|5.0.0.7 |Manifest: NOSIGNATURE
jumpoverfences-neoforge-1.21-1.6.0.jar|Jump Over Fences|jumpoverfences|1.6.0 |Manifest: NOSIGNATURE
jamd-neo-5.1.0+mc1.21.1.jar |Just Another Mining Dimension |jamd|5.1.0 |Manifest: NOSIGNATURE
javd-neo-9.0.0+mc1.21.1.jar |Just Another Void Dimension |javd|9.0.0 |Manifest: NOSIGNATURE
justdirethings-1.4.8.jar|Just Dire Things|justdirethings|1.4.8 |Manifest: NOSIGNATURE
justenoughbreeding-neoforge-1.21.x-1.4.0.jar|Just Enough Breeding|justenoughbreeding|1.4.0 |Manifest: NOSIGNATURE
jeed-1.21-2.2.8.jar |Just Enough Effects Descriptio|jeed|1.21-2.2.8|Manifest: NOSIGNATURE
jei-1.21.1-neoforge-19.21.0.247.jar |Just Enough Items |jei |19.21.0.247 |Manifest: NOSIGNATURE
JustEnoughMekanismMultiblocks-1.21.1-7.1.jar|Just Enough Mekanism Multibloc|jei_mekanism_multiblocks|7.1 |Manifest: NOSIGNATURE
JustEnoughProfessions-neoforge-1.21.1-4.0.3.jar |Just Enough Professions (JEP) |justenoughprofessions |4.0.3 |Manifest: NOSIGNATURE
keepmysoiltilled-1.21.1-2.4.jar |Keep My Soil Tilled |keepmysoiltilled|2.4 |Manifest: NOSIGNATURE
konkrete_neoforge_1.9.9_MC_1.21.jar |Konkrete|konkrete|1.9.9 |Manifest: NOSIGNATURE
kubejs-neoforge-2101.7.1-build.181.jar|KubeJS|kubejs|2101.7.1-build.181|Manifest: NOSIGNATURE
kuma-api-neoforge-21.0.5-SNAPSHOT.jar |KumaAPI |kuma_api|21.0.5-SNAPSHOT |Manifest: NOSIGNATURE
laserbridges-1.21.1-1-neoforge.jar|Laser Bridges & Doors |laserbridges|1.21.1-1-neoforge |Manifest: NOSIGNATURE
laserio-1.9.11.jar|LaserIO |laserio |1.9.11|Manifest: NOSIGNATURE
light-overlay-12.0.0-neoforge.jar |Light Overlay |lightoverlay|12.0.0|Manifest: NOSIGNATURE
lithosphere-1.3.jar |Lithosphere |mr_lithosphere|1.3 |Manifest: NOSIGNATURE
lithostitched-neoforge-1.21.1-1.3.4.jar |Lithostitched |lithostitched |1.3.4 |Manifest: NOSIGNATURE
LittleTiles_ALPHA_v1.6.0-pre133_mc1.21.1.jar|LittleTiles |littletiles |1.6.0-pre133|Manifest: NOSIGNATURE
logbegone-neoforge-1.21.1-1.0.3.jar |Log Begone|logbegone |1.0.3 |Manifest: NOSIGNATURE
lootintegrations-1.21-3.9.jar |Lootintegrations mod|lootintegrations|3.9 |Manifest: NOSIGNATURE
lootintegrations_yungs-1.2.jar|lootintegrations_yungs mod|lootintegrations_yungs|1 |Manifest: NOSIGNATURE
lootr-neoforge-1.21-1.10.33.85.jar|Lootr |lootr |1.21-1.10.33.85 |Manifest: NOSIGNATURE
MagicDoorknob-1.21.1-1.1.0.1948.jar |Magic Doorknob|magic_doorknob|1.21.1-1.1.0.1948 |Manifest: NOSIGNATURE
mcjtylib-1.21-9.0.4.jar |McJtyLib|mcjtylib|1.21-9.0.4|Manifest: NOSIGNATURE
merequester-neoforge-1.21.1-1.1.8.jar |ME Requester|merequester |1.21.1-1.1.8|Manifest: NOSIGNATURE
Measurements-neoforge-1.21-3.0.0.jar|Measurements|measurements|3.0.0 |Manifest: NOSIGNATURE
megacells-4.1.0.jar |MEGA Cells|megacells |4.1.0 |Manifest: NOSIGNATURE
Mekanism-1.21.1-10.7.7.64.jar |Mekanism|mekanism|10.7.7|Manifest: NOSIGNATURE
MekanismLasers-1.21.1-1.1.7.jar |Mekanism Lasers |mekanism_lasers |1.1.7 |Manifest: NOSIGNATURE
mekanism_turrets-2.0.9.jar|Mekanism Turrets|mekanism_turrets|2.0.9 |Manifest: NOSIGNATURE
mekanism_unleashed-1.21-0.2.1.jar |Mekanism Unleashed|mekanism_unleashed|1.21-0.2.1|Manifest: NOSIGNATURE
MekanismAdditions-1.21.1-10.7.7.64.jar|Mekanism: Additions |mekanismadditions |10.7.7|Manifest: NOSIGNATURE
MekanismGenerators-1.21.1-10.7.7.64.jar |Mekanism: Generators|mekanismgenerators|10.7.7|Manifest: NOSIGNATURE
melody_neoforge_1.0.10_MC_1.21.jar|Melody|melody|1.0.10|Manifest: NOSIGNATURE
minecolonies-1.1.774-1.21.1-snapshot.jar|MineColonies|minecolonies|1.1.774-1.21.1-snaps|Manifest: NOSIGNATURE
client-1.21.1-20240808.144430-srg.jar |Minecraft |minecraft |1.21.1|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
mininggadgets-1.18.6.jar|Mining Gadgets|mininggadgets |1.18.6|Manifest: NOSIGNATURE
mob_grinding_utils-1.1.6+mc1.21.1.jar |Mob Grinding Utils|mob_grinding_utils|1.1.6+mc1.21.1|Manifest: NOSIGNATURE
Modern-Dynamics-0.9.2.jar |Modern Dynamics |moderndynamics|0.9.2 |Manifest: NOSIGNATURE
modernfix-neoforge-5.19.5+mc1.21.1.jar|ModernFix |modernfix |5.19.5+mc1.21.1 |Manifest: NOSIGNATURE
modonomicon-1.21.1-neoforge-1.108.2.jar |Modonomicon |modonomicon |1.108.2 |Manifest: NOSIGNATURE
modular-routers-13.1.0+mc1.21.1.jar |Modular Routers |modularrouters|13.1.0|Manifest: NOSIGNATURE
Moonrise-NeoForge-0.1.0-beta.8+68ea18b.jar|Moonrise|moonrise|0.1.0-beta.8+68ea18b|Manifest: NOSIGNATURE
morered-1.21.1-6.0.0.3.jar|More Red|morered |6.0.0.3 |Manifest: NOSIGNATURE
MoreRed-CCT-Compat-1.21.1-1.1.0.jar |More Red x CC:Tweaked Compat|moreredxcctcompat |1.21.1-1.1.0|Manifest: NOSIGNATURE
MouseTweaks-neoforge-mc1.21-2.26.1.jar|Mouse Tweaks|mousetweaks |2.26.1|Manifest: NOSIGNATURE
multipiston-1.2.51-1.21.1-snapshot.jar|Multi-Piston|multipiston |1.2.51-1.21.1-snapsh|Manifest: NOSIGNATURE
NaturesCompass-1.21.1-3.0.3-neoforge.jar|Nature's Compass|naturescompass|1.21.1-3.0.2-neoforg|Manifest: NOSIGNATURE
Neat-1.21-40-NEOFORGE.jar |Neat|neat|1.21-40-NEOFORGE|Manifest: NOSIGNATURE
neoforge-21.1.74-universal.jar|NeoForge|neoforge|21.1.74 |Manifest: NOSIGNATURE
netherportalfix-neoforge-1.21.1-21.1.1.jar|NetherPortalFix |netherportalfix |21.1.1|Manifest: NOSIGNATURE
not_enough_glyphs-1.21.1-4.0.2.jar|Not Enough Glyphs |not_enough_glyphs |4.0.2 |Manifest: NOSIGNATURE
Not Enough Recipe Book-NEOFORGE-0.4.1.jar |Not Enough Recipe Book|nerb|0.4.1 |Manifest: NOSIGNATURE
NotableBubbleText-1.21-4.0.0.jar|Notable Bubble Text |nbt |4.0.0 |Manifest: NOSIGNATURE
occultism-1.21.1-neoforge-1.166.0.jar |Occultism |occultism |1.166.0 |Manifest: NOSIGNATURE
occultism_kubejs-1.21.1-neoforge-1.8.0.jar|Occultism KubeJS|occultism_kubejs|1.8.0 |Manifest: NOSIGNATURE
OctoLib-NEOFORGE-0.4.2.jar|OctoLib |octolib |0.4.2 |Manifest: NOSIGNATURE
OpenBlocksTrophies-1.21-4.3.27.jar|OpenBlocks Trophies |obtrophies|1.21-4.3.27 |Manifest: NOSIGNATURE
overloadedarmorbar-neoforge-1.21-2.jar|OverloadedArmorBar|overloadedarmorbar|2 |Manifest: NOSIGNATURE
Patchouli-1.21-87-NEOFORGE.jar|Patchouli |patchouli |1.21-87-NEOFORGE|Manifest: NOSIGNATURE
pipe_connector-neoforge-0.5.3.jar |Pipe Connector|pipe_connector|0.5.3 |Manifest: NOSIGNATURE
pipez-neoforge-1.21.1-1.2.19.jar|Pipez |pipez |1.21.1-1.2.19 |Manifest: NOSIGNATURE
Placebo-1.21.1-9.5.4.jar|Placebo |placebo |9.5.4 |Manifest: NOSIGNATURE
player-animation-lib-forge-2.0.0-alpha1+1.21.jar|Player Animator |playeranimator|2.0.0-alpha1+1.21 |Manifest: NOSIGNATURE
pneumaticcraft-repressurized-8.2.3+mc1.21.1.jar |PneumaticCraft: Repressurized |pneumaticcraft|8.2.3 |Manifest: NOSIGNATURE
pocketstorage-1.2.4+1.21.1-b40.jar|Pocket Storage|pocketstorage |1.2.4+1.21.1-b40|Manifest: NOSIGNATURE
polylib-2100.0.3-build.159-neoforge.jar |PolyLib |polylib |2100.0.3-build.159|Manifest: NOSIGNATURE
Powah-6.1.2.jar |Powah |powah |6.1.2 |Manifest: NOSIGNATURE
productivelib-1.21.0-0.1.8.jar|Productive Lib|productivelib |1.21.0-0.1.8|Manifest: NOSIGNATURE
pmc-1.0.1.jar |Productive Tree and Mekanism C|pmc |1.0.1 |Manifest: NOSIGNATURE
productivetrees-1.21.1-0.5.6.jar|Productive Trees|productivetrees |1.21.1-0.5.6|Manifest: NOSIGNATURE
projectvibrantjourneys-1.21.1-7.0.3.jar |Project: Vibrant Journeys |projectvibrantjourneys|1.21.1-7.0.3|Manifest: NOSIGNATURE
quickpaths-1.21.1-3.5.jar |Quick Paths |quickpaths|3.5 |Manifest: NOSIGNATURE
railcraft-reborn-1.21.1-1.2.2.jar |Railcraft Reborn|railcraft |1.2.2 |Manifest: NOSIGNATURE
RainShield-1.21.1-2.0.1.jar |Rain Shield |rainshield|2.0.1 |Manifest: NOSIGNATURE
rechiseled-1.1.6a-neoforge-mc1.21.jar |Rechiseled|rechiseled|1.1.6+a |Manifest: NOSIGNATURE
rechiseled_chipped-1.2.jar|Rechiseled: Chipped |rechiseled_chipped|1.2 |Manifest: NOSIGNATURE
redstonepen-1.21-neoforge-1.11.41.jar |Redstone Pen|redstonepen |1.11.41 |Manifest: bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
relics-1.21-0.9.2.0.jar |Relics|relics|0.9.2.0 |Manifest: NOSIGNATURE
repeatable_trial_vaults-neoforge-1.21-1.0.2.jar |Repeatable Trial Vaults |repeatable_trial_vaults |1.0.2 |Manifest: NOSIGNATURE
repurposed_structures-7.5.10+1.21.1-neoforge.jar|Repurposed Structures |repurposed_structures |7.5.10+1.21.1-neofor|Manifest: NOSIGNATURE
repurposed_structures_pneumaticcraft_repressurized|Repurposed Structures - Pneuma|repurposed_structures_pneumati|6 |Manifest: NOSIGNATURE
resourcefullib-neoforge-1.21-3.0.11.jar |Resourceful Lib |resourcefullib|3.0.11|Manifest: NOSIGNATURE
rftoolsbase-1.21-6.0.1.jar|RFToolsBase |rftoolsbase |1.21-6.0.1|Manifest: NOSIGNATURE
rftoolspower-1.21-7.0.0.jar |RFToolsPower|rftoolspower|1.21-7.0.0|Manifest: NOSIGNATURE
rhino-2101.2.5-build.54.jar |Rhino |rhino |2101.2.5-build.54 |Manifest: NOSIGNATURE
rgp_client-1.0.2.jar|Rocket Game Platform Client |rgp_client|1.0.2 |Manifest: NOSIGNATURE
Searchables-neoforge-1.21.1-1.0.2.jar |Searchables |searchables |1.0.2 |Manifest: NOSIGNATURE
servercore-neoforge-1.5.5+1.21.1.jar|ServerCore|servercore|1.5.5+1.21.1|Manifest: NOSIGNATURE
shrink-2.0.0.43-neoforge.jar|Shrink|shrink|2.0.0.43|Manifest: NOSIGNATURE
SimpleDiscordRichPresence-neoforge-87.0.1-build.49|Simple Discord Rich Presence|sdrp|87.0.1-build.49+mc1.|Manifest: NOSIGNATURE
inventorysorter-1.21-24.0.5.jar |Simple Inventory Sorter |inventorysorter |24.0.5|Manifest: NOSIGNATURE
simplemagnets-1.1.12-neoforge-mc1.21.jar|Simple Magnets|simplemagnets |1.1.12|Manifest: NOSIGNATURE
SimpleTeleportersReforged-1.21-2.0.0.jar|Simple Teleporters|simpleteleporters |2.0.0 |Manifest: NOSIGNATURE
simple_weather-1.0.7.jar|Simple Weather|simple_weather|1.0.7 |Manifest: NOSIGNATURE
simplylight-1.4.6+1.21-b53.jar|Simply Light|simplylight |1.4.6+1.21-b53|Manifest: NOSIGNATURE
sky-aesthetics-1.2.5-neoforge.jar |Sky Aesthetics|sky_aesthetics|1.2.5 |Manifest: NOSIGNATURE
SmartBrainLib-neoforge-1.21.1-1.16.1.jar|SmartBrainLib |smartbrainlib |1.16.1|Manifest: NOSIGNATURE
sodium-neoforge-0.6.0-beta.4+mc1.21.1.jar |Sodium|sodium|0.6.0-beta.4+mc1.21.|Manifest: NOSIGNATURE
SolarGeneration-1.21-7.0.0.jar|SolarGeneration |solargeneration |7.0.0 |Manifest: NOSIGNATURE
sophisticatedbackpacks-1.21-3.20.19.1124.jar|Sophisticated Backpacks |sophisticatedbackpacks|3.20.19 |Manifest: NOSIGNATURE
sophisticatedcore-1.21-0.6.47.728.jar |Sophisticated Core|sophisticatedcore |0.6.47|Manifest: NOSIGNATURE
sophisticatedstorage-1.21-0.10.49.932.jar |Sophisticated Storage |sophisticatedstorage|0.10.49 |Manifest: NOSIGNATURE
spark-1.10.109-neoforge.jar |spark |spark |1.10.109|Manifest: NOSIGNATURE
spectrelib-neoforge-0.17.2+1.21.jar |SpectreLib|spectrelib|0.17.2+1.21 |Manifest: NOSIGNATURE
Statues-1.21.1-0.4.12.jar |Statues Mod |statues |0.4.12|Manifest: NOSIGNATURE
stellaris-1.21-neoforge-1.2.0-beta1.jar |Stellaris |stellaris |1.2.0-beta1 |Manifest: NOSIGNATURE
stevescarts-1.21-1.2.11-neoforge.jar|StevesCarts2|stevescarts |1.2.11|Manifest: NOSIGNATURE
StructureCompass-1.21.1-4.0.1.jar |Structure Compass Mod |structurecompass|4.0.1 |Manifest: NOSIGNATURE
structureessentials-1.21-3.4.jar|Structure Essentials mod|structureessentials |3.4 |Manifest: NOSIGNATURE
structure-expansion-neoforge-87.0.0.jar |Structure Expansion |structureexpansion|87.0.0|Manifest: NOSIGNATURE
structurize-1.0.754-1.21.1-snapshot.jar |Structurize |structurize |1.0.754-1.21.1-snaps|Manifest: NOSIGNATURE
Super Factory Manager-1.21.1-4.19.0.jar |Super Factory Manager |sfm |4.19.0|Manifest: NOSIGNATURE
supermartijn642configlib-1.1.8-neoforge-mc1.21.jar|SuperMartijn642's Config Libra|supermartijn642configlib|1.1.8 |Manifest: NOSIGNATURE
supermartijn642corelib-1.1.17i-neoforge-mc1.21.jar|SuperMartijn642's Core Lib|supermartijn642corelib|1.1.17+i|Manifest: NOSIGNATURE
sushigocrafting-1.21-0.6.3.jar|Sushi Go Crafting |sushigocrafting |0.6.3 |Manifest: NOSIGNATURE
twilightforest-1.21.1-4.6.2790-universal.jar|The Twilight Forest |twilightforest|4.6.2790|Manifest: NOSIGNATURE
theurgy-1.21.1-neoforge-1.58.0.jar|Theurgy |theurgy |1.58.0|Manifest: NOSIGNATURE
theurgy_kubejs-1.21.1-neoforge-1.4.0.jar|Theurgy KubeJS|theurgy_kubejs|1.4.0 |Manifest: NOSIGNATURE
titanium-1.21-4.0.27.jar|Titanium|titanium|4.0.27|Manifest: NOSIGNATURE
ToastControl-1.21-9.0.0.jar |Toast Control |toastcontrol|9.0.0 |Manifest: NOSIGNATURE
toms-peripherals-1.21-1.3.0.jar |Tom's Peripherals |toms_peripherals|1.3.0 |Manifest: NOSIGNATURE
ToolKit-neoforge-87.0.1.jar |Toolkit |toolkit |87.0.1|Manifest: NOSIGNATURE
torchmaster-neoforge-1.21.1-21.1.5-beta.jar |Torchmaster |torchmaster |21.1.5-beta |Manifest: NOSIGNATURE
towntalk-1.2.0.jar|Towntalk|towntalk|1.2.0 |Manifest: NOSIGNATURE
trashcans-1.0.18b-neoforge-mc1.21.jar |Trash Cans|trashcans |1.0.18+b|Manifest: NOSIGNATURE
treetap-1.21.1-0.4.2.jar|Tree Tap|treetap |1.21.1-0.4.2|Manifest: NOSIGNATURE
trenzalore-neo-6.1.1+mc1.21.1.jar |Trenzalore|trenzalore|6.1.1 |Manifest: NOSIGNATURE
blockui-1.0.192-1.21.1-snapshot.jar |UI Library Mod|blockui |1.0.192-1.21.1-snaps|Manifest: NOSIGNATURE
UsefulSlime-neoforge-1.21-1.11.0.jar|UsefulSlime |usefulslime |1.11.0|Manifest: NOSIGNATURE
utilitarian-1.21.1-0.13.4.jar |Utilitarian |utilitarian |1.21.1-0.13.4 |Manifest: NOSIGNATURE
variantsandventures-neoforge-mc1.21.1-1.0.6.jar |Variants & Ventures |variantsandventures |1.0.6 |Manifest: NOSIGNATURE
villagespawnpoint-1.21.1-4.4.jar|Village Spawn Point |villagespawnpoint |4.4 |Manifest: NOSIGNATURE
waystones-neoforge-1.21.1-21.1.5.jar|Waystones |waystones |21.1.5|Manifest: NOSIGNATURE
watut-neoforge-1.21.0-1.1.4.jar |What Are They Up To |watut |1.21.0-1.1.4|Manifest: NOSIGNATURE
DungeonsArise-1.21.x-2.1.60-release.jar |When Dungeons Arise |dungeons_arise|2.1.60|Manifest: NOSIGNATURE
DungeonsAriseSevenSeas-1.21.x-1.0.3.2-neoforge.jar|When Dungeons Arise: Seven Sea|dungeons_arise_seven_seas |1.0.3.2 |Manifest: NOSIGNATURE
WitherSkeletonTweaks-1.21.1-10.0.2.jar|Wither Skeleton Tweaks|wstweaks|10.0.2|Manifest: NOSIGNATURE
wits-1.3.0+1.21-neoforge.jar|WITS|wits|1.3.0+1.21-neoforge |Manifest: NOSIGNATURE
xnet-1.21-7.0.2.jar |XNet|xnet|1.21-7.0.2|Manifest: NOSIGNATURE
xptome-1.21.1-2.4.jar |XP Tome |xpbook|2.4 |Manifest: NOSIGNATURE
xycraft_core-0.7.45-all.jar |XyCraft Core|xycraft_core|0.7.45|Manifest: NOSIGNATURE
xycraft_machines-0.7.45.jar |XyCraft Machines|xycraft_machines|0.7.45|Manifest: NOSIGNATURE
xycraft_override-0.7.45.jar |XyCraft Override|xycraft_override|0.7.45|Manifest: NOSIGNATURE
xycraft_world-0.7.45.jar|XyCraft World |xycraft_world |0.7.45|Manifest: NOSIGNATURE
yeetusexperimentus-neoforge-87.0.0.jar|Yeetus Experimentus |yeetusexperimentus|87.0.0|Manifest: NOSIGNATURE
YungsApi-1.21.1-NeoForge-5.1.2.jar|YUNG's API|yungsapi|1.21.1-NeoForge-5.1.|Manifest: NOSIGNATURE
YungsBetterDesertTemples-1.21.1-NeoForge-4.1.2.jar|YUNG's Better Desert Temples|betterdeserttemples |1.21.1-NeoForge-4.1.|Manifest: NOSIGNATURE
YungsBetterDungeons-1.21.1-NeoForge-5.1.2.jar |YUNG's Better Dungeons|betterdungeons|1.21.1-NeoForge-5.1.|Manifest: NOSIGNATURE
YungsBetterEndIsland-1.21.1-NeoForge-3.1.1.jar|YUNG's Better End Island|betterendisland |1.21.1-NeoForge-3.1.|Manifest: NOSIGNATURE
YungsBetterJungleTemples-1.21.1-NeoForge-3.1.1.jar|YUNG's Better Jungle Temples|betterjungletemples |1.21.1-NeoForge-3.1.|Manifest: NOSIGNATURE
YungsBetterMineshafts-1.21.1-NeoForge-5.1.1.jar |YUNG's Better Mineshafts|bettermineshafts|1.21.1-NeoForge-5.1.|Manifest: NOSIGNATURE
YungsBetterStrongholds-1.21.1-NeoForge-5.1.2.jar|YUNG's Better Strongholds |betterstrongholds |1.21.1-NeoForge-5.1.|Manifest: NOSIGNATURE
YungsBetterWitchHuts-1.21.1-NeoForge-4.1.1.jar|YUNG's Better Witch Huts|betterwitchhuts |1.21.1-NeoForge-4.1.|Manifest: NOSIGNATURE
YungsBridges-1.21.1-NeoForge-5.1.1.jar|YUNG's Bridges|yungsbridges|1.21.1-NeoForge-5.1.|Manifest: NOSIGNATURE
ZeroCore2-1.21.1-2.4.13.jar |Zero CORE 2 |zerocore|1.21.1-2.4.13 |Manifest: NOSIGNATURE

### Current Behavior

Discoverd the following problem:
when opening a Rack in a pre update placed Rack, items disappear when placed in Rack.

when placing a new Rack items placed in Rack reappear in hand after closing rack and reopening it.

game crashes when building Supply Camp Fortress in Fortress Style.

### Expected Behavior

not to dupe items.

not to crash.

### Reproduction Steps

for crash:
- start new world
- get suppy camp.
- crash

for dupe:
- place Rack
- access Rack
- move item in rack
- close intentory
- access rack
- profits

### Logs

https://gist.github.com/satakrion/18ad9d124ea5d262962bd24e40351849

### Anything else?

gist for crashing:
https://gist.github.com/satakrion/f63042f141a6919a8e377eed2e9612c4

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by jpenilla**
Fixes #10417
Fixes #10418
Fixes https://github.com/Tuinity/Moonrise/issues/69

# Changes proposed in this pull request
Adjusts chunk loaded check and chunk cache for compatibility with the Moonrise chunk system.
The new calls have equivalent functionality and will work with the Vanilla chunk system and Moonrise's.
I tested founding a colony in a fresh world as well as founding a second colony (abandoning the first one) with and without Moonrise.

## Testing
- [X] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/api/util/WorldUtil.java [hunk 1]
```diff
@@ -67,7 +68,7 @@ public static boolean isChunkLoaded(final LevelAccessor world, final int x, fina
             final ChunkHolder holder = ((ServerChunkCache) world.getChunkSource()).chunkMap.getVisibleChunkIfPresent(ChunkPos.asLong(x, z));
             if (holder != null)
             {
-                return holder.getFullChunkFuture().getNow(ChunkHolder.UNLOADED_LEVEL_CHUNK).isSuccess();
+                return holder.getFullStatus().isOrAfter(FullChunkStatus.FULL);
```
Comment (someaddons) [inline src/main/java/com/minecolonies/api/util/WorldUtil.java]: This actually just tells us if it will be loaded eventually, not if it does exist right now. Why not use the "holder.getChunkIfPresent" check for both?

Comment (jpenilla) [reply src/main/java/com/minecolonies/api/util/WorldUtil.java]: Not sure how I missed that, but getChunkIfPresent will work here. Thanks for the review, PR is updated.

Comment (jpenilla) [reply src/main/java/com/minecolonies/api/util/WorldUtil.java]: After talking with @Spottedleaf we determined that both the full status and getChunkIfPresent should be used due to some implementation details of the Moonrise chunk system, for vanilla it is redundant but doesn't hurt anything.
For ChunkCache, getChunkIfPresent is fine on its own as entity ticking is already checked which means we already know the full status will be FULL or after.

Changing this behavior to closer align with vanilla is something I'm interested in but not sure about a timeline for. If/when we make that change the code in this PR would still be valid, as it is for vanilla.

**Review by someaddons — APPROVED** [review]
