### PR TITLE
Several small fixes

### LINKED ISSUE #727: [Suggestion] Assign Builder at build request
Pretty simply, when using the build scepter, a GUI opens up and allows assigning a specific builder for that job, if having more than one builder. Gets a bit frustrating when a builder picks up a job from way over on the other side of the colony. That, or have an algorithm that has the builder start with the closest job and work their way out ... I suppose.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/43374536-suggestion-assign-builder-at-build-request?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #1193: [enhancement] be able to control the permissions/protections
I would like to be able to control all of the things manually that the townhall block manipulates with its protection powers.

I have noticed that hostile mobs don't spawn inside the protected area, they'll come in to it, but they won't spawn into it. Even with no torches. If you need to kill them, you have to travel to the edge of the zone of protection and there they are all clumped together. Apparently, they hide the beer and cigarettes when you show up.

This is also true of the passive mobs.

The only cases where it is not true is when a mod adds mobs that don't inherit from the vanilla mobs, those mobs will spawn inside the town borders easily and often. For instance, the roots mods, which adds baby deer (bambi), has no issue spawning inside the town border. Animania however apparently inherits the vanilla mobs as its mobs like the ones mentioned above congregate or rather aggregate at the town border.

Additionally, when people are traveling through your town and they become hungry, they can not eat because of the protection. They also can't attack hostile mobs that are hunting them down for their human skins to make demonic drums from.

So a full permission system either in a config or accessible via the townhall block that allows us to toggle each of the things that the protection covers.

Back to mob spawn, I built a dark tower in my town, also known as a mob dropper, it never drops mobs and very extremely rarely spawns mobs. When they do spawn they never enter the chute but despawn instead. I think it has something to do with the permissions/protection.

This might be a bug report, but I see it more of as a chance to make enhancements that solve it.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #1193
Closes #727

# Changes proposed in this pull request:
- Fixes problems with several dman trying to deliver at the same time.
- Fixes problems with food not being delivered correctly
- Allows players to eat food in colonies and defend themselves against mobs
- Assigns smartly the closest possible builder to the workorder

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 1]
```diff
@@ -962,6 +962,28 @@ public void setNeedsTool(final IToolType neededTool, final int minimalLevel)
...
 
+    @Override
+    public boolean equals(final Object o)
+    {
+        if(!(o instanceof AbstractBuilding))
+        {
+            return false;
+        }
+
+        if(((AbstractBuilding) o).getID().equals(this.getID()))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java]: MINOR Replace this if-then-else statement by a single return statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1126)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 66 issues
* ![MAJOR][MAJOR] 33 major
* ![MINOR][MINOR] 33 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 35 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): class "AbstractBuilding" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L122](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L122): Remove this reference to "BuildingBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L124](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L124): Remove this reference to "BuildingFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/colony/workorders/WorkOrderBuildDecoration.java [hunk 2]
```diff
@@ -182,47 +182,57 @@ public void attemptToFulfill(@NotNull final Colony colony)
...
      * This rule does "Unused method parameters should be removed"
      * But in this case extending class may need to use the sendMessage parameter
-     * @param colony which the work order belong to
-     * @param hasBuilder true if we have a builder for this work order
+     *
+     * @param colony      which the work order belong to
+     * @param hasBuilder  true if we have a builder for this work order
      * @param sendMessage true if we need to send the message
      */
     @SuppressWarnings("squid:S1172")
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/workorders/WorkOrderBuildDecoration.java:216]: INFO Suppressing the 'squid:S1172' warning is not allowed [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1309)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 68 issues
* ![MAJOR][MAJOR] 33 major
* ![MINOR][MINOR] 32 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 35 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): class "AbstractBuilding" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L122](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L122): Remove this reference to "BuildingBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L124](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L124): Remove this reference to "BuildingFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 69 issues
* ![MAJOR][MAJOR] 34 major
* ![MINOR][MINOR] 32 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 35 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): class "AbstractBuilding" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L122](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L122): Remove this reference to "BuildingBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L124](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L124): Remove this reference to "BuildingFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 3]
```diff
@@ -962,6 +962,18 @@ public void setNeedsTool(final IToolType neededTool, final int minimalLevel)
         this.needsToolLevel = minimalLevel;
     }
 
+    @Override
+    public boolean equals(final Object o)
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java:966]: 👍

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java [hunk 4]
```diff
@@ -962,6 +962,18 @@ public void setNeedsTool(final IToolType neededTool, final int minimalLevel)
...
+    {
+        return o instanceof AbstractBuilding && ((AbstractBuilding) o).getID().equals(this.getID());
+    }
+
+    @Override
+    public int hashCode()
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java:972]: 👍

File: src/main/java/com/minecolonies/coremod/colony/buildings/BuildingHome.java [hunk 5]
```diff
@@ -237,6 +238,23 @@ public boolean hasResident(final CitizenData citizen)
     }
 
     /**
+     * Checks if food in the home is required.
+     * If yes set foodNeeded to true, else to false.
+     */
+    public void checkIfFoodNeeded()
+    {
+        boolean needFood = false;
+        for(final CitizenData resident: residents)
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/colony/buildings/BuildingHome.java]: This can simply be done by a lamda (with findFirst and filter)
Would make this Code footprint a lot smaller and the JVM can optimize it better.

**Review by marchermans — CHANGES_REQUESTED** [review]
Change the for-loop to a lamda and we are good to go.

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 69 issues
* ![MAJOR][MAJOR] 34 major
* ![MINOR][MINOR] 32 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 35 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): class "AbstractBuilding" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L122](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L122): Remove this reference to "BuildingBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L124](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L124): Remove this reference to "BuildingFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 69 issues
* ![MAJOR][MAJOR] 34 major
* ![MINOR][MINOR] 32 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 35 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): class "AbstractBuilding" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L122](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L122): Remove this reference to "BuildingBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L124](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L124): Remove this reference to "BuildingFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by marvin-bitterlich** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1194/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Review by marchermans — APPROVED** [review]
