### PR TITLE
Bugfix/#758 concurrency issue

### LINKED ISSUE #758: Crash : PM Description: Ticking block entity  java.util.ConcurrentModificationException [$5 awarded]
### Minecolonies version

version minecolonies-universal-1.10.2-0.6.3317 or curse 

### Expected behavior

- XXX

### Actual behaviour

- YYY

### Steps to reproduce the problem

I came back from nether and this happens. It corrupt the world (every try to reload the save gives this very same crash.) I had to edit the world with MCEdit and delete the warehouse entity, and then I was able to load the world (now I have a citizen asking for a warehouse to work with :-)

By the way, what is this delivery man going to do? as of now seems not doing anything apart to see the floor everywhere looking for something...

1. XYZ
2. ZYX
3. ...
4. Profit

<bountysource-plugin>

---
The **[$5 bounty](https://www.bountysource.com/issues/43762553-crash-pm-description-ticking-block-entity-java-util-concurrentmodificationexception?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github)** on this issue has been claimed at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #993: Warehouse Ticking Block Entity Crash
### Minecolonies version

minecolonies-universal-1.11.2-0.8.1010

---- Minecraft Crash Report ----

WARNING: coremods are present:
  NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.2.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  ForgelinPlugin (Forgelin-1.4.2.jar)
  AstralCore (astralsorcery-1.4.0.jar)
  llibrary (llibrary-1.7.6-1.11.2.jar)
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
  RebornCoreASM (RebornCore-1.11.2-2.14.2.94-universal.jar)
  IvToolkit (IvToolkit-1.3.3.jar)
  SFRCore (SolarFluxReborn_1.11.2-2.15r.jar)
  BookshelfLoadingPlugin (Bookshelf-1.11.2-1.5.0.371.jar)
  LoadingPlugin (HardcoreDarkness-MC1.11.2-1.9.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.88.jar)
  HammerCoreCore (HammerCore_1.11.2-1.6.0.jar)
  literalascension (literalascension-1.11.2-1.0.2.2.jar)
  LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  LoadingPlugin (Quark-r1.2-91.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 5/14/17 5:08 PM
Description: Ticking block entity

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at java.util.Collections$UnmodifiableCollection$1.next(Unknown Source)
	at com.minecolonies.coremod.tileentities.TileEntityWareHouse.checkInWareHouse(TileEntityWareHouse.java:158)
	at com.minecolonies.coremod.tileentities.TileEntityWareHouse.func_73660_a(TileEntityWareHouse.java:98)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1784)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at java.util.Collections$UnmodifiableCollection$1.next(Unknown Source)
	at com.minecolonies.coremod.tileentities.TileEntityWareHouse.checkInWareHouse(TileEntityWareHouse.java:158)
	at com.minecolonies.coremod.tileentities.TileEntityWareHouse.func_73660_a(TileEntityWareHouse.java:98)

-- Block entity being ticked --
Details:
	Name: minecraft:minecolonies.warehouse // com.minecolonies.coremod.tileentities.TileEntityWareHouse
	Block type: ID #2759 (tile.minecolonies.blockHutWareHouse // com.minecolonies.coremod.blocks.BlockHutWareHouse)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (34,69,478), Chunk: (at 2,4,14 in 2,29; contains blocks 32,0,464 to 47,255,479), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #2759 (tile.minecolonies.blockHutWareHouse // com.minecolonies.coremod.blocks.BlockHutWareHouse)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1802)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Xaal'/215, l='MpServer', x=-13.64, y=70.00, z=487.78]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (178,64,266), Chunk: (at 2,4,10 in 11,16; contains blocks 176,0,256 to 191,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 497181 game time, 798091 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 126 total; [EntityCreeper['Creeper'/13825, l='MpServer', x=-65.50, y=13.00, z=510.50], EntityWitch['Witch'/13826, l='MpServer', x=-65.50, y=13.00, z=510.50], EntityZombie['Zombie'/13830, l='MpServer', x=-41.46, y=38.54, z=418.60], EntityBat['Bat'/12557, l='MpServer', x=54.53, y=49.95, z=534.53], EntitySkeleton['Skeleton'/13839, l='MpServer', x=-20.50, y=34.00, z=545.50], EntitySkeleton['Skeleton'/13840, l='MpServer', x=-15.50, y=34.00, z=542.50], EntitySkeleton['Skeleton'/13073, l='MpServer', x=55.50, y=49.00, z=536.50], EntityCreeper['Creeper'/13587, l='MpServer', x=-17.57, y=45.00, z=438.80], EntityZombie['Zombie'/10261, l='MpServer', x=-29.52, y=45.00, z=556.72], EntityZombie['Zombie'/13077, l='MpServer', x=-11.50, y=47.00, z=444.50], EntityItem['item.item.egg'/13845, l='MpServer', x=8.54, y=71.00, z=549.30], EntityCow['Cow'/278, l='MpServer', x=-60.50, y=72.00, z=434.50], EntityChicken['Chicken'/279, l='MpServer', x=-62.62, y=70.00, z=437.77], EntityBat['Bat'/12568, l='MpServer', x=14.75, y=62.10, z=548.25], EntityCreeper['Creeper'/13336, l='MpServer', x=21.50, y=58.00, z=550.50], EntityItem['item.tile.sapling.oak'/13592, l='MpServer', x=-37.42, y=70.00, z=532.46], EntityCreeper['Creeper'/13337, l='MpServer', x=23.50, y=58.00, z=549.50], EntityItem['item.tile.sapling.oak'/13594, l='MpServer', x=-30.30, y=69.00, z=530.88], EntityZombie['Zombie'/13339, l='MpServer', x=23.50, y=58.00, z=549.50], EntityItem['item.tile.sapling.oak'/13596, l='MpServer', x=-33.72, y=69.00, z=530.01], EntityItem['item.tile.sapling.oak'/13598, l='MpServer', x=-33.36, y=69.00, z=531.87], EntityBat['Bat'/11808, l='MpServer', x=17.27, y=64.10, z=545.75], EntityItem['item.tile.sapling.oak'/13601, l='MpServer', x=-31.55, y=69.00, z=531.91], EntityZombie['Zombie'/12066, l='MpServer', x=17.50, y=34.00, z=492.50], EntityAncientGolem['Ancient Golem'/12323, l='MpServer', x=9.50, y=59.00, z=522.50], EntityItem['item.tile.sapling.oak'/13091, l='MpServer', x=-37.26, y=79.00, z=526.13], EntityChicken['Chicken'/292, l='MpServer', x=-72.21, y=72.00, z=467.49], EntityAncientGolem['Ancient Golem'/12324, l='MpServer', x=4.50, y=59.00, z=525.50], EntityItem['item.item.apple'/13093, l='MpServer', x=-35.39, y=70.00, z=528.54], EntitySkeleton['Skeleton'/12326, l='MpServer', x=9.50, y=59.00, z=523.50], EntityZombie['Zombie'/13862, l='MpServer', x=-81.50, y=37.00, z=482.50], EntityItem['item.tile.sapling.oak'/13095, l='MpServer', x=-33.32, y=69.00, z=525.13], EntityItem['item.tile.sapling.oak'/13607, l='MpServer', x=-35.81, y=70.00, z=535.40], EntityItem['item.item.apple'/13097, l='MpServer', x=-30.30, y=69.00, z=531.13], EntityItem['item.tile.sapling.oak'/13354, l='MpServer', x=-31.17, y=69.00, z=530.01], EntitySquid['Squid'/299, l='MpServer', x=-21.67, y=57.08, z=507.39], EntitySquid['Squid'/300, l='MpServer', x=-17.12, y=57.43, z=510.70], EntitySquid['Squid'/301, l='MpServer', x=-21.30, y=57.48, z=512.16], EntityItem['item.tile.sapling.oak'/13101, l='MpServer', x=-36.76, y=78.00, z=527.86], EntitySkeleton['Skeleton'/302, l='MpServer', x=-20.39, y=57.24, z=513.70], EntityAshen['Ashen'/12846, l='MpServer', x=53.50, y=14.00, z=481.50], EntitySquid['Squid'/303, l='MpServer', x=-21.67, y=57.00, z=509.14], EntityItem['item.tile.sapling.oak'/13103, l='MpServer', x=-33.78, y=69.00, z=525.99], EntitySquid['Squid'/304, l='MpServer', x=-15.40, y=56.73, z=511.41], EntitySquid['Squid'/305, l='MpServer', x=-19.90, y=56.00, z=505.39], EntityItem['item.tile.sapling.oak'/13105, l='MpServer', x=-35.10, y=80.00, z=526.88], EntitySquid['Squid'/306, l='MpServer', x=-18.70, y=56.50, z=511.60], EntityCreeper['Creeper'/10546, l='MpServer', x=-91.50, y=27.00, z=505.50], EntityItem['item.tile.sapling.oak'/13106, l='MpServer', x=-35.13, y=70.00, z=528.92], EntityCreeper['Creeper'/12083, l='MpServer', x=-26.50, y=34.00, z=561.50], EntitySquid['Squid'/313, l='MpServer', x=-18.63, y=56.07, z=510.84], EntityItem['item.item.egg'/11577, l='MpServer', x=-72.66, y=72.00, z=467.82], EntitySkeleton['Skeleton'/10809, l='MpServer', x=52.50, y=46.00, z=458.50], EntityCitizen['Adalyn C. Williams'/314, l='MpServer', x=2.92, y=69.00, z=491.91], EntityBat['Bat'/13115, l='MpServer', x=61.49, y=23.04, z=486.45], EntityZombie['Zombie'/12605, l='MpServer', x=0.49, y=37.00, z=532.18], EntityZombie['Zombie'/13629, l='MpServer', x=-89.50, y=33.00, z=549.50], EntitySpider['Spider'/13630, l='MpServer', x=-89.91, y=33.00, z=554.84], EntityCitizen['Cyrille A. Barber'/319, l='MpServer', x=2.50, y=69.00, z=511.34], EntityCitizen['Abigail M. Alicock'/11839, l='MpServer', x=-5.47, y=70.00, z=490.42], EntityDeer['Deer'/320, l='MpServer', x=-65.84, y=69.36, z=551.39], EntityItem['item.tile.sapling.oak'/13122, l='MpServer', x=-37.15, y=70.00, z=529.88], EntityBat['Bat'/9288, l='MpServer', x=-2.24, y=52.41, z=518.36], EntityCitizen['Cecily A. Barnes'/329, l='MpServer', x=19.51, y=69.00, z=514.42], EntityChicken['Chicken'/332, l='MpServer', x=8.14, y=71.00, z=550.21], EntityItem['item.tile.sapling.oak'/13137, l='MpServer', x=-41.15, y=70.00, z=528.13], EntityZombie['Zombie'/11860, l='MpServer', x=20.91, y=36.00, z=495.47], EntityBat['Bat'/13908, l='MpServer', x=34.05, y=44.82, z=413.17], EntityBat['Bat'/13910, l='MpServer', x=34.73, y=44.00, z=414.53], EntityChicken['Chicken'/87, l='MpServer', x=-6.58, y=69.00, z=453.48], EntityItem['item.item.egg'/7516, l='MpServer', x=-6.64, y=69.00, z=452.97], EntityBat['Bat'/12125, l='MpServer', x=-13.84, y=27.05, z=561.25], EntitySkeleton['Skeleton'/12642, l='MpServer', x=-83.70, y=28.00, z=439.85], EntityDeer['Deer'/98, l='MpServer', x=3.17, y=73.00, z=435.34], EntitySkeleton['Skeleton'/12643, l='MpServer', x=-83.11, y=28.00, z=439.17], EntityDeer['Deer'/99, l='MpServer', x=11.86, y=71.00, z=432.93], EntityCitizen['Charity E. Hakebourne'/357, l='MpServer', x=-15.54, y=69.00, z=523.51], EntityItem['item.tile.sapling.oak'/13157, l='MpServer', x=-37.63, y=70.00, z=530.99], EntityZombie['Zombie'/13415, l='MpServer', x=-86.27, y=21.00, z=442.50], EntityCitizen['Josiah I. Gifford'/364, l='MpServer', x=-33.31, y=69.00, z=522.24], EntitySpider['Spider'/13932, l='MpServer', x=-15.50, y=34.00, z=543.50], EntitySpider['Spider'/13933, l='MpServer', x=-15.50, y=34.00, z=541.50], EntityPlayerSP['Xaal'/215, l='MpServer', x=-13.64, y=70.00, z=487.78], EntityItem['item.tile.sapling.oak'/12920, l='MpServer', x=-34.88, y=70.00, z=532.13], EntityZombie['Zombie'/13689, l='MpServer', x=63.50, y=38.00, z=525.50], EntityItem['item.tile.sapling.oak'/12922, l='MpServer', x=-38.38, y=70.00, z=531.56], EntityCreeper['Creeper'/13179, l='MpServer', x=55.50, y=15.00, z=479.50], EntityItem['item.tile.sapling.oak'/12924, l='MpServer', x=-38.56, y=70.00, z=533.67], EntityAncientGolem['Ancient Golem'/11389, l='MpServer', x=32.50, y=35.00, z=426.50], EntityZombie['Zombie'/13693, l='MpServer', x=-78.50, y=14.00, z=411.50], EntityZombie['Zombie'/13694, l='MpServer', x=-78.50, y=14.00, z=409.50], EntityCreeper['Creeper'/13695, l='MpServer', x=-81.50, y=14.00, z=412.50], EntityCreeper['Creeper'/13696, l='MpServer', x=-80.50, y=14.00, z=408.50], EntityZombie['Zombie'/3974, l='MpServer', x=-3.83, y=51.00, z=518.69], EntitySkeleton['Skeleton'/13703, l='MpServer', x=-86.50, y=20.00, z=438.50], EntitySkeleton['Skeleton'/13704, l='MpServer', x=-88.50, y=20.00, z=440.50], EntitySkeleton['Skeleton'/13705, l='MpServer', x=-88.50, y=20.00, z=439.50], EntitySkeleton['Skeleton'/12947, l='MpServer', x=-20.50, y=11.00, z=501.50], EntitySkeleton['Skeleton'/12948, l='MpServer', x=-19.50, y=11.00, z=501.50], EntityBat['Bat'/12450, l='MpServer', x=-81.25, y=26.82, z=485.44], EntityZombie['Zombie'/13225, l='MpServer', x=-74.50, y=18.00, z=523.50], EntitySkeleton['Skeleton'/8624, l='MpServer', x=-0.73, y=52.00, z=520.50], EntityItem['item.item.feather'/11189, l='MpServer', x=-7.67, y=68.00, z=452.23], EntityBat['Bat'/13751, l='MpServer', x=23.25, y=36.99, z=489.54], EntityItem['item.tile.sapling.oak'/13248, l='MpServer', x=-35.49, y=70.00, z=530.88], EntitySkeleton['Skeleton'/12994, l='MpServer', x=-6.47, y=49.00, z=512.73], EntityItem['item.tile.sapling.oak'/13000, l='MpServer', x=-38.23, y=84.00, z=524.15], EntityItem['item.tile.sapling.oak'/13002, l='MpServer', x=-30.91, y=78.00, z=524.32], EntitySquid['Squid'/216, l='MpServer', x=-21.73, y=56.56, z=506.27], EntityItem['item.tile.sapling.oak'/13528, l='MpServer', x=-43.19, y=70.00, z=529.37], EntitySkeleton['Skeleton'/13273, l='MpServer', x=-19.50, y=42.00, z=413.50], EntityCreeper['Creeper'/223, l='MpServer', x=-0.41, y=52.00, z=504.19], EntityZombie['Zombie'/12513, l='MpServer', x=-54.50, y=41.00, z=523.50], EntitySkeleton['Skeleton'/12516, l='MpServer', x=-44.50, y=23.00, z=417.50], EntityCow['Cow'/232, l='MpServer', x=-69.66, y=72.00, z=422.20], EntityBat['Bat'/13800, l='MpServer', x=-41.68, y=25.54, z=481.83], EntityChicken['Chicken'/234, l='MpServer', x=-82.17, y=75.00, z=446.26], EntityChicken['Chicken'/235, l='MpServer', x=-82.56, y=73.00, z=440.48], EntityChicken['Chicken'/236, l='MpServer', x=-92.49, y=70.00, z=434.20], EntityItem['item.tile.sapling.oak'/13806, l='MpServer', x=-36.88, y=70.00, z=531.20], EntityChicken['Chicken'/243, l='MpServer', x=-89.50, y=75.00, z=458.57], EntityChicken['Chicken'/244, l='MpServer', x=-87.22, y=76.00, z=452.53], EntityCreeper['Creeper'/12277, l='MpServer', x=-75.50, y=21.00, z=436.50], EntityChicken['Chicken'/249, l='MpServer', x=-76.55, y=75.00, z=445.65], EntityCow['Cow'/250, l='MpServer', x=-74.53, y=72.00, z=431.84], EntityEnderman['Enderman'/13308, l='MpServer', x=3.50, y=58.00, z=512.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3364396480 bytes (3208 MB) / 7946633216 bytes (7578 MB) up to 7946633216 bytes (7578 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms6144m -Xmx8192m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2296 115 mods loaded, 115 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2296-universal.jar) 
	UCHIJAAAA	forge{13.20.0.2296} [Minecraft Forge] (forge-1.11.2-13.20.0.2296-universal.jar) 
	UCHIJAAAA	ivtoolkit{1.3.3} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHIJAAAA	jei{4.3.5.275} [Just Enough Items] (jei_1.11.2-4.3.5.275.jar) 
	UCHIJAAAA	abyssalcraft{1.9.4-pre-2} [AbyssalCraft] (AbyssalCraft-1.11.2-1.9.4-pre-2.jar) 
	UCHIJAAAA	actuallyadditions{1.11.2-r107} [Actually Additions] (ActuallyAdditions-1.11.2-r107.jar) 
	UCHIJAAAA	akashictome{1.1-7} [Akashic Tome] (AkashicTome-1.1-7.jar) 
	UCHIJAAAA	aquaculture{1.5.0} [Aquaculture] (Aquaculture-1.11.2-1.5.0.33.jar) 
	UCHIJAAAA	astralsorcery{1.4.0} [Astral Sorcery] (astralsorcery-1.4.0.jar) 
	UCHIJAAAA	morphtool{1.1-13} [Morph-o-Tool] (Morph-o-Tool-1.1-13.jar) 
	UCHIJAAAA	quark{r1.2-91} [Quark] (Quark-r1.2-91.jar) 
	UCHIJAAAA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJAAAA	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UCHIJAAAA	betterbedrockgen{6.0.1} [BetterBedrockGen] (BBG-6.0.1.jar) 
	UCHIJAAAA	bdlib{1.13.2.7} [BD Lib] (bdlib-1.13.2.7-mc1.11.2.jar) 
	UCHIJAAAA	betterachievements{0.4.3.12} [Better Achievements] (BetterAchievements-1.11.2-0.4.3.12.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.11-0.11.1.239+9162f74.jar) 
	UCHIJAAAA	biomesoplenty{6.1.0.2213} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.1.0.2213-universal.jar) 
	UCHIJAAAA	guideapi{1.11.2-2.1.1-52} [Guide-API] (Guide-API-1.11.2-2.1.1-52.jar) 
	UCHIJAAAA	bloodmagic{1.11-2.1.10-79} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.10-79.jar) 
	UCHIJAAAA	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.11-1.5.1.jar) 
	UCHIJAAAA	bookshelf{1.5.0.371} [Bookshelf] (Bookshelf-1.11.2-1.5.0.371.jar) 
	UCHIJAAAA	sonarcore{4.0.0} [SonarCore] (SonarCore-1.11.2-4.0.0.jar) 
	UCHIJAAAA	calculator{4.0.0} [Calculator] (Calculator-1.11.2-4.0.0.jar) 
	UCHIJAAAA	chameleon{1.11.2-3.1.0} [Chameleon] (Chameleon-1.11.2-3.1.0.jar) 
	UCHIJAAAA	codechickenlib{2.6.0.254} [CodeChicken Lib] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHIJAAAA	chickenchunks{2.3.0.63} [ChickenChunks] (ChickenChunks-1.11.2-2.3.0.63-universal.jar) 
	UCHIJAAAA	chisel{MC1.11.2-0.0.10.14} [Chisel] (Chisel-MC1.11.2-0.0.10.14.jar) 
	UCHIJAAAA	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	UCHIJAAAA	clienttweaks{2.1.2} [Client Tweaks] (ClientTweaks_1.11-2.1.2.jar) 
	UCHIJAAAA	cosmeticarmorreworked{1.11.2-v1a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.11.2-v1a.jar) 
	UCHIJAAAA	craftingtweaks{7.1.9} [Crafting Tweaks] (CraftingTweaks_1.11.2-7.1.9.jar) 
	UCHIJAAAA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.11.2-3.0.24.jar) 
	UCHIJAAAA	crafttweaker{3.0.24} [Crafttweaker] (CraftTweaker-1.11.2-3.0.24.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.11.2-3.0.24.jar) 
	UCHIJAAAA	darkutils{1.2.0.134} [Dark Utilities] (DarkUtilities-1.11.2-1.2.0.134.jar) 
	UCHIJAAAA	ptrmodellib{1.0.0} [ptrmodellib] (Decocraft-2.4.2_1.11.2.jar) 
	UCHIJAAAA	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.11.2.jar) 
	UCHIJAAAA	ding{1.0.1} [Ding] (Ding-1.11-1.0.1.jar) 
	UCHIJAAAA	storagedrawers{1.11.2-4.2.6} [Storage Drawers] (StorageDrawers-1.11.2-4.2.6.jar) 
	UCHIJAAAA	bitdrawers{0.41} [Drawers & Bits] (DrawersBits-1.11.2-0.41.jar) 
	UCHIJAAAA	dsurround{3.4.2.0} [§3Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.4.2.0.jar) 
	UCHIJAAAA	presets{3.4.2.0} [§3Presets!] (DynamicSurroundings-1.11.2-3.4.2.0.jar) 
	UCHIJAAAA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod-1.11.2-1.3.0.jar) 
	UCHIJAAAA	embers{0.212} [Embers] (embers-0.212.jar) 
	UCHIJAAAA	enderstorage{1.0} [EnderStorage] (EnderStorage-1.11.2-2.3.0.112-universal.jar) 
	UCHIJAAAA	shetiphiancore{3.4.4} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.4.jar) 
	UCHIJAAAA	endertanks{1.5.4} [EnderTanks] (endertanks-1.11.0-1.5.4.jar) 
	UCHIJAAAA	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.4.1.jar) 
	UCHIJAAAA	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIJAAAA	fluxnetworks{2.0.0} [FluxNetworks] (FluxNetworks-1.11.2-2.0.0.jar) 
	UCHIJAAAA	forestry{5.3.4.99} [Forestry] (forestry_1.11.2-5.3.4.99.jar) 
	UCHIJAAAA	forgelin{1.4.2} [Forgelin] (Forgelin-1.4.2.jar) 
	UCHIJAAAA	mcmultipart{2.0.0} [MCMultiPart] (MCMultiPart-2.0.0.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.1x-3.6.3.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.1x-3.6.3.jar) 
	UCHIJAAAA	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.11.2-alpha-0.0.1.jar) 
	UCHIJAAAA	gendustry{1.6.5.7} [GenDustry] (gendustry-1.6.5.7-mc1.11.2.jar) 
	UCHIJAAAA	hammercore{1.6.0} [Hammer Core] (HammerCore_1.11.2-1.6.0.jar) 
	UCHIJAAAA	hardcoredarkness{1.9} [Hardcore Darkness] (HardcoreDarkness-MC1.11.2-1.9.jar) 
	UCHIJAAAA	helpfixer{1.4+17} [HelpFixer] (HelpFixer-1.11-1.4+17.jar) 
	UCHIJAAAA	hopperducts{1.4.9} [Hopper Ducts] (hopperducts-mc1.11.2-1.4.9.jar) 
	UCHIJAAAA	inventorytweaks{1.62+beta.88.22444d0} [Inventory Tweaks] (InventoryTweaks-1.62+beta.88.jar) 
	UCHIJAAAA	ironchest{1.11.2-7.0.18.800} [Iron Chest] (ironchest-1.11.2-7.0.18.800.jar) 
	UCHIJAAAA	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.11.2.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJAAAA	je_calculation{1.11.2-2.6.4} [Just Enough Calculation] (JustEnoughCalculation-1.11.2-2.6.4.jar) 
	UCHIJAAAA	jeresources{0.6.3.5} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.3.5.jar) 
	UCHIJAAAA	llibrary{1.7.6} [LLibrary] (llibrary-1.7.6-1.11.2.jar) 
	UCHIJAAAA	literalascension{1.11.2-1.0.2.2} [Literal Ascension] (literalascension-1.11.2-1.0.2.2.jar) 
	UCHIJAAAA	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHIJAAAA	minecolonies{1.11.2-0.8.1010} [MineColonies] (minecolonies-universal-1.11.2-0.8.1010.jar) 
	UCHIJAAAA	moreoverlays{1.11} [MoreOverlays] (moreoverlays-1.11-mc1.11.2.jar) 
	UCHIJAAAA	morpheus{1.11.2-3.2.13} [Morpheus] (Morpheus-1.11.2-3.2.13.jar) 
	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.11.2.jar) 
	UCHIJAAAA	natura{1.11.2-4.2.0.13} [Natura] (natura-1.11.2-4.2.0.13.jar) 
	UCHIJAAAA	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.11-4.3.1.jar) 
	UCHIJAAAA	nmsot{1.2.0-mc1.11.2} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.0-mc1.11.2.jar) 
	UCHIJAAAA	recipehandler{0.8} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.8(1.11).jar) 
	UCHIJAAAA	samsocean{1.0.1} [Ocean Floor Classic] (OceanFloor-1.11-1.0.1.jar) 
	UCHIJAAAA	omlib{1.11.2-3.0.0-70} [OMLib] (omlib-1.11.2-3.0.0-70.jar) 
	UCHIJAAAA	openmodularturrets{1.10.2-3.0.0-124} [Open Modular Turrets] (openmodularturrets-1.10.2-3.0.0-124.jar) 
	UCHIJAAAA	oreexcavation{1.3.88} [OreExcavation] (OreExcavation-1.3.88.jar) 
	UCHIJAAAA	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2h.jar) 
	UCHIJAAAA	platforms{1.3.4} [Platforms] (platforms-1.11.0-1.3.4.jar) 
	UCHIJAAAA	pressure{1.3.1.5} [Pressure Pipes] (pressure-1.3.1.5-mc1.11.2.jar) 
	UCHIJAAAA	reborncore{2.14.2.94} [Reborn Core] (RebornCore-1.11.2-2.14.2.94-universal.jar) 
	UCHIJAAAA	quantumstorage{4.2.1} [QuantumStorage] (QuantumStorage-1.11.2-4.2.1.jar) 
	UCHIJAAAA	rangedpumps{0.4} [Ranged Pumps] (rangedpumps-0.4.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.14.2.94} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.14.2.94-universal.jar) 
	UCHIJAAAA	reccomplex{1.3.1} [Recurrent Complex] (RecurrentComplex-1.3.1.jar) 
	UCHIJAAAA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.11.2-1.7.4.jar) 
	UCHIJAAAA	refinedstorage{1.4.4} [Refined Storage] (refinedstorage-1.4.4.jar) 
	UCHIJAAAA	xreliquary{1.11.2-1.3.3.653} [Reliquary] (Reliquary-1.11.2-1.3.3.653.jar) 
	UCHIJAAAA	rftools{6.00} [RFTools] (rftools-1.1x-6.00.jar) 
	UCHIJAAAA	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55.jar) 
	UCHIJAAAA	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCHIJAAAA	roots{0.017} [Roots 2] (roots-2-0.017.jar) 
	UCHIJAAAA	ropebridge{2.0.5} [Rope Bridge] (ropebridge-1.11.2-2.0.5.jar) 
	UCHIJAAAA	solarfluxreborn{2.15r} [Solar Flux Reborn] (SolarFluxReborn_1.11.2-2.15r.jar) 
	UCHIJAAAA	soulshardstow{1.11-2.6.6-47} [Soul Shards - The Old Ways] (SoulShards-TOW-1.11-2.6.6-47.jar) 
	UCHIJAAAA	stevescarts{2.2.3.17} [Steve's Carts 2] (StevesCarts-1.11.2-2.2.3.17.jar) 
	UCHIJAAAA	tconstruct{1.11.2-2.7.0.12} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.12.jar) 
	UCHIJAAAA	beneath{1.2.0} [The Beneath] (The Beneath-1.11.2-1.2.0.jar) 
	UCHIJAAAA	tp{2.2.0-Hotfix} [Tiny Progressions] (tinyprogressions-1.11.2-2.2.0-Hotfix.jar) 
	UCHIJAAAA	tombmanygraves{1.11.2-3.0.7} [Tomb Many Graves] (TombManyGraves-1.11.2-3.0.7.jar) 
	UCHIJAAAA	totemic{1.11.2-0.8.6} [Totemic] (Totemic-1.11.2-0.8.6.jar) 
	UCHIJAAAA	vc{4.34.38} [ViesCraft] (ViesCraft-1.11.2-4.34.38.jar) 
	UCHIJAAAA	waila{1.7.1} [waila] (Waila-1.7.1_1.11.2.jar) 
	UCHIJAAAA	wawla{2.4.0.232} [What Are We Looking At] (Wawla-1.11.2-2.4.0.232.jar) 
	UCHIJAAAA	waystones{3.0.13} [Waystones] (Waystones_1.11.2-3.0.13.jar) 
	UCHIJAAAA	denseores{1.0} [denseores] (denseores-1.11-alpha-1.0.1.jar) 
	Loaded coremods (and transformers): 
NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.2.0.jar)
  org.blockartistry.DynSurround.asm.Transformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  shetiphian.core.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.4.2.jar)
  
AstralCore (astralsorcery-1.4.0.jar)
  
llibrary (llibrary-1.7.6-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
  team.chisel.common.asm.ChiselTransformer
RebornCoreASM (RebornCore-1.11.2-2.14.2.94-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
IvToolkit (IvToolkit-1.3.3.jar)
  
SFRCore (SolarFluxReborn_1.11.2-2.15r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
BookshelfLoadingPlugin (Bookshelf-1.11.2-1.5.0.371.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
LoadingPlugin (HardcoreDarkness-MC1.11.2-1.9.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.88.jar)
  invtweaks.forge.asm.ContainerTransformer
HammerCoreCore (HammerCore_1.11.2-1.6.0.jar)
  com.mrdimka.hammercore.asm.HammerCoreTransformer
literalascension (literalascension-1.11.2-1.0.2.2.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
LoadingPlugin (Quark-r1.2-91.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 960M/PCIe/SSE2'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* AbyssalCraftAPI (1.9.0) from AbyssalCraft-1.11.2-1.9.4-pre-2.jar
		* AbyssalCraftAPI|Biome (1.9.0) from AbyssalCraft-1.11.2-1.9.4-pre-2.jar
		* AbyssalCraftAPI|Block (1.9.0) from AbyssalCraft-1.11.2-1.9.4-pre-2.jar
		* AbyssalCraftAPI|Condition (1.9.0) from AbyssalCraft-1.11.2-1.9.4-pre-2.jar
		* AbyssalCraftAPI|Disruption (1.9.0) from AbyssalCraft-1.11.2-1.9.4-pre-2.jar
		* AbyssalCraftAPI|Energy (1.9.0) from AbyssalCraft-1.11.2-1.9.4-pre-2.jar
		* AbyssalCraftAPI|Entity (1.9.0) from AbyssalCraft-1.11.2-1.9.4-pre-2.jar
		* AbyssalCraftAPI|Event (1.9.0) from AbyssalCraft-1.11.2-1.9.4-pre-2.jar
		* AbyssalCraftAPI|Integration (1.9.0) from AbyssalCraft-1.11.2-1.9.4-pre-2.jar
		* AbyssalCraftAPI|Internal (1.9.0) from AbyssalCraft-1.11.2-1.9.4-pre-2.jar
		* AbyssalCraftAPI|Item (1.9.0) from AbyssalCraft-1.11.2-1.9.4-pre-2.jar
		* AbyssalCraftAPI|Necronomicon (1.9.0) from AbyssalCraft-1.11.2-1.9.4-pre-2.jar
		* AbyssalCraftAPI|Recipe (1.9.0) from AbyssalCraft-1.11.2-1.9.4-pre-2.jar
		* AbyssalCraftAPI|Ritual (1.9.0) from AbyssalCraft-1.11.2-1.9.4-pre-2.jar
		* AbyssalCraftAPI|Spell (1.9.0) from AbyssalCraft-1.11.2-1.9.4-pre-2.jar
		* actuallyadditionsapi (33) from ActuallyAdditions-1.11.2-r107.jar
		* Baubles|API (1.4.0.2) from Baubles-1.11-1.4.3.jar
		* BetterAchievements|API (0.4.3.12) from BetterAchievements-1.11.2-0.4.3.12.jar
		* bloodmagic|API (1.11-2.1.10-79) from BloodMagic-1.11-2.1.10-79.jar
		* BotaniaAPI (79) from AkashicTome-1.1-7.jar
		* calculatorapi (1.9.4 - 1.0) from Calculator-1.11.2-4.0.0.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.11.2-0.0.10.14.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.11.2-0.0.10.14.jar
		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-13.10.jar
		* CoFHAPI (1.8.9R1.2.0B1) from SolarFluxReborn_1.11.2-2.15r.jar
		* cofhapi (1.4.0) from extrautils2-1.11.2-1.4.1.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from SolarFluxReborn_1.11.2-2.15r.jar
		* cofhapi|energy (1.4.0) from extrautils2-1.11.2-1.4.1.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.11.jar
		* compatlayer (0.2.8) from compatlayer-1.11.2-0.2.8.jar
		* CraftingTweaks|API (4.1) from CraftingTweaks_1.11.2-7.1.9.jar
		* CSLib|API (0.3.0) from Decocraft-2.4.2_1.11.2.jar
		* fluxapi (1.0) from FluxNetworks-1.11.2-2.0.0.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|core (5.1.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|farming (2.2.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|food (1.1.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|world (2.1.0) from forestry_1.11.2-5.3.4.99.jar
		* funkylocomotion_api (2.0) from funky-locomotion-1.11.2-alpha-0.0.1.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.7-mc1.11.2.jar
		* Guide-API|API (2.0.0) from Guide-API-1.11.2-2.1.1-52.jar
		* jeresources|API (0.6.3.5) from JustEnoughResources-1.11.2-0.6.3.5.jar
		* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* JustEnoughItemsAPI (4.12.0) from jei_1.11.2-4.3.5.275.jar
		* mcjtylib_ng (2.3.11) from mcjtylib-1.1x-2.3.11.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.11.2.jar
		* pressureAPI (1.3.1.5) from pressure-1.3.1.5-mc1.11.2.jar
		* reborncoreAPI (2.14.2.94) from RebornCore-1.11.2-2.14.2.94-universal.jar
		* reborncoreAPI|Fuel (2.14.2.94) from RebornCore-1.11.2-2.14.2.94-universal.jar
		* reborncoreAPI|Power (2.14.2.94) from RebornCore-1.11.2-2.14.2.94-universal.jar
		* reborncoreAPI|Recipe (2.14.2.94) from RebornCore-1.11.2-2.14.2.94-universal.jar
		* reborncoreAPI|Tile (2.14.2.94) from RebornCore-1.11.2-2.14.2.94-universal.jar
		* stevescartsAPI (2.2.3.17) from StevesCarts-1.11.2-2.2.3.17.jar
		* stevescartsAPI|FARMS (2.2.3.17) from StevesCarts-1.11.2-2.2.3.17.jar
		* StorageDrawersAPI (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.6.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-1.4.4.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from refinedstorage-1.4.4.jar
		* StorageDrawersAPI|pack (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.6.jar
		* StorageDrawersAPI|registry (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.6.jar
		* StorageDrawersAPI|render (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.6.jar
		* StorageDrawersAPI|storage (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.6.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from refinedstorage-1.4.4.jar
		* totemic|API (1.11.2-4.1.0) from Totemic-1.11.2-0.8.6.jar
		* WailaAPI (1.3) from Waila-1.7.1_1.11.2.jar
	chickenchunks Invalid Fingerprint Reports: - No invalid fingerprints.: 
	enderstorage Invalid Fingerprint Reports: - No invalid fingerprints.: 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.14.2.94
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 0
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 960M/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.05, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz

### LINKED ISSUE #1027: crash after giving farmer cotton seeds from a different mod
### Minecolonies version

version 1.10.2-0.8.1342

### Expected behavior
I was just minding my own business setting up a new farm. When the farmer started to request more cotton seeds after he planted those that i gave him, the game crashed. 

here is a crash log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.7.102-universal.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  llibrary (llibrary-1.7.4-1.10.2.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.8.255-universal.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  IceAndFireForgeLoading (iceandfire-1.0.1 (1).jar)
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156-universal.jar)
  AstralCore (astralsorcery-1.4.1.jar)
  BCModPlugin (zz-backpacks 1.10.2 - 3.1.1.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 5/21/17 11:28 AM
Description: Ticking block entity

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at java.util.Collections$UnmodifiableCollection$1.next(Unknown Source)
	at com.minecolonies.coremod.tileentities.TileEntityWareHouse.checkInWareHouse(TileEntityWareHouse.java:158)
	at com.minecolonies.coremod.tileentities.TileEntityWareHouse.func_73660_a(TileEntityWareHouse.java:98)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at java.util.Collections$UnmodifiableCollection$1.next(Unknown Source)
	at com.minecolonies.coremod.tileentities.TileEntityWareHouse.checkInWareHouse(TileEntityWareHouse.java:158)
	at com.minecolonies.coremod.tileentities.TileEntityWareHouse.func_73660_a(TileEntityWareHouse.java:98)

-- Block entity being ticked --
Details:
	Name: minecolonies.WareHouse // com.minecolonies.coremod.tileentities.TileEntityWareHouse
	Block type: ID #2188 (tile.minecolonies.blockHutWareHouse // com.minecolonies.coremod.blocks.BlockHutWareHouse)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (-143,63,120), Chunk: (at 1,3,8 in -9,7; contains blocks -144,0,112 to -129,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #2188 (tile.minecolonies.blockHutWareHouse // com.minecolonies.coremod.blocks.BlockHutWareHouse)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Guncrusader'/588, l='MpServer', x=-176.99, y=66.85, z=176.48]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-220,64,212), Chunk: (at 4,4,4 in -14,13; contains blocks -224,0,208 to -209,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1043049 game time, 1805454 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 81 total; [EntityItem['item.tile.sapling.oak'/236549, l='MpServer', x=-183.39, y=65.00, z=224.04], EntityItem['item.tile.sapling.oak'/241412, l='MpServer', x=-155.09, y=66.00, z=222.20], EntitySkeleton['Skeleton'/240649, l='MpServer', x=-204.50, y=29.00, z=123.50], EntityItem['item.tile.sapling.oak'/241423, l='MpServer', x=-152.00, y=66.00, z=214.10], EntityItem['item.tile.sapling.oak'/236300, l='MpServer', x=-166.88, y=66.00, z=223.88], EntityBat['Bat'/239635, l='MpServer', x=-121.73, y=56.11, z=107.24], EntityItem['item.tile.sapling.oak'/239891, l='MpServer', x=-154.09, y=69.00, z=206.57], EntityCreeper['Creeper'/240658, l='MpServer', x=-195.50, y=20.00, z=144.50], EntityCreeper['Creeper'/240411, l='MpServer', x=-156.50, y=37.00, z=105.50], EntityCitizen['Judith V. Garrard'/281, l='MpServer', x=-158.30, y=65.00, z=183.49], EntityCreeper['Creeper'/241439, l='MpServer', x=-157.41, y=20.00, z=170.14], EntitySkeleton['Skeleton'/241441, l='MpServer', x=-158.90, y=20.00, z=169.44], EntitySkeleton['Skeleton'/241440, l='MpServer', x=-158.05, y=20.00, z=169.52], EntitySkeleton['Skeleton'/240932, l='MpServer', x=-233.73, y=43.00, z=120.53], EntityBat['Bat'/241194, l='MpServer', x=-147.40, y=39.10, z=200.75], EntityCitizen['Hannah E. Atherton'/303, l='MpServer', x=-190.70, y=64.00, z=216.50], EntityCreeper['Creeper'/240690, l='MpServer', x=-104.49, y=22.00, z=186.84], EntityCitizen['Olivia E. Cox'/308, l='MpServer', x=-144.31, y=63.06, z=147.07], EntityCitizen['Zoe X. Barker'/313, l='MpServer', x=-153.49, y=65.00, z=182.95], EntityBat['Bat'/239417, l='MpServer', x=-106.75, y=55.10, z=103.75], EntityBat['Bat'/239416, l='MpServer', x=-100.14, y=54.10, z=103.65], EntityFlicker['entity.arsmagica2.Flicker.name'/240957, l='MpServer', x=-145.50, y=26.00, z=137.50], EntityCitizen['Elliot P. Churmond'/320, l='MpServer', x=-155.49, y=66.00, z=217.37], EntityZombie['Zombie'/238658, l='MpServer', x=-167.50, y=58.00, z=153.50], EntityItem['item.tile.sapling.oak'/236871, l='MpServer', x=-166.13, y=66.00, z=220.47], EntityCitizen['Paola T. Haddock'/327, l='MpServer', x=-133.45, y=63.00, z=149.25], EntityPig['Pig'/328, l='MpServer', x=-128.28, y=63.00, z=127.48], EntityItem['item.tile.sapling.oak'/240203, l='MpServer', x=-146.89, y=66.00, z=211.32], EntityCitizen['Philip R. Gasper'/330, l='MpServer', x=-161.79, y=65.00, z=186.87], EntityCitizen['Mildred R. Amcotts'/332, l='MpServer', x=-140.40, y=65.00, z=183.35], EntityPlayerSP['Guncrusader'/588, l='MpServer', x=-176.99, y=66.85, z=176.48], EntitySpider['Spider'/239694, l='MpServer', x=-128.87, y=36.00, z=99.29], EntitySpider['Spider'/239693, l='MpServer', x=-122.56, y=36.00, z=99.17], EntityPig['Pig'/338, l='MpServer', x=-144.27, y=56.00, z=117.46], EntitySkeleton['Skeleton'/239697, l='MpServer', x=-125.57, y=36.00, z=101.60], EntityCitizen['Bailey G. Barstaple'/339, l='MpServer', x=-113.50, y=68.00, z=103.60], EntitySkeleton['Skeleton'/239696, l='MpServer', x=-122.79, y=38.00, z=105.50], EntityZombie['Zombie'/240736, l='MpServer', x=-104.50, y=31.00, z=174.50], EntityHorse['Horse'/359, l='MpServer', x=-176.99, y=66.00, z=176.48], EntityItem['item.tile.sapling.oak'/236397, l='MpServer', x=-166.09, y=66.00, z=217.22], EntityZombie['Zombie'/237955, l='MpServer', x=-135.06, y=56.00, z=109.50], EntitySpider['Spider'/237954, l='MpServer', x=-122.01, y=57.10, z=109.30], EntityItem['item.tile.sapling.oak'/236672, l='MpServer', x=-143.02, y=66.00, z=233.74], EntityCitizen['Frédérique D. Bathurst'/119172, l='MpServer', x=-177.26, y=65.00, z=161.33], EntityCitizen['Jayden Y. Crocker'/221581, l='MpServer', x=-129.50, y=67.00, z=83.70], EntitySkeleton['Skeleton'/241300, l='MpServer', x=-228.50, y=18.00, z=134.50], EntityZombie['Zombie'/241306, l='MpServer', x=-200.50, y=34.00, z=111.50], EntityCreeper['Creeper'/239261, l='MpServer', x=-182.50, y=24.00, z=175.50], EntitySpider['Spider'/238499, l='MpServer', x=-120.96, y=37.92, z=97.97], EntityCreeper['Creeper'/238498, l='MpServer', x=-130.33, y=36.00, z=100.54], EntityZombie['Zombie'/239525, l='MpServer', x=-141.48, y=56.00, z=116.20], EntityItem['item.tile.sapling.oak'/241069, l='MpServer', x=-157.88, y=75.00, z=219.13], EntityBat['Bat'/240556, l='MpServer', x=-157.20, y=37.06, z=126.52], EntityZombie['Zombie'/241334, l='MpServer', x=-162.50, y=18.00, z=183.50], EntityItem['item.tile.sapling.oak'/241082, l='MpServer', x=-155.12, y=70.00, z=210.88], EntityItem['item.tile.sapling.oak'/239294, l='MpServer', x=-160.17, y=66.00, z=212.96], EntityItem['item.tile.sapling.oak'/240830, l='MpServer', x=-160.81, y=73.00, z=220.13], EntityItem['item.tile.sapling.oak'/238789, l='MpServer', x=-155.21, y=72.00, z=212.88], EntityCitizen['Karsen S. Chilton'/131017, l='MpServer', x=-180.42, y=65.00, z=166.98], EntityBat['Bat'/241358, l='MpServer', x=-154.66, y=28.95, z=142.11], EntityCow['Cow'/207, l='MpServer', x=-255.75, y=63.00, z=111.42], EntityBat['Bat'/241356, l='MpServer', x=-160.20, y=28.31, z=152.01], EntityCow['Cow'/208, l='MpServer', x=-242.59, y=68.00, z=108.47], EntityCow['Cow'/209, l='MpServer', x=-246.18, y=70.00, z=118.51], EntityItem['item.item.apple'/239312, l='MpServer', x=-158.69, y=66.00, z=210.13], EntityPig['Pig'/213, l='MpServer', x=-254.16, y=65.00, z=228.83], EntityCow['Cow'/214, l='MpServer', x=-231.23, y=66.00, z=224.48], EntityPig['Pig'/215, l='MpServer', x=-252.46, y=64.00, z=238.72], EntityMagmaMonsterGrunt['Magma Monster Grunt'/240862, l='MpServer', x=-164.50, y=10.37, z=201.50], EntitySkeleton['Skeleton'/240864, l='MpServer', x=-226.31, y=52.00, z=145.51], EntityPig['Pig'/229, l='MpServer', x=-246.32, y=65.00, z=245.45], EntityItem['item.tile.sapling.oak'/239333, l='MpServer', x=-139.88, y=66.00, z=212.91], EntitySkeleton['Skeleton'/241391, l='MpServer', x=-222.50, y=22.00, z=178.50], EntityZombie['Zombie'/241390, l='MpServer', x=-222.50, y=22.00, z=179.50], EntityBat['Bat'/240882, l='MpServer', x=-156.78, y=27.99, z=142.22], EntityBat['Bat'/240881, l='MpServer', x=-159.49, y=22.40, z=162.41], EntitySkeleton['Skeleton'/241393, l='MpServer', x=-220.50, y=22.00, z=180.50], EntityBat['Bat'/240880, l='MpServer', x=-166.92, y=25.10, z=148.66], EntitySkeleton['Skeleton'/241392, l='MpServer', x=-221.50, y=22.00, z=180.50], EntitySkeleton['Skeleton'/237051, l='MpServer', x=-133.46, y=56.00, z=112.20], EntityItem['item.tile.sapling.oak'/240892, l='MpServer', x=-158.88, y=73.00, z=220.88]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 559963488 bytes (534 MB) / 4221042688 bytes (4025 MB) up to 4221042688 bytes (4025 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096M -Xms2096M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.32 Powered by Forge 12.18.3.2281 83 mods loaded, 83 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281.jar) 
	UCHIJAAAA	Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281.jar) 
	UCHIJAAAA	backpacks16840{3.1.1} [Backpacks!] (zz-backpacks 1.10.2 - 3.1.1.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.8.255-universal.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	cofhcore{4.1.1} [CoFH Core] (CoFHCore-1.10.2-4.1.1.156-universal.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r98} [Actually Additions] (ActuallyAdditions-1.10.2-r98.jar) 
	UCHIJAAAA	aether_legacy{v1.4.1} [Aether Legacy] (aether_legacy-1.4.jar) 
	UCHIJAAAA	Baubles{1.3.8} [Baubles] (Baubles-1.10.2-1.3.8.jar) 
	UCHIJAAAA	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UCHIJAAAA	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJAAAA	JEI{3.14.7.416} [Just Enough Items] (jei_1.10.2-3.14.7.416.jar) 
	UCHIJAAAA	BloodMagic{1.10.2-2.1.10-79} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.10.2-2.1.10-79.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	animus{2016-12-05} [Animus] (Animus-2016-12-05.jar) 
	UCHIJAAAA	appleskin{1.0.5} [AppleSkin] (AppleSkin-mc1.10.2-1.0.5.jar) 
	UCHIJAAAA	arsmagica2{1.5.018} [Ars Magica 2] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UCHIJAAAA	astralsorcery{1.4.1} [Astral Sorcery] (astralsorcery-1.4.1.jar) 
	UCHIJAAAA	Psi{r1.0-42} [Psi] (Psi-r1.0-42.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	BiblioCraft{2.2.1} [BiblioCraft] (BiblioCraft[v2.2.1][MC1.10.2].jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2142} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2142-universal.jar) 
	UCHIJAAAA	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.10.2-1.5.1.jar) 
	UCHIJAAAA	bookshelf{1.4.3.338} [Bookshelf] (Bookshelf-1.10.2-1.4.3.338.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.8.255} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.8.255-universal.jar) 
	UCHIJAAAA	brandonscore{9.9.9} [Brandon's Core] (BrandonsCore-1.10.2-2.1.7.102-universal.jar) 
	UCHIJAAAA	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCHIJAAAA	cookingforblockheads{4.2.39} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.39.jar) 
	UCHIJAAAA	dailies{1.10.2-6} [Bailey's Dailies] (dailies-1.10.2-6.jar) 
	UCHIJAAAA	darkutils{1.1.6.105} [Dark Utilities] (DarkUtilities-1.10.2-1.1.6.105.jar) 
	UCHIJAAAA	draconicevolution{2.0.12} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.12.222-universal.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.65-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.65-beta.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.1.186} [Ender IO] (EnderIO-1.10.2-3.1.186.jar) 
	UCHIJAAAA	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.4.1.jar) 
	UCHIJAAAA	grapplemod{1.10.2-v8} [Grappling hook mod] (grapplemod-1.10-v8.jar) 
	UCHIJAAAA	GraveStone{1.0.4} [GraveStone] (GraveStone-1.10.2-Graves-1.0.4.jar) 
	UCHIJAAAA	hardcorewither{2.2.3} [Hardcore Wither] (hardcoreWither-1.10.2-2.2.3-beta-4bd2a01-universal.jar) 
	UCHIJAAAA	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.10.2.jar) 
	UCHIJAAAA	iceandfire{1.0.1} [Ice and Fire] (iceandfire-1.0.1 (1).jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.4.203} [Mantle] (Mantle-1.10.2-1.1.4.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.3.500} [Tinkers' Construct] (TConstruct-1.10.2-2.6.3.jar) 
	UCHIJAAAA	immersiveengineering{0.10-58} [Immersive Engineering] (ImmersiveEngineering-0.10-58.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCHIJAAAA	KaishiWeapons{v0.1} [Kaishi's Weapons Pack] (KaishiWeapons-1.9.4.jar) 
	UCHIJAAAA	lootbags{2.3.7} [Loot Bags] (LootBags-1.10.2-2.3.7.jar) 
	UCHIJAAAA	magma_monsters{0.1.15} [magma_monsters] (MagmaMonsters-0.1.15.jar) 
	UCHIJAAAA	minecolonies{1.10.2-0.8.1342} [MineColonies] (minecolonies-universal-1.10.2-0.8.1342.jar) 
	UCHIJAAAA	mysticalagriculture{1.5.2} [Mystical Agriculture] (mysticalagriculture[1.10.2]-1.5.2b.jar) 
	UCHIJAAAA	natura{1.10.2-4.1.0.53} [Natura] (natura-1.10.2-4.1.0.53.jar) 
	UCHIJAAAA	Neat{1.3-12} [Neat] (Neat 1.3-12.jar) 
	UCHIJAAAA	notenoughwands{1.4.0} [Not Enough Wands] (notenoughwands-1.10-1.4.0.jar) 
	UCHIJAAAA	omlib{1.10.2-3.0.0-45} [OMLib] (omlib-1.10.2-3.0.0-45.jar) 
	UCHIJAAAA	openmodularturrets{1.10.2-3.0.0-56} [Open Modular Turrets] (openmodularturrets-1.10.2-3.0.0-56.jar) 
	UCHIJAAAA	overlord{2.3.7} [Overlord] (Overlord-1.10.2-2.3.7.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	ProjectE{1.10.2-PE1.3.0} [ProjectE] (ProjectE-1.10.2-PE1.3.0.jar) 
	UCHIJAAAA	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCHIJAAAA	randomthings{3.7.5} [Random Things] (RandomThings-MC1.10.2-3.7.5.jar) 
	UCHIJAAAA	thermalfoundation{2.0.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.0.5.81-universal.jar) 
	UCHIJAAAA	redstonearsenal{2.0.3} [Redstone Arsenal] (RedstoneArsenal-1.10.2-2.0.3.29-universal.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.3.585} [Reliquary] (Reliquary-1.10.2-1.3.3.585 (1).jar) 
	UCHIJAAAA	rftools{5.62} [RFTools] (rftools-1.10-5.62.jar) 
	UCHIJAAAA	rftoolscontrol{1.5.2} [RFTools Control] (rftoolsctrl-1.10-1.5.2.jar) 
	UCHIJAAAA	rftoolsdim{4.45} [RFTools Dimensions] (rftoolsdim-1.10-4.45.jar) 
	UCHIJAAAA	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCHIJAAAA	roots{0.208} [Roots] (roots-0.208.jar) 
	UCHIJAAAA	simplyjetpacks{2.1.1.43} [Simply Jetpacks 2] (SimplyJetpacks2-1.10.2-2.1.1.43.jar) 
	UCHIJAAAA	spartanshields{1.3} [Spartan Shields] (SpartanShields-1.10.2-1.3.jar) 
	UCHIJAAAA	stevescarts{2.1.3.80} [Steve's Carts 2] (StevesCarts-1.10.2-2.1.3.80.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.2.7} [Storage Drawers] (StorageDrawers-1.10.2-3.2.7.jar) 
	UCHIJAAAA	subcommonlib{1.2} [Subaraki's Common Library] (sublib 1.10.2 v1.1.2.0.jar) 
	UCHIJAAAA	tammodized{0.8.4} [TamModized] (TamModized-1.10.2-0.8.4.jar) 
	UCHIJAAAA	thermalexpansion{5.0.4} [Thermal Expansion] (ThermalExpansion-1.10.2-5.0.4.90-universal.jar) 
	UCHIJAAAA	tinker_io{release 2.3.6} [Tinker I/O] (tinker_io-1.10.2-release 2.3.6.jar) 
	UCHIJAAAA	voidcraft{0.19.4} [VoidCraft] (VoidCraft-1.10.2-0.19.4.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJAAAA	wolfarmor{1.3.1} [Wolf Armor and Storage] (wolfarmor-1.3.1.2.jar) 
	UCHIJAAAA	mcmultipart{1.2.0_74} [MCMultiPart] (MCMultiPart-experimental-1.2.0_74-universal.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
Brandon's Core (BrandonsCore-1.10.2-2.1.7.102-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
llibrary (llibrary-1.7.4-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.8.255-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  lumien.randomthings.asm.ClassTransformer
IceAndFireForgeLoading (iceandfire-1.0.1 (1).jar)
  com.github.alexthe666.iceandfire.access.IceAndFireTransformer
ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  am2.asm.Transformer
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
AstralCore (astralsorcery-1.4.1.jar)
  
BCModPlugin (zz-backpacks 1.10.2 - 3.1.1.jar)
  brad16840.common.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 369.09' Renderer: 'GeForce GTX 950M/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	CodeChickenLib Invalid Fingerprint Reports: 
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * An unsupportted RF API is installed (1.7.10R1.3.1 from (guessing) jar:file:/C:/Users/Thys%20Wentzel/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102-universal.jar!/cofh/api/CoFHAPIProps.class).
                    Ender IO needs at least 1.4.0 and will NOT work with older versions.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Thys%20Wentzel/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Thys%20Wentzel/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Thys%20Wentzel/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Thys%20Wentzel/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Thys%20Wentzel/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Thys%20Wentzel/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Thys%20Wentzel/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Thys%20Wentzel/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Thys%20Wentzel/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.7.102-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash. Scroll up!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Launched Version: 1.10.2-forge1.10.2-12.18.3.2281
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 950M/PCIe/SSE2 GL version 4.5.0 NVIDIA 369.09, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

### PR DESCRIPTION
**Pull request by cltnschlosser**
Closes #758 
Closes #1027
Closes #993 

Further testing still needs to be done, but this should fix the crashes. Unsure of what exactly was modifying the lists. Unless the AI and block ticks were done separately. Its possible that in single player the AI task was running on the server thread, and the block tick on the client thread.

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/tileentities/TileEntityWareHouse.java [hunk 1]
```diff
@@ -92,10 +93,10 @@ public void update()
                 if (i == index)
                 {
                     if(buildingEntry.getValue() instanceof AbstractBuildingWorker
-                            && !list.contains(buildingEntry.getValue())
-                            && ((AbstractBuildingWorker) buildingEntry.getValue()).needsAnything())
+                            && !taskQueue.contains(buildingEntry.getValue())
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/tileentities/TileEntityWareHouse.java:96]: MINOR This call to "contains()" may be a performance hot spot if the collection is large. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2250)

File: src/main/java/com/minecolonies/coremod/tileentities/TileEntityWareHouse.java [hunk 2]
```diff
@@ -189,13 +187,14 @@ public boolean checkInWareHouse(@NotNull final AbstractBuilding buildingEntry, b
...
                 {
                     buildingEntry.setOnGoingDelivery(true);
-                    list.add(buildingEntry);
+                    taskQueue.add(buildingEntry);
                 }
                 return true;
             }
-            if (list.contains(buildingEntry))
+
+            if (taskQueue.contains(buildingEntry))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/tileentities/TileEntityWareHouse.java:195]: MINOR This call to "contains()" may be a performance hot spot if the collection is large. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2250)

File: src/main/java/com/minecolonies/coremod/tileentities/TileEntityWareHouse.java [hunk 3]
```diff
@@ -117,32 +118,28 @@ public boolean checkInWareHouseForFood(final BuildingHome buildingEntry, final b
...
                 {
                     buildingEntry.setOnGoingDelivery(true);
-                    list.add(buildingEntry);
+                    taskQueue.add(buildingEntry);
                 }
                 return true;
             }
 
-            if (list.contains(buildingEntry))
+            if (taskQueue.contains(buildingEntry))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/tileentities/TileEntityWareHouse.java:126]: MINOR This call to "contains()" may be a performance hot spot if the collection is large. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2250)

File: src/main/java/com/minecolonies/coremod/tileentities/TileEntityWareHouse.java [hunk 4]
```diff
@@ -169,14 +166,15 @@ public boolean checkInWareHouse(@NotNull final AbstractBuilding buildingEntry, b
...
                         buildingEntry.setOnGoingDelivery(true);
-                        list.add(buildingEntry);
+                        taskQueue.add(buildingEntry);
                     }
                     return true;
                 }
             }
-            if (list.contains(buildingEntry))
+
+            if (taskQueue.contains(buildingEntry))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/tileentities/TileEntityWareHouse.java:175]: MINOR This call to "contains()" may be a performance hot spot if the collection is large. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2250)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 70 issues
* ![MAJOR][MAJOR] 29 major
* ![MINOR][MINOR] 41 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L38](https://github.com/Minecolonies/minecolonies/blob/28b251e90ef958deb980e5c87931e147ec210ad0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L38): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 32 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L38](https://github.com/Minecolonies/minecolonies/blob/28b251e90ef958deb980e5c87931e147ec210ad0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L38): class "AbstractBuilding" has 68 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L106](https://github.com/Minecolonies/minecolonies/blob/28b251e90ef958deb980e5c87931e147ec210ad0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L106): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L106](https://github.com/Minecolonies/minecolonies/blob/28b251e90ef958deb980e5c87931e147ec210ad0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L106): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L107](https://github.com/Minecolonies/minecolonies/blob/28b251e90ef958deb980e5c87931e147ec210ad0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L107): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L107](https://github.com/Minecolonies/minecolonies/blob/28b251e90ef958deb980e5c87931e147ec210ad0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L107): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L108](https://github.com/Minecolonies/minecolonies/blob/28b251e90ef958deb980e5c87931e147ec210ad0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L108): Remove this reference to "BuildingBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L109](https://github.com/Minecolonies/minecolonies/blob/28b251e90ef958deb980e5c87931e147ec210ad0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L109): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L109](https://github.com/Minecolonies/minecolonies/blob/28b251e90ef958deb980e5c87931e147ec210ad0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L109): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L110](https://github.com/Minecolonies/minecolonies/blob/28b251e90ef958deb980e5c87931e147ec210ad0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L110): Remove this reference to "BuildingFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by marvin-bitterlich** [comment]
LGTM we may have to see if we can get rid of some of the contains calls, but the n should be small in all cases 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1025/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by marchermans** [comment]
Some of These changes will be overriden by the new DMan System.
I am still working on its actuall implementation with regards to the WareHouse and the DMan AI.

However the State Based AI should make it much reliable when it comes to multithreading.

**Comment by marchermans** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1025/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by cltnschlosser** [comment]
If the contains performance becomes an issue we could keep a HashSet in parallel with this to give us a constant time contains.

**Comment by xavierh** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1025/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1025/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by Raycoms** [comment]
can you make a port to 1.10 as well?
