### PR TITLE
Overhaul study items

### LINKED ISSUE #10210: Configliststudyitems issue.
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.660

### Structurize Version

1.20.1-1.0.742

### Related Mods and their Versions

Minecolonies Offical WinterColonies-1.11

### Current Behavior

Library Students will only request the item at the top of configliststudyitems, and even if other items are placed to enable their study, they will still request the item at the top of configliststudyitems.
https://youtu.be/L8e8EjCLMd0

(To test, I changed the first item in configliststudyitems to a dragon egg.)
	#Items consumed by citizens in the Library. 
	configliststudyitems = ["minecraft:dragon_egg;600;10", "minecraft:book;600;10"]

### Expected Behavior

Request all items in configliststudyitems at the same time, and don’t request them again if they are already available.

### Reproduction Steps

1. Build a library. 
2. Place books in the library. 
3. Recruit workers.

### Logs

No crash

### Anything else?

Curious, how many people are unaware that they can actually give them books to study, which are about 1,000,000 times better than paper?

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Thodor12**
Closes #10210

# Changes proposed in this pull request
- Converted study items to a datapack in favor of configuration
- Changed the AI so that they're able to request several study items at once

## Testing
- [X] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

**Review by marchermans — APPROVED** [review]

**Review by marchermans — DISMISSED** [review]

File: src/main/java/com/minecolonies/core/colony/buildings/workerbuildings/BuildingLibrary.java [hunk 1]
```diff
@@ -36,25 +31,20 @@ public class BuildingLibrary extends AbstractBuilding
...
      */
-    private final Random random = new Random();
+    private final List<BlockPos> bookCases = new ArrayList<>();
 
     /**
-     * Study Item list, loaded from config, Typle<int,int> First is the study chance increase,second is the breakchance
+     * Random obj for random calc.
      */
-    private final List<StudyItem> studyItems;
+    private final Random random = new Random();
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/core/colony/buildings/workerbuildings/BuildingLibrary.java]: Remove Random and re-use MathUtils.RANDOM I would say here

File: src/main/java/com/minecolonies/core/entity/ai/workers/education/EntityAIStudy.java [hunk 2]
```diff
@@ -115,56 +117,60 @@ private IAIState study()
             return getState();
         }
 
+        final Map<ResourceLocation, StudyItem> studyItems = StudyItemListener.getAllStudyItems();
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/core/entity/ai/workers/education/EntityAIStudy.java]: Do we even need the ResLoc for anything here?

**Review by Raycoms — APPROVED** [review]

**Review by someaddons — APPROVED** [review]
