### PR TITLE
Fix/7568

### LINKED ISSUE #7568: ServerHangWatchdog detected that a single server tick took 180.00 seconds
### Prerequisites

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.356-ALPHA
- Structurize Version: 0.13.210-ALPHA
- Related Mods and their Versions:

## Expected behavior
No nullpointer

## Actual behavior
I'm trying to move my warehouse and started to move items from the warehouse to separate chests.
When I break a rack and take the items, so of the workers run into AI issues.
I play in single player. Also after some minutes the game (server?) freezes and no interaction is possible. All entities are frozen. Like when u have disconnect on a MP session.

## Steps to reproduce the issue

1. Have about 5 couriers.
2. Destroy some racks in the warehouse.
3. Wait for AI errors.

### Logs

- latest.log: https://gist.github.com/MeikelLP/58f063afe093d52ee77ed9683c34217c
- crashlog: https://gist.github.com/MeikelLP/8969c40a41ca8285cf0042f909ac5588

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #7568
Closes #
Closes #

# Changes proposed in this pull request:
- Better method usage of courier
- Make sure courier inventory is not full before pickup attempt.
-

Review please

### CODE REVIEW

**Review by someaddons — APPROVED** [review]

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java [hunk 1]
```diff
@@ -542,7 +543,7 @@ public boolean gatherIfInTileEntity(final TileEntity entity, final ItemStack is)
             return false;
         }
 
-        if (InventoryUtils.hasEnoughInProvider(entity, is, is.getCount()))
+        if (entity instanceof TileEntityRack && ((TileEntityRack) entity).getCount(new ItemStorage(is)) >= is.getCount())
```
Comment (MotionlessTrain) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java:551]: This does not seem to work when a courier is gathering crafted items from buildings. TileEntityColonyBuilding is inherited from TileEntityRack, but the getCount method returns 0 when querying for the itemstack/storage
