### PR TITLE
Make citizens dislike swimming more, and fix proritization of jumping

### LINKED ISSUE #754: Pathing issue with colonists: They go swimming [$10 awarded]
### Minecolonies version

version 0.6.3317.

### Expected behavior

- When a colonist/guard goes to the next waypoint, they stay on dry land.

### Actual behaviour

- They take the shortest route, typically going for a swim, even if there is no way for them to get out of the water on the other side.

### Steps to reproduce the problem

1. Build a Fishing hut on one side of a large body of water.
2. Place a citizen hut on the opposite side of body of water.
3. Make sure that there is a dry land/bridge route to the citizen hut. Preferable both. Make sure route is not a direct route to either huts.
4. Use the command _/time add x_ to make it night time.
5. Watch as the fisherman swims across the body of water, ignore the dry route.

<bountysource-plugin>

---
The **[$10 bounty](https://www.bountysource.com/issues/43703647-pathing-issue-with-colonists-they-go-swimming?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github)** on this issue has been claimed at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by cltnschlosser**
Closes #754 

I'd like someone to take this build and play around with it a bit, I think the swimming cost value might need to be tweaked still.

### CODE REVIEW

**Comment by Raycoms** [comment]
:shipit: for me already.

On discord we have a "tester" channel. Just post the jar there and ping @here to get someone to test it for you.

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1051/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/AbstractPathJob.java [hunk 1]
```diff
@@ -718,6 +719,9 @@ protected final boolean walk(@NotNull final Node parent, @NotNull final BlockPos
                 //  Early out on previously visited and closed nodes
                 return false;
             }
+
+            // Update change in position
+            dPos = dPos.add(0, yDelta, 0);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/AbstractPathJob.java]: MINOR Introduce a new variable instead of reusing the parameter "dPos". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1226)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 32 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 31 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractPathJob.java#L30](https://github.com/Minecolonies/minecolonies/blob/83bade2ec8932b7c3705565a2ac8214cfe818632/src/main/java/com/minecolonies/coremod/entity/pathfinding/AbstractPathJob.java#L30): class "AbstractPathJob" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/83bade2ec8932b7c3705565a2ac8214cfe818632/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/83bade2ec8932b7c3705565a2ac8214cfe818632/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/83bade2ec8932b7c3705565a2ac8214cfe818632/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/83bade2ec8932b7c3705565a2ac8214cfe818632/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/83bade2ec8932b7c3705565a2ac8214cfe818632/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/83bade2ec8932b7c3705565a2ac8214cfe818632/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/83bade2ec8932b7c3705565a2ac8214cfe818632/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/83bade2ec8932b7c3705565a2ac8214cfe818632/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions](https://github.com/Minecolonies/minecolonies/blob/83bade2ec8932b7c3705565a2ac8214cfe818632/src/main/java/com/minecolonies/coremod/colony/permissions): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 31 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 30 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractPathJob.java#L30](https://github.com/Minecolonies/minecolonies/blob/92539269c12fc079d7361a3b376af4a71cadd296/src/main/java/com/minecolonies/coremod/entity/pathfinding/AbstractPathJob.java#L30): class "AbstractPathJob" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/92539269c12fc079d7361a3b376af4a71cadd296/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/92539269c12fc079d7361a3b376af4a71cadd296/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/92539269c12fc079d7361a3b376af4a71cadd296/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/92539269c12fc079d7361a3b376af4a71cadd296/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/92539269c12fc079d7361a3b376af4a71cadd296/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/92539269c12fc079d7361a3b376af4a71cadd296/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/92539269c12fc079d7361a3b376af4a71cadd296/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/92539269c12fc079d7361a3b376af4a71cadd296/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions](https://github.com/Minecolonies/minecolonies/blob/92539269c12fc079d7361a3b376af4a71cadd296/src/main/java/com/minecolonies/coremod/colony/permissions): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAICitizenWander.java [hunk 2]
```diff
@@ -45,17 +45,18 @@ public boolean shouldExecute()
         {
             return false;
         }
-        Vec3d Vec3d = RandomPositionGenerator.findRandomTarget(citizen, 10, 7);
-        if (Vec3d == null)
+
+        Vec3d vec3d = RandomPositionGenerator.getLandPos(citizen, 10, 7);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAICitizenWander.java:49]: MAJOR Assign this magic number 10 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 7 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 35 issues
* ![MAJOR][MAJOR] 5 major
* ![MINOR][MINOR] 30 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EntityAICitizenWander.java#L72](https://github.com/Minecolonies/minecolonies/blob/7c25f37380e06532150da5640e10887ed2df528a/src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAICitizenWander.java#L72): Assign this magic number 100 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityAICitizenWander.java#L77](https://github.com/Minecolonies/minecolonies/blob/7c25f37380e06532150da5640e10887ed2df528a/src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAICitizenWander.java#L77): Assign this magic number 120 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [AbstractPathJob.java#L30](https://github.com/Minecolonies/minecolonies/blob/7c25f37380e06532150da5640e10887ed2df528a/src/main/java/com/minecolonies/coremod/entity/pathfinding/AbstractPathJob.java#L30): class "AbstractPathJob" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/7c25f37380e06532150da5640e10887ed2df528a/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/7c25f37380e06532150da5640e10887ed2df528a/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/7c25f37380e06532150da5640e10887ed2df528a/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/7c25f37380e06532150da5640e10887ed2df528a/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/7c25f37380e06532150da5640e10887ed2df528a/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/7c25f37380e06532150da5640e10887ed2df528a/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/7c25f37380e06532150da5640e10887ed2df528a/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 35 issues
* ![MAJOR][MAJOR] 5 major
* ![MINOR][MINOR] 30 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EntityAICitizenWander.java#L72](https://github.com/Minecolonies/minecolonies/blob/77a75ee25b059be18f47349b3acec72d49b30a82/src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAICitizenWander.java#L72): Assign this magic number 100 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityAICitizenWander.java#L77](https://github.com/Minecolonies/minecolonies/blob/77a75ee25b059be18f47349b3acec72d49b30a82/src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAICitizenWander.java#L77): Assign this magic number 120 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [AbstractPathJob.java#L30](https://github.com/Minecolonies/minecolonies/blob/77a75ee25b059be18f47349b3acec72d49b30a82/src/main/java/com/minecolonies/coremod/entity/pathfinding/AbstractPathJob.java#L30): class "AbstractPathJob" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/77a75ee25b059be18f47349b3acec72d49b30a82/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/77a75ee25b059be18f47349b3acec72d49b30a82/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/77a75ee25b059be18f47349b3acec72d49b30a82/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/77a75ee25b059be18f47349b3acec72d49b30a82/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/77a75ee25b059be18f47349b3acec72d49b30a82/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/77a75ee25b059be18f47349b3acec72d49b30a82/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/77a75ee25b059be18f47349b3acec72d49b30a82/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 35 issues
* ![MAJOR][MAJOR] 5 major
* ![MINOR][MINOR] 30 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EntityAICitizenWander.java#L72](https://github.com/Minecolonies/minecolonies/blob/94a03c3049027270044ccb9b2787de1459dd5ce9/src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAICitizenWander.java#L72): Assign this magic number 100 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityAICitizenWander.java#L77](https://github.com/Minecolonies/minecolonies/blob/94a03c3049027270044ccb9b2787de1459dd5ce9/src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAICitizenWander.java#L77): Assign this magic number 120 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [AbstractPathJob.java#L30](https://github.com/Minecolonies/minecolonies/blob/94a03c3049027270044ccb9b2787de1459dd5ce9/src/main/java/com/minecolonies/coremod/entity/pathfinding/AbstractPathJob.java#L30): class "AbstractPathJob" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/94a03c3049027270044ccb9b2787de1459dd5ce9/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/94a03c3049027270044ccb9b2787de1459dd5ce9/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/94a03c3049027270044ccb9b2787de1459dd5ce9/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/94a03c3049027270044ccb9b2787de1459dd5ce9/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/94a03c3049027270044ccb9b2787de1459dd5ce9/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/94a03c3049027270044ccb9b2787de1459dd5ce9/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/94a03c3049027270044ccb9b2787de1459dd5ce9/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java [hunk 3]
```diff
@@ -82,20 +84,20 @@ public Path getPathToPos(final BlockPos pos)
...
-//    @Override
-//    protected boolean isDirectPathBetweenPoints(final Vec3d Vec3d, final Vec3d Vec3d1, final int i, final int i1, final int i2)
-//    {
-//        //we don't use, so it doesn't matter
-//        return false;
-//    }
+    @Override
+    protected boolean isDirectPathBetweenPoints(final Vec3d start, final Vec3d end, int sizeX, int sizeY, int sizeZ)
+    {
+        // TODO improve road walking. This is better in some situations, but still not great.
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java]: INFO Complete the task associated to this TODO comment. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java [hunk 4]
```diff
@@ -304,31 +291,31 @@ else if (entity.isInWater())
 
                 this.getPath().setCurrentPathIndex(oldIndex);
 
-                Vec3d Vec3d = this.getPath().getPosition(this.entity);
+                Vec3d vec3d = this.getPath().getPosition(this.entity);
 
-                if (Vec3d.squareDistanceTo(new Vec3d(entity.posX, Vec3d.yCoord, entity.posZ)) < 0.1
-                      && Math.abs(entity.posY - Vec3d.yCoord) < 0.5)
+                if (vec3d.squareDistanceTo(new Vec3d(entity.posX, vec3d.yCoord, entity.posZ)) < 0.1
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java:296]: MAJOR Assign this magic number 0.1 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java [hunk 5]
```diff
@@ -304,31 +291,31 @@ else if (entity.isInWater())
...
+                      && Math.abs(entity.posY - vec3d.yCoord) < 0.5)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java:297]: MAJOR Assign this magic number 0.5 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java [hunk 6]
```diff
@@ -131,6 +131,7 @@ public boolean walkToBlock(@NotNull BlockPos target, int range, boolean onMove)
                 currentProxy = target;
             }
 
+            //TODO any reason we don't just call proxyList.clear() ?
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java]: INFO Complete the task associated to this TODO comment. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java [hunk 7]
```diff
@@ -91,153 +90,156 @@ public static void debugDraw(final double frame)
...
-        //that should set the colors correctly
-        VertexBuffer.pos((double) (-i - 1), -5.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
-        VertexBuffer.pos((double) (-i - 1), 12.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
-        VertexBuffer.pos((double) (i + 1), 12.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
-        VertexBuffer.pos((double) (i + 1), -5.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
+        final Tessellator tessellator = Tessellator.getInstance();
+        final VertexBuffer vertexBuffer = tessellator.getBuffer();
+        vertexBuffer.begin(GL11.GL_QUADS, DefaultVertexFormats.POSITION_COLOR);
+        vertexBuffer.pos((double) (-i - 1), -5.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
+        vertexBuffer.pos((double) (-i - 1), 12.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java:224]: MAJOR Assign this magic number 12.0D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.25F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java [hunk 8]
```diff
@@ -91,153 +90,156 @@ public static void debugDraw(final double frame)
...
+        vertexBuffer.pos((double) (i + 1), 12.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java:225]: MAJOR Assign this magic number 12.0D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.25F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java [hunk 9]
```diff
@@ -91,153 +90,156 @@ public static void debugDraw(final double frame)
...
         if (Math.sqrt(dx * dx + dy * dy + dz * dz) <= 5D)
         {
-            renderDebugText(n, f1);
+            renderDebugText(n);
         }
 
-        GL11.glScaled(0.25, 0.25, 0.25);
-
-        GL11.glBegin(GL11.GL_QUADS);
+        GlStateManager.scale(0.25D, 0.25D, 0.25D);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java:130]: MAJOR Assign this magic number 0.25D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.25D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.25D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java [hunk 10]
```diff
@@ -91,153 +90,156 @@ public static void debugDraw(final double frame)
...
-        VertexBuffer.pos((double) (-i - 1), 12.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
-        VertexBuffer.pos((double) (i + 1), 12.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
-        VertexBuffer.pos((double) (i + 1), -5.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
+        final Tessellator tessellator = Tessellator.getInstance();
+        final VertexBuffer vertexBuffer = tessellator.getBuffer();
+        vertexBuffer.begin(GL11.GL_QUADS, DefaultVertexFormats.POSITION_COLOR);
+        vertexBuffer.pos((double) (-i - 1), -5.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
+        vertexBuffer.pos((double) (-i - 1), 12.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
+        vertexBuffer.pos((double) (i + 1), 12.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
+        vertexBuffer.pos((double) (i + 1), -5.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java:226]: MAJOR Assign this magic number 5.0D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.25F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java [hunk 11]
```diff
@@ -91,153 +90,156 @@ public static void debugDraw(final double frame)
...
         final String s1 = String.format("F: %.3f [%d]", n.getCost(), n.getCounterAdded());
         final String s2 = String.format("G: %.3f [%d]", n.getScore(), n.getCounterVisited());
         final FontRenderer fontrenderer = Minecraft.getMinecraft().fontRendererObj;
-        GL11.glPushAttrib(GL11.GL_ALL_ATTRIB_BITS);
-        GL11.glPushMatrix();
-        GL11.glTranslatef(0.0F, 0.75F, 0.0F);
-        GL11.glNormal3f(0.0F, 1.0F, 0.0F);
+        GlStateManager.pushAttrib();
+        GlStateManager.pushMatrix();
+        GlStateManager.translate(0.0F, 0.75F, 0.0F);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java:198]: MAJOR Assign this magic number 0.75F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java [hunk 12]
```diff
@@ -91,153 +90,156 @@ public static void debugDraw(final double frame)
...
-        GL11.glDepthMask(true);
-        GL11.glTranslatef(0.0F, -5F, 0.0F);
-        fontrenderer.drawString(s1, -fontrenderer.getStringWidth(s1) / 2, 0, 553648127);
-        GL11.glTranslatef(0.0F, 8F, 0.0F);
-        fontrenderer.drawString(s2, -fontrenderer.getStringWidth(s2) / 2, 0, 553648127);
-        GL11.glPopMatrix();
-        GL11.glPopAttrib();
+        GlStateManager.enableTexture2D();
+
+        GlStateManager.translate(0.0F, -5F, 0.0F);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java:230]: MAJOR Assign this magic number 5F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java [hunk 13]
```diff
@@ -91,153 +90,156 @@ public static void debugDraw(final double frame)
...
+        fontrenderer.drawString(s1, -fontrenderer.getStringWidth(s1) / 2, 0, 0xFFFFFFFF);
+        GlStateManager.translate(0.0F, 8F, 0.0F);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java:232]: MAJOR Assign this magic number 8F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java [hunk 14]
```diff
@@ -91,153 +90,156 @@ public static void debugDraw(final double frame)
...
-        GL11.glScalef(-f1, -f1, f1);
-        GL11.glTranslatef(0.0F, (float) (0.25D / f1), 0.0F);
-        GL11.glDepthMask(false);
-
-        final Tessellator tessellator = Tessellator.getInstance();
-        final VertexBuffer VertexBuffer = tessellator.getBuffer();
-        GL11.glDisable(GL11.GL_TEXTURE_2D);
+        GlStateManager.rotate(-renderManager.playerViewY, 0.0F, 1.0F, 0.0F);
+        GlStateManager.rotate(renderManager.playerViewX, 1.0F, 0.0F, 0.0F);
+        GlStateManager.scale(-0.014F, -0.014F, 0.014F);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java]: MAJOR Assign this magic number 0.014F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.014F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.014F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java [hunk 15]
```diff
@@ -91,153 +90,156 @@ public static void debugDraw(final double frame)
...
+        GlStateManager.translate(0.0F, 18F, 0.0F);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java]: MAJOR Assign this magic number 18F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java [hunk 16]
```diff
@@ -91,153 +90,156 @@ public static void debugDraw(final double frame)
...
+        GlStateManager.enableTexture2D();
+
+        GlStateManager.translate(0.0F, -5F, 0.0F);
+        fontrenderer.drawString(s1, -fontrenderer.getStringWidth(s1) / 2, 0, 0xFFFFFFFF);
+        GlStateManager.translate(0.0F, 8F, 0.0F);
+        fontrenderer.drawString(s2, -fontrenderer.getStringWidth(s2) / 2, 0, 0xFFFFFFFF);
+
+        GlStateManager.enableDepth();
+        GlStateManager.depthMask(true);
+        GlStateManager.translate(0.0F, -8F, 0.0F);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java:237]: MAJOR Assign this magic number 8F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java [hunk 17]
```diff
@@ -91,153 +90,156 @@ public static void debugDraw(final double frame)
...
+        fontrenderer.drawString(s1, -fontrenderer.getStringWidth(s1) / 2, 0, 0xFFFFFFFF);
+        GlStateManager.translate(0.0F, 8F, 0.0F);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java:239]: MAJOR Assign this magic number 8F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java [hunk 18]
```diff
@@ -91,153 +90,156 @@ public static void debugDraw(final double frame)
...
             final double pdx = n.parent.pos.getX() - n.pos.getX() + 0.125;
             final double pdy = n.parent.pos.getY() - n.pos.getY() + 0.125;
             final double pdz = n.parent.pos.getZ() - n.pos.getZ() + 0.125;
 
-            GL11.glVertex3d(0.5, 0.5, 0.5);
-            GL11.glVertex3d(pdx / 0.25, pdy / 0.25, pdz / 0.25);
-
-            GL11.glEnd();
+            vertexBuffer.begin(GL11.GL_LINES, DefaultVertexFormats.POSITION_COLOR);
+            vertexBuffer.pos(0.5D, 0.5D, 0.5D).color(0.75F, 0.75F, 0.75F, 1.0F).endVertex();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java:182]: MAJOR Assign this magic number 0.5D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.5D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.5D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.75F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.75F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.75F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java [hunk 19]
```diff
@@ -91,153 +90,156 @@ public static void debugDraw(final double frame)
...
     {
-        GL11.glPushMatrix();
-        GL11.glTranslated((double) n.pos.getX() + 0.375, (double) n.pos.getY() + 0.375, (double) n.pos.getZ() + 0.375);
-
-        final float f = 1.6F;
-        final float f1 = (float) (0.016666668D * f / 2);
-
-        //  Nameplate
+        GlStateManager.pushMatrix();
+        GlStateManager.translate((double) n.pos.getX() + 0.375, (double) n.pos.getY() + 0.375, (double) n.pos.getZ() + 0.375);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java:119]: MAJOR Assign this magic number 0.375 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.375 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.375 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java [hunk 20]
```diff
@@ -91,153 +90,156 @@ public static void debugDraw(final double frame)
...
             final double pdy = n.parent.pos.getY() - n.pos.getY() + 0.125;
             final double pdz = n.parent.pos.getZ() - n.pos.getZ() + 0.125;
 
-            GL11.glVertex3d(0.5, 0.5, 0.5);
-            GL11.glVertex3d(pdx / 0.25, pdy / 0.25, pdz / 0.25);
-
-            GL11.glEnd();
+            vertexBuffer.begin(GL11.GL_LINES, DefaultVertexFormats.POSITION_COLOR);
+            vertexBuffer.pos(0.5D, 0.5D, 0.5D).color(0.75F, 0.75F, 0.75F, 1.0F).endVertex();
+            vertexBuffer.pos(pdx / 0.25, pdy / 0.25, pdz / 0.25).color(0.75F, 0.75F, 0.75F, 1.0F).endVertex();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java:183]: MAJOR Assign this magic number 0.25 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.25 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.25 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.75F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.75F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.75F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java [hunk 21]
```diff
@@ -91,153 +90,156 @@ public static void debugDraw(final double frame)
...
-
-        //  Nameplate
+        GlStateManager.pushMatrix();
+        GlStateManager.translate((double) n.pos.getX() + 0.375, (double) n.pos.getY() + 0.375, (double) n.pos.getZ() + 0.375);
 
         final Entity entity = Minecraft.getMinecraft().getRenderViewEntity();
         final double dx = n.pos.getX() - entity.posX;
         final double dy = n.pos.getY() - entity.posY;
         final double dz = n.pos.getZ() - entity.posZ;
         if (Math.sqrt(dx * dx + dy * dy + dz * dz) <= 5D)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java:125]: MAJOR Assign this magic number 5D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java [hunk 22]
```diff
@@ -91,153 +90,156 @@ public static void debugDraw(final double frame)
...
 
-        //that should set the colors correctly
-        VertexBuffer.pos((double) (-i - 1), -5.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
-        VertexBuffer.pos((double) (-i - 1), 12.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
-        VertexBuffer.pos((double) (i + 1), 12.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
-        VertexBuffer.pos((double) (i + 1), -5.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
+        final Tessellator tessellator = Tessellator.getInstance();
+        final VertexBuffer vertexBuffer = tessellator.getBuffer();
+        vertexBuffer.begin(GL11.GL_QUADS, DefaultVertexFormats.POSITION_COLOR);
+        vertexBuffer.pos((double) (-i - 1), -5.0D, 0.0D).color(0.0F, 0.0F, 0.0F, 0.25F).endVertex();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java:223]: MAJOR Assign this magic number 5.0D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.25F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 126 issues
* ![MAJOR][MAJOR] 87 major
* ![MINOR][MINOR] 35 minor
* ![INFO][INFO] 4 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/cb268ef8ec9bf3c744fe4ec8c71c927828f47758/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.222 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/cb268ef8ec9bf3c744fe4ec8c71c927828f47758/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 44 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/cb268ef8ec9bf3c744fe4ec8c71c927828f47758/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): class "Colony" has 83 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L178](https://github.com/Minecolonies/minecolonies/blob/cb268ef8ec9bf3c744fe4ec8c71c927828f47758/src/main/java/com/minecolonies/coremod/colony/Colony.java#L178): Assign this magic number 5 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L558](https://github.com/Minecolonies/minecolonies/blob/cb268ef8ec9bf3c744fe4ec8c71c927828f47758/src/main/java/com/minecolonies/coremod/colony/Colony.java#L558): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1022](https://github.com/Minecolonies/minecolonies/blob/cb268ef8ec9bf3c744fe4ec8c71c927828f47758/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1022): Assign this magic number 20 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1023](https://github.com/Minecolonies/minecolonies/blob/cb268ef8ec9bf3c744fe4ec8c71c927828f47758/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1023): Assign this magic number 60 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1147](https://github.com/Minecolonies/minecolonies/blob/cb268ef8ec9bf3c744fe4ec8c71c927828f47758/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1147): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1149](https://github.com/Minecolonies/minecolonies/blob/cb268ef8ec9bf3c744fe4ec8c71c927828f47758/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1149): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1151](https://github.com/Minecolonies/minecolonies/blob/cb268ef8ec9bf3c744fe4ec8c71c927828f47758/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1151): Assign this magic number 128 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java [hunk 23]
```diff
@@ -82,20 +84,20 @@ public Path getPathToPos(final BlockPos pos)
...
-//    @Override
-//    protected boolean isDirectPathBetweenPoints(final Vec3d Vec3d, final Vec3d Vec3d1, final int i, final int i1, final int i2)
-//    {
-//        //we don't use, so it doesn't matter
-//        return false;
-//    }
+    @Override
+    protected boolean isDirectPathBetweenPoints(final Vec3d start, final Vec3d end, final int sizeX, final int sizeY, final int sizeZ)
+    {
+        // TODO improve road walking. This is better in some situations, but still not great.
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java:97]: INFO Complete the task associated to this TODO comment. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java [hunk 24]
```diff
@@ -91,153 +90,156 @@ public static void debugDraw(final double frame)
...
 
         final RenderManager renderManager = Minecraft.getMinecraft().getRenderManager();
-        GL11.glRotatef(-renderManager.playerViewY, 0.0F, 1.0F, 0.0F);
-        GL11.glRotatef(renderManager.playerViewX, 1.0F, 0.0F, 0.0F);
-        GL11.glScalef(-f1, -f1, f1);
-        GL11.glTranslatef(0.0F, (float) (0.25D / f1), 0.0F);
-        GL11.glDepthMask(false);
+        GlStateManager.rotate(-renderManager.playerViewY, 0.0F, 1.0F, 0.0F);
+        GlStateManager.rotate(renderManager.playerViewX, 1.0F, 0.0F, 0.0F);
+        GlStateManager.scale(-0.014F, -0.014F, 0.014F);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java:204]: MAJOR Assign this magic number 0.014F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.014F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
MAJOR Assign this magic number 0.014F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java [hunk 25]
```diff
@@ -91,153 +90,156 @@ public static void debugDraw(final double frame)
...
+        GlStateManager.translate(0.0F, 18F, 0.0F);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java:205]: MAJOR Assign this magic number 18F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 123 issues
* ![MAJOR][MAJOR] 87 major
* ![MINOR][MINOR] 32 minor
* ![INFO][INFO] 4 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/3d17da0c13e8119958638ab5b27f1ea32858ca48/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.222 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/3d17da0c13e8119958638ab5b27f1ea32858ca48/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 44 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/3d17da0c13e8119958638ab5b27f1ea32858ca48/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): class "Colony" has 83 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L178](https://github.com/Minecolonies/minecolonies/blob/3d17da0c13e8119958638ab5b27f1ea32858ca48/src/main/java/com/minecolonies/coremod/colony/Colony.java#L178): Assign this magic number 5 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L558](https://github.com/Minecolonies/minecolonies/blob/3d17da0c13e8119958638ab5b27f1ea32858ca48/src/main/java/com/minecolonies/coremod/colony/Colony.java#L558): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1022](https://github.com/Minecolonies/minecolonies/blob/3d17da0c13e8119958638ab5b27f1ea32858ca48/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1022): Assign this magic number 20 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1023](https://github.com/Minecolonies/minecolonies/blob/3d17da0c13e8119958638ab5b27f1ea32858ca48/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1023): Assign this magic number 60 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1147](https://github.com/Minecolonies/minecolonies/blob/3d17da0c13e8119958638ab5b27f1ea32858ca48/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1147): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1149](https://github.com/Minecolonies/minecolonies/blob/3d17da0c13e8119958638ab5b27f1ea32858ca48/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1149): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1151](https://github.com/Minecolonies/minecolonies/blob/3d17da0c13e8119958638ab5b27f1ea32858ca48/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1151): Assign this magic number 128 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by cltnschlosser** [comment]
Not fixing the Pathfinding debug magic numbers, because I'll be honest, some of them are kinda magic.

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 123 issues
* ![MAJOR][MAJOR] 87 major
* ![MINOR][MINOR] 32 minor
* ![INFO][INFO] 4 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/c9ad2327ee568931f3b46dfc54763f4d29741c72/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.222 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/c9ad2327ee568931f3b46dfc54763f4d29741c72/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 44 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/c9ad2327ee568931f3b46dfc54763f4d29741c72/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): class "Colony" has 83 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L178](https://github.com/Minecolonies/minecolonies/blob/c9ad2327ee568931f3b46dfc54763f4d29741c72/src/main/java/com/minecolonies/coremod/colony/Colony.java#L178): Assign this magic number 5 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L558](https://github.com/Minecolonies/minecolonies/blob/c9ad2327ee568931f3b46dfc54763f4d29741c72/src/main/java/com/minecolonies/coremod/colony/Colony.java#L558): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1022](https://github.com/Minecolonies/minecolonies/blob/c9ad2327ee568931f3b46dfc54763f4d29741c72/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1022): Assign this magic number 20 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1023](https://github.com/Minecolonies/minecolonies/blob/c9ad2327ee568931f3b46dfc54763f4d29741c72/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1023): Assign this magic number 60 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1147](https://github.com/Minecolonies/minecolonies/blob/c9ad2327ee568931f3b46dfc54763f4d29741c72/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1147): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1149](https://github.com/Minecolonies/minecolonies/blob/c9ad2327ee568931f3b46dfc54763f4d29741c72/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1149): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1151](https://github.com/Minecolonies/minecolonies/blob/c9ad2327ee568931f3b46dfc54763f4d29741c72/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1151): Assign this magic number 128 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by cltnschlosser** [comment]
Currently awaiting testing feedback

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java [hunk 26]
```diff
@@ -272,7 +272,7 @@ else if (targetY <= levelDepth && workerY > levelDepth)
                 if (level.getRandomNode() != null && level.getRandomNode().getParent() != null)
                 {
                     final List<BlockPos> nodesToTarget = new ArrayList<>();
-                    com.minecolonies.coremod.entity.ai.citizen.miner.Node currentNode = level.getNode(level.getRandomNode().getParent());
+                    Node currentNode = level.getNode(level.getRandomNode().getParent());
                     while (new Point2D.Double(currentNode.getX(), currentNode.getZ()) != currentNode.getParent() && currentNode.getParent() != null)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java:276]: MAJOR Use the "equals" method if value comparison was intended. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1698)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java [hunk 27]
```diff
@@ -304,7 +304,7 @@ else if (targetY <= levelDepth)
 
                 if (lastNode != null && lastNode.getParent() != null)
                 {
-                    com.minecolonies.coremod.entity.ai.citizen.miner.Node currentNode = level.getNode(lastNode.getParent());
+                    Node currentNode = level.getNode(lastNode.getParent());
                     while (new Point2D.Double(currentNode.getX(), currentNode.getZ()) != currentNode.getParent() && currentNode.getParent() != null)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java:308]: MAJOR Use the "equals" method if value comparison was intended. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1698)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java [hunk 28]
```diff
@@ -235,7 +235,7 @@ private BlockPos getMinerProxy(final BlockPos target, final double distanceToPat
             {
                 if (level.getRandomNode() != null && level.getRandomNode().getParent() != null)
                 {
-                    com.minecolonies.coremod.entity.ai.citizen.miner.Node currentNode = level.getNode(level.getRandomNode().getParent());
+                    Node currentNode = level.getNode(level.getRandomNode().getParent());
                     while (new Point2D.Double(currentNode.getX(), currentNode.getZ()) != currentNode.getParent() && currentNode.getParent() != null)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java:239]: MAJOR Use the "equals" method if value comparison was intended. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1698)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java [hunk 29]
```diff
@@ -315,7 +315,7 @@ else if (targetY <= levelDepth)
                 if (level.getRandomNode().getParent() != null)
                 {
                     final List<BlockPos> nodesToTarget = new ArrayList<>();
-                    com.minecolonies.coremod.entity.ai.citizen.miner.Node currentNode = level.getNode(level.getRandomNode().getParent());
+                    Node currentNode = level.getNode(level.getRandomNode().getParent());
                     while (new Point2D.Double(currentNode.getX(), currentNode.getZ()) != currentNode.getParent() && currentNode.getParent() != null)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java:319]: MAJOR Use the "equals" method if value comparison was intended. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1698)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 102 issues
* ![MAJOR][MAJOR] 72 major
* ![MINOR][MINOR] 28 minor
* ![INFO][INFO] 2 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/aa511441080e6b95589115dac6d6f229e37008f5/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.225 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L47](https://github.com/Minecolonies/minecolonies/blob/aa511441080e6b95589115dac6d6f229e37008f5/src/main/java/com/minecolonies/coremod/colony/Colony.java#L47): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 44 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L47](https://github.com/Minecolonies/minecolonies/blob/aa511441080e6b95589115dac6d6f229e37008f5/src/main/java/com/minecolonies/coremod/colony/Colony.java#L47): class "Colony" has 83 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L181](https://github.com/Minecolonies/minecolonies/blob/aa511441080e6b95589115dac6d6f229e37008f5/src/main/java/com/minecolonies/coremod/colony/Colony.java#L181): Assign this magic number 5 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L561](https://github.com/Minecolonies/minecolonies/blob/aa511441080e6b95589115dac6d6f229e37008f5/src/main/java/com/minecolonies/coremod/colony/Colony.java#L561): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1025](https://github.com/Minecolonies/minecolonies/blob/aa511441080e6b95589115dac6d6f229e37008f5/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1025): Assign this magic number 20 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1026](https://github.com/Minecolonies/minecolonies/blob/aa511441080e6b95589115dac6d6f229e37008f5/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1026): Assign this magic number 60 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1150](https://github.com/Minecolonies/minecolonies/blob/aa511441080e6b95589115dac6d6f229e37008f5/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1150): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1152](https://github.com/Minecolonies/minecolonies/blob/aa511441080e6b95589115dac6d6f229e37008f5/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1152): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1154](https://github.com/Minecolonies/minecolonies/blob/aa511441080e6b95589115dac6d6f229e37008f5/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1154): Assign this magic number 128 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by cltnschlosser** [comment]
Those sonar issues will be fixed in a future pull request.

The testers seem to like the pathfinding changes, so this is ready for review @Minecolonies/maintainers

**Comment by marvin-bitterlich** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1051/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)
