### PR TITLE
Fix/#4190

### LINKED ISSUE #4083: Enchantment stripped when using "fufill request"
### Minecolonies version

Version: minecolonies-1.12.2-0.10.545-ALPHA-universal

### Expected behavior

If worker isn't able to use enchanted tool (or enchantment level is too high), worker will take valid item (correct level enchantment, or none if present)
- 

### Actual behaviour

When player has enchanted item and regular item of same type (Used Iron axe with efficiency V and normal Iron as well as stone Efficiency V and regular stone). May be inventory dependent, but the farthest right bottom slot had correct item, and middle of second row had enchanted. Both times, worker took enchanted item and removed enchantment
- 

### Steps to reproduce the problem

Enchanted item further left and up than an unenchanted item, and "Fufill request" with worker
1. 
2. 
3. 
4. ... Profit

### LINKED ISSUE #4190: Request system problem when carrying more than requested
### Minecolonies version

Version: minecolonies-0.10.493-RELEASE-universal

### Expected behavior

- Worker asks for exact number of resource and upon fulfilling, worker proceeds.

### Actual behaviour

- If resource can be stacked and amount of resource exceeds the requested amount, the requestor does not process the request and proceed, but rather asks again. For example, the builder asks for 20 cobblestone stairs and I have 30 in my inventory. I fulfill the request and it disappears from the gui for half a second and then returns. The builder has 20 cobblestone stairs at this point, but is still waiting as if I haven't given them yet. If I fulfill again, it gives the remaining 10 cobblestone stairs. Now the builder has all 30 cobblestone stairs, but the request now appears to be processed. If I originally only had 20 cobblestone stairs in my inventory when fulfilling the request, it would have processed as expected.

### LINKED ISSUE #4196: Crusher doesn't do job daily
### Minecolonies version

Version: minecolonies-0.10.593-RELEASE-universal

### Expected behavior

- Everyday the crusher makes requests for the materials needed to crush up to double the max amount. 

### Actual behaviour

-  The crusher doesn't make the request everyday, but only after the builder has built/upgraded the crusher hut, as far as I can tell. Sleeping in a bed right by the crusher hut shows the crusher does nothing the next day, even with the needed resources in his inventory. I've noticed this since first building the crusher hut and currently up to level 4. The crusher hut style is medieval oak.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #4190
Closes #4083
Closes #4196

# Changes proposed in this pull request:
- Fix issues related to transferring items.
- Improve sleeping (better performance, more regular wakeup calls for daily jobs)
-

Review please

### CODE REVIEW

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/main/java/com/minecolonies/coremod/network/messages/TransferItemsRequestMessage.java  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=4771284&bid=15900093)

**Review by someaddons — DISMISSED** [review]

File: src/main/java/com/minecolonies/coremod/client/gui/WindowHutBuilder.java [hunk 1]
```diff
@@ -242,8 +242,8 @@ private void transferItems(@NotNull final Button button)
         {
             // The itemStack size should not be greater than itemStack.getMaxStackSize, We send 1 instead
             // and use quantity for the size
-            @NotNull final ItemStack itemStack = new ItemStack(res.getItem(), 1);
-            itemStack.setTag(res.getItemStack().getTag());
+            @NotNull final ItemStack itemStack = res.getItemStack().copy();
+            itemStack.setCount(1);
```
Comment (Asherslab) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowHutBuilder.java:246]: I feel like it might fix more bugs if we simply actually create multiple stacks with proper stack sizes instead of our NBT hacky thing

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/client/gui/WindowHutBuilder.java:246]: That's what I did in this PR =P I removed the NBT hacky thing and just copyed the stack and adjusted the size.

Comment (Asherslab) [reply src/main/java/com/minecolonies/coremod/client/gui/WindowHutBuilder.java:246]: yeah but you're setting it to 1, it'd never go over?

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/client/gui/WindowHutBuilder.java:246]: Yeah we send the amount extra.

**Comment by marvin-bitterlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/main/java/com/minecolonies/coremod/network/messages/TransferItemsRequestMessage.java  -3
+ src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAISleep.java  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=4771284&bid=15900093)

**Review by someaddons — APPROVED** [review]

File: src/main/java/com/minecolonies/coremod/client/gui/WindowHutBuilder.java (hunk 1 above)
Comment (marchermans) [reply src/main/java/com/minecolonies/coremod/client/gui/WindowHutBuilder.java:246]: ..... I am not sure this is the right approach here.....

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/client/gui/WindowHutBuilder.java:246]: It's because we sometimes send more than the max stacksize, we have to send the amount and the stack we want to send separate.
