### PR TITLE
Fix crusher and fletcher things

### LINKED ISSUE #11300: Stack constructor error in logs after requesting item
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [x] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.1079

### Structurize Version

1.20.1-1.0.784

### Related Mods and their Versions

_No response_

### Current Behavior

After requesting flint via a postbox an error appears in the console.

"Stack count mismatch (stack=3 gravel, count=384). ItemStack's count will be ignored. [...] java.lang.Exception: Stack constructor [...]"
 
https://pastebin.com/raw/6qvTwY6G

### Expected Behavior

Flint should be delivered with no error.

### Reproduction Steps

1. Have a fletcher
2. Use a postbox
3. Have no flint in warehouse
4. Request 64 flint

### Logs

https://pastebin.com/raw/6qvTwY6G

### Anything else?

_No response_

### Footer

---
 ## Viewers
  *  Add a 👍 reaction to the bug report if you are also affected. This helps the bug report become more visible without cluttering the comments.
  *  ⚠️ Only add a comment if you have new insights or background information not already mentioned. Off-topic or "+1" comments will be deleted to keep the discussion focused.

### PR DESCRIPTION
**Pull request by uecasm**
Closes #11300

# Changes proposed in this pull request
- Makes the crusher produce flint from crushing gravel, not crushing cobble.
- Simplifies AI request logic and fix sync logic not accounting for existing items correctly.
    - Probably not thoroughly tested, but seems sane.
    - In particular this replaces a check for "has any amount of the item -> request none" with "has some amount -> request enough to top off".
- Ensure persisted and otherwise `ItemStorage` uses unit stacks to avoid request warnings.

## Testing
- [x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please (needs selective porting)

### CODE REVIEW

**Review by Raycoms — DISMISSED** [review]

File: src/main/java/com/minecolonies/api/crafting/ItemStorage.java [hunk 1]
```diff
@@ -46,7 +47,7 @@ public class ItemStorage
      */
     public ItemStorage(@NotNull final ItemStack stack, final int amount, final boolean ignoreDamageValue)
     {
-        this.stack = stack;
+        this.stack = stack.copyWithCount(1);
```
Comment (someaddons) [inline src/main/java/com/minecolonies/api/crafting/ItemStorage.java]: we probably should clean up the callsites which are making unnecessary copies then

Comment (Raycoms) [reply src/main/java/com/minecolonies/api/crafting/ItemStorage.java]: I had overlooked this, I'm not so sure we should do a copy on new ItemStorage always. We often do a quick wrap to get a hashable object in a loop so this would be terrible performance wise.

Comment (uecasm) [reply src/main/java/com/minecolonies/api/crafting/ItemStorage.java]: It does seem safer to do a copy regardless, to ensure it's disconnected from an inventory stack that might be modified later.  Though if we're not worried about that I could make it only do this if the count > 1.

Comment (Raycoms) [reply src/main/java/com/minecolonies/api/crafting/ItemStorage.java]: Sometimes we use this just for the hashing, without permanent storage. E.g.
if map contains (new ItemStorage(stack)), count doesn't matter here, as we just are doing a temp contains check. Don't need to copy and set to 1 for this.

Comment (uecasm) [reply src/main/java/com/minecolonies/api/crafting/ItemStorage.java]: Hmm, ok, I've removed those.  Haven't tested it since my test colony doesn't have the problematic recipe persisted any more, but I believe it should still work.

**Review by someaddons — APPROVED** [review]

**Comment by Raycoms** [comment]
Please make port PR
