### PR TITLE
Fix builder and miner problems when chunks are unloaded + more

### LINKED ISSUE #518: Miner gets stuck at bottom of ladder
### Minecolonies version

version: universal-1.11-0.6.2464

### Expected behavior

- Miner should step out of ladder when mining new shaft at a certain node

### Actual behaviour

- Miner mines when on ladder thus sliding down to the bottom

### Steps to reproduce the problem

1. Build a miner hut
2. Let miner create all the nodes, and create shafts at the bottom most node
3. Tell miner to create shaft in the node above the bottom most node

### PR DESCRIPTION
**Pull request by Raycoms**
Fix error in the proxy. Make worker not move while turning

Closes #518 and maybe a view more

# Changes proposed in this pull request:
- correctly Reset state after unload
- Correctly path to miner level
- Remove unnecessary retrieve

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 1]
```diff
@@ -522,6 +527,19 @@ private boolean checkIfCanceled()
             currentStructure = null;
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: This method seems like something that should just be overridable instead of a bunch of instanceof sections

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 2]
```diff
@@ -834,6 +852,10 @@ private AIState startBuilding()
     {
         if (currentStructure == null)
         {
+            if(job instanceof JobBuilder && ((JobBuilder) job).getWorkOrder() != null)
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: Make an overridable onStartedBuildingWithoutStructure method or something

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 3]
```diff
@@ -1236,6 +1258,16 @@ private BlockPos getNodeMiningPosition(BlockPos blockToMine)
...
                 return blockToMine;
             }
+            final Point2D parentPos = buildingMiner.getCurrentLevel().getRandomNode().getParent();
+            if(parentPos != null && buildingMiner.getCurrentLevel().getNode(parentPos) != null
+                    && buildingMiner.getCurrentLevel().getNode(parentPos).getStyle() == Node.NodeType.SHAFT)
+            {
+                final BlockPos ladderPos = buildingMiner.getLadderLocation();
+                return new BlockPos(
+                        ladderPos.getX() + buildingMiner.getVectorX() * OTHER_SIDE_OF_SHAFT
+                        , buildingMiner.getCurrentLevel().getDepth()
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: Why are we doing this stupid thing with the commas? They always go end the end of the line when splitting?

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 1 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: Probably better yes

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 2 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: Done

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 3 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: changed but I'm afraid sonar will be unhappy.

Comment (cltnschlosser) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: This one wasn't chnaged

**Comment by marvin-bitterlich** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/559/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)
