### PR TITLE
Ai fixes

### LINKED ISSUE #9057: [BUG] Smelter broken - only breaks 1 ore block then complains, in loop.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.3

### MineColonies Version

minecolonies-1.19.4-1.0.1342-ALPHA

### Structurize Version

structurize-1.19.4-1.0.489-ALPHA

### Related Mods and their Versions

1. forge-1.19.4-45.0.42
2. blockui-1.19.4-0.0.73-ALPHA
3. domum_ornamentum-1.19.4-1.0.88-ALPHA-universal
4. jei-1.19.4-forge-13.1.0.2
5. journeymap-1.19.4-5.9.5-forge
6. multipiston-1.19.3-1.2.26-ALPHA

### Current Behavior

-Smelter will break 1 ore block, then complain it has no ores, so will take the single raw ore it made and goes to smelt it. Once it's made an ingot, it will grab it, store it, call for pickup, then repeat.

If you turn off the raw ore smelting, to make him break down all the ores first this will happen:

-Smelter breaks down 1 ore block, then complains it needs ores, then stops complaining, complains again, stops, breaks one ore block, then complains... repeat forever.

-The inventory is full of ore blocks to break
-All ores are turned on in the smelter panel

### Expected Behavior

-Smelter will break down all the ores blocks
-Smelter will then take the raw ores and go smelt them in batch

### Reproduction Steps

1. Make smelter
2. Hire smelter
3. set fuel and give them some
4. Place stacks of ore block (not raw ores)
5. (Optional) Disable all the raw ore smelting in the smelter panel for 2nd behavior.

### Logs

[latest.log](https://github.com/ldtteam/minecolonies/files/11175901/latest.log)

### Anything else?

https://www.youtube.com/watch?v=2DAMFYtLeLQ

Here's a quick video of the behavior after raw ores have been turned off to only make him break the ore blocks first.

When I did a colony in 1.19.3, the smelter acted normally and not like this, it would break all the ores, then smelt the stacks after.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #9081: [BUG] No XP Study delay in Library under certain conditions
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1283-ALPHA

### Structurize Version

1.0.483-ALPHA

### Related Mods and their Versions

_No response_

### Current Behavior

I asked in the discord about this because I am NOT actually using the current version as I play on a server and didn't want to inconvenience my fellow players, however when diving into the code I found the problem (possibly) in the main branch and wanted to bring it to someone's attention.
image

I noticed that my library workers would just pace back and forth from the bookshelf to the hut block never stopping. Later I had a new worker who was just standing at the bookshelf and I heard the page turning sound I hadn't heard before.

This got me intrigued because the bookshelf guy was gaining xp at a much slower rate then the rest of my colony had.
The only difference I could see was that the slow guy had books and paper. I gave books and paper to the other guy and he started doing the same thing. When I took them away he went for his rapid pacing again.

Upon diving in to the code I found the section for the study AI and I believe I've found the solution.

I'm never done a contribution before and when I clicked "make pull request" it said to submit an issue first so here it is. The fix is just moving one line which I show here on my forked repo:
https://github.com/mrlamb/minecolonies/commit/ebd1b138a087827fe254f9507077145b6d9edacd

Essentially the study method awards the xp, looks if the library has any study items, moves to the hut and then returns the function without ever grabbing the items, so the loop just keeps happening for rapid xp gain.

### Expected Behavior

I expect library workers to stand around at the bookshelf for STUDY_DELAY time before doing another pass.

### Reproduction Steps

1. Build Library
2. Assign Workers
3. Place study items in the hut inventory
4. manually give study items to one guy
5. (for most consistent reproduction) give some non study item to second guy
6. after a short time second guy will start running back and forth getting level up after level up

### Logs

https://gist.github.com/mrlamb/e0d8a67c24587a61f96b934b4b59cc1c

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #9111: [BUG] Colonists dying of fall damage outside level 5 residence
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1351

### Structurize Version

1.0.472

### Related Mods and their Versions

_No response_

### Current Behavior

Colonists seem to be mysteriously dying of fall damage outside this specific level 5 residence. This is the second time its happened and I have no clue as to why this is happening. I haven't noticed this with any other residences other than this one, but it seems to be rare.

### Expected Behavior

Colonists should not be falling to their death randomly

### Reproduction Steps

Build level 5 Minecolonies style residence
Wait for colonist to die of fall damage

### Logs

https://pastebin.com/hqd4aS3e

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #9125: [BUG] Flowers Tab GUI is empty in the Apiary building
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.4

### MineColonies Version

minecolonies-1.19.4-1.0.1401-ALPHA

### Structurize Version

structurize-1.19.4-1.0.489-ALPHA

### Related Mods and their Versions

1. Forge Version: Forge 1.19.4 45.0.57
2. BlockUI Version: blockui-1.19.4-0.0.73-ALPHA
3. Domum Ornamentum Version: domum_ornamentum-1.19.4-1.0.88-ALPHA-universal

### Current Behavior

Flowers Tab GUI is empty in the Apiary building block.s

### Expected Behavior

Flowers Tab GUI appears in the Apiary building block.

### Reproduction Steps

1. Launch Minecraft with the mods
2. Select Multiplayer
3. Join a server with the minecolonie mod
4. Proceed until you have an Apiary
5. Select the Flowers Tab and Observe the Issue

### Logs

https://gist.github.com/xarkore/d956b7a0b09e16eaa644d9201d4258ed

### Anything else?

image

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #9081
Closes #9057
Closes #9111
Closes #9125

# Changes proposed in this pull request:
- Make smelter break multiple batches
- Make Library students properly handle the pickup
- Fix crafter random pathing
- Fix citizens teleporting outside into mid-air

Review please

### CODE REVIEW

**Review by marchermans — DISMISSED** [review]

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/smelter/EntityAIWorkSmelter.java [hunk 1]
```diff
@@ -64,9 +64,56 @@ public class EntityAIWorkSmelter extends AbstractEntityAIUsesFurnace<JobSmelter,
...
+            worker.decreaseSaturationForContinuousAction();
+            worker.getCitizenExperienceHandler().addExperience(0.2);
+        }
+
+        Network.getNetwork()
+          .sendToTrackingEntity(new LocalizedParticleEffectMessage(inputItem, building.getID()), worker);
+        Network.getNetwork()
+          .sendToTrackingEntity(new LocalizedParticleEffectMessage(inputItem, building.getID().below()), worker);
+
+        worker.swing(InteractionHand.MAIN_HAND);
```
Comment (uecasm) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/smelter/EntityAIWorkSmelter.java:112]: Might be useful to put at least the ore block and possibly also a pick in their hands, just for feedback purposes.  (Even if the pick is a purely imaginary one, since they don't actually use it... unless maybe they should.)

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/smelter/EntityAIWorkSmelter.java:112]: yeah, as they dont actually use the pick, I didnt want to put anything in their hand they dont have in their inventory.

Comment (MotionlessTrain) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/smelter/EntityAIWorkSmelter.java:112]: Not sure if it should be required that they actually should use a pickaxe. Would that mean that the players would need to enchant it with Fortune I - Fortune IV for level 2 - 5? And would they need to give a diamond pickaxe to a level 1 smeltery as well (even though that is not in line with the tool material requirements for level 1)?

Comment (uecasm) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/smelter/EntityAIWorkSmelter.java:112]: No, even if we do require a pick it's easy enough to just pretend that it's enchanted, similar to how we currently do it.
But it doesn't seem like a silly idea to require a level-appropriate pick that takes durability damage as they work, as a cost of work similar to the log stripping.  (And could even be done mostly automatically with that existing code.  I think that even takes care of the tool request?  Though I'm not completely sure about that.)

Though I wasn't even really suggesting that, just something visual -- similar to how the sifter shows what they're currently working on.

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/smelter/EntityAIWorkSmelter.java:112]: As the items currently stay in the hut inventory I guess its fine to not hold it and just show the particles. Else it would require bigger changes then.

Comment (uecasm) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/smelter/EntityAIWorkSmelter.java:112]: They stay in the hut inventory for the sifter, too.  It's just to give the player some idea of what they're doing.  And it's like two lines of code 😛

File: src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java [hunk 2]
```diff
@@ -941,24 +963,22 @@ private void discoverModCompat()
...
     {
-        Set<ItemStorage> flowers = new HashSet<>();
-
-        for (final Item item : ForgeRegistries.ITEMS.tags().getTag(ItemTags.FLOWERS))
+        if (flowers.isEmpty())
         {
-            final NonNullList<ItemStack> list = NonNullList.create();
-            item.fillItemCategory(CreativeModeTab.TAB_SEARCH, list);
-            for (final ItemStack stack : list)
+            for (final Item item : ForgeRegistries.ITEMS.tags().getTag(ItemTags.FLOWERS))
```
Comment (someaddons) [inline src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java:974]: could you use the `allItems` List instead of refilling a creative tab here? since we already do that for all items

File: src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java [hunk 3]
```diff
@@ -447,6 +462,13 @@ public Set<ItemStorage> getCopyOfPlantables()
         return new HashSet<>(plantables);
     }
 
+    @Override
+    public Set<ItemStorage> getCopyOfFlowers()
+    {
+        if (flowers.isEmpty()) Log.getLogger().error("getCopyOfFlowers when empty");
+        return new HashSet<>(flowers);
```
Comment (someaddons) [inline src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java]: Use immutable collection instead of returning a copy

File: src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java (hunk 2 above)
Comment (Raycoms) [reply src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java:974]: This is still more efficient, as this just uses the sublist of items that are already tagged. Not ALL

File: src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java (hunk 3 above)
Comment (Raycoms) [reply src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java]: Should be a part of a bigger rework. We partially use the copies filter them down etc, so would have to be very careful. The methods are called "getCopy" on purpose atm.

Comment (someaddons) [reply src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java]: don't think we should keep repeating bad behaviour though :D the bigger rework is unlikely to ever happen

**Review by someaddons — APPROVED** [review]

**Review by someaddons — APPROVED** [review]

**Review by someaddons — APPROVED** [review]
