### PR TITLE
1.10 changes to delete colony command

### LINKED ISSUE #1632: Add parameter to colony deletion to keep structures
I'd like to be able to keep the structures I've built with Mine Colonies, even when my colony gets corrupted and I need to delete it. I'd be able to continue to live out of those buildings. I could then place the schematics over top and start my colony right back where I was once issues are resolved.

### Minecolonies version

version Any

### Expected behavior

- Optionally, colony buildings aren't removed when colony is deleted

### Actual behaviour

- Colony buildings are removed when colony is deleted

### Steps to reproduce the problem

1. Create town hall
2. Delete colony
3. ...
4. Profit

### PR DESCRIPTION
**Pull request by RVOtakuMike**
Attempts to close #1632

# Changes proposed in this pull request:
- Attempts to make "/minecolonies colony delete <id>" accept true/false to prevent removing buildings.

Assistance please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/commands/generalcommands/CheckForAutoDeletesCommand.java [hunk 1]
```diff
@@ -76,8 +76,8 @@ else if (sender instanceof TileEntity)
             {
                 sender.sendMessage(new TextComponentString("Successful"));
                 for (final Colony col : coloniesToDelete)
-                {
-                    server.addScheduledTask(() -> ColonyManager.deleteColony(col.getID()));
+                {//TODO: bugcheck
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/generalcommands/CheckForAutoDeletesCommand.java:79]: MINOR Move this trailing comment on the previous empty line. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3ATrailingCommentCheck)
INFO Complete the task associated to this TODO comment. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/coremod/colony/ColonyManager.java [hunk 2]
```diff
@@ -174,23 +174,22 @@ public static void deleteColony(final int id)
                     colonyWorlds.add(world);
                 }
             }
-            Log.getLogger().info("Removing buildings for " + id);
-            for (final AbstractBuilding building : new ArrayList<>(colony.getBuildings().values()))
-            {
+
+            if (canDelete = true) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/ColonyManager.java:178]: MAJOR Extract the assignment out of this expression. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AAssignmentInSubExpressionCheck)
MAJOR Remove this useless assignment to local variable "canDelete". [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1854)
MINOR Move this left curly brace to the beginning of next line of code. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR Introduce a new variable instead of reusing the parameter "canDelete". [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1226)

File: src/main/java/com/minecolonies/coremod/colony/ColonyManager.java [hunk 3]
```diff
@@ -174,23 +174,22 @@ public static void deleteColony(final int id)
...
+                Log.getLogger().info("Removing buildings for " + id);
+                for (final AbstractBuilding building : new ArrayList<>(colony.getBuildings().values())) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/ColonyManager.java:180]: MINOR Move this left curly brace to the beginning of next line of code. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

File: src/main/java/com/minecolonies/coremod/colony/ColonyManager.java [hunk 4]
```diff
@@ -174,23 +174,22 @@ public static void deleteColony(final int id)
...
                 final BlockPos location = building.getLocation();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/ColonyManager.java:181]: MINOR Make this line start at column 21. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AIndentationCheck)

File: src/main/java/com/minecolonies/coremod/colony/ColonyManager.java [hunk 5]
```diff
@@ -174,23 +174,22 @@ public static void deleteColony(final int id)
...
                 Log.getLogger().info("Delete Building at " + location);
                 building.deconstruct();
                 building.destroy();
-                for (final World world : colonyWorlds)
-                {
-                    if (world.getBlockState(location).getBlock() instanceof AbstractBlockHut)
-                    {
+                for (final World world : colonyWorlds) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/ColonyManager.java:185]: MINOR Move this left curly brace to the beginning of next line of code. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

File: src/main/java/com/minecolonies/coremod/colony/ColonyManager.java [hunk 6]
```diff
@@ -174,23 +174,22 @@ public static void deleteColony(final int id)
...
+                    if (world.getBlockState(location).getBlock() instanceof AbstractBlockHut) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/ColonyManager.java:186]: MINOR Move this left curly brace to the beginning of next line of code. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR Make this line start at column 25. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AIndentationCheck)

File: src/main/java/com/minecolonies/coremod/colony/ColonyManager.java [hunk 7]
```diff
@@ -174,23 +174,22 @@ public static void deleteColony(final int id)
...
                         Log.getLogger().info("Found Block, deleting " + world.getBlockState(location).getBlock());
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/ColonyManager.java:187]: MINOR Make this line start at column 29. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AIndentationCheck)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 47 issues
* ![MAJOR][MAJOR] 4 major
* ![MINOR][MINOR] 42 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ColonyManager.java#L41](https://github.com/Minecolonies/minecolonies/blob/e20428fc32fc095929be517a75ce3ad249b7ce3b/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L41): class "ColonyManager" has 50 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ColonyManager.java#L602](https://github.com/Minecolonies/minecolonies/blob/e20428fc32fc095929be517a75ce3ad249b7ce3b/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L602): Either log or rethrow this exception. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1166)
1. ![MINOR][MINOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/e20428fc32fc095929be517a75ce3ad249b7ce3b/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/e20428fc32fc095929be517a75ce3ad249b7ce3b/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render#](https://github.com/Minecolonies/minecolonies/blob/e20428fc32fc095929be517a75ce3ad249b7ce3b/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/e20428fc32fc095929be517a75ce3ad249b7ce3b/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [ColonyManager.java#L604](https://github.com/Minecolonies/minecolonies/blob/e20428fc32fc095929be517a75ce3ad249b7ce3b/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L604): Use a logger to log this exception. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1148)
1. ![MINOR][MINOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/e20428fc32fc095929be517a75ce3ad249b7ce3b/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions#](https://github.com/Minecolonies/minecolonies/blob/e20428fc32fc095929be517a75ce3ad249b7ce3b/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [requestsystem#](https://github.com/Minecolonies/minecolonies/blob/e20428fc32fc095929be517a75ce3ad249b7ce3b/src/main/java/com/minecolonies/coremod/colony/requestsystem#): Add a 'package-info.java' file to document the 'requestsystem' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
