### PR TITLE
Fix tooltip

### LINKED ISSUE #1636: Mouse-over not working in shelving-chest
### Minecolonies version

version 1.12.2-0.8.4802 or curse 7.5.6522.42411

### Expected behavior

When the mouse points at an item in the shelving unit or your inventory while the shelf is open, the name of the item you are pointing at should pop up like in the normal chests.

### Actual behaviour

You point - nothing pops up. You then have to guess whether that is dark oak or spruce etc.

### Steps to reproduce the problem

1. Make a warehouse with shelves
2. Drop in some objects
3. Hover the mouse over them and wait for the description, give up
4. Compare with a normal chest

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #1636

# Changes proposed in this pull request:
- Fixes tooltips

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/achievements/package-info.java [hunk 1]
```diff
@@ -3,8 +3,7 @@
  * <p>
  * Contains a subclass of:
  * <p>
- * - {@link net.minecraft.stats.Achievement}
- * - {@link net.minecraftforge.common.AchievementPage}
+//todo fill in as soon as existent
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/achievements/package-info.java]: INFO Complete the task associated to this TODO comment. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/locations/EntityLocation.java [hunk 2]
```diff
@@ -0,0 +1,179 @@
...
+     * @return True when reachable, false when not.
+     */
+    @Override
+    public boolean isReachableFromLocation(@NotNull final ILocation location)
+    {
+        checkEntity();
+        return !(entity == null || entity.get() == null) && location.getDimension() == getDimension();
+    }
+
+    @SuppressWarnings("squid:S2972")
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/locations/EntityLocation.java]: INFO Suppressing the 'squid:S2972' warning is not allowed [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1309)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/locations/EntityLocation.java [hunk 3]
```diff
@@ -0,0 +1,179 @@
...
+         * Moving the curly braces really makes the code hard to read.
+         */
+        public TypeToken<EntityLocation> getFactoryOutputType()
+        {
+            return new TypeToken<EntityLocation>() {};
+        }
+
+        @NotNull
+        @Override
+        @SuppressWarnings("squid:LeftCurlyBraceStartLineCheck")
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/locations/EntityLocation.java]: INFO Suppressing the 'squid:LeftCurlyBraceStartLineCheck' warning is not allowed [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1309)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/locations/EntityLocation.java [hunk 4]
```diff
@@ -0,0 +1,179 @@
...
+    {
+
+        ////// --------------------------- NBTConstants --------------------------- \\\\\\
+        private static final String NBT_MSB = "Id_MSB";
+        private static final String NBT_LSB = "Id_LSB";
+        ////// --------------------------- NBTConstants --------------------------- \\\\\\
+
+        @NotNull
+        @Override
+        @SuppressWarnings("squid:LeftCurlyBraceStartLineCheck")
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/locations/EntityLocation.java]: INFO Suppressing the 'squid:LeftCurlyBraceStartLineCheck' warning is not allowed [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1309)

File: src/main/java/com/minecolonies/coremod/achievements/MineColoniesAchievementPage.java [hunk 5]
```diff
@@ -10,17 +9,177 @@
...
+     * @param achievementMinerDeathLava
+     * @param achievementMinerDeathFall
+     * @param achievementLumberjackDeathTree
+     * @param achievementFisherDeathGuardian
+     * @param achievementGuardDeathEnderman
+     * @param achievementPlayerDeathGuard
      * @param achievements A list of achievements to display
      */
-    public MineColoniesAchievementPage(final String name, final Achievement... achievements)
+    public MineColoniesAchievementPage(
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/achievements/MineColoniesAchievementPage.java]: MAJOR Constructor has 81 parameters, which is greater than 10 authorized. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS00107)

File: src/main/java/com/minecolonies/coremod/achievements/MineColoniesAchievementPage.java [hunk 6]
```diff
@@ -10,17 +9,177 @@
...
+            final MineColoniesAchievement achievementMinerDeathLava,
+            final MineColoniesAchievement achievementMinerDeathFall,
+            final MineColoniesAchievement achievementLumberjackDeathTree,
+            final MineColoniesAchievement achievementFisherDeathGuardian,
+            final MineColoniesAchievement achievementGuardDeathEnderman,
+            final MineColoniesAchievement achievementPlayerDeathGuard,
+            final Advancement... achievements)
     {
-        super(name, achievements);
+        //todo will have to call super
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/achievements/MineColoniesAchievementPage.java]: INFO Complete the task associated to this TODO comment. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/coremod/achievements/MineColoniesAchievementPage.java [hunk 7]
```diff
@@ -10,17 +9,177 @@
  *
  * @since 0.2
  */
-public class MineColoniesAchievementPage extends AchievementPage
+public class MineColoniesAchievementPage
 {
+    //todo have to extend advancement at some point
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/achievements/MineColoniesAchievementPage.java]: INFO Complete the task associated to this TODO comment. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRangeGuard.java [hunk 8]
```diff
@@ -179,24 +189,38 @@ protected AIState searchTarget()
      */
     protected AIState huntDown()
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRangeGuard.java]: MAJOR Reduce the number of returns of this method 7, down to the maximum allowed 6. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1142)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRangeGuard.java [hunk 9]
```diff
@@ -256,6 +280,12 @@ public void attackEntityWithRangedAttack(@NotNull final EntityLivingBase entityT
         worker.damageItemInHand(1);
     }
 
+    @Override
+    public void setSwingingArms(final boolean swingingArms)
+    {
+        //todo
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRangeGuard.java]: INFO Complete the task associated to this TODO comment. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/coremod/blocks/BlockWaypoint.java [hunk 10]
```diff
@@ -0,0 +1,120 @@
...
+        return false;
+    }
+
+    /**
+     * @deprecated (Remove this as soon as minecraft offers anything better).
+     */
+    @SuppressWarnings(DEPRECATION)
+    @Override
+    @Deprecated
+    public boolean isFullBlock(final IBlockState state)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockWaypoint.java]: INFO Do not forget to remove this deprecated code someday. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1133)

File: src/main/java/com/minecolonies/coremod/blocks/BlockWaypoint.java [hunk 11]
```diff
@@ -0,0 +1,120 @@
...
+    }
+
+    /**
+     * Used to determine ambient occlusion and culling when rebuilding chunks
+     * for render.
+     * @deprecated
+     *
+     * @return true
+     */
+    //todo: remove once we no longer need to support this
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockWaypoint.java]: INFO Complete the task associated to this TODO comment. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/coremod/blocks/BlockWaypoint.java [hunk 12]
```diff
@@ -0,0 +1,120 @@
...
+import com.minecolonies.coremod.creativetab.ModCreativeTabs;
+import net.minecraft.block.Block;
+import net.minecraft.block.material.Material;
+import net.minecraft.block.state.IBlockState;
+import net.minecraft.item.Item;
+import net.minecraft.item.ItemBlock;
+import net.minecraft.util.EnumFacing;
+import net.minecraft.util.math.BlockPos;
+import net.minecraft.world.IBlockAccess;
+import net.minecraftforge.fml.common.registry.GameRegistry;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockWaypoint.java]: MINOR Remove this unused import 'net.minecraftforge.fml.common.registry.GameRegistry'. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/blocks/BlockWaypoint.java [hunk 13]
```diff
@@ -0,0 +1,120 @@
...
+     * for render.
+     * @deprecated
+     *
+     * @return true
+     */
+    //todo: remove once we no longer need to support this
+    @SuppressWarnings(DEPRECATION)
+    @Override
+    @Deprecated
+    public boolean isOpaqueCube(final IBlockState state)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockWaypoint.java]: INFO Do not forget to remove this deprecated code someday. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1133)

File: src/main/java/com/minecolonies/coremod/blocks/BlockHutLumberjack.java [hunk 14]
```diff
@@ -1,5 +1,7 @@
 package com.minecolonies.coremod.blocks;
 
+import net.minecraft.block.Block;
+import net.minecraftforge.registries.IForgeRegistry;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockHutLumberjack.java]: MINOR Remove this unused import 'net.minecraftforge.registries.IForgeRegistry'. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/requests/AbstractRequest.java [hunk 15]
```diff
@@ -0,0 +1,407 @@
...
+    private final List<IToken> children;
+    @NotNull
+    private final IRequester   requester;
+    @NotNull
+    private RequestState state = RequestState.CREATED;
+    @Nullable
+    private R      result;
+    @Nullable
+    private IToken parent;
+    @SuppressWarnings("squid:S1170")
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/requests/AbstractRequest.java]: INFO Suppressing the 'squid:S1170' warning is not allowed [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1309)

File: src/main/java/com/minecolonies/coremod/blocks/BlockHutCitizen.java [hunk 16]
```diff
@@ -1,5 +1,7 @@
 package com.minecolonies.coremod.blocks;
 
+import net.minecraft.block.Block;
+import net.minecraftforge.registries.IForgeRegistry;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockHutCitizen.java]: MINOR Remove this unused import 'net.minecraftforge.registries.IForgeRegistry'. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAICitizenWander.java [hunk 17]
```diff
@@ -70,7 +68,7 @@ public boolean shouldExecute()
      */
     private boolean isToOld()
     {
-        return citizen.getAge() >= 100;
+        return citizen.getGrowingAge() >= 100;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAICitizenWander.java]: MAJOR Assign this magic number 100 to a well-named constant, and use the constant instead. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/achievements/MineColoniesAchievement.java [hunk 18]
```diff
@@ -13,35 +13,33 @@
  *
  * @since 0.2
  */
-public class MineColoniesAchievement extends Achievement
+public class MineColoniesAchievement
 {
-
+    //todo this will make new advancements at some point
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/achievements/MineColoniesAchievement.java]: INFO Complete the task associated to this TODO comment. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/coremod/achievements/MineColoniesAchievement.java [hunk 19]
```diff
@@ -53,8 +51,8 @@ public MineColoniesAchievement(final String id, final int offsetX, final int off
      * @param itemStackIcon The icon to show
      * @param parent        the parent achievement
      */
-    public MineColoniesAchievement(final String id, final int offsetX, final int offsetY, final ItemStack itemStackIcon, final Achievement parent)
+    public MineColoniesAchievement(final String id, final int offsetX, final int offsetY, final ItemStack itemStackIcon, final Advancement parent)
     {
-        super(Constants.MOD_ID + "." + id, id, offsetX, offsetY, itemStackIcon, parent);
+        //super(Constants.MOD_ID + "." + id, id, offsetX, offsetY, itemStackIcon, parent);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/achievements/MineColoniesAchievement.java]: MINOR This block of commented-out lines of code should be removed. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

File: src/main/java/com/minecolonies/coremod/achievements/MineColoniesAchievement.java [hunk 20]
```diff
@@ -13,35 +13,33 @@
...
      * @param offsetX   X position placement on the board
      * @param offsetY   Y position placement on the board
      * @param blockIcon The icon to show
      * @param parent    the parent achievement
      */
-    public MineColoniesAchievement(final String id, final int offsetX, final int offsetY, final Block blockIcon, final Achievement parent)
+    public MineColoniesAchievement(final String id, final int offsetX, final int offsetY, final Item blockIcon, final MineColoniesAchievement parent)
     {
-        super(Constants.MOD_ID + "." + id, id, offsetX, offsetY, blockIcon, parent);
+        //super(Constants.MOD_ID + "." + id, id, offsetX, offsetY, blockIcon, parent);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/achievements/MineColoniesAchievement.java]: MINOR This block of commented-out lines of code should be removed. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

File: src/main/java/com/minecolonies/coremod/achievements/MineColoniesAchievement.java [hunk 21]
```diff
@@ -13,35 +13,33 @@
...
      * @param offsetX  X position placement on the board
      * @param offsetY  Y position placement on the board
      * @param itemIcon The icon to show
      * @param parent   the parent achievement
      */
-    public MineColoniesAchievement(final String id, final int offsetX, final int offsetY, final Item itemIcon, final Achievement parent)
+    public MineColoniesAchievement(final String id, final int offsetX, final int offsetY, final Block itemIcon, final MineColoniesAchievement parent)
     {
-        super(Constants.MOD_ID + "." + id, id, offsetX, offsetY, itemIcon, parent);
+        //super(Constants.MOD_ID + "." + id, id, offsetX, offsetY, itemIcon, parent);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/achievements/MineColoniesAchievement.java]: MINOR This block of commented-out lines of code should be removed. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

File: src/main/java/com/minecolonies/coremod/blocks/BlockHutBuilder.java [hunk 22]
```diff
@@ -1,5 +1,7 @@
 package com.minecolonies.coremod.blocks;
 
+import net.minecraft.block.Block;
+import net.minecraftforge.registries.IForgeRegistry;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/BlockHutBuilder.java]: MINOR Remove this unused import 'net.minecraftforge.registries.IForgeRegistry'. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java [hunk 23]
```diff
@@ -1,44 +1,115 @@
...
 import net.minecraft.block.Block;
+import net.minecraft.item.Item;
+import net.minecraftforge.registries.IForgeRegistry;
 
 /**
  * Class to create the modBlocks.
  * References to the blocks can be made here
  */
-public final class ModBlocks
+public class ModBlocks
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java]: MAJOR Refactor this class so it has no more than 20 public fields, rather than the 24 it currently has. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1820)
MINOR Make this class "final" or add a public constructor. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS2974)

File: src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java [hunk 24]
```diff
@@ -1,44 +1,115 @@
...
-    public static final Block blockHutFarmer              = new BlockHutFarmer();
-    public static final Block blockHutFisherman           = new BlockHutFisherman();
-    public static final Block blockSubstitution           = new BlockSubstitution();
-    public static final Block blockSolidSubstitution      = new BlockSolidSubstitution();
-    public static final Block blockHutField               = new BlockHutField();
-    public static final Block blockHutGuardTower          = new BlockHutGuardTower();
-    public static final Block blockHutWareHouse           = new BlockHutWareHouse();
-    public static final Block blockConstructionTape       = new BlockConstructionTape();
-    public static final Block blockConstructionTapeCorner = new BlockConstructionTapeCorner();
+    public static BlockHutTownHall            blockHutTownHall;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java]: MINOR Make this "public static blockHutTownHall" field final [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1444)
MINOR Make blockHutTownHall a static final constant or non-public and provide accessors if needed. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

File: src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java [hunk 25]
```diff
@@ -1,44 +1,115 @@
...
+    public static BlockHutCitizen             blockHutCitizen;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java]: MINOR Make this "public static blockHutCitizen" field final [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1444)
MINOR Make blockHutCitizen a static final constant or non-public and provide accessors if needed. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

File: src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java [hunk 26]
```diff
@@ -1,44 +1,115 @@
...
+    public static BlockHutMiner               blockHutMiner;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java]: MINOR Make this "public static blockHutMiner" field final [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1444)
MINOR Make blockHutMiner a static final constant or non-public and provide accessors if needed. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

File: src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java [hunk 27]
```diff
@@ -1,44 +1,115 @@
...
+    public static BlockHutLumberjack          blockHutLumberjack;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java]: MINOR Make this "public static blockHutLumberjack" field final [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1444)
MINOR Make blockHutLumberjack a static final constant or non-public and provide accessors if needed. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

File: src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java [hunk 28]
```diff
@@ -1,44 +1,115 @@
...
+    public static BlockHutBaker               blockHutBaker;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java]: MINOR Make this "public static blockHutBaker" field final [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1444)
MINOR Make blockHutBaker a static final constant or non-public and provide accessors if needed. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

File: src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java [hunk 29]
```diff
@@ -1,44 +1,115 @@
...
+    public static BlockHutBuilder             blockHutBuilder;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java]: MINOR Make this "public static blockHutBuilder" field final [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1444)
MINOR Make blockHutBuilder a static final constant or non-public and provide accessors if needed. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

File: src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java [hunk 30]
```diff
@@ -1,44 +1,115 @@
...
+    public static BlockHutDeliveryman         blockHutDeliveryman;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java]: MINOR Make this "public static blockHutDeliveryman" field final [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1444)
MINOR Make blockHutDeliveryman a static final constant or non-public and provide accessors if needed. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

File: src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java [hunk 31]
```diff
@@ -1,44 +1,115 @@
...
+    public static BlockHutBlacksmith          blockHutBlacksmith;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java]: MINOR Make this "public static blockHutBlacksmith" field final [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1444)
MINOR Make blockHutBlacksmith a static final constant or non-public and provide accessors if needed. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

File: src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java [hunk 32]
```diff
@@ -1,44 +1,115 @@
...
+    public static BlockHutStonemason          blockHutStonemason;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java]: MINOR Make this "public static blockHutStonemason" field final [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1444)
MINOR Make blockHutStonemason a static final constant or non-public and provide accessors if needed. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

File: src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java [hunk 33]
```diff
@@ -1,44 +1,115 @@
...
+    public static BlockHutFarmer              blockHutFarmer;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java]: MINOR Make this "public static blockHutFarmer" field final [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1444)
MINOR Make blockHutFarmer a static final constant or non-public and provide accessors if needed. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

File: src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java [hunk 34]
```diff
@@ -1,44 +1,115 @@
...
+    public static BlockHutFisherman           blockHutFisherman;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java]: MINOR Make this "public static blockHutFisherman" field final [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1444)
MINOR Make blockHutFisherman a static final constant or non-public and provide accessors if needed. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

File: src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java [hunk 35]
```diff
@@ -1,44 +1,115 @@
...
+    public static BlockSubstitution           blockSubstitution;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java]: MINOR Make this "public static blockSubstitution" field final [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1444)
MINOR Make blockSubstitution a static final constant or non-public and provide accessors if needed. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

File: src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java [hunk 36]
```diff
@@ -1,44 +1,115 @@
...
+    public static BlockSolidSubstitution      blockSolidSubstitution;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java]: MINOR Make this "public static blockSolidSubstitution" field final [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1444)
MINOR Make blockSolidSubstitution a static final constant or non-public and provide accessors if needed. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

**Review by marchermans — APPROVED** [review]
