### PR TITLE
improve gathering, improve javadoc, fix workers...

### LINKED ISSUE #1814: Farmer Not Working
### Minecolonies version

minecolonies-universal-1.12.2-0.8.5930

### Expected behavior

Farmer not work?

### Actual behaviour

he does not go to the field and do not plant fields

### LINKED ISSUE #1817: [1.12.2-0.8.5941] issue
Tested with:
minecolonies-universal-1.12.2-0.8.5941

Builder = stalled at request shovel as try build mine level 5 stone version. (its pretty much same as one from 5930)
https://puu.sh/yCPL0/598356adce.png
https://puu.sh/yCPKf/cc1f23e3f4.png

Farmer = Stalled in Prepare and farm plant loop (No Request) (wooden Hoe 64 x Seeds)
https://puu.sh/yCPSf/630e20384f.png
https://puu.sh/yCPSS/12fa7e6bea.png
Its Inventory and request:
https://puu.sh/yCPUx/ed97e31796.png
https://puu.sh/yCPVK/3820652775.png
EDIT: I might try trace it down and it seem that it try find the fields but it show no field in the list.
https://puu.sh/yCSDK/7e72381833.png
https://puu.sh/yCSE9/19277c94d3.png

fml-client-latest.log
https://hastebin.com/cikomajaqi.scala
latest.log
https://hastebin.com/teyameziwe.sql

### LINKED ISSUE #1819: Town Hall - GUI - Cosmetic
minecrat 1.12.2
mine colonies 8.5941

When you click on the town hall gui and then click on "information".  The # of cooks is missing from the gui.

### LINKED ISSUE #1823: Request gui - clicking on "fulfill"
mine craft 1.12.2
mine colonies 8.5941

Lets say. builder.

Builder is requesting an item Say a Bed.   You have 4 beds in your inventory.  You right click on builder and then click on request.  You then see he wants 1 bed.  you click on "FULFILL".   IT removed EVERY BED from your inventory and give it to him.   It doesn't just give what he asks for which is 1.

### PR DESCRIPTION
**Pull request by Raycoms**
Fixes not working workers, because of wrong javadoc (also fixed).
Also fixes problem with swords -> weapon.
Also let's the dman dump averagely every third gather trip if he doesn't find anything to gather.

Review please

Edit By Orion:
I fixed several bugs in the RS that caused it to behave stupidly when it was reassigning from the player request resolver (aka DMan dropoff). Also fixed a bug that caused it to do child to parent request updates twice, which caused some log spam hat no consequence for the player however.

Also edit by Orion:
The mentioned dumping logic is also adapted. The player can configure a minimal maximal amount of buildings between which a random amount is selected.

Again edit by Orion - In the name of @bob0bob
Thanks bob for the fixes! I fixed the farmer my self but pulled in al other changes.
Closes #1823
Closes #1819
Closes #1814
Closes #1817

### CODE REVIEW

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 70 issues
* ![MAJOR][MAJOR] 17 major
* ![MINOR][MINOR] 50 minor
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L55](https://github.com/Minecolonies/minecolonies/blob/0dfc65e45631566f0aefa8e53a1870e34471ef0d/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L55): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 31 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L55](https://github.com/Minecolonies/minecolonies/blob/0dfc65e45631566f0aefa8e53a1870e34471ef0d/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L55): class "AbstractEntityAIBasic" has 53 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L240](https://github.com/Minecolonies/minecolonies/blob/0dfc65e45631566f0aefa8e53a1870e34471ef0d/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L240): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L474](https://github.com/Minecolonies/minecolonies/blob/0dfc65e45631566f0aefa8e53a1870e34471ef0d/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L474): Refactor this method to reduce its Cognitive Complexity from 22 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L714](https://github.com/Minecolonies/minecolonies/blob/0dfc65e45631566f0aefa8e53a1870e34471ef0d/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L714): Remove this unused private "requestWithoutSpam" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [EntityAIWorkDeliveryman.java#L130](https://github.com/Minecolonies/minecolonies/blob/0dfc65e45631566f0aefa8e53a1870e34471ef0d/src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java#L130): Reduce the number of returns of this method 7, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [EntityAIWorkDeliveryman.java#L413](https://github.com/Minecolonies/minecolonies/blob/0dfc65e45631566f0aefa8e53a1870e34471ef0d/src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java#L413): Reduce the number of returns of this method 7, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [EntityAIWorkDeliveryman.java#L413](https://github.com/Minecolonies/minecolonies/blob/0dfc65e45631566f0aefa8e53a1870e34471ef0d/src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java#L413): The Cyclomatic Complexity of this method "deliver" is 19 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [EntityAIWorkDeliveryman.java#L413](https://github.com/Minecolonies/minecolonies/blob/0dfc65e45631566f0aefa8e53a1870e34471ef0d/src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java#L413): Refactor this method to reduce its Cognitive Complexity from 29 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [EntityAIWorkFisherman.java#L504](https://github.com/Minecolonies/minecolonies/blob/0dfc65e45631566f0aefa8e53a1870e34471ef0d/src/main/java/com/minecolonies/coremod/entity/ai/citizen/fisherman/EntityAIWorkFisherman.java#L504): Assign this magic number 0.5F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Asherslab** [comment]
Sounds good :shipit:

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1807/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/StandardPlayerRequestResolver.java [hunk 1]
```diff
@@ -119,7 +121,7 @@ public IRequest getFollowupRequestForCompletion(@NotNull final IRequestManager m
     @Override
     public IRequest onRequestCancelledOrOverruled(@NotNull final IRequestManager manager, @NotNull final IRequest request) throws IllegalArgumentException
     {
-        return null;
+        return getFollowupRequestForCompletion(manager, request);
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/StandardPlayerRequestResolver.java:124]: @Raycoms This is what was causing the bug. When i reassign i cancel the request. However the SPRR was not updating its internal dataset. The error only happened when and only when the DMan picked up a stack that was FINALLY assigned to the Player, since the SRRR does handle reassignments properly as it makes use of that functionality.

**Review by marchermans — APPROVED** [review]
I finally found the bug.

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java [hunk 2]
```diff
@@ -129,8 +132,20 @@ public EntityAIWorkDeliveryman(@NotNull final JobDeliveryman deliveryman)
...
+
         if (gatherTarget == null)
         {
+            if (gatherCount == maximalGatherCount)
+            {
+                maximalGatherCount = Configurations.requestSystem.minimalBuildingsToGather + worker.getRandom().nextInt(Math.max(1, Configurations.requestSystem.maximalBuildingsToGather - Configurations.requestSystem.minimalBuildingsToGather));
+                gatherCount = 0;
+                return DUMPING;
+            }
+
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java]: MAJOR Split this 244 characters long line (which is greater than 180 authorized). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00103)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java [hunk 3]
```diff
@@ -129,8 +132,20 @@ public EntityAIWorkDeliveryman(@NotNull final JobDeliveryman deliveryman)
      */
     public AIState gather()
     {
+        if (maximalGatherCount < 0)
+        {
+            maximalGatherCount = Configurations.requestSystem.minimalBuildingsToGather + worker.getRandom().nextInt(Math.max(1, Configurations.requestSystem.maximalBuildingsToGather - Configurations.requestSystem.minimalBuildingsToGather));
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java:137]: MAJOR Split this 240 characters long line (which is greater than 180 authorized). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00103)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java [hunk 4]
```diff
@@ -129,8 +132,20 @@ public EntityAIWorkDeliveryman(@NotNull final JobDeliveryman deliveryman)
...
+        }
+
         if (gatherTarget == null)
         {
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java]: MAJOR Split this 240 characters long line (which is greater than 180 authorized). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00103)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/StandardPlayerRequestResolver.java [hunk 5]
```diff
@@ -15,6 +16,7 @@
 import com.minecolonies.coremod.colony.Colony;
 import com.minecolonies.coremod.util.ServerUtils;
 import net.minecraft.entity.player.EntityPlayer;
+import net.minecraft.item.ItemStack;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/StandardPlayerRequestResolver.java:19]: MINOR Remove this unused import 'net.minecraft.item.ItemStack'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/StandardPlayerRequestResolver.java [hunk 6]
```diff
@@ -7,6 +7,7 @@
 import com.minecolonies.api.colony.requestsystem.location.ILocation;
 import com.minecolonies.api.colony.requestsystem.manager.IRequestManager;
 import com.minecolonies.api.colony.requestsystem.request.IRequest;
+import com.minecolonies.api.colony.requestsystem.requestable.IDeliverable;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/StandardPlayerRequestResolver.java:10]: MINOR Remove this unused import 'com.minecolonies.api.colony.requestsystem.requestable.IDeliverable'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/StandardPlayerRequestResolver.java [hunk 7]
```diff
@@ -119,7 +121,7 @@ public IRequest getFollowupRequestForCompletion(@NotNull final IRequestManager m
     @Override
     public IRequest onRequestCancelledOrOverruled(@NotNull final IRequestManager manager, @NotNull final IRequest request) throws IllegalArgumentException
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/StandardPlayerRequestResolver.java:122]: MINOR Remove the declaration of thrown exception 'java.lang.IllegalArgumentException' which is a runtime exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/init/StandardFactoryControllerInitializer.java [hunk 8]
```diff
@@ -39,7 +39,9 @@ public static void onPreInit()
         StandardFactoryController.getInstance().registerNewFactory(new DeliveryRequestResolverFactory());
         StandardFactoryController.getInstance().registerNewFactory(new WarehouseRequestResolverFactory());
         StandardFactoryController.getInstance().registerNewFactory(new BuildingRequestResolverFactory());
-        StandardFactoryController.getInstance().registerNewFactory(new PlayerRequestResolverFactory());
+        StandardFactoryController.getInstance().registerNewFactory(new StandardPlayerRequestResolverFactory());
         StandardFactoryController.getInstance().registerNewFactory(new StandardRetryingRequestResolverFactory());
+
+        StandardFactoryController.getInstance().registerNewClassRenaming("com.minecolonies.coremod.colony.requestsystem.resolvers.PlayerRequestResolver", "com.minecolonies.coremod.colony.requestsystem.resolvers.StandardPlayerRequestResolver");
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/init/StandardFactoryControllerInitializer.java:45]: MAJOR Split this 243 characters long line (which is greater than 180 authorized). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00103)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 113 issues
* ![CRITICAL][CRITICAL] 3 critical
* ![MAJOR][MAJOR] 30 major
* ![MINOR][MINOR] 76 minor
* ![INFO][INFO] 4 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [RequestHandler.java#L88](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L88): Add a default case to this switch. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ASwitchLastCaseIsDefaultCheck)
1. ![CRITICAL][CRITICAL] [AbstractRequest.java#L444](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/requests/AbstractRequest.java#L444): Missing curly brace. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00121)
1. ![CRITICAL][CRITICAL] [StandardPlayerRequestResolver.java#L157](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/StandardPlayerRequestResolver.java#L157): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![MAJOR][MAJOR] [RequestHandler.java#L29](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L29): Add a private constructor to hide the implicit public one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1118)
1. ![MAJOR][MAJOR] [RequestHandler.java#L114](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L114): Refactor this method to reduce its Cognitive Complexity from 36 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [RequestHandler.java#L143](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L143): Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS135)
1. ![MAJOR][MAJOR] [RequestHandler.java#L195](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L195): Merge this if statement with the enclosing one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1066)
1. ![MAJOR][MAJOR] [RequestHandler.java#L502](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L502): Remove this unused private "AssigningResult" constructor. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [RequestHandler.java#L516](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L516): Add parentheses to make the operator precedence explicit. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS864)
1. ![MAJOR][MAJOR] [AbstractRequest.java#L458](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/requests/AbstractRequest.java#L458): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java [hunk 9]
```diff
@@ -129,8 +132,20 @@ public EntityAIWorkDeliveryman(@NotNull final JobDeliveryman deliveryman)
...
+            if (gatherCount == maximalGatherCount)
+            {
+                maximalGatherCount = Configurations.requestSystem.minimalBuildingsToGather + worker.getRandom().nextInt(Math.max(1, Configurations.requestSystem.maximalBuildingsToGather - Configurations.requestSystem.minimalBuildingsToGather));
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java:144]: MAJOR Split this 244 characters long line (which is greater than 180 authorized). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00103)

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java [hunk 10]
```diff
@@ -129,8 +132,20 @@ public EntityAIWorkDeliveryman(@NotNull final JobDeliveryman deliveryman)
      */
     public AIState gather()
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java:133]: MAJOR Reduce the number of returns of this method 8, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 111 issues
* ![CRITICAL][CRITICAL] 3 critical
* ![MAJOR][MAJOR] 29 major
* ![MINOR][MINOR] 75 minor
* ![INFO][INFO] 4 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [RequestHandler.java#L88](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L88): Add a default case to this switch. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ASwitchLastCaseIsDefaultCheck)
1. ![CRITICAL][CRITICAL] [AbstractRequest.java#L444](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/requests/AbstractRequest.java#L444): Missing curly brace. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00121)
1. ![CRITICAL][CRITICAL] [StandardPlayerRequestResolver.java#L157](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/StandardPlayerRequestResolver.java#L157): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![MAJOR][MAJOR] [RequestHandler.java#L29](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L29): Add a private constructor to hide the implicit public one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1118)
1. ![MAJOR][MAJOR] [RequestHandler.java#L114](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L114): Refactor this method to reduce its Cognitive Complexity from 36 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [RequestHandler.java#L143](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L143): Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS135)
1. ![MAJOR][MAJOR] [RequestHandler.java#L195](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L195): Merge this if statement with the enclosing one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1066)
1. ![MAJOR][MAJOR] [RequestHandler.java#L502](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L502): Remove this unused private "AssigningResult" constructor. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [RequestHandler.java#L516](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L516): Add parentheses to make the operator precedence explicit. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS864)
1. ![MAJOR][MAJOR] [AbstractRequest.java#L458](https://github.com/Minecolonies/minecolonies/blob/f2c90cd03dfd8cc19e05c35d757d46a8a0f4bb36/src/main/java/com/minecolonies/coremod/colony/requestsystem/requests/AbstractRequest.java#L458): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java [hunk 11]
```diff
@@ -105,16 +96,7 @@ public boolean canResolve(
     public void resolve(
                          @NotNull final IRequestManager manager, @NotNull final IRequest<? extends IDeliverable> request) throws RuntimeException
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java:97]: MINOR Remove the declaration of thrown exception 'java.lang.RuntimeException' which is a runtime exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java [hunk 12]
```diff
@@ -130,6 +112,24 @@ public void resolve(
         manager.updateRequestState(request.getToken(), RequestState.COMPLETED);
     }
 
+    @NotNull
+    private AbstractBuilding getBuildingFromRequest(
+      @NotNull final IRequestManager manager, @NotNull final IRequest<? extends IDeliverable> request) throws RuntimeException
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java:117]: MAJOR Define and throw a dedicated exception instead of using a generic one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00112)
MINOR Remove the declaration of thrown exception 'java.lang.RuntimeException' which is a runtime exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 128 issues
* ![CRITICAL][CRITICAL] 7 critical
* ![MAJOR][MAJOR] 37 major
* ![MINOR][MINOR] 80 minor
* ![INFO][INFO] 4 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [WindowTownHall.java#L351](https://github.com/Minecolonies/minecolonies/blob/dec48d79742e95d17477b8543818f8d43bc83d6c/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L351): Use already-defined constant 'BUTTON_ACTIONS' instead of duplicating its value here. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [WindowTownHall.java#L698](https://github.com/Minecolonies/minecolonies/blob/dec48d79742e95d17477b8543818f8d43bc83d6c/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L698): Use already-defined constant 'BUTTON_TRIGGER' instead of duplicating its value here. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [RequestHandler.java#L88](https://github.com/Minecolonies/minecolonies/blob/dec48d79742e95d17477b8543818f8d43bc83d6c/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L88): Add a default case to this switch. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ASwitchLastCaseIsDefaultCheck)
1. ![CRITICAL][CRITICAL] [AbstractRequest.java#L444](https://github.com/Minecolonies/minecolonies/blob/dec48d79742e95d17477b8543818f8d43bc83d6c/src/main/java/com/minecolonies/coremod/colony/requestsystem/requests/AbstractRequest.java#L444): Missing curly brace. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00121)
1. ![CRITICAL][CRITICAL] [BuildingRequestResolver.java#L151](https://github.com/Minecolonies/minecolonies/blob/dec48d79742e95d17477b8543818f8d43bc83d6c/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java#L151): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![CRITICAL][CRITICAL] [BuildingRequestResolver.java#L158](https://github.com/Minecolonies/minecolonies/blob/dec48d79742e95d17477b8543818f8d43bc83d6c/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java#L158): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![CRITICAL][CRITICAL] [StandardPlayerRequestResolver.java#L157](https://github.com/Minecolonies/minecolonies/blob/dec48d79742e95d17477b8543818f8d43bc83d6c/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/StandardPlayerRequestResolver.java#L157): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![MAJOR][MAJOR] [WindowCitizen.java#L349](https://github.com/Minecolonies/minecolonies/blob/dec48d79742e95d17477b8543818f8d43bc83d6c/src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java#L349): Remove this unused private "getNicePositionString" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [RequestHandler.java#L29](https://github.com/Minecolonies/minecolonies/blob/dec48d79742e95d17477b8543818f8d43bc83d6c/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L29): Add a private constructor to hide the implicit public one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1118)
1. ![MAJOR][MAJOR] [RequestHandler.java#L114](https://github.com/Minecolonies/minecolonies/blob/dec48d79742e95d17477b8543818f8d43bc83d6c/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L114): Refactor this method to reduce its Cognitive Complexity from 36 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Raycoms** [comment]
:shipit: will merge it in the morning.
Great job @OrionDevelopment !
