### PR TITLE
Fix/citizen spawn at townhall

### LINKED ISSUE #350: Crash with build tool
### Minecolonies version
All the newest ones 1.10 and 1.11

### Actual behaviour

- Use build tool -> switch to decoration mode -> switch back to hut mode. Still able to switch decoration style. That shouldn't be possible.

### PR DESCRIPTION
**Pull request by Raycoms**
Fixes #350 #292 #350 #355

Fixes some navigation problems.
An old bug with the builder crashing.
And citizens now correctly spawn at their townhalls.
Also: Miner correctly mines underground.

Some work to fix some bugs/crashes, sonar + anti griefing.

Monsters can only be spawned by the colony officer +

Explosions have a seperate config toggle.
Add config option

Only friendly players can pickUp, only officer can kill citizens.

Turn on/off griefing prot with config + fix playerContainerEvent

And add new fisherman, farmer and townhall schematics.

Reset style when switching back to huts.
Adds a new command to add Officers per command

That way admins can access colonies of players.
Create file for addOfficerCommand

Fix for crash of farmer building on destroyed.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 1]
```diff
@@ -567,25 +567,47 @@ private BlockPos getPositionInDirection(final EnumFacing facing, final int dista
...
+     * Calculates the floor level
+     *
+     * @param position input position
+     * @param depth    the iteration depth
+     * @return returns BlockPos position with air above
+     */
+    @Nullable
+    private BlockPos getFloor(@NotNull BlockPos position, int depth)
+    {
+        if (depth > 50)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:596]: MINOR Assign this magic number 50 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 2]
```diff
@@ -567,25 +567,47 @@ private BlockPos getPositionInDirection(final EnumFacing facing, final int dista
     }
 
     /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 3]
```diff
@@ -567,25 +567,47 @@ private BlockPos getPositionInDirection(final EnumFacing facing, final int dista
...
     {
+        final BlockPos floor = getFloor(position, 0);
+        if (floor == null)
+        {
+            return position;
+        }
+        return floor;
+    }
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java [hunk 4]
```diff
@@ -201,6 +203,16 @@ private BlockPos getMinerProxy(final BlockPos target, final double distanceToPat
             //Check if miner is underground in shaft and his target is overground.
             if (workerY <= levelDepth && targetY > levelDepth)
             {
+                if(level.getRandomNode().getParent() != null)
+                {
+                    com.minecolonies.coremod.entity.ai.citizen.miner.Node currentNode = level.getNode(level.getRandomNode().getParent());
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java:208]: MAJOR Unnecessary use of fully qualified name 'com.minecolonies.coremod.entity.ai.citizen.miner.Node' due to existing import 'com.minecolonies.coremod.entity.ai.citizen.miner.*' [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3AUnnecessaryFullyQualifiedName)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java [hunk 5]
```diff
@@ -217,6 +229,23 @@ else if (targetY <= levelDepth && workerY > levelDepth)
 
                 //Then add the ladder position as the latest node.
                 proxyList.add(new BlockPos(ladderPos.getX(), level.getDepth(), ladderPos.getZ()));
+
+                if(level.getRandomNode().getParent() != null)
+                {
+                    List<BlockPos> nodesToTarget = new ArrayList<>();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java]: MINOR Local variable 'nodesToTarget' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java [hunk 6]
```diff
@@ -217,6 +229,23 @@ else if (targetY <= levelDepth && workerY > levelDepth)
...
+                    com.minecolonies.coremod.entity.ai.citizen.miner.Node currentNode = level.getNode(level.getRandomNode().getParent());
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java]: MAJOR Unnecessary use of fully qualified name 'com.minecolonies.coremod.entity.ai.citizen.miner.Node' due to existing import 'com.minecolonies.coremod.entity.ai.citizen.miner.*' [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3AUnnecessaryFullyQualifiedName)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 7 issues
* MAJOR 3 major
* MINOR 4 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [ShowColonyInfoCommand.java#L53](https://github.com/Minecolonies/minecolonies/blob/79e2aa548486aa7438374c33be2f17758db52f4b/src/main/java/com/minecolonies/coremod/commands/ShowColonyInfoCommand.java#L53): The Cyclomatic Complexity of this method "execute" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

File: src/main/java/com/minecolonies/coremod/blocks/BlockHutTownHall.java [hunk 7]
```diff
@@ -44,8 +45,12 @@ public void onBlockPlacedBy(
         if(placer.getActiveHand().equals(EnumHand.MAIN_HAND))
         {
             final Colony colony = ColonyManager.getClosestColony(worldIn, pos);
-            if (colony == null && placer instanceof EntityPlayer)
+
+            if ((colony == null
+                    || BlockPosUtil.getDistance2D(colony.getCenter(), pos) >= Configurations.workingRangeTownHall * 2 + Configurations.townHallPadding)
```
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/blocks/BlockHutTownHall.java:50]: So we create a second colony when someone places the townhall somewhere else?

File: src/main/java/com/minecolonies/coremod/network/messages/BuildToolPlaceMessage.java [hunk 8]
```diff
@@ -142,18 +145,21 @@ private static void handleHut(
             return;
         }
 
+        final Block block = Block.getBlockFromName(Constants.MOD_ID + ":blockHut" + hut);
         final Colony tempColony = ColonyManager.getClosestColony(world, buildPos);
-        if (tempColony != null && !tempColony.getPermissions().hasPermission(player, Permissions.Action.MANAGE_HUTS))
+        if (tempColony != null
```
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/network/messages/BuildToolPlaceMessage.java:150]: Can we flip all these & &  to || that would look way better

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 9]
```diff
@@ -910,7 +932,7 @@ else if (entity instanceof EntityMinecart)
      */
     private BlockPos getNodeMiningPosition(BlockPos blockToMine)
     {
-        if(((BuildingMiner) getOwnBuilding()).getCurrentLevel() == null || ((BuildingMiner) getOwnBuilding()).getCurrentLevel().getRandomNode() != null)
+        if(((BuildingMiner) getOwnBuilding()).getCurrentLevel() == null || ((BuildingMiner) getOwnBuilding()).getCurrentLevel().getRandomNode() == null)
```
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: Can we make the casted building a variable?

File: src/main/java/com/minecolonies/coremod/blocks/BlockHutTownHall.java (hunk 7 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/blocks/BlockHutTownHall.java:50]: no, he never reaches this spot if he tries to place his townhall outside of his own townhall range.

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/blocks/BlockHutTownHall.java:50]: He only reaches this if the placement is valid. But we can't be sure whether he is placing it again or the first time. (Inside the correct range)

File: src/main/java/com/minecolonies/coremod/network/messages/BuildToolPlaceMessage.java (hunk 8 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/network/messages/BuildToolPlaceMessage.java:150]: It would look better I also thought about that. But we would lose the context. It would be harder to interprete.

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 9 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: Sure

File: src/main/java/com/minecolonies/coremod/network/messages/BuildToolPlaceMessage.java (hunk 8 above)
Comment (marvin-bitterlich) [reply src/main/java/com/minecolonies/coremod/network/messages/BuildToolPlaceMessage.java:150]: Hmmm maybe not worth it then...

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 10]
```diff
@@ -910,11 +932,16 @@ else if (entity instanceof EntityMinecart)
      */
     private BlockPos getNodeMiningPosition(BlockPos blockToMine)
     {
-        if(((BuildingMiner) getOwnBuilding()).getCurrentLevel() == null || ((BuildingMiner) getOwnBuilding()).getCurrentLevel().getRandomNode() != null)
+        if(getOwnBuilding() instanceof BuildingMiner)
         {
-            return blockToMine;
+            BuildingMiner buildingMiner = (BuildingMiner) getOwnBuilding();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:937]: MINOR Local variable 'buildingMiner' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java [hunk 11]
```diff
@@ -217,6 +229,23 @@ else if (targetY <= levelDepth && workerY > levelDepth)
 
                 //Then add the ladder position as the latest node.
                 proxyList.add(new BlockPos(ladderPos.getX(), level.getDepth(), ladderPos.getZ()));
+
+                if(level.getRandomNode().getParent() != null)
+                {
+                    final List<BlockPos> nodesToTarget = new ArrayList<>();
+                    com.minecolonies.coremod.entity.ai.citizen.miner.Node currentNode = level.getNode(level.getRandomNode().getParent());
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/pathfinding/WalkToProxy.java:236]: MAJOR Unnecessary use of fully qualified name 'com.minecolonies.coremod.entity.ai.citizen.miner.Node' due to existing import 'com.minecolonies.coremod.entity.ai.citizen.miner.*' [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3AUnnecessaryFullyQualifiedName)

File: src/main/java/com/minecolonies/coremod/commands/AddOfficerCommand.java [hunk 12]
```diff
@@ -0,0 +1,90 @@
...
+        {
+            playerName = args[1];
+        }
+
+        if(playerName == null || playerName.isEmpty())
+        {
+            playerName = sender.getName();
+        }
+
+        Colony colony = ColonyManager.getColony(colonyId);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/commands/AddOfficerCommand.java:61]: MINOR Local variable 'colony' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/coremod/configuration/ConfigurationHandler.java [hunk 13]
```diff
@@ -46,6 +46,9 @@ public static synchronized void init(final File file)
             citizenRespawnInterval = getClampedInt(config, CATEGORY_GAMEPLAY,
               "citizenRespawnInterval", citizenRespawnInterval, CITIZEN_RESPAWN_INTERVAL_MIN, CITIZEN_RESPAWN_INTERVAL_MAX, "Citizen respawn interval in seconds");
             builderInfiniteResources = config.get(CATEGORY_GAMEPLAY, "builderInfiniteResources", builderInfiniteResources, "Does Builder have infinite resources?").getBoolean();
+            enableColonyProtection = config.get(CATEGORY_GAMEPLAY, "enableColonyProtection", enableColonyProtection, "Enable the automatic colony protection?").getBoolean();
+            turnOffExplosionsInColonies = config.get(CATEGORY_GAMEPLAY, "turnOffExplosionsInColonies", turnOffExplosionsInColonies, "Turn off explosions inside the colonies radius?").getBoolean();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/configuration/ConfigurationHandler.java:50]: MINOR Split this 196 characters long line (which is greater than 180 authorized). [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS00103)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 7 issues
* MAJOR 3 major
* MINOR 4 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [ShowColonyInfoCommand.java#L53](https://github.com/Minecolonies/minecolonies/blob/2f222dd0a639e46c46a20fd4549449df6c780ca0/src/main/java/com/minecolonies/coremod/commands/ShowColonyInfoCommand.java#L53): The Cyclomatic Complexity of this method "execute" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

**Comment by Raycoms** [comment]
@Kostronor can you take a look at this?

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 7 issues
* MAJOR 3 major
* MINOR 4 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [ShowColonyInfoCommand.java#L53](https://github.com/Minecolonies/minecolonies/blob/65ede058d488fe41e605ec1ef62af41f927ae17d/src/main/java/com/minecolonies/coremod/commands/ShowColonyInfoCommand.java#L53): The Cyclomatic Complexity of this method "execute" is 12 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

**Comment by Raycoms** [comment]
@Kostronor

**Comment by marvin-bitterlich** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/356/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)
