### PR TITLE
Fix fuel check in smeltercrafter when furnace goes missing

### LINKED ISSUE #5850: AI Crashed
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version:  minecolonies-0.13.290-ALPHA-universal
- Structurize Version: minecolonies-0.13.290-ALPHA-universal

## Problem description
AI Crashed

[debug.log.gz](https://github.com/ldtteam/minecolonies/files/5312387/debug.log.gz)
[latest.log.gz](https://github.com/ldtteam/minecolonies/files/5312388/latest.log.gz)

### PR DESCRIPTION
**Pull request by Mekle001**
Closes #5850 

# Changes proposed in this pull request:
- If the furnace position doesn't have a furnace, remove it from the list and move on. 

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java [hunk 1]
```diff
@@ -257,6 +257,11 @@ private boolean isFuelNeeded()
             if (WorldUtil.isBlockLoaded(world, pos))
             {
                 final TileEntity entity = world.getTileEntity(pos);
+                if(!(entity instanceof FurnaceTileEntity))
+                {
+                    getOwnBuilding().removeFromFurnaces(pos);
+                    continue;
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java:263]: I wonder if this could cause a concurrent modification exception. Are we iterating over a copy?

Comment (Mekle001) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIRequestSmelter.java:263]: Just tested this scenario. I didn't get an exception.

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/5851/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)
