### PR TITLE
Fix npe in unReserveGrave

### LINKED ISSUE #7090: Undertaker not doing job, just AI-erroring
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.158-ALPHA

### Logs

- latest.log: https://gist.github.com/Lielac/5abc737753d5bcca83ee71a61c9aa7aa

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by chandler05**
Closes #7090
Closes #
Closes #

# Changes proposed in this pull request:
- Fix an npe caused by the unReserveGrave method
-
-

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
Were you able to reproduce this? I didn't look too deep into this, but, I wonder why this happens in the first place

**Comment by chandler05** [comment]
Couldn't reproduce, not sure why the grave pos would have been null.

**Comment by chandler05** [comment]
Other than that I don't know how it could have happened.

**Review by Mekle001 — DISMISSED** [review]

**Comment by Raycoms** [comment]
I guess this might stem from the player removing the grave before the citizen gets to it, but, you let the chunk unload

**Comment by someaddons** [comment]
I've taken a look and the actual issue of the NPE is not that the blockpositions is null, but that the graves list does not contain the position, which can happen since building might not be up to date on what the graves list  has. So we should add a `graves.contains(pos)` check in addition to the null check.

Also noticed that the Tileentity checks are only tileentity != null, should be instead a `tileentity instanceof GraveType` to have the proper type check too.

File: src/main/java/com/minecolonies/coremod/colony/managers/GraveManager.java [hunk 1]
```diff
@@ -197,7 +197,7 @@ public boolean reserveGrave(@NotNull final BlockPos pos)
     @Override
     public void unReserveGrave(@NotNull final BlockPos pos)
     {
-        if (graves.get(pos))
+        if (graves.containsKey(pos) && graves.get(pos) != null)
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/colony/managers/GraveManager.java]: Doesn't need the null check, contains does this already, so this should be graves.containsKey(pos) && graves.get(pos)
The method that calls this then needs the te instanceof Grave instead of != null too

Comment (chandler05) [reply src/main/java/com/minecolonies/coremod/colony/managers/GraveManager.java]: Ok, done.

**Review by Raycoms — APPROVED** [review]

**Review by someaddons — APPROVED** [review]

File: src/main/java/com/minecolonies/coremod/colony/managers/GraveManager.java (hunk 1 above)
Comment (MatthiasMann) [reply src/main/java/com/minecolonies/coremod/colony/managers/GraveManager.java]: doing a containsKey followed by get will perform the same operation twice on the map. It would be cheaper to just use get and check the result if you never insert null values.

Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/colony/managers/GraveManager.java]: you're right that it would be cheaper, although this place isnt called frequent enough to make a difference and is a bit nicer to read this way
