### PR TITLE
correctly get the world to avoid crashes

### LINKED ISSUE #1761: Right click on Guard - Crash
minecolonies-universal-
minecraft 1.12.2-
mine colonies 0.8.5810

Crash right clicking on citizen to get their gui.   Tried different citizen and every citizen right click caused crash.

[crash-2017-12-04_21.52.30-client.txt](https://github.com/Minecolonies/minecolonies/files/1529636/crash-2017-12-04_21.52.30-client.txt)
[crash-2017-12-04_21.50.38-client.txt](https://github.com/Minecolonies/minecolonies/files/1529637/crash-2017-12-04_21.50.38-client.txt)

### LINKED ISSUE #1769: Crash when right clicking builder
### Minecolonies version

version 1.12.2-0.8.5875

### Expected behavior

- Opens builder GUI/inventory

### Actual behaviour

- client side crash, but server does not crash

### Steps to reproduce the problem

Right click on builder

Note = i am using direwolf 1.12 from curse and just added minecolonies to it.

crash report 
https://pastebin.com/Jj9RMUpz

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #1761 
Closes #1769

# Changes proposed in this pull request:
- Correctly get the world

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/proxy/ClientProxy.java [hunk 1]
```diff
@@ -2,6 +2,7 @@
 
 import com.minecolonies.api.util.Log;
 import com.minecolonies.api.util.constant.Constants;
+import com.minecolonies.coremod.MineColonies;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/proxy/ClientProxy.java]: MINOR Remove this unused import 'com.minecolonies.coremod.MineColonies'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 42 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MINOR][MINOR] 41 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [CommonProxy.java#L125](https://github.com/Minecolonies/minecolonies/blob/8e9ccc0cb7514fd5a24f0df18276cee30cab2cb5/src/main/java/com/minecolonies/coremod/proxy/CommonProxy.java#L125): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![MINOR][MINOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/8e9ccc0cb7514fd5a24f0df18276cee30cab2cb5/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/8e9ccc0cb7514fd5a24f0df18276cee30cab2cb5/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render#](https://github.com/Minecolonies/minecolonies/blob/8e9ccc0cb7514fd5a24f0df18276cee30cab2cb5/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/8e9ccc0cb7514fd5a24f0df18276cee30cab2cb5/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/8e9ccc0cb7514fd5a24f0df18276cee30cab2cb5/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions#](https://github.com/Minecolonies/minecolonies/blob/8e9ccc0cb7514fd5a24f0df18276cee30cab2cb5/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [init#](https://github.com/Minecolonies/minecolonies/blob/8e9ccc0cb7514fd5a24f0df18276cee30cab2cb5/src/main/java/com/minecolonies/coremod/colony/requestsystem/init#): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [locations#](https://github.com/Minecolonies/minecolonies/blob/8e9ccc0cb7514fd5a24f0df18276cee30cab2cb5/src/main/java/com/minecolonies/coremod/colony/requestsystem/locations#): Add a 'package-info.java' file to document the 'locations' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [management#](https://github.com/Minecolonies/minecolonies/blob/8e9ccc0cb7514fd5a24f0df18276cee30cab2cb5/src/main/java/com/minecolonies/coremod/colony/requestsystem/management#): Add a 'package-info.java' file to document the 'management' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Asherslab** [comment]
Looks good to me! :shipit:

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1771/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java [hunk 2]
```diff
@@ -94,7 +105,16 @@ public boolean canResolve(
     public void resolve(
                          @NotNull final IRequestManager manager, @NotNull final IRequest<? extends IDeliverable> request) throws RuntimeException
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java:106]: MINOR Remove the declaration of thrown exception 'java.lang.RuntimeException' which is a runtime exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

File: src/main/java/com/minecolonies/coremod/inventory/ContainerMinecoloniesBuildingInventory.java [hunk 3]
```diff
@@ -13,50 +13,38 @@
...
     private final int inventorySize;
 
+    /**
+     * Public constructor to create the minecolonies building container.
+     * @param playerInventory the player inv.
+     * @param inventory the inv itself.
+     * @param colonyId the colony id.
+     * @param buildingId the building id.
+     */
     public ContainerMinecoloniesBuildingInventory(
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/inventory/ContainerMinecoloniesBuildingInventory.java:45]: MAJOR Refactor this method to reduce its Cognitive Complexity from 24 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java [hunk 4]
```diff
@@ -672,7 +673,7 @@ private void fulfill(@NotNull final Button button)
 
             final AbstractBuildingView building = ColonyManager.getColonyView(citizen.getColonyId()).getBuilding(citizen.getWorkBuilding());
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java]: MAJOR Remove this useless assignment to local variable "building". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1854)
MINOR Remove this unused "building" local variable. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1481)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java [hunk 5]
```diff
@@ -21,6 +21,7 @@
 import com.minecolonies.coremod.colony.buildings.views.AbstractBuildingView;
 import com.minecolonies.coremod.network.messages.OpenInventoryMessage;
 import com.minecolonies.coremod.network.messages.TransferItemsRequestMessage;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java]: MINOR Remove this unused import 'com.minecolonies.coremod.network.messages.TransferItemsRequestMessage'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 59 issues
* ![CRITICAL][CRITICAL] 3 critical
* ![MAJOR][MAJOR] 6 major
* ![MINOR][MINOR] 50 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BuildingRequestResolver.java#L151](https://github.com/Minecolonies/minecolonies/blob/1ff33de523168693618bbe0b7da25e72ae103370/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java#L151): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![CRITICAL][CRITICAL] [BuildingRequestResolver.java#L158](https://github.com/Minecolonies/minecolonies/blob/1ff33de523168693618bbe0b7da25e72ae103370/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java#L158): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![CRITICAL][CRITICAL] [CommonProxy.java#L125](https://github.com/Minecolonies/minecolonies/blob/1ff33de523168693618bbe0b7da25e72ae103370/src/main/java/com/minecolonies/coremod/proxy/CommonProxy.java#L125): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![MAJOR][MAJOR] [WindowCitizen.java#L351](https://github.com/Minecolonies/minecolonies/blob/1ff33de523168693618bbe0b7da25e72ae103370/src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java#L351): Remove this unused private "getNicePositionString" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [WindowCitizen.java#L559](https://github.com/Minecolonies/minecolonies/blob/1ff33de523168693618bbe0b7da25e72ae103370/src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java#L559): Split this 238 characters long line (which is greater than 180 authorized). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00103)
1. ![MAJOR][MAJOR] [BuildingRequestResolver.java#L41](https://github.com/Minecolonies/minecolonies/blob/1ff33de523168693618bbe0b7da25e72ae103370/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java#L41): Assign this magic number 100 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [BuildingRequestResolver.java#L100](https://github.com/Minecolonies/minecolonies/blob/1ff33de523168693618bbe0b7da25e72ae103370/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java#L100): Return an empty collection instead of null. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1168)
1. ![MINOR][MINOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/1ff33de523168693618bbe0b7da25e72ae103370/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/1ff33de523168693618bbe0b7da25e72ae103370/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [WindowCitizen.java#L8](https://github.com/Minecolonies/minecolonies/blob/1ff33de523168693618bbe0b7da25e72ae103370/src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java#L8): Remove this unused import 'com.minecolonies.api.util.ItemStackUtils'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 59 issues
* ![CRITICAL][CRITICAL] 3 critical
* ![MAJOR][MAJOR] 6 major
* ![MINOR][MINOR] 50 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BuildingRequestResolver.java#L151](https://github.com/Minecolonies/minecolonies/blob/43094e3110274ca2cd3c187cd76d2d583e7ee0ac/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java#L151): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![CRITICAL][CRITICAL] [BuildingRequestResolver.java#L158](https://github.com/Minecolonies/minecolonies/blob/43094e3110274ca2cd3c187cd76d2d583e7ee0ac/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java#L158): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![CRITICAL][CRITICAL] [CommonProxy.java#L125](https://github.com/Minecolonies/minecolonies/blob/43094e3110274ca2cd3c187cd76d2d583e7ee0ac/src/main/java/com/minecolonies/coremod/proxy/CommonProxy.java#L125): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![MAJOR][MAJOR] [WindowCitizen.java#L351](https://github.com/Minecolonies/minecolonies/blob/43094e3110274ca2cd3c187cd76d2d583e7ee0ac/src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java#L351): Remove this unused private "getNicePositionString" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [WindowCitizen.java#L559](https://github.com/Minecolonies/minecolonies/blob/43094e3110274ca2cd3c187cd76d2d583e7ee0ac/src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java#L559): Split this 238 characters long line (which is greater than 180 authorized). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00103)
1. ![MAJOR][MAJOR] [BuildingRequestResolver.java#L41](https://github.com/Minecolonies/minecolonies/blob/43094e3110274ca2cd3c187cd76d2d583e7ee0ac/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java#L41): Assign this magic number 100 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [BuildingRequestResolver.java#L100](https://github.com/Minecolonies/minecolonies/blob/43094e3110274ca2cd3c187cd76d2d583e7ee0ac/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java#L100): Return an empty collection instead of null. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1168)
1. ![MINOR][MINOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/43094e3110274ca2cd3c187cd76d2d583e7ee0ac/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/43094e3110274ca2cd3c187cd76d2d583e7ee0ac/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [WindowCitizen.java#L8](https://github.com/Minecolonies/minecolonies/blob/43094e3110274ca2cd3c187cd76d2d583e7ee0ac/src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java#L8): Remove this unused import 'com.minecolonies.api.util.ItemStackUtils'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 68 issues
* ![CRITICAL][CRITICAL] 8 critical
* ![MAJOR][MAJOR] 9 major
* ![MINOR][MINOR] 51 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1431](https://github.com/Minecolonies/minecolonies/blob/fd964ea91945307cbaaeb50999d0ebd714b1c5e2/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1431): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1460](https://github.com/Minecolonies/minecolonies/blob/fd964ea91945307cbaaeb50999d0ebd714b1c5e2/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1460): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1471](https://github.com/Minecolonies/minecolonies/blob/fd964ea91945307cbaaeb50999d0ebd714b1c5e2/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1471): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1574](https://github.com/Minecolonies/minecolonies/blob/fd964ea91945307cbaaeb50999d0ebd714b1c5e2/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1574): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1688](https://github.com/Minecolonies/minecolonies/blob/fd964ea91945307cbaaeb50999d0ebd714b1c5e2/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1688): Missing curly brace. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00121)
1. ![CRITICAL][CRITICAL] [BuildingRequestResolver.java#L151](https://github.com/Minecolonies/minecolonies/blob/fd964ea91945307cbaaeb50999d0ebd714b1c5e2/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java#L151): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![CRITICAL][CRITICAL] [BuildingRequestResolver.java#L158](https://github.com/Minecolonies/minecolonies/blob/fd964ea91945307cbaaeb50999d0ebd714b1c5e2/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java#L158): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![CRITICAL][CRITICAL] [CommonProxy.java#L125](https://github.com/Minecolonies/minecolonies/blob/fd964ea91945307cbaaeb50999d0ebd714b1c5e2/src/main/java/com/minecolonies/coremod/proxy/CommonProxy.java#L125): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![MAJOR][MAJOR] [WindowCitizen.java#L351](https://github.com/Minecolonies/minecolonies/blob/fd964ea91945307cbaaeb50999d0ebd714b1c5e2/src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java#L351): Remove this unused private "getNicePositionString" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [WindowCitizen.java#L559](https://github.com/Minecolonies/minecolonies/blob/fd964ea91945307cbaaeb50999d0ebd714b1c5e2/src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java#L559): Split this 238 characters long line (which is greater than 180 authorized). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00103)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 68 issues
* ![CRITICAL][CRITICAL] 8 critical
* ![MAJOR][MAJOR] 9 major
* ![MINOR][MINOR] 51 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1431](https://github.com/Minecolonies/minecolonies/blob/1e7b468df14bb22c861aa5fd09b436c734137210/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1431): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1460](https://github.com/Minecolonies/minecolonies/blob/1e7b468df14bb22c861aa5fd09b436c734137210/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1460): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1471](https://github.com/Minecolonies/minecolonies/blob/1e7b468df14bb22c861aa5fd09b436c734137210/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1471): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1574](https://github.com/Minecolonies/minecolonies/blob/1e7b468df14bb22c861aa5fd09b436c734137210/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1574): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1688](https://github.com/Minecolonies/minecolonies/blob/1e7b468df14bb22c861aa5fd09b436c734137210/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1688): Missing curly brace. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00121)
1. ![CRITICAL][CRITICAL] [BuildingRequestResolver.java#L151](https://github.com/Minecolonies/minecolonies/blob/1e7b468df14bb22c861aa5fd09b436c734137210/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java#L151): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![CRITICAL][CRITICAL] [BuildingRequestResolver.java#L158](https://github.com/Minecolonies/minecolonies/blob/1e7b468df14bb22c861aa5fd09b436c734137210/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java#L158): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![CRITICAL][CRITICAL] [CommonProxy.java#L125](https://github.com/Minecolonies/minecolonies/blob/1e7b468df14bb22c861aa5fd09b436c734137210/src/main/java/com/minecolonies/coremod/proxy/CommonProxy.java#L125): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![MAJOR][MAJOR] [WindowCitizen.java#L351](https://github.com/Minecolonies/minecolonies/blob/1e7b468df14bb22c861aa5fd09b436c734137210/src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java#L351): Remove this unused private "getNicePositionString" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [WindowCitizen.java#L559](https://github.com/Minecolonies/minecolonies/blob/1e7b468df14bb22c861aa5fd09b436c734137210/src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java#L559): Split this 238 characters long line (which is greater than 180 authorized). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00103)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Review by marchermans — APPROVED** [review]

File: src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java [hunk 6]
```diff
@@ -669,10 +668,7 @@ private void fulfill(@NotNull final Button button)
...
                 itemStack = inventory.getStackInSlot(InventoryUtils.findFirstSlotInItemHandlerWith(new InvWrapper(inventory), requestPredicate));
             }
-
-            final AbstractBuildingView building = ColonyManager.getColonyView(citizen.getColonyId()).getBuilding(citizen.getWorkBuilding());
-
-            MineColonies.getNetwork().sendToServer(new TransferItemsRequestMessage(building, itemStack, isCreative ? amount : count, false));
+            MineColonies.getNetwork().sendToServer(new TransferItemsToCitizenRequestMessage(citizen, itemStack, isCreative ? amount : count, citizen.getColonyId()));
             MineColonies.getNetwork().sendToServer(new UpdateRequestStateMessage(citizen.getColonyId(), request.getToken(), RequestState.OVERRULED, itemStack));
         }
     }
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java]: MAJOR Remove this useless assignment to local variable "building". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1854)
MINOR Remove this unused "building" local variable. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1481)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java [hunk 7]
```diff
@@ -20,7 +19,7 @@
 import com.minecolonies.coremod.colony.ColonyView;
 import com.minecolonies.coremod.colony.buildings.views.AbstractBuildingView;
 import com.minecolonies.coremod.network.messages.OpenInventoryMessage;
-import com.minecolonies.coremod.network.messages.TransferItemsRequestMessage;
+import com.minecolonies.coremod.network.messages.TransferItemsToCitizenRequestMessage;
 import com.minecolonies.coremod.network.messages.UpdateRequestStateMessage;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java]: MINOR Remove this unused import 'com.minecolonies.coremod.network.messages.TransferItemsRequestMessage'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java [hunk 8]
```diff
@@ -5,7 +5,6 @@
 import com.minecolonies.api.colony.requestsystem.request.RequestState;
 import com.minecolonies.api.colony.requestsystem.requestable.IDeliverable;
 import com.minecolonies.api.util.InventoryUtils;
-import com.minecolonies.api.util.ItemStackUtils;
 import com.minecolonies.api.util.LanguageHandler;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java]: MINOR Remove this unused import 'com.minecolonies.api.util.ItemStackUtils'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 68 issues
* ![CRITICAL][CRITICAL] 8 critical
* ![MAJOR][MAJOR] 9 major
* ![MINOR][MINOR] 51 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1431](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1431): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1460](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1460): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1471](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1471): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1574](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1574): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1688](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1688): Missing curly brace. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00121)
1. ![CRITICAL][CRITICAL] [BuildingRequestResolver.java#L151](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java#L151): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![CRITICAL][CRITICAL] [BuildingRequestResolver.java#L158](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java#L158): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![CRITICAL][CRITICAL] [CommonProxy.java#L125](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/proxy/CommonProxy.java#L125): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![MAJOR][MAJOR] [WindowCitizen.java#L351](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java#L351): Remove this unused private "getNicePositionString" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [WindowCitizen.java#L559](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java#L559): Split this 238 characters long line (which is greater than 180 authorized). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00103)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 63 issues
* ![CRITICAL][CRITICAL] 8 critical
* ![MAJOR][MAJOR] 8 major
* ![MINOR][MINOR] 47 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1431](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1431): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1460](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1460): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1471](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1471): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1574](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1574): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1688](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1688): Missing curly brace. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00121)
1. ![CRITICAL][CRITICAL] [BuildingRequestResolver.java#L151](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java#L151): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![CRITICAL][CRITICAL] [BuildingRequestResolver.java#L158](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/colony/requestsystem/resolvers/BuildingRequestResolver.java#L158): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![CRITICAL][CRITICAL] [CommonProxy.java#L125](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/proxy/CommonProxy.java#L125): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1186)
1. ![MAJOR][MAJOR] [WindowCitizen.java#L349](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java#L349): Remove this unused private "getNicePositionString" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [WindowCitizen.java#L557](https://github.com/Minecolonies/minecolonies/blob/e6fa3fbb612957c171e5e6aa04cffe8272bf756b/src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java#L557): Split this 238 characters long line (which is greater than 180 authorized). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00103)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
