### PR TITLE
Fix Ultra-derp 11528

### LINKED ISSUE #11528: Scarecrow/field issue
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.1260

### Structurize Version

1.0.805

### Related Mods and their Versions

1. Forge: Sorry, idk how to check
2: DO: 1.0.228
3: BlockUI: 1.0.209

### Current Behavior

okayy so the scarecrows lose their assigned seed, thus being unallocated from farms, and whem i try to set them again, game chrases out instantly, giving this: "The game crashed: mousepressed event for bo screen
Error: java.lang.NullPointerException: Cannot invoke "com.minecolonies.core.colony.buildingextensions.FarmField.getSeed()" because "this.farmField" is null"

Now, I can break the scarecrows, and seemingly the issue disappears, can reassign them to each farmer, but after some time of minding my own business, I see that there is nothing going on on the fields, since the scarecrows got effed again.

aaand the logs: https://gist.github.com/c16kum/17f72be3948293d2f089a6918a96e344

### Expected Behavior

Well I think yall know that

### Reproduction Steps

Welp I have wrote it already, but I think csarecrows lose their seeds when I leave the game, but just a guess.

### Logs

https://gist.github.com/c16kum/17f72be3948293d2f089a6918a96e344

### Anything else?

_No response_

### Footer

---
 ## Viewers
  *  Add a 👍 reaction to the bug report if you are also affected. This helps the bug report become more visible without cluttering the comments.
  *  ⚠️ Only add a comment if you have new insights or background information not already mentioned. Off-topic or "+1" comments will be deleted to keep the discussion focused.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #11528
Closes #

# Changes proposed in this pull request
- Fix issue with field unregistering
- Add re-register to guarantee on click
- Don't clean colony views & chunks like that!

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/core/blocks/BlockScarecrow.java [hunk 1]
```diff
@@ -99,6 +99,11 @@ public ItemInteractionResult useItemOn(
             }
         }
 
+        final IColony iColony = IColonyManager.getInstance().getIColony(worldIn, pos);
```
Comment (someaddons) [inline src/main/java/com/minecolonies/core/blocks/BlockScarecrow.java:102]: does this useItemOn call trigger on interacting with an empty hand? not sure if this is the right vanilla call

Comment (Raycoms) [reply src/main/java/com/minecolonies/core/blocks/BlockScarecrow.java:102]: Yes, empty stack use then

**Review by someaddons — APPROVED** [review]
