### PR TITLE
Fix/citizen5

### LINKED ISSUE #1703: bug probleme
### Minecolonies version

minecolonies-universal-1.11.2-0.8.5090.jar 
and
minecolonies-universal-1.11.2-0.8.5085.jar 

### Expected behavior

impossible to use the construction tool to put any building when I validate it speaks to me as if I wanted to ask the boat while these for the town hall, the builder's building and any other building the tool does not work

### LINKED ISSUE #1706: Crash with Delivery man interacting with warehouse
Minecolonies version 0.8.5081

[crash-2017-11-27_21.33.24-client.txt](https://github.com/Minecolonies/minecolonies/files/1505629/crash-2017-11-27_21.33.24-client.txt)

Happens randomly don't know how to reproduce it.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #1706
Closes #1703

# Changes proposed in this pull request: Fixes for:
- Bug with buildTool/supplyship-camp
- Crash with dman.
- Problem with pathing (locomotion)
- Problem with finding the right bed to sleep in.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/tileentities/TileEntityWareHouse.java [hunk 1]
```diff
@@ -23,6 +23,7 @@
 import org.jetbrains.annotations.NotNull;
 import org.jetbrains.annotations.Nullable;
 
+import java.util.ArrayList;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/tileentities/TileEntityWareHouse.java:26]: MINOR Remove this unused import 'java.util.ArrayList'. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 70 issues
* ![MAJOR][MAJOR] 30 major
* ![MINOR][MINOR] 39 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [WindowBuildTool.java#L38](https://github.com/Minecolonies/minecolonies/blob/10c708b09b0357d1f212ead48c335371c1431d8d/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L38): class "WindowBuildTool" has 41 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L261](https://github.com/Minecolonies/minecolonies/blob/10c708b09b0357d1f212ead48c335371c1431d8d/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L261): Remove this unused "staticSchematicMode" private field. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1068)
1. ![MAJOR][MAJOR] [BuildingHome.java#L258](https://github.com/Minecolonies/minecolonies/blob/10c708b09b0357d1f212ead48c335371c1431d8d/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingHome.java#L258): Merge this if statement with the enclosing one. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1066)
1. ![MAJOR][MAJOR] [BuildingHome.java#L362](https://github.com/Minecolonies/minecolonies/blob/10c708b09b0357d1f212ead48c335371c1431d8d/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingHome.java#L362): Reduce this class from 38 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [EntityCitizen.java#](https://github.com/Minecolonies/minecolonies/blob/10c708b09b0357d1f212ead48c335371c1431d8d/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#): This file has 1,463 lines, which is greater than 1,000 authorized. Split it into smaller files. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L75](https://github.com/Minecolonies/minecolonies/blob/10c708b09b0357d1f212ead48c335371c1431d8d/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L75): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 63 to the maximum authorized 30 or less. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L75](https://github.com/Minecolonies/minecolonies/blob/10c708b09b0357d1f212ead48c335371c1431d8d/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L75): class "EntityCitizen" has 101 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L381](https://github.com/Minecolonies/minecolonies/blob/10c708b09b0357d1f212ead48c335371c1431d8d/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L381): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L383](https://github.com/Minecolonies/minecolonies/blob/10c708b09b0357d1f212ead48c335371c1431d8d/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L383): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L384](https://github.com/Minecolonies/minecolonies/blob/10c708b09b0357d1f212ead48c335371c1431d8d/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L384): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS881)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 70 issues
* ![MAJOR][MAJOR] 30 major
* ![MINOR][MINOR] 39 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [WindowBuildTool.java#L38](https://github.com/Minecolonies/minecolonies/blob/4098065e4b9285aa91bbe9b2cdbdbc9d9c619ace/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L38): class "WindowBuildTool" has 41 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L261](https://github.com/Minecolonies/minecolonies/blob/4098065e4b9285aa91bbe9b2cdbdbc9d9c619ace/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L261): Remove this unused "staticSchematicMode" private field. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1068)
1. ![MAJOR][MAJOR] [BuildingHome.java#L258](https://github.com/Minecolonies/minecolonies/blob/4098065e4b9285aa91bbe9b2cdbdbc9d9c619ace/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingHome.java#L258): Merge this if statement with the enclosing one. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1066)
1. ![MAJOR][MAJOR] [BuildingHome.java#L362](https://github.com/Minecolonies/minecolonies/blob/4098065e4b9285aa91bbe9b2cdbdbc9d9c619ace/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingHome.java#L362): Reduce this class from 38 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [EntityCitizen.java#](https://github.com/Minecolonies/minecolonies/blob/4098065e4b9285aa91bbe9b2cdbdbc9d9c619ace/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#): This file has 1,462 lines, which is greater than 1,000 authorized. Split it into smaller files. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L75](https://github.com/Minecolonies/minecolonies/blob/4098065e4b9285aa91bbe9b2cdbdbc9d9c619ace/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L75): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 63 to the maximum authorized 30 or less. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L75](https://github.com/Minecolonies/minecolonies/blob/4098065e4b9285aa91bbe9b2cdbdbc9d9c619ace/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L75): class "EntityCitizen" has 101 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L381](https://github.com/Minecolonies/minecolonies/blob/4098065e4b9285aa91bbe9b2cdbdbc9d9c619ace/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L381): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L383](https://github.com/Minecolonies/minecolonies/blob/4098065e4b9285aa91bbe9b2cdbdbc9d9c619ace/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L383): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L384](https://github.com/Minecolonies/minecolonies/blob/4098065e4b9285aa91bbe9b2cdbdbc9d9c619ace/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L384): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS881)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 70 issues
* ![MAJOR][MAJOR] 30 major
* ![MINOR][MINOR] 39 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [WindowBuildTool.java#L38](https://github.com/Minecolonies/minecolonies/blob/6ceeba619b652eec36a0273537219fee6e052eee/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L38): class "WindowBuildTool" has 41 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L261](https://github.com/Minecolonies/minecolonies/blob/6ceeba619b652eec36a0273537219fee6e052eee/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L261): Remove this unused "staticSchematicMode" private field. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1068)
1. ![MAJOR][MAJOR] [BuildingHome.java#L258](https://github.com/Minecolonies/minecolonies/blob/6ceeba619b652eec36a0273537219fee6e052eee/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingHome.java#L258): Merge this if statement with the enclosing one. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1066)
1. ![MAJOR][MAJOR] [BuildingHome.java#L362](https://github.com/Minecolonies/minecolonies/blob/6ceeba619b652eec36a0273537219fee6e052eee/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingHome.java#L362): Reduce this class from 38 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [EntityCitizen.java#](https://github.com/Minecolonies/minecolonies/blob/6ceeba619b652eec36a0273537219fee6e052eee/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#): This file has 1,462 lines, which is greater than 1,000 authorized. Split it into smaller files. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L75](https://github.com/Minecolonies/minecolonies/blob/6ceeba619b652eec36a0273537219fee6e052eee/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L75): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 63 to the maximum authorized 30 or less. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L75](https://github.com/Minecolonies/minecolonies/blob/6ceeba619b652eec36a0273537219fee6e052eee/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L75): class "EntityCitizen" has 101 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L381](https://github.com/Minecolonies/minecolonies/blob/6ceeba619b652eec36a0273537219fee6e052eee/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L381): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L383](https://github.com/Minecolonies/minecolonies/blob/6ceeba619b652eec36a0273537219fee6e052eee/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L383): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L384](https://github.com/Minecolonies/minecolonies/blob/6ceeba619b652eec36a0273537219fee6e052eee/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L384): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS881)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
