### PR TITLE
Fixes

### LINKED ISSUE #8198: [BUG] Restaurant can hand out low-level food
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.550-Alpha

### Structurize Version

1.0.371-Alpha

### Related Mods and their Versions

_No response_

### Current Behavior

A level 3 cook is able to hand out pufferfish, even though pufferfish isn't available anymore in the food list of the restaurant.

### Expected Behavior

The cook would ignore the pufferfish (and clownfish) that is in their racks, and request higher quality food

### Reproduction Steps

1. Build a low level restaurant
2. Give them a large backlog of pufferfish (make sure that food is enabled)
3. Upgrade it to level 3

If it turns out to be caused by the update to the restaurants that those low-level food items wouldn't show anymore, there would be a step 2.5 in between to update from a version before that feature to a version after that feature

### Logs

N/A

### Anything else?

I'm actually not sure whether this has been caused by the update to the restaurants lately, when the low-level food was removed from the gui, or if this can also happen when you upgrade a restaurant on later versions.
The restaurant I experienced it with has been level 3 for quite a while now

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #8204: [BUG] Children will not grow up after many hours IRL
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.552-ALPHA

### Structurize Version

1.18.2-1.0.370-ALPHA

### Related Mods and their Versions

1. Forge version: 1.18.2-40.0.32
2. Modpack: https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-new (3/28/2022 version)

### Current Behavior

Initially, we were using the mod pack Medieval Minecraft [FORGE] v2 [MineColonies version 1.18.2-1.0.504-BETA] and had no issues, but after upgrading to Medieval Minecraft [FORGE] v3 [MineColonies version 1.18.2-1.0.552-ALPHA],
we are now having issues with children not growing up in both single-player and multiplayer.
Children will not grow up at all even after many hours IRL. 
Reverting back to Medieval Minecraft [FORGE] v2 [MineColonies version 1.18.2-1.0.504-BETA] allowed children to grow up fine, but I wanted to call this out because the latest version of the mod pack we use is causing issues.

### Expected Behavior

Children should grow up after a few in-game days.

### Reproduction Steps

1. Download the mod pack ([HERE](https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-new))
2. Set up a Colony with children
3. Wait a few in-game days
4. Children will not grow up

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #8198
Closes #8204
Closes #

# Changes proposed in this pull request:
- Allow children to grow up again
- Adjust cook food handling better
- Allow updating the set of settings

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/cook/EntityAIWorkCook.java [hunk 1]
```diff
@@ -248,7 +250,7 @@ else if (InventoryUtils.hasItemInItemHandler(handler, stack -> CAN_EAT.test(stac
     }
 
     /**
-     * Check if the entity to serve can eat the given stack
+     * Check if the entity to serve can eat the given tack
```
Comment (Thodor12) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/cook/EntityAIWorkCook.java]: Accidental change?

File: src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/StringSetting.java [hunk 2]
```diff
@@ -107,6 +108,16 @@ public void trigger()
         }
     }
 
+    @Override
+    public void updateSetting(final ISetting iSetting)
```
Comment (Thodor12) [inline src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/StringSetting.java:112]: Maybe instead of hard clearing the old values we could check the different items between the 2 lists?
So if the old contains "a", "b", "c" and the new settings would contain "a", "b", "c", "d" it would only append "d" on the end, this way it wouldn't matter if positions of settings swap around because they're always appended instead of potentially inserted somewhere in the center.

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/buildings/modules/settings/StringSetting.java:112]: I thought about that, but if we remove a settingvalue from a building, we actually want it gone from all.

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/cook/EntityAIWorkCook.java (hunk 1 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/cook/EntityAIWorkCook.java]: yes

**Review by someaddons — APPROVED** [review]

**Review by Thodor12 — APPROVED** [review]
