### PR TITLE
Fix #6048 and fix inventory detection issues

### LINKED ISSUE #6048: Water bottle
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:  1.16.4
- MineColonies Version: minecolonies-0.13.420-ALPHA-universal
- Structurize Version: structurize-0.13.96-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

Request water bottles via postbox

## Actual behavior

Unable to search for and request water bottles

## Steps to reproduce the issue

1. 
Open up postbox
2. 
Search for "water"
3. 
Only Water buckets are listed

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #6048
Closes #
Closes #

# Changes proposed in this pull request:
- Allows postbox to request enchanted books, potions and tipped arrows now
- Fix some inventory detection issues by using a set
- Use the more efficient building searching method

Review please

### CODE REVIEW

**Review by someaddons — DISMISSED** [review]

File: src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java [hunk 1]
```diff
@@ -219,9 +225,35 @@ public void discover(final boolean serverSide)
...
+        for(Potion potion : Registry.POTION)
+        {
+            if (!potion.getEffects().isEmpty())
+            {
+                stacks.add(PotionUtils.addPotionToItemStack(new ItemStack(Items.TIPPED_ARROW), potion));
+            }
+        }
+
+        allBlocks = ImmutableList.copyOf(stacks);
     }
```
Comment (marchermans) [inline src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java]: This method is either named wrong, or does literally not what is written on the can.
Rename the method.

Also make this a parallel stream. With more then 1000+ entries in that list of items this should help.

**Review by marchermans — CHANGES_REQUESTED** [review]

**Review by marchermans — APPROVED** [review]

**Review by someaddons — APPROVED** [review]
