### PR TITLE
fix #6116 and network version

### LINKED ISSUE #6116: Miner Pathfinding
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.452
- Structurize Version: 0.13.96
- Related Mods and their Versions:

## Expected behavior

Miner descends mineshaft, begins mining out node at set level.

## Actual behavior

Miner approaches their destination on the surface, stands around "Working".  I think this common on relatively shallow levels where the X/Z coordinates are further from the hut block than the Y coordinate - the miner finds their way closer on the surface than via the mineshaft. If I break blocks in front/beneath them, they will walk closer to their destination.
I have also had miners try to reach their destination via the wrong Y level of the mine, one level up/down, and be unable to pathfind to their destination node unless I break the blocks in front/above or below of them.

(note, this miner is not attached to the sandstone mine in the distance, his stone mine is mostly behind the camera)

## Steps to reproduce the issue

1. Mine at a shallow level
2. Allow long corridors to develop
3. Miner path-finds to the destination on the surface not through the mine.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #6116
Closes #
Closes #

# Changes proposed in this pull request:
- Fix some miner pathfining
- Adjust networking version

Review please

### CODE REVIEW

**Review by marchermans — DISMISSED** [review]

**Review by someaddons — DISMISSED** [review]

File: src/main/java/com/minecolonies/coremod/Network.java [hunk 1]
```diff
@@ -7,7 +7,7 @@
     /**
      * The network instance.
      */
-    private static NetworkChannel network = new NetworkChannel("net-channel");
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/Network.java:10]: public?

File: src/main/java/com/minecolonies/coremod/network/NetworkChannel.java [hunk 2]
```diff
@@ -113,8 +114,8 @@
      */
     public NetworkChannel(final String channelName)
     {
-        rawChannel =
-          NetworkRegistry.newSimpleChannel(new ResourceLocation(Constants.MOD_ID, channelName), () -> LATEST_PROTO_VER, ACCEPTED_PROTO_VERS::equals, ACCEPTED_PROTO_VERS::equals);
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/network/NetworkChannel.java:117]: remove unused constants

File: src/main/java/com/minecolonies/coremod/Network.java (hunk 1 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/Network.java:10]: good catch

**Review by marchermans — APPROVED** [review]
