### PR TITLE
Removes plantantion flowers from florist

### LINKED ISSUE #5088: Remove sugar cane and cactus from florist
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 

### Expected behavior

- Cactus and sugar cane are now handled by the plantation so they can be removed from the florist. 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

### PR DESCRIPTION
**Pull request by PowerSchill**
Signed-off-by: Mark E. Schill <Mark.Schill@cmschill.net>

Closes #5088
Closes #
Closes #

# Changes proposed in this pull request:
-
-
-

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingFlorist.java [hunk 1]
```diff
@@ -221,7 +222,9 @@ public ItemStack getFlowerToGrow()
             case 4:
             case 5:
             default:
-                return IColonyManager.getInstance().getCompatibilityManager().getCopyOfPlantables();
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingFlorist.java]: that should probably be filtered in the copyOfPlantables creation

Comment (PowerSchill) [reply src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingFlorist.java]: I thought that was used in the compost section but you are correct

File: src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java [hunk 2]
```diff
@@ -355,7 +355,10 @@ public ItemStack getSaplingForLeaf(final BlockState block)
     @Override
     public List<ItemStorage> getCopyOfPlantables()
     {
-        return ImmutableList.copyOf(plantables);
+        return ImmutableList.copyOf(plantables)
+                 .stream()
```
Comment (Raycoms) [inline src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java]: I mean, we should prevent them getting into this list in the first place.

Comment (Raycoms) [reply src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java]: No need to filter every call the list.

Comment (PowerSchill) [reply src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java]: Ok, I see now. `discoverablePlantables` refers to compostable items but its beecause it w was copied from compostable not that it used them. I will fix.

**Review by someaddons — DISMISSED** [review]

File: src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java [hunk 3]
```diff
@@ -565,15 +565,20 @@ private void discoverCompostableItems()
...
 
     /**
-     * Create complete list of compostable items.
+     * Create complete list of plantable items.
      */
     private void discoverPlantables()
     {
         if (plantables.isEmpty())
         {
-            plantables.addAll(ImmutableList.copyOf(allBlocks.stream().filter(this::isPlantable).map(ItemStorage::new).collect(Collectors.toList())));
```
Comment (Raycoms) [inline src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java:574]: Can't we actually put this in the isPlantable check? Would be much more efficient.

File: src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java [hunk 4]
```diff
@@ -262,7 +262,8 @@ public boolean isCompost(final ItemStack itemStack)
     @Override
     public boolean isPlantable(final ItemStack itemStack)
     {
-        if (itemStack.isEmpty() || itemStack.getItem() == Items.WITHER_ROSE)
```
Comment (Raycoms) [inline src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java]: Lol, I just checked into the config file and actually the reason it's here in the first place is because it's in the list of plantables in the default config. So just removing it there should solve this for the future already.

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/5111/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)
