### PR TITLE
Changes to delete colony command

### LINKED ISSUE #1632: Add parameter to colony deletion to keep structures
I'd like to be able to keep the structures I've built with Mine Colonies, even when my colony gets corrupted and I need to delete it. I'd be able to continue to live out of those buildings. I could then place the schematics over top and start my colony right back where I was once issues are resolved.

### Minecolonies version

version Any

### Expected behavior

- Optionally, colony buildings aren't removed when colony is deleted

### Actual behaviour

- Colony buildings are removed when colony is deleted

### Steps to reproduce the problem

1. Create town hall
2. Delete colony
3. ...
4. Profit

### PR DESCRIPTION
**Pull request by RVOtakuMike**
Closes #1632 

# Changes proposed in this pull request:
- Change the delete colony command to optionally destroy structures instead of always destroying them.
- Add config option for weither or not to destroy structures on autodelete.
The command is now /mc colony delete <id> <true or false>

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/ColonyManager.java [hunk 1]
```diff
@@ -173,7 +173,7 @@ public static void deleteColony(final int id)
                     citizenData.getCitizenEntity().onDeath(CONSOLE_DAMAGE_SOURCE);
                     colonyWorlds.add(world);
                 }
-            }
+            }if(canDestroy){
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/ColonyManager.java]: MAJOR At most one statement is allowed per line, but 2 statements were found on this line. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS00122)
MINOR Move this left curly brace to the beginning of next line of code. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

File: src/main/java/com/minecolonies/coremod/colony/ColonyManager.java [hunk 2]
```diff
@@ -173,7 +173,7 @@ public static void deleteColony(final int id)
...
             Log.getLogger().info("Removing buildings for " + id);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/ColonyManager.java]: MINOR Make this line start at column 17. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AIndentationCheck)

File: src/main/java/com/minecolonies/coremod/colony/ColonyManager.java [hunk 3]
```diff
@@ -155,7 +155,7 @@ public static void markDirty()
      *
      * @param id the colonies id.
      */
-    public static void deleteColony(final int id)
+    public static void deleteColony(final int id, boolean canDestroy)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/ColonyManager.java]: MAJOR Provide multiple methods instead of using "canDestroy" to determine which action to take. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS2301)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 42 issues
* ![MAJOR][MAJOR] 4 major
* ![MINOR][MINOR] 38 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ColonyManager.java#L41](https://github.com/Minecolonies/minecolonies/blob/b2bf8870fa916853b65342fd1ffd57705e62cb67/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L41): class "ColonyManager" has 50 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ColonyManager.java#L604](https://github.com/Minecolonies/minecolonies/blob/b2bf8870fa916853b65342fd1ffd57705e62cb67/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L604): Either log or rethrow this exception. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1166)
1. ![MINOR][MINOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/b2bf8870fa916853b65342fd1ffd57705e62cb67/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/b2bf8870fa916853b65342fd1ffd57705e62cb67/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render#](https://github.com/Minecolonies/minecolonies/blob/b2bf8870fa916853b65342fd1ffd57705e62cb67/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/b2bf8870fa916853b65342fd1ffd57705e62cb67/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [ColonyManager.java#L180](https://github.com/Minecolonies/minecolonies/blob/b2bf8870fa916853b65342fd1ffd57705e62cb67/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L180): Make this line start at column 21. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AIndentationCheck)
1. ![MINOR][MINOR] [ColonyManager.java#L186](https://github.com/Minecolonies/minecolonies/blob/b2bf8870fa916853b65342fd1ffd57705e62cb67/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L186): Make this line start at column 25. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AIndentationCheck)
1. ![MINOR][MINOR] [ColonyManager.java#L188](https://github.com/Minecolonies/minecolonies/blob/b2bf8870fa916853b65342fd1ffd57705e62cb67/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L188): Make this line start at column 29. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AIndentationCheck)
1. ![MINOR][MINOR] [ColonyManager.java#L606](https://github.com/Minecolonies/minecolonies/blob/b2bf8870fa916853b65342fd1ffd57705e62cb67/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L606): Use a logger to log this exception. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1148)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 42 issues
* ![MAJOR][MAJOR] 4 major
* ![MINOR][MINOR] 38 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ColonyManager.java#L41](https://github.com/Minecolonies/minecolonies/blob/5ddac6ad27610fc28cccbebf2ca4bdb01716464b/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L41): class "ColonyManager" has 50 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ColonyManager.java#L604](https://github.com/Minecolonies/minecolonies/blob/5ddac6ad27610fc28cccbebf2ca4bdb01716464b/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L604): Either log or rethrow this exception. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1166)
1. ![MINOR][MINOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/5ddac6ad27610fc28cccbebf2ca4bdb01716464b/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/5ddac6ad27610fc28cccbebf2ca4bdb01716464b/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render#](https://github.com/Minecolonies/minecolonies/blob/5ddac6ad27610fc28cccbebf2ca4bdb01716464b/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/5ddac6ad27610fc28cccbebf2ca4bdb01716464b/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [ColonyManager.java#L180](https://github.com/Minecolonies/minecolonies/blob/5ddac6ad27610fc28cccbebf2ca4bdb01716464b/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L180): Make this line start at column 21. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AIndentationCheck)
1. ![MINOR][MINOR] [ColonyManager.java#L186](https://github.com/Minecolonies/minecolonies/blob/5ddac6ad27610fc28cccbebf2ca4bdb01716464b/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L186): Make this line start at column 25. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AIndentationCheck)
1. ![MINOR][MINOR] [ColonyManager.java#L188](https://github.com/Minecolonies/minecolonies/blob/5ddac6ad27610fc28cccbebf2ca4bdb01716464b/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L188): Make this line start at column 29. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AIndentationCheck)
1. ![MINOR][MINOR] [ColonyManager.java#L606](https://github.com/Minecolonies/minecolonies/blob/5ddac6ad27610fc28cccbebf2ca4bdb01716464b/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L606): Use a logger to log this exception. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1148)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/commands/generalcommands/CheckForAutoDeletesCommand.java [hunk 4]
```diff
@@ -46,6 +46,7 @@ public boolean canRankUseCommand(@NotNull final Colony colony, @NotNull final En
     @Override
     public void execute(@NotNull final MinecraftServer server, @NotNull final ICommandSender sender, @NotNull final String... args) throws CommandException
     {
+
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/commands/generalcommands/CheckForAutoDeletesCommand.java]: I think you can remove the whitespace again

Comment (RVOtakuMike) [reply src/main/java/com/minecolonies/coremod/commands/generalcommands/CheckForAutoDeletesCommand.java]: Woops, on it.

File: src/main/java/com/minecolonies/coremod/colony/ColonyManager.java [hunk 5]
```diff
@@ -174,6 +174,8 @@ public static void deleteColony(final int id)
                     colonyWorlds.add(world);
                 }
             }
+            if(canDestroy)
+            {
             Log.getLogger().info("Removing buildings for " + id);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/ColonyManager.java:179]: MINOR Make this line start at column 17. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AIndentationCheck)

File: src/main/java/com/minecolonies/coremod/colony/ColonyManager.java [hunk 6]
```diff
@@ -155,7 +155,7 @@ public static void markDirty()
      *
      * @param id the colonies id.
      */
-    public static void deleteColony(final int id)
+    public static void deleteColony(final int id, final boolean canDestroy)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/colony/ColonyManager.java:158]: MAJOR Provide multiple methods instead of using "canDestroy" to determine which action to take. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS2301)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 40 issues
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 37 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ColonyManager.java#L41](https://github.com/Minecolonies/minecolonies/blob/3a6d0d1656ebb4597fb277579974f9aca4fd8112/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L41): class "ColonyManager" has 50 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ColonyManager.java#L606](https://github.com/Minecolonies/minecolonies/blob/3a6d0d1656ebb4597fb277579974f9aca4fd8112/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L606): Either log or rethrow this exception. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1166)
1. ![MINOR][MINOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/3a6d0d1656ebb4597fb277579974f9aca4fd8112/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/3a6d0d1656ebb4597fb277579974f9aca4fd8112/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render#](https://github.com/Minecolonies/minecolonies/blob/3a6d0d1656ebb4597fb277579974f9aca4fd8112/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/3a6d0d1656ebb4597fb277579974f9aca4fd8112/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [ColonyManager.java#L182](https://github.com/Minecolonies/minecolonies/blob/3a6d0d1656ebb4597fb277579974f9aca4fd8112/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L182): Make this line start at column 21. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AIndentationCheck)
1. ![MINOR][MINOR] [ColonyManager.java#L188](https://github.com/Minecolonies/minecolonies/blob/3a6d0d1656ebb4597fb277579974f9aca4fd8112/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L188): Make this line start at column 25. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AIndentationCheck)
1. ![MINOR][MINOR] [ColonyManager.java#L190](https://github.com/Minecolonies/minecolonies/blob/3a6d0d1656ebb4597fb277579974f9aca4fd8112/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L190): Make this line start at column 29. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AIndentationCheck)
1. ![MINOR][MINOR] [ColonyManager.java#L608](https://github.com/Minecolonies/minecolonies/blob/3a6d0d1656ebb4597fb277579974f9aca4fd8112/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L608): Use a logger to log this exception. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1148)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/commands/colonycommands/DeleteColonyCommand.java [hunk 7]
```diff
@@ -58,8 +58,8 @@ public boolean canRankUseCommand(@NotNull final Colony colony, @NotNull final En
     public void execute(@NotNull final MinecraftServer server, @NotNull final ICommandSender sender, @NotNull final String... args) throws CommandException
     {
         final int colonyId;
-
-        if (args.length == 0)
+        boolean canDestroy = true;
+        if (args == null || args.length == 0)
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/commands/colonycommands/DeleteColonyCommand.java]: Sorry, we can remove that args == null check here again as well

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1642/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 40 issues
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 37 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ColonyManager.java#L41](https://github.com/Minecolonies/minecolonies/blob/3d86141157b53b330eaa663a87fe04736152760a/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L41): class "ColonyManager" has 50 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ColonyManager.java#L606](https://github.com/Minecolonies/minecolonies/blob/3d86141157b53b330eaa663a87fe04736152760a/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L606): Either log or rethrow this exception. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1166)
1. ![MINOR][MINOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/3d86141157b53b330eaa663a87fe04736152760a/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/3d86141157b53b330eaa663a87fe04736152760a/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render#](https://github.com/Minecolonies/minecolonies/blob/3d86141157b53b330eaa663a87fe04736152760a/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/3d86141157b53b330eaa663a87fe04736152760a/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [ColonyManager.java#L182](https://github.com/Minecolonies/minecolonies/blob/3d86141157b53b330eaa663a87fe04736152760a/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L182): Make this line start at column 21. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AIndentationCheck)
1. ![MINOR][MINOR] [ColonyManager.java#L188](https://github.com/Minecolonies/minecolonies/blob/3d86141157b53b330eaa663a87fe04736152760a/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L188): Make this line start at column 25. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AIndentationCheck)
1. ![MINOR][MINOR] [ColonyManager.java#L190](https://github.com/Minecolonies/minecolonies/blob/3d86141157b53b330eaa663a87fe04736152760a/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L190): Make this line start at column 29. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AIndentationCheck)
1. ![MINOR][MINOR] [ColonyManager.java#L608](https://github.com/Minecolonies/minecolonies/blob/3d86141157b53b330eaa663a87fe04736152760a/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L608): Use a logger to log this exception. [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1148)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Review by Asherslab — APPROVED** [review]
Good job, looks great!
