### PR TITLE
fix 8291

### LINKED ISSUE #8291: [BUG] nether miner doesn't take avalible food from racks
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.0.657-ALPHA

### Structurize Version

1.0.392-RELEASE

### Related Mods and their Versions

valhelsia 3 modpack with structurize and minecolonies updated to newest

### Current Behavior

the nether miner doesn't take any food from rack and keeps requesting more, if supplied manually doesn't start working

### Expected Behavior

the miner takes the food and does his job

### Reproduction Steps

not sure, i had a colony on older version of mods, updated minecolonies and structurize to resolve some unrelated issues, and netherminer not  working, after the update the netherminer started behaving incorrectly
versions before i updated
minecolonies-1.16.5-1.0.527-ALPHA
structurize-1.16.5-1.0.365-ALPHA

### Logs

https://gist.github.com/adam110902/988d75255dc42a554644de9fb0ba50d2

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #8291
Closes #
Closes #

# Changes proposed in this pull request:
- Make a checkOrRequest method for deliverables and make the netherminer use it.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java [hunk 1]
```diff
@@ -1586,6 +1586,42 @@ && getOwnBuilding().getCompletedRequestsOfTypeFiltered(worker.getCitizenData(),
...
     }
 
+    /**
+     * Check if a request exists for a given deliverable.
+     * @param deliverable the deliverable to check of request.
+     * @return true if available or transfered.
+     */
+    public boolean checkIfRequestForItemExistOrCreate(@NotNull final IDeliverable deliverable)
+    {
+        final int invCount = InventoryUtils.getItemCountInItemHandler(worker.getInventoryCitizen(), deliverable::matches);
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java:1595]: we had some better inv util for cases like these where you do not want to know the full count, but if it has at least X as that allows early stops

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java:1595]: We actually do want to know the full count so that we can calculate the difference

**Review by someaddons — APPROVED** [review]
