### PR TITLE
Fix to update shields with banner when changed

### LINKED ISSUE #11105: Shield / Banner mismatch
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [x] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.978

### Structurize Version

1.20.1-1.0.775

### Related Mods and their Versions

_No response_

### Current Behavior

The guard shields are not showing the colony banner properly, and changing the colony banner does not change the shields. (yes, I know it's not latest-latest, but I haven't seen this issue reported before.)

Original banner:
Image

Shield:
Image

Shield item info:
Image

Changed colony banner: 
Image

Banner itself showing correctly:
Image

### Expected Behavior

I expect the shield to match the colony banner

### Reproduction Steps

1. Create colony banner with tinyflowers
2. layers below tinyflowers don't show on shield
3. change banner in TH
4. shield doesn't change

### Logs

https://gist.github.com/AnyankaT/98125ad18060bd1271759b6044848a2d

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by buffdelta**
Fixes #11105.

# Changes proposed in this pull request
- Fixed guard shield banners to switch to the new colony flag whenever a ColonyFlagMessage is executed.
- There are still a few issues with the guard shield banners where if the shield is picked up by or placed into their inventory, the shield banner will not change to the colony flag. Also, if you take the shield out of their inventory the guard will still have it equipped, and the shield will not update to the correct state. I figured these could be fixed in a subsequent PR.

## Testing
- [x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/core/network/messages/server/colony/ColonyFlagChangeMessage.java [hunk 1]
```diff
@@ -44,6 +52,18 @@ public ColonyFlagChangeMessage(IColony colony, ListTag patternList)
     protected void onExecute(NetworkEvent.Context ctxIn, boolean isLogicalServer, IColony colony)
     {
         colony.setColonyFlag(patterns);
+        for (ICitizenData citizen : colony.getCitizenManager().getCitizens())
```
Comment (Thodor12) [inline src/main/java/com/minecolonies/core/network/messages/server/colony/ColonyFlagChangeMessage.java]: In the eye of "separation of concern", this is the wrong place to put this. This should realistically live inside `colony.setFlag` and preferably should be more dynamic over just doing "instanceof JobKnight"

Comment (Raycoms) [reply src/main/java/com/minecolonies/core/network/messages/server/colony/ColonyFlagChangeMessage.java]: I agree, I would add this in the set flag of the colony.
Additionally, the entity might not be loaded, so you need an isPresent check.

Comment (Thodor12) [reply src/main/java/com/minecolonies/core/network/messages/server/colony/ColonyFlagChangeMessage.java]: When you realize that you did the exact same thing and now commenting on someone else (who copied you) to fix it 😎

**Comment by buffdelta** [comment]
Is this more like what you are looking for? I modeled it after the [ExternalWorkStations](https://github.com/ldtteam/minecolonies/blob/version/main/src/main/java/com/minecolonies/api/colony/jobs/IJobWithExternalWorkStations.java) interface as I _think_ they do similar things. But, I don't know if this what you had in mind, or if the citizen manager function goes there, or should even exists as a function.

File: src/main/java/com/minecolonies/core/colony/jobs/JobKnight.java [hunk 2]
```diff
@@ -98,4 +99,15 @@ public boolean ignoresDamage(@NotNull final DamageSource damageSource)
         }
         return super.ignoresDamage(damageSource);
     }
+
+    @Override
+    public void onColonyFlagChanged()
+    {
+        final AbstractEntityCitizen worker = this.getCitizen().getEntity().get();
+        CitizenItemUtils.setHeldItem(worker, InteractionHand.OFF_HAND, InventoryUtils.findFirstSlotInItemHandlerWith(this.getCitizen().getInventory(), Items.SHIELD));
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/core/colony/jobs/JobKnight.java]: the worker could still be null here due to chunk loading. Still needs ispresent check

**Review by Thodor12 — APPROVED** [review]

**Review by someaddons — APPROVED** [review]

**Comment by someaddons** [comment]
nvm
