### PR TITLE
Fix/colonypermissions

### LINKED ISSUE #2163: NPE in the fill bucket event
Sometimes I get this NPE on my server, happened twice today: 

```
Caused by: java.lang.NullPointerException
at com.minecolonies.coremod.permissions.ColonyPermissionEventHandler.on(ColonyPermissionEventHandler.java:410) ~[ColonyPermissionEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_450_ColonyPermissionEventHandler_on_FillBucketEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:651) ~[EventBus.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:589) ~[EventBus.class:?]
at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:434) ~[ForgeEventFactory.class:?]
at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:43) ~[ahi.class:?]
at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) ~[or.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:763) ~[pa.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) ~[PacketUtil.class:1.12.2-2586-7.1.0-BETA-2884]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkp000(SourceFile:539) ~[hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
... 7 more
```

### PR DESCRIPTION
**Pull request by mkienenb**
Closes #2163

Changes proposed in this pull request:
-  Perform checkstyle cleanup.
- Add missing javadocs.
- Ignore eclipse .checkstyle settings file
-  Fixes issue #2163 where clicking with a bucket and no target caused an NPE.
   I also reviewed the code but did not find any other potential NPE locations.

### CODE REVIEW

**Comment by Raycoms** [comment]
Looking good
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/2167/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Review by Raycoms — APPROVED** [review]

File: src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java [hunk 1]
```diff
@@ -44,6 +48,9 @@
 public class ColonyPermissionEventHandler
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java:48]: MAJOR Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 36 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 53 issues
* ![MAJOR][MAJOR] 52 major
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/ab1b07d17bb7992d22810d076e46a1a3628633dc/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/ab1b07d17bb7992d22810d076e46a1a3628633dc/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/ab1b07d17bb7992d22810d076e46a1a3628633dc/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/ab1b07d17bb7992d22810d076e46a1a3628633dc/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/ab1b07d17bb7992d22810d076e46a1a3628633dc/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [permissions#](https://github.com/Minecolonies/minecolonies/blob/ab1b07d17bb7992d22810d076e46a1a3628633dc/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [requestable#](https://github.com/Minecolonies/minecolonies/blob/ab1b07d17bb7992d22810d076e46a1a3628633dc/src/main/java/com/minecolonies/coremod/colony/requestable#): Add a 'package-info.java' file to document the 'requestable' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [data#](https://github.com/Minecolonies/minecolonies/blob/ab1b07d17bb7992d22810d076e46a1a3628633dc/src/main/java/com/minecolonies/coremod/colony/requestsystem/data#): Add a 'package-info.java' file to document the 'data' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [init#](https://github.com/Minecolonies/minecolonies/blob/ab1b07d17bb7992d22810d076e46a1a3628633dc/src/main/java/com/minecolonies/coremod/colony/requestsystem/init#): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [locations#](https://github.com/Minecolonies/minecolonies/blob/ab1b07d17bb7992d22810d076e46a1a3628633dc/src/main/java/com/minecolonies/coremod/colony/requestsystem/locations#): Add a 'package-info.java' file to document the 'locations' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Review by marchermans — APPROVED** [review]
