### PR TITLE
Fix food interaction & food smelting

### LINKED ISSUE #6929: Cook Cooking/Distributing Foods Not in Hut's Food List
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5.36.1.2
- MineColonies Version: minecolonies-0.14.100-ALPHA-universal.jar
- Structurize Version: structurize-0.13.163-ALPHA-universal.jar (Latest not compatible with Latest MineColonies)
- Related Mods and their Versions: ATM6 1.5.10b

## Expected behavior

Cook distributes only the food items on the list of food in the hut, and only makes said food items and requested items in recipe list (using fruit salad from harvest craft for compost, for example).

## Actual behavior

Cook makes requested foods, like fruit salad, but made 1300 when min stock is set to 4 stacks (256), which I understand is min stock, so maybe intended, but the cook is baking and distributing baked potatoes when they are not selected in the food list. Actually, the cook has done this with mutton, requesting it and cooking it even though the food list was not set to distribute cooked mutton. I have not tested this with other foods, but, it seems to be baked (furnace) foods only that this happens with. Seemingly the recipes for furnace food override or take priority over the huts food list.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

My colony is at 41/51 colonists, the town hall is at 4, the restaurant is at 4.

I thought perhaps it was related to a full warehouse, and the couriers moving stock out to the buildings, but, even with an empty warehouse, this happens.

The colonists were requesting better food, even though both baked potato and cooked mutton have less overall saturation, so, I am not sure it is related.

This would not be a problem, except the healer needs potatoes to cure the flu.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #6957: People complaining about low quality foods in their inventory
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

People complain about bad foods too much, even if they produce them, or they pick some up:
- Farmer, herders and fishers complain about raw crops and meats that they produced, and deny to eat that, meaning most of my workers will yell to my ear about foods
- Guards complains everytime they pick up some rotten flesh from killing zombies
Also, there are some instances where there are better foods already in their inventory, but they only focus on the bad stuff, then upset about it. There can be breads present in the inventory and the citizen wouldn't touch it

I forgot to take pictures sorry

## Steps to reproduce the issue

Could be replicate by giving a mixture of bad and good foods to the citizen. Otherwise just watch them, as they work this problem will occur

### Logs

- latest.log: 
- crashlog: 

### Notes

Really just want things to be changed into the old ways so that I can start dumping stacks of cheese in the restaurant again. Please have an option for it.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by vroni92**
Closes #6929
Closes #6957
Closes #

# Changes proposed in this pull request:
- Fix food interactions *again* (should now definitely not display when valid food is in inventory)
- Don't smelt food that's not on the menu
- Don't keep smeltable food that's not on the menu

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java [hunk 1]
```diff
@@ -121,7 +122,8 @@
     public BuildingCook(final IColony c, final BlockPos l)
     {
         super(c, l);
-        keepX.put((stack) -> !this.getModuleMatching(ItemListModule.class, m -> m.getId().equals(FOOD_EXCLUSION_LIST)).isItemInList(new ItemStorage(stack)), new Tuple<>(STACKSIZE, true));
+        keepX.put((stack) -> !this.getModuleMatching(ItemListModule.class, m -> m.getId().equals(FOOD_EXCLUSION_LIST)).isItemInList(new ItemStorage(stack))
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCook.java]: If we query this search twice, we should probably cache the result

File: src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java [hunk 2]
```diff
@@ -64,10 +64,12 @@ public static void init()
                        && InventoryUtils.findFirstSlotInItemHandlerNotEmptyWith(citizen.getInventory(), stack -> CAN_EAT.test(stack) && (citizen.getWorkBuilding() == null || citizen.getWorkBuilding().canEat(stack))) == -1);
         InteractionValidatorRegistry.registerStandardPredicate(new TranslationTextComponent(BETTER_FOOD),
           citizen -> InventoryUtils.findFirstSlotInItemHandlerNotEmptyWith(citizen.getInventory(),
-                  stack -> CAN_EAT.test(stack) && !(citizen.getWorkBuilding() == null || citizen.getWorkBuilding().canEat(stack))) != -1 && !citizen.isChild());
+                  stack -> CAN_EAT.test(stack) && !(citizen.getWorkBuilding() == null || citizen.getWorkBuilding().canEat(stack))) != -1 && InventoryUtils.findFirstSlotInItemHandlerNotEmptyWith(citizen.getInventory(),
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java]: make this a big lambda, 

stack -> {

}

Also, there seems something off, in the findFirstSlotInItemHandler we also do findFirstSlotInItemHandler?
I think the negation of the entire ( ) probably creates confusion, we should rewrite this more understandably

File: src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java [hunk 3]
```diff
@@ -63,13 +63,9 @@ public static void init()
           citizen -> InventoryUtils.findFirstSlotInItemHandlerNotEmptyWith(citizen.getInventory(), ISCOOKABLE) != -1
                        && InventoryUtils.findFirstSlotInItemHandlerNotEmptyWith(citizen.getInventory(), stack -> CAN_EAT.test(stack) && (citizen.getWorkBuilding() == null || citizen.getWorkBuilding().canEat(stack))) == -1);
         InteractionValidatorRegistry.registerStandardPredicate(new TranslationTextComponent(BETTER_FOOD),
-          citizen -> InventoryUtils.findFirstSlotInItemHandlerNotEmptyWith(citizen.getInventory(),
-                  stack -> CAN_EAT.test(stack) && !(citizen.getWorkBuilding() == null || citizen.getWorkBuilding().canEat(stack))) != -1 && InventoryUtils.findFirstSlotInItemHandlerNotEmptyWith(citizen.getInventory(),
-                  stack -> CAN_EAT.test(stack) && (citizen.getWorkBuilding() == null || citizen.getWorkBuilding().canEat(stack))) == -1 && !citizen.isChild());
+          citizen -> citizen.needsBetterFood() && !citizen.isChild());
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/apiimp/initializer/InteractionValidatorInitializer.java]: first the isChild check, that one is cheaper

**Review by someaddons — APPROVED** [review]
