### PR TITLE
Restaurant sitting and some fixes

### LINKED ISSUE #6263: Bad values listed in config file for average number of nights between raids
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 525
- Structurize Version: 104

### Notes

My minecolonies-server.toml configuration file lists the following line:

`#The average number of nights between raids. [Default: 12, min: 1, max: 10]`

Default is greater than max?

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by someaddons**
Closes #6263

# Changes proposed in this pull request:
Adds sitting within restaurants, at predefined positions. Now citizens after receiving their food go to a sitting place, idle there for a bit and then eat. Also improved sitting logic a bit, now the entities take the shape of the block we want to sit on into consideration and adjust the Y level accordingly.

Studying childs now hold paper in their hands.
Improve set blockstate performance by bypassing vanilla's loop of all entity navigators, all other logic is done as usual, just that specific wont run.

Fix average raid config default

Review please

### CODE REVIEW

File: src/api/java/com/minecolonies/api/entity/citizen/AbstractEntityCitizen.java [hunk 1]
```diff
@@ -148,10 +148,22 @@ public BlockPos getPosition()
...
+        return false;
+    }
+
+    /**
+     * Disable vanilla steering logic for villagers
+     */
+    @Override
+    public boolean canPassengerSteer()
+    {
+        return false;
```
Comment (Raycoms) [inline src/api/java/com/minecolonies/api/entity/citizen/AbstractEntityCitizen.java:166]: wasn't there an elytra one too, to disable too?

Comment (someaddons) [reply src/api/java/com/minecolonies/api/entity/citizen/AbstractEntityCitizen.java:166]: elytra is private, so can't override

Comment (Raycoms) [reply src/api/java/com/minecolonies/api/entity/citizen/AbstractEntityCitizen.java:166]: AT =D
