### PR TITLE
Check level 1 for rotation if there's no level 0

### LINKED ISSUE #8743: [BUG] Schematics that are part of another schematic are not rotated.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1088-ALPHA

### Structurize Version

1.0.459-ALPHA

### Related Mods and their Versions

Forge version 43.1.13

### Current Behavior

Reproduced in Shire style with restaurant that is part of the tavern. Here in a creative test world I have 4 taverns in all possible rotations and as you can see the restaurant in all of them is built in the same direction and ignores rotation of the tavern:

Here's example in actual world:

### Expected Behavior

Restaurant schematic is rotated relative to the tavern.

### Reproduction Steps

1. Place 4 taverns each having a different rotation
2. Order builders to build taverns
3. Order builders to build restaurants.
4. Profit

### Logs

https://gist.github.com/janisl/7661d6e97ae6a4ffb54591022846bf7e

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #8808: Barracks showing errors in logs, every hour
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1132-BETA

### Structurize Version

1.0.467-BETA

### Related Mods and their Versions

Forge: 43.1.65
BlockUI: 0.0.64-ALPHA
Domum Ornamemtum: 1.0.75-ALPHA
MultiPiston: 1.2.21-ALPHA
MineColonies: 1.0.1132-BETA
Structurize: 1.0.467-BETA

### Reproduction Steps

Building barracks in Lost City Schema and review logs

### Logs

https://pastebin.com/TsGWtVSy

### Anything else?

No one is logged into the server but every hour it is throwing errors on the barracks build.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by uecasm**
~~Apparently doesn't #8808~~
Closes [discord report](https://discord.com/channels/139070364159311872/1003402487417548801/1050814935422210169)
Closes #8743 ~~(most likely, but not explicitly tested)~~

# Changes proposed in this pull request:
- Check the level 1 blueprint to determine rotation if a level 0 is not found.

Review please (do not backport)

### CODE REVIEW

**Comment by someaddons** [comment]
From those logs:
```
[08Dec2022 01:00:03.911] [Server thread/ERROR] [minecolonies/]: Failed to get rotation for military/lostcitybarrackstower1.blueprint: 
[08Dec2022 01:00:03.911] [Server thread/ERROR] [minecolonies/]: Failed to get rotation for military/lostcitybarrackstower2.blueprint: 
[08Dec2022 01:00:03.911] [Server thread/ERROR] [minecolonies/]: Failed to get rotation for military/lostcitybarrackstower3.blueprint: 
[08Dec2022 02:00:03.921] [Server thread/ERROR] [minecolonies/]: Failed to get rotation for military/lostcitybarrackstower1.blueprint: 
[08Dec2022 02:00:03.921] [Server thread/ERROR] [minecolonies/]: Failed to get rotation for military/lostcitybarrackstower2.blueprint: 
[08Dec2022 02:00:03.921] [Server thread/ERROR] [minecolonies/]: Failed to get rotation for military/lostcitybarrackstower3.blueprint: 
[08Dec2022 03:00:03.909] [Server thread/ERROR] [minecolonies/]: Failed to get rotation for military/lostcitybarrackstower1.blueprint
```
I dont think this will fix it, since they already try for higher levels but do not find it

**Comment by MotionlessTrain** [comment]
It will fix a similar report on discord (https://discord.com/channels/139070364159311872/1003402487417548801/1050814935422210169)

The one in #8808 seems like a weird schematic bug (there is no lostcitybarrackstower* schematic that I know of)
Rather, it seems that during the creation of the lostcity barracks, the barracks towers that have been included were called like that. I didn't know that during scanning of lostcity, so I called them barrackstower. This hasn't been a big issue, since they autoupgrade, but it is now visible in the logs

**Comment by uecasm** [comment]
Tested 8743 now and this does appear to fix it.  Caveat: existing buildings _might_ have saved the wrong rotation value.  If you're still getting the rotation error message in the logs periodically then you're ok, but if it stopped doing that (e.g. if you did build it to L1+) then it might have saved the wrong rotation.  If things build weird even after this fix, then you'll need to break the child hut blocks and repair the parent.

File: src/main/java/com/minecolonies/coremod/colony/buildings/AbstractSchematicProvider.java [hunk 1]
```diff
@@ -369,7 +369,11 @@ public int getRotation()
 
         try
         {
-            final Blueprint blueprint = StructurePacks.getBlueprint(this.structurePack, this.path, true);
+            Blueprint blueprint = StructurePacks.getBlueprint(this.structurePack, this.path, true);
+            if (blueprint == null && this.path.endsWith("0.blueprint"))
```
Comment (MotionlessTrain) [inline src/main/java/com/minecolonies/coremod/colony/buildings/AbstractSchematicProvider.java:373]: It looks like paths of pasted hut blocks don't end in ".blueprint" at the moment. The log of the discord report also mentions that the path is "military/altbarrackstower0". So this `if` condition may still fail in that case.
(Not sure if that is a bug or an intended change on Structurize's side)

**Comment by Raycoms** [comment]
I recently added something for that already

Sent from Proton Mail mobile

-------- Original Message --------
