### PR TITLE
Raiders and other Fixes

### LINKED ISSUE #4684: Darn raiders poping in middle of village
### Minecolonies version
Minecolonies: 0.11.802-BETA
Minecraft : 1.15.2
Forge: 31.1.35

### Expected behavior
A horde of darn raiders coming from the direction written in the logs

### Actual behaviour
[16:16:40] [Render thread/INFO]: [CHAT] §4Buckle up cowboy! There's some darn raiders comin' for DiabolosMan's Colony tonight, from North/West!
...
**37s later...**
DarnRaiderAttack

... 
[16:17:17] [Render thread/INFO]: [CHAT]  The Deliveryman Ruth N. Goddam has died at -873 70 -674 of entity.minecolonies.barbarian!
[16:17:17] [Render thread/INFO]: [CHAT] There has been a death in the colony. The colony will mourn Ruth N. Goddam tomorrow out of respect.
[16:17:25] [Render thread/INFO]: [CHAT]  The Healer Blanche I. Askew has died at -884 70 -663 of entity.minecolonies.barbarian!
[16:17:25] [Render thread/INFO]: [CHAT] There has been a death in the colony. The colony will mourn Blanche I. Askew tomorrow out of respect.
[16:17:35] [Render thread/INFO]: [CHAT] tile.blockhuttownhall.messagecolonistdead
[16:17:35] [Render thread/INFO]: [CHAT] There has been a death in the colony. The colony will mourn Wyatt O. Glennon tomorrow out of respect.
[16:17:41] [Render thread/INFO]: [CHAT]  The Builder Curtis W. Askew has died at -862 71 -674 of entity.minecolonies.barbarian!
[16:17:41] [Render thread/INFO]: [CHAT] There has been a death in the colony. The colony will mourn Curtis W. Askew tomorrow out of respect.
[16:17:46] [Render thread/INFO]: [CHAT]  The Farmer Hazel K. Glennon has died at -939 70 -535 of entity.minecolonies.barbarian!
[16:17:46] [Render thread/INFO]: [CHAT] There has been a death in the colony. The colony will mourn Hazel K. Glennon tomorrow out of respect.
[16:17:48] [Render thread/INFO]: [CHAT]  The Baker Brooklyn O. Clitherow has died at -889 70 -599 of entity.minecolonies.barbarian!
[16:17:48] [Render thread/INFO]: [CHAT] There has been a death in the colony. The colony will mourn Brooklyn O. Clitherow tomorrow out of respect.
[16:17:54] [Render thread/INFO]: [CHAT]  The Cook Victoria A. Askew has died at -876 70 -642 of entity.minecolonies.barbarian!
[16:17:54] [Render thread/INFO]: [CHAT] There has been a death in the colony. The colony will mourn Victoria A. Askew tomorrow out of respect.
...

I have a fortification all around my village and it is imposible that in 30s they kill all my villagers. They poped inside my village. This was awful. Is it possible to have a check to ensure that they pop at least at a minimum distance from town hall ?

### LINKED ISSUE #4697: BuildTool: building is null
### Minecolonies version

Version: minecolonies-0.11.827-ALPHA

### Expected behavior

Use building Tool to place Town Hall block, and not error

### Actual behaviour

- Tow Hall block is disappear
- Get "Start Your Colony" advancement
- Server error

### Steps to reproduce the problem

1. Use building tool place Town Hall

### Logs: Latest.log and crashlog at https://gist.github.com/

image

### LINKED ISSUE #4705: Leaving a colony message each time we log in for a colony over spawn area
### Minecolonies version
All versions since a long time

### Expected behavior
No chat message everytime we log in about leaving the colony of another player that set it on spawn area

### Actual behaviour
[13:28:11] [Render thread/INFO]: Connecting to ##########.omgcraft.fr., 10037
[13:28:41] [Render thread/INFO]: Starting JEI...
.... Many logs.....
[13:28:45] [Render thread/INFO]: Starting JEI took 4.227 s
[13:28:46] [Render thread/INFO]: [CHAT] Farewell, you're leaving nicotontige's colony.

### Steps to reproduce the problem
1) Have a player setting a colony closed to the spawn :-(.   
2) Another player connect to the server, he always have the notification he is leaving the colony of this player

### PR DESCRIPTION
**Pull request by someaddons**
Closes #4705
Closes #4697
Closes #4684

# Changes proposed in this pull request:

Add support for random pirate ship rotations, disabled for now till spawners are within schematics.
Add pathing options, which contains stuff like custom weights and wether swimming/rails etc is allowed
Raiders have a lower height cost, and pirates a lower swim cost.
Added water-enter cost, which is high and reduced water cost when already swimming

Fix: Raids initial spawn position got reworked, no longer spawns in the middle of a colony and is more randomly distributed now. The spawn pos is more dynamic now depending on loaded buildings and keeps a min distance to buildings. 
Fix: replace deprecated isBlockLoaded with isBlockPresent
Fix: Pirates spawning on the very top of their ships
Fix: Lumberjack now does cut down leaves in his way, previously he was stuck in pathing before trying to do so.
Fix: Water pathing sometimes running off, due to our paths beeing 1block above the water and the entity getting stuck in jumping, no longer accepting other movement.
Fix: Pathing jumps with slabs & co
Fix: Pathing not working when the destination wasnt reached, now uses the closes node.
Fix: Pathing not properly flagging the starting node as swimming/rails
Fix: Pathing sometimes early-outing a different node than intended, causing iffy pathing occasionally
Fix: Error upon placing townhall with building tool and no colony

Review please

### CODE REVIEW

File: src/api/java/com/minecolonies/api/entity/pathfinding/PathingOptions.java [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+
+    public PathingOptions withStartSwimCost(final double startSwimCost)
+    {
+        SWIM_COST_ENTER = startSwimCost;
+        return this;
+    }
+
+    public PathingOptions withSwimCost(final double swimCost)
+    {
+        SWIM_COST = swimCost;
```
Comment (Raycoms) [inline src/api/java/com/minecolonies/api/entity/pathfinding/PathingOptions.java]: If they are not constants, lowercase

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingTownHall.java [hunk 2]
```diff
@@ -113,10 +113,6 @@ public void serializeToView(@NotNull final PacketBuffer buf)
     @Override
     public int getClaimRadius(final int newLevel)
     {
-        if (newLevel + 1 < MineColonies.getConfig().getCommon().minTownHallPadding.get())
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingTownHall.java:116]: Why was this removed?

**Review by marchermans — COMMENTED** [review]
A simple question, if answered then this is ready.

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingTownHall.java (hunk 2 above)
Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingTownHall.java:116]: ah because we're always claiming the initial radius when creating the colony now
