### PR TITLE
Guard armor/dimension change fixes

### LINKED ISSUE #10653: Path issue, server spam, guard went through tempad portal
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [x] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.800

### Structurize Version

1.20.1-1.0.763

### Related Mods and their Versions

Forge: 47.2.23
Modpack: https://www.curseforge.com/minecraft/modpacks/wolf-craft-colonies

### Current Behavior

Not really a bug, but something I thought you should know.

There was a message spamming the server (snippet in log below). A knight was trying to tp 9000 blocks. I went to him and found him in someone else's colony, next to their waystone. I went to the point they were trying to tp to, it was the Knight's hut block, at another player's colony 9000 blocks away. I made myself an officer and I could recall him to the hut block. His settings were on 'patrol', not 'follow'. I am assuming the knight must have walked into a tempad portal (https://www.curseforge.com/minecraft/mc-mods/tempad) after the owner of the colony used it.

### Expected Behavior

I am hoping you can make it so citizens cannot be teleported by tempads or other external non-minecolonies mods if they are not in 'follow' mode (where it is intentional).
I'm assuming this will be difficult when combined with their need to tp at times.
I acknowledge it is the player's responsibility to ensure they don't leave portals around their colony for citizens to walk into, but it would be great if there was a simple way to stop it happening (which is beyond my skill set to know).

### Reproduction Steps

Make a tempad and teleport to another location
Have a citizen walk into the portal
Observe message spam as the poor citizen just tries to get home.

### Logs

https://gist.github.com/kezmodius/7ed83845f7585a80fafc851306824f6e

### Anything else?

I only saw the console spam as I was searching for a different incident. It started and stopped when the player was in their colony where the guard had been tp-ed to. I could search through the logs to find when it happened initially if you need.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by someaddons**
Closes #10653
Closes #

# Changes proposed in this pull request
- Prevent entity dimension changes
- Fix guards not unequipping armor after loosing their job
- Improve raidmanager logging for raids on colonies without loaded buildings

## Testing
- [x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/core/colony/jobs/AbstractJobGuard.java [hunk 1]
```diff
@@ -74,11 +77,29 @@ public void initEntityValues(AbstractEntityCitizen citizen)
...
+    @Override
+    public void onRemoval()
+    {
+        super.onRemoval();
+
+        if (this.getCitizen().getEntity().isPresent())
+        {
+            final Mob citizenEntity = getCitizen().getEntity().get();
+            // Unequip armor and weapons
+            citizenEntity.setItemSlot(EquipmentSlot.MAINHAND, ItemStackUtils.EMPTY);
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/core/colony/jobs/AbstractJobGuard.java]: This shouldn't work =D If we wanna unequip, then we move the stuff from the armor slots in the citizendata to the normal inventory

**Review by Raycoms — APPROVED** [review]
