### PR TITLE
Fix/builder supply camp

### LINKED ISSUE #577: Builder is refusing Grass
### Minecolonies version

MineColonies TestPack 0.6.3 (MineColonies 1.10.2-0.6.2724)

### Expected behavior

- Places block on both Dirt and Grass

### Actual behaviour

- Breaks Grass and replace it into Dirt

### LINKED ISSUE #840: Supply Camp as Decoration Can't be built.
When trying to build the Supply Camp as a decoration Builder will just stand there and do nothing.
Builder has all the materials in the list (pg. 2 GUI), and even the space required is cleared and clean.
Fire/Hire will reset him to go back and stare at the spot eternally. 
Several Minecraft days and fire/hire again.. same thing.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #577 
Closes #840

# Changes proposed in this pull request:
- Fixes problems with grass/dirt/variants being equally or not.
- Fixes problem with building fire (requires flint and steel now)

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 1]
```diff
@@ -750,6 +751,15 @@ private boolean handleMaterials(@NotNull final Block block, @NotNull final IBloc
             return true;
         }
 
+        if(block == Blocks.FIRE)
+        {
+            if(checkOrRequestItems(false, new ItemStack(Items.FLINT_AND_STEEL, 1)))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MINOR Replace this if-then-else statement by a single return statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1126)

File: src/main/java/com/minecolonies/coremod/util/BlockUtils.java [hunk 2]
```diff
@@ -212,6 +216,41 @@ public static ItemStack getItemStackFromBlockState(@NotNull final IBlockState bl
...
+        if((structureBlock == Blocks.DIRT || structureBlock == Blocks.GRASS) && (worldBlock == Blocks.DIRT || worldBlock == Blocks.GRASS))
+        {
+            if(structureBlock == Blocks.DIRT
+                    && (structureMetaData.getValue(BlockDirt.VARIANT) == BlockDirt.DirtType.COARSE_DIRT
+                    || worldMetadata.getValue(BlockDirt.VARIANT) == BlockDirt.DirtType.PODZOL))
+            {
+                return false;
+            }
+
+            if(worldBlock == Blocks.DIRT
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/util/BlockUtils.java]: MINOR Replace this if-then-else statement by a single return statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1126)

File: src/main/java/com/minecolonies/coremod/util/BlockUtils.java [hunk 3]
```diff
@@ -212,6 +216,41 @@ public static ItemStack getItemStackFromBlockState(@NotNull final IBlockState bl
...
+                return false;
+            }
+
+            return true;
+        }
+        return  false;
+    }
+
+
     private static Item getItem(@NotNull final IBlockState blockState)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/util/BlockUtils.java:249]: MAJOR This method has 142 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS138)
MAJOR Reduce the number of returns of this method 32, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
MAJOR The Cyclomatic Complexity of this method "getItem" is 41 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
MAJOR Refactor this method to reduce its Cognitive Complexity from 66 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

File: src/main/java/com/minecolonies/coremod/util/StructureWrapper.java [hunk 4]
```diff
@@ -3,13 +3,13 @@
...
 import com.minecolonies.coremod.configuration.Configurations;
 import com.minecolonies.structures.helpers.StructureProxy;
-import net.minecraft.block.Block;
-import net.minecraft.block.BlockDoor;
-import net.minecraft.block.BlockStairs;
+import net.minecraft.block.*;
 import net.minecraft.block.state.IBlockState;
 import net.minecraft.client.Minecraft;
 import net.minecraft.init.Blocks;
+import net.minecraft.init.Items;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/util/StructureWrapper.java]: MINOR Remove this unused import 'net.minecraft.init.Items'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 112 issues
* ![CRITICAL][CRITICAL] 5 critical
* ![MAJOR][MAJOR] 45 major
* ![MINOR][MINOR] 56 minor
* ![INFO][INFO] 6 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractJob.java#L328](https://github.com/Minecolonies/minecolonies/blob/77f906d483abb78857d3bb121a4a7a1379de37e0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L328): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractEntityAIStructure.java#L256](https://github.com/Minecolonies/minecolonies/blob/77f906d483abb78857d3bb121a4a7a1379de37e0/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L256): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![CRITICAL][CRITICAL] [AbstractEntityAIStructure.java#L302](https://github.com/Minecolonies/minecolonies/blob/77f906d483abb78857d3bb121a4a7a1379de37e0/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L302): Reduce the number of conditional operators (7) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![CRITICAL][CRITICAL] [AbstractEntityAIStructure.java#L831](https://github.com/Minecolonies/minecolonies/blob/77f906d483abb78857d3bb121a4a7a1379de37e0/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L831): Reduce the number of conditional operators (7) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![CRITICAL][CRITICAL] [BlockUtils.java#L296](https://github.com/Minecolonies/minecolonies/blob/77f906d483abb78857d3bb121a4a7a1379de37e0/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L296): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [AbstractJob.java#L50](https://github.com/Minecolonies/minecolonies/blob/77f906d483abb78857d3bb121a4a7a1379de37e0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L50): Remove this reference to "JobPlaceholder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L51](https://github.com/Minecolonies/minecolonies/blob/77f906d483abb78857d3bb121a4a7a1379de37e0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L51): Remove this reference to "JobBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L52](https://github.com/Minecolonies/minecolonies/blob/77f906d483abb78857d3bb121a4a7a1379de37e0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L52): Remove this reference to "JobDeliveryman". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L53](https://github.com/Minecolonies/minecolonies/blob/77f906d483abb78857d3bb121a4a7a1379de37e0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L53): Remove this reference to "JobMiner". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L54](https://github.com/Minecolonies/minecolonies/blob/77f906d483abb78857d3bb121a4a7a1379de37e0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L54): Remove this reference to "JobLumberjack". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 118 issues
* ![CRITICAL][CRITICAL] 5 critical
* ![MAJOR][MAJOR] 51 major
* ![MINOR][MINOR] 55 minor
* ![INFO][INFO] 7 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractJob.java#L328](https://github.com/Minecolonies/minecolonies/blob/4ce3820b0a0125b808da919334791fb0fc57580b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L328): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractEntityAIStructure.java#L256](https://github.com/Minecolonies/minecolonies/blob/4ce3820b0a0125b808da919334791fb0fc57580b/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L256): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![CRITICAL][CRITICAL] [AbstractEntityAIStructure.java#L302](https://github.com/Minecolonies/minecolonies/blob/4ce3820b0a0125b808da919334791fb0fc57580b/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L302): Reduce the number of conditional operators (7) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![CRITICAL][CRITICAL] [AbstractEntityAIStructure.java#L832](https://github.com/Minecolonies/minecolonies/blob/4ce3820b0a0125b808da919334791fb0fc57580b/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L832): Reduce the number of conditional operators (7) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![CRITICAL][CRITICAL] [BlockUtils.java#L291](https://github.com/Minecolonies/minecolonies/blob/4ce3820b0a0125b808da919334791fb0fc57580b/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L291): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [AbstractJob.java#L50](https://github.com/Minecolonies/minecolonies/blob/4ce3820b0a0125b808da919334791fb0fc57580b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L50): Remove this reference to "JobPlaceholder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L51](https://github.com/Minecolonies/minecolonies/blob/4ce3820b0a0125b808da919334791fb0fc57580b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L51): Remove this reference to "JobBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L52](https://github.com/Minecolonies/minecolonies/blob/4ce3820b0a0125b808da919334791fb0fc57580b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L52): Remove this reference to "JobDeliveryman". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L53](https://github.com/Minecolonies/minecolonies/blob/4ce3820b0a0125b808da919334791fb0fc57580b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L53): Remove this reference to "JobMiner". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L54](https://github.com/Minecolonies/minecolonies/blob/4ce3820b0a0125b808da919334791fb0fc57580b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L54): Remove this reference to "JobLumberjack". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 5]
```diff
@@ -851,8 +860,10 @@ private void placeBlockAt(@NotNull final Block block, @NotNull final IBlockState
         }
     }
 
-    private boolean placeBlock(@NotNull final BlockPos pos, final Block block, @NotNull final IBlockState blockState)
+    private boolean placeBlock(@NotNull final BlockPos pos, final Block block, @NotNull final IBlockState state)
     {
+        @NotNull IBlockState stateToPlace = state;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MAJOR This method has 144 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS138)
MAJOR Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
MAJOR The Cyclomatic Complexity of this method "placeBlock" is 46 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
MAJOR Refactor this method to reduce its Cognitive Complexity from 53 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 118 issues
* ![CRITICAL][CRITICAL] 5 critical
* ![MAJOR][MAJOR] 51 major
* ![MINOR][MINOR] 55 minor
* ![INFO][INFO] 7 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractJob.java#L328](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L328): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractEntityAIStructure.java#L256](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L256): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![CRITICAL][CRITICAL] [AbstractEntityAIStructure.java#L302](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L302): Reduce the number of conditional operators (7) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![CRITICAL][CRITICAL] [AbstractEntityAIStructure.java#L832](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L832): Reduce the number of conditional operators (7) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![CRITICAL][CRITICAL] [BlockUtils.java#L291](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L291): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [AbstractJob.java#L50](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L50): Remove this reference to "JobPlaceholder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L51](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L51): Remove this reference to "JobBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L52](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L52): Remove this reference to "JobDeliveryman". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L53](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L53): Remove this reference to "JobMiner". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L54](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L54): Remove this reference to "JobLumberjack". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 6]
```diff
@@ -851,8 +860,10 @@ private void placeBlockAt(@NotNull final Block block, @NotNull final IBlockState
         }
     }
 
-    private boolean placeBlock(@NotNull final BlockPos pos, final Block block, @NotNull final IBlockState blockState)
+    private boolean placeBlock(@NotNull final BlockPos pos, final Block block, @NotNull final IBlockState state)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: MAJOR This method has 144 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS138)
MAJOR Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
MAJOR The Cyclomatic Complexity of this method "placeBlock" is 46 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
MAJOR Refactor this method to reduce its Cognitive Complexity from 53 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 117 issues
* ![CRITICAL][CRITICAL] 4 critical
* ![MAJOR][MAJOR] 51 major
* ![MINOR][MINOR] 55 minor
* ![INFO][INFO] 7 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractJob.java#L328](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L328): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractEntityAIStructure.java#L256](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L256): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![CRITICAL][CRITICAL] [AbstractEntityAIStructure.java#L302](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L302): Reduce the number of conditional operators (7) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![CRITICAL][CRITICAL] [BlockUtils.java#L291](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L291): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [AbstractJob.java#L50](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L50): Remove this reference to "JobPlaceholder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L51](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L51): Remove this reference to "JobBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L52](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L52): Remove this reference to "JobDeliveryman". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L53](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L53): Remove this reference to "JobMiner". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L54](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L54): Remove this reference to "JobLumberjack". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L55](https://github.com/Minecolonies/minecolonies/blob/4dc56b167fc1e2d7c9c013085d21328fa54e73eb/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L55): Remove this reference to "JobFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

**Comment by Raycoms** [comment]
@Kostronor @cltnschlosser

File: src/main/java/com/minecolonies/coremod/util/BlockUtils.java (hunk 3 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/util/BlockUtils.java:249]: Yeah, as long as we don't have anything smarter to do this.
This is probably the best way to do this.

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 116 issues
* ![CRITICAL][CRITICAL] 4 critical
* ![MAJOR][MAJOR] 50 major
* ![MINOR][MINOR] 55 minor
* ![INFO][INFO] 7 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractJob.java#L328](https://github.com/Minecolonies/minecolonies/blob/8c8f64528daa34cc9a276d4e7b75e48f233e2d70/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L328): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractEntityAIStructure.java#L254](https://github.com/Minecolonies/minecolonies/blob/8c8f64528daa34cc9a276d4e7b75e48f233e2d70/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L254): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![CRITICAL][CRITICAL] [AbstractEntityAIStructure.java#L300](https://github.com/Minecolonies/minecolonies/blob/8c8f64528daa34cc9a276d4e7b75e48f233e2d70/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L300): Reduce the number of conditional operators (7) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![CRITICAL][CRITICAL] [BlockUtils.java#L291](https://github.com/Minecolonies/minecolonies/blob/8c8f64528daa34cc9a276d4e7b75e48f233e2d70/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L291): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [AbstractJob.java#L50](https://github.com/Minecolonies/minecolonies/blob/8c8f64528daa34cc9a276d4e7b75e48f233e2d70/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L50): Remove this reference to "JobPlaceholder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L51](https://github.com/Minecolonies/minecolonies/blob/8c8f64528daa34cc9a276d4e7b75e48f233e2d70/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L51): Remove this reference to "JobBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L52](https://github.com/Minecolonies/minecolonies/blob/8c8f64528daa34cc9a276d4e7b75e48f233e2d70/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L52): Remove this reference to "JobDeliveryman". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L53](https://github.com/Minecolonies/minecolonies/blob/8c8f64528daa34cc9a276d4e7b75e48f233e2d70/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L53): Remove this reference to "JobMiner". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L54](https://github.com/Minecolonies/minecolonies/blob/8c8f64528daa34cc9a276d4e7b75e48f233e2d70/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L54): Remove this reference to "JobLumberjack". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L55](https://github.com/Minecolonies/minecolonies/blob/8c8f64528daa34cc9a276d4e7b75e48f233e2d70/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L55): Remove this reference to "JobFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 7]
```diff
@@ -1027,75 +853,80 @@ public void resetCurrentStructure()
         currentStructure = null;
     }
 
+    //Unable to merge both loops since they rely on the end of the other.
+    @SuppressWarnings("squid:S3047")
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: INFO Suppressing the 'squid:S3047' warning is not allowed [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1309)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 8]
```diff
@@ -1027,75 +853,80 @@ public void resetCurrentStructure()
...
     private Boolean spawnEntity(@NotNull final Structure.StructureBlock currentBlock)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:714]: MAJOR Refactor this method to reduce its Cognitive Complexity from 32 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 113 issues
* ![CRITICAL][CRITICAL] 4 critical
* ![MAJOR][MAJOR] 49 major
* ![MINOR][MINOR] 50 minor
* ![INFO][INFO] 10 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractJob.java#L328](https://github.com/Minecolonies/minecolonies/blob/3890c59033076d6bb225ca39763b2748bce8614b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L328): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractEntityAIStructure.java#L173](https://github.com/Minecolonies/minecolonies/blob/3890c59033076d6bb225ca39763b2748bce8614b/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L173): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![CRITICAL][CRITICAL] [AbstractEntityAIStructure.java#L219](https://github.com/Minecolonies/minecolonies/blob/3890c59033076d6bb225ca39763b2748bce8614b/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L219): Reduce the number of conditional operators (7) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![CRITICAL][CRITICAL] [BlockUtils.java#L291](https://github.com/Minecolonies/minecolonies/blob/3890c59033076d6bb225ca39763b2748bce8614b/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L291): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [AbstractJob.java#L50](https://github.com/Minecolonies/minecolonies/blob/3890c59033076d6bb225ca39763b2748bce8614b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L50): Remove this reference to "JobPlaceholder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L51](https://github.com/Minecolonies/minecolonies/blob/3890c59033076d6bb225ca39763b2748bce8614b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L51): Remove this reference to "JobBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L52](https://github.com/Minecolonies/minecolonies/blob/3890c59033076d6bb225ca39763b2748bce8614b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L52): Remove this reference to "JobDeliveryman". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L53](https://github.com/Minecolonies/minecolonies/blob/3890c59033076d6bb225ca39763b2748bce8614b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L53): Remove this reference to "JobMiner". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L54](https://github.com/Minecolonies/minecolonies/blob/3890c59033076d6bb225ca39763b2748bce8614b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L54): Remove this reference to "JobLumberjack". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L55](https://github.com/Minecolonies/minecolonies/blob/3890c59033076d6bb225ca39763b2748bce8614b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L55): Remove this reference to "JobFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 9]
```diff
@@ -725,23 +503,36 @@ private AIState startBuilding()
             onStartWithoutStructure();
             return AIState.IDLE;
         }
+        final AIState nextState;
         switch (currentStructure.getStage())
         {
             case CLEAR:
```
Comment (marvin-bitterlich) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: why? this is double the lines with no extra readability

**Comment by Raycoms** [comment]
because sonar wanted it so.

2017-04-25 6:08 GMT-03:00 Marvin Hofmann <notifications@github.com>:

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 9 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: Sonar doesn't want that many returns, sonar does receive a solution it wants =D

Comment (marvin-bitterlich) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: Nope, wrong solution, I object. 

Sonar is not a sentient being. We are.

So we change this back and adapt the sonar rules to match what we want.

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 10]
```diff
@@ -156,82 +149,7 @@ private AIState completeBuild()
...
-                    minerBuilding.addLevel(currentLevel);
-                    minerBuilding.setCurrentLevel(minerBuilding.getNumberOfLevels());
-                    minerBuilding.resetStartingLevelShaft();
-                }
-                //Send out update to client
-                getOwnBuilding().markDirty();
-
-                ((JobMiner) job).setStructure(null);
-            }
+            executeSpecificCompleteActions();
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:153]: Good Work!

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 11]
```diff
@@ -308,15 +226,12 @@ private Boolean structureStep(final Structure.StructureBlock structureBlock)
                 return true;
             }
 
+
             @Nullable Block block = structureBlock.block;
             @Nullable IBlockState blockState = structureBlock.metadata;
-            if (structureBlock.block == ModBlocks.blockSolidSubstitution)
+            if (block == ModBlocks.blockSolidSubstitution
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java:223]: In the future we should a a Handler for the substitution. That way we can expand the substitution system easily. But for now i think this is okey.

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 9 above)
Comment (marchermans) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: I agree with @Kostronor that this is a weird change. However the Sonar rule for too many returns is a usefull rule. You might actually forget what we are returning in a method when said method is longer and complex. I think we should leave the rule and Judge based on the situation.

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 12]
```diff
@@ -769,6 +561,31 @@ private boolean handleMaterials(@NotNull final Block block, @NotNull final IBloc
...
+     * Get specific data of a tileEntity.
+     * Workers should implement this correctly if they require this behavior.
+     * @return list of items of the tile.
+     */
+    public List<ItemStack> getItemsFromTileEntity()
+    {
+        return Collections.emptyList();
+    }
+
+    public boolean handleSpecificMaterial(@NotNull final Block block)
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: Nice to have this as a specific method, but we should turn this into a list based approach.

Turn the if switches into their own handler, and have the handler actually do the heavy lifting.

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java [hunk 13]
```diff
@@ -863,10 +652,10 @@ private boolean placeBlock(@NotNull final BlockPos pos, final Block block, @NotN
         }
 
         //Workaround as long as we didn't rescan all of our buildings since BlockStairs now have different metadata values.
-        if (blockState.getBlock() instanceof BlockStairs
+        if (stateToPlace.getBlock() instanceof BlockStairs
```
Comment (marchermans) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: Again, these kind of if switches can easily be replaced with a System that is based on interfaces (event functional ones) that make these kind of methods better manageable then they are now.

Clearing out some of to Sonar issues in the proces.

**Review by marchermans — CHANGES_REQUESTED** [review]
Except for some changes regarding the stuff you guys do with if switches when handling the structure, which can eb refactored to make the code better readable and better to maintain. I am Okey. @Kostronor I have no idea if i should block, but i am going to. If you want you can overrule my review if you think rewriting that is not a priority right now, even though all small bits help and we have to start somewhere.

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java (hunk 9 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: Can't we delete the rules for switches?

Comment (marvin-bitterlich) [reply src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java]: The return rule has nothing to do with switches. So no.

**Review by marchermans — APPROVED** [review]
This is better.

File: src/main/java/com/minecolonies/coremod/placementhandlers/PlacementHandlers.java [hunk 14]
```diff
@@ -0,0 +1,346 @@
...
+        handlers.add(new DoorPlacementHandler());
+        handlers.add(new BedPlacementHandler());
+        handlers.add(new DoublePlantPlacementHandler());
+        handlers.add(new SpecialBlockPlacementAttemptHandler());
+        handlers.add(new FlowerPotPlacementHandler());
+        handlers.add(new BlockGrassPathPlacementHandler());
+        handlers.add(new StairBlockPlacementHandler());
+        handlers.add(new GeneralBlockPlacementHandler());
+    }
+
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/placementhandlers/PlacementHandlers.java]: MAJOR Reduce this class from 31 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)

File: src/main/java/com/minecolonies/coremod/placementhandlers/PlacementHandlers.java [hunk 15]
```diff
@@ -0,0 +1,346 @@
...
+            if (blockState instanceof BlockEndPortal
+                    || blockState instanceof BlockMobSpawner
+                    || blockState instanceof BlockDragonEgg
+                    || blockState instanceof BlockPortal)
+            {
+                return ActionProcessingResult.ACCEPT;
+            }
+            return ActionProcessingResult.IGNORE;
+        }
+    }
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/placementhandlers/PlacementHandlers.java]: MAJOR Reduce this class from 31 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)

File: src/main/java/com/minecolonies/coremod/placementhandlers/PlacementHandlers.java [hunk 16]
```diff
@@ -0,0 +1,346 @@
...
+
+import java.util.ArrayList;
+import java.util.List;
+
+/**
+ * Class containing all placement handler implementations.
+ */
+public final class PlacementHandlers
+{
+    public static final List<IPlacementHandler> handlers = new ArrayList<>();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/placementhandlers/PlacementHandlers.java:31]: MINOR Make this member "protected". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2386)

File: src/main/java/com/minecolonies/coremod/util/InventoryUtils.java [hunk 17]
```diff
@@ -187,6 +187,33 @@ public static int findFirstSlotInItemHandlerWith(@NotNull final IItemHandler ite
...
+        for (int slot = 0; slot < itemHandler.getSlots(); slot++)
+        {
+            if (notEmptyPredicate.test(itemHandler.getStackInSlot(slot)))
+            {
+                return slot;
+            }
+        }
+
+        return -1;
+        //TODO: Later harden contract to remove compare on slot := -1
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/util/InventoryUtils.java:212]: INFO Complete the task associated to this TODO comment. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/coremod/util/InventoryUtils.java [hunk 18]
```diff
@@ -187,6 +187,33 @@ public static int findFirstSlotInItemHandlerWith(@NotNull final IItemHandler ite
...
+        //throw new IllegalStateException("Item "+targetItem.getUnlocalizedName() + " not found in ItemHandler!");
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/util/InventoryUtils.java:213]: MINOR This block of commented-out lines of code should be removed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

File: src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java [hunk 19]
```diff
@@ -1135,7 +1135,7 @@ protected boolean checkOrRequestItems(@Nullable final ItemStack... items)
      * @param items         the items needed
      * @return false if they are in inventory
      */
-    protected boolean checkOrRequestItems(final boolean useItemDamage, @Nullable final ItemStack... items)
+    public boolean checkOrRequestItems(final boolean useItemDamage, @Nullable final ItemStack... items)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java:1138]: MAJOR Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 112 issues
* ![CRITICAL][CRITICAL] 2 critical
* ![MAJOR][MAJOR] 47 major
* ![MINOR][MINOR] 53 minor
* ![INFO][INFO] 10 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractJob.java#L328](https://github.com/Minecolonies/minecolonies/blob/66bb2f5aaab2f058272c90b0ff1caae65f45d57b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L328): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [BlockUtils.java#L291](https://github.com/Minecolonies/minecolonies/blob/66bb2f5aaab2f058272c90b0ff1caae65f45d57b/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L291): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [AbstractJob.java#L50](https://github.com/Minecolonies/minecolonies/blob/66bb2f5aaab2f058272c90b0ff1caae65f45d57b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L50): Remove this reference to "JobPlaceholder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L51](https://github.com/Minecolonies/minecolonies/blob/66bb2f5aaab2f058272c90b0ff1caae65f45d57b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L51): Remove this reference to "JobBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L52](https://github.com/Minecolonies/minecolonies/blob/66bb2f5aaab2f058272c90b0ff1caae65f45d57b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L52): Remove this reference to "JobDeliveryman". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L53](https://github.com/Minecolonies/minecolonies/blob/66bb2f5aaab2f058272c90b0ff1caae65f45d57b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L53): Remove this reference to "JobMiner". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L54](https://github.com/Minecolonies/minecolonies/blob/66bb2f5aaab2f058272c90b0ff1caae65f45d57b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L54): Remove this reference to "JobLumberjack". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L55](https://github.com/Minecolonies/minecolonies/blob/66bb2f5aaab2f058272c90b0ff1caae65f45d57b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L55): Remove this reference to "JobFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L56](https://github.com/Minecolonies/minecolonies/blob/66bb2f5aaab2f058272c90b0ff1caae65f45d57b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L56): Remove this reference to "JobFisherman". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L57](https://github.com/Minecolonies/minecolonies/blob/66bb2f5aaab2f058272c90b0ff1caae65f45d57b/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L57): Remove this reference to "JobGuard". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/placementhandlers/PlacementHandlers.java [hunk 20]
```diff
@@ -0,0 +1,346 @@
...
+        handlers.add(new DoublePlantPlacementHandler());
+        handlers.add(new SpecialBlockPlacementAttemptHandler());
+        handlers.add(new FlowerPotPlacementHandler());
+        handlers.add(new BlockGrassPathPlacementHandler());
+        handlers.add(new StairBlockPlacementHandler());
+        handlers.add(new GeneralBlockPlacementHandler());
+    }
+
+    //If he woudln't count the bracket spaces we'd be under 25 easily.
+    public static class FireplacementHandler implements IPlacementHandler
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/placementhandlers/PlacementHandlers.java:56]: MAJOR Reduce this class from 31 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)

File: src/main/java/com/minecolonies/coremod/placementhandlers/PlacementHandlers.java [hunk 21]
```diff
@@ -0,0 +1,346 @@
...
+                    || blockState instanceof BlockDragonEgg
+                    || blockState instanceof BlockPortal)
+            {
+                return ActionProcessingResult.ACCEPT;
+            }
+            return ActionProcessingResult.IGNORE;
+        }
+    }
+
+    public static class FlowerPotPlacementHandler implements IPlacementHandler
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/coremod/placementhandlers/PlacementHandlers.java:219]: MAJOR Reduce this class from 31 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)

**Comment by marvin-bitterlich** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/841/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 112 issues
* ![CRITICAL][CRITICAL] 2 critical
* ![MAJOR][MAJOR] 47 major
* ![MINOR][MINOR] 53 minor
* ![INFO][INFO] 10 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractJob.java#L328](https://github.com/Minecolonies/minecolonies/blob/25bd8300a749a0ddd23490bbdc0555b251406c04/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L328): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [BlockUtils.java#L291](https://github.com/Minecolonies/minecolonies/blob/25bd8300a749a0ddd23490bbdc0555b251406c04/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L291): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [AbstractJob.java#L50](https://github.com/Minecolonies/minecolonies/blob/25bd8300a749a0ddd23490bbdc0555b251406c04/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L50): Remove this reference to "JobPlaceholder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L51](https://github.com/Minecolonies/minecolonies/blob/25bd8300a749a0ddd23490bbdc0555b251406c04/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L51): Remove this reference to "JobBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L52](https://github.com/Minecolonies/minecolonies/blob/25bd8300a749a0ddd23490bbdc0555b251406c04/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L52): Remove this reference to "JobDeliveryman". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L53](https://github.com/Minecolonies/minecolonies/blob/25bd8300a749a0ddd23490bbdc0555b251406c04/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L53): Remove this reference to "JobMiner". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L54](https://github.com/Minecolonies/minecolonies/blob/25bd8300a749a0ddd23490bbdc0555b251406c04/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L54): Remove this reference to "JobLumberjack". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L55](https://github.com/Minecolonies/minecolonies/blob/25bd8300a749a0ddd23490bbdc0555b251406c04/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L55): Remove this reference to "JobFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L56](https://github.com/Minecolonies/minecolonies/blob/25bd8300a749a0ddd23490bbdc0555b251406c04/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L56): Remove this reference to "JobFisherman". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L57](https://github.com/Minecolonies/minecolonies/blob/25bd8300a749a0ddd23490bbdc0555b251406c04/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L57): Remove this reference to "JobGuard". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 112 issues
* ![CRITICAL][CRITICAL] 2 critical
* ![MAJOR][MAJOR] 47 major
* ![MINOR][MINOR] 53 minor
* ![INFO][INFO] 10 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractJob.java#L328](https://github.com/Minecolonies/minecolonies/blob/bdaad1b8b7dbc25f4435af9b4ac81a229f444276/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L328): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [BlockUtils.java#L291](https://github.com/Minecolonies/minecolonies/blob/bdaad1b8b7dbc25f4435af9b4ac81a229f444276/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L291): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [AbstractJob.java#L50](https://github.com/Minecolonies/minecolonies/blob/bdaad1b8b7dbc25f4435af9b4ac81a229f444276/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L50): Remove this reference to "JobPlaceholder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L51](https://github.com/Minecolonies/minecolonies/blob/bdaad1b8b7dbc25f4435af9b4ac81a229f444276/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L51): Remove this reference to "JobBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L52](https://github.com/Minecolonies/minecolonies/blob/bdaad1b8b7dbc25f4435af9b4ac81a229f444276/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L52): Remove this reference to "JobDeliveryman". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L53](https://github.com/Minecolonies/minecolonies/blob/bdaad1b8b7dbc25f4435af9b4ac81a229f444276/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L53): Remove this reference to "JobMiner". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L54](https://github.com/Minecolonies/minecolonies/blob/bdaad1b8b7dbc25f4435af9b4ac81a229f444276/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L54): Remove this reference to "JobLumberjack". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L55](https://github.com/Minecolonies/minecolonies/blob/bdaad1b8b7dbc25f4435af9b4ac81a229f444276/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L55): Remove this reference to "JobFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L56](https://github.com/Minecolonies/minecolonies/blob/bdaad1b8b7dbc25f4435af9b4ac81a229f444276/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L56): Remove this reference to "JobFisherman". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L57](https://github.com/Minecolonies/minecolonies/blob/bdaad1b8b7dbc25f4435af9b4ac81a229f444276/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L57): Remove this reference to "JobGuard". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 112 issues
* ![CRITICAL][CRITICAL] 2 critical
* ![MAJOR][MAJOR] 47 major
* ![MINOR][MINOR] 53 minor
* ![INFO][INFO] 10 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractJob.java#L328](https://github.com/Minecolonies/minecolonies/blob/6426f4df62e94bdbce76e04c80955c4cdcc5e6d0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L328): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [BlockUtils.java#L291](https://github.com/Minecolonies/minecolonies/blob/6426f4df62e94bdbce76e04c80955c4cdcc5e6d0/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L291): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [AbstractJob.java#L50](https://github.com/Minecolonies/minecolonies/blob/6426f4df62e94bdbce76e04c80955c4cdcc5e6d0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L50): Remove this reference to "JobPlaceholder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L51](https://github.com/Minecolonies/minecolonies/blob/6426f4df62e94bdbce76e04c80955c4cdcc5e6d0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L51): Remove this reference to "JobBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L52](https://github.com/Minecolonies/minecolonies/blob/6426f4df62e94bdbce76e04c80955c4cdcc5e6d0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L52): Remove this reference to "JobDeliveryman". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L53](https://github.com/Minecolonies/minecolonies/blob/6426f4df62e94bdbce76e04c80955c4cdcc5e6d0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L53): Remove this reference to "JobMiner". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L54](https://github.com/Minecolonies/minecolonies/blob/6426f4df62e94bdbce76e04c80955c4cdcc5e6d0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L54): Remove this reference to "JobLumberjack". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L55](https://github.com/Minecolonies/minecolonies/blob/6426f4df62e94bdbce76e04c80955c4cdcc5e6d0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L55): Remove this reference to "JobFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L56](https://github.com/Minecolonies/minecolonies/blob/6426f4df62e94bdbce76e04c80955c4cdcc5e6d0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L56): Remove this reference to "JobFisherman". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L57](https://github.com/Minecolonies/minecolonies/blob/6426f4df62e94bdbce76e04c80955c4cdcc5e6d0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L57): Remove this reference to "JobGuard". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 112 issues
* ![CRITICAL][CRITICAL] 2 critical
* ![MAJOR][MAJOR] 47 major
* ![MINOR][MINOR] 53 minor
* ![INFO][INFO] 10 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractJob.java#L328](https://github.com/Minecolonies/minecolonies/blob/ecaf42dcba34454a0be9d659b054634ce9d8c6f0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L328): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [BlockUtils.java#L291](https://github.com/Minecolonies/minecolonies/blob/ecaf42dcba34454a0be9d659b054634ce9d8c6f0/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L291): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [AbstractJob.java#L50](https://github.com/Minecolonies/minecolonies/blob/ecaf42dcba34454a0be9d659b054634ce9d8c6f0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L50): Remove this reference to "JobPlaceholder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L51](https://github.com/Minecolonies/minecolonies/blob/ecaf42dcba34454a0be9d659b054634ce9d8c6f0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L51): Remove this reference to "JobBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L52](https://github.com/Minecolonies/minecolonies/blob/ecaf42dcba34454a0be9d659b054634ce9d8c6f0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L52): Remove this reference to "JobDeliveryman". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L53](https://github.com/Minecolonies/minecolonies/blob/ecaf42dcba34454a0be9d659b054634ce9d8c6f0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L53): Remove this reference to "JobMiner". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L54](https://github.com/Minecolonies/minecolonies/blob/ecaf42dcba34454a0be9d659b054634ce9d8c6f0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L54): Remove this reference to "JobLumberjack". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L55](https://github.com/Minecolonies/minecolonies/blob/ecaf42dcba34454a0be9d659b054634ce9d8c6f0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L55): Remove this reference to "JobFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L56](https://github.com/Minecolonies/minecolonies/blob/ecaf42dcba34454a0be9d659b054634ce9d8c6f0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L56): Remove this reference to "JobFisherman". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L57](https://github.com/Minecolonies/minecolonies/blob/ecaf42dcba34454a0be9d659b054634ce9d8c6f0/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L57): Remove this reference to "JobGuard". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'
