### PR TITLE
Fix colony map

### LINKED ISSUE #10293: Townmap will only display the last map in inventory
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.719

### Structurize Version

1.0.752

### Related Mods and their Versions

BlockUI 1.0.190

### Current Behavior

When i put a map in the townhall / townmap inventory it displays the map correct. When i put more maps in it to map the rest of the colony it no longer displays the old map despite it is still in the townhall inventory. 
So it only displays the last map and not all of them.

### Expected Behavior

It should display all maps together.

### Reproduction Steps

Put more than one map in the townhall

### Logs

https://pastebin.com/QfcXnfZS

### Anything else?

SphaxBD Texture Pack

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Nightenom**
# Changes proposed in this pull request:
- fixes nbt checking for filled maps (1.21 only)
- reworks how colony map works internally regarding mapData (background map texture) - fixes various weird issues with zooming (no more jumpy) or items outside zoomdrag component
- actual changes: allow map of any scale (not just "normal" zero), center at player on open
(will port after merging)

[x] Yes I tested this before submitting it.
[ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/api/colony/buildings/workerbuildings/ITownHallView.java [hunk 1]
```diff
@@ -28,4 +33,20 @@ public interface ITownHallView extends IBuildingView
...
+
+    /**
+     * Getter for the mapdata.
+     * @return the original list.
+     */
+    List<MapEntry> getMapDataList();
+
+    public record MapEntry(MapId mapId, MapItemSavedData mapData)
+    {
+        public static final StreamCodec<RegistryFriendlyByteBuf, MapEntry> STREAM_CODEC =
```
Comment (someaddons) [inline src/main/java/com/minecolonies/api/colony/buildings/workerbuildings/ITownHallView.java:45]: why do we need a custom codec for vanilla maps? shouldnt we be able to use the vanilla codec for them?

Comment (Nightenom) [reply src/main/java/com/minecolonies/api/colony/buildings/workerbuildings/ITownHallView.java:45]: the first is item dataComp and has both codecs, the second is level savedData which doesnt have any codec

Comment (someaddons) [reply src/main/java/com/minecolonies/api/colony/buildings/workerbuildings/ITownHallView.java:45]: then I dont see why we dont simply sent the int and nbt via buffer?

Comment (Nightenom) [reply src/main/java/com/minecolonies/api/colony/buildings/workerbuildings/ITownHallView.java:45]: because in first comment you want to me to use vanilla codec? (for mapid)

File: src/main/resources/assets/minecolonies/lang/manual_en_us.json [hunk 2]
```diff
@@ -2485,7 +2485,7 @@
   "com.minecolonies.coremod.gui.townhall.stats.items_delivered": "Delivered Items: %d",
   "com.minecolonies.coremod.gui.townhall.stats.food_served": "Served Food: %d",
   "com.minecolonies.coremod.gui.townHall.map": "Town Map",
-  "com.minecolonies.coremod.townhall.map.warning": "Drop-off a normal scale Minecraft map in the Town Hall inventory first to unlock the map.",
+  "com.minecolonies.coremod.townhall.map.warning": "Drop-off a Minecraft map(s) in the Town Hall inventory first to unlock the map.",
```
Comment (Raycoms) [inline src/main/resources/assets/minecolonies/lang/manual_en_us.json]: This is to make sure they only drop the small ones off, not the big ones

File: src/main/java/com/minecolonies/api/colony/buildings/workerbuildings/ITownHallView.java (hunk 1 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/api/colony/buildings/workerbuildings/ITownHallView.java:45]: Can't we just do:
buf.writeNbt(data.save(new CompoundTag(), buf.registryAccess()))
+ Use the mapId codec from vanilla?

I think that was what Sam meant

File: src/main/resources/assets/minecolonies/lang/manual_en_us.json (hunk 2 above)
Comment (Nightenom) [reply src/main/resources/assets/minecolonies/lang/manual_en_us.json]: Read the PR doc :D

Comment (Raycoms) [reply src/main/resources/assets/minecolonies/lang/manual_en_us.json]: Yeah, but that was gameplay intentional to have maps only of a fixed size in there =D

Comment (Raycoms) [reply src/main/resources/assets/minecolonies/lang/manual_en_us.json]: reminder

File: src/main/resources/assets/minecolonies/lang/manual_en_us.json [hunk 3]
```diff
@@ -2485,8 +2485,6 @@
   "com.minecolonies.coremod.gui.interval.lastweek": "Last Week",
   "com.minecolonies.coremod.gui.interval.100days": "Last 100 Days",
   "com.minecolonies.coremod.gui.interval.alltime": "All Time",
-  "com.minecolonies.coremod.gui.townhall.stats.items_delivered": "Delivered Items: %d",
-  "com.minecolonies.coremod.gui.townhall.stats.food_served": "Served Food: %d",
```
Comment (Raycoms) [inline src/main/resources/assets/minecolonies/lang/manual_en_us.json:2489]: why?

Comment (Nightenom) [reply src/main/resources/assets/minecolonies/lang/manual_en_us.json:2489]: Dupe keys same values, see few lines above
