### PR TITLE
Fix/several

### LINKED ISSUE #5687: Builder getting stuck placing lanterns
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.200
- Structurize Version: 0.13.56
- Related Mods and their Versions: -

## Expected behavior
When building a structure, the builder takes lanterns from his chest, walks to the structure he is building, and places these lanterns.

## Actual behavior
After picking up the lanterns from his chest, the builder walks to the structure, but turns around halfway, and starts walking back to his hut. Once he arrives, he stows away several lanterns into a rack, waits a few seconds, then retrieves these lanterns from the rack again, and walks to the structure he is building again, after which this cycle starts over again.

## Steps to reproduce the issue

1. Upgrade a guard tower or a miner in the Asian style from level 2 to level 3 (probably affects other structures as well, but these are the ones I have found this issue to apply to)
2. Give the builder the resources he needs to build the building
3. Once the builder gets to the point of placing lanterns, he will become stuck in a cycle of walking to the build, back to his own hut, and replacing his materials.

### Logs

- latest.log: https://gist.github.com/Sindarin27/6c9349e56ab362576287128403c2d9ef
- crashlog: (no crash)

### Notes
I expect this to be an issue with the builder trying to place lanterns before the lantern's "support block" is placed, triggering him to go back to his hut. This issue might thus be fixed by having the builder place lanterns in the latest stage of building, much like torches and signs.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #5697: Busy Baker Bites Boundless Bread
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.207-ALPHA-universal
- Structurize Version: structurize-0.13.56-ALPHA
- Related Mods and their Versions:

## Expected behavior

The baker should be able to produce enough food to feed himself and others when given wheat.

## Actual behavior

The baker does not produce enough bread to feed himself. It would appear that the activity of creating bread causes the baker to lose more hunger shanks than the bread he produces can refill.

## Steps to reproduce the issue

1. Create a new game.
2. Create a town hall.
3. Disable new colonists at the town hall after one colonist appears.
4. Create a bakery and house.
5. Assign the colonist to the baker role and the house.
6. Give multiple stacks of wheat to the baker.
7. The baker eventually runs out of hunger shanks and starves.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #5703: Gui's have player inventory off by 1
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.1
- MineColonies Version: 0.12.201-ALPHA
- Structurize Version: 0.13.44-ALPHA
- Related Mods and their Versions: N/A

## Expected behavior
When viewing an inventory I expect the slots to line up.

## Actual behavior
When viewing the inventory of a block in which the player inventory exists. The player inventory slots are off by one pixel in the y direction, they should not be.

image

## Steps to reproduce the issue

1. Open the game with minecolonies installed.
2. Open the inventory of a minecolonies block.
3. Look at the inventory page, so that you have the players inventory on screen and hover over a player inventory slot.

### Logs

N/A no crash

### Notes
I'm playing the Valhesia 3 modpack with minecolonies updated before i launch.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #5703
Closes #5697
Closes #5687

# Changes proposed in this pull request:
- Fix builder stuck
- Fix inv offset
- Improve baker consumption

Review please

### CODE REVIEW

**Review by someaddons — APPROVED** [review]

File: src/main/java/com/minecolonies/coremod/client/gui/containers/WindowCitizenInventory.java [hunk 1]
```diff
@@ -13,6 +13,11 @@
  */
 public class WindowCitizenInventory extends ContainerScreen<ContainerCitizenInventory>
 {
+    /**
+     * Texture res loc.
+     */
+    private static final ResourceLocation TEXT = new ResourceLocation(Constants.MOD_ID, "textures/gui/generic_108.png");
```
Comment (Mekle001) [inline src/main/java/com/minecolonies/coremod/client/gui/containers/WindowCitizenInventory.java:19]: Can we pick another name? this name makes me think the texture is an image of "lore ipsum sit amet" in some fancy font.
