### PR TITLE
Fix several issues relate to building with the new RS

### LINKED ISSUE #1866: Inaccessable Inventories
Hey guys, updated to minecolonies-universal-1.12.2-0.8.6037 and none of the MC added inventories are accessible.  Have tried the building blocks and the racks.

### LINKED ISSUE #1870: Problems of the builder and the courier
Hello!

I use version 1.12.2-0.8.6037

The builder and can not build a bakery and also requires bread:
http://pixs.ru/showimage/2017121811_3548196_28703983.png

It can be seen that the white inscription on a white background and almost unreadable and also requires bread:
http://pixs.ru/showimage/2017121811_9887143_28703997.png

Here you can see that the builder in the inventory of bread in abundance:
http://pixs.ru/showimage/2017121811_5212349_28704008.png

 In the menu of necessary items, you can see that the bread is enough (the framework was also in the builder's building.) I myself tried to finish the bakery and set the frames where they were supposed to be):
http://pixs.ru/showimage/2017121811_8729947_28704024.png

 

When new people appear, all skills are always equal to 1. Is this how it should be?

 

When delivering items courier to the builder Minecraft freezes. You can move around the map, but do not interact with anything. There is no report on the crash.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #1870
Closes #1866

# Changes proposed in this pull request:
-
-
-

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/ProviderHandler.java [hunk 1]
```diff
@@ -101,14 +98,8 @@ public static void removeProviderInternal(final IStandardRequestManager manager,
...
         {
-            //If no requests are assigned to this resolver skip.
-            if (!manager.getResolverRequestMap().containsKey(resolverToken))
-            {
-                continue;
-            }
-
             //Skip if the resolver has no requests assigned.
-            if (manager.getResolverRequestMap().get(resolverToken).size() == 0)
+            if (!manager.getResolverRequestMap().containsKey(resolverToken) || manager.getResolverRequestMap().get(resolverToken).size() == 0)
```
Comment (OrionDevelopment) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/ProviderHandler.java]: This needs to be && instead of ||. Logic has changed else.

**Review by marchermans — DISMISSED** [review]

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java [hunk 2]
```diff
@@ -3,6 +3,7 @@
 import com.google.common.collect.ImmutableCollection;
 import com.google.common.reflect.TypeToken;
 import com.minecolonies.api.colony.requestsystem.manager.AssigningStrategy;
+import com.minecolonies.api.colony.requestsystem.manager.IRequestManager;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java:6]: MINOR Remove this unused import 'com.minecolonies.api.colony.requestsystem.manager.IRequestManager'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java [hunk 3]
```diff
@@ -220,9 +221,33 @@ public static IToken assignRequestDefault(final IStandardRequestManager manager,
     public static IToken reassignRequest(final IStandardRequestManager manager, final IRequest request, final Collection<IToken> resolverTokenBlackList)
       throws IllegalArgumentException
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java:222]: MINOR Remove the declaration of thrown exception 'java.lang.IllegalArgumentException' which is a runtime exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 103 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 15 major
* ![MINOR][MINOR] 81 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1438](https://github.com/Minecolonies/minecolonies/blob/d30073aceb0cc9d5cde8fe1ed76be02920930169/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1438): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1467](https://github.com/Minecolonies/minecolonies/blob/d30073aceb0cc9d5cde8fe1ed76be02920930169/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1467): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1478](https://github.com/Minecolonies/minecolonies/blob/d30073aceb0cc9d5cde8fe1ed76be02920930169/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1478): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1584](https://github.com/Minecolonies/minecolonies/blob/d30073aceb0cc9d5cde8fe1ed76be02920930169/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1584): Remove usage of generic wildcard type. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1698](https://github.com/Minecolonies/minecolonies/blob/d30073aceb0cc9d5cde8fe1ed76be02920930169/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1698): Missing curly brace. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00121)
1. ![CRITICAL][CRITICAL] [RequestHandler.java#L89](https://github.com/Minecolonies/minecolonies/blob/d30073aceb0cc9d5cde8fe1ed76be02920930169/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers/RequestHandler.java#L89): Add a default case to this switch. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ASwitchLastCaseIsDefaultCheck)
1. ![MAJOR][MAJOR] [WindowCitizen.java#L349](https://github.com/Minecolonies/minecolonies/blob/d30073aceb0cc9d5cde8fe1ed76be02920930169/src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java#L349): Remove this unused private "getNicePositionString" method. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#](https://github.com/Minecolonies/minecolonies/blob/d30073aceb0cc9d5cde8fe1ed76be02920930169/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#): This file has 1.125 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L81](https://github.com/Minecolonies/minecolonies/blob/d30073aceb0cc9d5cde8fe1ed76be02920930169/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L81): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 61 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L81](https://github.com/Minecolonies/minecolonies/blob/d30073aceb0cc9d5cde8fe1ed76be02920930169/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L81): class "AbstractBuilding" has 92 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
