### PR TITLE
Stuck handling fixes

### LINKED ISSUE #7341: Builder doesn't tp to their house at night when stuck on a roof during an upgrade.
- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.230-ALPHA-universal.jar

### Logs

I don't have a log, because it didn't throw anything in the console, but I have the colony export with the builder being stuck on the roof. 

[colony75Export.zip](https://github.com/ldtteam/minecolonies/files/6746375/colony75Export.zip)

## Steps to reproduce the issue / details

I talked to SomeAddons on Discord yesterday and from what I've learned, NPCs should tp to their houses at night. This builder doesn't do that. It may be related in some way to the fact that she was hungry and didn't have any food in her inventory. After I recalled her, she ate and teleported away to her bed.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #7341
Closes #
Closes #

# Changes proposed in this pull request:
- Fixes issues of citizens teleporting over short distances very quickly.
- Fixes issue of large distances leading to "almost infinite stucks".
-

Review please

### CODE REVIEW

File: src/api/java/com/minecolonies/api/entity/pathfinding/PathingStuckHandler.java [hunk 1]
```diff
@@ -290,19 +298,12 @@ private void tryUnstuck(final AbstractAdvancedPathNavigate navigator)
...
-                delayToNextUnstuckAction = 100;
-                int index = navigator.getPath().getNextNodeIndex() + teleportRange;
-                if (index < navigator.getPath().getNodeCount())
-                {
-                    final PathPoint togo = navigator.getPath().getNode(index);
-                    navigator.getOurEntity().teleportTo(togo.x + 0.5d, togo.y, togo.z + 0.5d);
-                    delayToNextUnstuckAction = 300;
-                }
-            }
+            int index = Math.min(navigator.getPath().getNextNodeIndex() + teleportRange, navigator.getPath().getNodeCount() - 1);
```
Comment (Raycoms) [inline src/api/java/com/minecolonies/api/entity/pathfinding/PathingStuckHandler.java:303]: This is a minor cleanup, I think this is better now.

**Review by someaddons — APPROVED** [review]
