### PR TITLE
Fix crash when selecting warehouse in another colony using resource scroll

### LINKED ISSUE #9496: [BUG] Linking resource scroll crashes game when player is in different colony
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.151 BETA

### Structurize Version

1.0.630

### Related Mods and their Versions

_No response_

### Current Behavior

Game crashes completely 100% of the time when attempting to check other colonies resources.

### Expected Behavior

Atleast an error message or exception being handled.
would be cool if it would be possible to link with either friendly or Officers roles

### Reproduction Steps

Colony owner of colony B tries to link his builder's resource scroll to Colony A's warehouse. 

### Logs

https://github.com/ldtteam/minecolonies/files/13047806/crash-2023-10-19_21.50.54-client.txt

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Thodor12**
Closes #9496 

# Changes proposed in this pull request:
- Fix crash when selecting a warehouse in another colony for a snapshot
- Extract logic for calculating snapshot to the item, not the window

[X] Yes I tested this before submitting it.
[ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/items/ItemResourceScroll.java [hunk 1]
```diff
@@ -56,6 +59,108 @@ public ItemResourceScroll(final Item.Properties properties)
         super("resourcescroll", properties.stacksTo(STACKSIZE).tab(ModCreativeTabs.MINECOLONIES));
     }
 
+    /**
+     * Check for the compound and return it. If not available create and return it.
+     *
+     * @param item the item to check in for.
+     * @return the compound of the item.
+     */
+    private static CompoundTag checkForCompound(final ItemStack item)
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/items/ItemResourceScroll.java]: item.getOrCreateTag() exists

**Comment by Raycoms** [comment]
Was this now tested in smp btw? And is the calc now fully client side again?

**Review by Raycoms — DISMISSED** [review]

**Review by someaddons — DISMISSED** [review]
