### PR TITLE
More Scan Tool

### LINKED ISSUE #1078: Miner doesn't ask for cobblestone/stops mining out of nothing
### Minecolonies version

version 0.8.1540 (but seems to have been there for the last few weeks over versions)

### Expected behavior

Miner asks for cobblestone like all other resources

### Actual behaviour

Mine stands around waiting for something but never asks for cobblestone

### Steps to reproduce the problem

1. Leave miner to do his thang
2. Notice he's not doing a lot of, you know, mining...
3. Give him everything you can think of until he gets cobblestone and then runs off happy
4. Profit

The Deliveryman seems just as confused as I am as to what the Miner is waiting around for, happily bringing him everything else he asks for (ladders, torches, etc) but no one seems to know he needs cobblestone, and he seems strangely shy about it. ;-)

### LINKED ISSUE #1096: Miner requests 1 item at a time
It takes a long time to build a level if you request every slab 1  at a time, and have to wait for the deliveryman.

This also hurts the verbal request, because he is repeating the same things often, so it gets filtered by the chat spam filter.

### LINKED ISSUE #1469: More build/scan tool
It would be nice if the scan tool would have several options:

Set/replace block, set biome, undo, redo

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #1469
Closes #1078 
Closes #1096 

# Changes proposed in this pull request:
- Adds replace/remove/set block possibility to scan Tool

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/network/messages/ReplaceBlockMessage.java [hunk 1]
```diff
@@ -0,0 +1,202 @@
...
+    public void toBytes(@NotNull final ByteBuf buf)
+    {
+        BlockPosUtil.writeToByteBuf(buf, from);
+        BlockPosUtil.writeToByteBuf(buf, to);
+        ByteBufUtils.writeItemStack(buf, blockTo);
+        ByteBufUtils.writeItemStack(buf, blockFrom);
+    }
+
+    @Override
+    public void messageOnServerThread(final ReplaceBlockMessage message, final EntityPlayerMP player)
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/network/messages/ReplaceBlockMessage.java:95]: MAJOR The Cyclomatic Complexity of this method "messageOnServerThread" is 34 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
MAJOR Refactor this method to reduce its Cognitive Complexity from 59 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

File: src/main/java/com/minecolonies/coremod/network/messages/ReplaceBlockMessage.java [hunk 2]
```diff
@@ -0,0 +1,202 @@
+package com.minecolonies.coremod.network.messages;
+
+import com.minecolonies.api.util.BlockPosUtil;
+import com.minecolonies.api.util.BlockUtils;
+import com.minecolonies.coremod.client.gui.WindowScan;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/network/messages/ReplaceBlockMessage.java]: MINOR Remove this unused import 'com.minecolonies.coremod.client.gui.WindowScan'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/network/messages/ReplaceBlockMessage.java [hunk 3]
```diff
@@ -0,0 +1,202 @@
...
+    /**
+     * Is this the correct block to remove it or replace it.
+     * @param worldStack the world stack to check.
+     * @param worldState the world state to check.
+     * @param compareStack the comparison stack.
+     * @return true if so.
+     */
+    public static boolean correctBlockToRemoveOrReplace(final ItemStack worldStack, final IBlockState worldState, final ItemStack compareStack)
+    {
+        return worldStack != null && (worldStack.isItemEqual(compareStack)
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/network/messages/ReplaceBlockMessage.java:207]: CRITICAL Reduce the number of conditional operators (7) used in the expression (maximum allowed 6). [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)

File: src/main/java/com/minecolonies/coremod/network/messages/ReplaceBlockMessage.java [hunk 4]
```diff
@@ -0,0 +1,202 @@
...
+                        }
+
+                        world.setBlockToAir(here);
+                        final ItemStack stackToPlace = message.blockTo.copy();
+                        stackToPlace.setCount(stackToPlace.getMaxStackSize());
+                        fakePlayer.setHeldItem(EnumHand.MAIN_HAND, stackToPlace);
+
+                        if (message.blockTo.getItem() instanceof ItemBed)
+                        {
+                            fakePlayer.rotationYaw = blockState.getValue(BlockBed.FACING).getHorizontalIndex() * 90;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/network/messages/ReplaceBlockMessage.java:123]: MAJOR Assign this magic number 90 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/coremod/network/messages/RemoveBlockMessage.java [hunk 5]
```diff
@@ -0,0 +1,97 @@
+package com.minecolonies.coremod.network.messages;
+
+import com.minecolonies.api.util.BlockPosUtil;
+import com.minecolonies.api.util.BlockUtils;
+import com.minecolonies.coremod.client.gui.WindowScan;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/network/messages/RemoveBlockMessage.java]: MINOR Remove this unused import 'com.minecolonies.coremod.client.gui.WindowScan'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowScan.java [hunk 6]
```diff
@@ -6,18 +6,22 @@
...
 import com.minecolonies.blockout.controls.Label;
 import com.minecolonies.blockout.controls.TextField;
 import com.minecolonies.blockout.views.ScrollingList;
 import com.minecolonies.coremod.MineColonies;
-import com.minecolonies.coremod.entity.EntityCitizen;
+import com.minecolonies.coremod.network.messages.RemoveBlockMessage;
+import com.minecolonies.coremod.network.messages.RemoveEntityMessage;
 import com.minecolonies.coremod.network.messages.ScanOnServerMessage;
 import net.minecraft.block.Block;
+import net.minecraft.block.BlockLiquid;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowScan.java]: MINOR Remove this unused import 'net.minecraft.block.BlockLiquid'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 63 issues
* ![CRITICAL][CRITICAL] 2 critical
* ![MAJOR][MAJOR] 56 major
* ![MINOR][MINOR] 5 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [WindowScan.java#L299](https://github.com/Minecolonies/minecolonies/blob/bab4e60efbcbe17426944ac2836b085277421ed1/src/main/java/com/minecolonies/coremod/client/gui/WindowScan.java#L299): Refactor this code to not nest more than 5 if/for/while/switch/try statements. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS134)
1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/bab4e60efbcbe17426944ac2836b085277421ed1/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/bab4e60efbcbe17426944ac2836b085277421ed1/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [WindowScan.java#L244](https://github.com/Minecolonies/minecolonies/blob/bab4e60efbcbe17426944ac2836b085277421ed1/src/main/java/com/minecolonies/coremod/client/gui/WindowScan.java#L244): Refactor this method to reduce its Cognitive Complexity from 44 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/bab4e60efbcbe17426944ac2836b085277421ed1/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/bab4e60efbcbe17426944ac2836b085277421ed1/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [permissions#](https://github.com/Minecolonies/minecolonies/blob/bab4e60efbcbe17426944ac2836b085277421ed1/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [requestable#](https://github.com/Minecolonies/minecolonies/blob/bab4e60efbcbe17426944ac2836b085277421ed1/src/main/java/com/minecolonies/coremod/colony/requestable#): Add a 'package-info.java' file to document the 'requestable' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [data#](https://github.com/Minecolonies/minecolonies/blob/bab4e60efbcbe17426944ac2836b085277421ed1/src/main/java/com/minecolonies/coremod/colony/requestsystem/data#): Add a 'package-info.java' file to document the 'data' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [init#](https://github.com/Minecolonies/minecolonies/blob/bab4e60efbcbe17426944ac2836b085277421ed1/src/main/java/com/minecolonies/coremod/colony/requestsystem/init#): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 62 issues
* ![CRITICAL][CRITICAL] 2 critical
* ![MAJOR][MAJOR] 56 major
* ![MINOR][MINOR] 4 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [WindowScan.java#L298](https://github.com/Minecolonies/minecolonies/blob/ba86fb4dfe275894fb5b1fe83afc256c1bcfb690/src/main/java/com/minecolonies/coremod/client/gui/WindowScan.java#L298): Refactor this code to not nest more than 5 if/for/while/switch/try statements. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS134)
1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/ba86fb4dfe275894fb5b1fe83afc256c1bcfb690/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/ba86fb4dfe275894fb5b1fe83afc256c1bcfb690/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [WindowScan.java#L243](https://github.com/Minecolonies/minecolonies/blob/ba86fb4dfe275894fb5b1fe83afc256c1bcfb690/src/main/java/com/minecolonies/coremod/client/gui/WindowScan.java#L243): Refactor this method to reduce its Cognitive Complexity from 44 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/ba86fb4dfe275894fb5b1fe83afc256c1bcfb690/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/ba86fb4dfe275894fb5b1fe83afc256c1bcfb690/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [permissions#](https://github.com/Minecolonies/minecolonies/blob/ba86fb4dfe275894fb5b1fe83afc256c1bcfb690/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [requestable#](https://github.com/Minecolonies/minecolonies/blob/ba86fb4dfe275894fb5b1fe83afc256c1bcfb690/src/main/java/com/minecolonies/coremod/colony/requestable#): Add a 'package-info.java' file to document the 'requestable' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [data#](https://github.com/Minecolonies/minecolonies/blob/ba86fb4dfe275894fb5b1fe83afc256c1bcfb690/src/main/java/com/minecolonies/coremod/colony/requestsystem/data#): Add a 'package-info.java' file to document the 'data' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [init#](https://github.com/Minecolonies/minecolonies/blob/ba86fb4dfe275894fb5b1fe83afc256c1bcfb690/src/main/java/com/minecolonies/coremod/colony/requestsystem/init#): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 62 issues
* ![CRITICAL][CRITICAL] 2 critical
* ![MAJOR][MAJOR] 56 major
* ![MINOR][MINOR] 4 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [WindowScan.java#L298](https://github.com/Minecolonies/minecolonies/blob/9c64d820a9ca8e0b6d126ebe2dff97b755cbce7d/src/main/java/com/minecolonies/coremod/client/gui/WindowScan.java#L298): Refactor this code to not nest more than 5 if/for/while/switch/try statements. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS134)
1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/9c64d820a9ca8e0b6d126ebe2dff97b755cbce7d/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/9c64d820a9ca8e0b6d126ebe2dff97b755cbce7d/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [WindowScan.java#L243](https://github.com/Minecolonies/minecolonies/blob/9c64d820a9ca8e0b6d126ebe2dff97b755cbce7d/src/main/java/com/minecolonies/coremod/client/gui/WindowScan.java#L243): Refactor this method to reduce its Cognitive Complexity from 44 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/9c64d820a9ca8e0b6d126ebe2dff97b755cbce7d/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/9c64d820a9ca8e0b6d126ebe2dff97b755cbce7d/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [permissions#](https://github.com/Minecolonies/minecolonies/blob/9c64d820a9ca8e0b6d126ebe2dff97b755cbce7d/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [requestable#](https://github.com/Minecolonies/minecolonies/blob/9c64d820a9ca8e0b6d126ebe2dff97b755cbce7d/src/main/java/com/minecolonies/coremod/colony/requestable#): Add a 'package-info.java' file to document the 'requestable' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [data#](https://github.com/Minecolonies/minecolonies/blob/9c64d820a9ca8e0b6d126ebe2dff97b755cbce7d/src/main/java/com/minecolonies/coremod/colony/requestsystem/data#): Add a 'package-info.java' file to document the 'data' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [init#](https://github.com/Minecolonies/minecolonies/blob/9c64d820a9ca8e0b6d126ebe2dff97b755cbce7d/src/main/java/com/minecolonies/coremod/colony/requestsystem/init#): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/network/messages/ReplaceBlockMessage.java [hunk 7]
```diff
@@ -0,0 +1,211 @@
...
+                        }
+                        else if(newBlockState.getBlock() instanceof BlockDirectional && blockState.getBlock() instanceof BlockDirectional)
+                        {
+                            final IBlockState transformation = newBlockState.withProperty(BlockDirectional.FACING, blockState.getValue(BlockDirectional.FACING));
+                            world.setBlockState(here, transformation);
+                        }
+                        else if(newBlockState.getBlock() instanceof BlockSlab && blockState.getBlock() instanceof BlockSlab)
+                        {
+                            final IBlockState transformation;
+                            if (blockState.getBlock() instanceof BlockDoubleStoneSlab || blockState.getBlock() instanceof BlockDoubleStoneSlabNew)
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/network/messages/ReplaceBlockMessage.java:152]: CRITICAL Refactor this code to not nest more than 5 if/for/while/switch/try statements. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS134)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 63 issues
* ![CRITICAL][CRITICAL] 3 critical
* ![MAJOR][MAJOR] 56 major
* ![MINOR][MINOR] 4 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [WindowScan.java#L298](https://github.com/Minecolonies/minecolonies/blob/8eaf5d9a5a5433302f73d261727c511601575c27/src/main/java/com/minecolonies/coremod/client/gui/WindowScan.java#L298): Refactor this code to not nest more than 5 if/for/while/switch/try statements. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS134)
1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/8eaf5d9a5a5433302f73d261727c511601575c27/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/8eaf5d9a5a5433302f73d261727c511601575c27/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [WindowScan.java#L243](https://github.com/Minecolonies/minecolonies/blob/8eaf5d9a5a5433302f73d261727c511601575c27/src/main/java/com/minecolonies/coremod/client/gui/WindowScan.java#L243): Refactor this method to reduce its Cognitive Complexity from 44 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/8eaf5d9a5a5433302f73d261727c511601575c27/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/8eaf5d9a5a5433302f73d261727c511601575c27/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [permissions#](https://github.com/Minecolonies/minecolonies/blob/8eaf5d9a5a5433302f73d261727c511601575c27/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [requestable#](https://github.com/Minecolonies/minecolonies/blob/8eaf5d9a5a5433302f73d261727c511601575c27/src/main/java/com/minecolonies/coremod/colony/requestable#): Add a 'package-info.java' file to document the 'requestable' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [data#](https://github.com/Minecolonies/minecolonies/blob/8eaf5d9a5a5433302f73d261727c511601575c27/src/main/java/com/minecolonies/coremod/colony/requestsystem/data#): Add a 'package-info.java' file to document the 'data' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [init#](https://github.com/Minecolonies/minecolonies/blob/8eaf5d9a5a5433302f73d261727c511601575c27/src/main/java/com/minecolonies/coremod/colony/requestsystem/init#): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/client/gui/WindowReplaceBlock.java [hunk 8]
```diff
@@ -0,0 +1,202 @@
...
+import com.minecolonies.api.util.constant.Constants;
+import com.minecolonies.blockout.Color;
+import com.minecolonies.blockout.Log;
+import com.minecolonies.blockout.Pane;
+import com.minecolonies.blockout.controls.*;
+import com.minecolonies.blockout.views.ScrollingList;
+import com.minecolonies.blockout.views.Window;
+import com.minecolonies.coremod.MineColonies;
+import com.minecolonies.coremod.network.messages.ReplaceBlockMessage;
+import net.minecraft.client.Minecraft;
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowReplaceBlock.java:14]: MINOR Remove this unused import 'net.minecraft.client.Minecraft'. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 64 issues
* ![CRITICAL][CRITICAL] 3 critical
* ![MAJOR][MAJOR] 56 major
* ![MINOR][MINOR] 5 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [WindowScan.java#L298](https://github.com/Minecolonies/minecolonies/blob/c12cb4d6a78511979e34b4d1d86c6328f1218337/src/main/java/com/minecolonies/coremod/client/gui/WindowScan.java#L298): Refactor this code to not nest more than 5 if/for/while/switch/try statements. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS134)
1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/c12cb4d6a78511979e34b4d1d86c6328f1218337/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/c12cb4d6a78511979e34b4d1d86c6328f1218337/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [WindowScan.java#L243](https://github.com/Minecolonies/minecolonies/blob/c12cb4d6a78511979e34b4d1d86c6328f1218337/src/main/java/com/minecolonies/coremod/client/gui/WindowScan.java#L243): Refactor this method to reduce its Cognitive Complexity from 44 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/c12cb4d6a78511979e34b4d1d86c6328f1218337/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/c12cb4d6a78511979e34b4d1d86c6328f1218337/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [permissions#](https://github.com/Minecolonies/minecolonies/blob/c12cb4d6a78511979e34b4d1d86c6328f1218337/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [requestable#](https://github.com/Minecolonies/minecolonies/blob/c12cb4d6a78511979e34b4d1d86c6328f1218337/src/main/java/com/minecolonies/coremod/colony/requestable#): Add a 'package-info.java' file to document the 'requestable' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [data#](https://github.com/Minecolonies/minecolonies/blob/c12cb4d6a78511979e34b4d1d86c6328f1218337/src/main/java/com/minecolonies/coremod/colony/requestsystem/data#): Add a 'package-info.java' file to document the 'data' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [init#](https://github.com/Minecolonies/minecolonies/blob/c12cb4d6a78511979e34b4d1d86c6328f1218337/src/main/java/com/minecolonies/coremod/colony/requestsystem/init#): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
