### PR TITLE
Building Modules

### LINKED ISSUE #6531: Visitor Requesting a Pickup
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: .610 ALPHA
- Structurize Version: .113 ALPHA
- Related Mods and their Versions: --

## Expected behavior

Visitors don't request pickups.

## Actual behavior

Visitor requests an item pickup. She had an empty inventory when I went to check.

She despawned a moment after I took these images so I couldn't show her inventory but here we go.
[Town Hall Showing she isn't a colonist](https://i.imgur.com/nrNRDcX.png)
[Clipboard showing pickup request at the bottom.](https://i.imgur.com/cTGQd1e.png)

## Steps to reproduce the issue

I honestly have no idea how to reproduce this. Have a tavern, don't have a courier, and wait, I guess?

### Logs

- latest.log: T[his doesn't have anything relevant I can see but here it is anyway](https://gist.github.com/Narcisism/ba02e33942adc3a0cd7f152652603303#file-mcolvisitorrequestbuglatest-log)
- crashlog: 

### Notes

This may be just a visual bug, as I don't have a warehouse yet and Caledonia's level 1 builder doesn't have racks, so the inventory there is a bit cluttered at the moment. However, the request did disappear when the visitor despawned.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #6542: Citizens getting stuck on rails
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.610-ALPHA
- Structurize Version: 0.13.113-ALPHA
- Related Mods and their Versions: Valhelsia 3 v3.1.8a modpack
- Minecolonies Style: Fortress

## Expected behavior

Citizens moving around town as normal, using Rails when available in their pathfinding.

## Actual behavior

Citizens are constantly getting stuck on Rails, trying to get on and off minecarts or just stuck where a rail ends to grass or grass path. Sometimes they get stuck being on their minecart in the grass off the tracks, but mostly they are stuck getting on and off the minecart at the end, but still "on" the rails. This tends to appear mostly when there is a "doorway" or a 1-block wide area they can stand on in the inner parapets, like the warehouse back door entrance, or a citizenAlternate building on an edge where the doorway entrance to the "Shed" is near the exit.

image
image
I could not get a good program to record a video. If need be, I can record on my phone and send separately in a DM/Email request.

## Steps to reproduce the issue

1.  Build a Fortress Style colony, level 3-5 buildings.
2.  Research Rails at the University
3.  Watch citizens "exiting" inner parapet walls. Most of the time they work.

### Logs

- latest.log: 
- crashlog: 
- * Do not have crashes related to this issue. If necessary, can send separately.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #6543: Guards/Couriers stopping for waypoints.
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 610
- Structurize Version: 113
- Related Mods and their Versions:

## Expected behavior

Expecting colonists to pass through waypoints

## Actual behavior

Guards and couriers (that I have seen so far) stop for roughly 4 seconds at EVERY way point between them and their destination. this is especially unhelpful when you have activated your rally banner and you watch 16 guards stop at every waypoint between them and you.

## Steps to reproduce the issue

1. build a nice colony
2. build lots of roads that have waypoints
3. trigger your rally banner and wait

### Logs

- latest.log: https://gist.github.com/Moobien/4b36882f7b5ae807e1dcdc55dcc4845d
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #6543
Closes #6531
Closes #6542 

# Changes proposed in this pull request:
- Fix wrong citizen id detection at UI
- Fix entities stopping at waypoints

Move module registry to building registry. With add module producer we can get access to modules from the building entry and can construct them without the building.

Review please

### CODE REVIEW

**Review by marchermans — DISMISSED** [review]

**Review by Mekle001 — DISMISSED** [review]

File: src/main/java/com/minecolonies/coremod/colony/buildings/registry/BuildingDataManager.java [hunk 1]
```diff
@@ -59,7 +62,12 @@ public IBuilding createFrom(final IColony colony, final BlockPos position, final
             return null;
         }
 
-        return entry.getBuildingProducer().apply(colony, position);
+        final IBuilding building = entry.getBuildingProducer().apply(colony, position);
```
Comment (someaddons) [inline src/main/java/com/minecolonies/coremod/colony/buildings/registry/BuildingDataManager.java]: could probably make this easier with an entry.apply() function and do the necessary logic within right?

**Review by someaddons — DISMISSED** [review]

**Review by someaddons — APPROVED** [review]
