### PR TITLE
Fix large bottle disappearing when milking with full inventory

### LINKED ISSUE #10939: Large Milk Bottles Destroyed With Full Inventory
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [x] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.1.924

### Structurize Version

1.0.773

### Related Mods and their Versions

I downloaded a fresh instance of Minecolonies plus dependencies plus JEI and Journeymap. I am unaware of any problems with these mods in reproducing this issue.

### Current Behavior

When milking the cow in my colony on a multiplayer server I play on, my inventory spots were full and the large milk bottles were disappearing/destroyed. When I made a test world with the mods described above, I loaded into a single player world to test. If your inventory is full but you're not wearing armor, the milk bottles will go into an armor slot. if you're wearing armor, the milk bottles will go into your off hand. If you're carrying something off hand, the milk bottles will be destroyed.

Image

Image

Image

I took a "screencast" (video of my gameplay) of the action of milking the cows, showing that all slots full results in the loss of the bottles, and that they do not auto-magically reappear when that slot is empty. It failed to upload. If you need that screencast to see what I mean, please advise on another way to get it to you.

### Expected Behavior

I expect that when my normal inventory slots are full, the large milk bottles will drop on the ground, like vanilla milk buckets do. I expect them to drop on the ground without appearing in an armor slot and without appearing in my off hand as well.

### Reproduction Steps

1. Fill your normal inventory with anything. Each slot must have an item in it.
2. Make sure large bottles are in your main hand.
3. Fill each armor slot.
4. Put something in your offhand (something non-placeable is easiest for testing).
5. Attempt to milk any cow. I tested cows in my colony and tested cows in the wild. I got the same results.

### Logs

https://gist.github.com/AliahMC/ffdda7a6cb55a4c648f24bd657143366

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by rivon0507**
Closes #10939 

# Changes proposed in this pull request
This PR addresses two issues with the Large Bottle:

 * When used on a cow or water source, the resulting **Large Milk Bottle** or **Large Water Bottle** could be lost if the player's inventory was full.
 * If armor slots were empty, the bottle could incorrectly end up in those slots.

 The new logic ensures that if the inventory is full, the resulting item is dropped into the world instead of being lost or misrouted.

## Testing
- [x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/core/items/ItemLargeBottle.java [hunk 1]
```diff
@@ -43,7 +41,9 @@ public InteractionResult interactLivingEntity(@NotNull final ItemStack stack, @N
         if (entity instanceof Cow && !entity.isBaby())
         {
             player.playSound(SoundEvents.COW_MILK, 1.0F, 1.0F);
-            InventoryUtils.addItemStackToItemHandler(new InvWrapper(player.getInventory()), ModItems.large_milk_bottle.getDefaultInstance());
+            if(!player.getInventory().add(ModItems.large_milk_bottle.getDefaultInstance())) {
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/core/items/ItemLargeBottle.java]: just formatting:

{

}

Comment (rivon0507) [reply src/main/java/com/minecolonies/core/items/ItemLargeBottle.java]: Right away

**Review by Raycoms — COMMENTED** [review]
Some merging went wrong =D

**Comment by uecasm** [comment]
Rather than replacing these calls, wouldn't it be better to fix `InventoryUtils.addItemStackToItemHandler`?  (Specifically, making it aware of armor slots, and making this check for failure.)

**Comment by Raycoms** [comment]
> Rather than replacing these calls, wouldn't it be better to fix `InventoryUtils.addItemStackToItemHandler`? (Specifically, making it aware of armor slots, and making this check for failure.)

Can we do this nicely for itemhandlers? Maybe we actually have to just wrap the player core inventory in the wrapper not the whole player inv?

**Review by someaddons — DISMISSED** [review]

**Comment by rivon0507** [comment]
Reverted to using `InventoryUtils.addItemStackToItemHandler` for adding large milk and water bottles, now with `PlayerMainInvWrapper` instead of `InvWrapper`.

**Review by Raycoms — APPROVED** [review]

**Comment by Raycoms** [comment]
Comment before I merge it. Can you replace the other usages of the playerinvwrapper, where it applies, to this?

**Comment by rivon0507** [comment]
I'll look for the occurrences and submit a PR later.
