### PR TITLE
Colony creation gui

### LINKED ISSUE #4607: Other players can't access GUI in multiplayer
### Minecolonies version

Version: minecolonies-0.11.817-ALPHA

### Expected behavior

- 
When right clicking the town hall or other block the GUI needs to open.
### Actual behaviour

- 
The GUI only opens for the player that placed the block.
If the town hall is destroyed and another player places it, that player is the only one that can open the GUI.
All players where made officers and the officer permissions where all enabled. 

### Steps to reproduce the problem

1.  Player 1 places the town hall
2.  Player 2 tries to open the town hall GUI
3.  Player 2 won't get the GUI
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/DriesVE/4297199ea3860c8cd07498fcf5c70bca
- crashlog:

### PR DESCRIPTION
**Pull request by someaddons**
Closes #4607
Closes #
Closes #

# Changes proposed in this pull request:
This PR changes how colony creation works, the colony is now created via a GUI you open by accessing a townhall, instead of upon townhall placement. The gui is looking like this:
image
image

and shows information about nearby colonies, the colony you own and why you can't build a colony here. It replaces our previously complicated chain of blockplacement/prevention/commandusage with chatlinks. 

Fixes:
- Add colonyview to important players upon login
- Add colonyview upon rank add
- Building blocks now always give feedback why the gui won't open
- Permissionhandler is no longer registered more than once per colony
- Colonyviews now know their owner and no longer just return null
- ChunkCapRange message now also send nearby colonies like ChunkCapSingle messages do

Review please

### CODE REVIEW

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyManage.java  11
- src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyDelete.java  2
- src/main/java/com/minecolonies/coremod/util/ChunkCapData.java  2
- src/main/java/com/minecolonies/coremod/network/messages/ColonyViewRemoveMessage.java  1
- src/main/java/com/minecolonies/coremod/network/messages/UpdateChunkRangeCapabilityMessage.java  1
- src/main/java/com/minecolonies/coremod/event/EventHandler.java  2
- src/main/java/com/minecolonies/coremod/colony/permissions/PermissionsView.java  1
- src/main/java/com/minecolonies/coremod/network/messages/ColonyDeleteOwnMessage.java  3
- src/main/java/com/minecolonies/coremod/network/messages/CreateColonyMessage.java  14
- src/main/java/com/minecolonies/coremod/util/ChunkClientDataHelper.java  5
         

Complexity decreasing per file
==============================
+ src/main/java/com/minecolonies/coremod/network/messages/DirectPlaceMessage.java  -1
+ src/main/java/com/minecolonies/coremod/blocks/huts/BlockHutTownHall.java  -4
         

Clones added
============
- src/main/java/com/minecolonies/coremod/blocks/huts/BlockHutTownHall.java  1
         

Clones removed
==============
+ src/api/java/com/minecolonies/api/blocks/AbstractBlockHut.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5344045&bid=17496065)

File: src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyManage.java [hunk 1]
```diff
@@ -0,0 +1,192 @@
...
+
+        if (findPaneOfTypeByID(TEXT_FEEDBACK, Text.class).getTextContent().isEmpty())
+        {
+            findPaneOfTypeByID(BUTTON_CREATE, ButtonImage.class).enable();
+            findPaneOfTypeByID(TEXT_FEEDBACK, Text.class).setTextContent(LanguageHandler.format("com.minecolonies.coremod.gui.colony.allowed.create"));
+        }
+    }
+
+    @Override
+    public void onButtonClicked(@NotNull final Button button)
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyManage.java]: Why not register them as button handlers?

File: src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyManage.java [hunk 2]
```diff
@@ -0,0 +1,192 @@
...
+
+    /**
+     * Finds the first nearby colony claim in the range
+     *
+     * @param world world to use
+     * @param start start position
+     * @param range search range
+     * @return
+     */
+    private static int findNextNearbyColony(final World world, final BlockPos start, final int range)
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyManage.java:148]: On the client side?

File: src/main/java/com/minecolonies/coremod/colony/Colony.java [hunk 3]
```diff
@@ -295,7 +295,6 @@ protected Colony(final int id, @Nullable final World world)
         this.id = id;
         if (world != null)
         {
-            this.dimensionId = world.getDimension().getType().getId();
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/colony/Colony.java]: don't we need this?

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/Colony.java]: if we don't se it here, in the next call it will always consider it to be 0

File: src/main/java/com/minecolonies/coremod/event/EventHandler.java [hunk 4]
```diff
@@ -785,11 +675,14 @@ public static void onWorldLoad(@NotNull final WorldEvent.Load event)
     @SubscribeEvent
     public static void onWorldUnload(@NotNull final WorldEvent.Unload event)
     {
-        Log.getLogger().warn("World unload");
-
         if (event.getWorld() instanceof World)
         {
             IColonyManager.getInstance().onWorldUnload((World) event.getWorld());
         }
+        if (event.getWorld().isRemote() && event.getWorld().getDimension().getType() == DimensionType.OVERWORLD)
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/event/EventHandler.java:682]: Why only for overworld?

File: src/main/java/com/minecolonies/coremod/event/FMLEventHandler.java [hunk 5]
```diff
@@ -52,10 +52,6 @@ public static void onPlayerLogin(@NotNull final PlayerEvent.PlayerLoggedInEvent
             IColonyManager.getInstance().getIColonyByOwner(((ServerPlayerEntity) event.getPlayer()).getServerWorld(), event.getPlayer());
             //ColonyManager.syncAllColoniesAchievements();
         }
-        else
-        {
-            IColonyManager.getInstance().resetColonyViews();
-        }
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/event/FMLEventHandler.java:58]: I added this for when switching worlds in singlePlayer, don't we need this?

File: src/main/java/com/minecolonies/coremod/network/NetworkChannel.java [hunk 6]
```diff
@@ -93,6 +93,9 @@ public void registerCommonMessages()
         registerMessage(++idx, LumberjackReplantSaplingToggleMessage.class, LumberjackReplantSaplingToggleMessage::new);
         registerMessage(++idx, LumberjackRestrictionToggleMessage.class, LumberjackRestrictionToggleMessage::new);
         registerMessage(++idx, LumberjackScepterMessage.class, LumberjackScepterMessage::new);
+        registerMessage(++idx, CreateColonyMessage.class, CreateColonyMessage::new);
+        registerMessage(++idx, ColonyDeleteOwnMessage.class, ColonyDeleteOwnMessage::new);
+        registerMessage(++idx, ColonyViewRemoveMessage.class, ColonyViewRemoveMessage::new);
```
Comment (Nightenom) [inline src/main/java/com/minecolonies/coremod/network/NetworkChannel.java:98]: This may break universe when previous version connects to this version. Always add new messages to the end of the list, or increase network proto version

File: src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyManage.java (hunk 1 above)
Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyManage.java]: fixed

File: src/main/java/com/minecolonies/coremod/network/NetworkChannel.java (hunk 6 above)
Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/network/NetworkChannel.java:98]: previous version never are allowed to connect to a newer version afaik

File: src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyManage.java (hunk 2 above)
Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyManage.java:148]: ye its for displaying nearby colonies, and the client doesnt have a full list of colonies, but does get claim data

File: src/main/java/com/minecolonies/coremod/event/EventHandler.java (hunk 4 above)
Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/event/EventHandler.java:682]: its for removing the colony views on client side once you leave a world, and thats when the overworld is unloaded

File: src/main/java/com/minecolonies/coremod/event/FMLEventHandler.java (hunk 5 above)
Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/event/FMLEventHandler.java:58]: moved it to world unload instead, to not interfere with us sending views on login

File: src/main/java/com/minecolonies/coremod/network/NetworkChannel.java (hunk 6 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/network/NetworkChannel.java:98]: We add this always next to matching messages and it never was a problem.

File: src/main/java/com/minecolonies/coremod/event/EventHandler.java (hunk 4 above)
Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/event/EventHandler.java:682]: ok

File: src/main/java/com/minecolonies/coremod/network/NetworkChannel.java (hunk 6 above)
Comment (Nightenom) [reply src/main/java/com/minecolonies/coremod/network/NetworkChannel.java:98]: weird, i was able to connect against different version in non dev env while testing some small mods, might be their bug

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/network/messages/UpdateChunkRangeCapabilityMessage.java  1
- src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyDelete.java  2
- src/main/java/com/minecolonies/coremod/colony/permissions/PermissionsView.java  1
- src/main/java/com/minecolonies/coremod/util/ChunkClientDataHelper.java  5
- src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyManage.java  11
- src/main/java/com/minecolonies/coremod/network/messages/ColonyDeleteOwnMessage.java  3
- src/main/java/com/minecolonies/coremod/util/ChunkCapData.java  2
- src/main/java/com/minecolonies/coremod/network/messages/ColonyViewRemoveMessage.java  1
- src/main/java/com/minecolonies/coremod/network/messages/CreateColonyMessage.java  14
- src/main/java/com/minecolonies/coremod/event/EventHandler.java  2
         

Complexity decreasing per file
==============================
+ src/main/java/com/minecolonies/coremod/blocks/huts/BlockHutTownHall.java  -4
+ src/main/java/com/minecolonies/coremod/network/messages/DirectPlaceMessage.java  -1
         

Clones added
============
- src/main/java/com/minecolonies/coremod/blocks/huts/BlockHutTownHall.java  1
         

Clones removed
==============
+ src/api/java/com/minecolonies/api/blocks/AbstractBlockHut.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5344045&bid=17496065)

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/network/messages/ColonyViewRemoveMessage.java  1
- src/main/java/com/minecolonies/coremod/event/EventHandler.java  2
- src/main/java/com/minecolonies/coremod/network/messages/CreateColonyMessage.java  14
- src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyDelete.java  2
- src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyManage.java  11
- src/main/java/com/minecolonies/coremod/util/ChunkClientDataHelper.java  5
- src/main/java/com/minecolonies/coremod/network/messages/UpdateChunkRangeCapabilityMessage.java  1
- src/main/java/com/minecolonies/coremod/network/messages/ColonyDeleteOwnMessage.java  3
- src/main/java/com/minecolonies/coremod/util/ChunkCapData.java  2
- src/main/java/com/minecolonies/coremod/colony/permissions/PermissionsView.java  1
         

Complexity decreasing per file
==============================
+ src/main/java/com/minecolonies/coremod/blocks/huts/BlockHutTownHall.java  -4
+ src/main/java/com/minecolonies/coremod/network/messages/DirectPlaceMessage.java  -1
         

Clones added
============
- src/main/java/com/minecolonies/coremod/blocks/huts/BlockHutTownHall.java  1
         

Clones removed
==============
+ src/api/java/com/minecolonies/api/blocks/AbstractBlockHut.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5344045&bid=17496065)

File: src/api/java/com/minecolonies/api/colony/IColonyTagCapability.java [hunk 7]
```diff
@@ -97,7 +104,7 @@
         /**
          * The set of all close colonies. Only relevant in non dynamic claiming.
          */
-        private final Set<Integer> colonies = new HashSet<>();
+        private Set<Integer> colonies = new HashSet<>();
```
Comment (Asherslab) [inline src/api/java/com/minecolonies/api/colony/IColonyTagCapability.java:107]: Question:
Why remove the final here and make it so that we *set* the colonies (close colonies, should probably rename this field)
I think it'd be better to use an add (to list) method and keep it final. Then you could also add close colonies later on (say a new colony is placed down later) without getting, modifying, and setting, or elsewise

File: src/api/java/com/minecolonies/api/util/constant/GuardConstants.java [hunk 8]
```diff
@@ -110,7 +110,7 @@
     /**
      * Basic bonus hp for knights
      */
-    public static final int KNIGHT_HP_BONUS = 5;
+    public static final int KNIGHT_HP_BONUS = 15;
```
Comment (Asherslab) [inline src/api/java/com/minecolonies/api/util/constant/GuardConstants.java:113]: Why is this changed in this PR?

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingGuardTower.java [hunk 9]
```diff
@@ -67,6 +67,12 @@ public int getClaimRadius(final int newLevel)
         return Math.max(0, newLevel - 1);
     }
 
+    @Override
+    protected int getBonusHealth()
+    {
+        return BONUS_HP_SINGLE_GUARD + getBuildingLevel() * BONUS_HEALTH_PER_LEVEL;
```
Comment (Asherslab) [inline src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingGuardTower.java]: Leave Bonus health private and call `super.getBonusHealth()` here instead

**Review by Asherslab — CHANGES_REQUESTED** [review]

File: src/api/java/com/minecolonies/api/colony/IColonyTagCapability.java (hunk 7 above)
Comment (someaddons) [reply src/api/java/com/minecolonies/api/colony/IColonyTagCapability.java:107]: it is so that we can override the client's chunk data with new data on receiving a message

File: src/api/java/com/minecolonies/api/util/constant/GuardConstants.java (hunk 8 above)
Comment (someaddons) [reply src/api/java/com/minecolonies/api/util/constant/GuardConstants.java:113]: didnt want to make a new PR for two lines :D

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingGuardTower.java (hunk 9 above)
Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingGuardTower.java]: ye

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/event/EventHandler.java  2
- src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyDelete.java  2
- src/main/java/com/minecolonies/coremod/util/ChunkCapData.java  2
- src/main/java/com/minecolonies/coremod/util/ChunkClientDataHelper.java  5
- src/main/java/com/minecolonies/coremod/network/messages/ColonyDeleteOwnMessage.java  3
- src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyManage.java  11
- src/main/java/com/minecolonies/coremod/network/messages/UpdateChunkRangeCapabilityMessage.java  1
- src/main/java/com/minecolonies/coremod/colony/permissions/PermissionsView.java  1
- src/main/java/com/minecolonies/coremod/network/messages/CreateColonyMessage.java  14
- src/main/java/com/minecolonies/coremod/network/messages/ColonyViewRemoveMessage.java  1
         

Complexity decreasing per file
==============================
+ src/main/java/com/minecolonies/coremod/network/messages/DirectPlaceMessage.java  -1
+ src/main/java/com/minecolonies/coremod/blocks/huts/BlockHutTownHall.java  -4
         

Clones added
============
- src/main/java/com/minecolonies/coremod/blocks/huts/BlockHutTownHall.java  1
         

Clones removed
==============
+ src/api/java/com/minecolonies/api/blocks/AbstractBlockHut.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5344045&bid=17496065)

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyDelete.java  2
- src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyManage.java  11
- src/main/java/com/minecolonies/coremod/util/ChunkClientDataHelper.java  5
- src/main/java/com/minecolonies/coremod/network/messages/UpdateChunkRangeCapabilityMessage.java  1
- src/main/java/com/minecolonies/coremod/network/messages/ColonyViewRemoveMessage.java  1
- src/main/java/com/minecolonies/coremod/network/messages/CreateColonyMessage.java  14
- src/main/java/com/minecolonies/coremod/util/ChunkCapData.java  2
- src/main/java/com/minecolonies/coremod/event/EventHandler.java  2
- src/main/java/com/minecolonies/coremod/network/messages/ColonyDeleteOwnMessage.java  3
- src/main/java/com/minecolonies/coremod/colony/permissions/PermissionsView.java  1
         

Complexity decreasing per file
==============================
+ src/main/java/com/minecolonies/coremod/network/messages/DirectPlaceMessage.java  -1
+ src/main/java/com/minecolonies/coremod/blocks/huts/BlockHutTownHall.java  -4
         

Clones added
============
- src/main/java/com/minecolonies/coremod/blocks/huts/BlockHutTownHall.java  1
         

Clones removed
==============
+ src/api/java/com/minecolonies/api/blocks/AbstractBlockHut.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5344045&bid=17496065)

**Comment by marvin-bitterlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/network/messages/CreateColonyMessage.java  14
- src/main/java/com/minecolonies/coremod/util/ChunkCapData.java  2
- src/main/java/com/minecolonies/coremod/network/messages/UpdateChunkRangeCapabilityMessage.java  1
- src/main/java/com/minecolonies/coremod/network/messages/ColonyDeleteOwnMessage.java  3
- src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyManage.java  11
- src/main/java/com/minecolonies/coremod/util/ChunkClientDataHelper.java  5
- src/main/java/com/minecolonies/coremod/event/EventHandler.java  2
- src/main/java/com/minecolonies/coremod/client/gui/WindowTownHallColonyDelete.java  2
- src/main/java/com/minecolonies/coremod/network/messages/ColonyViewRemoveMessage.java  1
- src/main/java/com/minecolonies/coremod/colony/permissions/PermissionsView.java  1
         

Complexity decreasing per file
==============================
+ src/main/java/com/minecolonies/coremod/network/messages/DirectPlaceMessage.java  -1
+ src/main/java/com/minecolonies/coremod/blocks/huts/BlockHutTownHall.java  -4
         

Clones added
============
- src/main/java/com/minecolonies/coremod/blocks/huts/BlockHutTownHall.java  1
         

Clones removed
==============
+ src/api/java/com/minecolonies/api/blocks/AbstractBlockHut.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5344045&bid=17496065)
