### PR TITLE
Fix/building rotation

### LINKED ISSUE #10803: Builders rotate building at 'repair'
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [x] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.1.864-snapshot

### Structurize Version

1.0.768

### Related Mods and their Versions

1. Forge 47.2.0

### Current Behavior

While repairing the orientation of Decorations will be not respected

Image

### Expected Behavior

well, placing the Decoration/building as instructed?

### Reproduction Steps

Place a Decoration.
Have them repair it.

### Logs

-

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by uecasm**
Closes #10803

# Changes proposed in this pull request
- Reverts the "level 0 tags" change from #10804 since it causes weird chunk claims.
- Fixes incorrect building rotation due to duplicate rotation on cached blueprint.

## Testing
- [x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please (should port, with WO refactor)

### CODE REVIEW

File: src/main/java/com/minecolonies/core/entity/ai/workers/util/ConstructionTapeHelper.java [hunk 1]
```diff
@@ -43,13 +46,11 @@ private ConstructionTapeHelper() {}
      */
     public static void placeConstructionTape(@NotNull final IWorkOrder workOrder, @NotNull final Level world, final IColony colony)
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/core/entity/ai/workers/util/ConstructionTapeHelper.java:47]: Can't we do it async?

Comment (uecasm) [reply src/main/java/com/minecolonies/core/entity/ai/workers/util/ConstructionTapeHelper.java:47]: It's already calculated, there's no point calculating it again.  Plus the act of calculating it re-rotated the blueprint, since `loadBlueprint` returns a (possibly cached) pre-rotated copy.

Comment (Raycoms) [reply src/main/java/com/minecolonies/core/entity/ai/workers/util/ConstructionTapeHelper.java:47]: ah, fair

**Review by Raycoms — APPROVED** [review]

File: src/main/java/com/minecolonies/core/entity/ai/workers/util/ConstructionTapeHelper.java (hunk 1 above)
Comment (uecasm) [reply src/main/java/com/minecolonies/core/entity/ai/workers/util/ConstructionTapeHelper.java:47]: It's probably bad coding style that `calculateCorners` (not this one, but the call that was removed) also mutates the blueprint, but that's probably a refactor for another time.  I did at least update the javadoc for it 😆

**Review by someaddons — APPROVED** [review]
