### PR TITLE
Lumberjack improvements/fixes

### LINKED ISSUE #2885: Lumberjack issues
Version: 
minecolonies-1.12.2-0.9.127-ALPHA-universal.jar

### Expected behavior
I expect the Lumberjack to cut down trees

### Actual behaviour
I ran into two odd behaviors.. 

1. We had an insanely massive tree growing a good distance away from the lumberjack but he would always walk towards it even though there were trees which were much closer.  Then about half way he would stop and turn around and walk back to the area near his shack before repeating the same back and forth. 

We cut down the tree and that behavior stopped and then he was able to cut down trees for awhile until..

2. He started to walk amongst the trees but he would never cut anything.  He had the correct axe, a house and food, empty inventory space and no requests.  The trees were growing on a hilly area so I grew some trees on a flat area near his shack and he still wouldn't cut them down.

I ended up just removing him at the end of the day.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/63533266-lumberjack-issues?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #2937: Lumberjack often replants the wrong sapling type
I have two Lumberjacks, one dedicated to Dark Oak and one dedicated to Spruce. For some reason, the Dark Oak lumberjack is replanting Acacia or Oak saplings where the Dark Oak spots were. I don't even think she had Acacia saplings in her inventory so I'm unsure how she got them (she *did* have some before but I took them from her when I specialized them).

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/64389973-lumberjack-often-replants-the-wrong-sapling-type?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #3062: Lumberjack doesn't handle Dynamic trees seeds properly
Versions :
minecolonies-1.12.2-0.10.39-ALPHA-universal.jar
DynamicTrees-1.12.2-0.8.2.jar
DynamicTreesTC-1.12.2-1.1.2.jar

When using this setting in Dynamic Trees config file :

vanilla {
    # Right clicking with a vanilla sapling places a dynamic sapling instead. [default: false]
    B:replaceVanillaSapling=true
}

[16:58:46] [Server thread/ERROR] [minecolonies]: Pausing Entity Kylie E. Gill (com.minecolonies.coremod.job.Lumberjack) at BlockPos{x=3333, y=68, z=4078} for 25600 Seconds because of error:
[16:58:46] [Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:328]: java.lang.ClassCastException: com.ferreusveritas.dynamictrees.items.Seed cannot be cast to net.minecraft.item.ItemBlock

Full log :
[latest.log](https://github.com/ldtteam/minecolonies/files/2573912/latest.log)

### PR DESCRIPTION
**Pull request by someaddons**
**Lumberjack**:
Errors:
- Using oredict sapling when dumping, so nonvanilla saplings are also kept
- Added dynamic tree compat function to compare tree families(variants)
- Fixing error where a check during tree creation fails, but the LC still tried to use that Tree
- Fixing error where the LC kept trying to plant a sapling on an occupied spot
- Fixing error where all slime saplings were correct for any slimetree
- Using oredict to check if a stack is a sapling instead of instanceof, fixes replanting of some BOP trees
- If tree creationg fails it will now set isTree to false

Added:
- Trees now use an IProperty field to set their variant, instead of meta
- Calculating the sapling from a leaf for the tree now checks the Tree's variant to fit(fixes close/combined trees)
- Trees now only add fitting woodtypes as log to be cut, so combined Tree's of different variants are chopped and planted seperatly

Util:
- Added BlockStateUtils for helper functions for using blockstates and their properties
- Logging all exceptions during pathfinding, prev only Runtimeexceptions

Closes #2885
Closes #2937
Closes #3062

Review please

### CODE REVIEW

File: src/api/java/com/minecolonies/api/util/BlockStateUtils.java [hunk 1]
```diff
@@ -0,0 +1,218 @@
...
+import org.jetbrains.annotations.NotNull;
+
+import java.util.Collection;
+import java.util.HashMap;
+import java.util.Map;
+
+/**
+ * Utility class for handling block states and their properties
+ */
+public class BlockStateUtils
```
Comment (Raycoms) [inline src/api/java/com/minecolonies/api/util/BlockStateUtils.java:14]: I like this class, this will be useful in the future as well =)

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingLumberjack.java [hunk 2]
```diff
@@ -99,7 +101,13 @@ public BuildingLumberjack(final Colony c, final BlockPos l)
...
                 final ItemStack stack = getMainCitizen().getInventory().getStackInSlot(i);
 
-                if (ItemStackUtils.isEmpty(stack) || stack.getItem() != SAPLING_STACK.getItem())
+                if (ItemStackUtils.isEmpty(stack))
+                {
+                    continue;
+                }
+
+                // Check if item is sapling by Oredict
+                if (!Arrays.stream(OreDictionary.getOreIDs(stack)).anyMatch(x -> OreDictionary.getOreName(x).equals(SAPLINGS)))
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingLumberjack.java]: Much better.

Comment (Raycoms) [reply src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingLumberjack.java]: can't we call here isStackSapling ?

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java [hunk 3]
```diff
@@ -62,7 +65,7 @@
     /**
      * A lot of luck to get a guaranteed saplings drop.
      */
-    private static final int A_LOT_OF_LUCK = 100;
+    private static final int A_LOT_OF_LUCK = 10000;
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java:69]: That's a ton of luck =P

File: src/api/java/com/minecolonies/api/util/BlockStateUtils.java [hunk 4]
```diff
@@ -0,0 +1,218 @@
...
+    /**
+     * Get the property object of a state matching the given name
+     * Caches lookups in the propertyBlockMap hashmap
+     *
+     * @param state Blockstate we're checking for a property
+     * @param name  name of the property to find
+     */
+    public static IProperty getPropertyByNameFromState(@NotNull final IBlockState state, @NotNull final String name)
+    {
+        IProperty property = propertyBlockMap.get(state.getBlock().getClass().getName() + name);
```
Comment (marchermans) [inline src/api/java/com/minecolonies/api/util/BlockStateUtils.java]: Please use a separator here, between block and name.
Also NEVER EVER use Block.getClass(). Always use the registry name.

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java [hunk 5]
```diff
@@ -478,6 +558,12 @@ private void addAndSearch(@NotNull final World world, @NotNull final BlockPos lo
             return;
         }
 
+        // Check if the new log fits the Tree's base log type
+        if (!BlockStateUtils.stateEqualsStateByBlockAndProp(world.getBlockState(log), world.getBlockState(location), "variant"))
+        {
+            return;
+        }
+
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java:566]: That's a good catch!

File: src/api/java/com/minecolonies/api/util/BlockStateUtils.java [hunk 6]
```diff
@@ -0,0 +1,218 @@
...
+            return property;
+        }
+        else
+        {
+            // Cached map entry nonexistant or wrong, calculate new
+            property = getPropertyByName(state.getPropertyKeys(), name);
+
+            if (property != null)
+            {
+                propertyBlockMap.put(state.getBlock().getClass().getName() + name, property);
```
Comment (marchermans) [inline src/api/java/com/minecolonies/api/util/BlockStateUtils.java]: Again use the blocks registry key and use a separator.

**Comment by Raycoms** [comment]
Looks good for me
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/3059/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

File: src/api/java/com/minecolonies/api/util/BlockStateUtils.java [hunk 7]
```diff
@@ -0,0 +1,218 @@
...
+            {
+                tList.remove(prop);
+                break;
+            }
+        }
+
+        final IProperty[] tempArray = new IProperty[tList.size()];
+        tList.toArray(tempArray);
+
+        IBlockState newState = new BlockStateContainer(state.getBlock(), tempArray).getBaseState();
```
Comment (marchermans) [inline src/api/java/com/minecolonies/api/util/BlockStateUtils.java]: state.getBlock().getDefaultState() is much better.

File: src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingLumberjack.java (hunk 2 above)
Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingLumberjack.java]: oh ye good idea

File: src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java (hunk 3 above)
Comment (someaddons) [reply src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java:69]: the more luck the less rolls trying to get a drop! :D

**Review by marchermans — CHANGES_REQUESTED** [review]

File: src/api/java/com/minecolonies/api/util/BlockStateUtils.java (hunk 7 above)
Comment (someaddons) [reply src/api/java/com/minecolonies/api/util/BlockStateUtils.java]: getDefaultState does contain the properties though, just with the properties default value. Can't remove a property that way

File: src/api/java/com/minecolonies/api/util/BlockStateUtils.java (hunk 4 above)
Comment (someaddons) [reply src/api/java/com/minecolonies/api/util/BlockStateUtils.java]: 👍  thats a better identifier

File: src/api/java/com/minecolonies/api/util/BlockStateUtils.java (hunk 7 above)
Comment (marchermans) [reply src/api/java/com/minecolonies/api/util/BlockStateUtils.java]: The problem is that you have literally no idea what blockstate type you get.
In general on the server you only get BlockStateContainer.

But depending on the Block you can also get Forges ExtendedBlockStateContainer, with its unlisted properties, which you do not even take into account here.

What ever. I am opposed to the way you have done this. But @Raycoms is responsible for that part of the code so if he :shipit: then I am fine with that.

Comment (someaddons) [reply src/api/java/com/minecolonies/api/util/BlockStateUtils.java]: hm you got a valid point there, with other block state types it can't really fulfill its intended functionality. I think I'll just remove it then (not used anywhere anyways)

**Review by marchermans — DISMISSED** [review]

File: src/api/java/com/minecolonies/api/util/BlockStateUtils.java [hunk 8]
```diff
@@ -89,7 +88,7 @@ public static boolean stateEqualsStateInPropertyByName(@NotNull final IBlockStat
      */
     public static IProperty getPropertyByNameFromState(@NotNull final IBlockState state, @NotNull final String name)
     {
-        IProperty property = propertyBlockMap.get(state.getBlock().getClass().getName() + name);
+        IProperty property = propertyBlockMap.get(state.getBlock().getRegistryName() + ":prop:" + name);
```
Comment (marchermans) [inline src/api/java/com/minecolonies/api/util/BlockStateUtils.java]: Why are you inserting prop here?
Just do: Domain:path:property
With Domain:path from the registryname().toString()

**Review by marchermans — CHANGES_REQUESTED** [review]

**Review by marchermans — APPROVED** [review]
