### PR TITLE
more graceful food handling

### LINKED ISSUE #8097: [BUG] Improper buildings listed in the enchanters menu
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

451

### Structurize Version

346

### Related Mods and their Versions

forge: 75
blockui: 44
DO: 39

### Current Behavior

enchanters block lists a lot of buildings with no workers
Townhall
citizen huts
warehouses
tavern

### Expected Behavior

Should show blocks with workers assigned to them

### Reproduction Steps

open enchanters menu

### Logs

n/a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #8097
Closes #
Closes #

This improves the food handling of the cook.

# Changes proposed in this pull request:
- Only requests food if they have less than 6 stacks of the particular type.
- Only request food that has a min nutrition of building level -1 (i.e. citizen tolerate up to getting building level)
- Only displays food in the Ui that follows the same rules

Review please

### CODE REVIEW

**Review by someaddons — DISMISSED** [review]

File: src/api/java/com/minecolonies/api/colony/requestsystem/requestable/Food.java [hunk 1]
```diff
@@ -159,18 +169,21 @@ public static Food deserialize(final IFactoryController controller, final Packet
...
     }
 
     @Override
     public boolean matches(@NotNull final ItemStack stack)
     {
-        return ItemStackUtils.ISFOOD.test(stack) && !exclusionList.contains(new ItemStorage(stack)) && !(ItemStackUtils.ISCOOKABLE.test(stack) && exclusionList.contains(new ItemStorage(MinecoloniesAPIProxy.getInstance().getFurnaceRecipes().getSmeltingResult(stack))));
+        return ItemStackUtils.ISFOOD.test(stack)
+                 && !exclusionList.contains(new ItemStorage(stack))
+                 && !(ItemStackUtils.ISCOOKABLE.test(stack) && exclusionList.contains(new ItemStorage(MinecoloniesAPIProxy.getInstance().getFurnaceRecipes().getSmeltingResult(stack))))
+                 && (ItemStackUtils.ISCOOKABLE.test(stack) || stack.getItem().getFoodProperties() != null && stack.getItem().getFoodProperties().getNutrition() >= minNutrition);
```
Comment (uecasm) [inline src/api/java/com/minecolonies/api/colony/requestsystem/requestable/Food.java]: `ISFOOD` passing guarantees that `getFoodProperties() != null`.
What is the purpose of the `ItemStackUtils.ISCOOKABLE.test(stack) || ` check?  I don't like `&&` and `||` being combined without clarifying parentheses to indicate intended precedence, but also it doesn't seem useful, since the previous checks should have blocked anything that was cookable already.

Comment (uecasm) [reply src/api/java/com/minecolonies/api/colony/requestsystem/requestable/Food.java]: Also, you might want to consider making a static `FoodIngredient` instance for these sorts of checks -- it's already essentially an item predicate that will match only food that has certain min/max property levels.

Comment (Raycoms) [reply src/api/java/com/minecolonies/api/colony/requestsystem/requestable/Food.java]: The purpose is to only deliver food that is either above min or can be cooked (to end up above min)
