### PR TITLE
Fix archers not getting hired from archeries

### LINKED ISSUE #9442: [BUG] Guard tower don't automaticly hire from archery
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.171-Release

### Structurize Version

1.0.648-Beta

### Related Mods and their Versions

_No response_

### Current Behavior

I put both the guard tower and archery on automatic but the guard tower do not hire a archer from the archery

### Expected Behavior

That the guard tower automaticly would hire from the archery.

### Reproduction Steps

I tried it in a clean instance, but down a archery and 4 guard tower, put them all to automatic for archer but the last guard tower to not hire the archer squire

### Logs

https://gist.github.com/Jigewe/1bc6d40d7596041a32a3cdfe975248ca

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Thodor12**
Closes #9442

# Changes proposed in this pull request:
- Fixed faulty ModJobs comparison for archers
- Renamed the ModJobs entries for archers and knights and their training variants so the naming schemes make sense.

[X] Yes I tested this before submitting it.
[ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/api/java/com/minecolonies/api/colony/jobs/ModJobs.java [hunk 1]
```diff
@@ -24,14 +24,14 @@ public final class ModJobs
     public static final ResourceLocation COWBOY_ID         = new ResourceLocation(Constants.MOD_ID, "cowboy");
     public static final ResourceLocation SWINE_HERDER_ID   = new ResourceLocation(Constants.MOD_ID, "swineherder");
     public static final ResourceLocation CHICKEN_HERDER_ID = new ResourceLocation(Constants.MOD_ID, "chickenherder");
-    public static final ResourceLocation SMELTER_ID        = new ResourceLocation(Constants.MOD_ID, "smelter");
-    public static final ResourceLocation RANGER_ID         = new ResourceLocation(Constants.MOD_ID, "ranger");
-    public static final ResourceLocation KNIGHT_ID         = new ResourceLocation(Constants.MOD_ID, "knight");
+    public static final ResourceLocation SMELTER_ID = new ResourceLocation(Constants.MOD_ID, "smelter");
+    public static final ResourceLocation ARCHER_ID  = new ResourceLocation(Constants.MOD_ID, "ranger");
```
Comment (uecasm) [inline src/api/java/com/minecolonies/api/colony/jobs/ModJobs.java:28]: I understand the motivation to rename these, but I think it's more confusing than helpful to have `ARCHER_ID == "ranger"` (but if you changed the latter it would break more things).

Perhaps make this `RANGER_ID` again and use `RANGER_TRAINING_ID` below?

(Though FWIW I think the training ids are based on the building names, not the job names, i.e. they come from "Archery" and "Combat Academy", not "ranger" and "knight".)

Comment (MotionlessTrain) [reply src/api/java/com/minecolonies/api/colony/jobs/ModJobs.java:28]: Maybe a comment with explanation/TODO to change "ranger" as well on the next breaking version could help?

**Review by Raycoms — APPROVED** [review]

File: src/api/java/com/minecolonies/api/colony/jobs/ModJobs.java (hunk 1 above)
Comment (Thodor12) [reply src/api/java/com/minecolonies/api/colony/jobs/ModJobs.java:28]: I have no issue naming it all "ranger", but it would have to be consistent. Also I did, on purpose, not modify the ID itself, only the naming of it because I know that would break all existing entities.

Comment (Thodor12) [reply src/api/java/com/minecolonies/api/colony/jobs/ModJobs.java:28]: The main reason I named it all archer is because they are actually named archers too. So I figured that's easier to remember.

**Review by someaddons — APPROVED** [review]
