### PR TITLE
Average Housing on Happiness Calculation

### LINKED ISSUE #978: Question: Effect of housing on happiness according to the code
### Minecolonies version

Curse 0.7.984

### Expected behavior

Housing has an effect on overall happiness regardless of number of citizens.

### Actual behaviour

First understand that my understanding of the code is a bit basic.  I was looking to try and figure out what affected happiness since my happiness has been stuck at 1 for a long time.

It looks like to me that in https://github.com/Minecolonies/minecolonies/blob/version/1.10/src/main/java/com/minecolonies/coremod/colony/Colony.java, in updateOverallHappiness() starting at line 1189, that the "housing" variable will only ever be set to the building level of the home of the last citizen checked in the loop at line 1194:
        for(final CitizenData citizen: citizens.values())
by line 1212:
                housing = home.getBuildingLevel();

After the end of the loop, average housing is set by line 1218:
        final int averageHousing = housing/ Math.max(1, citizens.size());

All of this means to me that "housing" will never be higher than 5 (the max building level) and as such if you have 5 or more citizens, "averageHousing" will always be <= 1 and will never affect overall happiness because "averageHousing" has to be > 1 to increase overall happiness (starting at line 1220):
        if(averageHousing > 1)
        {
            increaseOverallHappiness(averageHousing * HAPPINESS_FACTOR);
        }

If I'm reading this incorrectly and the code is as it should be, please say so and close this ticket.

Thanks.

### PR DESCRIPTION
**Pull request by WORMSS**
Closes #978 

# Changes proposed in this pull request:
- Corrects calculating the happiness of citizens housing.
-
-

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/colony/Colony.java [hunk 1]
```diff
@@ -1209,7 +1209,7 @@ private void updateOverallHappiness()
             final BuildingHome home = citizen.getHomeBuilding();
             if(home != null)
             {
-                housing = home.getBuildingLevel();
+                housing += home.getBuildingLevel();
```
Comment (xavierh) [inline src/main/java/com/minecolonies/coremod/colony/Colony.java:1212]: Not correct, we need to do that only one per Homes

**Review by xavierh — DISMISSED** [review]
Not correct, we need to do that only once per Homes

File: src/main/java/com/minecolonies/coremod/colony/Colony.java (hunk 1 above)
Comment (WORMSS) [reply src/main/java/com/minecolonies/coremod/colony/Colony.java:1212]: Does the 2nd citizen living in a nice house not count as being happy?

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 55 issues
* ![MAJOR][MAJOR] 13 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 2 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/ebb8cf7bddac2d3e41823694612684554dacd2a1/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.233 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L43](https://github.com/Minecolonies/minecolonies/blob/ebb8cf7bddac2d3e41823694612684554dacd2a1/src/main/java/com/minecolonies/coremod/colony/Colony.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 43 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L43](https://github.com/Minecolonies/minecolonies/blob/ebb8cf7bddac2d3e41823694612684554dacd2a1/src/main/java/com/minecolonies/coremod/colony/Colony.java#L43): class "Colony" has 82 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L43](https://github.com/Minecolonies/minecolonies/blob/ebb8cf7bddac2d3e41823694612684554dacd2a1/src/main/java/com/minecolonies/coremod/colony/Colony.java#L43): Refactor this class so it has no more than 20 fields, rather than the 36 it currently has. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [Colony.java#L641](https://github.com/Minecolonies/minecolonies/blob/ebb8cf7bddac2d3e41823694612684554dacd2a1/src/main/java/com/minecolonies/coremod/colony/Colony.java#L641): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1159](https://github.com/Minecolonies/minecolonies/blob/ebb8cf7bddac2d3e41823694612684554dacd2a1/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1159): Assign this magic number 20 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1160](https://github.com/Minecolonies/minecolonies/blob/ebb8cf7bddac2d3e41823694612684554dacd2a1/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1160): Assign this magic number 60 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1273](https://github.com/Minecolonies/minecolonies/blob/ebb8cf7bddac2d3e41823694612684554dacd2a1/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1273): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1275](https://github.com/Minecolonies/minecolonies/blob/ebb8cf7bddac2d3e41823694612684554dacd2a1/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1275): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1277](https://github.com/Minecolonies/minecolonies/blob/ebb8cf7bddac2d3e41823694612684554dacd2a1/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1277): Assign this magic number 128 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/com/minecolonies/coremod/colony/Colony.java (hunk 1 above)
Comment (xavierh) [reply src/main/java/com/minecolonies/coremod/colony/Colony.java:1212]: If you have 3 Citizens but only 1 Citizens' hut level 2 (with Citizen A and B in it) 
You would have:
Citizen A +2
Citizen B +2
Citizen C +0
housing would be 4 when average >1 (4/3)
when housing should be 2 with average <1 (2/3) as in not very happy

Comment (WORMSS) [reply src/main/java/com/minecolonies/coremod/colony/Colony.java:1212]: So this would turn that into 
```
If you have 3 Citizens but only 1 Citizens' hut level 2 (with Citizen A and B in it)
You would have:
Citizen A +2
Citizen B +0 (Even though he is living in a house of level 2)
Citizen C +0
```

Comment (xavierh) [inline src/main/java/com/minecolonies/coremod/colony/Colony.java]: I would declare a list of house:

Comment (xavierh) [reply src/main/java/com/minecolonies/coremod/colony/Colony.java:1212]: I would declare a list of house:
```
final List<BuildingHome> homes = new ArrayList<>()
```

Then in the loop:
```
if (home !=null && homes.get(home)!=-1)
{
     housing += home.getBuildingLevel();
     homes.add(home);
}
```

Comment (WORMSS) [reply src/main/java/com/minecolonies/coremod/colony/Colony.java:1212]: That doesn't address the fact that a house that has been designed to hold 2 people, will have a maximum happiness of 2.5 at level 5.
Am I missing the reason we don't count the second person?
Otherwise you would always just make 2 houses since that can be 5 + 5.

Comment (xavierh) [reply src/main/java/com/minecolonies/coremod/colony/Colony.java:1212]: The level number for citizen huts is the number of citizen the hut can hold.
In other word, If your colony has more room for citizen than citizen, this will increase the happiness.
@Raycoms Could you comment on this.
I would have assumed that most of the time the number of citizen = the number of "beds" anyway so we would be at 1 most of the time.
Also why does it not decrease happiness when we don't have enough home ?

Comment (WORMSS) [reply src/main/java/com/minecolonies/coremod/colony/Colony.java:1212]: @xavierh ahhh, my understanding of the level system/happiness system is what was in error here..  
I thought: 
```  
1 citizen in level 1 house = 1 happy.. 
1 citizen in level 2 house = 2 happy..
```
Not that that a house of level 2 could hold 2 people.  
That clears up that confusion.  
How do you count extra houses if we are iterating through citizens, but we have more houses than citizens? (Eg, a citizen hasn't spawned yet, or one was killed).
There would potentially have a house that is not counted.

Though, I guess 1 citizen that is surrounded by 5 level 5 houses, would not be all too happy if he was surrounded by the corpses of his dead friends..

But I do agree if there are not enough houses, some type of lowering would happen.

Comment (xavierh) [reply src/main/java/com/minecolonies/coremod/colony/Colony.java:1212]: @WORMSS aggreed in some case, some house would not be counted.
@Raycoms I believe you wrote this, could you comment ?

**Comment by WORMSS** [comment]
@xavierh Updated to only count once

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 55 issues
* ![MAJOR][MAJOR] 13 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 2 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/926442a5100fcdfd16d2eb261fae9ecd0c4a780c/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.235 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L43](https://github.com/Minecolonies/minecolonies/blob/926442a5100fcdfd16d2eb261fae9ecd0c4a780c/src/main/java/com/minecolonies/coremod/colony/Colony.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 43 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L43](https://github.com/Minecolonies/minecolonies/blob/926442a5100fcdfd16d2eb261fae9ecd0c4a780c/src/main/java/com/minecolonies/coremod/colony/Colony.java#L43): class "Colony" has 82 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L43](https://github.com/Minecolonies/minecolonies/blob/926442a5100fcdfd16d2eb261fae9ecd0c4a780c/src/main/java/com/minecolonies/coremod/colony/Colony.java#L43): Refactor this class so it has no more than 20 fields, rather than the 36 it currently has. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [Colony.java#L641](https://github.com/Minecolonies/minecolonies/blob/926442a5100fcdfd16d2eb261fae9ecd0c4a780c/src/main/java/com/minecolonies/coremod/colony/Colony.java#L641): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1159](https://github.com/Minecolonies/minecolonies/blob/926442a5100fcdfd16d2eb261fae9ecd0c4a780c/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1159): Assign this magic number 20 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1160](https://github.com/Minecolonies/minecolonies/blob/926442a5100fcdfd16d2eb261fae9ecd0c4a780c/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1160): Assign this magic number 60 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1275](https://github.com/Minecolonies/minecolonies/blob/926442a5100fcdfd16d2eb261fae9ecd0c4a780c/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1275): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1277](https://github.com/Minecolonies/minecolonies/blob/926442a5100fcdfd16d2eb261fae9ecd0c4a780c/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1277): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1279](https://github.com/Minecolonies/minecolonies/blob/926442a5100fcdfd16d2eb261fae9ecd0c4a780c/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1279): Assign this magic number 128 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Raycoms** [comment]
I don't get what the problem with the current housing calculation is.
can you explain that to us?

**Comment by WORMSS** [comment]
@Raycoms https://github.com/Minecolonies/minecolonies/issues/978#issue-228180258

**Comment by Raycoms** [comment]
Hmm that doesn't seem like a good fix. I actually forgot the "+=" but now it seems a bit too op to count if for each citizen.

We don't need a list for that.

I think a real fix would be removing that calculation from the citizen loop and add a new loop iterating through all the buildings and checking if its a home and then doing the average of that.

**Comment by WORMSS** [comment]
I modified so we loop through each user. If he has a home, check if the home has been counted, if it has, skip, otherwise add the house and increment the value.

**Comment by Raycoms** [comment]
Yeah I understood that. Hmm still have to think about that, I don't really
like to store them in a list very much. I will think about it

2017-05-12 11:22 GMT-03:00 WORMSS <notifications@github.com>:

**Comment by Raycoms** [comment]
I was talking with xavier about that and noticed. If we make it your way it will only check for the general housing slots. So If all have housing = 1, else < 1 so it may only decrease and increase slightly.
The idea I had was to let it depend on the housing level.
So if every citizen lives in a lvl 5 house, the average will be 5.
So that 1 housing level 2 is better than 2 housing level 1.

Only think that needs to be fixed is the missing "+=" here.

File: src/main/java/com/minecolonies/coremod/colony/Colony.java (hunk 1 above)
Comment (xavierh) [reply src/main/java/com/minecolonies/coremod/colony/Colony.java:1212]: @WORMSS you were correct from the start:
Just do the +=

**Comment by WORMSS** [comment]
@Raycoms that was my first commit.. I was asked to change. 

https://github.com/Minecolonies/minecolonies/pull/981/commits/ebb8cf7bddac2d3e41823694612684554dacd2a1

**Comment by Raycoms** [comment]
Ahh yeah that sucks. But thanks for that find. I didn't see that I forgot that "+=" . Probably will help a lot of players when we get that straightened up. Could you just reset your pr to that commit so we can merge it?

**Comment by xavierh** [comment]
Sorry, my fault

**Comment by WORMSS** [comment]
Done

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/981/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by marvin-bitterlich** [comment]
:shipit:

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/981/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)
