### PR TITLE
Fix/111129

### LINKED ISSUE #11129: Canceling a schematic doesn't work properly
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

minecolonies-1.20.1-1.1.1018-snapshot

### Structurize Version

structurize-1.20.1-1.0.781-snapshot

### Related Mods and their Versions

_No response_

### Current Behavior

After canceling a request of a build in progress. It is removed from the work order. And the builder will "move on" to a new work order; however, they will still request items from the old work order. And will continue building the old work order. Rather than actually moving onto the work order they say they are on.

I've only tested on two different decoration controllers, have not tried it with huts.

https://github.com/user-attachments/assets/5b2b104d-1882-43a8-8944-d3376a5fa8f2

Image

### Expected Behavior

Expected to cancel properly like before

### Reproduction Steps

Buil

### Logs

https://gist.github.com/Jinotad/ee82550814a993154ab120354c147ab0

### Anything else?

Build a builders hut. 
Assign a decoration to be constructed to the builder, provide needed resources.
Assign a 2nd decoration to be constructed, then cancel the first one.
Observer builder's behavior.

### Footer

---
 ## Viewers
  *  Add a 👍 reaction to the bug report if you are also affected. This helps the bug report become more visible without cluttering the comments.
  *  ⚠️ Only add a comment if you have new insights or background information not already mentioned. Off-topic or "+1" comments will be deleted to keep the discussion focused.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #11129 
Closes #

# Changes proposed in this pull request
- Fix workorder cancellation
-

## Testing
- [x] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/api/colony/buildings/IBuilding.java [hunk 1]
```diff
@@ -319,7 +319,12 @@ <R> ImmutableList<IRequest<? extends R>> getOpenRequestsOfType(
 
     boolean hasCitizenCompletedRequestsToPickup(@NotNull ICitizenData data);
 
-    Collection<IRequest<?>> getCompletedRequests(@NotNull ICitizenData data);
+    /**
+     * Get completed requests for citizen or building (citizen independent, so if data is null)
+     * @param data the citizen data (or null).
+     * @return a collection of request.
+     */
+    Collection<IRequest<?>> getCompletedRequestsOrCitizenOrBuilding(@Nullable ICitizenData data);
```
Comment (MotionlessTrain) [inline src/main/java/com/minecolonies/api/colony/buildings/IBuilding.java]:
```suggestion
    Collection<IRequest<?>> getCompletedRequestsOfCitizenOrBuilding(@Nullable ICitizenData data);
```

This looks like a typo

**Comment by MotionlessTrain** [comment]
Ehm, I meant it needed to be updated on the other places too. I just didn't suggest all of those changes

**Review by MotionlessTrain — APPROVED** [review]

**Review by someaddons — APPROVED** [review]
