### PR TITLE
Hotfix/server building

### LINKED ISSUE #2396: Building switch style Client Crash
### Minecolonies version

minecolonies-universal-1.12.2-0.8.7972.jar

### Expected behavior

- When switching a Building style with a custom style, it doesn't crash

### Actual behaviour

- When switching a building style with a custom style (on a server) the client crashes with the following log: https://gist.github.com/Asherslab/25e4252f4670eeb25b60ab792f742b43
As far as we are aware, the custom style pack works perfectly using the Build Tool.
Also, we tried both with and without the stylepack installed on the client. both had the same crash.

### Steps to reproduce the problem

1. Install a custom style pack under `{server}/{world}/minecolonies/schematics`
2. boot up and try to switch an existing building's style to the new custom pack.
3. client crashes.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #2396

# Changes proposed in this pull request:
- Fixes style switch by downloading the schematic if required.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java [hunk 1]
```diff
@@ -185,6 +189,31 @@ private void updateResources()
...
+            }
+            else
+            {
+                Log.getLogger().error("WindowBuildTool: Need to download schematic on a standalone client/server. This should never happen");
+            }
+        }
+
         wrapper.setPosition(building.getLocation());
         wrapper.rotate(building.getRotation(), world, building.getLocation(), building.isMirrored() ? Mirror.FRONT_BACK : Mirror.NONE);
         while (wrapper.findNextBlock())
```
Comment (BuildTeamLinter) [inline src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java:219]: MAJOR Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS135)

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 52 issues
* ![MAJOR][MAJOR] 52 major

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/da9520904dad109a7425a74a3ad669807add7573/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/da9520904dad109a7425a74a3ad669807add7573/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L182](https://github.com/Minecolonies/minecolonies/blob/da9520904dad109a7425a74a3ad669807add7573/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L182): The Cyclomatic Complexity of this method "updateResources" is 26 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L182](https://github.com/Minecolonies/minecolonies/blob/da9520904dad109a7425a74a3ad669807add7573/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L182): Refactor this method to reduce its Cognitive Complexity from 43 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [WindowBuildBuilding.java#L336](https://github.com/Minecolonies/minecolonies/blob/da9520904dad109a7425a74a3ad669807add7573/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildBuilding.java#L336): Remove this unused method parameter "list". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/da9520904dad109a7425a74a3ad669807add7573/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/da9520904dad109a7425a74a3ad669807add7573/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [permissions#](https://github.com/Minecolonies/minecolonies/blob/da9520904dad109a7425a74a3ad669807add7573/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [requestable#](https://github.com/Minecolonies/minecolonies/blob/da9520904dad109a7425a74a3ad669807add7573/src/main/java/com/minecolonies/coremod/colony/requestable#): Add a 'package-info.java' file to document the 'requestable' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [data#](https://github.com/Minecolonies/minecolonies/blob/da9520904dad109a7425a74a3ad669807add7573/src/main/java/com/minecolonies/coremod/colony/requestsystem/data#): Add a 'package-info.java' file to document the 'data' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Review by Asherslab — APPROVED** [review]
Looks good!
