### PR TITLE
Many fixes

### LINKED ISSUE #8496: can't assign worker after moving hutblock
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

867A

### Structurize Version

408A

### Related Mods and their Versions

_No response_

### Current Behavior

can't assign builder to builder hut after moving it, it is not available until after a server reboot.

### Expected Behavior

place down builder hut then add a worker

### Reproduction Steps

disassemble builder hut
pick it up
place it down

### Logs

https://gist.github.com/SivartMcDorf/3f2eccd404fc9d4a1045511f0307b71b

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #8504: Citizen automatically assigned to manual-mode housing they were just evicted from
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.872-BETA

### Structurize Version

1.0.411-ALPHA

### Related Mods and their Versions

Forge version: 40.1.54
Block UI Version: 0.0.53-ALPHA
DO Version: 1.0.54-ALPHA

### Current Behavior

I had two citizens (kids are off) and two houses, one level 1 and one level 2.  One citizen lived in each house; I wanted to move the one in the level 1 house to the level 2 one, even though the level 2 one was farther from their workplace.

The colony default housing mode was automatic.  Turning the level 1 house to manual and unassigning the citizen showed them as homeless, but shortly later they were re-assigned to the level 1 house even though the house was still on manual.  I repeated this both during the day and at night, with similar results.

Setting the level 2 house to manual and pulling the citizen from there worked.

### Expected Behavior

When a house is on manual mode, and I un-assign a citizen, they should *stay* unassigned from that house at least until I turn the house back to automatic, even if it’s the closest house to the workplace.

### Reproduction Steps

I have not reproduced this; if setting up the described situation does not allow a reproduction I probably can’t help.  I’ve already fixed this and forgot to make a backup first.

### Logs

Nothing except `[CHAT] All colonists are tucked into bed.` and some log spam whenever chunks are saved

### Anything else?

I fraudulently checked the checkbox above because otherwise I could not submit the form.  I’m on the latest beta, and none of the commits since then look relevant.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #8517: Fix Grave Size
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-1.0.862-ALPHA

### Structurize Version

1.18.1-1.0.408-ALPHA

### Related Mods and their Versions

no important relations

### Current Behavior

On death, citizens get a grave with the size of a chest

### Expected Behavior

On death, citizens should get a grave with the size of their inventory. This can change with research, so currently, everything greater than a chest from the citizens inventory disappears...

### Reproduction Steps

1. Research greater inventory for citizens
2. Fill citizen inventory
3. kill citizen, only grave with 3 Rows are preserved instead of full inventory

### Logs

-

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #8521: Inventory (hut/block inventory, using the button marked "Inventory") isn't seen in their overall hut inventory.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.893-ALPHA

### Structurize Version

structurize-1.18.2-1.0.411-ALPHA

### Related Mods and their Versions

Launching pack All the Mods 7 - ATM7 - 1.18.2 0.4.22 for Minecraft 1.18.2
[25/07/2022 19:45:36 PM] Logging into Minecraft!
[25/07/2022 19:45:36 PM] Access Token has expired. Attempting to refresh it.
[25/07/2022 19:45:36 PM] Oauth token expired. Attempting to refresh
[25/07/2022 19:45:37 PM] xsts auth expired. Attempting to get new auth
[25/07/2022 19:45:39 PM] Loader: Forge 40.1.60

### Current Behavior

When I add an item that has been requested, viewable on the clipboard, to the Inventory button of the hut block... they do not see the item until I use the sort command.  

### Expected Behavior

The inventory buttons inventory should be included in the overall block inventory

### Reproduction Steps

See current behavior

### Logs

https://gist.github.com/crysallis/5e0ffeb15797a3887643eb49b6cccba9

### Anything else?

I have a video example of this here
https://imgur.com/a/mOyiyv0

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #8541: Crafters wandering off after crafting
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.893

### Structurize Version

1.18.2-1.0.411

### Related Mods and their Versions

_No response_

### Current Behavior

After crafting, crafters seem to wander off some distance before running back and drop items into storage.
Then some couriers with decent level that came too fast tried to pick up those items from empty hut inventory, ended up failing the request.
And so workers send a request of the same items again, thus causing crafters to make extra items.
Those extras will stay in crafters' hut storage until next time the same item request failed.

### Expected Behavior

1. Crafters should not wander off distance before putting items into hut storage. 
2. Couriers should come and try to pick up items after those items are actually put into hut inventory.
3. Colonists should be able to locate requested items in other colonists own inventory.

Crafters could craft and put items directly in hut inventory, not in their own inventory. might be a way to fix this?

### Reproduction Steps

1. Request some items.
2-1. Use mobs or players to block crafters after they finished crafting before they put those items into hut inventory.
2-2 Sometimes it happens naturally without any interruption.

### Logs

https://gist.github.com/ethansyy/3be3a2e38e52cef05050e8cdf09f1ba7

### Anything else?

I drop the needed items on the floor, and bump into the workers, 
if they pick up those items during the pause, after the pause they sometimes don't recognize that they have the items in their inventory, and thus keep requesting same items from player.

I think this also has the same issue with the colonists' pauses.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #8545: [BUG] Racks frequently built invisible
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.912-ALPHA

### Structurize Version

1.19.1-1.0.423-ALPHA

### Related Mods and their Versions

Forge: 42.0.1
DO, BlockUI, and MultiPiston are irrelevant

### Current Behavior

Racks often place invisibly.  This is often reported on the Discord and I have seen it in warehouses multiple times, but below is the easiest reproduction

### Expected Behavior

All racks are visible

### Reproduction Steps

1. Get a supply camp deployer
2. Observe the preview of the Stone supply camp: it has the double racks in the wrong location
3. Place the Stone supply camp at UP or RIGHT rotation (as seen in the current build tool; no clue what that means after the update)
4. Observe that it figures out how the double racks work, and shows both of them correctly
5. Place the Stone supply camp in the DOWN rotation
7. Observe the two sets of double racks each look like one empty single rack and one air block
8. Place the Stone supply camp in the LEFT rotation
9. Observe that one rack is correct and one is broken

### Logs

N/A

### Anything else?

1. As you can see from my MineColonies version, I am not on 1.18; Iʼm on 1.19.  That is not an option when filing an issue.

2. This issue has been seen in *many* schematics by *many* people on the Discord.  If the fix looks like something specific to the Stone supply camp, it is not a fix for the entire issue.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #8541
Closes #8521
Closes #8517
Closes #8545
Closes #8496 
Closes #8504

# Changes proposed in this pull request:
- I don't know why that  was changed, but the crafters should only mark the request complete after dump.
- Warehouse block should also detect changes.
- Increase grave sizes to the max that allows fitting bigger citizen inventories in
- Solve an issue with amazon air sniping.
- Remove double deserialization/serialization handling with graves
- Improve rack pasting again
- Fix citizens auto assigning to cit huts
- Fix assignment to moved builder

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/placementhandlers/RackPlacementHandler.java [hunk 1]
```diff
@@ -50,14 +50,18 @@ public ActionProcessingResult handle(
...
-        BlockEntity entity = world.getBlockEntity(pos);
-
         world.setBlock(pos, blockState, UPDATE_FLAG);
         if (tileEntityData != null)
         {
             handleTileEntityPlacement(tileEntityData, world, pos, settings);
         }
 
+        final BlockEntity entity  = world.getBlockEntity(pos);
+        if (entity instanceof TileEntityRack && !((TileEntityRack) entity).isSingle() && ((TileEntityRack) entity).getOtherChest() != null)
```
Comment (uecasm) [inline src/main/java/com/minecolonies/coremod/placementhandlers/RackPlacementHandler.java:60]: It might be a good idea to update the block state even if the other chest is null.  The other rack in the pair may not be placed yet, or it may have been placed at different coordinates (rotation does not update the other-chest position).

In theory we should want all racks to revert to single when the first one is placed, and then update back to double when the second one is.

File: src/main/java/com/minecolonies/coremod/entity/mobs/aitasks/RaiderRangedAI.java [hunk 2]
```diff
@@ -100,7 +100,7 @@ protected void doAttack(final LivingEntity target)
         AbstractArrow arrowEntity = CombatUtils.createArrowForShooter(user);
 
         arrowEntity.setBaseDamage(user.getAttribute(MOB_ATTACK_DAMAGE).getValue());
-        if (flightCounter > 5)
+        if (flightCounter > 5 && arrowEntity instanceof CustomArrowEntity)
         {
             ((CustomArrowEntity) arrowEntity).setPlayerArmorPierce();
```
Comment (uecasm) [inline src/main/java/com/minecolonies/coremod/entity/mobs/aitasks/RaiderRangedAI.java:105]: Can start using named casts instead of separate `instanceof` and cast, unless you're planning to backport this to 1.16...

**Comment by Raycoms** [comment]
I did that on purpose because else this can result in double or wrong connections, just want to update when the second is finished

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by uecasm** [comment]
> just want to update when the second is finished

I still think that's going to break by rotation.

**Comment by Raycoms** [comment]
> > just want to update when the second is finished
> 
> I still think that's going to break by rotation.

they know the relative rotation

**Review by someaddons — DISMISSED** [review]
