### PR TITLE
Serveral fixes

### LINKED ISSUE #5848: What's supposed to happen after the end?
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

Return home to continue ulgrading my town as normal, just with new mats :)

## Actual behavior

Online server, friend and i ran to the end, killed the dragon, farmed a city.  Then we got the "block is missing building" message on every root block in town and town hall says colony 1/2 is to close to claim a new colony there.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: there was no crash, and no errors in the server to upload. Its like the game thinks this is normal.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #5901: 1.15.2 Guards "jiggling" when guarding
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.328
- Structurize Version: 0.13.94

## Expected behavior

Guard stands in location normally.

## Actual behavior

Guards "jiggle/turn" back and forth violently when assigned to guard a location.

Zip file includes .flv recording of glitch.
[Guard Jiggle.zip](https://github.com/ldtteam/minecolonies/files/5358155/Guard.Jiggle.zip)

## Steps to reproduce the issue

Assign a guard to guard a location/block.

### Logs

- latest.log: https://gist.github.com/Borkius/7227b2e89821850fcb343a4adf98c4a2

### Notes

Using Craft to Exile (Dissonance) modpack, just to explain all the other mods in the log.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #5929: Citizens stay at home
Minecraft: 1.15.2
Minecolonies: 0.13.349 alpha
Structurize: 0.13.94 alpha

Problem:
My citizens stay at home in the morning. They only go to work, if I'm near their houses (<15 Blocks).  
Their houses are level 1 spruce medieval citizen houses ( no changes).
I do not sleep at night. At daytime 00:00 I have to go to their houses. Else they will stay at home.
My citizens are not stuck. As soon as I'm near their houses (any daytime) they come out and do their duty. 
(Sorry for my english.)

### PR DESCRIPTION
**Pull request by someaddons**
Closes #5901
Closes #5929
Closes #5848

# Changes proposed in this pull request:
Adds Custom arrows for our entities, which do not scale in damage with movement and despawn quickly after beeing on the ground for a bit, avoiding fps lag from large battles with thousands of arrows.

Some raid balancing:
Raiders now have less armor and scale less in health
Colonies raidlevel grows more linearly than before and is a bit lower.
When less than 5% of raiders remain the raids now automatically end.

Fixes:
Training archers no longer deal damage when shooting
ToggleAI no longer toggles single blocks on doors and instead uses the doors own toggle functionality
Raiders no longer accidentally toggle doors
Fix guarding guards "Jiggling" because they didnt fix up their starting position for pathing
Fix pathing starting positions, now it checks for an existing collision box and if the citizen is actually within it so that e.g. standing next to a Trapdoor no longer assumes a pathing node above the trapdoor. Before it used entity positions which can vary too much, and caused some cases where citizens get stuck.
Fix players not always beeing added to the colony view subs after dim changes, they now check if they're added each time they enter a chunk claimed by a colony making it more resistant.

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/coremod/entity/CustomArrowEntity.java [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+        // Set the old actual damage value back
+        setDamage(prevDamage);
+    }
+
+    @Override
+    public void tick()
+    {
+        super.tick();
+
+        if (this.timeInGround > 10)
```
Comment (Raycoms) [inline src/main/java/com/minecolonies/coremod/entity/CustomArrowEntity.java]: maybe a constant?

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/5928/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Review by Mekle001 — APPROVED** [review]
